scylladb/scylladb

locator/gossiping_property_file_snitch.cc, locator/gossiping_property_file_snitch.hh, message/messaging_service.cc, service/storage_service.cc
Despite docs discourage from using INADDR_ANY as listen address, this is not disabled in code. Worse -- some snitch drivers may gossip it around as the INTERNAL_IP state. This set prevents this from happening and also adds a sanity check not to use this value if it somehow sneaks in.
=> Avoid 0.0.0.0 (and :0) as preferred IP

locator/token_metadata.cc, locator/token_metadata.hh, message/messaging_service.cc, message/messaging_service.hh, service/storage_service.cc, test/pylib/rest_client.py, test/pylib/util.py, test/topology/test_topology.py
`get_rpc_client` calculates a `topology_ignored` field when creating a
client which says whether the client's endpoint had topology information
when this client was created. This is later used to check if that client
needs to be dropped and replaced with a new client which uses the
correct topology information.
The `topology_ignored` field was incorrectly calculated as `true` for
pending endpoints even though we had topology information for them. This
would lead to unnecessary drops of RPC clients later. Fix this.
Remove the default parameter for `with_pending` from
`topology::has_endpoint` to avoid similar bugs in the future.
Apparently this fixes #11780. The verbs used by decommission operation
use RPC client index 1 (see `do_get_rpc_client_idx` in
message/messaging_service.cc). From …
=> message: messaging_service: fix topology_ignored for pending endpoints in get_rpc_client

db/view/view.cc, locator/abstract_replication_strategy.cc, locator/abstract_replication_strategy.hh, locator/token_metadata.hh, repair/repair.cc, repair/repair.hh, repair/row_level.hh
As described in #11993 per-shard repair_info instances get the effective_replication_map on their own with no centralized synchronization.
This series ensures that the effective replication maps used by repair (and other associated structures like the token metadata and topology) are all in sync with the one used to initiate the repair operation.
While at at, the series includes other cleanups in this area in repair and view that are not fixes as the calls happen in synchronous functions that do not yield.
Fixes #11993
=> repair: harden effective replication map

message/messaging_service.cc
The gossip verbs are used to learn about topology of other nodes. If inter-dc/rack encryption is enabled, the knowledge of topology is necessary to decide whether it's safe to send unencrypted messages to nodes (i.e., whether the destination lies in the same dc/rack).
The logic in `messaging_service::get_rpc_client`, which decided whether a connection must be encrypted, was this (given that encryption is enabled): if the topology of the peer is known, and the peer is in the same dc/rack, don't encrypt. Otherwise encrypt.
However, it may happen that node A knows node B's topology, but B doesn't know A's topology. A deduces that B is in the same DC and rack and tries sending B an unencrypted message. As the code currently stands, this would cause B to call `on_internal_error`. This is what …
=> message: messaging_service: topology independent connection settings for GOSSIP verbs

db/system_keyspace.cc, gms/application_state.cc, gms/application_state.hh, gms/versioned_value.hh, raft/raft.hh, raft/server.cc, raft/server.hh, service/raft/raft_group0.cc, service/raft/raft_group0.hh, service/raft/raft_rpc.cc, service/raft/raft_rpc.hh, service/storage_service.cc, test/raft/randomized_nemesis_test.cc, test/raft/replication.hh, test/raft/replication_test.cc
We plan to stop storing IP addresses in Raft configuration, and instead use the information disseminated through gossip to locate Raft peers. Implement patches that are building up to that:
* improve Raft API of configuration change notifications
* disseminate raft host id in Gossip
* avoid using Raft addresses from Raft configuraiton, and instead consistently use the translation layer between raft server id <-> IP address
=> Build up to support of dynamic IP address changes in Raft

db/hints/manager.cc, db/hints/resource_manager.cc, replica/database.cc, replica/distributed_loader.cc, replica/table.cc, sstables/sstable_directory.cc, test/boost/database_test.cc, test/boost/lister_test.cc, test/boost/sstable_directory_test.cc, utils/lister.cc, utils/lister.hh
The lister accepts sort of a filter -- what kind of entries to list, regular, directories or both. It currently uses unordered_set, but enum_set is shorter and better describes the intent.
=> Make use of enum_set in directory lister

cql3/selection/selection.cc, test/boost/restrictions_test.cc, test/cql-pytest/test_scan.py
When filtering with multi column restriction present all other restrictions were ignored.
So a query like:
`SELECT * FROM WHERE pk = 0 AND (ck1, ck2) < (0, 0) AND regular_col = 0 ALLOW FILTERING;`
would ignore the restriction `regular_col = 0`.
This was caused by a bug in the filtering code:
https://github.com/scylladb/scylladb/blob/2779a171fc85de29db066a6fdb07cc4a3fbed120/cql3/selection/selection.cc#L433-L449
When multi column restrictions were detected, the code checked if they are satisfied and returned immediately.
This is fixed by returning only when these restrictions are not satisfied. When they are satisfied the other restrictions are checked as well to ensure all of them are satisfied.
This code was introduced back in 2019, when fixing #3574.
Perhaps back then it was impossible …
=> cql3: don't ignore other restrictions when a multi column restriction is present during filtering

alternator/executor.cc, alternator/serialization.cc, compaction/compaction.cc, mutation_compactor.hh, mutation_fragment.hh, mutation_fragment_stream_validator.hh, position_in_partition.hh, querier.hh, query-result-reader.hh, readers/mutation_reader.cc, readers/mutation_readers.cc, service/pager/query_pagers.cc, sstables/kl/reader.cc, sstables/mx/reader.cc, sstables/writer.cc, test/boost/mutation_query_test.cc, test/boost/mutation_test.cc, test/boost/secondary_index_test.cc, test/lib/mutation_assertions.hh, test/lib/mutation_source_test.cc
Fragment reordering and fragment dropping bugs have been plaguing us since forever. To fight them we added a validator to the sstable write path to prevent really messed up sstables from being written.
This series adds validation to the mutation compactor. This will cover reads and compaction among others, hopefully ridding us of such bugs on the read path too.
This series fixes some benign looking issues found by unit tests after the validator was added -- although how benign a producer emitting two partition-ends depends entirely on how the consumer reacts to it, so no such bug is actually benign.
Fixes: https://github.com/scylladb/scylladb/issues/11174
=> Add validator to the mutation compactor

docs/architecture/raft.rst, docs/operating-scylla/procedures/cluster-management/index.rst, docs/upgrade/upgrade-opensource/index.rst, docs/upgrade/upgrade-opensource/upgrade-guide-from-5.1-to-5.2/index.rst, docs/upgrade/upgrade-opensource/upgrade-guide-from-5.1-to-5.2/metric-update-5.1-to-5.2.rst, docs/upgrade/upgrade-opensource/upgrade-guide-from-5.1-to-5.2/upgrade-guide-from-5.1-to-5.2-generic.rst
Add new guide for upgrading 5.1 to 5.2.
In this new upgrade doc, include additional steps for enabling
Raft using the `consistent_cluster_management` flag. Note that we don't
have this flag yet but it's planned to replace the experimental flag in
5.2.
In the "Raft in ScyllaDB" document, add sections about:
- enabling Raft in existing clusters in Scylla 5.2,
- verifying that the internal Raft upgrade procedure finishes
successfully,
- recovering from a stuck Raft upgrade procedure or from a majority loss
situation.
Fix some problems in the documentation, e.g. it is not possible to
enable Raft in an existing cluster in 5.0, but the documentation claimed
that it is.
Follow-up items:
- if we decide for a different name for `consistent_cluster_management`,
use that name in the docs instead
- …
=> docs: describe the Raft upgrade and recovery procedures

cql3/expr/prepare_expr.cc, test/boost/expr_test.cc, test/lib/expr_test_utils.cc, test/lib/expr_test_utils.hh
Adds unit tests for the function `expr::prepare_expression`.
Three minor bugs were found by these tests, both fixed in this PR.
1. When preparing a map, the type for tuple constructor was taken from an unprepared tuple, which has `nullptr` as its type.
2. Preparing an empty nonfrozen list or set resulted in `null`, but preparing a map didn't. Fixed this inconsistency.
3. Preparing a `bind_variable` with `nullptr` receiver was allowed. The `bind_variable` ended up with a `nullptr` type, which is incorrect. Changed it to throw an exception,
=> cql3: expr: add unit tests for prepare_expression

reader_concurrency_semaphore.cc, reader_concurrency_semaphore.hh
We recently (in 7fbad8de875816f0fb71ffa1965ba65543354629) made sure all admission paths can trigger the eviction of inactive reads. As reader eviction happens in the background, a mechanism was added to make sure only a single eviction fiber was running at any given time. This mechanism however had a preemption point between stopping the fiber and releasing the evict lock. This gave an opportunity for either new waiters or inactive readers to be added, without the fiber acting on it. Since it still held onto the lock, it also prevented from other eviction fibers to start. This could create a situation where the semaphore could admit new reads by evicting inactive ones, but it still has waiters. Since an empty waitlist is also an admission criteria, once one waiter is wrongly added, many …
=> reader_concurrency_semaphore: fix waiter/inactive race

tools/scylla-sstable.cc
This series contains a mixed bag of improvements to  `scylla sstable dump-data`. These improvements are mostly aimed at making the json output clearer, getting rid of any ambiguities.
=> scylla-sstable: data-dump improvements

service/storage_proxy.cc, service/storage_proxy.hh
When processing a query, we keep a pointer to an effective_replication_map.
In a couple places we used the latest topology instead of the one held by the effective_replication_map
that the query uses and that might lead to inconsistencies if, for example, a node is removed from topology after decommission that happens concurrently to the query.
This change gets the topology& from the e_r_m in those cases.
Fixes #12050
=> storage_proxy: use erm topology

docs/_utils/redirects.yaml
This is a backport of https://github.com/scylladb/scylladb/pull/11154.
=> [branch 5.1 backport] doc: remove the Operator documentation pages from the core ScyllaDB docs

docs/alternator/compatibility.md
Currently, TTL is listed as one of the experimental features: https://docs.scylladb.com/stable/alternator/compatibility.html#experimental-api-features
This PR moves the feature description from the Experimental Features section to a separate section.
I've also added some links and improved the formatting.
@tzach I've relied on your release notes for RC1.
Refs: https://github.com/scylladb/scylladb/issues/5060
=> doc: document the Alternator TTL feature as GA

cql3/restrictions/statement_restrictions.cc, cql3/restrictions/statement_restrictions.hh, cql3/statements/batch_statement.cc, cql3/statements/modification_statement.cc, cql3/statements/modification_statement.hh, test/cql-pytest/test_null.py
[PR](https://github.com/scylladb/scylladb/pull/9314) fixed a similar issue with regular insert statements
but missed the LWT code path.
It's expected behaviour of
`modification_statement::create_clustering_ranges` to return an
empty range in this case, since `possible_lhs_values` it
uses explicitly returns `empty_value_set` if it evaluates `rhs`
to null, and it has a comment about it (All NULL
comparisons fail; no column values match.) On the other hand,
all components of the primary key are required to be set,
this is checked at the prepare phase, in
`modification_statement::process_where_clause`. So the only
problem was `modification_statement::execute_with_condition`
was not expecting an empty `clustering_range` in case of
a null clustering key.
Also this patch contains a fix for the …
=> Fix LWT insert crash if clustering key is null

docs/cql/ddl.rst
Release 5.1. introduced a new CQL extension that applies to the CREATE TABLE and ALTER TABLE statements. The ScyllaDB-specific extensions are described on a separate page, so the CREATE TABLE and ALTER TABLE should include links to that page and section.
Note: CQL extensions are described with Markdown, while the Data Definition page is RST. Currently, there's no way to link from an RST page to an MD subsection (using a section heading or anchor), so a URL is used as a temporary solution.
Related: https://github.com/scylladb/scylladb/pull/9810
=> doc: add the links to the per-partition rate limit extension 

cql3/expr/expression.cc, test/boost/expr_test.cc, test/cql-pytest/cassandra_tests/validation/entities/collections_test.py, test/cql-pytest/cassandra_tests/validation/operations/select_single_column_relation_test.py, test/cql-pytest/cassandra_tests/validation/operations/select_test.py, test/cql-pytest/test_scan.py
As a part of CQL rewrite we want to be able to perform filtering by calling `evaluate()` on an expression and checking if it evaluates to `true`. Currently trying to do that for a binary operator would result in an error.
Right now checking if a binary operation like `col1 = 123` is true is done using `is_satisfied_by`, which is able to check if a binary operation evaluates to true for a small set of predefined cases.
Eventually once the grammar is relaxed we will be able to write expressions like: `(col1 < col2) = (1 > ?)`, which doesn't fit with what `is_satisfied_by` is supposed to do.
Additionally expressions like `1 = NULL` should evaluate to `NULL`, not `true` or `false`. `is_satsified_by` is not able to express that properly.
The proper way to go is implementing …
=> cql3: expr: make it possible to evaluate expr::binary_operator

test.py, test/pylib/artifact_registry.py, test/pylib/manager_client.py, test/pylib/rest_client.py, test/pylib/scylla_cluster.py, test/topology/test_topology.py
The `add_server` function now takes an optional `ReplaceConfig` struct
(implemented using `NamedTuple`), which specifies the ID of the replaced
server and whether to reuse the IP address.
If we want to reuse the IP address, we don't allocate one using the host
registry. This required certain refactors: moving the code responsible
for allocation of IPs outside `ScyllaServer`, into `ScyllaCluster`.
Add two tests, but they are now skipped: one of them is failing (unability
for new node to join group 0) and both suffer from a hardcoded 60-second sleep
in Scylla.
=> test.py: support node replace operation

bytes_ostream.hh, compaction/compaction_manager.cc, cql3/statements/create_index_statement.cc, db/per_partition_rate_limit_options.hh, direct_failure_detector/failure_detector.cc, mutation_fragment.cc, mutation_partition.cc, raft/log.cc, replica/database.cc, replica/database.hh, schema.cc, sstables/generation_type.hh, tasks/task_manager.hh, transport/server.cc, utils/logalloc.cc, utils/observable.hh
Fix some issues found with gcc 12. Note we can't fully compile with gcc yet, due to [1].
[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98056
=> treewide: improve compatibility with gcc 12

repair/repair.cc, repair/repair.hh, repair/repair_task.hh, repair/row_level.cc, repair/row_level.hh, tasks/task_manager.hh
The PR introduces shard_repair_task_impl which represents a repair task
that spans over a single shard repair.
repair_info is replaced with shard_repair_task_impl, since both serve 
similar purpose.
=> Task manager shard repair tasks

db/config.cc, db/config.hh, gms/feature_service.cc, gms/feature_service.hh, test/boost/mutation_reader_test.cc, test/boost/sstable_3_x_test.cc, test/boost/sstable_compaction_test.cc, test/lib/sstable_test_env.hh, test/lib/sstable_utils.hh, test/lib/test_services.cc, test/lib/test_services.hh
Mainly this PR removes global db::config and feature service that are used by sstables::test_env as dependencies for embedded sstables_manager. Other than that -- drop unused methods, remove nested test_env-s and relax few cases that use two temp dirs at a time for no gain.
=> Cleanup sstables::test_env's manager usage

cql3/statements/select_statement.cc, cql3/statements/select_statement.hh
Split the simple (and common) case from the complex case,
and coroutinize the latter. Hopefully this generates better
code for the simple case, and it makes the complex case a
little nicer.
=> cql3: select_statement: split and coroutinize process_results()

main.cc, replica/database.cc, replica/database.hh, replica/distributed_loader.cc, replica/table.cc, sstables/sstable_directory.cc, sstables/sstable_directory.hh, sstables/sstables_manager.cc, sstables/sstables_manager.hh, test/boost/sstable_directory_test.cc, test/lib/cql_test_env.cc, test/lib/sstable_test_env.hh, test/lib/test_services.cc, tools/scylla-sstable.cc
This PR hits two goals for "object storage" effort
1. Sstables loader "knows" that sstables components are stored in a Linux directory and uses utils/lister to access it. This is not going to work with sstables over object storage, the loader should be abstracted from the underlying storage.
2. Currently class keyspace and class column_family carry "datadir" and "all_datadirs" on board which are path on local filesystem where sstable files are stored (those usually started with /var/lib/scylla/data). The paths include subsdirs like "snapshots", "staging", etc. This is not going to look nice for obejct storage, the /var/lib/ prefix is excessive and meaningless in this case. Instead, ks and cf should know their "location" and some other component should know the directory where in which the …
=> Make sstable_directory call sstable_manager for sstables' components

alternator/ttl.cc
The first patch in this small series fixes a hang during shutdown when the expired-item scanning thread can hang in a retry loop instead of quitting.  These hangs were seen in some test runs (issue #12145).
The second patch is a failsafe against additional bugs like those solved by the first patch: If any bugs causes the same page fetch to repeatedly time out, let's stop the attempts after 10 retries instead of retrying for ever. When we stop the retries, a warning will be printed to the log, Scylla will wait until the next scan period and start a new scan from scratch - from a random position in the database, instead of hanging potentially-forever waiting for the same page.
=> alternator: fix hangs related to TTL scanning

cql3/statements/batch_statement.cc
As it has a do_with(), coroutinizing it is an automatic win.
=> cql3: batch_statement: coroutinize get_mutations()

column_computation.hh, cql3/statements/create_index_statement.cc, cql3/statements/select_statement.cc, db/view/view.cc, db/view/view.hh, gms/feature_service.hh, index/secondary_index_manager.cc, mutation_fragment.hh, mutation_partition.cc, mutation_partition.hh, replica/table.cc, schema.cc, test/boost/multishard_mutation_query_test.cc, test/boost/sstable_3_x_test.cc, test/cql-pytest/cassandra_tests/validation/entities/secondary_index_on_static_column_test.py, test/cql-pytest/cassandra_tests/validation/entities/secondary_index_test.py, test/cql-pytest/test_materialized_view.py, test/cql-pytest/test_secondary_index.py, view_info.hh
This pull request introduces support for global secondary indexes based on static columns.
Local secondary indexes based on secondary columns are not planned to be supported and are explicitly forbidden. Because there is only one static row per partition and local indexes require full partition key when querying, such indexes wouldn't be very useful and would only waste resources.
The index table for secondary indexes on static columns, unlike other secondary indexes, do not contain clustering keys from the base table. A static column's value determines a set of full partitions, so the clustering keys would only be unnecessary.
The already existing logic for querying using secondary indexes works after introducing minimal notifications. The view update generation path now works on a …
=> Secondary indexes on static columns

db/system_keyspace.cc, db/system_keyspace.hh, gms/application_state.cc, gms/application_state.hh, gms/gossiper.cc, gms/versioned_value.hh, main.cc, service/raft/raft_address_map.hh, service/raft/raft_group0.cc, service/raft/raft_group0.hh, service/raft/raft_group_registry.cc, service/raft/raft_group_registry.hh, service/storage_service.cc, service/storage_service.hh, test/lib/cql_test_env.cc
Thanks to #12250, Host IDs uniquely identify nodes. We can use them as Raft IDs which simplifies the code and makes reasoning about it easier, because Host IDs are always guaranteed to be present (while Raft IDs may be missing during upgrade).
Fixes: https://github.com/scylladb/scylladb/issues/12204
=> Use Host ID as Raft ID

service/storage_service.cc
update_normal_tokens checks that that the endpoint is in topology. Currently we call update_topology on this path only if it's not a normal_token_owner, but there are paths when the endpoint could be a normal token owner but still
be pending in topology so always update it, just in case.
=> storage_service: handle_state_normal: always update_topology before update_normal_tokens

cql3/expr/expression.cc, cql3/expr/prepare_expr.cc, test/boost/expr_test.cc
This PR implements two things:
* Getting the value of a conjunction of elements separated by `AND` using `expr::evaluate`
* Preparing conjunctions using `prepare_expression`
---
`NULL` is treated as an "unkown value" - maybe `true` maybe `false`.
`TRUE AND NULL` evaluates to `NULL` because it might be `true` but also might be `false`.
`FALSE AND NULL` evaluates to `FALSE` because no matter what value `NULL` acts as, the result will still be `FALSE`.
Unset and empty values are not allowed.
Usually in CQL the rule is that when `NULL` occurs in an operation the whole expression becomes `NULL`, but here we decided to deviate from this behavior.
Treating `NULL` as an "unkown value" is the standard SQL way of handing `NULLs` in conjunctions.
It works this way in MySQL and Postgres so we do it …
=> cql3: expr: make it possible to prepare and evaluate conjunctions

api/endpoint_snitch.cc, db/hints/host_filter.cc, locator/token_metadata.cc, locator/token_metadata.hh, locator/topology.cc, locator/topology.hh, message/messaging_service.cc, service/storage_service.cc, test/boost/network_topology_strategy_test.cc
Now, with a44ca0690642b0b33d78932432fbab92de1cc0f7, is_normal_token_owner that replaced is_member
does not rely anymore on the pending status
of endpoints in topology.
With that we can get rid of this state and just keep all endpoints we know about in the topology.
=> topology: get rid of pending state

cache_flat_mutation_reader.hh, compaction/compaction.cc, mutation_compactor.hh, mutation_fragment.cc, mutation_fragment.hh, mutation_partition.cc, mutation_writer/partition_based_splitting_writer.cc, position_in_partition.hh, query-request.hh, query.cc, readers/multishard.cc, readers/mutation_fragment_v1_stream.hh, service/pager/query_pagers.cc, sstables/metadata_collector.cc, sstables/mx/writer.cc, test/boost/cache_flat_mutation_reader_test.cc, test/boost/clustering_ranges_walker_test.cc, test/boost/mutation_fragment_test.cc, test/boost/mutation_reader_test.cc, test/boost/mutation_test.cc, test/boost/range_tombstone_list_test.cc, test/boost/row_cache_test.cc, test/boost/sstable_conforms_to_mutation_source_test.cc, test/boost/types_test.cc, test/lib/mutation_source_test.cc, types.cc
This PR fixes several bugs related to handling of non-full
clustering keys.
One is in trim_clustering_row_ranges_to(), which is broken for non-full keys in reverse
mode. It will trim the range to position_in_partition_view::after_key(full_key) instead of
position_in_partition_view::before_key(key), hence it will include the
key in the resulting range rather than exclude it.
Fixes #12180
after_key() was creating a position which is after all keys prefixed
by a non-full key, rather than a position which is right after that
key.
This will issue will be caught by cql_query_test::test_compact_storage
in debug mode when mutation_partition_v2 merging starts inserting
sentinels at position after_key() on preemption.
It probably already causes problems for such keys as after_key() is used 
in …
=> Fix handling of non-full clustering keys in the read path

main.cc, repair/repair.cc, repair/repair.hh, repair/row_level.hh, service/storage_service.cc, service/storage_service.hh, test/boost/UUID_test.cc, utils/UUID.hh
This includes merges 396d9e6a46 and 2c021affd1
Things that got changed here:
1. All the node_ops_... stuff in storage_service was coroutinized after 5.0, so in this merge the changes were de-coroutinized back
2. Had to cherry-pick molding for UUID (69fcc053bbb and 489e50ef3a7)
3. tracker::is_aborted() was added after 5.0, it caused minor context conflict
4. watchdog interval was changed, also caused minor context conflict
refs: #10284
=> Backport nodeops abort thread use-after-free patches

api/api-doc/task_manager_test.json, api/task_manager.cc, api/task_manager_test.cc, repair/repair.cc, repair/repair_task.hh, repair/row_level.cc, tasks/task_manager.cc, tasks/task_manager.hh, tasks/test_module.hh
Type of operation is related to a specific implementation 
of a task. Then, it should rather be access with a virtual 
method in tasks::task_manager::task::impl than be 
its attribute.
=> tasks: get task's type with method

docs/operating-scylla/admin-tools/scylla-sstable.rst, docs/operating-scylla/admin-tools/scylla-types.rst, tools/scylla-sstable.cc
Currently the scylla tools (`scylla-types` and `scylla-sstable`) have documentation in two places: high level documentation can be found at `docs/operating-scylla/admin-tools/scylla-{types,sstable}.rst`, while low level, more detailed documentation is embedded in the tool itself. This is especially pronounced for `scylla-sstable`, which only has a short description of its operations online, all details being found only in the command-line help.
We want to move away from this model, such that all documentation can be found online, with the command-line help being reserved to documenting how the various switches and flags work, on top of a short description of the operation and a link to the detailed online docs.
=> docs: move documentation of tools online

test/alternator/test_metrics.py, test/alternator/test_ttl.py
This series backports several patches which add or enable tests for  Alternator TTL. The series does not touch the code - just tests.
The goal of backporting more tests is to get the code - which is already in branch 5.1 - tested. It wasn't a good idea to backport code without backporting the tests for it.
=> Backport Alternator TTL tests

api/storage_service.cc, replica/database.hh, replica/table.cc
This a backport of 9fa17838929a3ca8ec6e0568a4c72062d7ed3e73 (#11902) to branch-5.0
Flush the memtable before cleaning up the table so not to leave any disowned tokens in the memtable
as they might be resurrected if left in the memtable.
Refs #1239
=> Backport 5.0: cleanup compaction: flush memtable

docs/operating-scylla/admin.rst, docs/operating-scylla/procedures/cluster-management/add-dc-to-existing-dc.rst, docs/operating-scylla/procedures/cluster-management/create-cluster-multidc.rst, docs/operating-scylla/procedures/cluster-management/create-cluster.rst, docs/operating-scylla/procedures/cluster-management/ec2-dc.rst, docs/operating-scylla/procedures/cluster-management/rebuild-node.rst, docs/operating-scylla/procedures/cluster-management/replace-dead-node.rst, docs/troubleshooting/node-joined-without-any-data.rst
Fixes https://github.com/scylladb/scylladb/issues/12318
This PR removes all occurrences of the `auto_bootstrap` option in the docs. 
In most cases, I've simply removed the option name and its definition, but sometimes additional changes were necessary:
- In node-joined-without-any-data.rst, I removed the `auto_bootstrap `option as one of the causes of the problem.
- In rebuild-node.rst, I removed the first step in the procedure (enabling the `auto_bootstrap `option).
- In admin. rst, I removed the section about manual bootstrapping - it's based on setting `auto_bootstrap` to false, which is not possible now.
=> docs: remove auto_bootstrap option from the documentation

flat_mutation_reader.cc, range_tombstone_change_generator.hh
This series backports 0a3aba36e6e4b78ef6e7bb2f5ee204aa2cccfe1c to branch 5.0.
It ensures that a closing range_tombstone_change is emitted if the highest tombstone is open ended
since range_tombstone_change_generator::flush does not do it by default.
With the additional testing added 9a59e9369b87b1bcefed6d1d5edf25c5d3451bc4 unit tests fail without the additional patches in the series, so it exposes a latent bug in the branch where the closing range_tombstone_change is not always emitted when flushing on end of partition of end of position range.
One additional change was required for unit tests to pass:
```diff
diff --git a/range_tombstone_change_generator.hh b/range_tombstone_change_generator.hh
index 6f98be5dce..9cde8d9b20 100644
--- a/range_tombstone_change_generator.hh
+++ …
```
=> Branch 5.0: backport 'range_tombstone_change_generator: flush: emit closing range_tombstone_change'

repair/repair.cc, repair/repair.hh, repair/repair_task.hh, repair/row_level.cc, service/storage_service.cc, service/storage_service.hh, tasks/task_manager.cc, tasks/task_manager.hh
Aborting of repair operation is fully managed by task manager.
Repair tasks are aborted:
- on shutdown; top level repair tasks subscribe to global abort source. On shutdown all tasks are aborted recursively
- through node operations (applies to data_sync_repair_task_impls and their descendants only); data_sync_repair_task_impl subscribes to node_ops_info abort source
- with task manager api (top level tasks are abortable)
- with storage_service api and on failure; these cases were modified to be aborted the same way as the ones from above are.
=> Abort repair tasks

docs/dev/reverse-reads.md, mutation.hh, mutation_consumer.hh, mutation_partition.cc, test/boost/mutation_test.cc
This commit removes consume_in_reverse::legacy_half_reverse, an option
once used to indicate that the given key ranges are sorted descending,
based on the clustering key of the start of the range, and that the
range tombstones inside partition would be sorted (descending, as all
the mutation fragments would) according to their end (but range
tombstone would still be stored according to their start bound).
As it turns out, mutation::consume, when called with legacy_half_reverse
option produces invalid fragment stream, one where all the row
tombstone changes come after all the clustering rows. This was not an
issue, since when constructing results from the query, Scylla would not
pass the tombstones to the client, but instead compact data beforehand.
In this commit, the …
=> Remove legacy half reverse

reader_concurrency_semaphore.cc, reader_concurrency_semaphore.hh, reader_permit.hh, replica/database.cc, sstables/kl/reader.cc, sstables/mx/reader.cc
Sstable read related metrics are broken for a long time now. First, the introduction of inactive reads (https://github.com/scylladb/scylladb/issues/1865) diluted this metric, as it now also contained inactive reads (contrary to the metric's name). Then, after moving the semaphore in front of the cache (3d816b7c1) this metric became completely broken as this metric now contains all kinds of reads: disk, in-memory and inactive ones too.
This series aims to remedy this:
* `scylla_database_active_reads` is fixed to only include active reads.
* `scylla_database_active_reads_memory_consumption` is renamed to `scylla_database_reads_memory_consumption` and its description is brought up-to-date.
* `scylla_database_disk_reads` is added to track current reads that are gone to disk.
* …
=> replica/database: fix read related metrics

configure.py, dht/i_partitioner.hh, docs/operating-scylla/admin-tools/scylla-sstable.rst, lang/lua.cc, lang/lua_scylla_types.hh, test/cql-pytest/test_tools.py, tools/json_writer.hh, tools/lua_sstable_consumer.cc, tools/lua_sstable_consumer.hh, tools/scylla-sstable-scripts/README.md, tools/scylla-sstable-scripts/dump.lua, tools/scylla-sstable-scripts/find-incomplete-clustering-row-keys.lua, tools/scylla-sstable-scripts/fragment-stats.lua, tools/scylla-sstable-scripts/slice.lua, tools/scylla-sstable.cc, tools/scylla-types.cc, tools/sstable_consumer.hh
Introduce a new "script" operation, which loads a script from the specified path, then feeds the mutation fragment stream to it. The script can then extract, process and present information from the sstable as it wishes.
For now only Lua scripts are supported for the simple reason that Lua is easy to write bindings for, it is simple and lightweight and more importantly we already have Lua included in the Scylla binary as it is used as the implementation language for UDF/UDA. We might consider WASM support in the future, but for now we don't have any language support in WASM available.
Example:
```lua
function new_stats(key)
return {
partition_key = key,
total = 0,
partition = 0,
static_row = 0,
clustering_row = 0,
range_tombstone_change = 0,
};
end
total_stats = new_stats(nil);
function …
```
=> tools/scylla-sstable: add lua scripting support

api/storage_service.cc, replica/database.hh, replica/table.cc
This a backport of 9fa17838929a3ca8ec6e0568a4c72062d7ed3e73 (#11902) to branch-5.1
Flush the memtable before cleaning up the table so not to leave any disowned tokens in the memtable
as they might be resurrected if left in the memtable.
Refs #1239
=> Backport 5.1 cleanup compaction flush memtable

configure.py
The planned integration of cross-module optimizations in scylladb/scylladb-enterprise requires several changes to `configure.py`. To minimize the divergence between the `configure.py`s of both repositories, this series upstreams some of these changes to scylladb/scylladb.
The changes mostly remove dead code and fix some traps for the unaware.
=> configure.py: a bunch of clean-up changes

db/system_keyspace.cc, db/system_keyspace.hh, main.cc, replica/database.hh, replica/distributed_loader.cc, replica/distributed_loader.hh, service/raft/raft_group0.cc, service/raft/raft_group0.hh, service/raft/raft_group_registry.cc, service/raft/raft_group_registry.hh, service/raft/raft_sys_table_storage.cc, service/storage_service.cc, test/lib/cql_test_env.cc, test/pylib/util.py, test/topology/test_topology.py, test/topology_raft_disabled/test_raft_upgrade.py
Make it so that failures in `removenode`/`decommission` don't lead to reduced availability, and any leftovers in group 0 can be removed by `removenode`:
- In `removenode`, make the node a non-voter before removing it from the token ring. This removes the possibility of having a group 0 voting member which doesn't correspond to a token ring member. We can still be left with a non-voter, but that's doesn't reduce the availability of group 0.
- As above but for `decommission`.
- Make it possible to remove group 0 members that don't correspond to token ring members from group 0 using `removenode`. 
- Add an API to query the current group 0 configuration.
Fixes #11723.
=> raft: improve group 0 reconfiguration failure handling

cql3/expr/expression.hh, cql3/expr/prepare_expr.cc, cql3/expr/restrictions.cc, test/boost/expr_test.cc, test/lib/expr_test_utils.cc, test/lib/expr_test_utils.hh
`prepare_expression` takes an unprepared CQL expression straight from the parser output and prepares it. Preparation consists of various type checks that are needed to ensure that the expression is correct and to reason about it.
While `prepare_expression` supports a number of different types of expressions, until now it was impossible to prepare a `binary_operator`. Eventually we would like to be able to prepare all kinds of expressions, so this PR adds the missing support for `binary_operator`.
=> cql3/expr: make it possible to prepare binary_operator

test.py, test/pylib/pool.py
If the after test check fails (is_after_test_ok is False), discard the cluster and raise exception so context manager (pool) does not recycle it.
Ignore exception re-raised by the context manager.
Fixes #12360
=> test.py: handle broken clusters for Python suite

docs/upgrade/index.rst
Fix https://github.com/scylladb/scylla-docs/issues/3968
This PR adds the information that an upgrade to each successive major version is required to upgrade from an old ScyllaDB version.
=> doc: add the general upgrade policy

test/pylib/scylla_cluster.py
Don't use a range scan, which is very inefficient, to perform a query for checking CQL availability.
Improve logging when waiting for server startup times out. Provide details about the failure: whether we managed to obtain the Host ID of the server and whether we managed to establish a CQL connection.
=> test/pylib: scylla_cluster: improve server startup check

types.cc
- makes all regexes static
If making regex compilation static
for uuid_type_impl and timeuuid_type_impl helps then it should
also help for timestamp_type and simple_date_type.
-  remove unnecessary tolower transform in simple_date_type_impl::from_sstring
Following function uses only decimal and '-' characters (see date_re). They are not
affected by tolower call in any way.
Aditionally std::strtoll supports "0x" prefixes but also accepts
upper case version "0X" so it's also not affected by tolower call.
get_simple_date_time only casts strings to integer types using
boost:lexical_cast so also not affected by tolower.
Finally, serialize only uses str to include it in an exception text
so tolower doesn't affect it in a positive way. It's even better
that input is displayed to the user as it …
=> Make regexes in types.cc static and remove unnecessary tolower transform

conf/scylla.yaml, docs/operating-scylla/procedures/cluster-management/_common/prereq.rst, docs/operating-scylla/procedures/cluster-management/add-dc-to-existing-dc.rst, docs/operating-scylla/procedures/cluster-management/add-node-to-cluster.rst, docs/operating-scylla/procedures/cluster-management/create-cluster-multidc.rst, docs/operating-scylla/procedures/cluster-management/create-cluster.rst, docs/operating-scylla/procedures/cluster-management/ec2-dc.rst, docs/operating-scylla/procedures/cluster-management/replace-dead-node-or-more.rst, docs/operating-scylla/procedures/cluster-management/replace-dead-node.rst
New clusters that use a fresh conf/scylla.yaml will have `consistent_cluster_management: true`, which will enable Raft, unless the user explicitly turns it off before booting the cluster.
People using existing yaml files will continue without Raft, unless consistent_cluster_management is explicitly requested during/after upgrade.
Also update the docs: cluster creation and node addition procedures.
Fixes #12572.
=> Enable Raft by default in new clusters

test/pylib/scylla_cluster.py, test/topology/test_topology.py
If a server is stopped suddenly (i.e. not graceful), commitlog might be in inconsistent state. Add a test case and enable Scylla configuration options to handle this.
Fixes https://github.com/scylladb/scylladb/issues/12218
=> pytest: start after ungraceful stop

test/boost/sstable_directory_test.cc, test/lib/sstable_test_env.hh, test/lib/test_services.cc
Today's sstable_test_env starts with a default-configured db::config and, thus, sstables_manager. Test cases that run in this env always create a tempdir to store sstable files in on their own. Next patching makes sstable-manager and friends fully control the data-dir path in order to support object storage for sstables in a nice way, and this behavior of tests upsets this ongoing work.
Said that, this PR configures sstable_test_env with a tempdir and pins down the cases using it to stick to that directory, rather than to the custom one.
=> Configure sstable_test_env with tempdir

db/view/row_locking.cc
Since we're potentially searching the row_lock in parallel to acquiring the read_lock on the partition, we're racing with row_locker::unlock that may erase the _row_locks entry for the same clustering key, since there is no lock to protect it up until the partition lock has been acquired and the lock_partition future is resolved.
This change moves the code to search for or allocate the row lock _after_ the partition lock has been acquired to make sure we're synchronously starting the read/write lock function on it, without yielding, to prevent this use-after-free.
This adds an allocation for copying the clustering key in advance that wasn't needed before if the lock for it was already found, but the view building is not on the hot path so we can tolerate that.
This is required on top of …
=> view: row_lock: lock_ck: find or construct row_lock under partition lock

cql3/expr/expression.cc, test/boost/expr_test.cc, test/cql-pytest/test_filtering.py
`evaluation_inputs` is a struct which contains data needed to evaluate expressions - values of columns, bind variables and other data.
`is_on_of()` is a function used to to evaluate `IN` restrictions. It checks whether the LHS is one of elements on the RHS list.
Generally when evaluating expressions we get the `evaluation_inputs` as an argument and we should pass them along to any functions that evaluate subexpressions.
`is_one_of()` got the inputs as an argument, but didn't pass them along to `equal()`, instead it creates new empty `evaluation_inputs{}` and gives that to `equal()`.
At first [I thought this was a bug](https://github.com/scylladb/scylladb/pull/12356#discussion_r1084300969) - with missing information there could be a crash if `equal()` tried to evaluate an expression with a …
=> cql3: expr: don't pass empty evaluation_inputs in is_one_of

docs/operating-scylla/procedures/cluster-management/remove-node.rst
This PR extends the description of using `nodetool removenode `to remove an unavailable node, as requested in https://github.com/scylladb/scylla-enterprise/issues/2338.
=> docs: extend the warning on using "nodetool removenode"

alternator/streams.cc
Fixes #12601 (maybe?)
Sort the set of tables on ID. This should ensure we never generate duplicates in a paged listing here. Can obviously miss things if they are added between paged calls and end up with a "smaller" UUID/ARN, but that is to be expected.
=> alterator::streams: Sort tables in list_streams to ensure no duplicates

test/alternator/conftest.py, test/alternator/test_streams.py
The first patch in this series enables a previously-skipped test for what happens with Limit=0. The test passes.
The second patch adds an xfailng test for very large Limit.
=> test/alternator: tests for Limit parameter of ListStreams operation

compaction/compaction_manager.cc, compaction/compaction_manager.hh, compaction/task_manager_module.hh, main.cc, tasks/task_manager.cc, tasks/task_manager.hh, test/boost/mutation_test.cc, test/boost/sstable_3_x_test.cc, test/boost/sstable_compaction_test.cc, test/lib/cql_test_env.cc, test/lib/sstable_utils.cc, test/lib/sstable_utils.hh, test/lib/test_services.hh, test/perf/perf_sstable.hh
Introduces task manager's compaction module. That's an initial
part of integration of compaction with task manager. 
When fully integrated, task manager will allow user to track compaction 
operations, check status and progress of each individual one. It will help 
with creating an asynchronous version of rest api that forces any compaction.
Currently, users can see with /task_manager/list_modules api call that
compaction is one of the modules accessible through task manager. 
They won't get any additional information though, since compaction 
tasks are not created yet.
A shared_ptr to compaction module is kept in compaction manager.
=> Add compaction module to task manager

replica/compaction_group.hh, replica/database.hh, replica/table.cc
[table: Fix disk-space related metrics](https://github.com/scylladb/scylladb/commit/529a1239a98eefd2b1aa6a6785e8c4b88d43de60) fixes the table's disk space  related metrics.
whereas second patch fixes an inefficiency when computing statistics which can be triggered with multiple compaction groups.
=> Fix inefficiency when rebuilding table statistics with compaction groups

configure.py, test/boost/commitlog_test.cc, test/boost/database_test.cc, test/boost/memtable_test.cc, test/boost/mutation_reader_test.cc, test/boost/reader_concurrency_semaphore_test.cc, test/boost/row_cache_test.cc, test/boost/sstable_compaction_test.cc, test/boost/sstable_datafile_test.cc, test/boost/sstable_directory_test.cc, test/boost/sstable_mutation_test.cc, test/boost/sstable_resharding_test.cc, test/boost/sstable_set_test.cc, test/boost/view_build_test.cc, test/lib/key_utils.cc, test/lib/key_utils.hh, test/lib/mutation_source_test.cc, test/lib/random_schema.cc, test/lib/random_schema.hh, test/lib/simple_schema.hh, test/lib/sstable_utils.cc, test/lib/sstable_utils.hh, test/lib/test_services.cc, test/lib/test_services.hh, test/lib/test_utils.cc, test/perf/perf_sstable.hh
We currently have two method families to generate partition keys:
* make_keys() in test/lib/simple_schema.hh
* token_generation_for_shard() in test/lib/sstable_utils.hh
Both work only for schemas with a single partition key column of `text` type and both generate keys of fixed size.
This is very restrictive and simplistic. Tests, which wanted anything more complicated than that had to rely on open-coded key generation.
Also, many tests started to rely on the simplistic nature of these keys, in particular two tests started failing because the new key generation method generated keys of varying size:
* sstable_compaction_test.sstable_run_based_compaction_test
* sstable_mutation_test.test_key_count_estimation
These two tests seems to depend on generated keys all being of the same size. This …
=> test/lib: introduce key_utils.hh

docs/faq.rst, docs/upgrade/_common/upgrade-guide-from-2021.x.y-to-2021.x.z-ubuntu-and-debian.rst, docs/upgrade/_common/upgrade-guide-from-2022.x.y-to-2022.x.z-ubuntu-and-debian.rst, docs/upgrade/_common/upgrade-guide-v2022-patch-ubuntu-and-debian-p1.rst
This PR is related to https://github.com/scylladb/scylla-enterprise/issues/2176.
It adds a FAQ about a workaround to install a ScyllaDB version that is not the most recent patch version.
In addition, the link to that FAQ is added to the patch upgrade guides 2021 and 2022 .
=> doc: document the workaround to install a non-latest ScyllaDB version

cql3/functions/functions.cc, cql3/functions/functions.hh, cql3/statements/drop_function_statement.cc, test/cql-pytest/test_uda.py, test/cql-pytest/util.py
This patch fixes 2 issues with checking whether UDFs are used in UDAs:
1) UDFs types are not considered during the check, which prevents us from dropping a UDF that isn't used in any UDAs, but shares its name with one of them.
2) the REDUCEFUNC is not considered during the check, which allows dropping a UDF even though it's used in a UDA as the REDUCEFUNC.
Additionally, tests for these issues are added
=> uda: improve checking whether UDFs are used in UDAs in DROP statements

docs/upgrade/index.rst
Related: https://github.com/scylladb/scylladb/pull/12586
This PR improves the upgrade policy added with https://github.com/scylladb/scylladb/pull/12586, according to the feedback from:
@tzach
> Upgrading from 4.6 to 5.0 is not clear; better to use 4.x to 4.y versions as an example.
and @bhalevy
> It is not completely clear that when upgrading through several versions, the whole cluster needs to be upgraded to each consecutive version, not just the rolling node.
In addition, the content is organized into sections for the sake of readability.
=> doc: improve the general upgrade policy

compaction/compaction_manager.cc, main.cc, replica/table.cc
- main: consider EDQUOT as environmental failure also
- main: use defer_verbose_shutdown() to shutdown compaction manager
- replica/table: extract should_retry() int with_retry
- replica/table: retry on EDQUOT when flushing memtable
Fixes #12626
=> Handle EDQUOT error just like ENOSPC

locator/abstract_replication_strategy.cc, locator/abstract_replication_strategy.hh, locator/token_metadata.cc
This two-patch series aims to improve `get_address_ranges()` by eliminating cases of quadratic behavior
which were noticed to cause huge allocations, and by deduplicating the code of `get_address_ranges()`
with the almost-identical `get_ranges()`.
Refs https://github.com/scylladb/scylladb/issues/10337
Refs https://github.com/scylladb/scylladb/issues/10817
Refs https://github.com/scylladb/scylladb/issues/10836
Refs https://github.com/scylladb/scylladb/issues/10837
Fixes https://github.com/scylladb/scylladb/issues/12724
=> locator: token_metadata: improve get_address_ranges()

replica/distributed_loader.cc, replica/distributed_loader.hh, sstables/sstable_directory.cc, sstables/sstable_directory.hh, test/boost/sstable_directory_test.cc
Now it's scattered between dist. loader and sstable directory code making the latter quite bloated. Keeping everything in distributed loader makes the sstable_directory code compact and easier to patch to support object storage backend.
=> Keep reshape and reshard logic in distributed loader

cql3/query_processor.cc, service/client_state.hh, test/cql-pytest/test_batch.py, test/cql-pytest/test_shedding.py, transport/server.cc
CQL transport sever error handling fixes and improvements:
* log failed requests with `DEBUG` level for easier debugging;
* in case of unhandled errors, deliver them to the client as `SERVER_ERROR`'s
* fix for `protocol_error`'s in case of shedded big requests;
* explicit tests have been written for the error handling problems above.
=> Transport server error handling fixes

repair/repair.cc, test/rest_api/test_storage_service.py
System keyspace is a keyspace with local replication strategy and thus
it does not need to be repaired. It is possible to invoke repair
of this keyspace through the api, which leads to runtime error since
peer_events and scylla_table_schema_history have different sharding logic.
For keyspaces with local replication strategy repair_service::do_repair_start
returns immediately.
=> repair: finish repair immediately on local keyspaces

raft/server.cc, test/pylib/rest_client.py, test/topology/test_snapshot.py, test/topology/test_topology.py, test/topology_raft_disabled/test_raft_upgrade.py
Force snapshot with schema changes while server down. Then verify schema when bringing back up the server.
=> test/raft: test snapshot threshold

service/storage_proxy.cc, test/cql-pytest/test_cdc.py, test/cql/cdc_with_lwt_test.cql, test/cql/cdc_with_lwt_test.result, test/cql/suite.yaml
`paxos_response_handler::learn_decision` was calling
`cdc_service::augment_mutation_call` concurrently with
`storage_proxy::mutate_internal`. `augment_mutation_call` was selecting
rows from the base table in order to create the preimage, while
`mutate_internal` was writing rows to the table. It was therefore
possible for the preimage to observe the update that it accompanied,
which doesn't make any sense, because the preimage is supposed to show
the state before the update.
Fix this by performing the operations sequentially. We can still perform
the CDC mutation write concurrently with the base mutation write.
`cdc_with_lwt_test` was sometimes failing in debug mode due to this bug
and was marked flaky. Unmark it.
Also fix a comment in `cdc_with_lwt_test`.
Fixes #12098
=> Sequence CDC preimage select with Paxos learn write

lang/wasm.cc, test/cql-pytest/test_wasm.py
Currently, because serialize_visitor::operator() is not implemented for counters, we cannot convert a counter returned by a WASM UDF to bytes when returning from wasm::run_script().
We could disallow using counters as WASM UDF return types, but an easier solution which we're already using in Lua UDFs is treating the returned counters as 64-bit integers when deserializing. This patch implements the latter approach and adds a test for it.
=> wasm: deserialize counters as integers

cql3/functions/functions.cc, cql3/functions/functions.hh, cql3/functions/user_aggregate.hh, cql3/statements/drop_function_statement.cc, db/schema_tables.cc, test/cql-pytest/test_uda.py
This patch is based on #12681, only last 3 commits are relevant.
As described in #12709, currently, when a UDF used in a UDA is replaced, the UDA is not updated until the whole node is restarted.
This patch fixes the issue by updating all affected UDAs when a UDF is replaced.
Additionally, it includes a few convenience changes
=> functions: handle replacing UDFs used in UDAs

test/pylib/manager_client.py, test/pylib/rest_client.py, test/pylib/scylla_cluster.py
Recently we enabled RBNO by default in all topology operations. This
made the operations a bit slower (repair-based topology ops are a bit
slower than classic streaming - they do more work), and in debug mode
with large number of concurrent tests running, they might timeout.
The timeout for bootstrap was already increased before, do the same for
decommission/removenode. The previously used timeout was 300 seconds
(this is the default used by aiohttp library when it makes HTTP
requests), now use the TOPOLOGY_TIMEOUT constant from ScyllaServer which
is 1000 seconds.
=> test/pylib: use larger timeout for decommission/removenode

compaction/compaction_strategy.cc, replica/table.cc
Both patches are important to fix inefficiencies when updating the backlog tracker, which can manifest as a reactor stall, on a special event like schema change.
No conflicts when backporting.
Regression since https://github.com/scylladb/scylladb/commit/1d9f53c881c562b276250c4503801ee92d6d2aa6, which is present in branch 5.1 onwards.
=> Backport compaction-backlog-tracker fixes to branch-5.2

compaction/compaction_strategy.cc, replica/table.cc
Both patches are important to fix inefficiencies when updating the backlog tracker, which can manifest as a reactor stall, on a special event like schema change.
A simple conflict was resolved in the first patch, since master has compaction groups. It was very easy to resolve.
Regression since https://github.com/scylladb/scylladb/commit/1d9f53c881c562b276250c4503801ee92d6d2aa6, which is present in 5.1 onwards. So probably it merits a backport to 5.2 too.
=> Backport compaction-backlog-tracker fixes to branch-5.1

replica/database.hh, replica/distributed_loader.cc, replica/distributed_loader.hh
There's the distribtued_loader::populate_column_family() helper that manages sstables on their way towards table on boot. The method naturally belongs the the table_population_metadata -- a helper class that in fact prepares the ground for the method in question.
This PR moves the method into metadata class and removes whole lot of extra alias-references and private-fields exporting methods from it. Also it keeps start_subdir and populate_c._f. logic close to each other and relaxes several excessive checks from them.
=> Move population code into table_population_metadata

api/compaction_manager.cc, compaction/compaction_manager.cc, compaction/compaction_manager.hh, db/system_keyspace.cc, db/system_keyspace.hh
There are two methods to mess with compaction history -- update and get. The former had been patched to use local system-keyspace instance by 907fd2d3 (system_keyspace: De-static compaction history update) now it's time for the latter (spoiler: it's only used by the API handler)
=> Get compaction history without using qctx

test/rest_api/task_manager_utils.py, test/rest_api/test_task_manager.py
Tests of each module that is integrated with task manager use
calls to task manager api. Boilerplate to call, check status, and
get result may be reduced using functions. 
task_manager_utils.py contains wrappers for task manager api
calls and helpers that may be reused by different tests.
=> Add task manager utils for tests

test/boost/mutation_test.cc
In test_v2_apply_monotonically_is_monotonic_on_alloc_failures we
generate mutations with non-full continuity, so we should pass
is_evictable::yes to apply_monotonically(). Otherwise, it will assume
fully-continuous versions and not try to maintain continuity by
inserting sentinels.
This manifested in sporadic failures on continuity check.
Fixes #12882
=> test: mutation_test: Fix sporadic failure due to continuity mismatch

auth/CMakeLists.txt, cql3/CMakeLists.txt, rust/CMakeLists.txt
- build: cmake: link cql3 against wasmtime_bindings
- build: cmake: output rust binding headers in expected dir
- build: cmake: link auth against cql3
=> build: cmake: sync with `configure.py` (4/n)

CMakeLists.txt, alternator/CMakeLists.txt, cmake/FindxxHash.cmake, cmake/add_version_library.cmake
- build: cmake: build release.cc as a library
- build: cmake: link alternator against cql3
- build: cmake: link scylla against xxHash::xxhash
- build: cmake: use lld or gold as linker if available
=> build: cmake: sync with `configure.py` (5/n) 

docs/operating-scylla/procedures/backup-restore/_common/manager.rst, docs/operating-scylla/procedures/backup-restore/restore.rst
Fixes https://github.com/scylladb/scylladb/issues/12945
This PR removes the incorrect information and updates the link to the relevant page in the Manager docs.
=> doc: remove the incorrect information about IPs from the Restore page

test/cql-pytest/test_shedding.py
The test relies on exact request size, this doesn't work if compression is applied. The driver enables compression only if both the server and the client agree on the codec to use. If compression package
(e.g. lz4) is not installed, the compression
is not used.
The trick with locally_supported_compressions is needed since I couldn't find any standard means to disable compression other than the compression flag
on the cluster object, which seemed too broad.
fixes: #12836
=> test_shed_too_large_request fix: disable compression

repair/repair.cc, repair/repair_task.hh, repair/row_level.cc
Shard id is logged twice in repair (once explicitly, once added by logger).
Redundant occurrence is deleted.
shard_repair_task_impl::id (which contains global repair shard)
is renamed to avoid further confusion.
Fixes: #12955
=> Shard of shard repair task impl

test/boost/sstable_datafile_test.cc
Some test cases can be made a bit more compact by using the sugar provided by the aforementioned sugar
=> Refine usage of sstable_test_env::reusable_sst() method

service/forward_service.cc, test/boost/cql_query_test.cc
Aggregation query on counter column is failing because forward_service is looking for function with counter as an argument and such function doesn't exist. Instead the long type should be used. 
Fixes: #12939
=> service:forward_service: use long type instead of counter in function mocking

mutation/mutation_fragment.cc, mutation/mutation_fragment.hh, mutation/mutation_fragment_v2.hh, reader_permit.hh, test/boost/reader_concurrency_semaphore_test.cc
Said method can now throw `std::bad_alloc` since aab5954. All call-sites should have been adapted in the series introducing the throw, but some managed to slip through because the oom unit test didn't run in debug mode. This series fixes the remaining unpatched call-sites and makes sure the test runs in debug mode too, so leaks like this are detected.
Fixes: #12767
=> Fix memory leaks caused by throwing reader_concurrency_semaphore::consume()

cdc/generation.cc, cdc/generation.hh, db/commitlog/replay_position.hh, db/schema_tables.cc, db/view/view_update_backlog.hh, utils/UUID.hh
- db/view: use operator<=> to define comparison operators
- utils: UUID: use defaulted operator<=>
- db: schema_tables: use defaulted operator<=>
- cdc: generation: schema_tables: use defaulted operator<=>
- db::commitlog::replay_position: use defaulted operator<=>
=> treewide: use (defaulted) operator<=> when appropriate

db/chained_delegating_reader.hh, db/size_estimates_virtual_reader.cc, db/view/build_progress_virtual_reader.hh, index/built_indexes_virtual_reader.hh, readers/combined.cc, readers/delegating_v2.hh, readers/filtering.hh, readers/flat_mutation_reader_v2.hh, readers/multishard.cc, readers/mutation_reader.cc, readers/mutation_readers.cc, row_cache.cc, sstables/kl/reader.cc, sstables/mx/reader.cc, test/boost/flat_mutation_reader_test.cc
The series fixes the `make_nonforwardable` reader, it shouldn't emit `partition_end` for previous partition after `next_partition()` and `fast_forward_to()`
Fixes: #12249
=> readers/nonforwarding: don't emit partition_end on next_partition,fast_forward_to

CMakeLists.txt, auth/CMakeLists.txt, cmake/FindThrift.cmake, cmake/Findlibxcrypt.cmake, db/CMakeLists.txt, interface/CMakeLists.txt, mutation/CMakeLists.txt, replica/CMakeLists.txt, streaming/CMakeLists.txt, thrift/CMakeLists.txt
- build: cmake: support thrift < 0.11.0
- build: cmake: find Thrift before using it
- build: cmake: find libxcrypt before using it
- build: cmake: expose scylla_gen_build_dir from "interface"
- build: cmake: extract thrift out
- build: cmake: link the whole auth
- build: cmake: extract mutation,db,replica,streaming out
=> build: cmake: sync with `configure.py` (7/n)

docs/alternator/compatibility.md
This PR adds a note to the Alternator TTL section to specify in which Open Source and Enterprise versions the feature was promoted from experimental to non-experimental.
The challenge here is that OSS and Enterprise are (still) **documented together**, but they're **not in sync** in promoting the TTL feature: it's still experimental in 5.1 (released) but no longer experimental in 2022.2 (to be released soon).
We can take one of the following approaches:
a) Merge this PR with master and ask the 2022.2 users to refer to master.
b) Merge this PR with master and then backport to branch-5.1. If we choose this approach, it is necessary to backport https://github.com/scylladb/scylladb/pull/11997 beforehand to avoid conflicts.
I'd opt for a) because it makes more sense from the OSS perspective …
=> doc: specify the versions where Alternator TTL is no longer experimental

CMakeLists.txt, cdc/CMakeLists.txt, compaction/CMakeLists.txt, dht/CMakeLists.txt, gms/CMakeLists.txt, lang/CMakeLists.txt, locator/CMakeLists.txt, mutation_writer/CMakeLists.txt, raft/CMakeLists.txt, readers/CMakeLists.txt, replica/CMakeLists.txt, rust/CMakeLists.txt, service/CMakeLists.txt, test/CMakeLists.txt, test/boost/CMakeLists.txt, test/lib/CMakeLists.txt, test/perf/CMakeLists.txt, tools/CMakeLists.txt, tracing/CMakeLists.txt, transport/CMakeLists.txt, utils/CMakeLists.txt
- build: cmake: extract more subsystem out into its own CMakeLists.txt
- build: cmake: remove swagger_gen_files
- build: cmake: remove stale TODO comments
- build: cmake: expose scylla_gen_build_dir
- build: cmake: link against cryptopp
- build: cmake: add missing source to utils
- build: cmake: move lib sources into test-lib
- build: cmake: add test/perf
=> cmake: sync with `configure.py` (8/n)

db/commitlog/commitlog.cc
Fixes #12810
We did not update total_size_on_disk in commitlog totals when use o_dsync was off.
This means we essentially ran with no registered footprint, also causing broken comparisons in delete_segments.
=> commitlog: Fix updating of total_size_on_disk on segment alloc when o_dsync is off

db/batchlog_manager.cc, db/batchlog_manager.hh, db/commitlog/commitlog_replayer.cc, db/commitlog/commitlog_replayer.hh, db/system_keyspace.cc, db/system_keyspace.hh, main.cc, test/boost/commitlog_test.cc, test/boost/database_test.cc, test/boost/view_build_test.cc, test/boost/virtual_reader_test.cc, test/lib/cql_test_env.cc, test/lib/cql_test_env.hh
There are two places that do it -- commitlog and batchlog replayers. Both can have local system-keyspace reference and use system-keyspace local query-processor for it. The peering save_truncation_record() is not that simple and is not patched by this PR
=> Remove qctx from helpers that retrieve truncation record

db/config.cc, db/config.hh, service/storage_service.cc, service/storage_service.hh
This patch fixes a problem which affects decommission and removenode
which may lead to data consistency problems under conditions which
lead one of the nodes to unliaterally decide to abort the node
operation without the coordinator noticing.
If this happens during streaming, the node operation coordinator would
proceed to make a change in the gossiper, and only later dectect that
one of the nodes aborted during sending of decommission_done or
removenode_done command. That's too late, because the operation will
be finalized by all the nodes once gossip propagates.
It's unsafe to finalize the operation while another node aborted. The
other node reverted to the old topolgy, with which they were running
for some time, without considering the pending replica when handling
requests. As a …
=> storage_service: Make node operations safer by detecting asymmetric abort

alternator/executor.cc, alternator/streams.cc, api/api.cc, api/authorization_cache.cc, api/cache_service.cc, api/column_family.cc, api/commitlog.cc, api/compaction_manager.cc, api/config.cc, api/endpoint_snitch.cc, api/error_injection.cc, api/failure_detector.cc, api/gossiper.cc, api/hinted_handoff.cc, api/lsa.cc, api/messaging_service.cc, api/storage_proxy.cc, api/storage_service.cc, api/stream_manager.cc, api/system.cc, api/task_manager.cc, api/task_manager_test.cc
- api: reference httpd::* symbols like 'httpd::*'
- alternator: using chrono_literals before using it
- api: s/request/http::request/
the last two commits were inspired Pavel's comment of
> It looks like api/ code was caught by some using namespace seastar::httpd shortcut.
they should be landed before we merge and include https://github.com/scylladb/seastar/pull/1536 in Scylla.
=> api: s/request/http::request/

replica/distributed_loader.cc
- distributed_loader: print log without using fmt::format()
- distributed_loader: correct a typo in comment
=> distributed_loader: print log without using fmt::format() and fix of typo

dist/common/scripts/scylla_raid_setup
Just like 4a8ed4c, we also need to wait for udev event completion to
create /dev/disk/by-uuid/$UUID for newly formatted disk, to mount the
disk just after formatting.
Also added code to check make sure uuid and uuid based device path are valid.
Fixes #11359
=> scylla_raid_setup: prevent mount failed for /var/lib/scylla for branch-5.0

cql3/statements/cas_request.cc, test/cql-pytest/test_unset.py
This is another attempt to fix #13001 on `branch-5.1`.
In #13001 we found a test case which causes a crash on `branch-5.1` because it didn't handle `UNSET_VALUE` properly:
```python3
def test_unset_insert_where(cql, table2):
p = unique_key_int()
stmt = cql.prepare(f'INSERT INTO {table2} (p, c) VALUES ({p}, ?)')
with pytest.raises(InvalidRequest, match="unset"):
cql.execute(stmt, [UNSET_VALUE])
def test_unset_insert_where_lwt(cql, table2):
p = unique_key_int()
stmt = cql.prepare(f'INSERT INTO {table2} (p, c) VALUES ({p}, ?) IF NOT EXISTS')
with pytest.raises(InvalidRequest, match="unset"):
cql.execute(stmt, [UNSET_VALUE])
```
This problem has been fixed on `master` by PR #12517. I tried to backport it to `branch-5.1` (#13029), but this didn't go well - it was a big change that touched a …
=> [branch-5.1] - minimal fix for crash caused by empty primary key range in LWT update

sstables/sstable_directory.cc, sstables/sstable_directory.hh
- sstables: sstable_directory: avoid unnecessarily constructing tuple<> from pair<>
- sstables: sstable_directory: add type constraints
=> sstables: sstable_directory: avoid unnecessarily constructing tuple<> from pair<>

cql3/expr/prepare_expr.cc, test/boost/expr_test.cc, test/cql-pytest/test_cast.py
CQL supports type casting using C-style casts.
For example it's possible to do: `blob_column = (blob)funcReturningInt()`
This functionality is pretty limited, we only allow such casts between types that have a compatible binary representation. Compatible means that the bytes will stay unchanged after the conversion.
This means that it's legal to cast an int to blob (int is just a 4 byte blob), but it's illegal to cast a bigint to int (change 4 bytes -> 8 bytes).
This simplifies things, to cast we can just reinterpret the value as the other type.
Another use of C-style casts are type hints. Sometimes it's impossible to infer the exact type of an expression from the context. In such cases the type can be specified by casting the expression to this type.
For example: …
=> cql3: improve support for C-style parenthesis casts

test/cql-pytest/test_lwt.py
Adds two test cases which test what happens when we perform an LWT UPDATE, but the partition/clustering key has 0 possible values. This can happen e.g when a column is supposed to be equal to two different values (`c = 0 AND c = 1`).
Empty partition ranges work properly, empty clustering range currently causes a crash (#13129).
I added tests for both of these cases.
=> cql-pytest/lwt_test: test LWT UPDATE when partition/clustering ranges are empty

auth/permission.cc, auth/permission.hh, auth/resource.cc, auth/resource.hh, auth/service.cc, cql3/Cql.g, cql3/cql3_type.hh, cql3/selection/abstract_function_selector.hh, cql3/selection/selection.cc, cql3/selection/selection.hh, cql3/statements/authorization_statement.cc, cql3/statements/authorization_statement.hh, cql3/statements/create_function_statement.cc, cql3/statements/function_statement.cc, cql3/statements/function_statement.hh, cql3/statements/list_permissions_statement.cc, cql3/statements/permission_altering_statement.cc, cql3/statements/select_statement.cc, db/cql_type_parser.cc, db/cql_type_parser.hh, service/client_state.cc, service/client_state.hh, test/boost/schema_change_test.cc, test/boost/user_function_test.cc, test/cql-pytest/test_permissions.py
This series aims to allow users to set permissions on user-defined functions.
The implementation is based on Cassandra's documentation and should be fully compatible: https://cassandra.apache.org/doc/latest/cassandra/cql/security.html#cql-permissions
Fixes: #5572
Fixes: #10633
=> Allow setting permissions for user-defined functions

CMakeLists.txt, compaction/CMakeLists.txt, cql3/CMakeLists.txt, data_dictionary/CMakeLists.txt, db/CMakeLists.txt, index/CMakeLists.txt, repair/CMakeLists.txt, replica/CMakeLists.txt, service/CMakeLists.txt, sstables/CMakeLists.txt, test/boost/CMakeLists.txt, test/lib/CMakeLists.txt, transport/CMakeLists.txt, utils/CMakeLists.txt
- build: cmake: remove test which does not exist yet
- build: cmake: document add_scylla_test()
- build: cmake: extract index, repair and data_dictionary out
- build: cmake: extract scylla-main out
- build: cmake: find Snappy before using it
- build: cmake: add missing linkages
- build: cmake: add missing sources to test-lib
- build: cmake: link sstables against libdeflate
- build: cmake: link Boost::regex against ICU::uc
=> cmake: sync with `configure.py` (11/n)

db/large_data_handler.cc, replica/database.cc
The `database::stop` method is sometimes hanging and it's always hard to spot where exactly it sleeps. Few more logging messages would make this much simpler.
refs: #13100
refs: #10941
=> Improve database shutdown verbosity

CMakeLists.txt, cmake/limit_jobs.cmake, rust/CMakeLists.txt, test/boost/CMakeLists.txt, test/lib/CMakeLists.txt, utils/CMakeLists.txt
this is the 12nd changeset of a series which tries to give an overhaul to the CMake building system. this series has two goals:
- to enable developer to use CMake for building scylla. so they can use tools (CLion for instance) with CMake integration for better developer experience
- to enable us to tweak the dependencies in a simpler way. a well-defined cross module / subsystem dependency is a prerequisite for building this project with the C++20 modules.
this changeset includes following changes:
- build: cmake: remove Seastar from the option name
- build: cmake: add missing sources in test-lib and utils
- build: cmake: do not include main.cc in scylla-main
- build: cmake: define SEASTAR_TESTING_MAIN for SEASTAR tests
- build: cmake: add more tests
=> cmake: sync with `configure.py` (12/n)

replica/distributed_loader.cc, sstables/sstable_directory.cc, sstables/sstable_directory.hh, sstables/sstables.cc, sstables/sstables.hh, test/boost/sstable_resharding_test.cc
Today, the SSTable generation provides a hint on which shard owns a
particular SSTable. That hint determines which shard will load the
SSTable into memory.
With upcoming UUID generation, we will no longer have this hint
embedded into the SSTable generation, meaning that SSTables will be
loaded at random shards. This is not good because shards will have
to reference memory from other shards to access the SSTable
metadata that was allocated elsewhere.
This patch changes sstable_directory to:
1) Use generation value to only determine which shard will calculate
the owner shards for SSTables. Essentially works like a round-robin
distribution.
2) The shard assigned to compute the owners for a SSTable will do
so reading the minimum from disk, usually only Scylla file is
needed.
3) Once that …
=> Load SSTable at the shard that actually own it

gms/gossiper.cc, gms/gossiper.hh, repair/repair.cc, repair/repair.hh, repair/row_level.hh, service/storage_service.cc, service/storage_service.hh
This series handles errors when aborting node operations and prints them rather letting them leak and be exposed to the user.
Also, cleanup the node_ops logging formats when aborting different node ops
and add more error logging around errors in the "worker" nodes.
=> Do not mask node operation errors

db/schema_tables.cc, db/system_distributed_keyspace.cc, db/system_distributed_keyspace.hh, db/system_keyspace.cc, db/system_keyspace.hh, replica/database.cc, replica/database.hh, replica/distributed_loader.cc, schema/schema.cc, schema/schema.hh, schema/schema_builder.hh
Our end goal (#12642) is to mark raft tables to use
schema commitlog. There are two similar
cases in code right now - `with_null_sharder`
and `set_wait_for_sync_to_commitlog` `schema_builder`
methods. The problem is that if we need to
mark some new schema with one of these methods
we need to do this twice - first in
a method describing the schema
(e.g. `system_keyspace::raft()`) and second in the
function `create_table_from_mutations`, which is not
obvious and easy to forget.
`create_table_from_mutations` is called when schema object
is reconstructed from mutations, `with_null_sharder`
and `set_wait_for_sync_to_commitlog` must be called from it
since the schema properties they describe are
not included in the mutation representation of the schema.
This series proposes to distinguish …
=> Refactor schema, introduce schema_static_props and move several properties into it

docs/getting-started/os-support.rst
Fixes https://github.com/scylladb/scylladb/issues/13138 
Fixes https://github.com/scylladb/scylladb/issues/13153
This PR:
- Fixes outdated information about the recommended OS. Since version 5.2, the recommended OS should be Ubuntu 22.04 because that OS is used for building the ScyllaDB image.
- Adds the OS support information for version 5.2.
This PR (both commits) needs to be backported to branch-5.2.
=> doc: Updates the recommended OS to be Ubuntu 22.04

CMakeLists.txt, cmake/limit_jobs.cmake, test/boost/CMakeLists.txt, test/lib/CMakeLists.txt
this is the 13rd changeset of a series which tries to give an overhaul to the CMake building system. this series has two goals:
- to enable developer to use CMake for building scylla. so they can use tools (CLion for instance) with CMake integration for better developer experience
- to enable us to tweak the dependencies in a simpler way. a well-defined cross module / subsystem dependency is a prerequisite for building this project with the C++20 modules.
this changeset includes following changes:
- build: cmake: increase per link job mem to 4GiB
- build: cmake: add missing sources to test-lib
- build: cmake: add more tests
- build: cmake: remote quotes in "include()" commands
- build: cmake: drop unnecessary linkages
=> cmake: sync with `configure.py` (13/n)

reader_concurrency_semaphore.cc, reader_concurrency_semaphore.hh, reader_permit.hh, readers/flat_mutation_reader_v2.hh, readers/multishard.hh, replica/database.cc, scylla-gdb.py, sstables/mx/reader.cc, test/boost/querier_cache_test.cc, test/boost/reader_concurrency_semaphore_test.cc, test/manual/sstable_scan_footprint_test.cc
A read that requested memory and has to wait for it can be registered as inactive. This can happen for example if the memory request originated from a background I/O operation (a read-ahead maybe).
Handling this case is currently very difficult. What we want to do is evict such a read on-the-spot: the fact that there is a read waiting on memory means memory is in demand and so inactive reads should be evicted. To evict this reader, we'd first have to remove it from the memory wait list, which is almost impossible currently, because `expiring_fifo<>`, the type used for the wait list, doesn't allow for that. So in this PR we set out to make this possible first, by transforming all current queues to be intrusive lists of permits. Permits are already linked into an intrusive list, to allow …
=> reader_concurrency_semaphore: handle read blocked on memory being registered as inactive

reader_concurrency_semaphore.cc, reader_permit.hh, test/boost/reader_concurrency_semaphore_test.cc
This PR backports https://github.com/scylladb/scylladb/commit/2f4a7934570cfb035c928c58d716ab838fb69109 to branch-5.2. Said patch depends on some other patches that are not part of any release yet.
This PR should apply to 5.1 and 5.0 too.
=> [backport]  reader_concurrency_semaphore:: clear_inactive_reads(): defer evicting to evict()

reader_concurrency_semaphore.cc, reader_permit.hh, test/boost/reader_concurrency_semaphore_test.cc
This PR backports https://github.com/scylladb/scylladb/commit/2f4a7934570cfb035c928c58d716ab838fb69109 to branch-5.1. Said patch depends on some other patches that are not part of any release yet.
=> [backport] reader_concurrency_semaphore:: clear_inactive_reads(): defer evicting to evict() 

data_dictionary/data_dictionary.cc, data_dictionary/keyspace_metadata.hh, replica/database.cc, replica/database.hh, replica/table.cc, test/boost/mutation_test.cc, test/boost/sstable_3_x_test.cc, test/boost/sstable_compaction_test.cc, test/lib/test_services.cc, test/perf/perf_sstable.hh
The `storage_options` describes where sstables should be located. Currently the object reside on keyspace_metadata, but is thus not available at the place it's needed the most -- the `table::make_sstable()` call. This set converts keyspace_metadata::storage_opts to be lw-shared-ptr and shares the ptr with class table.
refs: #12523 (detached small change from large PR)
=> Give table a reference to storage_options

repair/repair.cc
While repair requested by user is performed, some tables 
may be dropped. When the repair proceeds to these tables, 
it should skip them and continue with others.
When no_such_column_family is thrown during user requested 
repair, it is logged and swallowed. Then the repair continues with 
the remaining tables.
Fixes: #13045
=> Ignore no such column family in repair

replica/database.hh, sstables/sstables.hh, sstables/sstables_manager.hh, test/boost/database_test.cc, test/boost/mutation_reader_test.cc, test/boost/reader_concurrency_semaphore_test.cc, test/boost/schema_changes_test.cc, test/boost/sstable_3_x_test.cc, test/boost/sstable_compaction_test.cc, test/boost/sstable_datafile_test.cc, test/boost/sstable_directory_test.cc, test/boost/sstable_mutation_test.cc, test/boost/sstable_resharding_test.cc, test/boost/sstable_test.hh, test/lib/sstable_test_env.hh, test/lib/sstable_utils.cc, test/lib/sstable_utils.hh, test/lib/test_services.cc, test/lib/test_services.hh, test/perf/perf_sstable.hh
This series cleans up unit test in preparation for PR #12994.
Helpers are added (or reused) to not rely on specific sstable generation numbers where possible (other than loading reference sstables that are committed to the repo with given generation numbers), and to generate the sstables for tests easily, taking advantage of generation management in `sstable_test_env`, `table_for_tests`, or `replica::table` itself.
=> Unit tests cleanup for sstable generation changes

reader_concurrency_semaphore.cc, reader_concurrency_semaphore.hh, test/boost/reader_concurrency_semaphore_test.cc
Remove redundant "Total: ..." line.
Include the entire `reader_concurrency_semaphore::stats` in the printout. This includes a lot of metrics not exported to monitoring. These metrics are very valuable when debugging timeouts but are otherwise uninteresting. To avoid bloating our monitoring with such niche metrics, we dump them when they are interesting: when timeouts happen. To be really helpful, we do need historic values too, but this shouldn't be a problem: timeouts come in bursts, we usually get at least a handful of diagnostics dumps at a time.
New stats are also added to record the reason why reads are queued on the semaphore.
Printout before:
```
INFO  2023-03-14 12:43:54,496 [shard 0] reader_concurrency_semaphore - Semaphore test_reader_concurrency_semaphore_memory_limit_no_leaks …
```
=> reader_concurrency_semaphore: improve diagnostics printout

cql3/statements/permission_altering_statement.cc
Currently, when granting a permission on a funciton resource, we only check if the function exists, regardless of whether it's a user or a builtin function. We should not support altering permissions on builtin functions, so this patch adds a check for confirming that the found function is not builtin.
Additionally, adjust an error exception thrown when trying to alter a permission that does not apply on a given resource
=> cql: check if the function is builtin when granting permissisons

db/sstables-format-selector.cc, gms/feature_service.cc, sstables/sstables.cc, sstables/sstables.hh, sstables/version.hh, test/boost/sstable_datafile_test.cc, test/lib/cql_test_env.cc, test/perf/memory_footprint_test.cc
There's a need to convert both -- version and format -- to string and back. Currently, there's a disperse set of helpers in sstables/ code doing that and this PR brings some other to it
- adds fmt::formatter<> specialization for both types
- leaves one set of {format|version}_from_string() helpers converting any string-ish object into value
refs: #12523
=> Sanitize {format_types|version_types} to/from string converters

db/system_keyspace.cc, db/system_keyspace.hh, gms/feature_service.cc, gms/feature_service.hh, gms/gossiper.cc, test/lib/cql_test_env.cc, tools/schema_loader.cc
There was an attempt to cut feature-service -> system-keyspace dependency (#13172) which turned out to require more changes. Here's a preparation squeezing from this future work.
This set 
- leaves only batch-enabling API in feature service
- keeps the need for async context in feature service
- narrows down system keyspace features API to only load and store records
- relaxes features updating logic in sys.ks.
- cosmetic
=> Clean enabled features manipulations in system keyspace

multishard_mutation_query.cc, readers/multishard.cc, readers/multishard.hh, replica/database.cc, test/boost/multishard_mutation_query_test.cc, test/lib/reader_lifecycle_policy.hh
When creating the reader, the lifecycle policy might return one that was saved on the last page and survived in the cache. This reader might have skipped some fast-forwarding ranges while sitting in the cache. To avoid using a reader reading a stale range (from the read's POV), check its read range and fast forward it if necessary.
Fixes: https://github.com/scylladb/scylladb/issues/12916
=> readers/multishard: shard_reader: fast-forward created reader to current range

dist/redhat/scylla.spec
s/%{version}/%{version}-%{release}/ in `Requires:` sections.
this enforces the runtime dependencies of exactly the same releases between scylla packages.
Fixes #13222
=> dist/redhat: enforce dependency on %{release} also

mutation/mutation_fragment.cc, mutation/mutation_fragment_v2.hh, mutation/range_tombstone.cc, mutation/range_tombstone.hh, mutation/range_tombstone_list.cc, test/boost/range_tombstone_list_test.cc
this is a part of a series migrating from `operator<<(ostream&, ..)` based formatting to fmtlib based formatting. the goal here is to enable fmtlib to print `range_tombstone` and `range_tombstone_change` without using ostream<<. also, this change removes all existing callers of `operator<<(ostream, const range_tombstone &)` and `operator<<(ostream, const range_tombstone_change &)`, and then removes these two `operator<<`s.
Refs #13245
=> mutation: replace operator<<(.., const range_tombstone&) with fmt formatter

service/storage_service.cc, service/storage_service.hh
The `wait_for_normal_state_handled_on_boot` function waits until
`handle_state_normal` finishes for the given set of nodes. It was used
in `run_bootstrap_ops` and `run_replace_ops` to wait until NORMAL states
of existing nodes in the cluster are processed by the joining node
before continuing the joining process. One reason to do it is because at
the end of `handle_state_normal` the joining node might drop connections
to the NORMAL nodes in order to reestablish new connections using
correct encryption settings. In tests we observed that the connection
drop was happening in the middle of repair/streaming, causing
repair/streaming to abort.
Unfortunately, calling `wait_for_normal_state_handled_on_boot` in
`run_bootstrap_ops`/`run_replace_ops` is too late to fix all problems.
Before either …
=> storage_service: wait for normal state handlers earlier in the boot procedure

raft/server.cc
at least, we need to access the declarations of exceptions, like`not_a_leader` and `dropped_entry`, so, instead of relying on other header to do this job for us, we should include the header which include the declaration. so, in this chance "raft.h" is include explicitly. also, include boost headers using "<path/to/header>` instead of "path/to/header` for more consistency.
=> raft: includes used header and use <path/to/header> for include boost headers

db/schema_tables.cc, db/system_keyspace.cc, db/system_keyspace.hh, main.cc, replica/database.cc, replica/database.hh, replica/distributed_loader.cc, replica/distributed_loader.hh, schema/schema.hh, test/lib/cql_test_env.cc, test/pylib/internal_types.py, test/pylib/manager_client.py, test/pylib/scylla_cluster.py, test/topology_raft_disabled/test_raft_upgrade.py
We need this so that we can have multi-partition mutations which are applied atomically. If they live on different shards, we can't guarantee atomic write to the commitlog.
Fixes: #12642
=> Raft, use schema commit log

api/storage_service.cc, compaction/task_manager_module.cc, compaction/task_manager_module.hh, test/rest_api/test_compaction_task.py
Task manager task implementations of classes that cover
cleanup keyspace compaction which can be started through 
/storage_service/keyspace_compaction/ api.
Top level task covers the whole compaction and creates child
tasks on each shard.
=> Cleanup keyspace compaction task

thrift/controller.cc
This is used for readiness API: /storage_service/rpc_server and the fix prevents from returning 'true' prematurely.
Some improvement for readiness was added in a51529dd1547fe029e8c259f8b03891106f6edc0 but thrift implementation wasn't fully done.
Fixes https://github.com/scylladb/scylladb/issues/12376
=> thrift: return address in listen_addresses() only after server is ready

db/extensions.cc, db/extensions.hh, replica/database.cc, replica/distributed_loader.cc
The concept is needed by enterprise functionality, but in the hunt for globals this sticks out and should be removed.
This is also partially prompted by the need to handle the keyspaces in the above set special on shutdown as well as startup. I.e. we need to ensure all user keyspaces are flushed/closed earlier then these. I.e. treat as "system" keyspace for this purpose.
These changes adds a "extension internal" keyspace set instead, which for now (until enterprise branches are updated) also included the "load_prio" set. However, it changes distributed loader to use the extension API interface instead, as well as adds shutdown special treatment to replica::database.
=> Get rid of global variable "load_prio_keyspaces" (step 1)

cmake/mode.RELEASE.cmake, idl/CMakeLists.txt, service/CMakeLists.txt, test/boost/CMakeLists.txt, test/perf/CMakeLists.txt
this is the 15th changeset of a series which tries to give an overhaul to the CMake building system. this series has two goals:
- to enable developer to use CMake for building scylla. so they can use tools (CLion for instance) with CMake integration for better developer experience
- to enable us to tweak the dependencies in a simpler way. a well-defined cross module / subsystem dependency is a prerequisite for building this project with the C++20 modules.
this changeset includes following changes:
- build: cmake: add two missing tests
- build: cmake: port more cxxflags from configure.py
=> cmake: sync with `configure.py` (15/n)

api/api.hh, api/failure_detector.cc, api/messaging_service.cc, api/storage_service.cc, api/stream_manager.cc, bytes.cc, bytes.hh, gms/gossip_digest.hh, gms/inet_address.cc, gms/inet_address.hh, init.cc, message/messaging_service.cc
this is a part of a series migrating from `operator<<(ostream&, ..)` based formatting to fmtlib based formatting. the goal here is to enable fmtlib to print `bytes` and `gms::inet_address` without using ostream<<. also, this change removes all existing callers of `operator<<(ostream, const bytes &)` and `operator<<(ostream, const gms::inet_address&)`.
`gms::inet_address` related changes are included here in hope to demonstrate the usage of delimiter specifier of `fmt_hex` 's formatter.
Refs #13245
=> bytes, gms: replace operator<<(..) with fmt formatter

auth/authenticated_user.cc, auth/authenticated_user.hh, cql3/authorized_prepared_statements_cache.hh
this is a part of a series migrating from `operator<<(ostream&, ..)` based formatting to fmtlib based formatting. the goal here is to enable fmtlib to print `authenticated_user` without using ostream<<. also, this change removes all existing callers of `operator<<(ostream, const authenticated_user&)`.
Refs #13245
=> auth: replace operator<<(..) with fmt formatter

db/schema_tables.hh, docs/operating-scylla/admin-tools/scylla-sstable.rst, test/cql-pytest/nodetool.py, test/cql-pytest/test_tools.py, tools/schema_loader.cc, tools/schema_loader.hh, tools/scylla-sstable.cc
`scylla-sstable` currently has two ways to obtain the schema:
* via a `schema.cql` file.
* load schema definition from memory (only works for system tables).
This meant that for most cases it was necessary to export the schema into a `CQL` format and write it to a file. This is very flexible. The sstable can be inspected anywhere, it doesn't have to be on the same host where it originates form. Yet in many cases the sstable *is* inspected on the same host where it originates from. In this cases, the schema is readily available in the schema tables on disk and it is plain annoying to have to export it into a file, just to quickly inspect an sstable file.
This series solves this annoyance by providing a mechanism to load schemas from the on-disk schema tables. Furthermore, an auto-detect …
=> tool/scylla-sstable: more flexibility in obtaining the schema

cql3/query_processor.cc, cql3/query_processor.hh, cql3/statements/create_function_statement.cc, db/schema_tables.cc, lang/wasm.cc, lang/wasm.hh, main.cc, replica/database.cc, replica/database.hh, test/boost/wasm_alloc_test.cc, test/boost/wasm_test.cc, test/lib/cql_test_env.cc
The wasm engine is moved from replica::database to the query_processor.
The wasm instance cache and compilation thread runner were already there,
but now they're also initialized in the query_processor constructor.
By moving the initialization to the constructor, we can now
be certain that all wasm-related objects (wasm instance cache,
compilation thread runner, and wasm engine, which was already
passed in the constructor) are initialized when we try to use
them because we have to use the query processor to access them
anyway.
The change is also motivated by the fact that we're planning
to take Wasm UDFs out of experimental, after which they should
stop getting special treatment.
=> Initialize Wasm together with query_processor

compound_compat.hh, sstables/index_entry.hh
this is a part of a series migrating from `operator<<(ostream&, ..)` based formatting to fmtlib based formatting. the goal here is to enable fmtlib to print `composite` and `composite_view` without using ostream<<. also, this change removes `operator<<(ostream, const composite&)` ,  `operator<<(ostream, const composite_view&)` along with their callers.
Refs #13245
=> compound_compat: replace operator<<(..) with fmt formatter 

HACKING.md, conf/scylla.yaml, db/config.cc, db/config.hh, dist/common/scripts/scylla_blocktune.py, dist/common/scripts/scylla_fstrim, dist/common/scripts/scylla_util.py, docs/operating-scylla/scylla-yaml.inc, main.cc, replica/database.cc, test/lib/cql_test_env.cc
The commitlog api originally implied that the commitlog_directory would contain files from a single commitlog instance. This is checked in segment_manager::list_descriptors, if it encounters a file with an unknown prefix, an exception occurs in `commitlog::descriptor::descriptor`, which is logged with the `WARN` level.
A new schema commitlog was added recently, which shares the filesystem directory with the main commitlog. This causes warnings to be emitted on each boot. This patch solves the warnings problem by moving the schema commitlog to a separate directory. In addition, the user can employ the new `schema_commitlog_directory` parameter to move the schema commitlog to another disk drive.
This is expected to be released in 5.3.
As #13134 (raft tables->schema commitlog) is also …
=> Schema commitlog separate dir

db/view/build_progress_virtual_reader.hh, index/built_indexes_virtual_reader.hh, replica/database.hh, sstables/mx/reader.cc
That's courtersy of https://github.com/raphaelsc/seastar/commit/153813d3b88f284fe135c8ac3c00d6777faad276, which annotates Seastar smart pointer classes with Clang's consumed attributes, to help Clang to statically spot use-after-move bugs.
=> Treewide use-after-move bug fixes

alternator/executor.cc, mutation/mutation_fragment.cc, mutation/position_in_partition.hh, partition_snapshot_row_cursor.hh
this is a part of a series migrating from `operator<<(ostream&, ..)` based formatting to fmtlib based formatting. the goal here is to enable fmtlib to print `position_in_partition` and `partition_region` without using ostream<<. also, this change removes `operator<<(ostream, const position_in_partition_view&)` ,  `operator<<(ostream, const partition_region&)` along with their callers.
Refs #13245
=>  mutation: replace operator<<(..) with fmt formatter

db/schema_tables.hh, docs/operating-scylla/admin-tools/scylla-sstable.rst, test/cql-pytest/nodetool.py, test/cql-pytest/test_tools.py, tools/schema_loader.cc, tools/schema_loader.hh, tools/scylla-sstable.cc
This PR reverts the scylla sstable schema loading improvements as they fail in CI every other run. I am already working on fixes for these but I am not sure I understand all the failures so it is best to revert and re-post the series later.
Fixes: #13404
Fixes: #13410
=> Revert scylla sstable schema improvements

sstables/sstables.cc, sstables/writer.hh
Writing into sstable component output stream should be done with care. In particular -- flushing can happen only once right before closing the  stream. Flushing the stream in between several writes is not going to work, because file stream would step on unaligned IO and S3 upload stream would send completion message to the server and would lose any  subsequent write.
Most of the file_writer users already obey that and flush the writer once right before closing it. The do_write_simple() is extra careful about exceptions handling, but it's an overkill (see first patch).
It's better to make file_writer API explicitly lack the ability to flush itself by flushing the stream when closing the writer.
=> Remove explicit flush() from sstable component writer

compaction/compaction_manager.cc, compaction/compaction_manager.hh, replica/table.cc
A problem in compaction reevaluation can cause the SSTable set to be left uncompacted for indefinite amount of time, potentially causing space and read amplification to be suboptimal.
Two revaluation problems are being fixed, one after off-strategy compaction ended, and another in compaction manager which intends to periodically reevaluate a need for compaction. 
Fixes https://github.com/scylladb/scylladb/issues/13429.
Fixes https://github.com/scylladb/scylladb/issues/13430.
=> Compaction reevaluation bug fixes

db/system_keyspace.cc, db/system_keyspace.hh, service/raft/raft_group0_client.cc, service/storage_service.cc
The system_keyspace.hh now includes raft stuff, topology changes stuff, task_manager stuff, etc. It's going to include tablets.hh (but maybe not). Anything that deals with system keyspace, and includes system_keyspace.hh, would transitively pull these too. This header is becoming a central hub for all the features.
This PR removes all the headers from system_keyspace.hh that correspond to other "subsystems" keeping only generic mutations/querying and seastar ones.
=> Debloat system_keyspace.hh (and a bit of .cc)

service/storage_service.cc, service/storage_service.hh
Use token_metadata get_endpoint_to_host_id_map_for_reading
to get all normal token owners for all node operations,
rather than using gossip for some operation and
token_metadata for others.
Fixes #12862
=> Standardize node ops sync_nodes selection

cql3/cql3_type.cc, cql3/statements/create_keyspace_statement.cc, cql3/statements/create_table_statement.cc, cql3/statements/index_target.cc, cql3/statements/index_target.hh, db/commitlog/commitlog.cc, duration.cc, index/secondary_index.cc, sstables/sstables.cc, test/boost/cql_query_test.cc, thrift/thrift_validation.cc, types/types.cc, utils/config_file_impl.hh
Except for where usage of `std::regex` is required by 3rd party library interfaces.
As demonstrated countless times, std::regex's practice of using recursion for pattern matching can result in stack overflow, especially on AARCH64. The most recent incident happened after merging https://github.com/scylladb/scylladb/pull/13075, which (indirectly) uses `sstables::make_entry_descriptor()` to test whether a certain path is a valid scylla table path in a trial-and-error manner. This resulted in stacks blowing up in AARCH64.
To prevent this, use the already tried and tested method of switching from `std::regex` to `boost::regex`. Don't wait until each of the `std::regex` sites explode, replace them all preemptively.
Refs: https://github.com/scylladb/scylladb/issues/13404
=> tree: migrate from std::regex to boost::regex

sstables/sstables.cc, sstables/types.hh, tools/scylla-sstable.cc
SSTable summary is one of the components fully loaded into memory that may have a significant footprint.
This series reduces the summary footprint by reducing the amount of token information that we need to keep
in memory for each summary entry.
Of course, the benefit of this size optimization is proportional to the amount of summary entries, which
in turn is proportional to the number of partitions in a SSTable.
Therefore we can say that this optimization will benefit the most tables which have tons of small-sized
partitions, which will result in big summaries.
Results:
```
BEFORE
[1000000  pkeys]		 data size: 	4035888890,  summary -> memory footprint: 	5843232,  entries: 88158
[10000000 pkeys]		 data size: 	40368888890, summary -> memory footprint: 	55787128, entries: 844925
AFTER …
```
=> Reduce memory footprint of SSTable index summary

db/config.cc, db/config.hh, main.cc
This series adds an option to read the relabel config from file.
Most of Scylla's metrics are reported per-shard, some times they are also reported per scheduling
groups or per tables.  With modern hardware, this can quickly grow to a large number of metrics that 
overload Scylla and the  collecting server. 
One of the main issues around metrics reduction is that many of the metrics are only
helpful in certain situations.
For example, Scylla monitoring only looks at a subset of the metrics. So in large deployments
it would be helpful to scrap only those.
An option to do that, would be to mark all dashboards related metrics with a label value, and then Prometheus
will request only metrics with that label value.
There are two main limitations to scrap by label values:
1. some of the metrics …
=> Metrics relabel from file

alternator/executor.cc, alternator/ttl.cc, db/tags/utils.cc, db/tags/utils.hh, service/migration_manager.hh, test/alternator/test_tag.py
Alternator's implementation of TagResource, UntagResource and UpdateTimeToLive (the latter uses tags to store the TTL configuration) was unsafe for concurrent modifications - some of these modifications may be lost. This short series fixes the bug, and also adds (in the last patch) a test that reproduces the bug and verifies that it's fixed.
The cause of the incorrect isolation was that we separately read the old tags and wrote the modified tags. In this series we introduce a new function, `modify_tags()` which can do both under one lock, so concurrent tag operations are serialized and therefore isolated as expected.
Fixes #6389.
=> alternator: fix isolation of concurrent modifications to tags

mutation/mutation_fragment.cc, mutation/mutation_partition.cc, mutation/mutation_partition.hh, mutation/mutation_partition_v2.cc, mutation/tombstone.hh, partition_snapshot_row_cursor.hh, utils/to_string.hh
this is a part of a series to migrating from `operator<<(ostream&, ..)` based formatting to fmtlib based formatting. the goal here is to enable fmtlib to print `tombstone` and `shadowable_tombstone` without the help of fmt::ostream. and their `operator<<(ostream,..)` are dropped, as there are no users of them anymore.
Refs #13245
=> utils, mutation: replace operator<<(..) with fmt formatter

db/view/view.cc, locator/token_metadata.cc, locator/token_metadata.hh, locator/topology.cc, locator/topology.hh, service/storage_service.cc
Currently, token_metadata_impl maintains a "shadow" endpoint to host_id map on top of the maps in topology.
This series first reimplements the functions that currently use this map to use topology instead.
Then the important users of `get_endpoint_to_host_id_map_for_reading`: node_ops_ctl and view_builder
and converted to use a new `topology::for_each_node` function to process all nodes in topology directly, without going through `get_endpoint_to_host_id_map_for_reading`.
=> token_metadata: use topology nodes for endpoint_to_host_id map

db/view/view.cc, db/view/view.hh, replica/database.hh
There's a legacy safety check in view code that needs to find a base table from its schema ID. To do it it calls for global storage proxy instance. The comment says that this code can be removed once computes_column feature is known by everyone. I'm not sure if that's the case, so here's more complicated yet less incompatible way to stop using global proxy instance.
=> Remove global proxy usage from view builder's value_getter

scripts/open-coredump.sh
Lately we have observed that some builds are missing the package_url in the build metadata. This is usually caused by changes in how build metadata is stored on the servers and the s3 reloc server failing to dig them out of the metadata files. A user can usually still obtain the package url but currently there is no way to plug in user-obtained scylla package into the script's workflow.
This PR fixes this by allowing the user to provide the package as `$ARTIFACT_DIR/scylla.package` (in unpacked form).
=> scripts/open-coredump.sh: allow user to plug in scylla package

db/schema_tables.hh, docs/operating-scylla/admin-tools/scylla-sstable.rst, test/cql-pytest/nodetool.py, test/cql-pytest/test_tools.py, tools/schema_loader.cc, tools/schema_loader.hh, tools/scylla-sstable.cc
scylla-sstable currently has two ways to obtain the schema:
* via a `schema.cql` file.
* load schema definition from memory (only works for system tables).
This meant that for most cases it was necessary to export the schema into a CQL format and write it to a file. This is very flexible. The sstable can be inspected anywhere, it doesn't have to be on the same host where it originates form. Yet in many cases the sstable is inspected on the same host where it originates from. In this cases, the schema is readily available in the schema tables on disk and it is plain annoying to have to export it into a file, just to quickly inspect an sstable file.
This series solves this annoyance by providing a mechanism to load schemas from the on-disk schema tables. Furthermore, an auto-detect …
=>  tool/scylla-sstable: more flexibility in obtaining the schema

docs/dev/reader-concurrency-semaphore.md, reader_concurrency_semaphore.cc, reader_permit.hh
The names of these states have been the source of confusion ever since they were introduced. Give them names which better reflects their true meaning and gives less room for misinterpretation. The changes are:
* active/unused  -> active
* active/used    -> active/need_cpu
* active/blocked -> active/await
Hopefully the new names do a better job at conveying what these states really mean:
* active - a regular admitted permit, which is active (as opposed to an inactive permit).
* active/need_cpu - an active permit which was marked as needing CPU for the read to make progress. This permit prevents admission of new permits while it is in this state.
* active/await - a former active/need_cpu permit, which has to wait on I/O or a remote shard. While in this state, it doesn't block the admission …
=> reader_permit: give better names to active* states

test/pylib/manager_client.py, test/pylib/random_tables.py, test/pylib/rest_client.py, test/topology/conftest.py, test/topology/test_mutation_schema_change.py, test/topology_custom/test_custom.py, test/topology_raft_disabled/test_raft_upgrade.py
Reproducers for https://github.com/scylladb/scylladb/issues/10770.
(Already fixed in https://github.com/scylladb/scylladb/commit/15ebd5907177ba8709bc40ad2fa9ae773a9cf674)
Includes necessary improvements and fixes to `pylib`.
=> test: reproducers for store mutation with schema change and host down

reader_concurrency_semaphore.cc, reader_concurrency_semaphore.hh, test/boost/reader_concurrency_semaphore_test.cc
The patch doesn't apply cleanly, so a targeted backport PR was necessary.
I also needed to cherry-pick two patches from https://github.com/scylladb/scylladb/pull/13255 that the backported patch depends on. Decided against backporting the entire https://github.com/scylladb/scylladb/pull/13255 as it is quite an intrusive change.
Fixes: https://github.com/scylladb/scylladb/issues/11803
=> Backport "reader_concurrency_semaphore: don't evict inactive readers needlessly" to branch-5.2

reader_concurrency_semaphore.cc, reader_concurrency_semaphore.hh, test/boost/reader_concurrency_semaphore_test.cc
The patch doesn't apply cleanly, so a targeted backport PR was necessary.
I also needed to cherry-pick two patches from https://github.com/scylladb/scylladb/pull/13255 that the backported patch depends on. Decided against backporting the entire https://github.com/scylladb/scylladb/pull/13255 as it is quite an intrusive change.
Fixes: https://github.com/scylladb/scylladb/issues/11803
=> Backport "reader_concurrency_semaphore: don't evict inactive readers needlessly" to branch-5.0

reader_concurrency_semaphore.cc, reader_concurrency_semaphore.hh, test/boost/reader_concurrency_semaphore_test.cc
The patch doesn't apply cleanly, so a targeted backport PR was necessary.
I also needed to cherry-pick two patches from https://github.com/scylladb/scylladb/pull/13255 that the backported patch depends on. Decided against backporting the entire https://github.com/scylladb/scylladb/pull/13255 as it is quite an intrusive change.
Fixes: https://github.com/scylladb/scylladb/issues/11803
=> Backport "reader_concurrency_semaphore: don't evict inactive readers needlessly" to branch-5.1

types/types.cc, utils/big_decimal.cc, utils/big_decimal.hh
in this series, we use <=> operator to replace `big_decimal::compare()` for better readability. also, we trade the chained ternary expression with a more verbose if-else statement for better performance and readability.
=> utils: big_decimal: optimize big_decimal::compare() and use <=> operator

db/system_keyspace.cc, db/system_keyspace.hh, service/storage_service.cc, service/storage_service.hh, service/topology_state_machine.hh
Add new columns to the `system.topology` table: `shard_count` and `ignore_msb`. When a node bootstraps or restarts and observes that the values stored in `topology` are different than the local values, it updates them. This is done in the `update_topology_with_local_metadata` function (the 'metadata' here being the two values).
Additional flag persisted in `system.scylla_local` is used to safely avoid performing read barriers when the values didn't change on node restart. A comment in `update_topology_with_local_metadata` explains why this flag is needed.
An example use case where `shard_count` and `ignore_msb` are needed is creating CDC generations.
Fixes: #13508
=> raft topology: store `shard_count` and `ignore_msb` in topology

alternator/server.cc, utils/aws_sigv4.cc, utils/aws_sigv4.hh
The AWS signature-generating code was moved from alternator some time ago as is. Now it's clear that in which places it should be extended to work for S3 client as well. The enhancements are
- Support UNSIGNED-PAYLOAD to omit calculating checksums for request body
- Include full URL path into the signature, not just hard-coded "/" string
- Don't check datastamp expiration if not asked for
This is a part of #13493
=> Extend aws_sigv4 code to suite S3 client needs

docs/using-scylla/tracing.rst
Fixes https://github.com/scylladb/scylla-doc-issues/issues/823.
This PR extends the note on the Tracing page to explain what is meant by setting the RF to ALL and adds a link for reference.
=> doc: extend the information about the recommended RF on the Tracing page

cql3/functions/aggregate_fcts.cc, test/cql-pytest/test_aggregate.py, test/cql-pytest/test_cast_data.py
This short PR fixes a bug in SUM() aggregation where if the data contains +Inf and -Inf the returned sum should be NaN but we returned an error instead. This is a recent regression uncovered by a dtest (see issue #13551), but in the first patch we add additional tests in the cql-pytest framework which reproduce this bug and explore various other areas (wrongly) implicated by the failing dtest.
Fixes #13551
=> cql:  allow SUM() aggregations which result in a NaN

compound.hh, cql3/expr/expression.cc, cql3/expr/prepare_expr.cc, cql3/functions/aggregate_fcts.cc, cql3/functions/as_json_function.hh, cql3/functions/bytes_conversion_fcts.hh, cql3/functions/castas_fcts.cc, cql3/functions/error_injection_fcts.cc, cql3/functions/functions.cc, cql3/functions/native_scalar_function.hh, cql3/functions/time_uuid_fcts.hh, cql3/functions/token_fct.hh, cql3/functions/user_function.cc, cql3/functions/user_function.hh, cql3/functions/uuid_fcts.hh, cql3/selection/abstract_function_selector.hh, cql3/selection/aggregate_function_selector.hh, db/functions/scalar_function.hh, keys.hh, lang/wasm.cc, lang/wasm.hh
Database functions currently receive their arguments as an std::vector. This
is inflexible (for example, one cannot use small_vector to reduce allocations).
This series adapts the function signature to accept parameters using std::span.
Some changes in the keys interface are needed to support this. Lastly, one call
site is migrated to small_vector.
This is in support of changing selectors to use expressions.
=> db, cql3: functions: switch argument passing to std::span

db/view/view.cc, db/view/view.hh, db/view/view_builder.hh, db/view/view_update_generator.hh, replica/database.hh, replica/table.cc, view_info.hh
The method needs proxy to get data_dictionary::database from to pass down to select_statement::prepare(). And a legacy bit that can come with data_dictionary::database as well. Fortunately, all the call traces that end up at select_statement() start inside table:: methods that have view_update_generator, or at view_builder::consumer that has reference to view_builder. Both services can share the database reference. However, the call traces in question pass through several code layers, so the PR adds data_dictionary::database to those layers one by one.
=> Remove global proxy usage from view_info::select_statement()

api/api.cc, api/api_init.hh, api/storage_proxy.cc, api/storage_proxy.hh, api/storage_service.cc, db/view/view.cc, main.cc
There are few places in the API handlers that call global proxy for their needs. Most of those places are easy to patch, because proxy is either at http_ctx thing right inside the handler code. Also there's a handler code in view_builder that needs proxy too, but it really needs topology, not proxy, and can get it elsewhere (the handler is coroutinized while at it)
=> Remove global proxy usage from API handlers

test/boost/s3_test.cc, test/lib/test_utils.hh, test/object_store/run, test/pylib/minio_server.py
The tests in question are using MINIO_SERVER_ADDRESS environment variable to export minio server address from pylib to test cases. Also they use hard-coded public bucket name. Both plays badly with AWS S3, the former due to MINIO_... in its name and the latter because public bucket name can be any.
So this PR puts address and public bucket name into S3_..._FOR_TEST environment variables and fixes output stream closure on failure while at it.
Detached from #13493
=> Tune up S3 unit tests environment usage (and a bit more)

test/topology/conftest.py
Remove unnecessary asyncio marker and re-introduce top level logger instance.
=> test/pylib: topology fix asyncio fixture and fix logger

dht/i_partitioner.hh, dht/token.cc, dht/token.hh
this is a part of a series to migrating from `operator<<(ostream&, ..)` based formatting to fmtlib based formatting. the goal here is to enable fmtlib to print `dht::token` without the help of `operator<<`.
the corresponding `operator<<()` is preserved in this change, as it has lots of users in this project, we will tackle them case-by-case in follow-up changes.
also, the forward declaration of `operator<<(ostream&, constdht::token&)` in `dht/i_partitioner.hh` is removed. ias it not necessary.
=> dht: specialize fmt::formatter<dht::token>

replica/database.hh, replica/distributed_loader.cc, replica/distributed_loader.hh
Backport of 4aa0b16852656ce11f13b78156fbf28cffbe8c1a to branch-5.0
Merge 'distributed_loader: detect highest generation before populating column families' from Benny Halevy
We should scan all sstables in the table directory and its
subdirectories to determine the highest sstable version and generation
before using it for creating new sstables (via reshard or reshape).
Otherwise, the generations of new sstables created when populating staging (via reshard or reshape) may collide with generations in the base directory, leading to https://github.com/scylladb/scylladb/issues/11789
\Refs https://github.com/scylladb/scylladb/issues/11789
\Fixes https://github.com/scylladb/scylladb/issues/11793
\Closes https://github.com/scylladb/scylladb/pull/11795
=> Backport 5.0 distributed loader detect highest generation

db/system_keyspace.cc, utils/UUID_gen.hh
in `make_group0_history_state_id_mutation`, when adding a new entry to
the group 0 history table, if the parameter `gc_older_than` is engaged,
we create a range tombstone in the mutation which deletes entries older
than the new one by `gc_older_than`. In particular if
`gc_older_than = 0`, we want to delete all older entries.
There was a subtle bug there: we were using millisecond resolution when
generating the tombstone, while the provided state IDs used microsecond
resolution. On a super fast machine it could happen that we managed to
perform two schema changes in a single millisecond; this happened
sometimes in `group0_test.test_group0_history_clearing_old_entries`
on our new CI/promotion machines, causing the test to fail because the
tombstone didn't clear the entry correspodning to …
=> db: system_keyspace: use microsecond resolution for group0_history range tombstone

cdc/generation.cc, cdc/generation.hh, cdc/generation_service.hh, db/system_distributed_keyspace.cc, db/system_keyspace.cc, db/system_keyspace.hh, docs/dev/cdc.md, idl/storage_service.idl.hh, main.cc, service/raft/group0_state_machine.cc, service/raft/group0_state_machine.hh, service/raft/raft_group0.cc, service/raft/raft_group0.hh, service/raft/raft_group0_client.cc, service/raft/raft_group0_client.hh, service/storage_service.cc, service/storage_service.hh, service/topology_state_machine.cc, service/topology_state_machine.hh, test/lib/cql_test_env.cc
Introduce a new table `CDC_GENERATIONS_V3` (`system.cdc_generations_v3`).
The table schema is a copy-paste of the `CDC_GENERATIONS_V2` schema. The
difference is that V2 lives in `system_distributed_keyspace` and writes to it
are distributed using regular `storage_proxy` replication mechanisms based on
the token ring.  The V3 table lives in `system_keyspace` and any mutations
written to it will go through group 0.
Extend the `TOPOLOGY` schema with new columns:
- `new_cdc_generation_data_uuid` will be stored as part of a bootstrapping
node's `ring_slice`, it stores UUID of a newly introduced CDC
generation which is used as partition key for the `CDC_GENERATIONS_V3`
table to access this new generation's data. It's a regular column,
meaning that every row (corresponding to a node) will have …
=> Manage CDC generations when bootstrapping nodes using Raft Group 0 topology coordinator

locator/topology.cc, locator/topology.hh, test/boost/locator_topology_test.cc, test/boost/network_topology_strategy_test.cc
Fixes a problem when raft-based topology is enabled, which loads
topology from storage. It starts by clearing topology and then adding
nodes one by one. Before this patch, this violates internal invariant
of topology object which puts the local node as the first node. This
would manifest by triggering an assert in topology::pop_node() which
throws if popping the node at index 0 in order to keep the information
about local node around. This is normally prevented by a check in
topology::remove_node() which avoid calling pop_node() if removing the
local node. But since there is no node which is marked as local, this
check allows the first node to be popped.
To fix the problem I lift the invariant that local node is always in
_nodes. We still have information about local node in config. …
=> Fix topology management when raft-based topology is enabled

main.cc, scylla-gdb.py, service/storage_proxy.cc, service/storage_proxy.hh, test/boost/schema_change_test.cc, test/lib/cql_test_env.cc, test/lib/cql_test_env.hh
All users of global proxy are gone (*), proxy can be made fully main/cql_test_env local.
(*) one test case still needs it, but can get it via cql_test_env
=> De-globalize storage proxy

replica/database.hh, replica/distributed_loader.cc, replica/table.cc, sstables/generation_type.hh, test/boost/database_test.cc, test/boost/sstable_test.cc, test/lib/sstable_test_env.hh
this is the first step to the uuid-based generation identifier. the goal is to encapsulate the generation related logic in generator, so its consumers do not have to understand the difference between the int64_t based generation and UUID v1 based generation.
this commit should not change the behavior of existing scylla. it just allows us to derive from `generation_generator` so we can have another generator which generates UUID based generation identifier.
=> sstables, replica: add generation generator

db/schema_tables.cc, locator/topology.cc
`seastar::current_backtrace()` can be quite heavey.
When we pass it to a log message in relatively detailed log_level
(debug/trace), we pay the price of `current_backtrace` every time,
but we rarely print the message.
=> Restrict logging of current_backtrace to log_level

test/boost/stall_free_test.cc, utils/stall_free.hh
This series adds handling of null std::unique_ptr to utils::clear_gently
and handling of std::optional and seastar::optimized_optional (both engaged and disengaged cases).
Also, unit tests were added to tests the above cases.
Fixes #13636
=> clear_gently: handle null unique_ptr and optional values

cql3/functions/functions.cc, cql3/functions/functions.hh, cql3/functions/user_aggregate.hh, cql3/statements/drop_function_statement.cc, cql3/statements/drop_type_statement.cc, db/schema_tables.cc, test/boost/user_types_test.cc, test/cql-pytest/test_uda.py, test/cql-pytest/util.py
This patch backports https://github.com/scylladb/scylladb/pull/12710 to branch-5.2. To resolve the conflicts that it's causing, it also includes
* https://github.com/scylladb/scylladb/pull/12680
* https://github.com/scylladb/scylladb/pull/12681
=> Backport bugfixes regarding UDT, UDF, UDA interactions to branch-5.2

test/object_store/run
when reading this source code, there are a handful issues reported by my flycheck plugin. none of them is critical, but better off fixing them.
=> test: object_store: fix various pylint warnings

bytes.hh, locator/abstract_replication_strategy.hh, test/boost/hashers_test.cc, utils/hashers.cc, utils/hashers.hh, utils/hashing.hh, utils/simple_hashers.hh
Consolidate `bytes_view_hasher` and abstract_replication_strategy `factory_key_hasher` which are the same into a reusable utils::basic_xx_hasher.
To be used in a followup series for netw:msg_addr.
=> utils: add basic_xx_hasher

cql3/expr/prepare_expr.cc, cql3/operation.cc, test/cql/lwt_test.result
Fix a few cases where instead of printing column names in error messages, we printed weird stuff like ASCII codes or the address of the name.
Fixes #13657
=> cql3: fix a few misformatted printouts of column names in error messages

cql3/operation.cc, dht/i_partitioner.cc, dht/range_streamer.cc, dht/token.cc, dht/token.hh, gms/inet_address.hh, repair/repair.cc, test/boost/UUID_test.cc, tombstone_gc.cc
std::rel_ops was deprecated in C++20, as C++20 provides a better solution for defining comparison operators. and all the use cases previously to be addressed by `using namespace std::rel_ops` have been addressed either by `operator<=>` or the default-generated `operator!=`.
so, in this series, to avoid using deprecated facilities, let's drop all these `using namespace std::rel_ops`. there are many more cases where we could either use `operator<=>` or the default-generated `operator!=` to simplify the implementation. but here, we care more about `std::rel_ops`, we will drop the most (if not all of them) of the explicitly defined `operator!=`  and other comparison operators later.
=> treewide:  stop using std::rel_ops

test/boost/reusable_buffer_test.cc, transport/request.hh, transport/response.hh, transport/server.cc, utils/fragmented_temporary_buffer.hh, utils/reusable_buffer.hh, zstd.cc
Common compression libraries work on contiguous buffers.
Contiguous buffers are a problem for the allocator. However, as long as they are short-lived,
we can avoid the expensive allocations by reusing buffers across tasks. 
This idea is already applied to the compression of CQL frames, but with some deficiencies.
`utils: redesign reusable_buffer` attempts to improve upon it in a few ways. See its commit message for an extended discussion.
Compression buffer reuse also happens in the zstd SSTable compressor, but the implementation is misguided. Every `zstd_processor` instance reuses a buffer, but each instance has its own buffer. This is very bad, because a healthy database might have thousands of concurrent instances (because there is one for each sstable reader). Together, the buffers …
=> utils: redesign reusable_buffer

db/system_keyspace.cc, service/storage_service.cc, service/topology_state_machine.cc, service/topology_state_machine.hh
We change the meaning and name of `replication_state`: previously it was meant
to describe the "state of tokens" of a specific node; now it describes the
topology as a whole - the current step in the 'topology saga'. It was moved
from `ring_slice` into `topology`, renamed into `transition_state`, and the
topology coordinator code was modified to switch on it first instead of node
state - because there may be no single transitioning node, but the topology
itself may be transitioning.
This PR was extracted from #13683, it contains only the part which refactors
the infrastructure to prepare for non-node specific topology transitions.
#13683 uses the infrastructure to implement operations around CDC generations.
=> raft topology: refactor the coordinator to allow non-node specific topology transitions

cmake/mode.common.cmake, configure.py, cql3/stats.hh, sstables/compress.cc, sstables/sstables.cc
this change silences the warning of `-Wmissing-braces` from
clang. in general, we can initialize an object without constructor
with braces. this is called aggregate initialization.
but the standard does allow us to initialize each element using
either copy-initialization or direct-initialization. but in our case,
neither of them applies, so the clang warns like
```
suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
options.elements.push_back({bytes(k.begin(), k.end()), bytes(v.begin(), v.end())});
^~~~~~~~~~~~~~~~~~~~~~~~~
{                        }
```
in this change,
also, take the opportunity to use structured binding to simplify the
related code.
=> treewide: reenable -Wmissing-braces

cql3/Cql.g, cql3/expr/expression.cc, cql3/expr/expression.hh, cql3/expr/prepare_expr.cc, cql3/expr/restrictions.cc, cql3/functions/functions.cc, cql3/functions/functions.hh, cql3/restrictions/statement_restrictions.cc, cql3/restrictions/statement_restrictions.hh, cql3/selection/selectable.cc, cql3/statements/modification_statement.cc, cql3/statements/select_statement.cc, test/boost/expr_test.cc, test/boost/statement_restrictions_test.cc, test/cql-pytest/test_filtering.py
Let's remove `expr::token` and replace all of its functionality with `expr::function_call`.
`expr::token` is a struct whose job is to represent a partition key token.
The idea is that when the user types in `token(p1, p2) < 1234`, this will be internally represented as an expression which uses `expr::token` to represent the `token(p1, p2)` part.
The situation with `expr::token` is a bit complicated.
On one hand side it's supposed to represent the partition token, but sometimes it's also assumed that it can represent a generic call to the `token()` function, for example `token(1, 2, 3)` could be a `function_call`, but it could also be `expr::token`.
The query planning code assumes that each occurence of expr::token
represents the partition token without checking the arguments.
Because of …
=> cql3/expr: remove expr::token

cdc/generation.cc, cdc/generation_id.hh, clocks-impl.cc, db_clock.hh
this is a part of a series to migrating from `operator<<(ostream&, ..)` based formatting to fmtlib based formatting. the goal here is to enable fmtlib to print `cdc::generation_id` and `db_clock::time_point` without the help of `operator<<`.
the formatter of `cdc::generation_id` uses that of `db_clock::time_point` , so these two commits are posted together in a single pull request.
the corresponding `operator<<()` is removed in this change, as all its callers are now using fmtlib for formatting now.
Refs #13245
=> cdc, db_clock: specialize fmt::formatter<{db_clock::time_point, generation_id}>

cdc/split.cc, compaction/compaction_state.hh, db/schema_tables.cc, locator/topology.hh, raft/server.cc, reader_concurrency_semaphore.cc
this series silences the warnings from GCC 13. some of these changes are considered as critical fixes, and posted separately.
see also #13243
=> treewide: fix warnings from GCC-13

compaction/compaction.cc, compaction/compaction_manager.cc, compaction/compaction_manager.hh, replica/database.hh, replica/distributed_loader.cc, replica/table.cc
This series fixes a few issues caused by f1bbf705f9b6faa406baac04f418a93b09a53c19
(f1bbf705f9b6faa406baac04f418a93b09a53c19):
- table, compaction_manager: prevent cross shard access to owned_ranges_ptr
- Fixes #13631 
- distributed_loader: distribute_reshard_jobs: pick one of the sstable shard owners
- compaction: make_partition_filter: do not assert shard ownership
- allow the filtering reader now used during resharding to process tokens owned by other shards
=> Do not access owned_ranges_ptr across shards in update_sstable_cleanup_state

compaction/compaction_manager.cc, compaction/table_state.hh, replica/compaction_group.hh, replica/table.cc, test/lib/test_services.cc
In many cases we trigger offstrategy compaction opportunistically
also when there's nothing to do.  In this case we still print
to the log lots of info-level message and call
`run_offstrategy_compaction` that wastes more cpu cycles
on learning that it has nothing to do.
This change bails out early if the maintenance set is empty
and prints a "Skipping off-strategy compaction" message in debug
level instead.
Fixes #13466
Also, add an group_id class and return it from compaction_group and table_state.
Use that to identify the compaction_group / table_state by "ks_name.cf_name compaction_group=idx/total" in log messages.
Fixes #13467
=> Tone down offstrategy log message

alternator/serialization.cc, alternator/serialization.hh, configure.py, test/alternator/test_number.py, test/boost/alternator_unit_test.cc
DynamoDB limits the allowed magnitude and precision of numbers - valid
decimal exponents are between -130 and 125 and up to 38 significant
decimal digitst are allowed. In contrast, Scylla uses the CQL "decimal"
type which offers unlimited precision. This can cause two problems:
1. Users might get used to this "unofficial" feature and start relying
on it, not allowing us to switch to a more efficient limited-precision
implementation later.
2. If huge exponents are allowed, e.g., 1e-1000000, summing such a
number with 1.0 will result in a huge number, huge allocations and
stalls. This is highly undesirable.
This series adds more tests in this area covering additional corner cases,
and then fixes the issue by adding the missing verification where it's
needed. After the series, all 12 tests …
=> alternator: fix validation of numbers' magnitude and precision

sstables/sstables.cc, sstables/sstables.hh, test/boost/sstable_datafile_test.cc, test/boost/sstable_resharding_test.cc, test/lib/sstable_test_env.hh, test/lib/test_services.cc, test/lib/test_services.hh
Currently there are only 2 tests for S3 -- the pure client test and compound object_store test that launches scylla, creates s3-backed table and CQL-queries it. At the same time there's a whole lot of small unit test for sstables functionality, part of it can run over S3 storage too.
This PR adds this support and patches several test cases to use it. More test cases are to come later on demand.
fixes: #13015
=> Add S3 support to sstables::test_env

cmake/mode.common.cmake, configure.py, cql3/CMakeLists.txt
it turns out the only places where we have compiler warnings of -W-parentheses-equality is the source code generated by ANTLR. strictly speaking, this is valid C++ code, just not quite readable from the hygienic point of view. so let's enable this warning in the source tree, but only disable it when compiling the sources generated by ANTLR.
please note, this warning option is supported by both GCC and Clang, so no need to test if it is supported.
for a sample of the warnings, see:
```
/home/kefu/dev/scylladb/build/cmake/cql3/CqlLexer.cpp:21752:38: error: equality comparison with extraneous parentheses [-Werror,-Wparentheses-equality]
if ( (LA4_0 == '$'))
~~~~~~^~~~~~
/home/kefu/dev/scylladb/build/cmake/cql3/CqlLexer.cpp:21752:38: note: remove extraneous parentheses around the comparison …
```
=> build: only apply -Wno-parentheses-equality to ANTLR generated sources

db/size_estimates_virtual_reader.cc, reader_concurrency_semaphore.cc, reader_concurrency_semaphore.hh, reader_permit.hh, readers/multishard.cc, replica/database.cc, sstables/consumer.hh, test/boost/continuous_data_consumer_test.cc, test/boost/reader_concurrency_semaphore_test.cc
In https://github.com/scylladb/scylladb/pull/13482 we renamed the reader permit states to more descriptive names. That PR however only covered only the states themselves and their usages, as well as the documentation in `docs/dev`.
This PR is a followup to said PR, completing the name changes: renaming all symbols, names, comments etc, so all is consistent and up-to-date.
=> tree: finish the reader_permit state renames

mutation/mutation_compactor.hh, test/boost/mutation_test.cc
e2c9cdb576c2186719ce7181dd6619f1994e262e moved the validation of the range tombstone change to the place where it is actually consumed, so we don't attempt to pass purged or discarded range tombstones to the validator. In doing so however, the validate pass was moved after the consume call, which moves the range tombstone change, the validator having been passed a moved-from range tombstone. Fix this by moving he validation to before the consume call.
Refs: #12575
=> mutation/mutation_compactor: validate range tombstone change before it is moved

sstables/sstables.cc, sstables/writer.hh
One is unused, the other one is not really required in public
=> Remove some file_writer public methods

sstables/sstables.cc
The method in question suffers from scylladb/seastar#1298. The PR fixes it and makes a bit shorter along the way
=> Close toc file in remove_by_toc_name()

CMakeLists.txt, cmake/mode.common.cmake
to avoid the FTBFS after we bump up the Seastar submodule which bumped up its API level to v7. and API v7 is a breaking change. so, in order to unbreak the build, we have to hardwire the API level to 6. `configure.py` also does this.
=> build: cmake: use Seastar API level 6

test/pylib/scylla_cluster.py, test/pylib/util.py, test/pylib_test/pytest.ini, test/pylib_test/run, test/pylib_test/suite.yaml, test/pylib_test/test_util.py
This is a follow-up to #13399, the patch
addresses the issues mentioned there:
* linesep can be split between blocks;
* linesep can be part of UTF-8 sequence;
* avoid excessively long lines, limit to 256 chars;
* the logic of the function made simpler and more maintainable.
=> scylla_cluster.py: fix read_last_line

cql3/statements/cas_request.cc, test/cql-pytest/test_unset.py
In #13001 we found a test case which causes a crash because it didn't handle `UNSET_VALUE` properly:
```python3
def test_unset_insert_where(cql, table2):
p = unique_key_int()
stmt = cql.prepare(f'INSERT INTO {table2} (p, c) VALUES ({p}, ?)')
with pytest.raises(InvalidRequest, match="unset"):
cql.execute(stmt, [UNSET_VALUE])
def test_unset_insert_where_lwt(cql, table2):
p = unique_key_int()
stmt = cql.prepare(f'INSERT INTO {table2} (p, c) VALUES ({p}, ?) IF NOT EXISTS')
with pytest.raises(InvalidRequest, match="unset"):
cql.execute(stmt, [UNSET_VALUE])
```
This PR does an absolutely minimal change to fix the crash.
It adds a check the moment before the crash would happen.
To make sure that everything works correctly, and to detect any possible breaking changes, I wrote a bunch of tests …
=> [branch-5.0] - minimal fix for crash caused by empty primary key range in LWT update

api/storage_service.cc, replica/distributed_loader.cc, replica/table.cc, sstables/generation_type.hh, sstables/sstable_directory.cc, test/boost/sstable_3_x_test.cc, test/boost/sstable_compaction_test.cc, test/boost/sstable_datafile_test.cc, test/boost/sstable_directory_test.cc, test/boost/sstable_resharding_test.cc, test/boost/sstable_test.cc, test/lib/sstable_test_env.hh
this series prepares for the UUID based generation by replacing the general `value()` function with the function with more specific name: `as_int()`.
=> replica, sstable: replace generation_type::value() with generation_type::as_int()

compaction/compaction.cc, compaction/compaction.hh, mutation/mutation_fragment_stream_validator.hh, readers/mutation_reader.cc, sstables/mx/reader.cc, sstables/mx/reader.hh, sstables/sstables.cc, sstables/sstables.hh, test/boost/mutation_fragment_test.cc, test/boost/sstable_compaction_test.cc, test/cql-pytest/conftest.py, test/cql-pytest/test_sstable_validation.py, test/cql-pytest/test_tools.py, tools/scylla-sstable.cc
In addition to the data file itself. Currently validation avoids the
index altogether, using the crawling reader which only relies on the
data file and ignores the index+summary. This is because a corrupt
sstable usually has a corrupt index too and using both at the same time
might hide the corruption. This patch adds targeted validation of the
index, independent of and in addition to the already existing data
validation: it validates the order of index entries as well as whether
the entry points to a complete partition in the data file.
This will usually result in duplicate errors for out-of-order
partitions: one for the data file and one for the index file.
Fixes: #9611
=> compaction: validate: validate the index too

service/raft/raft_group_registry.cc, service/raft/raft_group_registry.hh
All Raft verbs include `dst_id`, the ID of the destination server, but it isn't checked. `append_entries` will work even if it arrives at completely the wrong server (but in the same group). It can cause problems, e.g. in the scenario of replacing a dead node.
This commit adds verifying if `dst_id` matches the server's ID and if it doesn't, the Raft verb is rejected.
Closes #12179
Testcase and scylla's configuration: https://github.com/margdoc/scylla/commit/57d3ef14d848840b93346fdb9f86c7605d53bdcd
It artificially lengthens the duration of replacing the old node. It increases the chance of getting the RPC command sent to a replaced node, by the new node.
In the logs of the node that replaced the old one, we can see logs in the form:
```
DEBUG <time> [shard 0] raft_group_registry - Got …
```
=> raft: verify RPC destination ID

idl/gossip_digest.idl.hh, idl/raft.idl.hh, idl/raft_storage.idl.hh, raft/internal.hh, raft/raft.hh, utils/tagged_integer.hh
Change f5f566bdd8b2fbffd104593dba033175f51b26ae introduced
tagged_integer and replaced raft::internal::tagged_uint64
with utils::tagged_integer.
However, the idl type for raft::internal::tagged_uint64
was not marked as final, but utils::tagged_integer is, breaking
the on-the-wire compatibility.
This change restores the use of raft::internal::tagged_uint64
for the raft types and adds back an idl definition for
it that is not marked as final, similar to the way
raft::internal::tagged_id extends utils::tagged_uuid.
Fixes #13752
=> Restore raft::internal::tagged_uint64 type

sstables/generation_type.hh, sstables/sstables.cc
in this series, we encode the value of generation using UUID to prepare for the UUID generation identifier. simpler this way, as we don't need to have two ways to encode integer or a timeduuid: uuid with a zero timestamp, and a variant. also, add a `from_string()` factory method to convert string to generation to hide the the underlying type of value from generation_type's users.
=> sstable: encode value using UUID

cql3/expr/prepare_expr.cc, test/cql-pytest/test_filtering.py
Let's say that we have a prepared statement with a token restriction:
```cql
SELECT * FROM some_table WHERE token(p1, p2) = ?
```
After calling `prepare` the drivers receives some information about the prepared statment, including names of values bound to each bind marker.
In case of a partition token restriction (`token(p1, p2) = ?`) there's an expectation that the name assigned to this bind marker will be `"partition key token"`.
In a recent change the code handling `token()` expressions has been unified with the code that handles generic function calls, and as a result the name has changed to `token(p1, p2)`.
It turns out that the Java driver relies on the name being `"partition key token"`, so a change to `token(p1, p2)` broke some things.
This patch sets the name back to `"partition …
=> cql3/prepare_expr: force token() receiver name to be partition key token

data_dictionary/data_dictionary.cc, data_dictionary/storage_options.hh
in this series, `data_dictionary::storage_options` is refactored so that each dedicated storage option takes care of itself, instead of putting all the logic into `storage_options`. cleaner this way. as the next step, i will add yet another set of options for the tiered_storage which is backed by the s3_storage and the local filesystem_storage. with this change, we will be able to group the per-option functionalities together by the option thy are designed for, instead of sharding them by the actual function.
=> data_dictionary: define helpers in options and define == operator only

test/boost/sstable_3_x_test.cc, test/boost/sstable_datafile_test.cc, test/boost/sstable_move_test.cc, test/boost/sstable_mutation_test.cc, test/boost/sstable_test.cc, test/lib/sstable_test_env.hh
the series drops some of the callers using SSTable generation as integer. as the generation of SSTable is but an identifier, we should not use it as an integer out of generation_type's implementation.
=> test: sstable_*test: avoid using helper using generation_type::int_t 

compaction/compaction_manager.cc, test/rest_api/test_storage_service.py
It is possible that a node will have no owned token ranges
in some keyspaces based on their replication strategy,
if the strategy is configured to have no replicas in
this node's data center.
In this case we should go ahead with cleanup that will
effectively delete all data.
Note that this is current very inefficient as we need
to filter every partition and drop it as unowned.
It can be optimized by either special casing this case
or, better, use skip forward to the next owned range.
This will skip to end-of-stream since there are no
owned ranges.
Fixes #13634
Also, add a respective rest_api unit test
=> Allow no owned token ranges in cleanup compaction

cql3/cql3_type.cc, cql3/statements/alter_type_statement.cc, cql3/statements/create_type_statement.cc, cql3/statements/drop_type_statement.cc, cql3/ut_name.cc, cql3/ut_name.hh, cql3/util.cc, test/cql-pytest/test_permissions.py, test/cql-pytest/util.py
This series fixes an issue with altering permissions on UDFs with
parameter types that are UDTs with quoted names and adds
a test for it.
The issue was caused by the format of the temporary string
that represented the UDT in `auth::resource`. After parsing the
user input to a raw type, we created a string representing the 
UDT using `ut_name::to_string()`. The segment of the resulting
string that represented the name of the UDT was not quoted,
making us unable to parse it again when the UDT was being
`prepare`d. Other than for this purpose, the `ut_name::to_string()`
is used only for logging, so the solution was modifying it to
maybe quote the UDT name.
Ref: https://github.com/scylladb/scylladb/pull/12869
=> cql: enable setting permissions on resources with quoted UDT names

mutation/mutation_fragment.cc, mutation/mutation_fragment.hh, mutation/mutation_fragment_v2.hh, reader_concurrency_semaphore.cc, reader_permit.hh, test/boost/querier_cache_test.cc, test/boost/reader_concurrency_semaphore_test.cc
This PR contains some small improvements to the safety of consuming/releasing resources to/from the semaphore:
* reader_permit: make the low-level `consume()/signal()` API private, making the only user (an RAII class) friend.
* reader_resources: split `reset()` into `noexcept` and potentially throwing variant.
* reader_resources::reset_to(): try harder to avoid calling `consume()` (when the new resource amount is smaller then the previous one)
=> reader_permit: minor improvements to resource consume/release safety

api/api-doc/column_family.json, api/api-doc/storage_service.json, api/column_family.cc, api/storage_service.cc, compaction/compaction.cc, compaction/leveled_compaction_strategy.cc, compaction/size_tiered_compaction_strategy.cc, compaction/table_state.hh, compaction/time_window_compaction_strategy.cc, replica/database.hh, replica/table.cc, test/boost/sstable_compaction_test.cc, test/lib/test_services.cc, test/lib/test_services.hh, test/rest_api/test_column_family.py, test/rest_api/test_storage_service.py
Adding new APIs /column_family/tombstone_gc and /storage_service/tombstone_gc, that will allow for disabling tombstone garbage collection (GC) in compaction.
Mimicks existing APIs /column_family/autocompaction and /storage_service/autocompaction.
column_family variant must specify a single table only, following existing convention.
whereas the storage_service one can specify an entire keyspace, or a subset of a tables in a keyspace.
column_family API usage
-----
```
The table name must be in keyspace:name format
Get status:
curl -s -X GET "http://127.0.0.1:10000/column_family/tombstone_gc/ks:cf"
Enable GC
curl -s -X POST "http://127.0.0.1:10000/column_family/tombstone_gc/ks:cf"
Disable GC
curl -s -X DELETE "http://127.0.0.1:10000/column_family/tombstone_gc/ks:cf"
```
storage_service API …
=> Allow tombstone GC in compaction to be disabled on user request

main.cc, replica/database.cc, replica/database.hh, sstables/sstables_manager.cc, sstables/sstables_manager.hh, sstables/storage.cc, test/lib/cql_test_env.cc, test/lib/cql_test_env.hh, test/lib/sstable_test_env.hh, test/lib/test_services.cc, utils/s3/client.cc, utils/s3/client.hh
Currently s3::client is created for each sstable::storage. It's later shared between sstable's files and upload sink(s). Also foreign_sstable_open_info can produce a file from a handle making a new standalone client. Coupled with the seastar's http client spawning connections on demand, this makes it impossible to control the amount of opened connections to object storage server.
In order to put some policy on top of that (as well as apply workload prioritization) s3 clients should be collected in one place and then shared by users. Since s3::client uses seastar::http::client under the hood which, in turn, can generate many connections on demand, it's enough to produce a single s3::client per configured endpoint one each shard and then share it between all the sstables, files and sinks. …
=> Share s3 clients between sstables

sstables/sstables.cc
It consists of two parts -- call for do_read_simple() with lambda and handling of its results. PR coroutinizes it in two steps for review simplicity -- first the lambda, then the outer caller. Then restores indentation.
=> Coroutinize sstable::read_toc()

alternator/controller.cc, alternator/executor.cc, alternator/executor.hh, db/config.cc, test/lib/alternator_test_env.cc
before this change, alternator_timeout_in_ms is not live-updatable,
as after setting executor's default timeout right before creating
sharded executor instances, they never get updated with this option
anymore. but many users would like to set the driver timers based on
server timers. we need to enable them to configure timeout even 
when the server is still running.
in this change,
* `alternator_timeout_in_ms` is marked as live-updateable
* `executor::_s_default_timeout` is changed to a thread_local variable,
so it can be updated by a per-shard updateable_value. and
it is now a updateable_value, so its variable name is updated
accordingly. this value is set in the ctor of executor, and
it is disconnected from the corresponding named_value<> option
in the dtor of executor.
* …
=> alternator,config: make alternator_timeout_in_ms live-updateable

configure.py, gms/heart_beat_state.hh, service/storage_service.cc, test/boost/tagged_integer_test.cc, utils/tagged_integer.hh
It turns out that numeric_limits defines an implicit implementation
for std::numeric_limits<utils::tagged_integer<Tag, ValueType>>
which apprently returns a default-constructed tagged_integer
for min() and max(), and this broke
`gms::heart_beat_state::force_highest_possible_version_unsafe()`
since [gms: heart_beat_state: use generation_type and version_type](https://github.com/scylladb/scylladb/compare/4cdad8bc8bc68cfcf1b2677da78e2b87aef77631)
(merged in [Merge 'gms: define and use generation and version types'...](https://github.com/scylladb/scylladb/compare/7f04d8231df86ae4dda31318464fa0e8a100eaff))
Implementing min/max correctly
Fixes #13801
=> Fix heart_beat_state::force_highest_possible_version_unsafe

gms/gossiper.cc, gms/gossiper.hh, service/storage_service.cc
This series introduces a new gossiper method: get_endpoints that returns a vector of endpoints (by value) based on the endpoint state map.
get_endpoints is used here by gossiper and storage_service for iterations that may preempt
instead of iterating direction over the endpoint state map (`_endpoint_state_map` in gossiper or via `get_endpoint_states()`) so to prevent use-after-free that may potentially happen if the map is rehashed while the function yields causing invalidation of the loop iterators.
Fixes #13899
=> Do not yield while traversing the gossiper endpoint state map

test/pylib/minio_server.py
CI once failed due to mc being unable to configure minio server. There's currently no glues why it could happen, let's increase the minio.py verbosity a bit
refs: #13896
=> Improve verbosity of test/pylib/minio.py

cql3/statements/create_keyspace_statement.cc, cql3/statements/create_keyspace_statement.hh, cql3/statements/create_role_statement.hh, cql3/statements/create_table_statement.cc, cql3/statements/create_table_statement.hh, cql3/statements/function_statement.cc, cql3/statements/function_statement.hh, cql3/statements/role-management-statements.cc, cql3/statements/schema_altering_statement.cc, cql3/statements/schema_altering_statement.hh, test/cql-pytest/test_permissions.py
Currently, when a user creates a function or a keyspace, no
permissions on functions are update.
Instead, the user should gain all permissions on the function
that they created, or on all functions in the keyspace they have
created. This is also the behavior in Cassandra.
However, if the user is granted permissions on an function after
performing a CREATE OR REPLACE statement, they may
actually only alter the function but still gain permissions to it
as a result of the approach above, which requires another
workaround added to this series.
Lastly, as of right now, when a user is altering a function, they
need both CREATE and ALTER permissions, which is incompatible
with Cassandra - instead, only the ALTER permission should be
required.
This series fixes the mentioned issues, and the tests …
=> cql: update permissions when creating/altering a function/keyspace

range_tombstone_change_generator.hh, test/boost/row_cache_test.cc
range_tombstone_change_generator::flush() mishandles the case when two range
tombstones are adjacent and flush(pos, end_of_range=true) is called with pos
equal to the end bound of the lesser-position range tombstone.
In such case, the start change of the greater-position rtc will be accidentally
emitted, and there won't be an end change, which breaks reader assumptions by
ending the stream with an unclosed range tombstone, triggering an assertion.
This is due to a non-strict inequality used in a place where strict inequality
should be used. The modified line was intended to close range tombstones
which end exactly on the flush position, but this is unnecessary because such
range tombstones are handled by the last `if` in the function anyway.
Instead, this line caused range tombstones …
=> range_tombstone_change_generator: fix an edge case in flush()

db/config.cc, db/config.hh, gms/gossiper.cc, gms/gossiper.hh, repair/repair.cc, repair/repair.hh, repair/row_level.hh, service/storage_service.cc, service/storage_service.hh
This branch backports to branch-5.2 several fixes related to node operations:
- ba919aa88aa462b91520f73d3b7c2e775caaee87 (PR #12980; Fixes: #11011, #12969)
- 53636167caae299389018c6f2f805560e64d4ce7 (part of PR #12970; Fixes: #12764, #12956)
- 5856e69462342a6559aa066c9837f4bb9fe17f98 (part of PR #12970)
- 2b44631ded8b9dd4db70a0cabdc8c87789698cc6 (PR #13028; Fixes: #12989)
- 6373452b317dc8475076ca7353004cc4908b865e (PR #12799; Fixes #12798)
=> [Backport 5.2]: node ops backports

replica/database.cc, replica/database.hh, replica/distributed_loader.cc, replica/global_table_ptr.hh, replica/table.cc
There are several places that need to carry a pointer to a table that's shard-wide accessible -- database snapshot and truncate code and distributed loader. The database code uses `get_table_on_all_shards()` returning a vector of foreign lw-pointers, the loader code uses its own global_column_family_ptr class.
This PR generalizes both into global_table_ptr facility.
=> Generalize global table pointer

compaction/compaction_manager.cc, compaction/compaction_manager.hh, compaction/table_state.hh, replica/compaction_group.hh, replica/table.cc, sstables/sstable_set.cc, sstables/sstable_set.hh, sstables/sstable_set_impl.hh, test/boost/sstable_set_test.cc, test/lib/test_services.cc
cleanup_compaction should resolve only after all
sstables that require cleanup are cleaned up.
Since it is possible that some of them are in staging
and therefore cannot be cleaned up, retry once a second
until they become eligible.
Timeout if there is no progress within 5 minutes
to prevent hanging due to view building bug.
Fixes #9559
=> perform_cleanup: wait until all candidates are cleaned up

api/storage_service.cc, db/system_keyspace.cc, docs/dev/topology-over-raft.md, service/storage_service.cc, service/storage_service.hh, service/topology_state_machine.cc, service/topology_state_machine.hh, test/pylib/manager_client.py, test/topology_experimental_raft/test_topology_ops.py
`check_and_repair_cdc_streams` is an existing API which you can use when the
current CDC generation is suboptimal, e.g. after you decommissioned a node the
current generation has more stream IDs than you need. In that case you can do
`nodetool checkAndRepairCdcStreams` to create a new generation with fewer
streams.
It also works when you change number of shards on some node. We don't
automatically introduce a new generation in that case but you can use
`checkAndRepairCdcStreams` to create a new generation with restored
shard-colocation.
This PR implements the API on top of raft topology, it was originally
implemented using gossiper.  It uses the `commit_cdc_generation` topology
transition state and a new `publish_cdc_generation` state to create new CDC
generations in a cluster without any …
=> raft topology: implement `check_and_repair_cdc_streams` API

db/view/view.cc, locator/abstract_replication_strategy.cc, locator/abstract_replication_strategy.hh, locator/everywhere_replication_strategy.cc, locator/everywhere_replication_strategy.hh, locator/local_strategy.cc, locator/local_strategy.hh, locator/tablets.cc, locator/tablets.hh, locator/token_metadata.cc, locator/token_metadata.hh, service/storage_proxy.cc, service/storage_service.cc, service/storage_service.hh, test/boost/token_metadata_test.cc, utils/sequenced_set.hh, utils/stall_free.hh
This refactoring is a follow-up for https://github.com/scylladb/scylladb/pull/13376, move per keyspace data structures related to topology changes from `token_metadata` to `erm`.
We move `pending_endpoints` and `read_endpoints`, along with their computation logic, from `token_metadata` to `vnode_effective_replication_map`. The `vnode_effective_replication_map` seems more appropriate for them since it contains functionally similar `replication_map` and we will be able to reuse `pending_endpoints/read_endpoints` across keyspaces sharing the same `factory_key`.
At present, `pending_endpoints` and `read_endpoints` are updated in the `update_pending_ranges` function. The update logic comprises two parts - preparing data common to all keyspaces/replication_strategies, and calculating the …
=> Move pending_ranges and endpoints_for_reading from token_metadata to erm

multishard_mutation_query.cc, partition_slice_builder.cc, partition_slice_builder.hh, test/boost/database_test.cc
With regards to closing the looked-up querier if an exception is thrown. In particular, this requires closing the querier if a semaphore mismatch is detected. Move the table lookup above the line where the querier is looked up, to avoid having to handle the exception from it. As a consequence of closing the querier on the error path, the lookup lambda has to be made a coroutine. This is sad, but this is executed once per page, so its cost should be insignificant when spread over an
entire page worth of work.
Also add a unit test checking that the mismatch is detected in the first place and that readers are closed.
Fixes: #13784
=> multishard_mutation_query: make reader_context::lookup_readers() exception safe

message/messaging_service.cc, message/messaging_service.hh
On connection setup, the isolation cookie of the connection is matched to the appropriate scheduling group. This is achieved by iterating over the known statement tenant connection types as well as the system connections and choosing the one with a matching name.
If a match is not found, it is assumed that the cluster is upgraded and the remote node has a scheduling group the local one doesn't have. To avoid demoting a scheduling group of unknown importance, in this case the default scheduling group is chosen.
This is problematic when upgrading an OSS cluster to an enterprise version, as the scheduling groups of the enterprise service-levels will match none of the statement tenants and will hence fall-back to the default scheduling group. As a consequence, while the cluster is mixed, user …
=>  message: match unknown tenants to the default tenant

replica/memtable.hh, test/boost/memtable_test.cc, test/boost/sstable_datafile_test.cc, test/boost/view_build_test.cc
There are several places in tests that either use default_priority_class() explicitly, or use some specific prio class obtained from priority manager. There's currently an ongoing work to remove all priority classes, this set makes the final patch a bit smaller and easier to review. In particular -- in many cases default_priority_class() is implicit and can be avoided by callers. Also, using any prio class by test is excessive, it can go with (implicit) default_priority_class.
ref: #13963
=> Use implicit default prio class in tests

sstables/index_reader.hh, sstables/sstables.cc, test/boost/sstable_3_x_test.cc, test/boost/sstable_datafile_test.cc, test/boost/sstable_mutation_test.cc, test/lib/sstable_utils.hh, tools/scylla-sstable.cc
The way index_reader maintains io_priority_class can be relaxed a bit. The main intent is to shorten the #13963 final patch a bit, as a side effect index_reader gets its portion of API polishing.
ref: #13963
=> Clean index_reader API

main.cc, streaming/stream_manager.cc, streaming/stream_manager.hh, test/lib/cql_test_env.cc
The manager is in charge of updating IO bandwidth on the respective prio class. Nowadays it uses global priority-manager, but unifying sched classes effort will require it to use non-global streaming sched group. After the patch the sched class field is unused, but it's a preparation towards huge (really huge) "switch to seastar API level 7" patch
ref: #13963
=> Put streaming sched group onto stream manager

cql3/statements/ks_prop_defs.cc, test/boost/network_topology_strategy_test.cc
A CREATE KEYSPACE query which specifies an empty string ('') as the replication factor value is currently allowed:
```cql
CREATE KEYSPACE bad_ks WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': ''};
```
This is wrong, it's invalid to have an empty replication factor string.
It creates a keyspace without any replication, so the tables inside of it aren't writable.
Trying to create a `SimpleStrategy` keyspace with such replication factor throws an error, `NetworkTopolgyStrategy` should do the same.
The problem was in `prepare_options`, it treated an empty replication factor string as no replication factor.
Changing it to `std::optional` fixes the problem,
Now `std::nullopt` means no replication factor, and `make_optional("")` means that there is a replication …
=> ks_prop_defs: disallow empty replication factor string in NTS

locator/abstract_replication_strategy.cc, locator/abstract_replication_strategy.hh, utils/stall_free.hh
This is a small follow-up for [this PR](https://github.com/scylladb/scylladb/pull/13715), it resolves some comments in the initial PR that didn't make their way into it.
* remove `noexcept` from `clear_gently`, since exceptions can be raised from move constructor;
* an optimisation for `vnode_effective_replication_map::get_range_addresses`, avoid redundant binary search.
=> Small improvements after pending_ranges, endpoints_for_reading -> erm PR

test/topology/test_tablets.py
We've observed sporadic failures of this test in CI related to driver reconnection after server restart.
Fixes #14032
=> Fix flakiness of test_tablets.py

sstables/storage.cc, test/boost/s3_test.cc, utils/s3/client.cc, utils/s3/client.hh
Current S3 uploading sink has implicit limit for the final file size that comes from two places. First, S3 protocol declares that uploading parts count from 1 to 10000 (inclusive). Second, uploading sink sends out parts once they grow above S3 minimal part size which is 5Mb. Since sstables puts data in 128kb (or smaller) portions, parts are almost exactly 5Mb in size, so the total uploading size cannot grow above ~50Gb. That's too low.
To break the limit the new sink (called jumbo sink) uses the UploadPartCopy S3 call that helps splicing several objects into one right on the server. Jumbo sink starts uploading parts into an intermediate temporary object called a piece and named ${original_object}_${piece_number}. When the number of parts in current piece grows above the configured limit …
=> Break S3 upload 50Gb file limit

replica/database.cc, replica/database.hh, replica/distributed_loader.cc, test/lib/cql_test_env.cc
This set encapsulates ks/cf directories creation and deletion into keyspace and table classes methods. This is needed to facilitate making the storage initialization storage-type aware in the future. Also this makes the replica/ code less involved in formatting sstables' directory path by hand.
refs: #13020
refs: #12707
=> Initialize/destroy ks/cf directories with explicit class methods

db/hints/manager.cc, db/hints/manager.hh, db/view/view.cc, service/storage_proxy.cc, service/storage_proxy.hh, test/pylib/manager_client.py, test/pylib/scylla_cluster.py, test/topology_custom/suite.yaml, test/topology_custom/test_shutdown_hang.py
The `view_update_write_response_handler` class, which is a subclass of
`abstract_write_response_handler`, was created for a single purpose:
to make it possible to cancel a handler for a view update write,
which means we stop waiting for a response to the write, timing out
the handler immediately. This was done to solve issue with node
shutdown hanging because it was waiting for a view update to finish;
view updates were configured with 5 minute timeout. See #3966, #4028.
Now we're having a similar problem with hint updates causing shutdown
to hang in tests (#8079).
`view_update_write_response_handler` implements cancelling by adding
itself to an intrusive list which we then iterate over to timeout each
handler when we shutdown or when gossiper notifies `storage_proxy`
that a node is down. …
=> service: storage_proxy: make hint write handlers cancellable

api/column_family.cc, api/storage_service.cc, api/storage_service.hh, compaction/task_manager_module.cc, compaction/task_manager_module.hh, schema/schema.cc, schema/schema_fwd.hh
In compaction logs table is identified by {keyspace}.{table_id}.
Instead, table name should be used in run_on_existing_tables
logs. To do so, task manager's compaction tasks use table_info
instead of table_id.
Keyspace argument is copied to run_on_existing_tables
to ensure it's alive.
=> Use table_info in compaction

alternator/executor.cc, test/alternator/test_batch.py
Summary of the patch set:
- eliminates not needed calls to rjson::find (~1% tps improvement in `perf-simple-query --write`)
- adds some very specific test in this area (more general cases were covered already)
- fixes some minor validation bug
Fixes https://github.com/scylladb/scylladb/issues/13251
=> alternator: eliminate duplicated rjson::find() of ExpressionAttributeNames and ExpressionAttributeValues

alternator/executor.cc, alternator/executor.hh, utils/rjson.cc
Adds preemption points used in Alternator when:
- sending bigger json response
- building results for BatchGetItem
I've tested manually by inserting in preemptible sections (e.g. before `os.write`) code similar to:
auto start  = std::chrono::steady_clock::now();
do { } while ((std::chrono::steady_clock::now() - start) < 100ms);
and seeing reactor stall times. After the patch they
were not increasing while before they kept building up due to no preemption.
Refs #7926
Fixes #13689
=> Yield while building large results in Alternator - rjson::print, executor::batch_get_item

message/messaging_service.cc, message/messaging_service.hh
Recent seastar update added rpc::server::shutdown() method that only isolates the server from the network, but lets all internal handler callbacks continue running up until stop() is called. This patch makes use of it in messaging service by calling this new shiny shutdown() in its shutdown() and calling good old stop() in its stop().
Intentionally, it will prevent scylla from freezing on drain in case some RPC handler gets stuck. It may later freeze on stop(), but it's less horrible. Also chances are that by stop time some other handler's dependencies would have been drained/shut-down so the handler can wake up and stop normally.
fixes: #14031
=> Enlighten messaging_service::shutdown()

test/cql-pytest/util.py, test/object_store/run
this series replaces hard-coded values with variables. will need to expand this test to cover most test cases when working on tiered-storage.
=> s3/test: cleanups to avoid using hardcoded values

raft/server.cc, test/raft/replication.hh
There are some cases where we can deduce that the entry was committed,
but we were throwing `commit_status_unknown`. Handle one more such case.
The added comment explains it in detail.
Also add a FIXME for another case where we throw `commit_status_unknown`
but we could do better.
Fixes: #14029
Fixes: #14072
=> raft: server: throw fewer `commit_status_unknown`s from `wait_for_entry`

docs/dev/reader-concurrency-semaphore.md, reader_concurrency_semaphore.cc
Containing two tables, describing all the possible operations seen in user, system and streaming semaphore diagnostics dumps.
=> docs/dev/reader-concurrency-semaphore.md: add section about operations

gms/feature_service.cc, gms/feature_service.hh, test/pylib/util.py, test/topology/suite.yaml, test/topology/test_cluster_features.py, test/topology_raft_disabled/test_raft_upgrade_basic.py, test/topology_raft_disabled/test_raft_upgrade_no_schema.py, test/topology_raft_disabled/util.py
This PR adds a set of tests for cluster features. The set covers those tests from the test plan for the upcoming "cluster features on raft" that do not depend on implementation-specific details. Those tests are applicable to the existing gossip-based implementation, so they can be useful for us right now.
The tests simulate cluster upgrades by conditionally marking support for the TEST_ONLY_FEATURE on the nodes via error injection. Therefore, the tests work only in non-release mode.
The `test_partial_upgrade_can_be_finished_with_removenode` test is marked as skipped because of a bug in gossip that prevents features from being enabled if a node was removed within the last 3 days (#14194).
=> Tests for cluster features

sstables/sstable_directory.cc, sstables/sstable_directory.hh
When scylla starts it collects dangling sstables from the datadir. It includes temporary sstable directories and pending-deletion log. S3-backed sstables cannot be garbage-collected like that, instead "garbage" entries from the ownership table should be processed. Currently the g.c. code is unaware of storage and scans datadir for whatever sstable it's called for.
This PR prepares the garbage_collect() call to become virtual, but no-op for ownership-table lister. Proper S3 garbage-collecting is not yet here, it needs an extra patch to seastar http client.
refs: #13024
=> Prepare sstable_directory lister to garbage_collect() s3 stuff

db/consistency_level.cc, db/consistency_level.hh, main.cc, replica/database.hh, replica/table.cc, service/storage_proxy.cc, service/storage_proxy.hh, test/lib/cql_test_env.cc
Move the initialization of `storage_proxy` early in the startup procedure, before starting
`system_keyspace`, `messaging_service`, `gossiper`, `storage_service` and more.
As a follow-up, we'll be able to move initialization of `query_processor` right
after `storage_proxy` (but this requires a bit of refactoring in
`query_processor` too).
Local queries through `storage_proxy` can be done after the early initialization step.
In a follow-up, when we do a similar thing for `query_processor`, we'll be able
to perform local CQL queries early as well. (Before starting `gossiper` etc.)
=> Initialize `storage_proxy` early, without `messaging_service` and `gossiper`

service/migration_manager.cc
to reduce the indentation level, and to improve the readability. also, take this opportunity to name some variables for better readability.
=> migration_manager: coroutinize some member functions of migration_manager

service/storage_service.cc
The `topology_coordinator::cleanup_group0_config_if_needed` function first checks whether the number of group 0 members is larger than the number of non-left entries in the topology table, then attempts to remove nodes in left state from group 0 and prints a warning if no such nodes are found. There are some problems with this check:
- Currently, a node is added to group 0 before it inserts its entry to the topology table. Such a node may cause the check to succeed but no nodes will be removed, which will cause the warning to be printed needlessly.
- Cluster features on raft will reverse the situation and it will be possible for an entry in system.topology to exist without the corresponding node being a part of group 0. This, in turn, may cause the check not to pass when it should and …
=> storage_service: remove optimization in cleanup_group0_config_if_needed

test/topology/test_cluster_features.py, test/topology/util.py, test/topology_raft_disabled/test_raft_upgrade_basic.py, test/topology_raft_disabled/test_raft_upgrade_majority_loss.py, test/topology_raft_disabled/test_raft_upgrade_no_schema.py, test/topology_raft_disabled/test_raft_upgrade_stuck.py, test/topology_raft_disabled/util.py
The test `test_downgrade_after_successful_upgrade_fails` shuts down the whole cluster, reconfigures the nodes and then restarts. Apparently, the python driver sometimes does not handle this correctly; in one test run we observed that the driver did not manage to reconnect to any of the nodes, even though the nodes managed to start successfully.
More context can be found on the python driver issue.
This PR works around this issue by using the existing `reconnect_driver` function (which is a workaround for a _different_ python driver issue already) to help the driver reconnect after the full cluster restart.
Refs: scylladb/python-driver#230
=> test/topology/test_cluster_features: workaround for python driver not reconnecting after full cluster restart

cql3/column_identifier.cc, cql3/column_identifier.hh, cql3/expr/expression.cc, test/boost/expr_test.cc, types/types.cc, types/types.hh, types/user.hh
Implement `expr:valuate()` for `expr::field_selection`.
`field_selection` is used to represent access to a struct field.
For example, with a UDT value:
```
CREATE TYPE my_type (a int, b int);
```
The expression `my_type_value.a` would be represented as a `field_selection`, which selects the field `a`.
Evaluating such an expression consists of finding the right element's value in a serialized UDT value and returning it.
Note that it's still not possible to use `field_selection` inside the `WHERE` clause. Enabling it would require changes to the grammar, as well as query planning, Current `statement_restrictions` just reacts with `on_internal_error` when it encounters a `field_selection`.
Nonetheless it's a step towards relaxing the grammar, and now it's finally possible to evaluate all …
=> cql3/expression: implement evaluate(field_selection) 

docs/operating-scylla/admin-tools/scylla-sstable.rst, test/cql-pytest/conftest.py, test/cql-pytest/run, test/cql-pytest/run.py, test/cql-pytest/test_tools.py, tools/scylla-sstable.cc
Exposing scrub compaction to the command-line. Allows for offline scrub of sstables, in cases where online scrubbing (via scylla itself) is not possible or not desired. One such case recently was an sstable from a backup which turned out to be corrupt, `nodetool refresh --load-and-stream` refusing to load it.
Fixes: #14203
=> scylla-sstable: add scrub operation

test/boost/mutation_reader_test.cc, test/boost/schema_changes_test.cc, test/boost/sstable_3_x_test.cc, test/boost/sstable_compaction_test.cc, test/boost/sstable_datafile_test.cc, test/boost/sstable_mutation_test.cc, test/lib/sstable_utils.cc, test/lib/sstable_utils.hh
There are tons of wrappers that help test cases make sstables for their needs. And lots of code duplication in test cases that do parts of those helpers' work on their own. This set cleans some bits of those
=> Sanitize sstables-making utils in tests

db/system_keyspace.cc, db/system_keyspace.hh, main.cc, replica/database.cc, replica/database.hh, replica/distributed_loader.cc, replica/distributed_loader.hh, test/lib/cql_test_env.cc
Initialization of `system_keyspace` is now done in a single place instead of
being spread out through the entire procedure. `system_keyspace` is also
available for queries much earlier which allows, for example, to load our Host
ID before we initialize any of the distributed services (like gossiper,
messaging_service etc.) This is doable because `query_processor` is now
available early. A couple of FIXMEs have been resolved.
Refs: #14202
=> Simplify `system_keyspace` initialization

cql3/expr/expression.cc, cql3/expr/expression.hh, test/boost/expr_test.cc, test/lib/expr_test_utils.cc, test/lib/expr_test_utils.hh
In preparation for converting selectors to evaluate expressions,
add support for evaluating column_mutation_attribute (representing
the WRITETIME/TTL pseudo-functions).
A unit test is added.
Fixes #12906
=> cql3: expr: support evaluate(column_mutation_attribute)

service/raft/raft_group0.cc, test/topology_experimental_raft/suite.yaml, test/topology_experimental_raft/test_blocked_bootstrap.py
Another node can stop after it joined the group0 but before it advertised itself in gossip. `get_inet_addrs` will try to resolve all IPs and `wait_for_peers_to_enter_synchronize_state` will loop indefinitely.
But `wait_for_peers_to_enter_synchronize_state` can return early if one of the nodes confirms that the upgrade procedure has finished. For that, it doesn't need the IPs of all group 0 members - only the IP of some nodes which can do the confirmation.
This pr restructures the code so that IPs of nodes are resolved inside the `max_concurrent_for_each` that `wait_for_peers_to_enter_synchronize_state` performs. Then, even if some IPs won't be resolved, but one of the nodes confirms a successful upgrade, we can continue.
Fixes #13543
=> raft topology: `wait_for_peers_to_enter_synchronize_state` doesn't need to resolve all IPs

cql3/statements/select_statement.cc, cql3/statements/select_statement.hh
Split off do_execute() into a fast path and slow(ish) path, and
coroutinize the latter.
perf-simple-query shows no change in performance (which is
unsurprising since it picks the fast path which is essentially unchanged).
=> cql3: select_statement: coroutinize and simplify do_execute()

cache_flat_mutation_reader.hh, mutation/mutation_cleaner.hh, mutation/mutation_partition.cc, partition_snapshot_row_cursor.hh, test/boost/row_cache_test.cc
Since `mvcc: make schema upgrades gentle` (https://github.com/scylladb/scylladb/commit/51e3b9321b2e7a5ae95e028287644db729f33968),
rows pointed to by the cursor can have different (older) schema
than the schema of the cursor's snapshot.
However, one place in the code wasn't updated accordingly,
causing a row to be processed with the wrong schema in the right
circumstances.
This passed through unit testing because it requires
a digest-computing cache read after a schema change,
and no test exercised this.
This series fixes the bug and adds a unit test which reproduces the issue.
Fixes #14110
=> cache_flat_mutation_reader: use the correct schema in prepare_hash

utils/s3/client.cc, utils/s3/client.hh
In its current state s3 client uses a single default-configured http client thus making different sched classes' workload compete with each other for sockets to make requests on. There's an attempt to handle that in upload-sink implementation that limits itself with some small number of concurrent PUT requests, but that doesn't help much as many sinks don't share this limit.
This PR makes S3 client maintain a set of http clients, one per sched-group, configures maximum number of TCP connections proportional to group's shares and removes the artificial limit from sinks thus making them share the group's http concurrency limit.
As a side effect, the upload-sink fixes the no-writes-after-flush protection -- if it's violated, write will result in exception, while currently it just hangs on a …
=> Add concurrency control and workload isolation for S3 client

docs/cql/dml.rst, docs/dev/timestamp-conflict-resolution.md, mutation/atomic_cell.cc, mutation/mutation_partition.cc, test/boost/mutation_test.cc, test/cql-pytest/test_using_timestamp.py
Currently, when two cells have the same write timestamp
and both are alive or expiring, we compare their value first,
before checking if either of them is expiring
and if both are expiring, comparing their expiration time
and ttl value to determine which of them will expire
later or was written later.
This was based on an early version of Cassandra.
However, the Cassandra implementation rightfully changed in
https://github.com/apache/cassandra/commit/e225c88a65f2e8091f8ea6212c291416674882a1 ([CASSANDRA-14592](https://issues.apache.org/jira/browse/CASSANDRA-14592)),
where the cell expiration is considered before the cell value.
To summarize, the motivation for this change is three fold:
1. Cassandra compatibility
2. Prevent an edge case where a null value is returned by select query when …
=> atomic_cell: compare value last

locator/token_metadata.cc, main.cc, service/storage_service.cc, test/topology_experimental_raft/test_topology_ops.py
This PR fixes some problems found after the PR was merged:
* missed `node_to_work_on` assignment in `handle_topology_transition`;
* change error reporting in `update_fence_version` from `on_internal_error` to regular exceptions, since that exceptions can happen during normal operation.
* `update_fence_version` has beed moved  after `group0_service.setup_group0_if_exist` in `main.cc`, otherwise we use uninitialized `token_metadata::version` and get an error.
Fixes: #14303
=> raft topology: fixes after #13884

service/forward_service.cc, test/cql-pytest/test_aggregate.py
There was a bug that caused aggregates to fail when used on column-sensitive columns.
For example:
```cql
SELECT SUM("SomeColumn") FROM ks.table;
```
would fail, with a message saying that there is no column "somecolumn".
This is because the case-sensitivity got lost on the way.
For non case-sensitive column names we convert them to lowercase, but for case sensitive names we have to preserve the name as originally written.
The problem was in `forward_service` - we took a column name and created a non case-sensitive `column_identifier` out of it.
This converted the name to lowercase, and later such column couldn't be found.
To fix it, let's make the `column_identifier` case-sensitive.
It will preserve the name, without converting it to lowercase.
Fixes: …
=> forward_service: fix forgetting case-sensitivity in aggregates 

compaction/compaction_manager.cc, compaction/compaction_manager.hh, compaction/task_manager_module.cc, repair/repair.cc, replica/database.hh, replica/table.cc, tasks/task_manager.hh, test/lib/sstable_utils.cc, test/rest_api/test_compaction_task.py
Task manager task covering compaction group major 
compaction.
Uses multiple inheritance on already existing
major_compaction_task_executor to keep track of
the operation with task manager.
=> Compaction group major compaction task

cql3/expr/expression.cc
Make evaluate()'s body more regular, then exploit it by
replacing the long list of branches with a lambda template.
=> cql3: expr: simplify evaluate()

cql3/statements/select_statement.cc
Improves readability, and probably a little faster too.
=> cql3: select_statement: coroutinize indexed statement's do_execute()

cql3/statements/describe_statement.cc, test/cql-pytest/test_describe.py
There was a bug in describe_statement. If executing `DESC FUNCTION  <uda name>` or ` DESC AGGREGATE <udf name>`, Scylla was crashing because the function was found (`functions::find()` searches both UDFs and UDAs) but the function was bad and the pointer wasn't checked after cast.
Added a test for this.
Fixes: #14360
=> cql3:statements:describe_statement: check pointer after casting to UDF/UDA

readers/multishard.cc, test/boost/mutation_reader_test.cc, test/boost/sstable_conforms_to_mutation_source_test.cc, test/lib/flat_mutation_reader_assertions.hh, test/lib/mutation_source_test.cc, test/lib/mutation_source_test.hh
The evictable reader must ensure that each buffer fill makes forward progress, i.e. the last fragment in the buffer has a position larger than the last fragment from the previous buffer-fill. Otherwise, the reader could get stuck in an infinite loop between buffer fills, if the reader is evicted in-between.
The code guranteeing this forward progress had a bug: the comparison between the position after the last buffer-fill and the current last fragment position was done in the wrong direction.
So if the condition that we wanted to achieve was already true, we would continue filling the buffer until partition end which may lead to OOMs such as in #13491.
There was already a fix in this area to handle `partition_start` fragments correctly - #13563 - but it missed that the position comparison …
=> readers: evictable_reader: don't accidentally consume the entire partition

cql3/statements/cas_request.cc, cql3/statements/modification_statement.cc, test/cql-pytest/test_lwt.py
LWT queries with empty clustering range used to cause a crash.
For example in:
```cql
UPDATE tab SET r = 9000 WHERE p = 1  AND c = 2 AND c = 2000 IF r = 3
```
The range of `c` is empty - there are no valid values.
This caused a segfault when accessing the `first` range:
```c++
op.ranges.front()
```
Cassandra rejects such queries at the preparation stage. It doesn't allow two `EQ` restriction on the same clustering column when an IF is involved.
We reject them during runtime, which is a worse solution. The user can prepare a query with `c = ? AND c = ?`, and then run it, but unexpectedly it will throw an `invalid_request_exception` when the two bound variables are different.
We could ban such queries as well, we already ban the usage of `IN` in conditional statements. The problem is that …
=> cql: fix crash on empty clustering range in LWT

gms/gossiper.cc, gms/gossiper.hh, message/messaging_service.cc, service/storage_service.cc
`handle_state_normal` may drop connections to the handled node. This
causes spurious failures if there's an ongoing concurrent operation.
This problem was already solved twice in the past in different contexts:
first in 53636167caae299389018c6f2f805560e64d4ce7, then in
79ee38181cf30ead7d5c4ee8ec13424e7084086f.
Time to fix it for the third time. Now we do this right after enabling
gossiping, so hopefully it's the last time.
This time it's causing snapshot transfer failures in group 0. Although
the transfer is retried and eventually succeeds, the failed transfer is
wasted work and causes an annoying ERROR message in the log which
dtests, SCT, and I don't like.
The fix is done by moving the `wait_for_normal_state_handled_on_boot()`
call before `setup_group0()`. But for the wait to work …
=> Wait for other nodes to be UP and NORMAL on bootstrap right after enabling gossiping

test/boost/index_with_paging_test.cc
Reduce test string value size, parallelize inserts, and use a prepared statement, 
The debug running time for this tests is reduced from 13:18 to 7:52.
Refs #13905
=> test/boost/index_with_paging_test: reduce running time

data_dictionary/data_dictionary.cc, data_dictionary/keyspace_metadata.hh, db/schema_tables.cc, replica/database.cc, replica/database.hh, service/migration_listener.hh, service/migration_manager.cc, service/storage_service.cc
This series aims at hardening schema merges and preventing inconsistencies across shards by
updating the database shards before calling the notification callback.
As seen in #13137, we don't want to call the notifications on all shards in parallel while the database shards are in flux.
In addition, any error to update the keyspace will cause abort so not to leave the database shards in an inconsistent state .
Other changes optimize this path by:
- updating shard 0 first, to seed the effective_replication_map.
- executing `storage_service::keyspace_changed` only once, on shard 0 to prevent quadratic update of the token_metadata and e_r_m on every keyspace change.
Fixes #13137
=> Call storage_service notifications only after keyspace schema changes are applied on all shards

docs/upgrade/_common/upgrade-guide-from-4.3-to-2021.1-ubuntu-and-debian.rst, docs/upgrade/_common/upgrade-guide-from-5.0-to-2022.1-ubuntu-and-debian.rst, docs/upgrade/upgrade-to-enterprise/upgrade-guide-from-4.3-to-2021.1/upgrade-guide-from-4.3-to-2021.1-rpm.rst, docs/upgrade/upgrade-to-enterprise/upgrade-guide-from-5.0-to-2022.1/upgrade-guide-from-5.0-to-2022.1-rpm.rst, docs/upgrade/upgrade-to-enterprise/upgrade-guide-from-5.1-to-2022.2/upgrade-guide-from-5.1-to-2022.2-generic.rst
This PR fixes the Restore System Tables section of the upgrade guides by adding a command to clean upgraded SStables during rollback or adding the entire section to restore system tables (which was missing from the older documents).
This PR fixes is a bug and must be backported to branch-5.3, branch-5.2., and branch-5.1.
Refs: https://github.com/scylladb/scylla-enterprise/issues/3046
(see https://github.com/scylladb/scylla-enterprise/issues/3046#issuecomment-1604232864)
=> doc: fix rollback in the 4.3-to-2021.1, 5.0-to-2022.1, and 5.1-to-2022.2  upgrade guides

api/task_manager.cc, tasks/task_manager.cc, tasks/task_manager.hh
Modify task_manager::task::impl::get_progress method so that,
whenever relevant, progress is calculated based on children's
progress. Otherwise progress indicates only whether the task
is finished or not. 
The method may be overriden in inheriting classes.
=> Find task manager task progress

main.cc, service/migration_manager.cc, service/migration_manager.hh, service/raft/raft_group0.cc, service/raft/raft_group0.hh, service/raft/raft_group0_client.cc, service/raft/raft_group0_client.hh, service/raft/raft_group_registry.cc, service/raft/raft_group_registry.hh
We want to disable `migration_manager` schema pulls and make schema
managed only by Raft group 0 if Raft is enabled. This will be important
with Raft-based topology, when schema will depend on topology (e.g. for
tablets).
We solved the problem partially in PR #13695. However, it's still
possible for a bootstrapping node to pull schema in the early part of
bootstrap procedure, before it setups group 0, because of how the
currently used `_raft_gr.using_raft()` check is implemented.
Here's the list of cases:
- If a node is bootstrapping in non-Raft mode, schema pulls must remain
enabled.
- If a node is bootstrapping in Raft mode, it should never perform a
schema pull.
- If a bootstrapped node is restarting in non-Raft mode but with Raft
feature enabled (which means we should start upgrading …
=> migration_manager: disable schema pulls when schema is Raft-managed

test/object_store/conftest.py, test/object_store/pytest.ini, test/object_store/run, test/object_store/suite.yaml, test/object_store/test_basic.py
in this series, test/object_storage is restructured into a pytest based test. this paves the road to a test suites covers more use cases. so we can some more lower-level tests for tiered/caching-store.
=> s3/test: restructure object_store test into a pytest based test suite

db/view/view.cc, db/view/view_updating_consumer.hh, mutation/mutation_rebuilder.hh, test/boost/mutation_test.cc, test/boost/view_build_test.cc
View update routines accept `mutation` objects.
But what comes out of staging sstable readers is a stream of mutation_fragment_v2 objects.
To build view updates after a repair/streaming, we have to convert the fragment stream into `mutation`s. This is done by piping the stream to mutation_rebuilder_v2.
To keep memory usage limited, the stream for a single partition might have to be split into multiple partial `mutation` objects. view_update_consumer does that, but in improper way -- when the split/flush happens inside an active range tombstone, the range tombstone isn't closed properly. This is illegal, and triggers an internal error.
This patch fixes the problem by closing the active range tombstone (and reopening in the same position in the next `mutation` object).
The tombstone is …
=> view: fix range tombstone handling on flushes in view_updating_consumer

docs/using-scylla/mig-tool-review.rst
Fixes https://github.com/scylladb/scylladb/issues/14459
This PR removes the (dead) link to the unirestore tool in a private repository. In addition, it adds minor language improvements.
=> doc: remove the dead link to unirestore

main.cc, service/raft/raft_group0.cc, service/raft/raft_group_registry.cc, service/raft/raft_group_registry.hh, service/raft/raft_rpc.cc, service/raft/raft_rpc.hh, test/lib/cql_test_env.cc
Avoid pinging self in direct failure detector, this adds confusing noise and adds constant overhead.
Fixes #14388
=> raft: do not ping self in direct failure detector

cdc/generation.cc, idl/group0_state_machine.idl.hh, idl/storage_service.idl.hh, raft/server.cc, raft/server.hh, service/broadcast_tables/experimental/lang.cc, service/raft/group0_state_machine.cc, service/raft/group0_state_machine.hh, service/raft/raft_group0_client.cc, service/raft/raft_group0_client.hh, service/raft/raft_sys_table_storage.cc, service/storage_service.cc, service/storage_service.hh, service/topology_state_machine.hh, test/boost/group0_cmd_merge_test.cc, test/topology_experimental_raft/test_cdc_generation_data.py
The CDC generation data can be large and not fit in a single command. This pr splits it into multiple mutations by smartly picking a `mutation_size_threshold` and sending each mutation as a separate group 0 command.
Commands are sent sequentially to avoid concurrency problems. 
Topology snapshots contain only mutation of current CDC generation data but don't contain any previous or future generations. If a new generation of data is being broadcasted but hasn't been entirely applied yet, the applied part won't be sent in a snapshot. New or delayed nodes can never get the applied part in this scenario.
Send the entire cdc_generations_v3 table in the snapshot to resolve this problem.
A mechanism to remove old CDC generations will be introduced as a follow-up.
=> raft topology: send cdc generation data in parts

repair/reader.hh, repair/row_level.cc, replica/database.cc, replica/database.hh, test/boost/repair_test.cc
Consider a cluster with no data, e.g. in tests. When a new node is bootstrapped with repair we iterate over all (shard, table, range), read data from all the peer nodes for the range, look for any discrepancies and heal them. Even for small num_tokens (16 in the tests) the number of affected ranges (those we need to consider) amounts to total number of tokens in the cluster, which is 32 for the second node and 48 for the third. Multiplying this by the number of shards and the number of tables in each keyspace gives thousands of ranges. For each of them we need to follow some row level repair protocol, which includes several RPC exchanges between the peer nodes and creating some data structures on them. These exchanges are processed sequentially for each shard, there are …
=> repair: optimise  repair reader with different shard count

replica/table.cc, sstables/sstables_manager.cc
instead using the operator=(T&&) to assign an instance of `T` to a
shared_ptr, assign a new instance of shared_ptr to it.
unlike std::shared_ptr, seastar::shared_ptr allows us to move a value
into the existing value pointed by shared_ptr with operator=(). the
corresponding change in seastar is
https://github.com/scylladb/seastar/commit/319ae0b530107dce510c27f45d21b4ad696ef07d.
but this is a little bit confusing, as the behavior of a shared_ptr
should look like a pointer instead the value pointed by it. and this
could be error-prune, because user could use something like
```c++
p = std::string();
```
by accident, and expect that the value pointed by `p` is cleared.
and all copies of this shared_ptr are updated accordingly. what
he/she really wants is:
```c++
*p = std::string();
```
and the …
=> replica,sstable: do not assign a value to a shared_ptr

db/view/view.cc, db/view/view_updating_consumer.hh, mutation_rebuilder.hh, test/boost/mutation_test.cc, test/boost/view_build_test.cc
View update routines accept mutation objects.
But what comes out of staging sstable readers is a stream of mutation_fragment_v2 objects.
To build view updates after a repair/streaming, we have to convert the fragment stream into mutations. This is done by piping the stream to mutation_rebuilder_v2.
To keep memory usage limited, the stream for a single partition might have to be split into multiple partial mutation objects. view_update_consumer does that, but in improper way -- when the split/flush happens inside an active range tombstone, the range tombstone isn't closed properly. This is illegal, and triggers an internal error.
This patch fixes the problem by closing the active range tombstone (and reopening in the same position in the next mutation object).
The tombstone is closed just …
=> [backport 5.2] view: fix range tombstone handling on flushes in view_updating_consumer

db/view/view.cc, db/view/view_updating_consumer.hh, mutation/mutation_rebuilder.hh, test/boost/mutation_test.cc, test/boost/view_build_test.cc
View update routines accept mutation objects.
But what comes out of staging sstable readers is a stream of mutation_fragment_v2 objects.
To build view updates after a repair/streaming, we have to convert the fragment stream into mutations. This is done by piping the stream to mutation_rebuilder_v2.
To keep memory usage limited, the stream for a single partition might have to be split into multiple partial mutation objects. view_update_consumer does that, but in improper way -- when the split/flush happens inside an active range tombstone, the range tombstone isn't closed properly. This is illegal, and triggers an internal error.
This patch fixes the problem by closing the active range tombstone (and reopening in the same position in the next mutation object).
The tombstone is closed just …
=> [backport 5.3] view: fix range tombstone handling on flushes in view_updating_consumer

db/view/view.cc, db/view/view_updating_consumer.hh, mutation_rebuilder.hh, test/boost/mutation_test.cc, test/boost/view_build_test.cc
View update routines accept mutation objects.
But what comes out of staging sstable readers is a stream of mutation_fragment_v2 objects.
To build view updates after a repair/streaming, we have to convert the fragment stream into mutations. This is done by piping the stream to mutation_rebuilder_v2.
To keep memory usage limited, the stream for a single partition might have to be split into multiple partial mutation objects. view_update_consumer does that, but in improper way -- when the split/flush happens inside an active range tombstone, the range tombstone isn't closed properly. This is illegal, and triggers an internal error.
This patch fixes the problem by closing the active range tombstone (and reopening in the same position in the next mutation object).
The tombstone is closed just …
=> [backport 5.1] view: fix range tombstone handling on flushes in view_updating_consumer

scylla-gdb.py, test/scylla-gdb/test_misc.py
The command is to print interesting and/or hard-to-get-by-hand info about individual tables
=> Add `scylla table` to scylla-gdb

compaction/compaction.cc, dht/partition_filter.hh, readers/mutation_readers.cc, sstables/mx/reader.cc, test/boost/sstable_compaction_test.cc, test/boost/sstable_datafile_test.cc
Today, SSTable cleanup skips to the next partition, one at a time, when it finds that the current partition is no longer owned by this node.
That's very inefficient because when a cluster is growing in size, existing nodes lose multiple sequential tokens in its owned ranges. Another inefficiency comes from fetching index pages spanning all unowned tokens, which was described in https://github.com/scylladb/scylladb/issues/14317.
To solve both problems, cleanup will now use multi range reader, to guarantee that it will only process the owned data and as a result skip unowned data. This results in cleanup scanning an owned range and then fast forwarding to the next one, until it's done with them all. This reduces significantly the amount of data in the index caching, as index will only be …
=> Make SSTable cleanup more efficient by fast forwarding to next owned range

compaction/compaction_manager.cc, tasks/task_manager.hh, test/lib/sstable_utils.cc
Due to wrong order of stopping of compaction services, shutdown needs 
to wait until all compactions are complete, which may take really long. 
Moreover, test version of compaction manager does not abort task manager,
which is strictly bounded to it, but stops its compaction module. This results 
in tests waiting for compaction task manager's tasks to be unregistered, 
which never happens.
Stopping and aborting of compaction manager and task manager's compaction 
module are performed in a proper order.
=> Stop task manager compaction module properly

service/raft/group0_state_machine.cc, utils/UUID.hh
In d2a4079bbeef21d051d07e317d871ad54efd1896, `merger` was modified so that when we merge a command, `last_group0_state_id` is taken to be the maximum of the merged command's state_id and the current `last_group0_state_id`. This is necessary for achieving the same behavior as if the commands were applied individually instead of being merged -- where we take the maximum state ID from `group0_history` table which was applied until now (because the table is sorted using the state IDs and we take the greatest row).
However, a subtle bug was introduced -- the `std::max` function uses the `utils::UUID` standard comparison operator which is unfortunately not the same as timeuuid comparison that Scylla performs when sorting the `group0_history` table. So in rare cases it could return the *smaller* …
=> group0_state_machine: use correct comparison for timeuuids in `merger`

api/api-doc/error_injection.json, api/error_injection.cc, test/boost/error_injection_test.cc, test/pylib/rest_client.py, utils/error_injection.hh
Add `parameters` map to `injection_shared_data`. Now tests can attach string data to injections that can be read in injected code via `injection_handler`.
Closes #14521
=> utils: error injection: add a string-to-string map of injection's parameters

test/pylib/async_cql.py, test/topology/conftest.py, test/topology/test_random_tables.py
Provide a way to fetch all pages for `run_async`.
While there, move the code to a common helper module.
Fixes https://github.com/scylladb/scylladb/issues/14451
=> test/pylib: handle paging for run_async

test/boost/database_test.cc, test/boost/memtable_test.cc, test/lib/mutation_source_test.cc, test/lib/mutation_source_test.hh
Split long-runing database mutation tests.
At a trade-off with verbosity, split these sub-tests for the long running tests `database_with_data_in_sstables_is_a_mutation_source_`*.
Refs #13905
=> test/boost/database_test: split mutation sub-tests

db/hints/sync_point.cc, test/rest_api/test_hinted_handoff.py
Fixes #9405 
`sync_point` API provided with incorrect sync point id might allocate crazy amount of memory and fail with `std::bad_alloc`.
To fix this, we can check if the encoded sync point has been modified before decoding. We can achieve this by calculating a checksum before encoding, appending it to the encoded sync point, and compering it with a checksum calculated in `db::hints::decode` before decoding.
=> db: hints: add checksum to sync_point encoding

idl/replica_exception.idl.hh, replica/exceptions.cc, replica/exceptions.hh, service/storage_proxy.cc
Fixes #10447
This issue is an expected behavior. However, `abort_requested_exception` is not handled properly.
1. The node is drained.
2. `migration_manager::drain` is called and executes `_as.request_abort();`.
3. The coordinator sends read RPCs to the drained replica. On the replica side, `storage_proxy::handle_read` calls `migration_manager::get_schema_for_read`, which is defined like this:
```cpp
future<schema_ptr> migration_manager::get_schema_for_write(/* ... */) {
if (_as.abort_requested()) {
co_return coroutine::exception(std::make_exception_ptr(abort_requested_exception()));
}
/* ... */
```
So, `abort_requested_exception` is thrown.
4. RPC doesn't preserve information about its type, and it is converted to a string containing its error message.
5. It is rethrown as …
=> storage_proxy: silence abort_requested_exception on reads and writes

gms/feature_service.cc, test/topology_custom/test_deprecating_cluster_features.py
The feature check in `enable_features_on_startup` loads the list
of features that were enabled previously, goes over every one of them
and checks whether each feature is considered supported and whether
there is a corresponding `gms::feature` object for it (i.e. the feature
is "registered"). The second part of the check is unnecessary
and wrong. A feature can be marked as supported but its `gms::feature`
object not be present anymore: after a feature is supported for long
enough (i.e. we only support upgrades from versions that support the
feature), we can consider such a feature to be deprecated.
When a feature is deprecated, its `gms::feature` object is removed and
the feature is always considered enabled which allows to remove some
legacy code. We still consider this feature to be …
=> feature_service: handle deprecated features correctly in feature check

cql3/Cql.g, cql3/constants.cc, cql3/constants.hh, cql3/expr/expression.hh, cql3/expr/prepare_expr.cc, cql3/operation.cc, cql3/operation.hh, cql3/restrictions/statement_restrictions.cc, cql3/restrictions/statement_restrictions.hh, cql3/statements/update_statement.cc, cql3/util.hh, test/boost/expr_test.cc
`expression`'s default constructor is dangerous as an it can leak
into computations and generate surprising results. Fix that by
removing the default constructor.
This is made somewhat difficult by the parser generator's reliance
on default construction, and we need to expand our workaround
(`uninitialized<>`) capabilities to do so.
We also remove some incidental uses of default-constructed expressions.
=> cql3: expr: remove the default constructor

db/query_context.hh, db/system_keyspace.cc, db/system_keyspace.hh, main.cc, service/paxos/paxos_state.cc, service/paxos/paxos_state.hh, service/storage_proxy.cc, service/storage_proxy.hh, test/boost/cql_query_test.cc, test/boost/extensions_test.cc, test/boost/query_processor_test.cc, test/lib/cql_test_env.cc, test/lib/cql_test_env.hh
The "fix" is straightforward -- callers of system_keyspace::*paxos* methods need to get system keyspace from somewhere. This time the only caller is storage_proxy::remote that can have system keyspace via direct dependency reference.
=> Remove qctx from system.paxos table access methods

service/storage_service.cc, service/storage_service.hh
The set in question is read-and-delete-only and thus always empty. Originally it was removed by commit c9993f020d (storage_service: get rid of handle_state_replacing), but some dangling ends were left. Consequentially, the on_alive() callback can get rid of few dead if-else branches
=> Remove dead replacing_nodes_pending_ranges_updater manipulations

mutation/mutation_compactor.hh, mutation/mutation_fragment_stream_validator.hh, readers/mutation_readers.cc, test/boost/mutation_test.cc
The mutation compactor has a validator which it uses to validate the stream of mutation fragments that passes through it. This validator is supposed to validate the stream as it enters the compactor, as opposed to its compacted form (output). This was true for most fragment kinds except range tombstones, as purged range tombstones were not visible to
the validator for the most part.
This mistake was introduced by https://github.com/scylladb/scylladb/commit e2c9cdb576c2186719ce7181dd6619f1994e262e, which itself was a flawed attempt at fixing an error seen because purged tombstones were not terminated by the compactor.
This patch corrects this mistake by fixing the above problem properly: on page-cut, if the validator has an active tombstone, a closing tombstone is generated for it, to …
=> mutation/mutation_compactor: validate the input stream

conf/scylla.yaml, db/config.cc, db/config.hh, replica/database.cc
Fixes #14668
In #14668, we have decided to introduce a new `scylla.yaml` variable for the schema commitlog segment size and set it to 128MB. The reason is that segment size puts a limit on the mutation size that can be written at once, and some schema mutation writes are much larger than average, as shown in #13864. This `schema_commitlog_segment_size_in_mb variable` variable is now added to `scylla.yaml` and `db/config`.
Additionally,  we do not derive the commitlog sync period for schema commitlog anymore because schema commitlog runs in batch mode, so it doesn't need this parameter. It has also been discussed in #14668.
=> config: set schema_commitlog_segment_size_in_mb to 128 

multishard_mutation_query.cc, querier.cc, querier.hh, replica/database.cc, replica/database.hh, test/boost/querier_cache_test.cc
If semaphore mismatch occurs, check whether both semaphores belong
to user. If so, log a warning, log a `querier_cache_scheduling_group_mismatches` stat and drop cached reader instead of throwing an error.
Until now, semaphore mismatch was only checked in multi-partition queries.  The PR pushes the check to `querier_cache` and perform it on all `lookup_*_querier` methods.
The mismatch can happen if user's scheduling group changed during
a query. We don't want to throw an error then, but drop and reset
cached reader.
This patch doesn't solve a problem with mismatched semaphores because of changes in service levels/scheduling groups but only mitigate it.
Refers: https://github.com/scylladb/scylla-enterprise/issues/3182
Refers: https://github.com/scylladb/scylla-enterprise/issues/3050 …
=> semaphore mismatch: don't throw an error if both semaphores belong to user

test/boost/sstable_compaction_test.cc, test/lib/simple_schema.hh
in this series, we use different table names in simple_backlog_controller_test. this test is a test exercising sstables compaction strategies. and it creates and keeps multiple tables in a single test session. but we are going to add metrics on per-table basis, and will use the table's ks and cf as the counter's labels. as the metrics subsystem does not allow multiple counters to share the same label. the test will fail when the metrics are being added.
to address this problem, in this change
1. a new ctor is added for `simple_schema`, so we can create `simple_schema` with different names
2. use the new ctor in simple_backlog_controller_test
Fixes #14767
=> test: use different table names in simple_backlog_controller_test 

db/view/view_updating_consumer.hh, mutation/mutation.cc, mutation/mutation.hh, mutation/mutation_rebuilder.hh, test/boost/view_build_test.cc
Te view updating consumer uses `_buffer_size` to decide when to flush the accumulated mutations, passing them to the actual view building code. This `_buffer_size` is incremented every time a mutation fragment is consumed. This is not exact, as e.g. range tombstones are represented differently in the mutation object, than in the fragment, but it is good enough. There is one flaw however: `_buffer_size` is not incremented when consuming a partition-start fragment. This is when the mutation object is created in the mutation rebuilder. This is not a big problem when partition have many rows, but if the partitions are tiny, the error in accounting quickly becomes significant. If the partitions are empty, `_buffer_size` is not bumped at all for empty partitions, and any number of these can …
=> view_updating_consumer: account empty partitions memory usage

db/system_keyspace.cc, db/system_keyspace.hh, main.cc, message/messaging_service.cc, message/messaging_service.hh
This is to make m.s. initialization more solid and simplify sys.ks.::setup()
=> Init messaging service preferred IP cache via config

db/config.cc, db/config.hh, db/schema_features.hh, db/schema_tables.cc, db/schema_tables.hh, gms/feature_service.cc, gms/feature_service.hh, schema_mutations.cc, schema_mutations.hh, service/migration_manager.cc, service/migration_manager.hh, test/boost/schema_change_test.cc, test/boost/schema_registry_test.cc, tools/schema_loader.cc
Schema digest is calculated by querying for mutations of all schema
tables, then compacting them so that all tombstones in them are
dropped. However, even if the mutation becomes empty after compaction,
we still feed its partition key. If the same mutations were compacted
prior to the query, because the tombstones expire, we won't get any
mutation at all and won't feed the partition key. So schema digest
will change once an empty partition of some schema table is compacted
away.
Tombstones expire 7 days after schema change which introduces them. If
one of the nodes is restarted after that, it will compute a different
table schema digest on boot. This may cause performance problems. When
sending a request from coordinator to replica, the replica needs
schema_ptr of exact schema version …
=> schema_mutations, migration_manager: Ignore empty partitions in per-table digest

tools/scylla-sstable.cc, tools/scylla-types.cc, tools/utils.cc, tools/utils.hh
The scaffolding required to have a working scylla tool app, is considerable, leading to a large amount of boilerplate code in each such app.  This logic is also very similar across the two tool apps we have and would presumably be very similar in any future app. This PR extracts this logic into `tools/utils.hh` and introduces `tool_app_template`, which is similar to `seastar::app_template`  in that it centralizes all the option handling and more in a single class, that each tool has to just instantiate and then call `run()` to run the app.
This cuts down on the repetition and boilerplate in our current tool apps and make prototyping new tool apps much easier.
=> tools: introduce tool_app_template and migrate all tools to it

cql3/functions/castas_fcts.cc, cql3/functions/functions.cc, test/cql-pytest/cassandra_tests/functions/cast_fcts_test.py, test/cql-pytest/test_cast_data.py, test/cql-pytest/test_counter.py, test/cql-pytest/test_native_functions.py, types/types.cc
We have had support for COUNTER columns for quite some time now, but some functionality was left unimplemented - various internal and CQL functions resulted in "unimplemented" messages when used, and the goal of this series is to fix those issues. The primary goal was to add the missing support for CASTing counters to other types in CQL (issue #14501), but we also add the missing CQL  `counterasblob()` and `blobascounter()` functions (issue #14742).
As usual, the series includes extensive functional tests for these features, and one pre-existing test for CAST that used to fail now begins to pass.
Fixes #14501
Fixes #14742
=> cql: add missing functions for the COUNTER column type

locator/topology.cc, locator/topology.hh, repair/repair.cc, service/storage_service.cc, test/boost/locator_topology_test.cc, test/boost/network_topology_strategy_test.cc
It is possible that topology will contain nodes that are no longer normal token owners, so they don't need to be sync'ed with.
Fixes scylladb/scylladb#14793
=> storage_service: refresh_sync_nodes: restrict to normal token owners

docs/dev/topology-over-raft.md, locator/load_sketch.hh, locator/tablets.cc, locator/tablets.hh, service/storage_service.cc, service/tablet_allocator.cc, service/tablet_allocator.hh, service/topology_state_machine.cc, service/topology_state_machine.hh, test/boost/tablets_test.cc, test/topology_experimental_raft/test_tablets.py
This change makes tablet load balancing more efficient by performing
migrations independently for different tablets, and making new load
balancing plans concurrently with active migrations. 
The migration track is interrupted by pending topology change operations.
The coordinator executes the load balancer on edges of tablet state
machine transitions. This allows new migrations to be started as soon
as tablets finish streaming.
The load balancer is also continuously invoked as long as it produces
a non-empty plan. This is in order to saturate the cluster with
streaming. A single make_plan() call is still not saturating, due
to the way algorithm is implemented.
Overload of shards is limited by the fact that load balancer algorithm tracks
streaming concurrency on both source and target …
=> Concurrent tablet migration and balancing

db/schema_tables.cc, db/schema_tables.hh, db/system_keyspace.hh, replica/database.cc, service/migration_manager.cc, service/migration_manager.hh, service/paxos/paxos_state.cc, test/boost/column_mapping_test.cc
There are three methods in system_keyspace namespace that run queries over `system.scylla_table_schema_history` table. For that they use qctx which's not nice.
Fortunately, all the callers already have the system_keyspace& local variable or argument they can pass to those methods. Since the accessed table belongs to system keyspace, the latter declares the querying methods as "friends" to let them get private `query_processor& _qp` member
=> Avoid using qctx in schema_tables' column-mapping queries

service/storage_proxy.cc, service/storage_proxy.hh
Prevent stalls caused by query_partition_key_range_concurrent
nested calls when it never yields.
Fixes #14008
=> Prevent stalls in query_partition_key_range_concurrent

api/column_family.cc, api/column_family.hh, api/compaction_manager.cc, api/storage_service.cc, cdc/generation.cc, db/commitlog/commitlog_replayer.cc, db/view/view_update_generator.cc, db/virtual_tables.cc, main.cc, repair/repair.cc, repair/row_level.cc, replica/data_dictionary_impl.hh, replica/database.cc, replica/database.hh, replica/distributed_loader.cc, scylla-gdb.py, service/misc_services.cc, service/storage_service.cc, streaming/stream_session.cc, test/boost/cql_query_large_test.cc, test/lib/cql_test_env.cc
Maps related to column families in database are extracted
to a column_families_data class. Access to them is possible only 
through methods. All methods which may preempt hold rwlock 
in relevant mode, so that the iterators can't become invalid.
Fixes: #13290
=> Prevent invalidation of iterators over database::_column_families

db/system_keyspace.cc, db/system_keyspace.hh
Those without `_as` suffix are just marked non-static
The `..._as` ones are made class methods (now they are local to system_keyspace.cc)
After that the `..._as` ones are patched to use `this->` instead of `qctx`
=> De-static system_keyspace's [gs]et_scylla_local_param(_as)?

cdc/generation.cc, cdc/generation.hh, service/raft/group0_state_machine.cc, service/storage_service.cc, test/topology_experimental_raft/test_topology_ops.py
Fixes #14055
We add the CDC generation optimality check in `storage_service::raft_check_and_repair_cdc_streams` so that it doesn't create new generations when unnecessary. Since `generation_service::check_and_repair_cdc_streams` already has this check, we extract it to the new `is_cdc_generation_optimal` function to not duplicate the code.
After this change, multiple tasks could wait for a single generation change. Calling `signal` on `topology_state_machine.event` would't wake them all. Moreover, we must ensure the topology coordinator wakes when his logic expects it. Therefore, we change all `signal` calls on `topology_state_machine.event` to `broadcast`.
We delay the deletion of the `new_cdc_generation` request to the moment when the topology transition reaches the …
=> storage_service: raft_check_and_repair_cdc_streams: don't create a new generation if current one is optimal

replica/distributed_loader.cc, utils/directories.cc, utils/directories.hh
Skip over verification of owner and mode of the snapshots
sub-directory as this might race with scylla-manager
trying to delete old snapshots concurrently.
Fixes #12010
=> Skip mode validation for snapshots

gms/feature_service.cc, gms/feature_service.hh, idl/storage_service.idl.hh, main.cc, service/storage_service.cc, service/storage_service.hh, service/topology_state_machine.cc, service/topology_state_machine.hh, test/lib/cql_test_env.cc, test/topology/test_cluster_features.py, test/topology_experimental_raft/suite.yaml, test/topology_experimental_raft/test_raft_cluster_features.py
This PR implements the functionality of the raft-based cluster features needed to safely manage and enable cluster features, according to the cluster features on raft design doc.
Enabling features is a two phase process, performed by the topology coordinator when it notices that there are no topology changes in progress and there are some not-yet enabled features that are declared to be supported by all nodes:
1. First, a global barrier is performed to make sure that all nodes saw and persisted the same state of the `system.topology` table as the coordinator and see the same supported features of all nodes. When booting, nodes are now forbidden to revoke support for a feature if all nodes declare support for it, a successful barrier this makes sure that no node will restart and disable …
=> Cluster features on raft: topology coordinator + check on boot

api/gossiper.cc, cdc/generation.cc, cdc/generation_service.hh, gms/endpoint_state.hh, gms/feature_service.cc, gms/gossiper.cc, gms/gossiper.hh, gms/i_endpoint_state_change_subscriber.hh, repair/row_level.cc, service/load_broadcaster.hh, service/migration_manager.cc, service/migration_manager.hh, service/misc_services.cc, service/raft/raft_group_registry.cc, service/storage_service.cc, service/storage_service.hh, service/view_update_backlog_broker.hh, streaming/stream_manager.cc, streaming/stream_manager.hh, utils/UUID.hh
This series cleans up and hardens the endpoint locking design and implementation in the gossiper and endpoint-state subscribers.
We make sure that all notifications (expect for `before_change`, that apparently can be dropped) are called under lock_endpoint, as well as all calls to gossiper::replicate, to serialize endpoint_state changes across all shards.
An endpoint lock gets a unique permit_id that is passed to the notifications and passed back by them if the notification functions call the gossiper back for the same endpoint on paths that modify the endpoint_state and may acquire the same endpoint lock - to prevent a deadlock.
Fixes scylladb/scylladb#14838
Refs scylladb/scylladb#14471
=> Gossiper endpoint locking

api/api-doc/storage_service.json, api/storage_service.cc, repair/repair.cc, repair/task_manager_module.hh
This patch adds the ranges_parallelism option to repair restful API.
Users can use this option to optionally specify the number of ranges to repair in parallel per repair job to a smaller number than the Scylla core calculated default max_repair_ranges_in_parallel.
Scylla manager can also use this option to provide more ranges (>N) in a single repair job but only repairing N ranges_parallelism in parallel, instead of providing N ranges in a repair job.
To make it safer, unlike the PR #4848, this patch does not allow user to exceed the max_repair_ranges_in_parallel.
Fixes #4847
=> repair: Add ranges_parallelism option

idl/storage_service.idl.hh, message/messaging_service.cc, message/messaging_service.hh, service/raft/group0_state_machine.cc, service/raft/group0_state_machine.hh, service/raft/raft_group0_client.cc, service/raft/raft_group0_client.hh
Hold a (newly added) group0_state_machine gate
that is closed and waited on in group0_state_machine::abort()
To prevent use-after-free when destroying the group0_state_machine
while transfer_snapshot runs.
Fixes #14907
Also, use an abort_source in group0_state_machine
to abort an ongoing transfer_snapshot operation
on group0_state_machine::abort()
=> group0_state_machine: await transfer_snapshot

cql3/untyped_result_set.cc, db/system_keyspace.cc, db/system_keyspace.hh, gms/feature_service.cc, service/storage_service.cc, service/topology_state_machine.cc, service/topology_state_machine.hh
Currently, feature service uses `system_keyspace::load_topology_state`
to load information about features from the `system.topology` table.
This function implicitly assumes that it is called after schema
commitlog replay and will correspond to the state of the topology state
machine after some command is applied.
However, feature check happens before the commitlog replay. If some
group 0 command consists of multiple mutations that are not applied
atomically, the `load_topology_state` function may fail to construct a
`service::topology` object based on the table state. Moreover, this
function not only checks `system.topology` but also
`system.cdc_generations_v3` - in the case of the issue, the entry that
was loaded from the this table didn't contain the `num_ranges`
parameter.
In order to …
=> feature_service: don't load whole topology state to check features

repair/repair.cc, repair/task_manager_module.hh
Delete unused shard_repair_task_impl members and incorrectly used method's argument.
=> repair: delete unused fields

compaction/compaction_manager.cc, compaction/compaction_manager.hh, compaction/task_manager_module.cc, compaction/task_manager_module.hh, replica/database.hh, replica/table.cc, test/rest_api/task_manager_utils.py, test/rest_api/test_compaction_task.py
All compaction task executors, except for regular compaction one, 
become task manager compaction tasks. 
Creating and starting of major_compaction_task_executor is modified
to be consistent with other compaction task executors.
=> Task manager tasks covering compaction group compaction

replica/database.cc
If some state update in database::add_column_family throws,
info about a column family would be inconsistent.
Undo already performed operations in database::add_column_family
when one throws.
Fixes: #14666.
=> Make database::add_column_family exception safe.

main.cc, service/storage_service.cc, service/storage_service.hh, service/tablet_allocator.cc, service/tablet_allocator.hh, test/boost/tablets_test.cc, test/lib/cql_test_env.cc, test/lib/cql_test_env.hh
The metrics are registered on-demand when load-balancer is invoked, so that only leader exports the metrics. When leader changes, the old leader will stop exporting.
The metrics are divided into two levels: per-dc and per-node. In prometheus, they will have appropriate labels for dc and host_id values.
=> Export tablet load-balancer metrics

cql3/query_processor.cc, cql3/query_processor.hh, cql3/statements/create_function_statement.cc, db/schema_tables.cc, lang/wasm.cc, lang/wasm.hh, lang/wasm_instance_cache.hh, main.cc, replica/database.cc, replica/database.hh, test/lib/cql_test_env.cc
This makes it possible to remove remaining users of the global qctx.
The thing is that db::schema_tables code needs to get wasm's engine, alien runner and instance cache to build wasm context for the merged function or to drop it from cache in the opposite case. To get the wasm stuff, this code uses global qctx -> query_processor -> wasm chain. However, the functions (un)merging code already has the database reference at hand, and its natural to get wasm stuff from it, not from the q.p. which is not available
So this PR packs the wasm engine, runner and cache on sharded<wasm::manager> instance, makes the manager be referenced by both q.p. and database and removes the qctx from schema tables code
=> Make replica::database and cql3::query_processor share wasm manager

cmake/mode.RELEASE.cmake
before this change, we use generator expression to initialize CMAKE_CXX_FLAGS_RELEASE, this has two problems:
1. the generator expression is not expanded when setting a regular variable.
2. the ending ">" is missing in one of the generator expression.
3. the parameters are not separated with ";"
so address them, let's just
* use `add_compile_options()` directly, as the corresponding `mode.${build_mode}.cmake` is only included when the "${build_mode}" is used.
* add comma in between the command line options.
* add the missing closing ">"
=> build: cmake: fixes for the release build

compaction/compaction_manager.cc, compaction/compaction_manager.hh, compaction/leveled_compaction_strategy.cc, sstables/sstables.cc, sstables/sstables.hh, test/boost/sstable_compaction_test.cc, test/boost/sstable_test.hh
Currently `sstable_requiring_cleanup` is updated using `compacting_sstable_registration`, but that mechanism is not used by offstrategy compaction, leading to #14304.
This series introduces `compaction_manager::on_compaction_completion` that intercepts the call
to the table::on_compaction_completion. This allows us to update `sstable_requiring_cleanup` right before the compacted sstables are deleted, making sure they are no leaked to `sstable_requiring_cleanup`, which would hold a reference to them until cleanup attempts to clean them up.
`cleanup_incremental_compaction_test` was adjusted to observe the sstables `on_delete` (by adding a new observer event) to detect the case where cleanup attempts to delete the leaked sstables and fails since they were already deleted from the file system …
=> Update sstable_requiring_cleanup on compaction completion

alternator/executor.cc, auth/common.cc, auth/service.cc, cql3/query_processor.cc, cql3/query_processor.hh, db/tags/utils.cc, redis/keyspace_utils.cc, service/migration_manager.hh, table_helper.cc, test/boost/cql_query_test.cc, test/boost/database_test.cc, test/boost/memtable_test.cc, test/boost/row_cache_test.cc, test/boost/schema_change_test.cc, test/lib/cql_test_env.cc, thrift/handler.cc
The `system.group0_history` table provides useful descriptions for each command committed to Raft group 0. One way of applying a command to group 0 is by calling `migration_manager::announce`. This function has the `description` parameter set to empty string by default. Some calls to `announce` use this default value which causes `null` values in `system.group0_history`. We want `system.group0_history` to have an actual description for every command, so we change all default descriptions to reasonable ones.
Going further, We remove the default value for the `description` parameter of `migration_manager::announce` to avoid using it in the future. Thanks to this, all commands in `system.group0_history` will have a non-null description.
Fixes #13370
=> migration_manager: announce: provide descriptions for all calls

test.py, test/object_store/conftest.py, test/pylib/minio_server.py
there is chance that the default port of 9000 has been used on the host running the test, in that case, we should try to use another available port.
so, in this change, we try ports in the ranges of [9000, 9000+1000), and use the first one which is not connectable.
Fixes #14985
=> s3/client: check for available port before starting minio server

gms/gossiper.cc, gms/gossiper.hh
Currently, `mark_dead` is called with null_permit_id
from `convict`, and in this case, by contract,
it should lock the endpoint, same as `mark_as_shutdown`.
This change somehow escaped #14845 so it amends it.
Fixes #14838
=> gossiper: convict: lock_endpoint

test/boost/cdc_test.cc, test/boost/cql_query_test.cc, test/boost/filtering_test.cc, test/boost/json_cql_query_test.cc, test/boost/querier_cache_test.cc, test/boost/reader_concurrency_semaphore_test.cc, test/boost/row_cache_test.cc, test/lib/cql_test_env.cc, test/lib/cql_test_env.hh, test/lib/random_schema.cc
There are some asserting checks for keyspace and table existence on cql_test_env that perform some one-linee work in a complex manner, tests can do better on their own. Removing it makes cql_test_env simpler
refs: #2795
=> Remove some stale sugar from cql_test_env

test/lib/cql_test_env.cc, test/lib/cql_test_env.hh
To add a sharded service to the cql_test_env one needs to patch it in 5 or 6 places
- add cql_test_env reference
- add cql_test_env constructor argument
- initialize the reference in initializer list
- add service variable to do_with method
- pass the variable to cql_test_env constructor
- (optionally) export it via cql_test_env public method
Steps 1 through 5 are annoying, things get much simpler if look like
- add cql_test_env variable
- (optionally) export it via cql_test_env public method
This is what this PR does
refs: #2795
=> Relax cql_test_env services maintenance

replica/compaction_group.hh, replica/table.cc, sstables/sstable_set.cc, sstables/sstable_set.hh, sstables/sstable_set_impl.hh, test/boost/sstable_compaction_test.cc, test/boost/sstable_datafile_test.cc, test/boost/sstable_set_test.cc
and use that in compaction_group, rather than
respective accumulators of its own.
This is part of of larger series to make cache updates exception safe.
Refs #14043
=> sstable_set: maintain bytes on disk

compaction/compaction.cc, replica/database.hh, replica/distributed_loader.cc, replica/table.cc, sstables/sstable_directory.cc, sstables/sstable_directory.hh, sstables/sstables.cc, sstables/sstables.hh, sstables/sstables_manager.cc, sstables/sstables_manager.hh, sstables/storage.cc, sstables/storage.hh, test/boost/database_test.cc, test/boost/sstable_compaction_test.cc, test/boost/sstable_directory_test.cc, test/boost/sstable_move_test.cc, test/lib/sstable_test_env.hh, test/lib/test_services.hh, tools/schema_loader.cc, tools/scylla-sstable.cc
An sstable can be in one of several states -- normal, quarantined, staging, uploading. Right now this "state" is hard-wired into sstable's path, e.g. quarantined sstable would sit in e.g. /var/lib/data/ks-cf-012345/quarantine/ directory. Respectively, there's a bunch of directory names constexprs in sstables.hh defining each "state". Other than being confusing, this approach doesn't work well with S3 backend. Additionally, there's snapshot subdir that adds to the confusion, because snapshot is not quite a state.
This PR converts "state" from constexpr char* directories names into a enum class and patches the sstable creation, opening and state-changing API to use that enum instead of parsing the path.
refs: #13017 
refs: #12707
=> Maintain sstable state explicitly

cmake/build_submodule.cmake
in this series, the build of rpm and deb from submodules is fixed:
1. correct the path of reloc package
2. add the dependency of reloc package to deb/rpm build targets
=> build: cmake: fix the build of rpm/deb from submodules

compaction/table_state.hh, db/config.cc, db/config.hh, locator/token_metadata.cc, locator/topology.hh, main.cc, replica/compaction_group.hh, replica/database.cc, replica/database.hh, replica/table.cc, scylla-gdb.py, test.py, test/boost/database_test.cc, test/boost/tablets_test.cc, test/lib/cql_test_env.cc, test/lib/test_services.cc, tools/scylla-sstable.cc
Compaction group is the data plane for tablets, so this integration
allows each tablet to have its own storage (memtable + sstables).
A crucial step for dynamic tablets, where each tablet can be worked
on independently.
There are still some inefficiencies to be worked on, but as it is,
it already unlocks further development.
```
INFO  2023-07-27 22:43:38,331 [shard 0] init - loading tablet metadata
INFO  2023-07-27 22:43:38,333 [shard 0] init - loading non-system sstables
INFO  2023-07-27 22:43:38,354 [shard 0] table - Tablet with id 0 present for ks.cf
INFO  2023-07-27 22:43:38,354 [shard 0] table - Tablet with id 2 present for ks.cf
INFO  2023-07-27 22:43:38,354 [shard 0] table - Tablet with id 4 present for ks.cf
INFO  2023-07-27 22:43:38,354 [shard 0] table - Tablet with id 6 present …
```
=> Wire tablet into compaction group

CMakeLists.txt, cmake/mode.COVERAGE.cmake, cmake/mode.SANITIZE.cmake
to mirror the build modes supported by `configure.py`.
=> build: cmake: support Coverage and Sanitize build modes

replica/distributed_loader.cc, utils/directories.cc, utils/directories.hh
This mini-series backports the fix for #12010 along with low-risk patches it depends on.
Fixes: #12010
=> [Backport-5.1] distributed_loader: process_sstable_dir: do not verify snapshots

sstables/mx/writer.cc, test/boost/sstable_compaction_test.cc, test/lib/sstable_utils.cc, test/lib/sstable_utils.hh
in this series, we also print the sstable name and pk when writing a tombstone whose local_deletion_time (ldt for short) is greater than INT32_MAX which cannot be represented by an uint32_t.
Fixes #15015
=> sstable, test: log sstable name and pk when capping local_deletion_time 

api/storage_service.cc, db/config.cc, db/config.hh, db/system_keyspace.cc, docs/dev/topology-over-raft.md, service/storage_service.cc, service/storage_service.hh, service/topology_state_machine.hh, test/pylib/manager_client.py, test/topology_experimental_raft/suite.yaml, test/topology_experimental_raft/test_raft_ignore_nodes.py
We add support for `--ignore-dead-nodes` in `raft_removenode` and `--ignore-dead-nodes-for-replace` in `raft_replace`. For now, we allow passing only host ids of the ignored nodes. Supporting IPs is currently impossible because `raft_address_map` doesn't provide a mapping from IP to a host id.
The main steps of the implementation are as follows:
- add the `ignore_nodes` column to `system.topology`,
- set the `ignore_nodes` value of the topology mutation in `raft_removenode` and `raft_replace`,
- extend `service::request_param` with alternative types that allow storing a set of ids of the ignored nodes,
- load `ignore_nodes` from `system.topology` into `request_param` in `system_keyspace::load_topology_state`,
- add `ignore_nodes` to `exclude_nodes` in …
=> raft topology: support --ignore-dead-nodes in removenode and replace

api/failure_detector.cc, db/hints/manager.cc, gms/endpoint_state.hh, gms/gossiper.cc, gms/gossiper.hh, service/migration_manager.cc, service/storage_service.cc
Currently he gossiper marks endpoint_state objects as alive/dead.
I some cases the endpoint_state::is_alive function is checked but in many other cases
gossiper::is_alive(endpoint) is used to determine if the endpoint is alive.
This series removed the endpoint_state::is_alive state and moves all the logic to gossiper::is_alive
that bases its decision on the endpoint having an endpoint_state and being in the _live_endpoints set.
For that, the _live_endpoints is made sure to be replicated to all shards when changed
and the endpoint_state changes are serialized under lock_endpoint, and also making sure that the
endpoint_state in the _endpoint_states_map is never updated in place, but rather a temporary copy is changed
and then safely replicated using gossiper::replicate
Refs …
=> Base node liveliness consistently on gossiper::is_alive

api/api-doc/storage_service.json, locator/token_metadata.cc
And verify the they returned host_id isn't null.
Call on_internal_error_noexcept in that case
since all token owners are expected to have their
host_id set. Aborting in testing would help fix
issues in this area.
Fixes scylladb/scylladb#14843
Refs scylladb/scylladb#14793
=> token_metadata::get_endpoint_to_host_id_map_for_reading: restrict to token owners

db/hints/manager.cc, db/hints/manager.hh, locator/token_metadata.cc, service/storage_service.cc, test.py, test/pylib/manager_client.py, test/pylib/random_tables.py, test/pylib/rest_client.py, test/topology/conftest.py, test/topology_experimental_raft/test_fencing.py
In this PR a simple test for fencing is added. It exercises the data plane, meaning if it somehow happens that the node has a stale topology version, then requests from this node will get an error 'stale topology'. The test just decrements the node version manually through CQL, so it's quite artificial. To test a more real-world scenario we need to allow the topology change fiber to sometimes skip unavailable nodes. Now the algorithm fails and retries indefinitely in this case.
The PR also adds some logs, and removes one seemingly redundant topology version increment, see the commit messages for details.
=> raft: add fencing tests

replica/distributed_loader.cc, utils/directories.cc, utils/directories.hh
This mini-series backports the fix for #12010 along with low-risk patches it depends on.
Fixes: #12010
=> [Backport 5.2] distributed_loader: process_sstable_dir: do not verify snapshots

service/storage_proxy.cc, service/storage_proxy.hh
As `create_write_response_handler` on this path accepts
an `inet_address_vector_replica_set` that corresponds to the
effective_replication_map_ptr in the paxos_response_handler,
but currently, the function retrieves a new
effective_replication_map_ptr
that may not hold all the said endpoints.
Fixes scylladb/scylladb#15138
=> paxos_response_handler: carry effective replication map

service/storage_proxy.cc, service/storage_proxy.hh
The effective_replication_map_ptr passed to
`create_write_response_handler` by `send_batchlog_mutation`
must be synchronized with the one used to calculate
_batchlog_endpoints to ensure they use the same topology.
Fixes scylladb/scylladb#15147
=> storage_proxy: mutate_atomically_result: carry effective replication map down to create_write_response_handler

api/api.cc, api/api_init.hh, api/storage_service.cc, api/storage_service.hh, cdc/generation.cc, cdc/generation_service.hh, main.cc, service/raft/group0_state_machine.cc, service/raft/group0_state_machine.hh, service/raft/raft_group0.cc, service/raft/raft_group0.hh, service/storage_service.cc, service/storage_service.hh, test/lib/cql_test_env.cc
The main goal of this PR is to stop cdc_generation_service from calling system_keyspace::bootstrap_complete(). The reason why it's there is that gen. service doesn't want to handle generation before node joined the ring or after it was decommissioned. The cleanup is done with the help of storage_service->cdc_generation_service explicit dependency brought back and this, in turn, suddenly freed the raft and API code from the need to carry cdc gen. service reference around.
=> Restore storage_service -> cdc_generation_service dependency

api/gossiper.cc, gms/gossiper.cc, gms/gossiper.hh, test/rest_api/test_gossiper.py
Modeled after get_live_members_synchronized,
get_unreachable_members_synchronized calls
replicate_live_endpoints_on_change to synchronize
the state of unreachable_members on all shards.
Fixes #12261
Fixes #15088
Also, add rest_api unit test for those apis
=> gossiper: add get_unreachable_members_synchronized and use over api

gms/gossip_digest_syn.cc, gms/gossip_digest_syn.hh, gms/gossiper.cc, gms/gossiper.hh, idl/gossip_digest.idl.hh, main.cc, service/raft/raft_group0.cc, test/manual/message.cc, test/topology_custom/suite.yaml, test/topology_custom/test_different_group0_ids.py
The user can bootstrap 3 different clusters and then connect them (#14448). When these clusters start gossiping, their token rings will be merged, but there will be 3 different group 0s in there. It results in a corrupted cluster.
We need to prevent such situations from happening in clusters which don't use Raft-based topology
-------
Gossiper service sets its group0 id on startup if it is stored in `scylla_local` or sets it during joining group0.
Send group0_id (if it is set) when the node tries to initiate the gossip round. When a node gets gossip_digest_syn it checks if its group0 id equals the local one and if not, the message is discarded.
Fixes #14448.
Performed manual tests with the following scenario:
1. setup a cluster of two nodes (one compiled with and one without this patch) …
=> gossip: add group0_id attribute to gossip_digest_syn

replica/database.hh, replica/table.cc, test/boost/cql_query_test.cc, test/boost/sstable_compaction_test.cc, test/lib/cql_assertions.cc, test/lib/cql_assertions.hh, test/lib/cql_test_env.cc, test/lib/cql_test_env.hh
The cql_test_env has a virtual require_column_has_value() helper that better fits cql_assertions crowd. Also, the helper in question duplicates some existing code, so it can also be made shorter (and one class table helper gets removed afterwards)
=> Move cell assertion from cql_test_env to cql_assertions

gms/gossiper.cc
Change 6449c59 brought back abort on listener failure, but this causes crashes when listeners hit expected errors like gate_closed.
Detect shutdown usig the gossiper _abort_source
and in this case just log a warning about the errors but do not abort.
Fixes scylladb/scylladb#15031
=> gossiper: apply_new_states: tolerate listener errors during shutdown

docs/operating-scylla/nodetool-commands/removenode.rst, service/raft/raft_address_map.hh, service/storage_service.cc, service/storage_service.hh, test/raft/raft_address_map_test.cc, test/topology_experimental_raft/test_raft_ignore_nodes.py
We want to stop supporting IPs for `--ignore-dead-nodes` in `raft_removenode` and `--ignore-dead-nodes-for-replace` for
`raft_replace`. However, we shouldn't remove these features without the deprecation period because the original `removenode` and `replace` operations still support them. So, we add them for now.
The `IP -> Raft ID` translation is done through the new `raft_address_map::find_by_addr` member function.
We update the documentation to inform about the deprecation of the IP support for `--ignore-dead-nodes`.
Fixes #15126
=> raft topology: add and deprecate support for --ignore-dead-nodes with IPs

gms/gossiper.cc, gms/gossiper.hh
Use common code to notify subscribers on_dead
from remove_endpoint() and from mark_dead().
Modeled after do_on_change_notifications.
Refs https://github.com/scylladb/scylladb/pull/15179#discussion_r1306969125
=> Gossiper: do_on_dead_notifications

alternator/executor.cc, api/failure_detector.cc, cdc/generation.cc, cdc/generation_service.hh, db/virtual_tables.cc, gms/endpoint_state.hh, gms/feature_service.cc, gms/gossiper.cc, gms/gossiper.hh, gms/i_endpoint_state_change_subscriber.hh, repair/row_level.cc, replica/table.cc, scylla-gdb.py, service/load_broadcaster.hh, service/migration_manager.cc, service/migration_manager.hh, service/raft/raft_group0.cc, service/raft/raft_group_registry.cc, service/storage_service.cc, service/storage_service.hh, service/view_update_backlog_broker.hh, streaming/stream_manager.cc, streaming/stream_manager.hh
This series ensures that endpoint state changes (for each single endpoint) are applied to the gossiper endpoint_state_map as a whole and on all shards.
Any failure in the process will keep the existing endpoint state intact.
Note that verbs that modify the endpoint states of multiple endpoints may still succeed to modify some of them before hitting an error and those changes are committed to the endpoint_state_map, so we don't ensure atomicity when updating multiple endpoints' states.
Fixes scylladb/scylladb#14794
Fixes scylladb/scylladb#14799
=> Gossiper: provide strong exception safety for endpoint state changes

gms/feature_service.cc, gms/feature_service.hh, idl/storage_service.idl.hh, service/raft/group0_state_machine.cc, service/storage_service.cc, service/storage_service.hh, service/topology_state_machine.cc, service/topology_state_machine.hh, test/topology/test_cluster_features.py, test/topology_experimental_raft/test_raft_cluster_features.py
This PR collects followups described in #14972:
- The `system.topology` table is now flushed every time feature-related columns are modified. This is done because of the feature check that happens before the schema commitlog is replayed.
- The implementation now guarantees that, if all nodes support some feature as described by the `supported_features` column, then support for that feature will not be revoked by any node.
Previously, in an edge case where a node is the last one to add support for some feature `X` in `supported_features` column, crashes before applying/persisting it and then restarts without supporting `X`, it would be allowed to boot anyway and would revoke support for the `X` in `system.topology`.
The existing behavior, although counterintuitive, was safe - the topology …
=> Cluster features on raft: topology coordinator + check on boot followups

replica/table.cc, sstables/open_info.hh, sstables/sstable_directory.cc, sstables/sstables.cc, tools/scylla-sstable.cc
to lower the programmer's cognitive load. as programmer might want
to pass the full path as the `fname` when calling
`make_descriptor(sstring sstdir, sstring fname)`, but this overload
only accepts the filename component as its second parameter. a
single `path` parameter would be easier to work with.
Refs #15187
=> sstables: change make_descriptor() to accept fs::path

configure.py, db/cache_tracker.hh, db/config.cc, db/config.hh, replica/database.cc, row_cache.cc, sstables/index_reader.hh, sstables/partition_index_cache.hh, sstables/partition_index_cache_stats.hh, sstables/sstables.cc, test/boost/CMakeLists.txt, test/boost/cache_algorithm_test.cc, test/boost/cached_file_test.cc, test/boost/sstable_mutation_test.cc, test/boost/sstable_partition_index_cache_test.cc, test/boost/suite.yaml, test/perf/perf_fast_forward.cc, utils/cached_file.hh, utils/cached_file_stats.hh, utils/lru.hh
Index caching was disabled by default because it caused performance regressions
for some small-partition workloads. See https://github.com/scylladb/scylladb/issues/11202.
However, it also means that there are workloads which could benefit from the
index cache, but (by default) don't.
As a compromise, we can set a default limit on the memory usage of index cache,
which should be small enough to avoid catastrophic regressions in
small-partition workloads, but big enough to accommodate workloads where
index cache is obviously beneficial.
This series adds such a configurable limit, sets it to to 0.2 of total cache memory by default,
and re-enables index caching by default.
Fixes #15118
=> config: add index_cache_fraction

gms/gossiper.cc, gms/gossiper.hh, utils/atomic_vector.hh
This series cleans up gossiper.
Methods that do not change the gossiper object are marked as const.
Dead code is removed.
=> Gossiper: mark const methods and remove dead code

configure.py
instead of flattening the functions into the script, let's structure them into functions. so they can be reused. and more maintainable this way.
Refs #15241
=> build: extract generate_compdb() out

compaction/compaction_manager.cc, compaction/compaction_manager.hh, tasks/task_manager.cc, tasks/task_manager.hh, tasks/test_module.hh, test/boost/sstable_compaction_test.cc
Passing the gate_closed_exception to the task promise
ends up with abandoned exception since no-one is waiting
for it.
Instead, enter the gate when the task is made
so it will fail make_task if the gate is already closed.
Fixes scylladb/scylladb#15211
In addition, this series adds a private abort_source for each task_manager module
(chained to the main task_manager::abort_source) and abort is requested on task_manager::module::stop().
gate holding in compaction_manager is hardened
and makes sure to stop compaction_manager and task_manager in sstable_compaction_test cases.
=> task_manager: module: make_task: enter gate when the task is created

test/boost/cql_query_test.cc
Some tests use non-threaded do_with_cql_env() and wrap the inner lambda with seastar::async(). The cql env already provides a helper for that
=> Explicitly use do_with_cql_env_thread in query test

test/pylib/manager_client.py, test/pylib/rest_client.py, test/topology/suite.yaml, test/topology/test_gossiper.py, test/topology/test_topology_remove_decom.py
Add tests for gossiper/endpoint/live and gossiper/endpoint/down
which run only in release mode.
Enable test_remove_node_with_concurrent_ddl and fix types and
variables names used by it, so that they can be reused in gossiper 
test.
Fixes: #15223.
=> test: topology: add tests for gossiper/endpoint/live and gossiper/endpoint/down

db/system_keyspace.cc, docs/dev/topology-over-raft.md, service/storage_service.cc, service/topology_state_machine.cc, service/topology_state_machine.hh, test/cql-pytest/test_cdc.py, test/topology_experimental_raft/suite.yaml, test/topology_experimental_raft/test_cdc_generation_publishing.py, test/topology_experimental_raft/test_topology_ops.py
Currently, the topology coordinator has the `topology::transition_state::publish_cdc_generation` state responsible for publishing the already created CDC generations to the user-facing description tables. This process cannot fail as it would cause some CDC updates to be missed. On the other hand, we would like to abort the `publish_cdc_generation` state when bootstrap aborts. Of course, we could also wait until handling this state finishes, even in the case of the bootstrap abort, but that would be inefficient. We don't want to unnecessarily block topology operations by publishing CDC generations.
The solution proposed by this PR is to remove the `publish_cdc_generation` state completely and introduce a new background fiber of the topology coordinator -- `cdc_generation_publisher` -- that …
=> raft topology: replace publish_cdc_generation with a bg fiber

db/system_keyspace.cc, db/system_keyspace.hh, locator/snitch_base.hh, main.cc, repair/repair.cc, service/storage_service.cc, test/lib/cql_test_env.cc
The local node's dc:rack pair is cached on system keyspace on start. However, most of other code don't need it as they get dc:rack from topology or directly from snitch. There are few places left that still mess with sysks cache, but they are easy to patch. So after this patch all the core code uses two sources of dc:rack -- topology / snitch -- instead of three.
=> Don't cache dc:rack on system keyspace local cache

dist/debian/debian_files_gen.py
so we can point `debian_files_gen.py` to builddir other than
'build', and can optionally use other output directory. this would
help to reduce the number of "magic numbers" in our building system.
Refs https://github.com/scylladb/scylladb/issues/15241
=> dist/debian: add command line option for builddir 

configure.py, dist/debuginfo/scripts/create-relocatable-package.py, scripts/create-relocatable-package.py
this series adds `--node-exporter-dir` and `--build-dir` options to `create-relocatable-package.py`. this enables us to use create relocatable package from arbitrary build directories.
Refs #15241
=> create-relocatable-package.py: add --node-exporter-dir and --build-dir options

docs/getting-started/installation-common/unified-installer.rst
in this series, we try to improve `unified-installer.rst`
- encourage user to install smaller package
- run `./install.sh` directly instead relying on that `sh` points to `bash`
=> docs: improve command line samples in unified-installer.rst

test/boost/s3_test.cc, test/lib/test_services.cc, test/object_store/conftest.py, test/perf/perf_s3_client.cc, test/pylib/minio_server.py
Currently minio starts with a bucket that has public anonymous access. Respectively, all tests use unsigned S3 requests. That was done for simplicity, and its better to apply some policy to the bucket and, consequentially, make tests sign their requests.
Other than the obvious benefit that we test requests signing in unit tests, another goal of this PR is to make it possible to simulate and test various error paths locally, e.g. #13745 and #13022
=> Stop using anonymous minio bucket for tests

mutation/mutation_partition.cc, mutation_query.hh, query-request.hh, replica/mutation_dump.cc, service/storage_proxy.cc, test/cql-pytest/test_select_from_mutation_fragments.py, test/pylib/manager_client.py, test/pylib/rest_client.py, test/pylib/scylla_cluster.py, test/topology_custom/test_read_repair.py, tools/scylla-sstable.cc
Currently, mutation query on replica side will not respond with a result which doesn't have at least one live row. This causes problems if there is a lot of dead rows or partitions before we reach a live row, which stem from the fact that resulting reconcilable_result will be large:
1. Large allocations.  Serialization of reconcilable_result causes large allocations for storing result rows in std::deque
2. Reactor stalls. Serialization of reconcilable_result on the replica side and on the coordinator side causes reactor stalls. This impacts not only the query at hand. For 1M dead rows, freezing takes 130ms, unfreezing takes 500ms. Coordinator  does multiple freezes and unfreezes. The reactor stall on the coordinator side is >5s
3. Too large repair mutations. If reconciliation works on …
=> database, storage_proxy: Reconcile pages with dead rows and partitions incrementally

CMakeLists.txt, dist/CMakeLists.txt
this change allows CMake to build the dist tarball for a certain build.
Refs https://github.com/scylladb/scylladb/issues/15241
=> build: cmake: add packaging support 

gms/gossiper.cc, gms/gossiper.hh, service/storage_service.cc
This function practically returned true from inception.
In d38deef499f72d4f4bd629e134fb15b750db6d6c
it started using messaging_service().knows_version(endpoint)
that also returns `true` unconditionally, to this day
So there's no point calling it since we can assume
that `uses_host_id` is true for all versions.
=> gossiper: get rid of uses_host_id

cmake/add_version_library.cmake, cmake/build_submodule.cmake, tools/CMakeLists.txt
in this series, the packaging of tools modules are improved:
- package cqlsh also. as cqlsh should be redistributed as a part of the unified package
- use ${arch} in the postfix of the python3 package. the python3 package is not architecture independent.
- set the version with tide for `Scylla_VERSION`, so it can be reused elsewhere.
Refs #15241
=> build: cmake: package cqlsh and fix the noarch postfix of python3 package

gms/gossiper.cc, gms/gossiper.hh
Many of the gossiper internal functions currently use seastar threads for historical reasons,
but since they are short living, the cost of spawning a seastar thread for them is excessive
and they can be simplified and made more efficient using coroutines.
=> Gossiper: replace seastar threads with coroutines

configure.py, unified/build_unified.sh
in this series, `unified/build_unified.sh` is improved in couple perspectives:
1. add `--build-dir` option, so we don't hardwire the build directory to the naming convention of `build/$mode`.
2. `--pkgs` is respected. this allows the caller to specify the paths to the dist tarballs instead of hardwiring to the paths defined in this script
these changes give us more flexibility when building unified package, and enable us to switch over to CMake based building system,
Refs #15241
=> unified: add --build-dir option and respect --pkgs

db/batchlog_manager.cc, db/batchlog_manager.hh, main.cc, test/lib/cql_test_env.cc
This code is now spread over main and differs in cql_test_env. The PR unifies both places and makes the manager start-stop look standard
refs: #2795
=> Sanitize batchlog manager start/stop

cmake/build_submodule.cmake, dist/CMakeLists.txt
a new target "dist-unified" is added, so that CMake can build unified
package, which is a bundle of all subcomponents, like cqlsh, python3,
jmx and tools.
Fixes #15241
=> build: cmake: add packaging support

test/boost/s3_test.cc, utils/s3/client.cc, utils/s3/client.hh
The added metrics include:
- http client metrics, which include the number of connections, the number of active connections and the number of new connections made so far
- IO metrics that mimic those for traditional IO -- total number of object read/write ops, total number of get/put/uploaded bytes and individual IO request delay (round-trip, including body transfer time)
fixes: #13369
=> Add metrics to S3 client

docs/dev/topology-over-raft.md, idl/storage_service.idl.hh, locator/abstract_replication_strategy.cc, locator/abstract_replication_strategy.hh, locator/tablet_metadata_guard.hh, locator/tablets.cc, locator/tablets.hh, message/messaging_service.cc, message/messaging_service.hh, replica/database.hh, replica/table.cc, service/storage_service.cc, service/storage_service.hh, service/tablet_allocator.cc, service/tablet_allocator.hh, service/topology_state_machine.cc, service/topology_state_machine.hh, test/boost/tablets_test.cc, test/topology_experimental_raft/test_tablets.py
Load balancer will recognize decommissioning nodes and will
move tablet replicas away from such nodes with highest priority.
Topology changes have now an extra step called "tablet draining" which
calls the load balancer. The step will execute tablet migration track
as long as there are nodes which require draining. It will not do regular
load balancing.
If load balancer is unable to find new tablet replicas, because RF
cannot be met or availability is at risk due to insufficient node
distribution in racks, it will throw an exception. Currently, topology
change will retry in a loop. We should make this error cause topology
change to be aborted. There is no infrastructure for
aborts yet, so this is not implemented.
=> Add support for decommission with tablets

dist/CMakeLists.txt
in this series,
- the build of unstripped package is fixed, and 
- the targets for building deb and rpm packages are added. these targets builds deb and rpm packages from the unstripped package.
=> build: cmake: add targets for building deb and rpm packages

configure.py, main.cc, test.py, test/nodetool/conftest.py, test/nodetool/rest_api_mock.py, test/nodetool/suite.yaml, test/nodetool/test_compact.py, test/nodetool/test_nodetool.py, tools/CMakeLists.txt, tools/entry_point.hh, tools/scylla-nodetool.cc, tools/utils.cc, utils/http.hh, utils/s3/client.cc
This series introduces a scylla-native nodetool.  It is invokable via the main scylla executable as the other native tools we have. It uses the seastar's new `http::client` to connect to the specified node and execute the desired commands.
For now a single command is implemented: `nodetool compact`, invokable as `scylla nodetool compact`. Once all the boilerplate is added to create a new tool, implementing a single command is not too bad, in terms of code-bloat. Certainly not as clean as a python implementation would be, but good enough. The advantages of a C++ implementation is that all of us in the core team know C++ and that it is shipped right as part of the scylla executable..
=> Introduce a scylla-native nodetool

scripts/create-relocatable-package.py
in this series, we do not assume the existence of "build" build directory. and prefer using the version files located under the directory specified with the `--build-dir` option.
Refs #15241
=> create-relocatable-package.py: do not assume "build" build directory

tools/scylla-nodetool.cc
in other words, do not create bpo::value unless transfer it to an
option_description.
`boost::program_options::value()` create a new typed_value<T> object,
without holding it with a shared_ptr. boost::program_options expects
developer to construct a `bpo::option_description` right away from it.
and `boost::program_options::option_description` takes the ownership
of the `type_value<T>*` raw pointer, and manages its life cycle with
a shared_ptr. but before passing it to a `bpo::option_description`,
the pointer created by `boost::program_options::value()` is a still
a raw pointer.
before this change, we initialize `operations_with_func` as global
variables using `boost::program_options::value()`. but unfortunately,
we don't always initialize a `bpo::option_description` from it --
we only do …
=> tools/scylla-nodetools: do not create unowned bpo::value 

replica/distributed_loader.cc, sstables/sstables.hh
Some time ago populating of tables from sstables was reworked to use sstable states instead of full paths (#12707). Since then few places in the populator was left that still operate on the state-based subdirectory name. This PR collects most of those dangling ends
refs: #13020
=> Use sstable_state in sstables populator

replica/distributed_loader.cc, replica/distributed_loader.hh
Populating of non-system keyspaces is now done by listing datadirs and assuming that each subdir found is a keyspace. For S3-backed keyspaces this is also true, but it's a bug (#13020). The loop needs to walk the list of known keyspaces instead, and try to find the keyspace storage later, based on the storage option.
=> Rewrap keyspace population loop

dist/CMakeLists.txt, dist/debuginfo/CMakeLists.txt
this target mirrors the "dist-server-debuginfo-{mode}" target in the `build.ninja` created by `configure.py`.
=> build: cmake: add "dist-server-debuginfo" target

compaction/compaction_manager.cc, compaction/compaction_manager.hh, test/lib/sstable_utils.cc
Compaction tasks executors serve two different purposes - as compaction
manager related entity they execute compaction operation and as task
manager related entity they track compaction status. 
When one role depends on the other, as it currently is for 
compaction_task_impl::done() and compaction_task_executor::compaction_done(),
requirements of both roles need to be satisfied at the same time in each 
corner case. Such complexity leads to bugs.
To prevent it, compaction_task_impl::done() of executors no longer depends 
on compaction_task_executor::compaction_done().
Fixes: #14912.
=> compaction: change behaviour of compaction task executors

db/schema_features.hh, db/schema_tables.cc, db/schema_tables.hh, db/system_keyspace.cc, db/system_keyspace.hh, gms/feature_service.cc, gms/feature_service.hh, replica/database.cc, service/migration_manager.cc, test/boost/schema_change_test.cc, test/boost/schema_registry_test.cc, test/pylib/log_browsing.py, test/topology_custom/suite.yaml, test/topology_custom/test_group0_schema_versioning.py
When performing a schema change through group 0, extend the schema mutations with a version that's persisted and then used by the nodes in the cluster in place of the old schema digest, which becomes horribly slow as we perform more and more schema changes (#7620).
If the change is a table create or alter, also extend the mutations with a version for this table to be used for `schema::version()`s instead of having each node calculate a hash which is susceptible to bugs (#13957).
When performing a schema change in Raft RECOVERY mode we also extend schema mutations which forces nodes to revert to the old way of calculating schema versions when necessary.
We can only introduce these extensions if all of the cluster understands them, so protect this code by a new cluster/schema feature, …
=> Don't calculate hashes for schema versions in Raft mode

cql3/query_processor.cc, service/storage_proxy.cc, transport/server.cc
This series mark multiple high cardinality counters with skip_when_empty flag.
After this patch the following counters will not be reported if they were never used:
```
scylla_transport_cql_errors_total
scylla_storage_proxy_coordinator_reads_local_node
scylla_storage_proxy_coordinator_completed_reads_local_node
scylla_transport_cql_errors_total
```
Also marked, the CAS related CQL operations.
Fixes #12751
=> Mark counters with skip when empty

compaction/compaction_backlog_manager.hh, compaction/compaction_manager.cc, compaction/compaction_state.hh
Currently, the moved-object's manager pointer is moved into the
constructed object, but without fixing the registration to
point to the moved-to object, causing #15248.
Although we could properly move the registration from
the moved-from object to the moved-to one, it is simpler
to just disallow moving a registered tracker, since it's
not needed anywhere. This way we just don't need to mess
with the trackers' registration.
The move-assignment operator has a similar problem,
therefore it is deleted in this series, and the function is
renamed to `transfer_backlog` that just doesn't deal with the
moved-from registration.  This is safe since it's only used internally
by the compaction manager.
Fixes #15248
=> compaction_backlog_tracker: do not allow moving registered trackers

docs/cql/types.rst, docs/using-scylla/counters.rst
This PR adds the information that counters do not support data expiration with TTL, plus the link to the TTL page.
Fixes https://github.com/scylladb/scylladb/issues/15479
=> doc: add a note that counters do not support TTL

sstables/sstable_directory.cc, sstables/sstable_directory.hh, sstables/storage.cc, sstables/storage.hh, test/boost/schema_change_test.cc, test/object_store/test_basic.py
Sstables in transitional states are marked with the respective 'status' in the registry. Currently there are two of such -- 'creating' and 'removing'. And the 'sealed' status for sstables in use.
On boot the distributed loader tries to garbage collect the dangling sstables. For filesystem storage it's done with the help of temorary sstables' dirs and pending deletion logs. For s3-backed sstables, the garbage collection means fetching all non-sealed entries and removing the corresponding objects from the storage.
Test included (last patch)
fixes #13024
=> Collect dangling object-store sstables

configure.py
in this series, we use the default values of options specifying the paths to tools for better readability. and also to ease the migration to CMake
Refs #15379
=> build: use default value of --with-* option s

configure.py
more structured this way. this also allows us to quickly identify the part which should/can be reused when migrating to CMake based building system.
Refs #15379
=> build: extract code fragments into functions

compaction/compaction.cc, compaction/compaction_manager.cc, compaction/compaction_manager.hh, test/boost/sstable_compaction_test.cc
Off-strategy suffers with a 100% space overhead, as it adopted
a sort of all or nothing approach. Meaning all input sstables,
living in maintenance set, are kept alive until they're all
reshaped according to the strategy criteria.
Input sstables in off-strategy are very likely to be mostly disjoint,
so it can greatly benefit from incremental compaction.
The incremental compaction approach is not only good for
decreasing disk usage, but also memory usage (as metadata of
input and output live in memory), and file desc count, which
takes memory away from OS.
Turns out that this approach also greatly simplifies the
off-strategy impl in compaction manager, as it no longer have
to maintain new unused sstables and mark them for
deletion on failure, and also unlink intermediary sstables
used …
=> Enable incremental compaction on off-strategy

cql3/statements/alter_table_statement.cc, cql3/statements/create_table_statement.cc, cql3/statements/create_table_statement.hh, test/boost/cql_query_test.cc
Table properties validation is performed on statement execution.
Thus, when one attempts to create a table with invalid options,
an incorrect command gets committed in Raft. But then its
application fails, leading to a raft machine being stopped.
Check table properties when create and alter statements are prepared.
Fixes: #14710.
=> Validate compaction strategy options in prepare

test/topology_custom/test_different_group0_ids.py, test/topology_custom/test_old_ip_notification_repro.py, test/topology_custom/test_select_from_mutation_fragments.py, test/topology_custom/test_shutdown_hang.py
Also, while at it, add copyright/license blurbs for tests that were missing it.
=> test/topology_custom/test_select_from_mutation_fragments.py: use async api and clean-up

docs/dev/object_storage.md, main.cc, test/boost/s3_test.cc, test/lib/test_services.cc, test/perf/perf_s3_client.cc, test/pylib/minio_server.py, utils/s3/client.cc, utils/s3/creds.hh
in this series, we rename s3 credential related variable and option names so they are more consistent with AWS's official document. this should help with the maintainability.
=> treewide: rename s3 credentials related variable and option names

replica/database.cc, replica/distributed_loader.cc, replica/distributed_loader.hh, test/boost/sstable_directory_test.cc
Currently the datadir is ignored.
Use it to construct the table's base path.
Fixes scylladb/scylladb#15418
=> populate_keyspace: use datadir

cql3/Cql.g, cql3/prepare_context.cc, cql3/prepare_context.hh, test/cql-pytest/test_prepare.py
When presented with queries that use the same named bind variables twice, like this one:
```cql
SELECT p FROM table WHERE p = :x AND c = :x
```
Scylla generated empty `partition_key_bind_indexes` (`pk_indexes`).
`pk_indexes` tell the driver which bind variables it should use to calculate the partition token for a query. Without it, the driver is unable to determine the token and it will send the query to a random node.
Scylla should generate pk_indexes which tell the driver that it can use bind variable with `bind_index = 0` to calculate the partition token for this query.
The problem was that `_target_columns` keep only a single target_column for each bind variable.
In the example above `:x` is compared with both `p` and `c`, but `_target_columns` would contain only one of them, and …
=>  cql3/prepare_context: fix generating pk_indexes for duplicate named bind variables

replica/distributed_loader.cc, sstables/sstable_directory.cc, sstables/sstable_directory.hh
Distributed loader code still "knows" that table's datadir is a filesystem directory with some structure. For S3-backed sstables this still works because for S3 keyspaces scylla still creates and maintains empty directories in datadir. This set fixes the dist. loader assumptions about that and moves them into sstable directory's lister.
refs: #13020
=> Don't mess with table directories in distributed loader

main.cc, service/forward_service.cc, service/forward_service.hh, test/lib/cql_test_env.cc
There's a dedicated forward_service::shutdown() method that's defer-scheduled in main for very early invocation. That's not nice, the fwd service start-shutdown-stop sequence can be made "canonical" by moving the shutting down code into abort source subscription. Similar thing was done for view updates generator in 3b95f4f107d28248f024d876284ab00e3e2d1412
refs: #2737
refs: #4384
=> Sanitize forward-service shutdown

api/api.cc, api/api_init.hh, api/storage_service.cc, api/storage_service.hh, main.cc, service/storage_service.hh
Storage service API set/unset has two flaws.
First, unset doesn't happen, so after storage service is stopped its handlers become "local is not initialized"-assertion and use-after-free landmines.
Second, setting of storage service API carry gossiper and system keyspace references, thus duplicating the knowledge about storage service dependencies.
This PR fixes both by adding the storage service API unsetting and by making the handlers use _only_ storage service instance, not any externally provided references.
=> Sanitize storage_service API maintenance

docs/faq.rst, docs/using-scylla/cassandra-compatibility.rst
This PR replaces a link to a section of the ScyllaDB website with little information about ScyllaDB vs. Cassandra with a link to
a documentation section where Cassandra compatibility is covered in detail.
In addition, it removes outdated or irrelevant information about versions from the Cassandra compatibility page.
Now that the documentation is versioned, we shouldn't add such information to the content.
Fixes https://github.com/scylladb/scylla-enterprise/issues/3454
=> doc: replace the link to Cassandra compatibility information

api/api-doc/storage_service.json, api/api.cc, api/api_init.hh, api/storage_service.cc, api/storage_service.hh, main.cc, service/storage_service.hh, test/topology_experimental_raft/test_fencing.py
Add a REST API to reload Raft topology state without having to restart a node and use it in `test_fence_hints`. Restarting the node has undesired side effects which cause test flakiness; more details provided in commit messages.
Refactor the test a bit while at it.
Fixes: #15285
=> Fix `test_fencing.py::test_fence_hints` flakiness

db/hints/internal/hint_storage.cc, db/hints/internal/hint_storage.hh, db/hints/manager.cc
This PR is the second step in refactoring the Hinted Handoff module. It cleans up the contents of the file `hint_storage.cc`. The biggest change is the transition from continuations to coroutines.
Refs #15358
=> db/hints: Clean up hint_storage.cc

api/api.cc, api/api_init.hh, api/storage_proxy.cc, api/storage_proxy.hh, api/storage_service.cc, main.cc
Registering API handlers for services need to
- happen next to the corresponding service's start
- use only the provided service, not any other ones (if needed, the handler's service can use its internal dependencies to do its job)
- get the service to handle requests via argument, not from http context (http context, in turn, is going _not_ to depend on anything)
The storage proxy handlers don't follow any of that rules, this PR fixes them
=> Sanitize storage_proxy API handlers

test/nodetool/conftest.py, test/nodetool/rest_api_mock.py, test/nodetool/test_backup.py, test/nodetool/test_binary.py, test/nodetool/test_compact.py, test/nodetool/test_gossip.py, test/nodetool/test_help.py, test/nodetool/test_traceprobability.py, test/nodetool/test_version.py, test/nodetool/utils.py, tools/scylla-nodetool.cc, tools/scylla-sstable.cc, tools/scylla-types.cc, tools/utils.cc, tools/utils.hh
The following new commands are implemented:
* disablebackup
* disablebinary
* disablegossip
* enablebackup
* enablebinary
* enablegossip
* gettraceprobability
* help
* settraceprobability
* statusbackup
* statusbinary
* statusgossip
* version
All are associated with tests. All tests (both old and new) pass with both the scylla-native and the cassandra nodetool implementation.
=> tools/nodetool: implement additional commands, part 1/N

sstables/sstable_set.cc, sstables/sstable_set.hh, sstables/sstable_set_impl.hh, test/boost/sstable_set_test.cc
All `sstable_set_impl` subclasses/implementations already keep a `schema_ptr` so we can make `sstable_set_impl::make_incremental_selector` function return both the selector and the schema that's being used by it.
That way, we can use the returned schema in `sstable_set::make_incremental_selector` function instead of `sstable_set::_schema` field which makes the field unused and allows us to remove it alltogether and reduce the memory footprint of `sstable_set` objects.
=> Remove _schema field from sstable_set

main.cc, test/boost/tracing_test.cc, tracing/trace_keyspace_helper.hh, tracing/tracing.cc, tracing/tracing.hh
Tracing is one of two global service left out there with its starting and stopping being pretty hairy. In order to de-globalize it and keep its start-stop under control the existing start-stop sequence is worth cleaning. This PR
* removes create_ , start_ and stop_ wrappers to un-hide the global tracing_instance thing
* renames tracing::stop() to shutdown() as it's in fact shutdown
* coroutinizes start/shutdown/stop while at it
Squeezed parts from #14156 that don't reorder start-stop calls
=> Sanitize tracing start-stop calls

reader_concurrency_semaphore.cc, test/boost/row_cache_test.cc, utils/logalloc.hh, utils/memory_limit_reached.hh
Consider the following code snippet:
```c++
future<> foo() {
semaphore.consume(1024);
}
future<> bar() {
return _allocating_section([&] {
foo();
});
}
```
If the consumed memory triggers the OOM kill limit, the semaphore will throw `std::bad_alloc`. The allocating section will catch this, bump std reserves and retry the lambda. Bumping the reserves will not do anything to prevent the next call to `consume()` from triggering the kill limit. So this cycle will repeat until std reserves are so large that ensuring the reserve fails. At this point LSA gives up and re-throws the `std::bad_alloc`. Beyond the useless time spent on code that is doomed to fail, this also results in expensive LSA compaction and eviction of the cache (while trying to ensure reserves).
Prevent this situation by …
=> logalloc, reader_concurrency_semaphore: cooperate on OOM kills

db/system_keyspace.cc, replica/table.cc, sstables/open_info.hh, sstables/sstable_directory.cc, sstables/sstables.cc, sstables/sstables.hh, sstables/storage.cc, tools/scylla-sstable.cc
The descriptor in question is used to parse sstable's file path and return back the result. Parser, among "relevant" info, also parses sstable directory and keyspace+table names. However, there are no code (almost) that needs those strings. And the need to construct descriptor with those makes some places obscurely use empty strings.
The PR removes sstable's directory, keyspace and table names from descriptor and, while at it, relaxes the sstable directory code that makes descriptor out of a real sstable object by (!) parsing its Data file path back.
=> Do not keep excessive info on sstables::entry_descriptor

api/api.cc, api/api_init.hh, api/hinted_handoff.cc, api/hinted_handoff.hh, main.cc, service/storage_proxy.cc, service/storage_proxy.hh
This is the continuation of 3e74432dbf.
Registering API handlers for services need to
- happen next to the corresponding service's start
- use only the provided service, not any other ones (if needed, the handler's service can use its internal dependencies to do its job)
- get the service to handle requests via argument, not from http context (http context, in turn, is going _not_ to depend on anything)
Hints API handlers want to use proxy, but also reference gossiper and capture proxy via http context. This PR fixes both and removes http_contex -> proxy dependency as no longer needed
=> Sanitize hints API handlers and remove proxy from http context

db/hints/internal/hint_endpoint_manager.cc, db/hints/internal/hint_endpoint_manager.hh, db/hints/manager.cc, db/hints/manager.hh, db/hints/resource_manager.cc, db/hints/resource_manager.hh, service/storage_proxy.cc
This PR is another step in refactoring the Hinted Handoff module. It aims at modernizing the code by moving to coroutines, using `std::ranges` instead of Boost's ones where possible, and uses other features coming with the new C++ standards.
It also tries to make the code clearer and get rid of confusing elements, e.g. using shared pointers where they shouldn't be used or marking methods as virtual even though nothing derives from the class. It also prevents `manager.hh` from giving direct access to internal structures (`hint_endpoint_manager` in this case).
Refs #15358
=> db/hints: Modernize manager

db/commitlog/commitlog.cc, db/commitlog/commitlog.hh, main.cc, replica/database.cc, test/lib/cql_test_env.cc, tombstone_gc.cc, tombstone_gc.hh
Yet another approach to Fixes #14870
(Originally suggested by @avikivity). Use commit log stored GC clock min positions to narrow compaction GC bounds.
(Still requires augmented manual flush:es with extensive CL clearing to pass various dtest, but this does not affect "real" execution). 
Adds a lowest timestamp of GC clock whenever a CF is added to a CL segment the first time. Because GC clock is wall 
clock time and only connected to TTL (not cell/row timestamps), this gives a fairly accurate view of GC low bounds
per segment. This is then (in a rather ugly way) propagated to tombstone_gc_state to narrow the allowed GC bounds for 
a CF, based on what is currently left in CL. 
Note: this is a rather unoptimized version - no caching or anything. But even so, should not be excessively …
=> RFC: Store and propagage GC timestamp markers from commitlog

db/system_keyspace.cc, sstables/sstable_directory.cc, test/boost/sstable_directory_test.cc
When populating system keyspace the sstable_directory forgets to create upload/ subdir in the tables' datadir because of the way it's invoked from distributed loader. For non-system keyspaces directories are created in table::init_storage() which is self-contained and just creates the whole layout regardless of what.
This PR makes system keyspace's tables use table::init_storage() as well so that the datadir layout is the same for all on-disk tables.
Test included.
fixes: #15708 
closes: scylladb/scylla-manager#3603
=> Initialize datadir for system and non-system keyspaces the same way

compaction/compaction.cc, compaction/compaction.hh, compaction/compaction_manager.cc, compaction/compaction_manager.hh, compaction/task_manager_module.cc, compaction/task_manager_module.hh, sstables/mx/reader.cc, sstables/mx/reader.hh, sstables/sstables.cc, sstables/sstables.hh, tasks/task_manager.cc, tasks/task_manager.hh
compaction_read_monitor_generator is an existing mechanism
for monitoring progress of sstables reading during compaction.
In this change information gathered by compaction_read_monitor_generator
is utilized by task manager compaction tasks of the lowest level, 
i.e. compaction executors, to calculate task progress.
compaction_read_monitor_generator has a flag, which decides whether
monitored changes will be registered by compaction_backlog_tracker.
This allows us to pass the generator to all compaction readers without
impacting the backlog.
Task executors have access to compaction_read_monitor_generator_wrapper,
which protects the internals of  compaction_read_monitor_generator
and provides only the necessary functionality.
=> Progress of compaction executors

CMakeLists.txt, cmake/mode.common.cmake
to match the behavior of `configure.py`.
=> build: cmake: pass -dynamic-linker to ld

api/api.cc, api/api_init.hh, api/task_manager.cc, api/task_manager.hh, api/task_manager_test.cc, api/task_manager_test.hh, main.cc
This is the continuation of 8c03eeb85d6b49d5adc4558d41e5695b0c8a642b
Registering API handlers for services need to
* get the service to handle requests via argument, not from http context (http context, in turn, is going not to depend on anything)
* unset the handlers on stop so that the service is not used after it's stopped (and before API server is stopped)
This makes task manager handlers work this way
=> Sanitize API -> task_manager dependency

mutation/json.hh, test/nodetool/rest_api_mock.py, test/nodetool/test_compactionhistory.py, test/nodetool/test_stop.py, tools/scylla-nodetool.cc, utils/rjson.hh
The following new commands are implemented:
* stop
* compactionhistory
All are associated with tests. All tests (both old and new) pass with both the scylla-native and the cassandra nodetool implementation.
=> tools/nodetool: implement additional commands, part 2/N

docs/architecture/raft.rst, docs/cql/ddl.rst, docs/operating-scylla/procedures/cluster-management/add-node-to-cluster.rst, docs/operating-scylla/procedures/cluster-management/remove-node.rst, docs/operating-scylla/procedures/cluster-management/replace-dead-node-or-more.rst, docs/operating-scylla/procedures/cluster-management/replace-dead-node.rst, docs/operating-scylla/procedures/cluster-management/replace-running-node.rst, docs/troubleshooting/cluster/index.rst, docs/troubleshooting/failed-add-remove-replace.rst, docs/troubleshooting/failed-update-schema.rst, docs/troubleshooting/handling-node-failures.rst, docs/troubleshooting/modeling/index.rst
This PR improves the way of how handling failures is documented and accessible to the user.
- The Handling Failures section is moved from Raft to Troubleshooting.
- Two new topics about failure are added to Troubleshooting with a link to the Handling Failures page (Failure to Add, Remove, or Replace a Node, Failure to Update the Schema).
- A note is added to the add/remove/replace node procedures to indicate that a quorum is required.
See individual commits for more details.
Fixes https://github.com/scylladb/scylladb/issues/13149
=> doc: improve the docs for handling failures

db/system_keyspace.cc, db/system_keyspace.hh, sstables/sstable_directory.cc, sstables/storage.cc, sstables/storage.hh, test/boost/sstable_resharding_test.cc, test/lib/test_services.cc, test/object_store/test_basic.py
before this change, we create a new UUID for a new sstable managed by the s3_storage, and we use the string representation of UUID defined by RFC4122 like "0aa490de-7a85-46e2-8f90-38b8f496d53b" for naming the objects stored on s3_storage. but this representation is not what we are using for storing sstables on local filesystem when the option of "uuid_sstable_identifiers_enabled" is enabled. instead, we are using a base36-based representation which is shorter.
to be consistent with the naming of the sstables created for local filesystem, and more importantly, to simplify the interaction between the local copy of sstables and those stored on object storage, we should use the same string representation of the sstable identifier.
so, in this change:
1. instead of creating a new UUID, just …
=> sstable: switch to uuid identifier for naming S3 sstable objects

cql3/CMakeLists.txt
this mirrors what we have in `configure.py`, to build the CqlParser with `-O1`
and disable `-fsanitize-address-use-after-scope` when compiling CqlParser.cc
in order to prevent the compiler from emitting code which uses large amount of stack
space at the runtime.
=> build: cmake: avoid using large amount stack of when compiling parser 

alternator/executor.cc, cdc/log.cc, db/system_distributed_keyspace.cc, redis/keyspace_utils.cc, service/migration_listener.hh, service/migration_manager.cc, service/migration_manager.hh, service/tablet_allocator.cc, table_helper.cc
There are some schema modifications performed automatically (during bootstrap, upgrade etc.) by Scylla that are announced by multiple calls to `migration_manager::announce` even though they are logically one change. Precisely, they appear in:
- `system_distributed_keyspace::start`,
- `redis:create_keyspace_if_not_exists_impl`,
- `table_helper::setup_keyspace` (for the `system_traces` keyspace).
All these places contain a FIXME telling us to `announce` only once. There are a few reasons for this:
- calling `migration_manager::announce` with Raft is quite expensive -- taking a `read_barrier` is necessary, and that requires contacting a leader, which then must contact a quorum,
- we must implement a retrying mechanism for every automatic `announce` if `group0_concurrent_modification` occurs …
=> reduce announcements of the automatic schema changes 

compaction/compaction.cc, compaction/compaction_manager.cc, compaction/compaction_manager.hh, compaction/leveled_compaction_strategy.cc, replica/database.hh, replica/table.cc, test/boost/sstable_compaction_test.cc
Off-strategy suffers with a 100% space overhead, as it adopted
a sort of all or nothing approach. Meaning all input sstables,
living in maintenance set, are kept alive until they're all
reshaped according to the strategy criteria.
Input sstables in off-strategy are very likely to be mostly disjoint,
so it can greatly benefit from incremental compaction.
The incremental compaction approach is not only good for
decreasing disk usage, but also memory usage (as metadata of
input and output live in memory), and file desc count, which
takes memory away from OS.
Turns out that this approach also greatly simplifies the
off-strategy impl in compaction manager, as it no longer have
to maintain new unused sstables and mark them for
deletion on failure, and also unlink intermediary sstables
used …
=> [branch-5.1] Enable incremental compaction on off-strategy

compaction/compaction.cc, compaction/compaction_manager.cc, compaction/compaction_manager.hh, compaction/leveled_compaction_strategy.cc, replica/compaction_group.hh, replica/table.cc, test/boost/sstable_compaction_test.cc
Off-strategy suffers with a 100% space overhead, as it adopted
a sort of all or nothing approach. Meaning all input sstables,
living in maintenance set, are kept alive until they're all
reshaped according to the strategy criteria.
Input sstables in off-strategy are very likely to be mostly disjoint,
so it can greatly benefit from incremental compaction.
The incremental compaction approach is not only good for
decreasing disk usage, but also memory usage (as metadata of
input and output live in memory), and file desc count, which
takes memory away from OS.
Turns out that this approach also greatly simplifies the
off-strategy impl in compaction manager, as it no longer have
to maintain new unused sstables and mark them for
deletion on failure, and also unlink intermediary sstables
used …
=> [branch-5.2] Enable incremental compaction on off-strategy

test/lib/cql_test_env.cc, test/lib/cql_test_env.hh, test/perf/perf_simple_query.cc
Usage:
```
build/dev/scylla perf-simple-query --tablets
```
=> Allow running perf-simple-query with tablets

db/system_keyspace.cc, service/storage_service.cc, test/topology_experimental_raft/test_topology_ops.py
Currently, when the topology coordinator accepts a node, it moves it to bootstrap state and assigns tokens to it (either new ones during bootstrap, or the replaced node's tokens). Only then it contacts the joining node to tell it about the decision and let it perform a read barrier.
However, this means that the tokens are inserted too early. After inserting the tokens the cluster is free to route write requests to it, but it might not have learned about all of the schema yet.
Fix the issue by inserting the tokens later, after completing the join node response RPC which forces the receiving node to perform a read barrier.
Refs: #15686
Fixes: #15738
=> raft topology: assign tokens after join node response rpc

docs/operating-scylla/nodetool-commands/compact.rst, docs/operating-scylla/nodetool-commands/stop.rst, docs/operating-scylla/nodetool.rst
While working on https://github.com/scylladb/scylladb/issues/15588, I noticed problems with the existing documentation, when comparing it with the actual code.
This PR contains fixes for nodetool compact, stop and scrub.
=> Nodetools docs improvements 1/N

test/nodetool/rest_api_mock.py, test/nodetool/test_cleanup.py, test/nodetool/test_compact.py, test/nodetool/test_snapshot.py, tools/scylla-nodetool.cc
This PR implements the following new nodetool commands:
* cleanup
* clearsnapshots
* listsnapshots
All commands come with tests and all tests pass with both the new and the current nodetool implementations.
=> Nodetool additional commands 3/N

replica/table.cc, row_cache.cc, row_cache.hh
Currently the cache updaters aren't exception safe
yet they are intended to be.
Instead of allowing exceptions from
`external_updater::execute` escape `row_cache::update`,
abort using `on_fatal_internal_error`.
Future changes should harden all `execute` implementations
to effectively make them `noexcept`, then the pure virtual
definition can be made `noexcept` to cement that.
Fixes scylladb/scylladb#15576
=> row_cache: abort on exteral_updater::execute errors

tools/scylla-sstable.cc, tools/utils.cc, tools/utils.hh
Refs https://github.com/scylladb/scylla-enterprise/issues/3461
Refs https://github.com/scylladb/scylla-enterprise/issues/3210
Adds a tool-app global db::config + extensions to each tool invocation + configurable init.
Uses this in scylla-sstables, allowing both enterprise-only configs to be read, as well as (almost all)
encrypted sstables. 
Note: Do not backport to enterprise before https://github.com/scylladb/scylla-enterprise/pull/3473 is merged, otherwise tools will break there.
=> scylla-sstable/tools: Use semi-properly initiated db::config + extensions to allow encrypted sstables

cql3/statements/select_statement.cc, db/schema_tables.cc, db/schema_tables.hh, db/view/view.cc, db/view/view.hh, gms/feature_service.cc, gms/feature_service.hh, replica/database.cc, service/migration_manager.cc
The purpose of `maybe_fix_legacy_secondary_index_mv_schema` was to deal
with legacy materialized view schemas used for secondary indexes,
schemas which were created before the notion of "computed columns" was
introduced. Back then, secondary index schemas would use a regular
"token" column. Later it became a computed column and old schemas would
be migrated during rolling upgrade.
The migration code was introduced in 2019
(db8d4a0cc649c74e30198dd83b082b0ad50b1314) and then fixed in 2020
(d473bc9b0669e9d3879ff0f329a9ed16378dd569).
The fix was present in Enterprise 2022.1 and in OSS 4.5. So, assuming
that users don't try crazy things like upgrading from 2021.X to 2023.X
(which we do not support), all clusters will have already executed the
migration code once they upgrade to 2023.X, meaning …
=> schema_tables: turn view schema fixing code into a sanity check

test/boost/sstable_compaction_test.cc, test/lib/sstable_test_env.hh, test/lib/test_services.cc, test/lib/test_services.hh
The object in question is used to facilitate creation of table objects for compaction tests. Currently the table_for_test carries a bunch of auxiliary objects that are needed for table creation, such as stats of all sorts and table state. However, there's also some "infrastructure" stuff onboard namely:
- reader concurrency semaphore
- cache tracker
- task manager
- compaction manager
And those four are excessive because all the tests in question run inside the sstables::test_env that has most of it.
This PR removes the mentioned objects from table_for_tests and re-uses those from test_env. Also, while at it, it also removes the table::config object from table_for_tests so that it looks more like core code that creates table does.
=> Put table_for_tests on a diet

test/boost/sstable_3_x_test.cc, test/boost/sstable_compaction_test.cc, test/lib/sstable_test_env.hh, test/lib/sstable_utils.cc, test/lib/sstable_utils.hh, test/lib/test_services.cc, test/lib/test_services.hh
There's such a wrapper class in test_services. After #15889 this class resembles the test_env_compaction_manager and can be replaced with it. However, two users of the former wrapper class need it just to construct table object, and the way they do it is re-implementation of table_for_tests class.
This PR patches the test cases to make use of table_for_tests and removes the compaction_manager_for_testing that becomes unused after it.
=> Drop compaction_manager_for_testing

alternator/executor.cc, cdc/log.cc, db/system_distributed_keyspace.cc, redis/keyspace_utils.cc, service/migration_listener.hh, service/migration_manager.cc, service/migration_manager.hh, service/tablet_allocator.cc, table_helper.cc
There are some schema modifications performed automatically (during bootstrap, upgrade etc.) by Scylla that are announced by multiple calls to `migration_manager::announce` even though they are logically one change. Precisely, they appear in:
- `system_distributed_keyspace::start`,
- `redis:create_keyspace_if_not_exists_impl`,
- `table_helper::setup_keyspace` (for the `system_traces` keyspace).
All these places contain a FIXME telling us to `announce` only once. There are a few reasons for this:
- calling `migration_manager::announce` with Raft is quite expensive -- taking a `read_barrier` is necessary, and that requires contacting a leader, which then must contact a quorum,
- we must implement a retrying mechanism for every automatic `announce` if `group0_concurrent_modification` occurs …
=> reduce announcements of the automatic schema changes

auth/service.cc, db/system_distributed_keyspace.cc, redis/keyspace_utils.cc, table_helper.cc
The follow-up to #15594.
We retry every automatic `migration_manager::announce` if `group0_concurrent_modification` occurs. Concurrent operations can happen during concurrent bootstrap in Raft-based topology, so we need this change to enable support for concurrent bootstrap.
This PR adds retry loops in 4 places:
- `service::create_keyspace_if_missing`,
- `system_distributed_keyspace::start`,
- `redis::create_keyspace_if_not_exists_impl`,
- `table_helper::setup_keyspace` (used for creating the `system_traces` keyspace).
Fixes #15435
=> retry automatic announcements of the schema changes on concurrent operation

main.cc, service/raft/group0_state_machine.cc, service/raft/group0_state_machine.hh, service/raft/raft_group0.cc, service/raft/raft_group0.hh, service/storage_service.cc
Topology on raft is still an experimental feature. The RPC verbs introduced in that mode shouldn't be used when it's disabled, otherwise we lose the right to make breaking changes to those verbs.
First, make sure that the aforementioned verbs are not sent outside the mode. It turns out that `raft_pull_topology_snapshot` could be sent outside topology-on-raft mode - after the PR, it no longer can.
Second, topology-on-raft mode verbs are now not registered at all on the receiving side when the mode is disabled.
Additionally tested by running `topology/` tests with `consistent_cluster_management: True` but with experimental features disabled.
Fixes: scylladb/scylladb#15862
=> raft: topology: outside topology-on-raft mode, make sure not to use its RPCs

test/object_store/test_basic.py
this series applies fixes to make the test more PEP8 compliant. the goal is to improve the readability and maintainability.
=> test/object_store: PEP8 compliant cleanups

test/boost/memtable_test.cc, test/boost/mutation_reader_test.cc, test/boost/repair_test.cc, test/boost/row_cache_test.cc, test/boost/sstable_3_x_test.cc, test/boost/sstable_compaction_test.cc, test/boost/sstable_conforms_to_mutation_source_test.cc, test/boost/sstable_datafile_test.cc, test/boost/sstable_mutation_test.cc, test/boost/sstable_test.hh, test/boost/view_build_test.cc, test/boost/virtual_table_mutation_source_test.cc, test/lib/sstable_utils.cc, test/lib/sstable_utils.hh
The helper makes sstable, writes mutations into it and loads one. Internally it uses the make_memtable() helper that prepares a memtable out of a vector of mutations. There are many test cases that don't use these facilities generating some code duplication.
The make_sstable() wrapper around make_sstable_easy() is removed along the way.
=> Sanitize usage of make_sstable_easy+make_memtable in tests

api/failure_detector.cc, test/rest_api/test_failure_detector.py
These APIs may return stale or simply incorrect data on shards
other than 0. Newer versions of Scylla are better at maintaining
cross-shard consistency, but we need a simple fix that can be easily and
without risk be backported to older versions; this is the fix.
Add a simple test to check that the `failure_detector/endpoints`
API returns nonzero generation.
Fixes: scylladb/scylladb#15816
=> api: failure_detector: invoke on shard 0

db/system_keyspace.cc, db/system_keyspace.hh, sstables/sstable_directory.cc, sstables/sstables.hh, sstables/storage.cc, test/boost/sstable_compaction_test.cc
The sstable currently can move between normal, staging and quarantine state runtime. For S3-backed sstables the state change means maintaining the state itself in the ownership table and updating it accordingly.
There's also the upload facility that's implemented as state change too, but this PR doesn't support this part.
fixes: #13017
=> Support state change for S3-backed sstables

service/storage_service.cc
When topology coordinator tries to fence the previous coordinator it performs a group0 operation. The current topology coordinator might be aborted in the meantime, which will result in a `raft::request_aborted` exception being thrown. After the fix to scylladb/scylladb#15728 was merged, the exception is caught, but then `sleep_abortable` is called which immediately throws `abort_requested_exception` as it uses the same abort source as the group0 operation. The `fence_previous_coordinator` function which does all those things is not supposed to throw exceptions, if it does - it causes `raft_state_monitor_fiber` to exit, completely disabling the topology coordinator functionality on that node.
Modify the code in the following way:
- Catch `abort_requested_exception` thrown from …
=> raft topology: handle abort exceptions better in fence_previous_coordinator

alternator/error.hh, alternator/executor.cc, alternator/rmw_operation.hh, alternator/server.cc, docs/alternator/compatibility.md, test/alternator/test_returnvalues.py, utils/rjson.hh
alternator: add support for ReturnValuesOnConditionCheckFailure feature
As announced in https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-dynamodb-cost-failed-conditional-writes/, DynamoDB added a new option for write operations (PutItem, UpdateItem, or DeleteItem), ReturnValuesOnConditionCheckFailure, which if set to ALL_OLD returns the current value of the item - but only if a condition check failed.
Fixes https://github.com/scylladb/scylladb/issues/14481
=> Alternator: Support new ReturnValuesOnConditionCheckFailure feature

test/nodetool/README.md, test/nodetool/rest_api_mock.py, test/nodetool/test_autocompaction.py, test/nodetool/test_drain.py, test/nodetool/test_flush.py, test/nodetool/test_snapshot.py, tools/scylla-nodetool.cc, utils/http.hh
This PR implements the following new nodetool commands:
* snapshot
* drain
* flush
* disableautocompaction
* enableautocompaction
All commands come with tests and all tests pass with both the new and the current nodetool implementations.
=> Nodetool additional commands 4/N

docs/cql/mv.rst, docs/using-scylla/materialized-views.rst
This PR is a follow-up to https://github.com/scylladb/scylladb/pull/15742#issuecomment-1766888218.
It adds CQL Reference for Materialized Views to the Materialized Views page.
In addition, it removes the irrelevant information about when the feature was added and replaces "Scylla" with "ScyllaDB".
(nobackport)
=> doc: add CQL Reference for Materialized Views and remove irrelevant version information

replica/database.cc, replica/database.hh, sstables/sstables_manager.cc, sstables/sstables_manager.hh, sstables/storage.cc, sstables/storage.hh, test/object_store/test_basic.py
After 146e49d0dd (Rewrap keyspace population loop) the datadir layout is no longer needed by sstables boot-time loader and finally directories can be omitted for S3-backed keyspaces. Tables of that keyspace don't touch/remove their datadirs either (snapshots still don't work for S3)
fixes: #13020
=> Do not create directories in datadir for S3-backed sstables

schema/schema.cc, test/boost/cql_query_test.cc, test/cql-pytest/test_describe.py
Add a space after each colon and comma (if they don't have any after) in values of table option which are json objects (`caching`, `tombstone_gc` and `cdc`).
This improves readability and matches client-side describe format.
Fixes: #14895
=> schema: add whitespaces to values of table options

test/boost/multishard_mutation_query_test.cc, test/lib/test_utils.hh
There are two tests, test_read_all and test_read_with_partition_row_limits, which asserts on every page as well
as at the end that there are no misses whatsoever. This is incorrect, because it is possible that on a given page, not all shards participate and thus there won't be a saved reader on every shard. On the subsequent page, a shard without a reader may produce a miss. This is fine. Refine the asserts, to check that we have only as much misses, as many
shards we have without readers on them.
Fixes: https://github.com/scylladb/scylladb/issues/14087
=> Multishard mutation query test fix misses expectations

gms/gossiper.cc, gms/gossiper.hh, service/storage_service.cc
Remove `fall_back_to_syn_msg` which is not necessary in newer Scylla versions.
Fix the calculation of `nodes_down` which could count a single node multiple times.
Make shadow round mandatory during bootstrap and replace -- these operations are unsafe to do without checking features first, which are obtained during the shadow round (outside raft-topology mode).
Finally, during node restart, allow the shadow round to be skipped when getting `timeout_error`s from contact points, not only when getting `closed_error`s (during restart it's best-effort anyway, and in general it's impossible to distinguish between a dead node and a partitioned node).
More details in commit messages.
Ref: https://github.com/scylladb/scylladb/issues/15675
=> Improvements to gossiper shadow round

service/raft/raft_group0.cc, service/raft/raft_group0.hh, service/storage_service.cc
When a node tries to join the cluster, it asks the topology
coordinator to add them and then waits for the response. The
response is not guaranteed to come back. If the topology
coordinator cannot contact the joining node, it moves the node to
the left state and moves on.
Currently, to handle the case when the response does not come back,
the joining node gives up waiting for it after 3 minutes. However,
it might take more time for the topology coordinator to start
handling the request to join, as it might be working on other tasks
like adding other nodes, performing tablet migrations, etc. In
general, any timeout duration would be unreliable.
Therefore, we get rid of the timeout. From now on, the operator
will be responsible for shutting down the node if the topology
coordinator fails to …
=> raft topology: join: do not time out waiting for the node to be joined

docs/_ext/scylladb_cc_properties.py, docs/_static/css/custom.css, docs/_templates/db_config.tmpl, docs/_templates/db_option.tmpl, docs/reference/configuration-parameters.rst
since we use `sphinx_multiversion` for building multiple versions of document. and in #15860, we changed the way how options are rendered, so the same change should be applied to the branch which includes the option list.
to address the conflicts, in addition to #15860, the depended PRs are also backported. so, in this pull request, following PRs are backported:
- #15827
- #15782
- #15860
=> [Backport 5.4]: docs: render options with role

auth/password_authenticator.cc, test/auth_cluster/conftest.py, test/auth_cluster/pytest.ini, test/auth_cluster/suite.yaml, test/auth_cluster/test_password_login_message.py, test/pylib/manager_client.py, test/topology/conftest.py
Propagate `exceptions::unavailable_exception` error message to the client such as cqlsh.
Fixes #2339
=> auth: fix error message when consistency level is not met

compaction/compaction.cc, compaction/compaction_strategy.cc, compaction/compaction_strategy.hh, compaction/compaction_strategy_impl.hh, compaction/time_window_compaction_strategy.cc, compaction/time_window_compaction_strategy.hh, replica/table.cc, streaming/consumer.cc, test/boost/sstable_compaction_test.cc
TWCS tables require partition estimation adjustment as incoming streaming data can be segregated into the time windows. 
Turns out we had two problems in this area that leads to suboptimal bloom filters.
1) With off-strategy enabled, data segregation is postponed, but partition estimation was adjusted as if segregation wasn't postponed. Solved by not adjusting estimation if segregation is postponed.
2) With off-strategy disabled, data segregation is not postponed, but streaming didn't feed any metadata into partition estimation procedure, meaning it had to assume the max windows input data can be segregated into (100). Solved by using schema's default TTL for a precise estimation of window count.
For the future, we want to dynamically size filters (see …
=> Fix partition estimation with TWCS tables during streaming

test/cql-pytest/test_permissions.py, test/cql-pytest/test_udf.py
This short series fixes test/cql-pytest/test_permissions.py to stop failing on Cassandra.
The second patch fixes these failures (and explains why). The first patch is a new test for UDFs, which helped me prove that one of the test_permissions.py failures in Cassandra is a Cassandra bug - some esoteric error path that prints the right message when no permissions are involved, becomes wrong when permissions are added.
Fixes #15969
=> test/cql-pytest: fix test_permissions.py to not fail on Cassandra

compaction/compaction_manager.hh, test/boost/sstable_compaction_test.cc, test/lib/sstable_test_env.hh, test/lib/sstable_utils.cc, test/lib/sstable_utils.hh, test/lib/test_services.cc
This is continuation of a34c8dc4 (Drop compaction_manager_for_testing).
There's one more wrapper over compaction_manager to access its private fields. All such access was recently moved to sstables::test_env's compaction manager, now it's time to drop the remaining legacy wrapper class.
=> Drop compaction_manager_test

compaction/compaction_manager.cc, compaction/compaction_manager.hh, compaction/task_manager_module.cc, compaction/task_manager_module.hh, tasks/task_manager.cc, test/rest_api/suite.yaml, test/rest_api/test_compaction_task.py
Compaction tasks which do not have a parent are abortable
through task manager. Their children are aborted recursively.
Compaction tasks of the lowest level are aborted using existing
compaction task executors stopping mechanism.
=> compaction: abort compaction tasks

test/cql-pytest/cassandra_tests/validation/operations/compact_storage_test.py, test/cql-pytest/cassandra_tests/validation/operations/select_single_column_relation_test.py, test/cql-pytest/test_compaction_strategy_validation.py, test/cql-pytest/test_describe.py, test/cql-pytest/test_filtering.py, test/cql-pytest/test_guardrail_replication_strategy.py, test/cql-pytest/test_keyspace.py, test/cql-pytest/test_materialized_view.py, test/cql-pytest/test_secondary_index.py
As a general rule, tests in test/cql-pytest shouldn't just pass on Scylla - they also should not fail on Cassandra; A test that fails on Cassandra may indicate that the test is wrong, or that Scylla's behavior is wrong and the test just enshrines that wrong behavior. Each time we see a test fail on Cassandra we need to check if this is not the case. We also have special markers scylla_only and cassandra_bug to put on tests that we know _should_ fail on Cassandra because it is missing some Scylla-only feature or there is a bug in Cassandra, respectively. Such tests will be xfailed/skipped when running on Cassandra, and not report failures.
Unfortunately, over time more several tests got into our suite in that did not pass on Cassandra. In this series I went over all of them, and fixed each …
=> Fix tests in test/cql-pytest/ that fail on Cassandra

cache_flat_mutation_reader.hh, mutation/mutation_partition_v2.cc, mutation/partition_version.cc, partition_snapshot_row_cursor.hh
This is a loose collection of fixes to rare row cache bugs flushed out by running test_concurrent_reads_and_eviction several million times. See individual commits for details.
Fixes #15483
=> Fix a few rare bugs in row cache

service/migration_manager.cc
This miniset addresses two potential conversions to `global_schema_ptr` of incomplete materialized views schemas.
One of them was completely unnecessary and also is a "chicken and an egg" problem where on the sync schema procedure itself a view schema was converted to `global_schema_ptr` solely for the purposes of logging. This can create a
"hickup" in the materialized views updates if they are comming from a node with a different mv schema.
The reason why sometimes a synced schema can have no base info is because of deactivision and reactivision of the schema inside the `schema_registry` which doesn't restore the base information due to lack of context.
When a schema is synced the problem becomes easy since we can just use the latest base information from the database.
Fixes #14011
=> Materialize_views:  don't construct `global_schema_ptr` from views schemas that lacks base information

cql3/statements/create_keyspace_statement.cc, replica/database.cc, sstables/sstables_manager.cc, sstables/sstables_manager.hh, test/cql-pytest/test_keyspace.py, test/object_store/test_basic.py
Currently CREATE KEYSPACE ... WITH STORAGE = { 'type' = 'S3' ... } will create keyspace even if the backend configuration is "invalid" in the sense that the requested endpoint is not known to scylla via object_storage.yaml config file. The first time after that when this misconfiguration will reveal itself is when flushing a memtable (see #15635), but it's good to know the endpoint is not configured earlier than that.
fixes: #15074
=> When creating S3-backed keyspace, check the endpoint instantly

mutation/mutation_partition.cc, mutation_query.hh, test/boost/mutation_query_test.cc
reconcilable_result_builder passes range tombstone changes to _rt_assembler
using table schema, not query schema.
This means that a tombstone with bounds (a; b), where a < b in query schema
but a > b in table schema, will not be emitted from mutation_query.
This is a very serious bug, because it means that such tombstones in reverse
queries are not reconciled with data from other replicas.
If *any* queried replica has a row, but not the range tombstone which deleted
the row, the reconciled result will contain the deleted row.
In particular, range deletes performed while a replica is down will not
later be visible to reverse queries which select this replica, regardless of the
consistency level.
As far as I can see, this doesn't result in any persistent data loss.
Only in that some data …
=> mutation_query: properly send range tombstones in reverse queries

test/lib/cql_test_env.cc
This PR contains two patches which get rid of unnecessary sleeps on cql_test_env teardown greatly reducing run time of tests.
Reduces run time of `build/dev/test/boost/schema_change_test` from 90s to 6s.
=> tests: Skip unnecessary sleeps in cql_test_env teardown

service/storage_service.cc, test/pylib/manager_client.py, test/pylib/scylla_cluster.py, test/topology/suite.yaml, test/topology/test_cluster_features.py, test/topology/test_replace_alive_node.py, test/topology_custom/suite.yaml, test/topology_custom/test_replace.py, test/topology_experimental_raft/test_raft_ignore_nodes.py
The replace operation is defined to succeed only if the node being
replaced is dead. We should reject this operation when the failure
detector considers the node being replaced alive.
Apart from adding this change, this PR adds a test case -
`test_replacing_alive_node_fails` - that verifies it. A few testing
framework adjustments were necessary to implement this test and
to avoid flakiness in other tests that use the replace operation after
the change. From now, we need to ensure that all nodes see the
node being replaced as dead before starting the replace. Otherwise,
the check added in this PR could reject the replace.
Additionally, this PR changes the replace procedure in a way that
if the replacing node reuses the IP of the node being replaced, other
nodes can see it as alive only …
=> raft topology: reject replace if the node being replaced is not dead

test/boost/sstable_compaction_test.cc
before this change, in sstable_run_based_compaction_test, we check
every 4 sstables, to verify that we close the sstable to be replaced
in a batch of 4.
since the integer-based generation identifier is monotonically
incremental, we can assume that the identifiers of sstables are like
0, 1, 2, 3, .... so if the compaction consumes sstable in a
batch of 4, the identifier of the first one in the batch should
always be the multiple of 4. unfortunately, this test does not work
if we use uuid-based identifier.
but if we take a closer look at how we create the dataset, we can
have following facts:
1. the `compaction_descriptor` returned by
`sstable_run_based_compaction_strategy_for_tests` never
set `owned_ranges` in the returned descriptor
2. in `compaction::setup_sstable_reader`, …
=> test/sstable_compaction_test: check every sstable replaced sstable 

configure.py, idl/raft.idl.hh, raft/raft.hh, raft/server.cc, raft/server.hh, service/raft/group0_fwd.hh, service/raft/raft_group0.cc, service/raft/raft_group_registry.cc, service/raft/raft_rpc.cc, service/raft/raft_rpc.hh
In topology on raft mode, the events "new node starts its group0 server" and "new node is added to group0 configuration" are not synchronized with each other. Therefore it might happen that the cluster starts sending commands to the new node before the node starts its server. This might lead to harmless, but ugly messages like:
INFO  2023-09-27 15:42:42,611 [shard 0:stat] rpc - client 127.0.0.1:56352 msg_id 2:  exception "Raft group b8542540-5d3b-11ee-99b8-1052801f2975 not found" in no_wait handler ignored
In order to solve this, the failure detector verb is extended to report information about whether group0 is alive. The raft rpc layer will drop messages to nodes whose group0 is not seen as alive.
Tested by adding a delay before group0 is started on the joining node, running all …
=> raft: send group0 RPCs only if the destination group0 server is seen as alive

test/pylib/manager_client.py, test/pylib/scylla_cluster.py, test/topology_experimental_raft/test_concurrent_bootstrap.py
We add a test for concurrent bootstrap in the raft-based topology.
Additionally, we extend the testing framework with a new function -
`ManagerClient.servers_add`. It allows adding multiple servers
concurrently to a cluster.
This PR is the first step to fix #15423. After merging it, if the new test
doesn't fail for some time in CI, we can:
- use `ManagerClient.servers_add` in other tests wherever possible,
- start initial servers concurrently in all suites with
`initial_size > 0`.
=> test: topology: test concurrent bootstrap

api/api-doc/storage_service.json, api/storage_service.cc, repair/repair.cc, repair/row_level.cc, repair/row_level.hh, repair/task_manager_module.hh
repair: Introduce small table optimization
*) Problem:
We have seen in the field it takes longer than expected to repair system tables
like system_auth which has a tiny amount of data but is replicated to all nodes
in the cluster. The cluster has multiple DCs. Each DC has multiple nodes. The
main reason for the slowness is that even if the amount of data is small,
repair has to walk though all the token ranges, that is num_tokens *
number_of_nodes_in_the_cluster. The overhead of the repair protocol for each
token range dominates due to the small amount of data per token range. Another
reason is the high network latency between DCs makes the RPC calls used to
repair consume more time.
*) Solution:
To solve this problem, a small table optimization for repair is introduced in
this patch. A …
=> repair: Introduce small table optimization

db/schema_tables.cc, db/system_keyspace.hh, repair/row_level.cc, service/migration_manager.cc, service/migration_manager.hh, service/storage_proxy.cc, streaming/stream_session.cc, test/pylib/log_browsing.py
- remove some code that is obsolete in newer Scylla versions,
- fix some minor bugs. These bugs appear to be benign, there are no known issues caused by them, but fixing them is a good idea nevertheless,
- refactor some code for better maintainability.
Parts of this PR were extracted from https://github.com/scylladb/scylladb/pull/15331 (which was merged but later reverted), parts of it are new.
=> Minor fixes and refactors

compaction/compaction_manager.cc, compaction/compaction_manager.hh, compaction/task_manager_module.cc, compaction/task_manager_module.hh, tasks/task_manager.cc, test/rest_api/suite.yaml, test/rest_api/test_compaction_task.py
Compaction tasks which do not have a parent are abortable
through task manager. Their children are aborted recursively.
Compaction tasks of the lowest level are aborted using existing
compaction task executors stopping mechanism.
=>  compaction: abort compaction tasks

db/config.hh, main.cc, replica/table.cc, sstables/storage.cc, test/boost/s3_test.cc, test/boost/schema_change_test.cc, test/lib/test_services.cc, test/object_store/conftest.py, test/object_store/test_basic.py, utils/exceptions.hh, utils/s3/client.cc, utils/s3/creds.hh
Nowadays if memtable gets flushed into misconfigured S3 storage, the flush fails and aborts the whole scylla process. That's not very elegant. First, because upon restart garbage collecting non-sealed sstables would fail again. Second, because re-configuring an endpoint can be done runtime, scylla re-reads this config upon HUP signal.
Flushing memtable restarts when seeing ENOSPC/EDQUOT errors from on-disk sstables. This PR extends this to handle misconfigured S3 endpoints as well.
fixes: #13745
=> Make memtable flush tolerate misconfigured S3 storage

api/api-doc/column_family.json, api/api-doc/storage_service.json, api/column_family.cc, api/storage_service.cc, compaction/task_manager_module.cc, compaction/task_manager_module.hh, db/config.cc, db/config.hh, docs/operating-scylla/nodetool-commands/compact.rst, docs/operating-scylla/nodetool-commands/flush.rst, replica/database.cc, replica/database.hh, replica/table.cc, test/nodetool/conftest.py, test/nodetool/test_compact.py, test/nodetool/test_flush.py, test/rest_api/test_column_family.py, test/rest_api/test_compaction_task.py, test/rest_api/test_storage_service.py, tools/scylla-nodetool.cc
Major compaction already flushes each table to make
sure it considers any mutations that are present in the
memtable for the purpose of tombstone purging.
See 64ec1c6ec64291064678e3818e3ffdee4294dbfe
However, tombstone purging may be inhibited by data
in commitlog segments based on `gc_time_min` in the
`tombstone_gc_state` (See f42eb4d1ce321e93b934ce23e128af29d23d66f8).
Flushing all sstables in the database release
all references to commitlog segments and there
it maximizes the potential for tombstone purging,
which is typically the reason for running major compaction.
However, flushing all tables too frequently might
result in tiny sstables.  Since when flushing all
keyspaces using `nodetool flush` the `force_keyspace_compaction`
api is invoked for keyspace successively, we need a …
=> Major compaction: flush commitlog by forcing new active segment and flushing all tables

CMakeLists.txt, configure.py
as part of the efforts to migrate to the CMake-based building system,
this change enables us to `configure.py` to optionally create
`build.ninja` with CMake.
in this change, we add a new option named `--use-cmake` to
`configure.py` so we can create `build.ninja`. please note,
instead of using the "Ninja" generator used by Seastar's
`configure.py` script, we use "Ninja Multi-Config" generator
along with `CMAKE_CROSS_CONFIGS` setting in this project.
so that we can generate a `build.ninja` which is capable of
building the same artifacts with multiple configuration.
Refs #15379
=> build: add an option to create building system with CMake

dist/common/scripts/scylla_swap_setup
This patch fixes error check and speed up swap allocation.
Following patches are included:
- scylla_swap_setup: run error check before allocating swap
avoid create swapfile before running error check
- scylla_swap_setup: use fallocate on ext4
this inclease swap allocation speed on ext4
=> scylla_swap_setup: run error check before allocating swap and increase swap allocation speed

sstables/sstable_directory.cc, sstables/sstable_directory.hh, sstables/sstables_manager.cc, sstables/storage.cc, sstables/storage.hh
The current implementation starts in sstables_manager that gets the deletion function from storage which, in turn, should atomically do sst.unlink() over a list of sstables (s3 driver is still not atomic though #13567).
This PR generalizes the atomic deletion inside sstables_manager method and removes the atomic deletor function that nobody liked when it was introduced (#13562)
=> Generalize atomic sstables deletion

test/nodetool/test_logging.py, test/nodetool/test_nodeops.py, test/nodetool/test_refresh.py, tools/scylla-nodetool.cc
This PR implements the following new nodetool commands:
* decomission
* rebuild
* removenode
* getlogginglevels
* setlogginglevel
* move
* refresh
All commands come with tests and all tests pass with both the new and the current nodetool implementations.
=> tools/scylla-nodetool: implement additional commands, part 5/N 

replica/database.cc
When a table is truncated or dropped it can be auto-snapshotted if the respective config option is set (by default it is). Non local storages don't implement snapshotting yet and emit on_internal_error() in that case aborting the whole process. It's better to skip snapshot with a warning instead.
=> Skip auto snapshot for non-local storages

compaction/task_manager_module.cc, replica/database.hh, replica/table.cc
Currently, if a compaction function enters the table
or compaction_group async_gate, we can't stop it
on the table/compaction_group stop path as they co_await
their respective async_gate.close().
This series introduces a table_ptr smart pointer to guards
the table object by entering its async_gate, and
it also defers awaiting the gate.close future
till after stopping ongoing compaction so that
closing the gate will prevent starting new compactions
while ongoing compaction can be stopped and finally
awaiting the close() future will wait for them to
unwind and exit the gate after being stopped.
Fixes #16305
=> Guard tables in compaction tasks

api/scrub_status.hh, api/storage_service.cc, test/nodetool/rest_api_mock.py, test/nodetool/test_scrub.py, tools/scylla-nodetool.cc
On top of the capabilities of the java-nodetool command, the following additional functionalit is implemented:
* Expose quarantine-mode option of the scrub_keyspace REST API
* Exit with error and print a message, when scrub finishes with abort or validation_errors return code
The command comes with tests and all tests pass with both the new and the current nodetool implementations.
Refs: #15588
Refs: #16208
=> scylla-nodetool: implement the scrub command

mutation_writer/multishard_writer.cc, reader_concurrency_semaphore.cc, reader_concurrency_semaphore.hh, replica/database.cc, replica/table.cc, scylla-gdb.py, sstables/sstables.cc, sstables/sstables_manager.cc, sstables/sstables_manager.hh, test/boost/hashers_test.cc, test/boost/mutation_reader_test.cc, test/boost/querier_cache_test.cc, test/boost/reader_concurrency_semaphore_test.cc, test/boost/row_cache_test.cc, test/lib/reader_concurrency_semaphore.hh, test/lib/reader_lifecycle_policy.hh, test/lib/test_services.cc, test/perf/perf.cc, test/unit/row_cache_stress_test.cc, tools/schema_loader.cc, tools/scylla-sstable.cc
Reduce code duplication by defining each metric just once, instead of three times, by having the semaphore register metrics by itself. This also makes the lifecycle of metrics contained in that of the semaphore. This is important on enterprise where semaphores are added and removed, together with service levels.
We don't want all semaphores to export metrics, so a new parameter is introduced and all call-sites make a call whether they opt-in or not.
Fixes: https://github.com/scylladb/scylladb/issues/16402
=> database, reader_concurrency_semaphore: deduplicate reader_concurrency_semaphore metrics 

test/boost/s3_test.cc, utils/s3/client.cc
The test case that validates upload-sink works does this by getting several random ranges from the uploaded object and checks that the content is what it should be. The range boundaries are generated like this:
```
uint64_t len = random(1, chunk_size);
uint64_t offset = random(file_size) - len;
```
The 2nd line is not correct, if random number happens less than the len the offset befomes "negative", i.e. -- very large 64-bit unsigned value.
Next, this offset:len gets into s3 client's get_object_contiguous() helper which in turn converts them into http range header's bytes-specifier format which is "first_bytet-last_byte" one. The math here is
```
first_byte = offset;
last_byte = offset + len - 1;
```
Here the overflow of the offset thing results in underflow of the last_byte -- it becomes …
=> Handle S3 partial read overflows

repair/repair.cc, repair/repair_task.hh, repair/row_level.cc
Shard id is logged twice in repair (once explicitly, once added by logger).
Redundant occurrence is deleted.
shard_repair_task_impl::id (which contains global repair shard)
is renamed to avoid further confusion.
Fixes: https://github.com/scylladb/scylladb/issues/12955
=> [Backport 5.2] Shard of shard repair task impl

test/boost/commitlog_test.cc
Fixes #16312
This test replays a segment before it might be closed or even fully flushed, thus it can (with the new semantics) generate a segment_truncation exception if hitting eof earlier than expected. (Note: test does not use pre-allocated segments).
(First patch makes the test coroutinized to make for a nicer, easier fix change.
=> commitlog_test::test_commitlog_reader: handle segment_truncation

alternator/executor.cc, db/view/view.cc, test/topology_experimental_raft/test_mv_tablets.py
The pull requests adds support for tablets in Alternator, and particularly focuses in getting Alternator's GSI and LSI (i.e., materialized views)  to work.
After this series support for tablets in Alternator _mostly_ work, but not completely:
1. CDC doesn't yet work with tablets, and Alternator needs to provide CDC (known as "DynamoDB Streams").
2. Alternator's TTL feature was not tested with tablets, and probably doesn't work because it assumes the replication map belongs to a keyspace.
Because of these reasons, Alternator does not yet use tablets by default and it needs to be enabled explicitly be adding an experimental tag to the new table. This will allow us to test Alternator with tablets even before it is ready for the limelight.
Fixes #16203
Fixes #16313
=> Add support for tablets in Alternator

test/cql-pytest/test_tools.py, test/nodetool/test_nodetool.py, tools/scylla-nodetool.cc, tools/scylla-sstable.cc, tools/scylla-types.cc, tools/utils.cc
Currently, `tool_app_template::run_async()` crashes when invoked with empty argv (with just `argv[0]` populated). This can happen if the tool app is invoked without any further args, e.g. just invoking `scylla nodetool`. The crash happens because unconditional dereferencing of `argv[1]` to get the current operation.
To fix, add an early-exit for this case, just printing a usage message and exiting with exit code 2.
Fixes: #16451
=>  tools/utils: tool_app_template: handle the case of no args 

CMakeLists.txt, cmake/mode.RelWithDebInfo.cmake, configure.py
this preserves the existing behavior of `configure.py` in the CMake
generated `build.ninja`.
* configure.py: map 'release' to 'RelWithDebInfo'
* cmake: rename cmake/mode.Release.cmake to cmake/mode.RelWithDebInfo.cmake
* CMakeLists.txt: s/Release/RelWithDebInfo/
=> build: cmake: map 'release' to 'RelWithDebInfo'

test/cql-pytest/test_tools.py, tools/schema_loader.cc, tools/scylla-sstable.cc
In other words, print more user-friendly messages, and avoid crashing.
Specifically:
* Don't crash when attempting to load schema tables from configured data-dir, while configuration does not have any configured data-directories.
* Detect the case where schema mutations have no rows for the current table -- the keyspace exists, but the table doesn't.
* Add negative tests for schema-loading.
Fixes: https://github.com/scylladb/scylladb/issues/16459
=> scylla-sstable: handle attempt to load schema for non-existent tables more gracefully

db/system_keyspace.hh, db/virtual_tables.cc, db/virtual_tables.hh, replica/database.cc, schema/schema_registry.cc, schema/schema_registry.hh
Both virtual tables and schema registry contain thread_local caches that are destroyed
at thread exit. after a Seastar change[1], these destructions can happen after the reactor
is destroyed, triggering a use-after-free.
Fix by scoping the destruction so it takes place earlier.
[1] https://github.com/scylladb/seastar/commit/101b245ed709d7170f3addcb4ebdc87763d6f65b
=> virtual_tables, schema_registry: fix use after free related to schema registry

db/config.cc, db/config.hh, db/schema_tables.cc, db/tags/utils.cc, db/view/view.cc, index/secondary_index_manager.cc, service/migration_manager.cc, test/lib/cql_test_env.cc, test/topology_experimental_raft/test_mv_tablets.py
Before this series, materialized views already work correctly on keyspaces with tablets, but secondary indexes do not. The goal of these series is make CQL secondary indexes fully supported on tablets:
1. First we need to make CREATE INDEX work with tablets (it didn't before this series). Fixes #16396.
2. Then we need to keep the promise that our documentation makes - that **local** secondary index should be synchronously updated - Fixes #16371.
As you can see in the patches below, and as was expected already in the design phase, the code changes needed to make indexes support tablets were minimal. But writing reliable tests for these issues was the biggest effort that went into this series.
=> Fix secondary index feature with tablets

cql3/statements/alter_keyspace_statement.cc, test/topology_custom/test_tablets.py
This switch is currently possible, but results in not supported keyspace state
=> Don't allow ALTER KEYSPACE to change replication strategy vnode/per-table flavor

dist/common/scripts/scylla_setup, dist/common/systemd/scylla-helper.slice, dist/common/systemd/scylla-server.service, dist/common/systemd/scylla-server.slice, scylla_post_install.sh
Since we decided to drop CentOS7 support from latest version of Scylla, now we can drop CentOS7 specific codes from packaging scripts and setup scripts.
Related scylladb/scylla-enterprise#3502
=> Drop CentOS7 specific codes

cql3/selection/selection.cc, cql3/selection/selection.hh, cql3/statements/select_statement.cc, test/cql-pytest/test_aggregate.py, test/cql-pytest/test_group_by.py
This short series fixes a regression from Scylla 5.2 to Scylla 5.4 in "SELECT * GROUP BY" - this query was supposed to return just a single row from each partition (the first one in clustering order), but after the expression rewrite started to wrongly return all rows.
The series also includes a regression test that verifies that this query works doesn't work correctly before this series, but works with this patch - and also works as expected in Scylla 5.2 and in Cassadra.
Fixes #16531.
=> cql: fix regression in SELECT * GROUP BY

cql3/statements/select_statement.cc, test/cql-pytest/test_permissions.py
Commit 62458b8e4f9c387d5ff5ad294c3383c5e8d54ce1 introduced the enforcement of EXECUTE permissions of functions in cql select. However, according to the reference in #12869, the permissions should be enforced only on UDFs and UDAs.
The code does not distinguish between the two so the permissions are also unintenionally enforced also on native function. This commit introduce the distinction and only enforces the permissions on non native functions.
Fixes #16526
Manually verified (before and after change) with the reproducer supplied in #16526 and also with some the `min` and `max` native functions.
Also added test that checks for regression on native functions execution and verified that it fails on authorization before 
the fix and passes after the fix.
=> select statement: verify EXECUTE permissions only for non native functions

api/api-doc/system.json, api/system.cc, test/pylib/rest_client.py, test/pylib/scylla_cluster.py
This change is motivated by wanting to have code coverage reporting support.
Currently the only way to get a profile dump in ScyllaDB is stopping it with SIGTERM, however, this doesn't
suite all cases, more specifically:
1. In dtest, when some of the tests intentionally abruptly kill a node
2. In test.py, where we would like to distinguish (at least for now), graceful shutdown of ScyllaDB testing and
teardown procedures (which currently kills the nodes).
This mini series adds two changes:
1. It adds the support for profile dumping in ScyllaDB with rest api ('/system/dump_profile')
2. It adds the support for this API in test.py and also adds a call for it as part of the node stop procedure in a permissive way that will not fail the teardown or test if the call doesn't succeed for whatever …
=> Profile dumping rest api support

alternator/executor.cc, auth/service.cc, cql3/statements/ks_prop_defs.cc, data_dictionary/data_dictionary.cc, data_dictionary/keyspace_metadata.hh, db/schema_tables.cc, db/system_distributed_keyspace.cc, table_helper.cc, test/lib/expr_test_utils.cc
The amount of arguments needed to create ks metadata object is pretty large and there are many different ways it can be and it is created over the code. This set simplifies it for the most typical patterns.
closes: #16447
closes: #16449
=> Sanitize keyspace_metadata creation

db/view/view.cc, test/topology_experimental_raft/test_mv_tablets.py
This small series improves two things in the multi-node tests for tablet supports in materialized views:
1. The test for Alternator LSI, which "sometimes" could reproduce the bug by creating 10-node cluster with a random tablet distribution, is replaced by a reliable 2-node cluster which controls the tablet distribution. The new test also confirms that tablets are actually enabled in Alternator (reviewers of the original test noted it would be easy to pass the test if tablets were accidentally not enabled... :-)).
2. Simplify the tablet lookup code in the test to not go through a "table id", and lookup the table's (or view's) name directly (requires a full-table of the tablets table, but that's entirely reasonable in a test).
The third patch in this series also fixes a comment typo …
=> Some cleanups in tests for tablets + MV 

service/storage_service.cc
In the Raft-based topology, we should never update token metadata
through gossip notifications. `storage_service::on_alive` and
`storage_service::on_remove` do it, so we ignore their parts that
touch token metadata.
Additionally, we improve some logs in other places where we ignore
the function because of using the Raft-based topology.
Fixes scylladb/scylladb#15732
=> raft topology: do not update token metadata in on_alive and on_remove

replica/database.cc, replica/database.hh, replica/memtable.cc, replica/memtable.hh, replica/table.cc, test/boost/memtable_test.cc
In 7d5e22b43b6 ("replica: memtable: don't forget memtable
memory allocation statistics") we taught memtable_list to remember
learned memory allocation reserves so a new memtable inherits these
statistics from an older memtable. Share it now further across tablets
that belong to the same table as well. This helps the statistics be more
accurate for tablets that are migrated in, as they can share existing
tablet's memory allocation history.
=> table, memtable: share log structured allocator statistics across all tablets in a table

test/raft/randomized_nemesis_test.cc
we are using `seastar::format()` to format `append_entry` in
`append_reg_model`, so we have to provide a `fmt::formatter` for
these callers which format `append_entry`.
despite that, with FMT_DEPRECATED_OSTREAM, the formatter is defined
by fmt v9, we don't have it since fmt v10. so this change prepares us
for fmt v10.
=> test: randomized_nemesis_test: add formatter for append_entry

gms/gossiper.cc, gms/gossiper.hh, service/raft/raft_group_registry.cc, service/storage_service.cc, test/topology_custom/test_old_ip_notification_repro.py
Currently, `add_saved_endpoint` is called from two paths:  One, is when loading states from system.peers in the join path (join_cluster, join_token_ring), when `_raft_topology_change_enabled` is false, and the other is from `storage_service::topology_state_load` when raft topology changes are enabled.
In the later path, from `topology_state_load`, `add_saved_endpoint` is called only if the endpoint_state does not exist yet.  However, this is checked without acquiring the endpoint_lock and so it races with the gossiper, and once `add_saved_endpoint` acquires the lock, the endpoint state may already be populated.
Since `add_saved_endpoint` applies local information about the endpoint state (e.g. tokens, dc, rack), it uses the local heart_beat_version, with generation=0 to update the …
=> Do not update endpoint state via gossiper::add_saved_endpoint once it was updated via gossip

raft/server.cc, raft/server.hh, service/broadcast_tables/experimental/lang.cc, service/raft/raft_group0.cc, service/raft/raft_group0_client.hh, service/storage_service.cc, test/raft/raft_server_test.cc, test/raft/replication.hh
During a shutdown, we call `storage_service::stop_transport` first.
We may try to apply a Raft command after that, or still be in the
the process of applying a command. In such a case, the shutdown
process will hang because Raft retries replicating a command until
it succeeds even in the case of a network error. It will stop when
a corresponding abort source is set. However, if we pass `nullptr`
to a function like `add_entry`, it won't stop. The shutdown
process will hang forever.
We fix all places that incorrectly pass `nullptr`. These shutdown
hangs are not only theoretical. The incorrect `add_entry` call in
`update_topology_state` caused scylladb/scylladb#16435.
Additionally, we remove the default `nullptr` values in all member
functions of `server` and `raft_group0_client` to avoid …
=> storage_service: make all Raft-based operations abortable

service/storage_service.cc, test/pylib/manager_client.py, test/topology/test_cluster_features.py, test/topology/test_topology_remove_decom.py, test/topology_custom/test_remove_alive_node.py, test/topology_custom/test_topology_remove_garbage_group0.py, test/topology_experimental_raft/test_node_isolation.py
The removenode operation is defined to succeed only if the node
being removed is dead. Currently, we reject this operation on the
initiator side (in `storage_service::raft_removenode`) when the
failure detector considers the node being removed alive. However,
it is possible that even if the initiator considers the node dead,
the topology coordinator will consider it alive when handling the
topology request. For example, the topology coordinator can use
a bigger failure detector timeout, or the node being removed can
suddenly resurrect.
This PR makes the topology coordinator reject removenode if the
node being removed is considered alive. It also adds
`test_remove_alive_node` that verifies this change.
Fixes scylladb/scylladb#16109
=> topology_coordinator: reject removenode if the removed node is alive

test/cql-pytest/test_tools.py, tools/scylla-sstable.cc
The default error handler throws an exception, which means scylla-sstable will exit with exception if there is any problem in the configuration. Not even ScyllaDB itself is this harsh -- it will just log a warning for most errors. A tool should be much more lenient. So this patch passes an error handler which just logs all errors with debug level.
If reading an sstable fails, the user is expected to investigate turning debug-level logging on. When they do so, they will see any problems while reading the configuration (if it is relevant, e.g. when using EAR).
Fixes: #16538
=> tools/scylla-sstable: pass error handler to utils::config_file::read_from_file()

test/boost/pretty_printers_test.cc, utils/pretty_printers.cc, utils/pretty_printers.hh
this is to mimic the formatting of `human_readable_value`, and to prepare for consolidating these two formatters, so we don't have two pretty printers in the tree.
=> utils/pretty_printers: add "I" specifier support

compaction/task_manager_module.hh, tasks/task_manager.cc, test/rest_api/test_compaction_task.py
Make compaction tasks internal. Drop all internal tasks without parents
immediately after they are done.
Fixes: #16735
Refs: #16694.
=> tasks: compaction: drop regular compaction tasks after they are finished

cql3/statements/alter_table_statement.cc, cql3/statements/create_table_statement.cc, cql3/statements/create_table_statement.hh, test/boost/cql_query_test.cc
Table properties validation is performed on statement execution.
Thus, when one attempts to create a table with invalid options,
an incorrect command gets committed in Raft. But then its
application fails, leading to a raft machine being stopped.
Check table properties when create and alter statements are prepared.
Fixes: https://github.com/scylladb/scylladb/issues/14710.
=> [Backport 5.2] Validate compaction strategy options in prepare

idl/storage_service.idl.hh, locator/abstract_replication_strategy.cc, locator/abstract_replication_strategy.hh, locator/tablets.cc, main.cc, service/raft/raft_address_map.hh, service/raft/raft_group0.cc, service/raft/raft_group_registry.cc, service/raft/raft_group_registry.hh, service/storage_service.cc, service/storage_service.hh, service/topology_state_machine.cc, service/topology_state_machine.hh, test/lib/cql_test_env.cc, test/topology/test_change_ip.py
The loop in `id2ip` lambda makes problems if we are applying an old raft log that contains long-gone nodes. In this case, we may never receive the `IP` for a node and stuck in the loop forever. In this series we replace the loop with an if - we just don't update the `host_id <-> ip` mapping in the `token_metadata.topology` if we don't have an `IP` yet.
The PR moves `host_id -> IP` resolution to the data plane, now it happens each time the IP-based methods of `erm` are called. We need this because IPs may not be known at the time the erm is built. The overhead of `raft_address_map` lookup is added to each data plane request, but it should be negligible. In this PR `erm/resolve_endpoints` continues to treat missing IP for `host_id` as `internal_error`, but we plan to relax this in the …
=> topology_state_load: stop waiting for IP-s

gms/gossiper.cc, gms/gossiper.hh, service/storage_service.cc
In a longevity test reported in scylladb/scylladb#16668 we observed that
NORMAL state is not being properly handled for a node that replaced
another node. Either handle_state_normal is not being called, or it is
but getting stuck in the middle. Which is the case couldn't be
determined from the logs, and attempts at creating a local reproducer
failed.
Thus the plan is to continue debugging using the longevity test, but we need
more logs. To check whether `handle_state_normal` was called and which branches
were taken, include some INFO level logs there. Also, detect deadlocks inside
`gossiper::lock_endpoint` by reporting an error message if `lock_endpoint`
waits for the lock for too long.
Ref: scylladb/scylladb#16668
=> Add more logging for `gossiper::lock_endpoint` and `storage_service::handle_state_normal`

api/api-doc/column_family.json, api/api-doc/storage_service.json, api/column_family.cc, api/storage_service.cc, compaction/task_manager_module.cc, compaction/task_manager_module.hh, db/config.cc, db/config.hh, docs/operating-scylla/nodetool-commands/compact.rst, docs/operating-scylla/nodetool-commands/flush.rst, replica/database.cc, replica/database.hh, replica/table.cc, test/nodetool/conftest.py, test/nodetool/rest_api_mock.py, test/nodetool/test_cleanup.py, test/nodetool/test_compact.py, test/nodetool/test_flush.py, test/rest_api/test_column_family.py, test/rest_api/test_compaction_task.py, test/rest_api/test_storage_service.py, tools/scylla-nodetool.cc
Major compaction already flushes each table to make
sure it considers any mutations that are present in the
memtable for the purpose of tombstone purging.
See 64ec1c6ec64291064678e3818e3ffdee4294dbfe
However, tombstone purging may be inhibited by data
in commitlog segments based on `gc_time_min` in the
`tombstone_gc_state` (See f42eb4d1ce321e93b934ce23e128af29d23d66f8).
Flushing all sstables in the database release
all references to commitlog segments and there
it maximizes the potential for tombstone purging,
which is typically the reason for running major compaction.
However, flushing all tables too frequently might
result in tiny sstables.  Since when flushing all
keyspaces using `nodetool flush` the `force_keyspace_compaction`
api is invoked for keyspace successively, we need a …
=> [Branch 5.4]: Major compaction: flush commitlog by forcing new active segment and flushing all tables

cql3/statements/alter_keyspace_statement.cc, cql3/statements/create_keyspace_statement.cc, cql3/statements/create_keyspace_statement.hh, cql3/statements/ks_prop_defs.cc, cql3/statements/ks_prop_defs.hh, docs/cql/ddl.rst, locator/network_topology_strategy.cc, locator/tablets.cc, redis/keyspace_utils.cc, test/boost/cql_query_test.cc, test/boost/tablets_test.cc, test/lib/cql_test_env.cc, test/pylib/scylla_cluster.py, test/topology/test_topology_failure_recovery.py, test/topology_custom/suite.yaml, test/topology_custom/test_tablets.py, test/topology_custom/test_topology_failure_recovery.py, test/topology_experimental_raft/test_mv_tablets.py, test/topology_experimental_raft/test_tablets.py, tools/schema_loader.cc
To enable tablets replication one needs to turn on the (experimental) feature and specify the `initial_tablets: N` option when creating a keyspace. We want tablets to become default in the future and allow users to explicitly opt it out if they want to.
This PR solves this by changing the CREATE KEYSPACE syntax wrt tablets options. Now there's a new TABLETS options map and the usage is
* `CREATE KEYSPACE ...` will turn tablets on or off based on cluster feature being enabled/disabled
* `CREATE KEYSPACE ... WITH TABLETS = { 'enabled': false }` will turn tablets off regardless of what
* `CREATE KEYSPACE ... WITH TABLETS = { 'enabled': true }` will try to enable tablets with default configuration
* `CREATE KEYSPACE ... WITH TABLETS = { 'initial': <int> }` is now the replacement for …
=> Turn on tablets on keyspace by default when the feature is enabled

db/view/view_update_generator.cc, dht/i_partitioner.cc, dht/partition_filter.hh
The goal of this PR is fix Scylla so that the dtest test_mvs_populating_from_existing_data, which starts to fail when enabling tablets, will pass.
The main fix (the second patch) is reverting code which doesn't work with tablets, and I explain why I think this code was not necessary in the first place.
Fixes #16598
=> view: revert cleanup filter that doesn't work with tablets

compaction/compaction_manager.cc, compaction/task_manager_module.hh, tasks/task_manager.cc, test/rest_api/test_compaction_task.py
Make compaction tasks internal. Drop all internal tasks without parents
immediately after they are done.
Fixes: https://github.com/scylladb/scylladb/issues/16735
Refs: https://github.com/scylladb/scylladb/issues/16694.
=> [Backport 5.4] tasks: compaction: drop regular compaction tasks after they are finished

service/storage_service.cc
If the joining node fails while handling the response from the
topology coordinator, it hangs even though it knows the join
operation has failed. Therefore, we ensure it shuts down in
this patch.
Additionally, we ensure that if the first join request response
was a rejection or the node failed while handling it, the
following acceptances by the (possibly different) coordinator
don't succeed. The node considers the join operation as failed.
We shouldn't add it to the cluster.
Fixes scylladb/scylladb#16333
=> raft topology: join: shut down a node on error in response handler

auth/allow_all_authorizer.hh, auth/authentication_options.hh, auth/authenticator.cc, auth/authenticator.hh, auth/authorizer.hh, auth/common.cc, auth/common.hh, auth/default_authorizer.cc, auth/default_authorizer.hh, auth/maintenance_socket_role_manager.cc, auth/maintenance_socket_role_manager.hh, auth/password_authenticator.cc, auth/password_authenticator.hh, auth/passwords.cc, auth/permissions_cache.cc, auth/permissions_cache.hh, auth/resource.cc, auth/role_manager.hh, auth/service.cc, auth/standard_role_manager.cc, auth/standard_role_manager.hh
these unused includes were identified by clangd. see https://clangd.llvm.org/guides/include-cleaner#unused-include-warning for more details on the "Unused include" warning.
=> auth: do not include unused headers

test/cql-pytest/cassandra_tests/validation/operations/alter_test.py, test/cql-pytest/conftest.py, test/cql-pytest/run.py, test/cql-pytest/suite.yaml, test/cql-pytest/test_cdc.py, test/cql-pytest/test_describe.py, test/cql-pytest/test_guardrail_replication_strategy.py, test/cql-pytest/test_keyspace.py, test/cql-pytest/test_select_from_mutation_fragments.py, test/cql-pytest/test_tablets.py, test/cql-pytest/test_tombstone_limit.py, test/cql-pytest/util.py
Add `--experimental-features=tablets` to both `test/cql-pytest/suite.yaml` and `test/cql-pytest/run.py`, so tablets are enabled. Detect tablet support in `contest.py` and add an xfail and skip marker to mark tests that fail/crash with tablets. These are expected to be fixed soon.
Some tests checking things around alter-keyspace, had to force-disable tablets on the created keyspace, because tablets interfere with the test (a keyspace with tablets cannot have simple strategy for example).
Tablets were also interfering with `test_keyspace.py:test_storage_options_local`, because it is expecting `system_schema.scylla_keyspaces` to not have any entries for local storage keyspace, but they have it if tablets are enabled. Adjust the test to account for this.
=> test/cql-pytest: run tests with tablets

configure.py, coverage_excludes.txt, coverage_sources.list, docs/dev/code-coverage.md, test.py, test/nodetool/suite.yaml, test/pylib/coverage_utils.py, test/pylib/lcov_utils.py, test/pylib/scylla_cluster.py, test/pylib_test/suite.yaml
This mini-set includes code coverage support for ScyllaDB, it provides:
1. Support for building ScyllaDB with coverage support.
2. Utilities for processing coverage profiling data
3. test.py support for generation and processing of coverage profiling into an lcov trace files which can later be used to produce HTML or textual coverage reports.
Refs #16323
=> Add code coverage support

docs/operating-scylla/procedures/_common/create_cluster_prerequisites_include.rst, docs/operating-scylla/procedures/cluster-management/create-cluster.rst
This PR:
- Removes the redundant information about previous versions from the Create Cluster page.
- Fixes language mistakes on that page, and replaces "Scylla" with "ScyllaDB".
(nobackport)
=> doc: improvements to the Create Cluster page

cql3/query_processor.cc, test/cql-pytest/test_materialized_view.py
When a base table changes and altered, so does the views that might
refer to the added column (which includes "SELECT *" views and also
views that might need to use this column for rows lifetime (virtual
columns).
However the query processor implementation for views change notification
was an empty function.
Since views are tables, the query processor needs to at least treat them
as such (and maybe in the future, do also some MV specific stuff).
This commit adds a call to `on_update_column_family` from within
`on_update_view`.
The side effect true to this date is that prepared statements for views
which changed due to a base table change will be invalidated.
Fixes https://github.com/scylladb/scylladb/issues/16392
This series also adds a test which fails without this fix and passes when …
=> Invalidate prepared statements for views when their schema changes.

service/storage_service.cc, service/storage_service.hh, test/topology_custom/test_replace.py, test/topology_custom/test_replace_with_same_ip_twice.py
Before the patch we called `gossiper.remove_endpoint` for IP-s of the left nodes. The problem is that in replace-with-same-ip scenario we called `gossiper.remove_endpoint` for IP which is used by the new, replacing node. The `gossiper.remove_endpoint` method puts the IP into quarantine, which means gossiper will ignore all events about this IP for `quarantine_delay` (one minute by default). If we immediately replace just replaced node with the same IP again, the bootstrap will fail since the gossiper events are blocked for this IP, and we won't be able to resolve an IP for the new host_id.
Another problem was that we called gossiper.remove_endpoint method, which doesn't remove an endpoint from `_endpoint_state_map`, only from live and unreachable lists. This means the IP will keep …
=> sync_raft_topology_nodes:  force_remove_endpoint for left nodes only if an IP is not used by other nodes

cql3/statements/create_index_statement.cc, cql3/statements/create_index_statement.hh, cql3/statements/create_view_statement.hh, index/secondary_index_manager.cc, index/secondary_index_manager.hh, replica/database.cc, test/boost/schema_loader_test.cc, test/cql-pytest/test_tools.py, tools/schema_loader.cc
Loading schemas of views and indexes was not supported, with either `--schema-file`, or when loading schema from schema sstables.
This PR addresses both:
* When loading schema from CQL (file), `CREATE MATERIALIZED VIEW` and `CREATE INDEX` statements are now also processed correctly.
* When loading schema from schema tables, `system_schema.views` is also processed, when the table has no corresponding entry in `system_schema.tables`.
Tests are also added.
Fixes: #16492
=> scylla-sstable: add support for loading schema of views and indexes

replica/table.cc, schema/schema.cc, schema/schema.hh, sstables/mx/writer.cc, sstables/sstables.cc, sstables/sstables.hh, streaming/consumer.cc
The sstable writer held the effective_replication_map_ptr while writing
sstables, which is both a layering violation and slows down tablet load
balancing. It was needed in order to ensure the sharder was stable. But
it turns out that sharding metadata is unnecessary for tablets, so just
skip the whole thing when writing an sstable for tablets.
=> sstables: writer: don't block topology changes while writing sstables

api/api.hh
This PR contains improvements related to usage of std::vector and looping over containers in the range-for loop.
It is advised to use `std::vector::reserve()` to avoid unneeded memory allocations when the total size is known beforehand.
When looping over a container that stores non-trivial types usage of const reference is advised to avoid redundant copies.
=> api/api.hh: improve usage of standard containers

test/boost/error_injection_test.cc, utils/error_injection.hh
before this change, we always cast the wait duration to millisecond,
even if it could be using a higher resolution. actually
`std::chrono::steady_clock` is using `nanosecond` for its duration,
so if we inject a deadline using `steady_clock`, we could be awaken
earlier due to the narrowing of the duration type caused by the
duration_cast.
in this change, we just use the duration as it is. this should allow
the caller to use the resolution provided by Seastar without losing
the precision. the tests are updated to print the time duration 
instead of count to provide information with a higher resolution.
Fixes #15902
=> tests: utils: error injection: print time duration instead of count

docs/dev/system_keyspace.md, docs/dev/topology-over-raft.md, locator/tablets.cc, locator/tablets.hh, locator/topology.cc, locator/topology.hh, replica/tablet_mutation_builder.hh, replica/tablets.cc, service/storage_service.cc, service/tablet_allocator.cc, service/tablet_allocator.hh, service/topology_state_machine.cc, service/topology_state_machine.hh, streaming/stream_reason.hh, test/boost/tablets_test.cc, test/topology_experimental_raft/test_tablets_removenode.py
New tablet replicas are allocated and rebuilt synchronously with node
operations. They are safely rebuilt from all existing replicas.
The list of ignored nodes passed to node operations is respected.
Tablet scheduler is responsible for scheduling tablet rebuilding transition which
changes the replicas set. The infrastructure for handling decommission
in tablet scheduler is reused for this.
Scheduling is done incrementally, respecting per-shard load
limits. Rebuilding transitions are recognized by load calculation to
affect all tablet replicas.
New kind of tablet transition is introduced called "rebuild" which
adds new tablet replica and rebuilds it from existing replicas. Other
than that, the transition goes through the same stages as regular
migration to ensure safe synchronization with …
=> tablets: Add support for removenode and replace handling

test.py, test/nodetool/conftest.py, test/nodetool/suite.yaml
before this change, we use a random address when launching
rest_api_mock server, but there are chances that the randomly
picked address conflicts with an already-used address on the
host. and the subprocess fails right away with the returncode of
1 upon this failure, but we just continue on and check the readiness
of the already-dead server. actually, we've seen test failures
caused by the EADDRINUSE failure, and when we checked the readiness
of the rest_api_mock by sending HTTP request and reading the
response, what we had is not a JSON encoded response but a webpage,
which was likely the one returned by a minio server.
in this change, we
* specify the "launcher" option of nodetool
test suite to "unshare", so that all its tests are launched
in separated namespaces.
* do not use a random …
=> test/nodetool: run nodetool tests using "unshare"

db/system_keyspace.cc, service/topology_coordinator.cc, service/topology_state_machine.hh, test/topology_experimental_raft/test_topology_ops.py
We didn't send the `barrier_and_drain` command to a
decommissioning node that could still be coordinating requests. It
could happen that a decommissioning node sent a request with an
old topology version after normal nodes received the new fence
version. Then, the request would fail on replicas with the stale
topology exception.
This PR fixes this problem by modifying `exec_global_command`.
From now on, it sends `barrier_and_drain` to a decommissioning
node.
We also stop filtering stale topology exceptions in
`test_topology_ops`. We added this filter after detecting the bug
fixed by this PR.
Fixes scylladb/scylladb#15804
Fixes scylladb/scylladb#16579
Fixes scylladb/scylladb#16642
=> raft topology: send barrier_and_drain to a decommissioning node

configure.py, db/commitlog/commitlog.cc, db/commitlog/commitlog.hh, db/commitlog/commitlog_replayer.cc, db/system_keyspace.cc, db/system_keyspace.hh, main.cc, replica/database.hh, replica/table.cc, service/storage_service.cc, test/boost/commitlog_cleanup_test.cc, test/boost/suite.yaml, test/pylib/manager_client.py, test/pylib/scylla_cluster.py, test/topology_experimental_raft/test_tablets.py
To avoid data resurrection, mutations deleted by cleanup operations should be skipped during commitlog replay.
This series implements the above for tablet cleanups, by using a new system table which holds records of cleanup operations.
Fixes #16752
=>  db: commitlog_replayer: ignore mutations affected by (tablet) cleanups 

test/nodetool/conftest.py
we should allow user to run nodetool tests without `test.py`. but there
are good chance that the host could be reused by multiple tests or
multiple users who could be using port 12345. by randomizing the IP and
port, they would have better chance to complete the test without running
into used port problem.
=> test/nodetool: return a randomized address if not running with unshare

mutation/mutation.hh, utils/config_file_impl.hh
Anonymous namespace implies internal linkage for its members.
When it is defined in a header, then each translation unit,
which includes such header defines its own unique instance
of members of the unnamed namespace that are ODR-used within
that translation unit.
This can lead to unexpected results including code bloat
or undefined behavior due to ODR violations.
This PR removes unnamed namespaces from header files.
References:
- [CppCoreGuidelines: "SF.21: Don’t use an unnamed (anonymous) namespace in a header"](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf21-dont-use-an-unnamed-anonymous-namespace-in-a-header)
- [SEI CERT C++: "DCL59-CPP. Do not define an unnamed namespace in a header file"](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL59-CPP.+Do+not+define …
=> Remove anonymous namespaces from headers

alternator/executor.cc, test/alternator/conftest.py, test/alternator/run, test/alternator/test_metrics.py, test/alternator/test_streams.py, test/alternator/test_ttl.py
This series does a similar change to Alternator as was done recently to CQL:
1. If the "tablets" experimental feature in enabled, new Alternator tables will use tablets automatically, without requiring an option on each new table. A default choice of initial_tablets is used. These choices can still be overridden per-table if the user wants to.
3. In particular, all test/alternator tests will also automatically run with tablets enabled
4. However, some tests will fail on tablets because they use features that haven't yet been implemented with tablets - namely Alternator Streams (Refs #16317) and Alternator TTL (Refs #16567). These tests will - until those features are implemented with tablets - continue to be run without tablets.
5. An option is added to the test/alternator/run to allow …
=> alternator: enable tablets by default if experimental feature is enabled

service/raft/raft_group0.cc, service/raft/raft_sys_table_storage.cc, test/topology_custom/test_raft_fix_broken_snapshot.py
The persisted snapshot index may be 0 if the snapshot was created in
older version of Scylla, which means snapshot transfer won't be
triggered to a bootstrapping node. Commands present in the log may not
cover all schema changes --- group 0 might have been created through the
upgrade upgrade procedure, on a cluster with existing schema. So a
deployment with index=0 snapshot is broken and we need to fix it. We can
use the new `raft::server::trigger_snapshot` API for that.
Also add a test.
Fixes scylladb/scylladb#16683
=> raft_group0: trigger snapshot if existing snapshot index is 0

db/config.cc, db/config.hh, docs/dev/system_keyspace.md, docs/dev/topology-over-raft.md, idl/storage_service.idl.hh, locator/tablets.cc, locator/tablets.hh, locator/topology.hh, message/messaging_service.cc, message/messaging_service.hh, replica/compaction_group.hh, replica/database.hh, replica/distributed_loader.cc, replica/table.cc, replica/tablet_mutation_builder.hh, replica/tablets.cc, service/storage_service.cc, service/storage_service.hh, service/tablet_allocator.cc, service/tablet_allocator.hh, service/tablet_allocator_fwd.hh, service/topology_coordinator.cc, test/boost/tablets_test.cc, test/topology_experimental_raft/test_fencing.py, test/topology_experimental_raft/test_tablets.py
The motivation for tablet resizing is that we want to keep the average tablet size reasonable, such that load rebalancing can remain efficient. Too large tablet makes migration inefficient, therefore slowing down the balancer.
If the avg size grows beyond the upper bound (split threshold), then balancer decides to split. Split spans all tablets of a table, due to power-of-two constraint.
Likewise, if the avg size decreases below the lower bound (merge threshold), then merge takes place in order to grow the avg size. Merge is not implemented yet, although this series lays foundation for it to be impĺemented later on.
A resize decision can be revoked if the avg size changes and the decision is no longer needed. For example, let's say table is being split and avg size drops below the target …
=> Implement tablet splitting

schema/schema.cc, schema/schema.hh
Instead of std::out_of_range(). Accessing a non-existing column is a serious bug and the backtrace coming with `on_internal_error()` can be very valuable when debugging it. As can be the coredump that is possible
to trigger with `--abort-on-internal-error`.
This change follows another similar change to `schema::column_at()`.
This should help us get to the bottom of the mysterious repair failures caused by invalid column access, seen in https://github.com/scylladb/scylladb/issues/16821.
Refs: https://github.com/scylladb/scylladb/issues/16821
=>  schema: column_mapping::{static,regular}_column_at(): use on_internal_error()

api/api-doc/storage_service.json, api/column_family.cc, api/storage_service.cc, api/tasks.cc, compaction/task_manager_module.cc, compaction/task_manager_module.hh, replica/database.hh, replica/table.cc, service/storage_service.cc, tools/scylla-nodetool.cc
according to the document "nodetool cleanup"
> Triggers removal of data that the node no longer owns
currently, scylla performs cleanup by rewriting the sstables. but
commitlog segments may still contain the mutations to the tables
which are dropped during sstable rewriting. when scylla server
restarts, the dirty mutations are replayed to the memtable. if
any of these dirty mutations changes the tables cleaned up. the
stale data are reapplied. this would lead to data resurrection.
so, in this change we following the same model of major compaction
where we
1. forcing new active segment,
2. flushing tables being cleaned up
3. perform cleanup using compaction
Fixes #4734
=> compaction_manager: flush tables before cleanup

main.cc, utils/directories.cc, utils/directories.hh
During startup, the contents of the data directory are verified to ensure that they have the right owner and permissions. Verifying all the contents, which includes files that will be read and closed immediately, and files that will be held open for longer durations, together, can lead to memory fragementation in the dentry/inode cache.
Mitigate this by updating the verification in a such way that these two set of files will be verified separately ensuring their separation in the dentry/inode cache.
Fixes https://github.com/scylladb/scylladb/issues/14506
=> directories: prevent inode cache fragmentation by orderly verifying data directory contents

configure.py, test/cql-pytest/test_native_functions.py, test/cql-pytest/test_type_date.py, utils/CMakeLists.txt, utils/UUID_gen.hh, utils/on_internal_error.cc, utils/on_internal_error.hh
This PR fixes the bug of certain calls to the `mintimeuuid()` CQL function which large negative timestamps could crash Scylla. It turns out we already had protections in place against very positive timestamps, but very negative timestamps could still cause bugs.
The actual fix in this series is just a few lines, but the bigger effort was improving the test coverage in this area. I added tests for the "date" type (the original reproducer for this bug used totimestamp() which takes a date parameter), and also reproducers for this bug directly, without totimestamp() function, and one with that function.
Finally this PR also replaces the assert() which made this molehill-of-a-bug into a mountain, by a throw.
Fixes #17035
=> Fix mintimeuuid() call that could crash Scylla

replica/table.cc, service/tablet_allocator.cc
this series addresses couple `-Wsign-compare` warnings surfaced in the tree.
=> replica, tablet_allocator: do not compare unsigned with signed

service/storage_service.cc
This is a follow up of "storage_service: Run stream_ranges cmd in streaming group" to fix indentation and drop a unnecessary co_return. 
Refs: #17090
=> storage_service: Fix indentation for stream_ranges

dht/i_partitioner.cc, dht/ring_position.hh, row_cache.cc
formatter.
in this change, we define formatters for `dht::ring_position_ext` and 
`dht::ring_position_view`, and drop their operator<<.
Refs #13245
=> db: add formatter for dht::ring_position_{ext,view}

db/system_keyspace.cc, docs/dev/topology-over-raft.md, service/storage_service.cc, service/topology_coordinator.cc, service/topology_state_machine.cc, service/topology_state_machine.hh, test/topology/test_topology_failure_recovery.py, test/topology_custom/test_topology_failure_recovery.py
After changing `left_token_ring` from a node state to a transition
state in scylladb/scylladb#17009, we do the same for
`rollback_to_normal`. `rollback_to_normal` was created as a node
state because `left_token_ring` was a node state.
This change will allow us to distinguish a failed removenode from
a failed decommission in the `rollback_to_normal` handler.
Currently, we use the same logic for both of them, so it's not
required. However, this might change, as it has happened with the
decommission and the failed bootstrap/replace in the
`left_token_ring` state (scylladb/scylladb#16797). We are making
this change now because it would be much harder after branching.
Fixes scylladb/scylladb#17032
=> raft topology: make rollback_to_normal a transition state

api/api-doc/storage_service.json, api/storage_service.cc, service/storage_service.cc, service/storage_service.hh
Validate replication strategy constraints in /storage_service/tablets/move API:
- replicas are not on the same node
- replicas don't move across DC (violates RF in each DC)
- availability is not reduced due to rack overloading
Add flag to force tablet move even though dc/rack constraints aren't fulfilled.
Test for the change: https://github.com/scylladb/scylla-dtest/pull/3911.
Fixes: #16379.
=> service: validate replication strategy constraints in tablet-moving API

test/cql-pytest/conftest.py, test/cql-pytest/test_cdc.py, test/cql-pytest/test_describe.py, test/cql-pytest/test_tombstone_limit.py
In a previous PR (https://github.com/scylladb/scylladb/pull/16840), we enabled tablets by default when running the cql-pytest suite. To handle tests which are failing with tablets enabled, we used a new fixture, `xfail_tablets` to mark these as xfail. This means that we effectively lost test coverage, as these tests can now freely fail and no-one will notice if this is due to a new regression. To restore test coverage, this PR re-enables all the previously disabled tests, by parametrizing each one of them to run with both vnodes and tablets, and targetedly mark as xfail, only the tablet variant. After these tests are fixed with tablets (or the underlying functionality they test is fixed to work with tablets), we will run them with both vnodes and tablets, because these tests apparently …
=> test/cql-pytest: re-enable disabled tests

concrete_types.hh, lang/lua.cc, types/types.cc
C++20 introduced a new overload of std::ostringstream::str() that is selected when the mentioned member function is called on r-value.
The new overload returns a string, that is move-constructed from the underlying string instead of being copy-constructed.
This change applies std::move() on stringstream objects before calling str() member function to avoid copying of the underlying buffer.
It also removes a helper function `inet_addr_type_impl::to_sstring()` - it was used only in two places. It was replaced with `fmt::to_string()`.
=> types/types.cc: move stringstream content instead of copying it

cql3/statements/ks_prop_defs.cc, locator/abstract_replication_strategy.cc, locator/abstract_replication_strategy.hh, locator/network_topology_strategy.cc, locator/simple_strategy.cc
RF values appear as strings and strategies classes convert them to integers. This PR removes some duplication of efforts in converting code.
=> Sanitize replication factor parsing by strategies

api/api-doc/raft.json, api/api.cc, api/api_init.hh, api/raft.cc, api/raft.hh, configure.py, main.cc, raft/fsm.cc, raft/fsm.hh, raft/server.cc, raft/server.hh, service/raft/raft_group0.cc, service/raft/raft_sys_table_storage.cc, test/boost/group0_cmd_merge_test.cc, test/raft/etcd_test.cc, test/raft/fsm_test.cc, test/raft/helpers.cc, test/raft/helpers.hh, test/topology_custom/test_raft_fix_broken_snapshot.py, test/topology_custom/test_raft_snapshot_request.py
Backports required to fix https://github.com/scylladb/scylladb/issues/16683 in 5.4:
- add an API to trigger Raft snapshot
- use the API when we restart and see that the existing snapshot is at index 0, to trigger a new one --- in order to fix broken deployments that already bootstrapped with index-0 snapshot (we may get such deployments by upgrading from 5.2)
=> [Backport 5.4] Raft snapshot fixes

data_dictionary/data_dictionary.cc, data_dictionary/keyspace_metadata.hh, locator/network_topology_strategy.cc, test/boost/network_topology_strategy_test.cc, test/cql-pytest/test_describe.py, test/cql-pytest/test_tablets.py, test/topology_custom/test_tablets.py
When creating a keyspace, scylla allows setting RF value smaller than there are nodes in the DC. With vnodes, when new nodes are bootstrapped, new tokens are inserted thus catching up with RF. With tablets, it's not the case as replica set remains unchanged.
With tablets it's good chance not to mimic the vnodes behavior and require as many nodes to be up and running as the requested RF is. This patch implementes this in a lazy manned -- when creating a keyspace RF can be any, but when a new table is created the topology should meet RF requirements. If not met, user can bootstrap new nodes or ALTER KEYSPACE.
closes: #16529
=> tablets: Make sure topology has enough endpoints for RF

api/api-doc/storage_service.json, api/storage_service.cc, locator/load_sketch.hh, locator/tablets.cc, locator/tablets.hh, repair/repair.cc, service/storage_service.cc, service/storage_service.hh, service/tablet_allocator.cc, test/boost/tablets_test.cc
The table query param is added to get the describe_ring result for a
given table.
Both vnode table and tablet table can use this table param, so it is
easier for users to user.
If the table param is not provided by user and the keyspace contains
tablet table, the request will be rejected.
E.g.,
curl "http://127.0.0.1:10000/storage_service/describe_ring/system_auth?table=roles"
curl "http://127.0.0.1:10000/storage_service/describe_ring/ks1?table=standard1"
Refs #16509
=> storage_service: Add describe_ring support for tablet table

test/nodetool/test_describering.py, test/nodetool/test_nodetool.py, test/nodetool/utils.py, tools/scylla-nodetool.cc
On top of the capabilities of the java-nodetool command, tablet support is also implemented: in addition to the existing keyspace parameter, an optional table parameter is also accepted and forwarded to the REST API. For tablet keyspaces this is required to get a ring description.
The command comes with tests and all tests pass with both the new and the current nodetool implementations.
Refs: https://github.com/scylladb/scylladb/issues/16846
=> scylla-nodetool: implement the describering command

bytes_ostream.hh, scylla-gdb.py, sstables/index_reader.hh, utils/managed_bytes.cc, utils/managed_bytes.hh, utils/mutable_view.hh
managed_bytes is implemented as chain of blob_storage objects.
Each blob_storage contains 24 bytes of metadata. But in the most
common case -- when there is only a single element in the chain --
16 bytes of this metadata is trivial/unused.
This is regrettable waste because managed_bytes is used for every
database cell in the memtables and cache. It means that every value
of size >= 7 bytes (smaller ones fit in the inline storage of
managed_bytes) receives 16 bytes of useless overhead.
To correct that, this series adds to managed_bytes an alternative storage
layout -- used for buffers small enough to fit in one fragment -- which only
stores the necessary minimum of metadata. (That is: a pointer to the parent,
to facilitate moving the storage during memory defragmentation).
This saves 16 …
=> utils: managed_bytes: optimize memory usage for small buffers

test/pylib/manager_client.py, test/topology_experimental_raft/test_tablets.py
Reimplements stop/start sequence using rolling_restart() which is safe
with regards to UP status propagation and not prone to sudden
connection drop which may cause later CQL queries to time out. It also
ensures that CQL is up on all the remaining nodes when the with_down
callback is executed.
The test was observed to fail in CI like this:
```
cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.157.135.26:9042 datacenter1>: ConnectionException('Pool for 127.157.135.26:9042 is shutdown')})
...
@pytest.mark.repair
@pytest.mark.asyncio
async def test_tablet_missing_data_repair(manager: ManagerClient):
...
for idx in range(0,3):
s = servers[idx].server_id
await manager.server_stop_gracefully(s, timeout=120)
>           await check()
``` …
=> test: py: tablets: Fix flakiness of test_tablet_missing_data_repair

gms/gossiper.cc, transport/controller.cc
RPC is not ready yet at this point, so we should not set this application state yet.
Also, simplify add_local_application_state as it contains dead code
that will never generate an internal error after 1d07a596bf23432326dadd74eb5b2857955fe15b.
Fixes #16932
=> transport: controller: do_start_server: do not set_cql_read for maintenance port

configure.py, mutation/partition_version.cc, mutation/partition_version.hh, row_cache.cc, row_cache.hh, test/boost/mvcc_test.cc, test/boost/row_cache_test.cc, utils/preempt.hh
Adds a test reproducing https://github.com/scylladb/scylladb/issues/16759, and the instrumentation needed for it.
=> row_cache: test cache consistency during multi-partition cache updates

cql3/statements/describe_statement.cc, db/view/view.cc, replica/database.hh, service/storage_service.cc, service/storage_service.hh, test/rest_api/test_storage_service.py
This API endpoint currently returns with status 500 if attempted to be called for a table which uses tablets. This series adds tablet support. No change in usage semantics is required, the endpoint already has a table parameter.
This endpoint is the backend of `nodetool getendpoints` which should now work, after this PR.
Fixes: #17313
=> api: storage_service/natural_endpoints: add tablets support

db/system_keyspace.cc, db/system_keyspace.hh, main.cc, service/raft/raft_group0.cc, service/raft/raft_group0.hh, service/storage_service.cc, service/storage_service.hh, test/lib/cql_test_env.cc, test/topology/test_change_ip.py
When a node changes IP address we need to remove its old IP from `system.peers` and gossiper.
We do this in `sync_raft_topology_nodes` when the new IP is saved into `system.peers` to avoid losing the mapping if the node crashes between deleting and saving the new IP. We also handle the possible duplicates in this case by dropping them on the read path when the node is restarted.
The PR also fixes the problem with old IPs getting resurrected when a node changes its IP address.
The following scenario is possible: a node `A` changes its IP from `ip1` to `ip2` with restart, other nodes are not yet aware of `ip2` so they keep gossiping `ip1`. After restart `A` receives `ip1` in a gossip message and calls `handle_major_state_change` since it considers it as a new node. Then `on_join` event is …
=> Purge old ip on change

compaction/task_manager_module.cc, replica/database.cc, replica/database.hh
Tables in keyspaces governed by replication strategy that uses tablets, have separate effective_replication_maps. Update the upgrade compaction task to handle this when getting owned key ranges for a keyspace.
Fixes #16848
=> compaction: upgrade: handle keyspaces that use tablets

repair/repair.cc, repair/row_level.cc, repair/row_level.hh, test/topology_experimental_raft/test_tablets.py
This patch wires up tombstone_gc repair with tablet repair. The flush
hints logic from the vnode table repair is reused. The way to mark the
finish of the repair is also adjusted for tablet repair because it only
has one shard per tablet token range instead of smp::count shards.
Fixes: #17046
Tests: test_tablet_repair_history
=> repair: Update repair history for tablet repair

cdc/generation.cc, cdc/generation.hh, cdc/metadata.cc, cdc/metadata.hh, docs/dev/cdc.md, docs/using-scylla/cdc/cdc-stream-generations.rst, test/topology_custom/test_writes_to_previous_cdc_generations.py
Before this PR, writes to the previous CDC generations would
always be rejected. After this PR, they will be accepted if the
write's timestamp is greater than `now - generation_leeway`.
This change was proposed around 3 years ago. The motivation was
to improve user experience. If a client generates timestamps by
itself and its clock is desynchronized with the clock of the node
the client is connected to, there could be a period during
generation switching when writes fail. We didn't consider this
problem critical because the client could simply retry a failed
write with a higher timestamp. Eventually, it would succeed. This
approach is safe because these failed writes cannot have any side
effects. However, it can be inconvenient. Writing to previous
generations was proposed to improve it. …
=> cdc: metadata: allow sending writes to the previous generations

test/nodetool/test_repair.py, test/nodetool/utils.py, tools/scylla-nodetool.cc
As usual, the new command is covered with tests, which pass with both the legacy and the new native implementation.
Refs: #15588
=> scylla-nodetool: implement the repair command

locator/topology.cc, locator/topology.hh
There's a bunch of debug- and trace-level logging of locator::node-s that also include current_backtrace(). Printing node is done via debug_format() helper that generates and returns an sstring to print. Backtrace printing is not very lightweight on its own because of backtrace collecting. Not to slow things down in info log level, which is default, all such prints are wrapped with explicit if-s about log-level being enabled or not.
This PR removes those level checks by introducing lazy_backtrace() helper and by providing a formatter for nodes that also results in lazy node format string calculation.
=> Improve printing of nodes and backtraces in topology

test/nodetool/conftest.py, test/nodetool/test_ring.py
so we exercise the cases where state and status are not "normal" and "up".
turns out the MBean is able to cache some objects. so the requets retrieving datacenter and rack are now marked `ANY`.
* filter out the requests whose `multiple` is `ANY`
* include the unconsumed requets in the raised `AssertionError`. this
should help with debugging.
Fixes #17401
=> test/nodetool: parameterize test_ring

repair/row_level.cc, repair/row_level.hh
Using `parallel_for_each_table` instance of `for_each_table_gently` on 
`repair_service::load_history`, to reduced bootstrap time.  
Using uuid_xor_to_uint32 on repair load_history dispatch to shard.
Ref: https://github.com/scylladb/scylladb/issues/16774
=> repair: accelerate repair load_history time

db/config.cc, db/config.hh, docs/operating-scylla/admin-tools/maintenance-socket.rst, generic_server.cc, generic_server.hh, redis/controller.cc, transport/controller.cc, transport/controller.hh
Set filesystem permissions for the maintenance socket to 660 (previously it was 755) to allow a scyllaadm's group to connect.
Split the logic of creating sockets into two separate functions, one for each case: when it is a regular cql controller or used by maintenance_socket.
Fixes https://github.com/scylladb/scylladb/issues/16487.
=> Maintenance socket: set filesystem permissions to 660

locator/tablets.cc, locator/tablets.hh, service/storage_service.cc, service/tablet_allocator.cc, service/topology_coordinator.cc, test/pylib/tablets.py, test/topology_custom/test_tablets_migration.py, test/topology_experimental_raft/test_tablets.py
It can happen that a node is lost during tablet migration involving that node. Migration will be stuck, blocking topology state machine. To recover from this, the current procedure is for the admin to execute nodetool removenode or replacing the node. This marks the node as "ignored" and tablet state machine can pick this up and abort the migration.
This PR implements the handling for streaming stage only and adds a test for it. Checking other stages needs more work with failure injection to inject failures into specific barrier.
To handle streaming failure two new stages are introduced -- cleanup_target and revert_migration. The former is to clean the pending replica that could receive some data by the time streaming stopped working, the latter is like end_migration, but doesn't commit …
=> Handle tablet migration failure while streaming

mutation/mutation_fragment.cc, mutation/mutation_fragment.hh, mutation/mutation_partition.hh, test/boost/frozen_mutation_test.cc
formatter.
* row_tombstone
* row_marker
* deletable_row::printer
* row::printer
* clustering_row::printer
* static_row::printer
* partition_start
* partition_end
* mutation_fragment::printer
and drop their operator<<:s
Refs #13245
=> mutation: add fmt::formatter for clustering_row, row_tombstone and friends

streaming/stream_request.cc, streaming/stream_request.hh, streaming/stream_session_state.cc, streaming/stream_session_state.hh
formatter.
* `streaming::stream_request`,
* `stream_session_state`
and drop their operator<<:s
Refs #13245
=> streaming: add fmt::formatter for stream_session_state and stream_request

api/column_family.cc
Those that collect vectors with ks/cf names can reserve the vectors in advance. Also one of those can use range loop for shorter code
=> Refine some api/column_family endpoints

compaction/compaction.cc, compaction/compaction_descriptor.hh
* `sstables::compaction_type`
* `sstables::compaction_type_options::scrub::mode`
* `sstables::compaction_type_options::scrub::quarantine_mode`
* `formatted_sstables_list`
Refs #13245
=> compaction: add fmt::formatter for types

test/boost/cache_flat_mutation_reader_test.cc, test/boost/expr_test.cc, test/lib/expr_test_utils.hh, test/perf/perf.cc, test/perf/perf.hh, test/unit/tree_test_key.hh
before this change, we rely on the default-generated fmt::formatter created from operator<<, but fmt v10 dropped the default-generated formatter. in this change, we define formatters for some types used in testing.
Refs #13245
=> test: add fmt::formatters

sstables/m_format_read_helpers.cc, sstables/mx/types.hh, sstables/sstables.hh, sstables/types.hh
formatter.
* bound_kind_m
* sstable_state
* indexable_element
* deletion_time
drop their operator<<:s
Refs #13245
=> sstables: add fmt::formatter for sstable types
