scylladb/scylladb

mutation/atomic_cell.cc, mutation/atomic_cell.hh, mutation/atomic_cell_or_collection.hh, mutation/canonical_mutation.cc, mutation/canonical_mutation.hh, mutation/mutation_partition.cc, mutation/mutation_partition_v2.cc
before this change, we rely on the default-generated fmt::formatter created from operator<<, but fmt v10 dropped the default-generated formatter.
in this change, we define formatters for 
* canonical_mutation
* atomic_cell_view
* atomic_cell
* atomic_cell_or_collection::printer
Refs #13245
=> mutation: add fmt::formatter for mutation types

sstables/index_reader.hh, sstables/sstables.cc, test/rest_api/test_column_family.py
If index_reader isn't closed before it is destroyed, then ongoing
sstables reads won't be awaited and assertion will be triggered.
Close index_reader in has_partition_key before destroying it.
Fixes: #17232.
=> sstables: close index_reader in has_partition_key

clustering_bounds_comparator.hh, test/unit/lsa_sync_eviction_test.cc, test/unit/row_cache_alloc_stress_test.cc, utils/logalloc.cc, utils/logalloc.hh, utils/managed_bytes.cc, utils/managed_bytes.hh
formatter.
* managed_bytes
* managed_bytes_view
* managed_bytes_opt
* occupancy_stats
and drop their operator<<:s
=> utils: add fmt::formatter for occupancy_stats, managed_bytes and friends 

gms/version_generator.cc, service/misc_services.cc
The function `gms::version_generator::get_next_version()` can only be called from shard 0 as it uses a global, unsynchronized counter to issue versions. Notably, the function is used as a default argument for the constructor of `gms::versioned_value` which is used from shorthand constructors such as `versioned_value::cache_hitrates`, `versioned_value::schema` etc.
The `cache_hitrate_calculator` service runs a periodic job which updates the `CACHE_HITRATES` application state in the local gossiper state. Each time the job is scheduled, it runs on the next shard (it goes through shards in a round-robin fashion). The job uses the `versioned_value::cache_hitrates` shorthand to create a `versioned_value`, therefore risking a data race if it is not currently executing on shard 0.
The PR fixes …
=> misc_services: fix data race from bad usage of get_next_version

sstables/index_reader.hh, sstables/sstables.cc, test/rest_api/test_column_family.py
If index_reader isn't closed before it is destroyed, then ongoing
sstables reads won't be awaited and assertion will be triggered.
Close index_reader in has_partition_key before destroying it.
Fixes: https://github.com/scylladb/scylladb/issues/17232.
=> [Backport 5.4] sstables: close index_reader in has_partition_key

sstables/index_reader.hh, sstables/sstables.cc, test/rest_api/test_column_family.py
If index_reader isn't closed before it is destroyed, then ongoing
sstables reads won't be awaited and assertion will be triggered.
Close index_reader in has_partition_key before destroying it.
Fixes: https://github.com/scylladb/scylladb/issues/17232.
=> [Backport 5.2] sstables: close index_reader in has_partition_key

db/config.cc, db/config.hh, multishard_mutation_query.cc, query-request.hh, replica/database.cc, replica/database.hh, replica/mutation_dump.cc, service/storage_proxy.cc, test/boost/database_test.cc, test/topology_custom/test_read_repair.py
This test needed a lot of data to ensure multiple pages when doing the read repair. This change two key configuration items, allowing for a drastic reduction of the data size and consequently a large reduction in run-time.
* Changes query-tombstone-page-limit 1000 -> 10. Before https://github.com/scylladb/scylladb/commit/f068d1a6fac3bfde2dc9782e7693382cda880a47,  reducing this to a too small value would start killing internal queries. Now, after said commit, this is no longer a concern, as this limit no longer affects unpaged queries.
* Sets (the new) query-page-size-in-bytes 1MB (default) -> 1KB.
The latter configuration is a new one, added by the first patches of this series. It allows configuring the page-size in bytes, after which pages are cut. Previously this was a hard-coded …
=>  test/topology_custom: test_read_repair.py: reduce run-time 

test.py, test/pylib/scylla_cluster.py, test/topology_experimental_raft/test_topology_ops.py
We decrease the server's request timeouts in topology tests so that
they are lower than the driver's timeout. Before, the driver could
time out its request before the server handled it successfully.
This problem caused scylladb/scylladb#15924.
Since scylladb/scylladb#15924 is the last issue mentioned in
scylladb/scylladb#15962, this PR also reenables background
writes in `test_topology_ops` with tablets disabled. The test
doesn't pass with tablets and background writes because of
scylladb/scylladb#17025. We will reenable background writes
with tablets after fixing that issue.
Fixes scylladb/scylladb#15924
Fixes scylladb/scylladb#15962
=> test: test_topology_ops: fix flakiness and reenable bg writes

CMakeLists.txt, cmake/mode.Coverage.cmake, cmake/mode.Debug.cmake, cmake/mode.Dev.cmake, cmake/mode.RelWithDebInfo.cmake, cmake/mode.Sanitize.cmake, rust/CMakeLists.txt
before this change, we used the lower-case CMake build configuration
name for the rust profile names. but this was wrong, because the
profiles are named with the scylla build mode.
in this change, we translate the `$<CONFIG>` to scylla build mode,
and use it for the profile name and for the output directory of
the built library.
=> build: cmake: use scylla build mode for rust profile name 

.github/mergify.yml, .github/scripts/label_promoted_commits.py, .github/workflows/add-label-when-promoted.yaml, .github/workflows/pr-require-backport-label.yaml
This PR includes 3 commits:
- **[actions] Add a check for backport labels**: As part of the Automation of ScyllaDB backports project, each PR should get either a `backport/none` or `backport/X.Y` label. Based on this label we will automatically open a backport PR for the relevant OSS release.
In this commit, I am adding a GitHub action to verify if such a label was added. This only applies to PR with a based branch of `master` or `next`. For releases, we don't need this check
- **Add Mergify (https://mergify.com/) configuration file**: In this PR we introduce the `.mergify.yml` configuration file, which
include a set of rules that we will use for automating our backport
process.
For each supported OSS release (currently 5.2 and 5.4) we have an almost
identical configuration section which …
=> Automation of ScyllaDB backports - Phase #1: Master → OSS backports

replica/compaction_group.hh, replica/database.hh, replica/table.cc, replica/tablets.cc, scylla-gdb.py, service/storage_service.cc
Make a specialized sstable_set for tablets
via tablet_storage_group_manager::make_sstable_set.
This sstable set takes a snapshot of the storage_groups
(compound) sstable_sets and maps the selected tokens
directly into the tablet compound_sstable_set.
This sstable_set provides much more efficient access
to the table's sstable sets as it takes advantage of the disjointness
of sstable sets between tablets/storage_groups, and making it is cheaper
that rebuilding a complete partitioned_sstable_set from all sstables in the table.
Fixes #16876
Cassandra-stress setup:
```
$ sudo cpupower frequency-set -g userspace
$ build/release/scylla (developer-mode options) --smp=16 --memory=8G --experimental-features=consistent-topology-changes --experimental-features=tablets
cqlsh> CREATE KEYSPACE keyspace1 …
```
=> Add specialized tablet_sstable_set

.github/workflows/docs-pages.yaml
Currently, the github docs-pages workflow is triggered only when changes are merged to the master/enterprise branches, which means that in the case of changes to a release branch, for example, a fix to branch-5.4, or a branch-5.4>branch-2024.1 merge, the docs-pages is not triggering and therefore the documentation is not updated with the new change,
In this change, I added the `branch-**` pattern, so changes to release branches will trigger the workflow
=> docs: trigger the docs-pages workflow on release branches

scylla-gdb.py
this changeset addresses some warnings raised by flake8 in hope to improve the readability of this script in general.
=> scylla-gdb.py: fixes warnings raised by flake8

replica/tablets.cc, replica/tablets.hh, service/storage_service.cc, service/topology_coordinator.cc, test/topology_custom/test_tablets_migration.py
There are 4 barrier-only stages when migrating a tablet and the test needs to fail pending/leaving replica that handles it in order to validate how coordinator handles dead node. Failing the barrier is done by suspending it with injection code and stopping the node without waking it up. The main difficulty here is how to tell one barrier RPC call from another, because they don't have anything onboard that could tell which stage the barrier is run for. This PR suggests that barrier injection code looks directly into the system.tablets table for the transition stage, the stage is already there by the time barrier is about to ack itself over RPC.
refs: #16527
=> Handle tablet migration failure in barrier stages

test/nodetool/test_snapshot.py, tools/scylla-nodetool.cc
The following incompatibilities were identified by `listsnapshots_test.py` in dtests:
* Command doesn't bail out when there are no snapshots, instead it prints meaningless empty report
* Formatting is incompatible
Both are fixed in this mini-series.
=> tools/scylla-nodetool: listsnapshot: make it compatible with origin

test.py
Today's test.py allows filtering tests to run with the `test.py --options name` syntax. The "name" argument is then considered to be some prefix, and when iterating tests only those whose name starts with that prefix are collected and executed. This has two troubles.
Minor: since it is prefix filtering, running e.g. topology_custom/test_tablets will run test_tablets _and_ test_tablets_migration from it. There's no way to exclude the latter from this selection. It's not common, but careful file names selection is welcome for better ~~user~~ testing experience.
Major: most of test files in topology and python suites contain many cases, some are extremely long. When the intent is to run a single, potentially fast, test case one needs to either wait or patch the test .py file by hand to …
=> Make it possible to run individual pytest cases with test.py

test/perf/perf_simple_query.cc
While measuring #17149 with this test some changes were applied, here they are
- keep initial_tablets number in output json's parameters section
- disable auto compaction
- add control over the amount of sstables generated for --bypass-cache case
=> Enhance perf-simple-query test

test/nodetool/test_ring.py, tools/scylla-nodetool.cc
before this change, "ring" subcommand has two issues:
1. `--resolve-ip` option accepts a boolean argument, but this option
should be a switch, which does not accept any argument at all
2. it always prints the endpoint no matter if `--resolve-ip` is
specified or not. but it should print the resolved name, instead
of an IP address if `--resolve-ip` is specified.
in this change, both issues are addressed. and the test is updated
accordingly to exercise the case where `--resolve-ip` is used.
=> tools/scylla-nodetool: print hostname if --resolve-ip is passed to "ring"

gms/endpoint_state.cc, gms/endpoint_state.hh, gms/gossiper.cc
The short series allows do_status_check to handle down nodes that don't have HOST_ID application state.
Fixes #16936
=> gossiper: do_status_check: allow evicting dead nodes from membership with no host_id

api/api-doc/storage_service.json, api/storage_service.cc, locator/abstract_replication_strategy.hh, locator/tablets.cc, locator/tablets.hh, service/storage_service.cc, service/storage_service.hh, test/pylib/rest_client.py, test/rest_api/test_storage_service.py, test/topology_experimental_raft/test_tablets.py
Before this change, when user tried to utilize
'storage_service/ownership/{keyspace}' API with
keyspace parameter that uses tablets, then internal
error was thrown. The code was calling a function,
that is intended for vnodes: get_vnode_effective_replication_map().
This commit introduces graceful handling of such scenario and
extends the API to allow passing 'cf' parameter that denotes
table name.
Now, when keyspace uses tablets and cf parameter is not passed
a descriptive error message is returned via BAD_REQUEST.
Users cannot query ownership for keyspace that uses tablets,
but they can query ownership for a table in a given keyspace that uses tablets.
Also, new tests have been added to test/rest_api/test_storage_service.py and
to test/topology_experimental_raft/test_tablets.py in order …
=> storage_service/ownership: handle requests when tablets are enabled

service/storage_service.cc, test/topology_custom/test_tablets_migration.py
There are four stages left to handle: cleanup, cleanup_target, end_migration and revert_migration. All are handling removed nodes already, so the PR just extends the test.
fixes: #16527
=> Handle tablet migration failure in wrapping-up stages

test/boost/flat_mutation_reader_test.cc, test/boost/network_topology_strategy_test.cc, test/lib/test_utils.cc, test/lib/test_utils.hh, utils/exception_container.hh, utils/human_readable.cc, utils/human_readable.hh, utils/to_string.cc, utils/to_string.hh
before this change, we rely on the default-generated fmt::formatter created
from operator<<, but fmt v10 dropped the default-generated formatter.
in this change, we define formatters for 
* utils::human_readable_value
* std::strong_ordering
* std::weak_ordering
* std::partial_ordering
* utils::exception_container
=> utils: add fmt::formatter for utils types

docs/dev/testing.md, test.py
This PR fixes comments left from #17481 , namely
- adds case selection to boost suite
- describes the case selection in documentation
=> Extend test.py's ability to select test cases

service/storage_service.cc, service/storage_service.hh, test/topology_custom/test_remove_rpc_client_with_pending_requests.py
It's too late to call `remove_rpc_client_with_ignored_topology` on messaging service when a node becomes normal. Data plane requests can be routed to the node much earlier, at least when topology switches to `write_both_read_new`. The `remove_rpc_client_with_ignored_topology` function shutdowns sockets and causes such requests to timeout.
In this PR we move the `remove_rpc_client_with_ignored_topology` call to the earliest point possible when a node first appears in `token_metadata.topology`.
From the topology coordinator perspective this happens when a joining node moves to `node_state::bootstrapping` and the topology moves to `transition_state::join_group0`. In `sync_raft_topology_nodes` the node should be contained in transition_nodes. The successful `wait_for_ip` before entering …
=> remove_rpc_client_with_ignored_topology: recreate rpc client earlier

test/nodetool/conftest.py, test/nodetool/rest_api_mock.py, test/nodetool/test_repair.py, test/nodetool/test_status.py, tools/scylla-nodetool.cc
The status command has an extensive amount of requests to the server. To be able to handle this more easily, the rest api mock server is refactored extensively to be more flexible, accepting expected requests out-of-order. While at it, the rest api mock server also moves away from a deprecated `aiohttp` feature: providing custom router argument to the `aiohttp` app. This forces us to pre-register all API endpoints that any test currently uses, although due to some templateing support, this is not as bad as it sounds. Still, this is an annoyance, but this point we have implemented almost all commands, so this won't be much a of a problem going forward.
=> tools/scylla-nodetool: implement the status command

service/migration_manager.cc, service/raft/raft_group0_client.cc
This is a backport of 0c376043ebe0d72364ed45763b0717aa4bd1955e and follow-up fix 57b14580f0985e27e3700f9a4256bf9f663ef1c1 to 5.4.
We haven't identified any specific issues in test or field in 5.4/2024.1 releases, but the bug should be fixed either way, it might bite us in unexpected ways.
For 5.4 it's even more important than 5.2 because in 5.4 in Raft mode schema pulls are disabled.
=> [Backport 5.4] migration_manager: take group0 lock during raft snapshot taking

service/migration_manager.cc, service/raft/raft_group0_client.cc, service/raft/raft_group0_client.hh
This is a backport of 0c376043ebe0d72364ed45763b0717aa4bd1955e and follow-up fix 57b14580f0985e27e3700f9a4256bf9f663ef1c1 to 5.2.
We haven't identified any specific issues in test or field in 5.2/2023.1 releases, but the bug should be fixed either way, it might bite us in unexpected ways.
=> [Backport 5.2] migration_manager: take group0 lock during raft snapshot taking

db/schema_tables.cc, service/migration_manager.cc, service/tablet_allocator.cc, test/cql-pytest/test_tablets.py, test/cql-pytest/util.py
This series adds notification before dropping views and indices so that the
tablet_allocator can generate mutations to respectively drop all tablets associated with them from system.tablets.
Additional unit tests were added for these cases.
Note that one case is not yet tested: where a table is allowed to be dropped while having views that depend on it, when it is dropped from the alternator path.
This is tested indirectly by testing dropping a table with live secondary index as it follows the same notification path as views in this series.
Fixes #17627
=> Drop tablets of dropped views and indices

db/schema_tables.cc, mutation/frozen_mutation.cc, mutation/frozen_mutation.hh
With large schemas, unfreezing can stall, especially as it requires
a lot of memory. Switch to a gentle version that will not stall.
As a preparation step, we add unfreeze_gently() for a span of mutations.
Fixes #17841
=> schema_tables: unfreeze frozen_mutation:s gently

api/api-doc/raft.json, api/raft.cc, db/system_keyspace.cc, db/system_keyspace.hh, db/view/view.cc, docs/dev/topology-over-raft.md, locator/abstract_replication_strategy.cc, locator/abstract_replication_strategy.hh, locator/tablets.cc, locator/tablets.hh, locator/topology.cc, replica/tablets.cc, replica/tablets.hh, service/storage_service.cc, service/storage_service.hh, service/tablet_allocator.cc, service/topology_coordinator.cc, service/topology_state_machine.cc, service/topology_state_machine.hh, test/boost/locator_topology_test.cc, test/boost/tablets_test.cc, test/perf/perf_tablets.cc, test/pylib/rest_client.py, test/topology/util.py, test/topology_experimental_raft/test_mv_tablets_replace.py, test/topology_experimental_raft/test_tablets_removenode.py
This PR fixes a problem with replacing a node with tablets when
RF=N. Currently, this will fail because tablet replica allocation for 
rebuild will not be able to find a viable destination, as the replacing node
is not considered to be a candidate. It cannot be a candidate because
replace rolls back on failure and we cannot roll back after tablets
were migrated.
The solution taken here is to not drain tablet replicas from replaced
node during topology request but leave it to happen later after the
replaced node is in left state and replacing node is in normal state.
The replacing node waits for this draining to be complete on boot
before the node is considered booted.
Fixes https://github.com/scylladb/scylladb/issues/17025
Nodes in the left state will be kept in tablet replica sets for a …
=> Fix node replace with tablets for RF=N

cmake/build_submodule.cmake, dist/CMakeLists.txt
this change is a follow up of ca7f7bf8e2, which changed the output path to build/$<CONFIG>/debian. but what dist/docker/debian/build_docker.sh expects is `build/dist/$config/debian/*.deb`, where `$config` is the normalized mode, when the debian packages are built using CMake generated rules, `$mode` is CMake configuration name, i.e., `$<CONFIG>`. so, ca7f7bf8e2 made a mistake, as it does not match the expectation of `build_docker.sh`.
in this change, this issue is addressed. so we use the same path in both `dist/CMakeLists.txt` and `dist/docker/debian/build_docker.sh`.
=> build: cmake: put server deb packages under build/dist/$<CONFIG>/debian

cdc/generation.cc, cdc/generation.hh, service/storage_service.cc, service/storage_service.hh
There is no need to map this node's inet_address to host_id. The storage_service can easily just pass the local host_id. While at it, get the other node's host_id directly from their endpoint_state instead of looking it up yet again in the gossiper, using the nodes' address.
Refs #12283
=> cdc: should_propose_first_generation: get my_host_id from caller

db/virtual_tables.cc, service/storage_service.cc, test/cql-pytest/test_describe.py, test/cql-pytest/test_virtual_tables.py
The token ring table is a virtual table (`system.token_ring`), which contains the ring information for all keyspaces in the system. This is essentially an alternative to `nodetool describering`, but since it is a virtual table, it allows for all the usual filtering/aggregation/etc. that CQL supports.
Up until now, this table only supported keyspaces which use vnodes. This PR adds support for tablet keyspaces. To accommodate these keyspaces a new `table_name` column is added, which is set to `ALL` for vnodes keyspaces. For tablet keyspaces, this contains the name of the table.
Simple sanity tests are added for this virtual table (it had none).
Fixes: #16850
=> db/virtual_tables: make token_ring_table tablet aware

raft/raft.hh, test/raft/generator.hh, test/raft/randomized_nemesis_test.cc
before this change, we rely on the default-generated fmt::formatter created from operator<<, but fmt v10 dropped the default-generated formatter.
* raft_call
* raft_read
* network_majority_grudge
* reconfiguration
* stop_crash
* operation::thread_id
* append_seq
* AppendReg::append
* AppendReg::ret
* operation::either_of<Ops...>
* operation::exceptional_result<Op>
* operation::completion<Op>
* operation::invocable<Op>
and drop their operator<<:s.
in which,
* `operator<<` for append_entry is never used. so it is removed.
* `operator<<` for `std::monostate` and `std::variant` are dropped. as we are now using their counterparts in {fmt}.
* stop_crash::result_type 's `fmt::formatter` is not added, as we cannot define a partial specialization of …
=> test: randomized_nemesis_test: add fmt::formatter for some types

test/nodetool/test_nodetool.py, tools/scylla-nodetool.cc, tools/utils.cc, tools/utils.hh
There was two more things missing:
* Allow global options to be positioned before the operation/command option (https://github.com/scylladb/scylladb/issues/16695)
* Ignore JVM args (https://github.com/scylladb/scylladb/issues/16696)
This PR fixes both. With this, hopefully we are fully compatible with nodetool as far as command line parsing is concerned.
After this PR goes in, we will need another fix to tools/java/bin/nodetool-wrapper, to allow user to benefit from this fix. Namely, after this PR, we can just try to invoke scylla-nodetool first with all the command-line args as-is. If it returns with exit-code 100, we fall back to nodetool. We will not need the current trick with `--help $1`. In fact, this trick doesn't work currently, because `$1` is not guaranteed to be the command in …
=> scylla-nodetool: make command-line parsing fully compatible with the legacy nodetool

mutation/mutation.cc, mutation/mutation.hh, service/storage_service.cc, test/boost/mutation_test.cc, test/topology_experimental_raft/test_cdc_generation_data.py
The group0 state machine calls `merge_topology_snapshot` from `transfer_snapshot`. It feeds it with `raft_topology_snapshot` returned from `raft_pull_topology_snapshot`. This snapshot includes the entire `system.cdc_generations_v3` table. It can be huge and break the commitlog `max_record_size` limit.
The `system.cdc_generations_v3` is a single-partition table, so all the data is contained in one mutation object. To fit the commitlog limit we split this mutation into many smaller ones and apply them in separate `database::apply` calls. That means we give up the atomicity guarantee, but we actually don't need it for `system.cdc_generations_v3` and `system.topology_requests`.
This PR fixes the dtest `update_cluster_layout_tests.py::TestLargeScaleCluster::test_add_many_nodes_under_load` …
=> storage_service::merge_topology_snapshot: handle big mutations

cdc/generation.hh, data_dictionary/data_dictionary.hh, exceptions/exceptions.hh, sstables/exceptions.hh, utils/exception_container.hh
before this change, we rely on the default-generated fmt::formatter created from operator<<, but fmt v10 dropped the default-generated
formatter.
in this change, `fmt::formatter` is added for following types for backward compatibility with {fmt} < 10:
* `utils::bad_exception_container_access`
* `cdc::no_generation_data_exception`
* classes derived from `sstables::malformed_sstable_exception`
* classes derived from `cassandra_exception`
=> treewide: add fmt::formatter for exception types

service/topology_coordinator.cc, test/boost/error_injection_test.cc, test/topology_experimental_raft/test_cdc_generation_clearing.py, test/topology_experimental_raft/test_cdc_generation_publishing.py, utils/error_injection.hh
In this PR, we ensure unpublished CDC generation's data is
never removed, which was theoretically possible. If it happened,
it could cause problems. CDC generation publisher would then try
to publish the generation with its data removed. In particular, the
precondition of calling `_sys_ks.read_cdc_generation` wouldn't be
satisfied.
We also add a test that passes only after the fix. However, this test
needs to block execution of the CDC generation publisher's loop
twice. Currently, error injections with handlers do not allow it
because handlers always share received messages. Apart from the
first created handler, all handlers would be instantly unblocked by
a message from the past that has already unblocked the first
handler. This seems like a general limitation that could cause
problems …
=> topology_coordinator: do not clear unpublished CDC generation's data

test/lib/sstable_test_env.hh, test/lib/sstable_utils.cc, test/lib/test_services.cc
Reduce the sprawl of sstables::test_env in .cc and .hh files, to ease
maintenance and reduce recompilations.
=> test/lib: sstable::test_env consolidate and reduce header footprint

api/api.cc, auth/common.cc, auth/common.hh, auth/default_authorizer.cc, auth/password_authenticator.cc, auth/service.cc, auth/standard_role_manager.cc, db/config.cc, db/config.hh, main.cc, service/migration_manager.cc, service/raft/raft_group0.cc, service/raft/raft_group0.hh, service/raft/raft_group0_client.cc, service/raft/raft_group0_client.hh, service/raft/raft_group_registry.cc, service/raft/raft_group_registry.hh, service/storage_service.cc, service/storage_service.hh, service/topology_coordinator.cc, test/pylib/manager_client.py, test/pylib/scylla_cluster.py, test/topology/conftest.py, test/topology_custom/test_raft_no_quorum.py, utils/composite_abort_source.hh, utils/error_injection.hh
In this PR we add timeouts support to raft groups registry. We introduce the `raft_server_with_timeouts` class, which wraps the `raft::server` add exposes its interface with additional `raft_timeout` parameter. If it's set, the wrapper cancels the `abort_source` after certain amount of time. The value of the timeout can be specified either in the `raft_timeout` parameter, or the default value can be set in `the raft_server_with_timeouts` class constructor.
The `raft_group_registry` interface is extended with `group0_with_timeouts()` method. It returns an instance of `raft_server_with_timeouts` for group0 raft server. The timeout value for it is configured in `create_server_for_group0`. It's one minute by default and can be overridden for tests with `group0-raft-op-timeout-in-ms` …
=> raft timeouts: better handling of lost quorum

test/nodetool/conftest.py, test/nodetool/rest_api_mock.py, test/nodetool/test_nodetool.py, test/nodetool/test_sstable.py, tools/scylla-nodetool.cc
These commands manage to avoid detection because they are not documented on https://opensource.docs.scylladb.com/stable/operating-scylla/nodetool.html.
They were discovered when running dtests, with ccm tuned to use the native nodetool directly. See https://github.com/scylladb/scylla-ccm/pull/565.
The commands come with tests, which pass with both the native and Java nodetools. I also checked that the relevant dtests pass with the native implementation.
=> tools/scylla-nodetool: implement the getsstables and sstableinfo commands

cql3/statements/select_statement.cc, test/cql-pytest/test_select_from_mutation_fragments.py
Memtables are fickle, they can be flushed when there is memory pressure, if there is too much commitlog or if there is too much data in them. The tests in test_select_from_mutation_fragments.py currently assume data written is in the memtable. This is tru most of the time but we have seen some odd test failures that couldn't be understood.
To make the tests more robust, flush the data to the disk and read it from the sstables. This means that some range scans need to filter to read from just a single mutation source, but this does not influence the tests.
Also fix a use-after-return found when modifying the tests.
This PR tentatively fixes the below issues, based on our best guesses on why they failed (each was seen just once):
Fixes: #16795
Fixes: #17031
=>  test/cql-pytest: test_select_from_mutation_fragments.py: move away from memtables

compaction/compaction_strategy.cc, compaction/compaction_strategy.hh, compaction/compaction_strategy_impl.hh, docs/cql/compaction.rst, docs/troubleshooting/pointless-compactions.rst, test/boost/sstable_compaction_test.cc, test/cql-pytest/test_compaction_strategy_validation.py
This change adds the missing Cassandra compaction option unchecked_tombstone_compaction.
Setting this option to true causes the compaction to ignore tombstone_threshold, and decide whether to do a compaction only based on the value of tombstone_compaction_interval
Fixes #1487
=> compaction: implement unchecked_tombstone_compaction

alternator/executor.cc, cql3/result_set.hh, test/alternator/test_query.py
Before this series, Alternator's Query and Scan operations convert an
entire result page to JSON without yielding. For a page of maximum
size (1MB) and tiny rows, this can cause a significant stall - the
test included in this PR reported stalls of 14-26ms on my laptop.
The problem is the describe_items() function, which does this conversion
immediately, without yielding. This patch changes this function to
return a future, and use a new result_set::visit_gently() method
that does what visit() does, but with yields when needed.
This PR improves #17995, but does not completely fix is as the stalls in the
are not completely eliminated. But on my laptop it usually reduces the stalls
to around 5ms. It appears that the remaining stalls some from other places
not fixed in this PR, such as …
=> alternator: reduce stall for Query and Scan with large pages

gms/feature.hh, service/storage_service.cc
The storage_service::track_upgrade_progress_to_topology_coordinator
function is supposed to wait on the SUPPORTS_CONSISTENT_TOPOLOGY_CHANGES
cluster feature (among other things) before starting the
raft_state_monitor_fiber. The wait is realized by passing a callback to
feature::when_enabled which sets a shared_promise that is waited on by
the tracking fiber. If the feature is already enabled, when_enabled will
call the callback immediately. However, if it's not, then it will return
a non-null listener_registration object - as long as it is alive, the
callback is registered. The listener_registration object was not
assigned to a variable which caused it to be destroyed shortly after the
when_enabled function returns.
Due to that, if upgrade was requested but the current group0 leader …
=> storage_service: keep subscription to raft topology feature alive

locator/load_sketch.hh, locator/network_topology_strategy.cc, locator/network_topology_strategy.hh, locator/tablet_replication_strategy.hh, locator/topology.hh, test/boost/network_topology_strategy_test.cc
This series provides a reallocate_tablets function, that's initially called by allocate_tablets_for_new_table.
The new allocation implementation is independent of vnodes/token ownership.
Rather than using the natural_endpoints_tracker, it implements its own tracking
based on dc/rack load (== number of replicas in rack), with the additional benefit
that tablet allocation will balance the allocation across racks, using a heap structure,
similar to the one we use to balance tablet allocation across shards in each node.
reallocate_tablets may also be called with an optional parameter pointing the the current tablet_map.
In this case the function either allocates more tablet replicas in datacenters for which the replication factor was increased,
or it will deallocate tablet replicas from …
=> network_topology_strategy: reallocate_tablets: support for rf changes

test/boost/database_test.cc, test/lib/cql_assertions.cc, test/unit/radix_tree_stress_test.cc
this series includes test related changes to enable us to drop `FMT_DEPRECATED_OSTREAM` deprecated in {fmt} v10.
Refs #13245
=> test: changes to prepare for dropping FMT_DEPRECATED_OSTREAM

main.cc, service/qos/service_level_controller.cc, service/qos/service_level_controller.hh
Setting data accessor implicitly depends on node joining the cluster
with raft leader elected as only then service level mutation is put
into scylla_local table. Calling it after join_cluster avoids starting
new cluster with older version only to immediately migrate it to the
latest one in the background.
=> main: reload service levels data accessor after join_cluster

test/topology/util.py, test/topology_experimental_raft/test_topology_upgrade.py
Test.py uses `ring_delay_ms = 0` by default. CDC creates generation's timestamp by adding `ring_delay_ms` to it.
In this test, nodes are learning about new generations (introduced by upgrade procedure and then by node bootstrap) concurrently with doing writes that should go to these generations.
Because of `ring_delay_ms = 0', the generation could have been committed when it should have already been in use.
This can be seen in the following logs from a node:
```
ERROR 2024-03-22 12:29:55,431 [shard 0:strm] cdc - just learned about a CDC generation newer than the one used the last time streams were retrieved. This generation, or some newer one, should have been used instead (new generation's timestamp: 2024/03/22 12:29:54, last time streams were retrieved: 2024/03/22 12:29:55). The new …
```
=> test.py: test_topology_upgrade_basic: make ring_delay_ms nonzero

test/cql-pytest/test_compaction_strategy_validation.py
currently, our homebrew formatter formats `std::map` like
```
{{k1, v1}, {k2, v2}}
```
while {fmt} formats a map like:
```
{k1: v1, k2: v2}
```
and if the type of key/value is string, {fmt} quotes it, so a
compaction strategy option is formatted like
```
{"max_threshold": "1"}
```
before switching the formatter to the ones supported by {fmt},
let's update the test to match with the new format. this should
reduce the overhead of reviewing the change of switching the
formatter. we can revert this change, and use a simpler approach
after the change of formatter lands.
=> test/cql-pytest: match error message formated using {fmt} 

db/config.cc, db/config.hh, sstables/sstables.cc, sstables/sstables.hh, sstables/sstables_manager.cc, sstables/sstables_manager.hh, test/boost/sstable_datafile_test.cc, test/cql-pytest/test_bloom_filter.py, test/lib/sstable_test_env.hh, test/lib/sstable_utils.hh, test/lib/test_services.cc
Added support to track and limit the memory usage by sstable components. A reclaimable component of an SSTable is one from which memory can be reclaimed. SSTables and their managers now track such reclaimable memory and limit the component memory usage accordingly. A new configuration variable defines the memory reclaim threshold. If the total memory of the reclaimable components exceeds this limit, memory will be reclaimed to keep the usage under the limit. This PR considers only the bloom filters as reclaimable and adds support to track and limit them as required.
The feature can be manually verified by doing the following :
1. run a single-node single-shard 1GB cluster
2. create a table with bloom-filter-false-positive-chance of 0.001 (to intentionally cause large bloom filter)
3. …
=> Track and limit memory used by bloom filters

repair/row_level.cc, repair/row_level.hh
Currently, we load the repair history during boot up. If the number of
repair history entries is high, it might take a while to load them.
In my test, to load 10M entries, it took around 60 seconds.
It is not a must to load the entries during boot up. It is better to
load them in the background to speed up the boot time.
Fixes #17993
=> repair: Load repair history in background

auth/common.cc, auth/service.cc, auth/service.hh, cql3/query_processor.hh, db/system_keyspace.cc, db/system_keyspace.hh, main.cc, service/storage_service.cc, service/topology_coordinator.cc, test/auth_cluster/test_auth_v2_migration.py, test/lib/cql_test_env.cc
Before the patch selection of auth version depended
on consistent topology feature but during raft recovery
procedure this feature is disabled so we need to persist
the version somewhere to not switch back to v1 as this
is not supported.
During recovery auth works in read-only mode, writes
will fail.
Fixes https://github.com/scylladb/scylladb/issues/17736
=> auth: keep auth version in scylla_local

repair/row.hh, repair/row_level.cc, test/boost/repair_test.cc
Repair memory limit includes only the size of frozen mutation
fragments in repair row. The size of other members of repair 
row may grow uncontrollably and cause out of memory.
Modify what's counted to repair memory limit.
Fixes: #16710.
=> repair: fix memory counting in repair

api/api-doc/storage_service.json, api/storage_service.cc, locator/tablets.cc, locator/tablets.hh, replica/tablets.cc, service/storage_service.cc, service/storage_service.hh, service/topology_coordinator.cc, test/pylib/rest_client.py, test/topology_custom/test_tablets_migration.py
When altering rf for a keyspace, all tablets in this ks may have less replicas. Part of this process is removing replicas from some node(s). This PR extends the tablets rebuild transition to handle this case by making pending_replica optional.
fixes: #18176
=> Extend tablet_transition_kind::rebuild to remove replicas

gms/gossiper.cc, test/topology_custom/test_gossip_boot.py
In testing, we've observed multiple cases where nodes would fail to
observe updated application states of other nodes in gossiper.
For example:
- in scylladb/scylladb#16902, a node would finish bootstrapping and enter
NORMAL state, propagating this information through gossiper. However,
other nodes would never observe that the node entered NORMAL state,
still thinking that it is in joining state. This would lead to further
bad consequences down the line.
- in scylladb/scylladb#15393, a node got stuck in bootstrap, waiting for
schema versions to converge. Convergence would never be achieved and the
test eventually timed out. The node was observing outdated schema state
of some existing node in gossip.
I created a test that would bootstrap 3 nodes, then wait until they all
observe each …
=> gossiper: lock local endpoint when updating heart_beat

repair/row.hh, repair/row_level.cc, test/boost/repair_test.cc
Repair memory limit includes only the size of frozen mutation
fragments in repair row. The size of other members of repair
row may grow uncontrollably and cause out of memory.
Modify what's counted to repair memory limit.
Fixes: https://github.com/scylladb/scylladb/issues/16710.
(cherry picked from commit https://github.com/scylladb/scylladb/commit/a4dc6553ab8f1a30a7eab88a5b4170a1201aa22a)
(cherry picked from commit https://github.com/scylladb/scylladb/commit/51c09a84cc421681f3f9f17c5b69e1976d7f5f8e)
Refs https://github.com/scylladb/scylladb/pull/17785
=> [Backport 5.2] repair: fix memory counting in repair

db/view/view.cc, db/view/view_builder.hh, main.cc, service/storage_service.cc, service/storage_service.hh, test/lib/cql_test_env.cc
For view builder draining there's dedicated deferred action in main while all other services that need to be drained do it via storage_service. The latter is to unify shutdown for services and to make `nodetool drain` drain everything, not just some part of those. This PR makes view builder drain look the same. As a side effect it also moves `mark_existing_views_as_built` from storage service to view builder and generalizes this marking code inside view builder itself.
refs: #2737
refs: #2795
=> Drain view_builder in generic drain

db/config.cc, db/config.hh, sstables/sstables.cc, sstables/sstables.hh, sstables/sstables_manager.cc, sstables/sstables_manager.hh, test/boost/sstable_datafile_test.cc, test/cql-pytest/test_bloom_filter.py, test/lib/sstable_test_env.hh, test/lib/sstable_utils.hh, test/lib/test_services.cc
Added support to track and limit the memory usage by sstable components. A reclaimable component of an SSTable is one from which memory can be reclaimed. SSTables and their managers now track such reclaimable memory and limit the component memory usage accordingly. A new configuration variable defines the memory reclaim threshold. If the total memory of the reclaimable components exceeds this limit, memory will be reclaimed to keep the usage under the limit. This PR considers only the bloom filters as reclaimable and adds support to track and limit them as required.
The feature can be manually verified by doing the following :
1. run a single-node single-shard 1GB cluster
2. create a table with bloom-filter-false-positive-chance of 0.001 (to intentionally cause large bloom filter)
3. …
=> [Backport 5.4] : Track and limit memory used by bloom filters

db/config.cc, db/config.hh, sstables/sstables.cc, sstables/sstables.hh, sstables/sstables_manager.cc, sstables/sstables_manager.hh, test/boost/sstable_datafile_test.cc, test/cql-pytest/test_bloom_filter.py, test/lib/sstable_test_env.hh, test/lib/sstable_utils.hh, test/lib/test_services.cc
Added support to track and limit the memory usage by sstable components. A reclaimable component of an SSTable is one from which memory can be reclaimed. SSTables and their managers now track such reclaimable memory and limit the component memory usage accordingly. A new configuration variable defines the memory reclaim threshold. If the total memory of the reclaimable components exceeds this limit, memory will be reclaimed to keep the usage under the limit. This PR considers only the bloom filters as reclaimable and adds support to track and limit them as required.
The feature can be manually verified by doing the following :
1. run a single-node single-shard 1GB cluster
2. create a table with bloom-filter-false-positive-chance of 0.001 (to intentionally cause large bloom filter)
3. …
=> [Backport 5.2] : Track and limit memory used by bloom filters

tools/scylla-nodetool.cc
Just like all the other commands already have it. These commands didn't have documentation at the point where they were implemented, hence the missing doc link.
The links don't work yet, but they will work once we release 6.0 and the current master documentation is promoted to stable.
=> tools/scylla-nodetool: add doc link for getsstables and sstableinfo commands

.gitignore, configure.py, install-dependencies.sh, tools/toolchain/Dockerfile, tools/toolchain/README.md, tools/toolchain/optimized_clang.sh, tools/toolchain/prepare
This is complete version of #12786, since I take over the issue from @mykaul.
Update from original version are:
- Support ARM64 build (disable BOLT for now since it doesn't functioning)
- Changed toolchain settings to get current scylla able to build (support WASM, etc)
- Stop git clone scylladb repo, create git-archive of current scylla directory and import it
-  Update Clang to 17.0.6
- Save entire clang directory for BUILD mode, not just /usr/bin/clang binary
- Implemented INSTALL_PREBUILT mode to install prebuilt image which built in BUILD mode
Note that this patch drops cross-build support of frozen toolchain, since building clang and scylla multiple time in qemu-user-static will very slow, it's not usable.
Instead, we should build the image for each architecture natively.
----
This …
=> toolchain: support building an optimized clang

replica/database.cc, replica/database.hh, replica/table.cc, sstables/sstable_directory.cc, sstables/sstable_directory.hh
The semaphore in question is used to limit parallelism of manipulations with table's sstables. It's currently used in two places -- sstable_directory (mainly on boot) and by table::take_snapshot() to take snapshot. For the latter, there's also a database -> sharded<directory_semaphore> reference.
This PR sanitizes the semaphore usage. The results are
- directory_semaphore no longer needs to friend several classes that mess with its internals
- database no longer references directory_semaphore
=> Sanitize sstables::directory_semaphore usage

install-dependencies.sh
in this changeset, we install `libxxhash-dev` and `cargo` for debian, and install cxxbridge for all distros, so that at least debian can be built without further preparations after running `install-dependencies.sh`.
=> install-dependencies.sh: add more dependencies for debian

api/storage_service.cc, db/snapshot-ctl.cc, db/snapshot-ctl.hh, replica/database.cc, replica/database.hh, test/boost/database_test.cc
There's a database::get_snapshot_details() method that returns collection of all snapshots for all ks.cf out there and there are several *snapshot_details* aux structures around it. This PR keeps only one "details" and cleans up the way it propagates from database up to the respective API calls.
=> Cleanup the way snapshot details are propagated via API

api/column_family.cc, api/storage_service.cc, db/snapshot-ctl.cc, db/snapshot-ctl.hh
The API endpoint in question calls table::get_snapshot_detail() which just walks table/snapshots/ directory. This can clash with creating a new snapshot. Database-wide walk is guarded with snapshot-ctl's locking, so should the per-table API do
=> Getting per-table snapshot size is racy wrt creating new snapshots

db/large_data_handler.cc, db/large_data_handler.hh, db/system_keyspace.cc, docs/dev/system_keyspace.md, docs/troubleshooting/large-partition-table.rst, sstables/metadata_collector.hh, sstables/mx/writer.cc, test/boost/sstable_3_x_test.cc
When issuing warnings about partitions with the number of rows above a configured threshold, the  large partitions handler does not take into consideration the number of range tombstone markers in the total rows count. This fix adds the number of range tombstone markers to the total number of rows and saves this total in system.large_partitions.rows (if it is above the threshold). It also adds a new column range_tombstones to the system.large_partitions table which only contains the number of range tombstone markers for the given partition.
This PR fixes the first part of issue #13968
It does not cover distinguishing between live and dead rows. A subsequent PR will handle that.
=> sstable: large data handler needs to count range tombstones as rows

cql3/statements/alter_table_statement.cc, cql3/statements/alter_view_statement.cc, cql3/statements/cf_prop_defs.cc, cql3/statements/cf_prop_defs.hh, cql3/statements/create_table_statement.cc, cql3/statements/create_view_statement.cc, data_dictionary/data_dictionary.cc, data_dictionary/data_dictionary.hh, data_dictionary/impl.hh, db/config.cc, db/config.hh, docs/cql/ddl.rst, docs/dev/topology-over-raft.md, replica/data_dictionary_impl.hh, test/lib/cql_test_env.cc, test/lib/expr_test_utils.cc, test/topology/test_mv.py, test/topology/util.py, test/topology_experimental_raft/test_tombstone_gc.py, tombstone_gc.cc, tombstone_gc.hh, tools/schema_loader.cc
Repair may miss some tablets that migrated across nodes.
So if tombstones expire after some timeout, then we can
have data resurrection.
Set default tombstone_gc mode to "repair" for tables which
use tablets (if repair is required).
Fixes: #16627.
=> cql3: statements: change default tombstone_gc mode for tablets

.github/pull_request_template.md, .github/workflows/pr-check-completed-tests.yaml
Today with the backport automation, the developer added the relevant backport label, but without any explanation of why
Adding the PR template with a placeholder for the developer to add his decision about backport yes or no
The placeholder is marked as a task, so once the explanation is added, the task must be checked as completed
Also adding another check to the PR summary will make it clear to the maintainer/reviewer if the developer explained about backport
=> [github] add PR template and action to verify PR tasks was completed

db/view/view.cc, db/view/view_update_generator.cc, db/view/view_update_generator.hh, replica/database.cc, replica/database.hh, replica/table.cc
The populate_views() and generate_and_propagate_view_updates() both naturally belong to view_update_generator -- they don't need anything special from table itself, but rather depend on some internals of the v.u.generator itself.
Moving them there lets removing the view concurrency semaphore from keyspace and table, thus reducing the cross-components dependencies.
=> Move some view updating methods from table to view_update_generator

api/storage_service.cc, repair/repair.cc
in `set_repair()`, despite that the repair is performed asynchronously,
we check the options specified by client immediately, and throw
`std::runtime_error`, if any of them is not supported.
before this change, these unhandled exceptions are translated to HTTP
500 error but the underlying HTTP router. but this is misleading, as
these errors are caused by client, not server.
in this change, we handle the `runtime_error`, and translate them
into `httpd::bad_param_exception`, so that the client can have
HTTP 400 (Bad Request) instead of HTTP 500 (Internal Server Error),
and with informative error message.
for instance, if we apply repair with "small_table_optimization" enabled
on a keyspace with tablets enabled. we should have an HTTP error 400
with "The small_table_optimization option is …
=> api/storage_service: convert runtime_error from repair to http error 

sstables/sstable_directory.cc, test/object_store/test_basic.py
On boot sstables are populated from normal location as well as from quarantine and staging. It turned out that sstables listed in registry (S3-backed ones) are not populated from non-normal states.
=> Fix population of non-normal sstables from registry

db/view/view.cc
There are two places that workaround db.column_family_exists() call with some fancy exceptions-catching lambda.
This PR makes things simpler.
=> Relax the way view builder code checks if a table exists

service/topology_coordinator.cc, test/topology_experimental_raft/test_topology_upgrade_not_stuck_after_recent_removal.py
During upgrade to raft topology, information about service levels is copied from the legacy tables in system_distributed to the raft-managed tables of group 0. system_distributed has RF=3, so if the cluster has only one or two nodes we should use lower consistency level than ALL - and the current procedure does exactly that, it selects QUORUM in case of two nodes and ONE in case of only one node. The cluster size is determined based on the call to _gossiper.num_endpoints().
Despite its name, gossiper::num_endpoints() does not necessarily return the number of nodes in the cluster but rather the number of endpoint states in gossiper (this behavior is documented in a comment near the declaration of this function). In some cases, e.g. after gossiper-based nodetool remove, the state might be …
=> topology_coordinator: compute cluster size correctly during upgrade

auth/common.cc, auth/common.hh, auth/default_authorizer.cc, auth/default_authorizer.hh, auth/password_authenticator.cc, auth/service.cc, auth/service.hh, auth/standard_role_manager.cc, auth/standard_role_manager.hh, test/auth_cluster/test_auth_v2_migration.py
We won't run:
- old pre auth-v1 migration code
- code creating auth-v1 tables
We will keep running:
- code creating default rows
- code creating auth-v1 keyspace (needed due to cqlsh legacy hack,
it errors when executing `list roles` or `list users` if
there is no system_auth keyspace, it does support case when
there is no expected tables)
Fixes https://github.com/scylladb/scylladb/issues/17737
=> auth: don't run legacy migrations in auth-v2 mode

generic_server.cc
It needs some local naming cleanup, but otherwise it's pretty simple
=> Coroutinize generic_server's listen() method

api/api.cc, api/collectd.cc, api/column_family.cc, api/compaction_manager.cc, api/config.cc, api/error_injection.cc, api/failure_detector.cc, api/gossiper.cc, api/messaging_service.cc, api/raft.cc, api/storage_service.cc, api/storage_service.hh, api/stream_manager.cc, api/system.cc, api/task_manager.cc, api/task_manager_test.cc, api/tasks.cc, api/token_metadata.cc, test/alternator/test_lsi.py
The name of the Scylla table backing an Alternator LSI looks like `basename:!lsiname`. Some REST API clients (including Scylla Manager) when they send a "!" character in the REST API request path may decide to "URL encode" it - convert it to `%21`.
Because of a Seastar bug (https://github.com/scylladb/seastar/issues/725) Scylla's REST API server forgets to do the URL decoding on the path part of the request, which leads to the REST API request failing to address the LSI table.
The first patch in this PR fixes the bug by using a new Seastar API introduced in https://github.com/scylladb/seastar/pull/2125 that does the URL decoding as appropriate. The second patch in the PR is a new test for this bug, which fails without the fix, and passes afterwards.
Fixes #5883.
=> alternator: fix REST API access to an Alternator LSI

test/auth_cluster/test_auth_v2_migration.py, test/auth_cluster/test_raft_service_levels.py, test/pylib/manager_client.py, test/pylib/scylla_cluster.py, test/topology/util.py, test/topology_custom/test_group0_schema_versioning.py, test/topology_custom/test_raft_fix_broken_snapshot.py, test/topology_custom/test_raft_recovery_basic.py, test/topology_custom/test_raft_recovery_majority_loss.py, test/topology_custom/test_raft_recovery_stuck.py, test/topology_experimental_raft/test_topology_recovery_basic.py, test/topology_experimental_raft/test_topology_recovery_majority_loss.py
Instead of performing a rolling restart by calling `restart` in a loop over every node in the cluster, use the dedicated
`manager.rolling_restart` function. This method waits until all other nodes see the currently processed node as up or down before proceeding to the next step. Not doing so may lead to surprising behavior.
In particular, in scylladb/scylladb#18369, a test failed shortly after restarting three nodes. Because nodes were restarted one after another too fast, when the third node was restarted it didn't send a notification to the second node because it still didn't know that the second node was alive. This led the second node to notice that the third node restarted by observing that it incremented its generation in gossip (it restarted too fast to be marked as down by the …
=> test: {auth,topology}: use manager.rolling_restart

db/view/view.cc, db/view/view_builder.hh, db/view/view_update_generator.cc, db/view/view_update_generator.hh, main.cc, service/storage_proxy.cc, service/storage_proxy.hh, service/storage_service.cc, service/storage_service.hh, test/lib/cql_test_env.cc
Some time ago #16558 was merged that moved view builder drain into generic drain. After this merge dtests started to fail from time to time, so the PR was reverted (see #18278). In #18295 the hang was found. View builder drain was moved from "before stopping messaging service to "after" it, and view update write handlers in proxy hanged for hard-coded timeout of 5 minutes without being aborted. Tests don't wait for 5 minutes and kill scylla, then complain about it and fail.
This PR brings back the original PR as well as the necessary fix that cancels view update write handlers on stop.
=> Drain view_builder in generic drain (again)

db/large_data_handler.cc, db/large_data_handler.hh, db/system_keyspace.cc, docs/dev/system_keyspace.md, docs/troubleshooting/large-partition-table.rst, gms/feature_service.hh, sstables/metadata_collector.hh, sstables/mx/writer.cc, test/boost/sstable_3_x_test.cc, test/lib/simple_schema.hh
This is the second half of the fix for issue #13968. The first half is already merged with PR #18346
Scylla issues warnings for partitions containing more rows than a configured threshold. The warning is issued by inserting a row into the `system.large_partitions` table. This row contains the information about the partition for which the warning is issued: keyspace, table, sstable, partition key and size, compaction time and the number of rows in the partition. A previous PR #18346 also added range tombstone count to this row.
This change adds a new counter for dead rows to the large_partitions table.
This change also adds cluster feature protection for writing into these new counters. This is needed in case a cluster is in the process of being upgraded to this new version, after which an …
=> sstables: add dead row count when issuing warning to system.large_partitions

scylla-gdb.py, sstables/sstables.cc, sstables/sstables.hh, sstables/sstables_manager.cc, sstables/sstables_manager.hh, test/boost/sstable_datafile_test.cc, test/boost/sstable_directory_test.cc, test/lib/sstable_test_env.hh, test/lib/sstable_utils.hh, utils/error_injection.hh
PR #17771 introduced a threshold for the total memory used by all bloom filters across SSTables. When the total usage surpasses the threshold, the largest bloom filter will be removed from memory, bringing the total usage back under the threshold. This PR adds support for reloading such reclaimed bloom filters back into memory when memory becomes available (i.e., within the 10% of available memory earmarked for the reclaimable components). 
The SSTables manager now maintains a list of all SSTables whose bloom filter was removed from memory and attempts to reload them when an SSTable, whose bloom filter is still in memory, gets deleted. The manager reloads from the smallest to the largest bloom filter to maximize the number of filters being reloaded into memory.
=> Reload reclaimed bloom filters when memory is available

repair/repair.cc
Currently if any shard repair task fails,
`tablet_repair_task_impl` per-shard loop
breaks, since it doesn't handle the expection.
Although repair does return an error, which
is as expected, we change vnode-based repair
to make a best effort and try to repair
as much as it can, even if any of the ranges
failed.
This causes the `test_repair_with_down_nodes_2b`
dtest to fail with tablets, as seen in, e.g.
https://jenkins.scylladb.com/view/master/job/scylla-master/job/tablets/job/gating-dtest-release-with-tablets/52/testReport/repair_additional_test/TestRepairAdditional/FullDtest___full_split002___test_repair_with_down_nodes_2b/
```
AssertionError: assert 1765 == 2000
```
Tablet repair code will be introduced in 6.0, no need to backport to earlier versions.
=> repair: tablet_repair: make best effort in spite of errors

cmake/build_submodule.cmake, dist/CMakeLists.txt
in the same spirit of d57a82c156, this change adds `dist-unified` as one of the default targets. so that it is built by default. the unified package is required to when redistributing the precompiled packages -- we publish the rpm, deb and tar balls to S3.
=> build: cmake build dist-unified by default and put tarballs under per-config paths

compaction/task_manager_module.cc, compaction/task_manager_module.hh, docs/dev/topology-over-raft.md, replica/compaction_group.hh, replica/database.hh, replica/table.cc, replica/tablets.cc, service/topology_coordinator.cc, test/boost/commitlog_cleanup_test.cc, test/boost/cql_query_large_test.cc, test/boost/sstable_3_x_test.cc, test/boost/sstable_compaction_test.cc, test/boost/sstable_test.hh, test/boost/view_complex_test.cc, test/lib/test_services.cc, test/perf/perf_fast_forward.cc, test/perf/perf_sstable.hh, test/topology_custom/test_tablets_migration.py
Allocate storage groups dynamically, i.e.:
- on table creation allocate only storage groups that are on this
shard;
- allocate a storage group for tablet that is moved to this shard;
- deallocate storage group for tablet that is moved out of this shard.
Output of `./build/release/scylla perf-simple-query -c 1 --random-seed=2248493992` before change:
```
random-seed=2248493992
enable-cache=1
Running test with config: {partitions=10000, concurrency=100, mode=read, frontend=cql, query_single_key=no, counters=no}
Disabling auto compaction
Creating 10000 partitions...
64933.90 tps ( 63.2 allocs/op,   0.0 logallocs/op,  14.2 tasks/op,   42163 insns/op,        0 errors)
65865.36 tps ( 63.1 allocs/op,   0.0 logallocs/op,  14.2 tasks/op,   42155 insns/op,        0 errors)
66649.36 tps ( 63.1 …
```
=> replica: allocate storage groups dynamically

cmake/add_version_library.cmake, configure.py, release.cc, release.hh, tools/scylla-nodetool.cc
Currently, all documentation links that feature anywhere in the help output of scylla-nodetool, are hard-coded to point to the documentation of the latest stable release. As our documentation is version and product (open-source or enterprise) specific, this is not correct. This PR addresses this, by generating documentation links such that they point to the documentation appropriate for the product and version of the scylladb release.
Fixes: https://github.com/scylladb/scylladb/issues/18276
=> scylla-nodetool: make documentation links product and version dependant

cql3/statements/describe_statement.cc, schema/schema.cc, schema/schema.hh, test/cql-pytest/test_describe.py
Currently all tables are printed in statements like `DESC TABLES`, `DESC KEYSPACE ks` or `DESC SCHEMA`.
But when we create a table with cdc enabled, additional table with `_scylla_cdc_log` suffix is created.
Those tables shouldn't be recreated manually but created automatically when the base table is created.
This patch hides tables with `_scylla_cdc_log` suffix in all describe statements.
To preserve properties values of those tables, `ALTER TABLE` statement with all properties and their current values for log cdc table is added to description of the base table.
Fixes #18459
=> cql/describe: hide cdc log tables

test/boost/chunked_vector_test.cc, utils/chunked_vector.hh
Currently, if the fill ctor throws an exception,
the destructor won't be called, as it object is not fully constructed yet.
Call the default ctor first (which doesn't throw)
to make sure the destructor will be called on exception.
Fixes scylladb/scylladb#18635
=> utils: chunked_vector: fill ctor: make exception safe

db/hints/manager.cc, db/hints/manager.hh
We don't attempt to create an endpoint manager for a hint directory if there is no mapping host ID–IP corresponding to the directory's name, an IP address. That prevents a segmentation fault.
Fixes scylladb/scylladb#18649
=> hinted handoff: Prevent segmentation fault when initializing endpoint managers 

api/api-doc/storage_service.json, api/storage_service.cc, locator/tablets.cc, locator/tablets.hh, service/storage_service.cc, service/storage_service.hh, test/nodetool/test_ring.py, test/nodetool/test_status.py, test/nodetool/test_tablehistograms.py, test/nodetool/test_toppartitions.py, tools/scylla-nodetool.cc
Currently, invoking `nodetool ring` on a tablet keyspace fails with an error, because it doesn't pass the required table parameter to `/storage_service/ownership/{keyspace}`. Further to this, the command will currently always output the vnode ring, regardless of the keyspace and table parameter. This series fixes this, adding tablet support to `/storage_service/tokens_endpoint`, which will now return the tablet ring (tablet token -> tablet primary replica mapping) if the new keyspace and table parameters are provided.
`nodetool status` also gets a touch-up, to provide the tablet ring's token count (the tablet count) when invoked with a tablet keyspace and table.
Fixes: #17889
Fixes: #18474
=> scylla-nodetool: add tablet support for ring command

main.cc, service/qos/service_level_controller.cc, service/qos/service_level_controller.hh, service/storage_proxy.cc, test/boost/service_level_controller_test.cc, test/lib/cql_test_env.cc, tracing/trace_keyspace_helper.cc
Recent commit 12f160045b (Get rid of fb_utilities) replaced the usage of global fb_utilities and made all services use topology::my_address() in order to get local node broadcast address. Some places resulted in long dependency chains dereferences. to get to topology This PR fixes some of them.
=> Simplify access to topology::my_address()

repair/row_level.cc, repair/row_level.hh
Database has token-metadata onboard and other services use it to get topology from. Repair code has simpler and cleaner ways to get access to topology.
=> repair: Don't get topology via database

db/view/view.cc, db/view/view_update_backlog.hh, db/view/view_update_generator.cc, db/view/view_update_generator.hh, exceptions/exceptions.cc, exceptions/exceptions.hh, replica/database.hh, replica/table.cc, service/storage_proxy.cc, service/storage_proxy.hh, test/topology_custom/test_mv_delete_partitions.py
This series is a reupload of #13792 with a few modifications, namely a test is added and the conflicts with recent tablet related changes are fixed.
See https://github.com/scylladb/scylladb/issues/12379 and https://github.com/scylladb/scylladb/pull/13583 for a detailed description of the problem and discussions.
This PR aims to extend the existing throttling mechanism to work with requests that internally generate a large amount of view updates, as suggested by @nyh.
The existing mechanism works in the following way:
* Client sends a request, we generate the view updates corresponding to the request and spawn background tasks which will send these updates to remote nodes
* Each background task consumes some units from the `view_update_concurrency_semaphore`, but doesn't wait for these …
=> mv: throttle view update generation for large queries

service/forward_service.cc
With a large tablet count, e.g. 128k, forward_service::dispatch() can potentially stall when grouping ranges per endpoint.
`    Reactor stalled for 4 ms on shard 1. Backtrace: 0x5eb15ea 0x5eb09f5 0x5eb1daf 0x3dbaf 0x2d01e57 0x33f7d1e 0x348255f 0x2d005d4 0x2d3d017 0x2d3d58c 0x2d3d225 0x5e59622 0x5ec328f 0x5ec4577 0x5ee84e0 0x5e8394a 0x8c946 0x11296f
`
Also there are inefficient copies that are being removed. partition_range_vector for a single endpoint can grow beyond 1M.
=> Fix stalls in forward_service::dispatch() with large tablet count

docs/operating-scylla/admin-tools/scylla-sstable.rst, test/cql-pytest/test_tools.py, tools/scylla-sstable.cc
when migrating to the uuid-based identifiers, the mapping from the
integer-based generation to the shard-id is preserved. we used to have
"gen % smp_count" for calculating the shard which is responsible to host
a given sstable. despite that this is not a documented behavior, this is
handy when we try to correlate an sstable to a shard, typically when
looking at a performance issue.
in this change, a new subcommand is added to expose the connection
between the sstable and its "owner" shards.
Fixes #16343
Closes https://github.com/scylladb/scylladb/pull/16345
(cherry picked from commit 273ee36bee048dff784ff52d8607794fe82fce4f)
Fixes #18381
=> [Backport 5.4] tools/scylla-sstable: add `scylla sstable shard-of` command

mutation/mutation_fragment_stream_validator.cc, mutation/mutation_fragment_stream_validator.hh, test/boost/mutation_fragment_test.cc
Even when configured to not do any validation at all, the validator still did some. This small series fixes this, and adds a test to check that validation levels in general are respected, and the validator doesn't validate more than it is asked to.
Fixes: #18662
=> mutation_fragment_stream_validating_filter: respect validating_level::none

configure.py, cql3/statements/describe_statement.cc, db/cql_type_parser.cc, db/cql_type_parser.hh, db/schema_tables.cc, db/schema_tables.hh, replica/database.cc, test/boost/CMakeLists.txt, test/boost/sorting_test.cc, test/cql-pytest/test_describe.py, tools/schema_loader.cc, types/types.cc, types/user.hh, utils/sorting.hh
User-defined types can depend on each other, creating directed acyclic graph.
In order to support restoring schema from `DESC SCHEMA`, UDTs should be
ordered topologically, not alphabetically as it was till now.
This patch changes the way UDTs are ordered in `DESC SCHEMA`/`DESC KEYSPACE <ks>` statements, so the output can be safely copy-pasted to restore the schema.
Fixes #18539
=> Sort user-defined types in describe statements

api/column_family.cc, api/storage_service.cc, api/storage_service.hh, replica/database.hh
There's a set of API endpoints that toggle per-table auto-compaction and tombstone-gc booleans. They all live in two different .cc files under api/ directory and duplicate code of each other. This PR generalizes those handlers, places them next to each other, fixes leak on stop and, as a nice side effect, enlightens database.hh header.
=> Improve modularity of some per-table API endpoints

replica/database.cc, sstables/sstables_manager.cc, sstables/sstables_manager.hh, test/lib/test_services.cc
PR https://github.com/scylladb/scylladb/pull/18186 introduced a fiber that reloads reclaimed bloom filters when memory becomes available. Use maintenance scheduling group to run that fiber instead of running it in the main scheduling group.
Fixes #18675
=> sstables_manager: use maintenance scheduling group to run components reload fiber

replica/compaction_group.hh, replica/database.hh, replica/table.cc, service/storage_service.cc, service/topology_coordinator.cc, test/topology_experimental_raft/test_tablets.py
Retrieval of tablet stats must be serialized with mutation to token metadata, as the former requires tablet id stability.
If tablet split is finalized while retrieving stats, the saved erm, used by all shards, can have a lower tablet count than the one in a particular shard, causing an abort as tablet map requires that any id feeded into it is lower than its current tablet count.
Fixes #18085.
=> storage_service: Fix race between tablet split and stats retrieval

db/view/view.cc, db/view/view_builder.hh, db/view/view_update_checks.hh, main.cc, repair/repair.hh, repair/row_level.cc, repair/row_level.hh, replica/distributed_loader.cc, replica/distributed_loader.hh, sstables_loader.cc, sstables_loader.hh, streaming/consumer.cc, streaming/consumer.hh, streaming/stream_manager.cc, streaming/stream_manager.hh, streaming/stream_session.cc, test/lib/cql_test_env.cc
The system-distributed-keyspace and view-update-generator often go in pair, because streaming, repair and sstables-loader (via distributed-loader) need them booth to check if sstable is staging and register it if it's such. The check is performed by messing directly with system_distributed.view_build_status table, and the registration happens via view-update-generator.
That's not nice, other services shouldn't know that view status is kept in system table. Also view-update-generator is a service to generae and push view updates, the fact that it keeps staging sstables list is the implementation detail.
This PR replaces dependencies on the mentioned pair of services with the single dependency on view-builder (repair, sstables-loader and stream-manager are enlightened) and hides the view …
=> Rework view services and system-distributed-keyspace dependencies

alternator/controller.cc, alternator/controller.hh, api/storage_service.cc, main.cc, protocol_server.hh, redis/controller.cc, redis/controller.hh, replica/database.hh, test/boost/cql_query_test.cc, test/manual/sstable_scan_footprint_test.cc, thrift/controller.cc, thrift/controller.hh, transport/controller.cc, transport/controller.hh
Database used to be (and still is in many ways) an object used to get configuration from. Part of the configuration is the set of pre-configured scheduling groups. That's not nice, services should use each other for some real need, not as proxies to configuration. This patch patches the places that explicitly switch to statement group _not_ to use database to get the group itself.
fixes: #17643
=> Do not export statement scheduling group from database

service/qos/raft_service_level_distributed_data_accessor.cc, test/auth_cluster/test_raft_service_levels.py
Raft service levels are read-only in recovery mode. This patch adds check and proper error message when a user tries to modify service levels in recovery mode.
Fixes https://github.com/scylladb/scylladb/issues/18827
=> qos/raft_service_level_distributed_data_accessor: print correct error message when trying to modify a service level in recovery mode

cql3/statements/prepared_statement.hh, tracing/trace_state.hh
Users of prepared statement reference it with the help of "smart" pointers. None of the users are supposed to modify the object they point to, so mark the respective pointer type as `pointer<const prepared_statement>`. Also mark the fields of prepared statement itself with const's (some of them already are)
=> Mark prepare_statement as immutable

cql3/statements/ks_prop_defs.cc, test/cql-pytest/test_tablets.py
If the user wants to change the default initial tablets value, it uses ALTER KEYSPACE statement. However, specifying `WITH tablets = { initial: $value }`  will take no effect, because statement analyzer only applies `tablets` parameters together with the `replication` ones, so the working statement should be `WITH replication = $old_parameters AND tablets = ...` which is not very convenient.
This PR changes the analyzer so that altering `tablets` happens independently from `replication`. Test included.
fixes: #18801
=> Fix parsing of initial tablets by ALTER

repair/row_level.cc
This series ignores errors in `load_history()` to prevent `abort_requested_exception` coming from `get_repair_module().check_in_shutdown()` from escaping during `repair_service::stop()`, causing
```
repair_service::~repair_service(): Assertion `_stopped' failed.
```
Fixes https://github.com/scylladb/scylladb/issues/18889
Backport to 6.0 required due to 523895145dac065d2ee695c52583f5ba8a693fa9
=> Harden the repair_service shutdown path

scylla-gdb.py, sstables/sstables.cc, sstables/sstables.hh, sstables/sstables_manager.cc, sstables/sstables_manager.hh, test/boost/sstable_datafile_test.cc, test/boost/sstable_directory_test.cc, test/lib/sstable_test_env.hh, test/lib/sstable_utils.hh, utils/error_injection.hh
PR #17771 introduced a threshold for the total memory used by all bloom filters across SSTables. When the total usage surpasses the threshold, the largest bloom filter will be removed from memory, bringing the total usage back under the threshold. This PR adds support for reloading such reclaimed bloom filters back into memory when memory becomes available (i.e., within the 10% of available memory earmarked for the reclaimable components). 
The SSTables manager now maintains a list of all SSTables whose bloom filter was removed from memory and attempts to reload them when an SSTable, whose bloom filter is still in memory, gets deleted. The manager reloads from the smallest to the largest bloom filter to maximize the number of filters being reloaded into memory.
Backported from …
=> [Backport 5.4] : Reload reclaimed bloom filters when memory is available

scylla-gdb.py, sstables/sstables.cc, sstables/sstables.hh, sstables/sstables_manager.cc, sstables/sstables_manager.hh, test/boost/sstable_datafile_test.cc, test/boost/sstable_directory_test.cc, test/lib/sstable_test_env.hh, test/lib/sstable_utils.hh
PR https://github.com/scylladb/scylladb/pull/17771 introduced a threshold for the total memory used by all bloom filters across SSTables. When the total usage surpasses the threshold, the largest bloom filter will be removed from memory, bringing the total usage back under the threshold. This PR adds support for reloading such reclaimed bloom filters back into memory when memory becomes available (i.e., within the 10% of available memory earmarked for the reclaimable components).
The SSTables manager now maintains a list of all SSTables whose bloom filter was removed from memory and attempts to reload them when an SSTable, whose bloom filter is still in memory, gets deleted. The manager reloads from the smallest to the largest bloom filter to maximize the number of filters being reloaded …
=> [Backport 5.2] : Reload reclaimed bloom filters when memory is available 

main.cc, replica/distributed_loader.cc, sstables_loader.cc, sstables_loader.hh
Currently the loader is called via API, which inherits the maintenance scheduling group from API http server. The loader then can either do load_and_stream() or call (legacy) distributed_loader::upload_new_sstables(). The latter first switches into streaming scheduling group, but the former doesn't and continues running in the maintenance one.
All this is not really a problem, because streaming sched group and maintenance sched group is one group under two different variable names. However, it's messy and worth delegating the sched group switch (even if it's a no-op) to the sstables-loader. As a nice side effect, this patch removes one place that uses database as proxy object to get configuration parameters.
=> Run sstables loader in scheduling group

locator/tablets.cc, locator/tablets.hh, repair/repair.cc, service/storage_service.cc
Tablet allocation does not guarantee fairness of
the first replica in the replicas set across dcs.
The lack of this fix cause the following dtest to fail:
repair_additional_test.py::TestRepairAdditional::test_repair_option_pr_multi_dc
Use the tablet_map get_primary_replica or get_primary_replica_within_dc,
respectively to see if this node is the primary replica for each tablet
or not.
Fixes https://github.com/scylladb/scylladb/issues/17752
No backport is required before 6.0 as tablets (and tablet repair) are introduced in 6.0
=> repair: Introduce new primary replica selection algorithm for tablets

db/hints/manager.cc, db/hints/manager.hh, service/storage_proxy.cc
In d0f5873, we introduced mappings IP–host ID between hint directories and the hint endpoint managers managing them. As a consequence, it may happen that one hint directory stores hints towards multiple nodes at the same time. If any of those nodes leaves the cluster, we should drain the hint directory. However, before these changes that doesn't happen – we only drain it when the node of the same host ID as the hint endpoint manager leaves the cluster.
This PR fixes that draining issue in the pre-host-ID-based hinted handoff. Now no matter which of the nodes corresponding to a hint directory leaves the cluster, the directory will be drained.
We also introduce error injections to be able to test that it indeed happens.
Fixes scylladb/scylladb#18761
=> db/hints: Use host ID to IP mappings to choose the ep manager to drain when node is leaving

db/schema_tables.cc, service/storage_service.cc, test/topology_custom/test_ip_mappings.py
If a node restart just before it stores bootstrapping node's IP it will
not have ID to IP mapping for bootstrapping node which may cause failure
on a write path. Detect this and fail bootstrapping if it happens.
=>  Fail bootstrap if ip mapping is missing during double write stage

replica/compaction_group.hh, replica/database.hh, replica/table.cc, service/storage_service.cc, service/topology_coordinator.cc, test/topology_experimental_raft/test_tablets.py
Retrieval of tablet stats must be serialized with mutation to token metadata, as the former requires tablet id stability.
If tablet split is finalized while retrieving stats, the saved erm, used by all shards, can have a lower tablet count than the one in a particular shard, causing an abort as tablet map requires that any id feeded into it is lower than its current tablet count.
Fixes https://github.com/scylladb/scylladb/issues/18085.
(cherry picked from commit https://github.com/scylladb/scylladb/commit/abcc68dbe771f1a05a73b0a1e1686f2b4e7fd57e)
(cherry picked from commit https://github.com/scylladb/scylladb/commit/551bf9dd58483c57e25341cc0e9af984e175b42f)
(cherry picked from commit https://github.com/scylladb/scylladb/commit/e7246751b649379b8188633ce92f02a64afcf465)
Refs …
=> [Backport 6.0] storage_service: Fix race between tablet split and stats retrieval

api/task_manager.cc, api/task_manager_test.cc, docs/dev/task_manager.md, tasks/task_manager.cc, tasks/task_manager.hh, tasks/test_module.hh, test/rest_api/rest_util.py, test/rest_api/task_manager_utils.py, test/rest_api/test_compaction_task.py, test/rest_api/test_repair_task.py, test/rest_api/test_task_manager.py
Task manager's tasks stay in memory after they are finished.
Moreover, even if a child task is unregistered from task manager,
it is still alive since its parent keeps a foreign pointer to it. Also,
when a task has finished successfully there is no point in keeping
all of its descendants in memory.
The patch introduces folding of task manager's tasks. Whenever
a task which has a parent is finished it is unregistered from task
manager and foreign_ptr to it (kept in its parent) is replaced
with its status. Children's statuses of the task are dropped unless
they or one of their descendants failed. So for each operation we
keep a tree of tasks which contains:
- a root task and its direct children (status if they are finished, a task 
otherwise);
- running tasks and their direct children (same …
=> [Backport 6.0] tasks: introduce task manager's task folding

db/view/node_view_update_backlog.hh, db/view/view.cc, service/misc_services.cc, service/storage_proxy.cc, service/storage_proxy.hh, test/boost/view_schema_test.cc
Currently, there are 2 ways of sharing a backlog with other nodes: through
a gossip mechanism, and with responses to replica writes. In gossip, we
check each second if the backlog changed, and if it did we update other
nodes with it. However if the backlog for this node changed on another
node with a write response, the gossiped backlog is currently not updated,
so if after the response the backlog goes back to the value from the previous
gossip round, it will not get sent and the other node will stay with an
outdated backlog - this can be observed in the following scenario:
1. Cluster starts, all nodes gossip their empty view update backlog to one another
2. On node N, `view_update_backlog_broker` (the backlog gossiper) performs an iteration of its backlog update loop, sees no change …
=> mv: gossip the same backlog if a different backlog was sent in a response

main.cc, test/topology_experimental_raft/test_alternator.py, test/topology_experimental_raft/test_mv_tablets.py
Alternator has a custom TTL implementation. This is based on a loop, which scans existing rows in the table, then decides whether each row have reached its end-of-life and deletes it if it did. This work is done in the background, and therefore it uses the maintenance (streaming) scheduling group. However, it was observed that part of this work leaks into the statement scheduling group, competing with user workloads, negatively affecting its latencies. This was found to be causes by the reads and writes done on behalf of the alternator TTL, which looses its maintenance scheduling group when these have to go to a remote node. This is because the messaging service was not configured to recognize the streaming scheduling group, when statement verbs like read or writes are invoked. The …
=> alternator: keep TTL work in the maintenance scheduling group

db/hints/manager.cc, db/hints/manager.hh, service/storage_proxy.cc
In [d0f5873](https://github.com/scylladb/scylladb/commit/d0f58736c839b1d9c76672ccac38d301d1dc1be6), we introduced mappings IP–host ID between hint directories and the hint endpoint managers managing them. As a consequence, it may happen that one hint directory stores hints towards multiple nodes at the same time. If any of those nodes leaves the cluster, we should drain the hint directory. However, before these changes that doesn't happen – we only drain it when the node of the same host ID as the hint endpoint manager leaves the cluster.
This PR fixes that draining issue in the pre-host-ID-based hinted handoff. Now no matter which of the nodes corresponding to a hint directory leaves the cluster, the directory will be drained.
We also introduce error injections to be able to test that it …
=>  [Backport 6.0] db/hints: Use host ID to IP mappings to choose the ep manager to drain when node is leaving

api/api-doc/error_injection.json, api/error_injection.cc, replica/database.cc, replica/table.cc, test/pylib/rest_client.py, test/topology_custom/test_repair.py, utils/error_injection.hh
This config item is propagated to the table object via table::config. Although the field in `table::config`, used to propagate the value, was `utils::updateable_value<T>`, it was assigned a constant and so the live-update chain was broken.
This series fixes this and adds a test which fails before the patch and passes after. The test needed new test infrastructure, around the failure injection api, namely the ability to exfiltrate the value of internal variable. This infrastructure is also added in this series.
Fixes: https://github.com/scylladb/scylladb/issues/18674
=> make enable_compacting_data_for_streaming_and_repair truly live-update

.github/clang-include-cleaner.json, .github/workflows/iwyu.yaml, alternator/executor.hh, alternator/stats.hh, exceptions/unrecognized_entity_exception.hh
in this changeset, we tighten the clang-include-cleaner workflow, and address the warnings in two more subdirectories in the source tree.
* it's a cleanup, no need to backport
=> .github: change severity to error in clang-include-cleaner 

test/boost/memtable_test.cc
before this change, when performing memtable_test, we expect that
the memtables of ks.cf is the only memtables being flushed. and
we inject 4 failures in the code path of flush, and wait until 4
of them are triggered. but in the background, `dirty_memory_manager`
performs flush on all tables when necessary. so, the total number of
failures is not necessary the total number of failures triggered
when flushing ks.cf, some of them could be triggered when flushing
system tables. that's why we have sporadict test failures from
this test. as we might check `t.min_memtable_timestamp()` too soon.
after this change, we increase `unspooled_dirty_soft_limit` setting,
in order to disable `dirty_memory_manager`, so that the only flush
is performed by the test.
Fixes …
=> test: memtable_test: increase unspooled_dirty_soft_limit 

db/config.cc, main.cc, utils/enum_option.hh
Some time ago it turned out that if unrecognized feature name is met in scylla.yaml, the whole experimental features list is ignored, but scylla continues to boot. There's UNUSED feature which is the proper way to deprecate a feature, and this PR improves its handling in several ways.
1. The recently removed "tablets" feature is partially brought back, but marked as UNUSED
2. Any UNUSED features met while parsing are printed into logs
3. The enum_option<> helper is enlightened along the way
refs: #18968
=> Improve handling of outdated --experimental-features

.github/clang-matcher.json, .github/workflows/clang-nightly.yaml, .github/workflows/clang-tidy.yaml
to be prepared for changes from clang, and enjoy the new warnings/errors from this compiler.
* it is an improvement in our CI, no need to backport.
=> .github: add workflow to build with clang nightly

main.cc
The API endpoints are registered for particular services (with rare exceptions), and once the corresponding service is ready, its endpoints section can be registered too. Same but reversed is for shutdown, and it's automatic with deferred actions.
refs: #2737
=> Register API endpoints next to corresponding services

db/hints/manager.cc, db/hints/sync_point.cc, db/hints/sync_point.hh, idl/hinted_handoff.idl.hh, test/boost/hint_test.cc
Change the format of sync points to use host ID instead of IPs, to be consistent with the use of host IDs in hinted handoff module.
Introduce sync point v3 format which is the same as v2 except it stores host IDs instead of IPs.
The decoding supports both formats with host IDs and IPs, so a sync point contains now a variant of either types, and in the case of new type the translation is avoided.
Fixes #18653
=> hinted handoff: migrate sync point to host ID

sstables/sstables.cc, sstables/sstables.hh, test/boost/schema_loader_test.cc, test/cql-pytest/test_tools.py, test/lib/random_schema.cc, tools/schema_loader.cc, tools/schema_loader.hh, tools/scylla-sstable.cc
As it turns out, each sstable carries its own schema in its serialization header (Statistics component). This schema is incomplete -- the names of the key columns are not stored, just their type. Static and regular columns do have names and types stored however. This bare-bones schema is enough to parse and display the content of the sstable. Another thing missing is schema options (the stuff after the `WITH` keyword, except the clustering order). The only options stored are the compression options (in the CompressionInfo component), this is actually needed to read the Data component.
This series adds a new method to `tools/schema_loader.cc` to extract the schema stored in the sstable itself. This new schema load method is used as the last fall-back for obtaining the schema, in case …
=> scylla-sstable: add method to load the schema from the sstable itself

.github/workflows/iwyu.yaml, api/authorization_cache.hh, api/cache_service.cc, api/cache_service.hh, api/column_family.hh, api/error_injection.cc, api/raft.cc, api/system.hh, api/task_manager_test.hh, api/tasks.hh, api/token_metadata.hh
these unused includes were identified by clangd. see https://clangd.llvm.org/guides/include-cleaner#unused-include-warning for more details on the "Unused include" warning.
also, add api to iwyu github workflow's CLEANER_DIR, to prevent future violations.
---
=> api: do not include unused headers

test/pylib/manager_client.py, test/pylib/scylla_cluster.py
This PR fixes two problems with the `expected_error`
parameter in `server_add` and `servers_add`.
1. It didn't work in `server_add` if the cluster was empty
because of an incorrect attempt to connect the driver.
2. It didn't work in `servers_add` completely because the
`seeds` parameter was handled incorrectly.
This PR only adds improvements in the testing framework,
no need to backport it.
=> test: servers_add: fix the expected_error parameter

dist/CMakeLists.txt
this change is created in the same spirit of 1186ddef16, which updated the rule for generating the stripped dist pkg, but it failed to update the one for generating the unstripped dist pkg. what's why we have build failure when the workflow is looking for the unstripped tar.gz:
```
08:02:47  ++ ls /jenkins/workspace/scylla-master/scylla-ci/scylla/build/RelWithDebInfo/dist/tar/scylla-unstripped-6.1.0~dev-0.20240613.d5bdddaeb40b.x86_64.tar.gz
08:02:47  ls: cannot access '/jenkins/workspace/scylla-master/scylla-ci/scylla/build/RelWithDebInfo/dist/tar/scylla-unstripped-6.1.0~dev-0.20240613.d5bdddaeb40b.x86_64.tar.gz': No such file or directory`
```
so, in this change, we fix the path.
Refs #2717
---
* cmake related change, hence no need to backport.
=> build: cmake: use path to be compatible with CI

cql3/query_processor.cc, cql3/statements/create_keyspace_statement.cc, cql3/statements/create_keyspace_statement.hh, cql3/statements/create_table_statement.cc, cql3/statements/create_table_statement.hh, cql3/statements/create_type_statement.cc, cql3/statements/create_type_statement.hh, cql3/statements/create_view_statement.cc, cql3/statements/create_view_statement.hh, cql3/statements/schema_altering_statement.cc, cql3/statements/schema_altering_statement.hh, service/raft/raft_group0_client.cc, service/raft/raft_group0_client.hh, test/boost/cql_query_test.cc, transport/messages/result_message.hh, transport/messages/result_message_base.hh
cql3: always return created event in create ks/table/type/view statement
In case multiple clients issue concurrently CREATE KEYSPACE IF NOT EXISTS
and later USE KEYSPACE it can happen that schema in driver's session is
out of sync because it synces when it receives special message from
CREATE KEYSPACE response.
Similar situation occurs with other schema change statements.
In this patch we fix only create keyspace/table/type/view statements
by always sending created event. Behavior of any other schema altering
statements remains unchanged.
Fixes https://github.com/scylladb/scylladb/issues/16909
**backport: no, it's not a regression**
=> cql3: always return created event in create keyspace statement

main.cc, test/pylib/scylla_cluster.py, test/topology_custom/test_alternator.py
This is a fairly elaborate backport of commit b2a500a9a14eb1debef1271336d1d453420eb0c5 to branch 5.4
The code patch itself is trivial, and backported cleanly. The big problem was the test, which was written using the "topology" test framework - because it needs to test a cluster, not a single node, because the scheduling group problem only happened when sending requests between different Scylla nodes.
I had to fix in the backport the following problems:
1. The test used a library function add_servers() which didn't exist in branch 5.4, so needed to switch to making three individual add_server() calls.
2. The test was randomly placed in the topology_experimental_raft directory, which runs with the tablets experimental flag enabled. In 5.4, the tablets code was broken with Alternator, and …
=>  [Backport 5.4] alternator: keep TTL work in the maintenance scheduling group

db/paxos_grace_seconds_extension.hh, schema/schema.cc, schema/schema.hh
Fixes #19334
Current impl uses hardcoded printing of a few extensions.
Instead, use extension options to string and print all.
Note: required to make enterprise CI happy again.
=> schema: Make "describe" use extensions to string

db/config.cc, db/config.hh, reader_concurrency_semaphore.cc, reader_concurrency_semaphore.hh, replica/database.cc, test/boost/reader_concurrency_semaphore_test.cc
Making the count resources on the maintenance (streaming) semaphore live update via config. This will allow us to improve repair speed on mixed-shard clusters, where we suspect that reader trashing -- due to the combination of high number of readers on each shard and very conservative reader count limit (10) -- is the main cause of the slowness.
Making this count limit confgurable allows us to start experimenting with this fix, without committing to a count limit increase (or removal), addressing the pain in the field.
Refs: #18269
No OSS backport needed.
=> configurable maintenance (streaming) semaphore count resource limit

test.py, test/object_store/conftest.py, test/pylib/manager_client.py, test/pylib/scylla_cluster.py, test/topology/conftest.py
Related: https://github.com/scylladb/scylladb/issues/17851
Fix the issue that test logs were not deleted
Fix the issue that the URL to the failed test directory was incorrectly shown even when artifacts_dir_url option was not provided
Fix the issue that there were no node logs when it failed to join the cluster
=> [test.py] Fix several issues in log gathering

replica/database.cc, sstables/sstables_manager.cc, sstables/sstables_manager.hh, test/lib/test_services.cc
PR https://github.com/scylladb/scylladb/pull/18186 introduced a fiber that reloads reclaimed bloom filters when memory becomes available. Use maintenance scheduling group to run that fiber instead of running it in the main scheduling group.
Fixes https://github.com/scylladb/scylladb/issues/18675
(cherry picked from commit https://github.com/scylladb/scylladb/commit/79f674629803a979a981333cfe6658c5e9874a22)
(cherry picked from commit https://github.com/scylladb/scylladb/commit/6f58768c460c8d9fe2f3303fa43bbe02574b5cf4)
Backported from https://github.com/scylladb/scylladb/pull/18721 to 5.4.
=> [Backport 5.4] sstables_manager: use maintenance scheduling group to run components reload fiber

auth/service.cc, auth/service.hh
With big number of shards in the cluster (e.g. 500+) due to cache
periodic refresh we experience high load on role_permissions table
(e.g. 1k op/s). The load on roles table is amplified because to populate
single entry in the cache we do several selects on roles table. Some
of this can't be avoided because roles are arranged in a tree-like
structure where permissions can be inherited.
This patch tries to reuse queries which are simply duplicated. It should
reduce the load on roles table by up to 50%.
Fixes scylladb/scylladb#19299
=> auth: reuse roles select query during cache population

test/boost/stall_free_test.cc, utils/chunked_vector.hh, utils/large_bitset.cc, utils/lsa/chunked_managed_vector.hh, utils/stall_free.hh
Replace the reserve_partial loop in large_bitset constructor with a new function - reserve_gently() that can reserve memory without stalling by repeatedly calling reserve_partial() method of the passed container.
=> utils/large_bitset: replace reserve_partial with utils::reserve_gently

db/view/view.cc, db/view/view_update_backlog.hh, idl/view.idl.hh, replica/database.cc, service/misc_services.cc, service/storage_proxy.cc
Currently, when calculating the view update backlog for gossip,
we start with `db::view::update_backlog()` and compare it to backlogs
from all shards. However, this backlog can't be compared to other
backlogs - it has size 0 and we compare the fraction current/size
when comparing backlogs, causing us to compare with `NaN`.
This patch fixes it by starting the comparisons with an empty backlog.
The patch introducing this issue (f70f774e404719ee6884c2c84d5def6e0690c7e7) wasn't backported, so this one doesn't need to be either
=> mv: fix value of the gossiped view update backlog

api/task_manager.cc, compaction/compaction_manager.cc, compaction/compaction_manager.hh, repair/repair.cc, repair/task_manager_module.hh, tasks/task_manager.cc, tasks/task_manager.hh, test/rest_api/test_task_manager.py
Currently if task_manager::task::impl::abort preempts before children are recursively aborted and then the task gets unregistered, we hit use after free since abort uses children vector which is no longer alive.
Modify abort method so that it goes over all tasks in task manager and aborts those with the given parent.
Fixes: #19304.
Requires backport to all versions containing task manager
=> tasks: fix tasks abort

dht/decorated_key.hh, dht/i_partitioner.cc, gms/application_state.cc, gms/application_state.hh, gms/endpoint_state.cc, gms/endpoint_state.hh, gms/gossiper.cc, gms/gossiper.hh, gms/inet_address.cc, gms/inet_address.hh, gms/versioned_value.hh, lang/wasm_instance_cache.cc, node_ops/node_ops_ctl.hh, test/boost/cdc_test.cc, test/boost/network_topology_strategy_test.cc, test/boost/serialization_test.cc, test/boost/types_test.cc, types/types.cc, types/types.hh
since we've switched almost all callers of the operator<< to {fmt}, let's drop the unused operator<<:s.
there are more occurrences of unused operator<< in the tree, but let's do the cleanup piecemeal.
---
this is a cleanup, so no need to backport
=> treewide: remove unused operator<<

api/api.cc, api/api_init.hh, api/storage_service.cc, api/storage_service.hh, main.cc
The service in question is pretty small one, but it has its API endpoint that lives in /storage_service group. Currently when a service starts and has any endpoints that depend on it, the endpoint registration should follow it (#2737). Here's the PR that does it for load meter. Another goal of this change is that http context now has one less dependency onboard.
=> Sanitize load_meter API handlers management

compaction/compaction_manager.cc, compaction/compaction_strategy.cc, compaction/compaction_strategy.hh, compaction/compaction_strategy_impl.hh, compaction/compaction_strategy_type.hh, compaction/leveled_compaction_strategy.cc, compaction/leveled_compaction_strategy.hh, compaction/size_tiered_compaction_strategy.cc, compaction/size_tiered_compaction_strategy.hh, compaction/task_manager_module.cc, compaction/task_manager_module.hh, compaction/time_window_compaction_strategy.cc, compaction/time_window_compaction_strategy.hh, replica/database.hh, sstables/storage.cc, sstables/storage.hh, test/boost/sstable_compaction_test.cc, test/boost/sstable_datafile_test.cc
Normally, the space overhead for TWCS is 1/N, where is number of windows. But during off-strategy, the overhead is 100% because input sstables cannot be released earlier.
Reshaping a TWCS table that takes ~50% of available space can result in system running out of space.
That's fixed by restricting every TWCS off-strategy job to 10% of free space in disk. Tables that aren't big will not be penalized with increased write amplification, as all input (disjoint) sstables can still be compacted in a single round.
Fixes #16514.
=> Reduce TWCS off-strategy space overhead

cql3/statements/select_statement.cc, test/boost/cql_query_test.cc
This patch adds a check if aggregation query is doing single-partition read and if so, makes the query to not use forward_service and do not parallelize the request. 
Fixes #19349
=> cql3/statement/select_statement: do not parallelize single-partition aggregations

gms/gossiper.cc, gms/gossiper.hh, service/storage_service.cc
The node booting in gossip topology waits until all NORMAL
nodes are UP. If we removed a different node just before,
the booting node could still see it as NORMAL and wait for
it to be UP, which would time out and fail the bootstrap.
This issue caused scylladb/scylladb#17526.
Fix it by recalculating the nodes to wait for in every step of the
of the `wait_alive` loop.
Although the issue fixed by this PR caused only test flakiness,
it could also manifest in real clusters. It's best to backport this
PR to 5.4 and 6.0.
Fixes scylladb/scylladb#17526
=> join_token_ring, gossip topology: recalculate sync nodes in wait_alive

.github/workflows/iwyu.yaml, cdc/cdc_extension.hh, cdc/metadata.cc, cdc/stats.hh
also add `auth` and `cdc` to iwyu's `CLEANER_DIR` setting.
---
=> cdc: do not include unused headers

api/api.cc, api/api_init.hh, api/failure_detector.cc, api/failure_detector.hh, api/gossiper.cc, api/gossiper.hh, main.cc
Gossiper has two blocs of endpoints, both are registered in legacy/random place in main. This PR moves them next to gossiper start and adds unregistration for both.
refs: #2737
=> Sanitize gossiper API endpoints management

cql3/query_processor.cc, cql3/query_processor.hh, db/batchlog_manager.cc
The `system.batchlog` table has a partition for each batch that failed to complete. After finally applying the batch, the partition is deleted. Although the table has gc_grace_second = 0, tombstones can still accumulate in memory, because we don't purge partition tombstones from either the memtable or the cache. This can lead to the cache and memtable of this table to accumulate many thousands of even millions of tombstones, making batchlog replay very slow. We didn't notice this before, because we would only replay all failed batches on unbootstrap, which is rare and a heavy and slow operation on its own right already.
With repair-based tombstone-gc however, we do a full batchlog replay at the beginning of each repair, and now this extra delay is noticeable.
Fix this by making sure …
=> batchlog replay: bypass tombstones generated by past replays

api/api.cc, api/api_init.hh, api/config.cc, api/config.hh, api/storage_proxy.cc, main.cc
API endpoints that need a particular service to get data from are registered next to this service (#2737). In /storage_proxy function there live some endpoints that work with config, so this PR moves them to the existing config.cc with config-related endpoints. The path these endpoints are registered with remains intact, so some tweak in proxy API registration is also here.
=> Move some /storage_proxy API endpoints to config.cc

gms/gossiper.cc, gms/gossiper.hh, service/storage_service.cc
The node booting in gossip topology waits until all NORMAL
nodes are UP. If we removed a different node just before,
the booting node could still see it as NORMAL and wait for
it to be UP, which would time out and fail the bootstrap.
This issue caused scylladb/scylladb#17526.
Fix it by recalculating the nodes to wait for in every step of the
of the `wait_alive` loop.
Although the issue fixed by this PR caused only test flakiness,
it could also manifest in real clusters. It's best to backport this
PR to 5.4 and 6.0.
Fixes scylladb/scylladb#17526
The first patch of the original PR merged to master,
017134fd3844ca4660c1bdbc7001f0676bb4bd80, differs because
the conflicting patch, e4c3c075102d9a826e737e601f936a96ec20535c,
hasn't been backported to 5.4. However, we don't have to
additionally …
=> [Backport 5.4] join_token_ring, gossip topology: recalculate sync nodes in wait_alive

db/paxos_grace_seconds_extension.hh, schema/schema.cc, schema/schema.hh, test/boost/cql_query_test.cc
Fixes https://github.com/scylladb/scylladb/issues/19334
Current impl uses hardcoded printing of a few extensions.
Instead, use extension options to string and print all.
Note: required to make enterprise CI happy again.
(cherry picked from commit https://github.com/scylladb/scylladb/commit/d27620e1462597e4c3cbbeb5df524e4528c85cf5)
(cherry picked from commit https://github.com/scylladb/scylladb/commit/73abc56d79dcc02f9874cae086f50ac208aa2bcf)
Refs https://github.com/scylladb/scylladb/pull/19337'
(Manually re-done from mergify fail #19358)
=>  [Backport 5.4] schema: Make "describe" use extensions to string #19358 

api/task_manager.cc, compaction/compaction_manager.cc, compaction/compaction_manager.hh, repair/repair.cc, repair/task_manager_module.hh, tasks/task_manager.cc, tasks/task_manager.hh, test/rest_api/test_task_manager.py
Currently if task_manager::task::impl::abort preempts before children are recursively aborted and then the task gets unregistered, we hit use after free since abort uses children vector which is no longer alive.
Modify abort method so that it goes over all tasks in task manager and aborts those with the given parent.
Fixes: https://github.com/scylladb/scylladb/issues/19304.
Requires backport to all versions containing task manager
(cherry picked from commit https://github.com/scylladb/scylladb/commit/3463f495b1c54f3ea0de96f1dcee807a86e49fe8)
(cherry picked from commit https://github.com/scylladb/scylladb/commit/50cb797d9525274ce0a196e161ecf53bd02314e7)
Refs https://github.com/scylladb/scylladb/pull/19305
=> [Backport 6.0] tasks: fix tasks abort

test/auth_cluster/test_auth_v2_migration.py, test/pylib/util.py
Those tests are sometimes failing on CI and we have two hypothesis:
1. Something wrong with consistency of statements
2. Interruption from another test run (e.g. same queries performed concurrently or data remained after previous run)
To exclude or confirm 2. we add random marker to avoid potential collision, in such case it will be clearly visible that wrong data comes from a different run.
Related scylladb/scylladb#18931
Related scylladb/scylladb#18319
backport: no, just a test fix
=> test: auth: add random tag to resources in test_auth_v2_migration

test.py, test/pylib/scylla_cluster.py
this PR has 2 commits
- [test: pass Scylla extra CMD args from test.py args](https://github.com/scylladb/scylladb/commit/6b367a04b5c7a6afcba284b65cc40cffda33a790)
- [test: adjust scylla_cluster.merge_cmdline_options behavior](https://github.com/scylladb/scylladb/commit/c60b36090a9400e011e951587000bd49448d2db8)
the main goal is to solve [test.py: provide an easy-to-remember, univeral way to run scylla with trace level logging](https://github.com/scylladb/scylladb/issues/14960) issue
but also can be used to easily apply additional arguments for all UnitTests and PythonTests on the fly from the test.py CMD
=> [test.py] add --extra-scylla-cmdline-options argument for test.py

CMakeLists.txt, compaction/compaction_manager.cc, configure.py, main.cc, readers/reversing_v2.hh, replica/compaction_group.hh, replica/table.cc, test/lib/test_services.cc, utils/config_file.cc, utils/config_file.hh
Switch the C++ standard from C++20 to C++23. This is straightforward, but there are a few
fallouts (mostly due to std::unique_ptr that became constexpr) that need to be fixed first.
Internal enhancement - no backport required
=> build: update C++ standard to C++23

api/storage_service.cc
All streams used by httpd handlers are to be closed by the handler itself, caller doesn't take care of that.
fixes: #19494
=> Close output_stream in get_snapshot_details() API handler

api/task_manager.cc
If client stops reading response early, the server-side stream throws but must be closed anyway. Seen in another endpoint and fixed by #19541
=> Close output stream in task manager's API get_tasks handler

service/storage_service.cc, test/topology_custom/test_long_join.py
A node may wait in the topology coordinator queue for awhile before been joined. Since the local address is added as expiring entry to the raft address map it may expire meanwhile and the bootstrap will fail. The series makes the entry non expiring.
Fixes  scylladb/scylladb#19523
Needs to be back ported to 6.0 since the bug may cause bootstrap to fail.
=> Do not expire local addres in raft address map since the local node cannot disappear

api/task_manager.cc
If client stops reading response early, the server-side stream throws but must be closed anyway. Seen in another endpoint and fixed by https://github.com/scylladb/scylladb/pull/19541
Original commit is 0ce00ebfbd845d9f3f71ade3c5e726815635e265
Had simple conflict with ffb5ad494fcb5779a22ace8af694a91c8598b5a5
closes: #19560
=> [Backport 5.4] Close output stream in task manager's API get_tasks handler

db/config.cc, db/config.hh, reader_concurrency_semaphore.cc, reader_concurrency_semaphore.hh, replica/database.cc, test/boost/reader_concurrency_semaphore_test.cc
The reader concurrency semaphore restricts the concurrency of reads that require CPU (intention: they read from the cache) to 1, meaning that if there is even a single active read which declares that it needs just CPU to proceed, no new read is admitted. This is meant to keep the concurrency of reads in the cache at 1. The idea is that concurrency in the cache is not useful: it just leads to the reactor rotating between these reads, all of the finishing later then they could if they were the only active read in the cache.
This was observed to backfire in the case where there reads from a single table are mostly very fast, but on some keys are very slow (hint: collection full of tombstones). In this case the slow read keeps up the fast reads in the queue, increasing the 99th percentile …
=> reader_concurrency_semaphore: make CPU concurrency configurable

cql3/statements/select_statement.cc, test/boost/cql_query_test.cc
This patch adds a check if aggregation query is doing single-partition read and if so, makes the query to not use forward_service and do not parallelize the request.
Fixes https://github.com/scylladb/scylladb/issues/19349
(cherry picked from commit https://github.com/scylladb/scylladb/commit/e9ace7c2031523099de0b076b9678264ddd74e5c)
(cherry picked from commit https://github.com/scylladb/scylladb/commit/8eb5ca820289d3ebec42e3108f3706bd0156ef79)
Refs https://github.com/scylladb/scylladb/pull/19350
=> [Backport 6.0] cql3/statement/select_statement: do not parallelize single-partition aggregations

cql3/statements/select_statement.cc, test/boost/cql_query_test.cc
This patch adds a check if aggregation query is doing single-partition read and if so, makes the query to not use forward_service and do not parallelize the request.
Fixes https://github.com/scylladb/scylladb/issues/19349
(cherry picked from commit https://github.com/scylladb/scylladb/commit/e9ace7c2031523099de0b076b9678264ddd74e5c)
(cherry picked from commit https://github.com/scylladb/scylladb/commit/8eb5ca820289d3ebec42e3108f3706bd0156ef79)
Refs https://github.com/scylladb/scylladb/pull/19350
=> [Backport 5.4] cql3/statement/select_statement: do not parallelize single-partition aggregations #19414

.github/workflows/iwyu.yaml, compaction/compaction.cc, compaction/compaction.hh, compaction/compaction_backlog_manager.hh, compaction/compaction_descriptor.hh, compaction/compaction_manager.hh, compaction/compaction_strategy.hh, compaction/size_tiered_compaction_strategy.hh, compaction/task_manager_module.hh, replica/compaction_group.hh, test/boost/sstable_compaction_test.cc
these unused includes were identified by clangd. see
https://clangd.llvm.org/guides/include-cleaner#unused-include-warning
for more details on the "Unused include" warning.
---
=> compaction: not include unused headers

db/hints/internal/common.hh, db/hints/internal/hint_sender.cc, db/hints/manager.cc, service/storage_proxy.cc, service/storage_proxy_stats.hh, test/topology_experimental_raft/test_fencing.py
Although Scylla already exposes metrics keeping track of various information related to hinted handoff, all of them correspond to either storing or sending hints. However, when debugging, it's also crucial to be aware of how many hints are coming to a given node and what their size is. Unfortunately, the existing metrics are not enough to obtain that information.
This PR introduces the following new metrics:
* `sent_bytes_total` – the total size of the hints that have been sent from a given shard,
* `received_hints_total` – the total number of hints that a given shard has received,
* `received_hints_bytes_total` – the total size of the hints a given shard has received.
It also renames `hints_manager_sent` to `hints_manager_sent_total` to avoid conflicts of prefixes between that metric and …
=> service/storage_proxy: Add metrics keeping track of incoming hints

db/config.cc, db/config.hh, replica/database.cc, replica/database.hh, replica/table.cc, test/topology_custom/test_repair.py
We currently disable tombstone GC for compaction done on the read path of streaming and repair, because those expired tombstones can still prevent data resurrection. With time-based tombstone GC, missing a repair for long enough can cause data resurrection because a tombstone is potentially GC'd before it could be spread to every node by repair. So repair disseminating these expired tombstones helps clusters which missed repair for long enough. It is not a guarantee because compaction could have done the GC itself, but it is better than nothing.
This last resort is getting less important with repair-based tombstone GC. Furthermore, we have seen this cause huge repair amplification in a cluster, where expired tombstones triggered repair replicating otherwise identical rows.
This series …
=> repair/streaming: enable toggling tombstone gc with a config item

api/api-doc/raft.json, api/raft.cc, service/raft/group0_state_machine.cc, service/raft/raft_group_registry.cc, service/raft/raft_group_registry.hh, test/pylib/rest_client.py, test/topology_custom/test_table_desc_read_barrier.py
Introduce REST API for triggering a read barrier.
This is to make sure the database schema is up to date on the node where the read barrier is triggered. One of the use cases is the database backup via the Scylla Manager, which requires that the schema backed up is matching the data or newer (data can be migrated, but an older schema would cause issues).
Fixes #19213
=> Add API for read barrier

mutation/mutation_partition_v2.cc, test/boost/logalloc_test.cc, utils/allocation_strategy.hh, utils/logalloc.cc
apply_monotonically() is run with reclaim disabled. So with some bad luck,
sentinel insertion might fail with bad_alloc even on a perfectly healthy node.
We can't deal with the failure of sentinel insertion, so this will result in a
crash.
This patch prevents the spurious OOM by reserving some memory (1 LSA segment)
and only making it available right before the critical allocations.
Fixes https://github.com/scylladb/scylladb/issues/19552
---
We might want to backport it to 5.4 and 6.0, or we might want to backport a simpler fix.
=>  mutation_partition_v2: in apply_monotonically(), avoid bad_alloc on sentinel insertion

compaction/compaction_manager.cc, compaction/compaction_strategy.cc, compaction/compaction_strategy.hh, compaction/compaction_strategy_impl.hh, compaction/compaction_strategy_type.hh, compaction/leveled_compaction_strategy.cc, compaction/leveled_compaction_strategy.hh, compaction/size_tiered_compaction_strategy.cc, compaction/size_tiered_compaction_strategy.hh, compaction/task_manager_module.cc, compaction/time_window_compaction_strategy.cc, compaction/time_window_compaction_strategy.hh, sstables/storage.cc, sstables/storage.hh, test/boost/sstable_compaction_test.cc, test/boost/sstable_datafile_test.cc
Normally, the space overhead for TWCS is 1/N, where is number of windows. But during off-strategy, the overhead is 100% because input sstables cannot be released earlier.
Reshaping a TWCS table that takes ~50% of available space can result in system running out of space.
That's fixed by restricting every TWCS off-strategy job to 10% of free space in disk. Tables that aren't big will not be penalized with increased write amplification, as all input (disjoint) sstables can still be compacted in a single round.
Fixes https://github.com/scylladb/scylladb/issues/16514.
(cherry picked from commit https://github.com/scylladb/scylladb/commit/b8bd4c51c27315019e7f18651c0cc73551b3f377)
(cherry picked from commit https://github.com/scylladb/scylladb/commit/51c7ee889e4205e51d211f159ebfb2066d8abf7d) …
=> [Backport 5.4] Reduce TWCS off-strategy space overhead

db/config.cc, db/config.hh, reader_concurrency_semaphore.cc, reader_concurrency_semaphore.hh, replica/database.cc, test/boost/reader_concurrency_semaphore_test.cc
The reader concurrency semaphore restricts the concurrency of reads that require CPU (intention: they read from the cache) to 1, meaning that if there is even a single active read which declares that it needs just CPU to proceed, no new read is admitted. This is meant to keep the concurrency of reads in the cache at 1. The idea is that concurrency in the cache is not useful: it just leads to the reactor rotating between these reads, all of the finishing later then they could if they were the only active read in the cache.
This was observed to backfire in the case where there reads from a single table are mostly very fast, but on some keys are very slow (hint: collection full of tombstones). In this case the slow read keeps up the fast reads in the queue, increasing the 99th percentile …
=> [Backport 6.0] reader_concurrency_semaphore: make CPU concurrency configurable

cql3/statements/create_keyspace_statement.cc, cql3/statements/create_table_statement.cc, docs/alternator/alternator.md, docs/using-scylla/cdc/index.rst, docs/using-scylla/counters.rst, docs/using-scylla/lwt.rst, test/cql-pytest/cassandra_tests/batch_test.py, test/cql-pytest/cassandra_tests/functions/cast_fcts_test.py, test/cql-pytest/cassandra_tests/validation/entities/counters_test.py, test/cql-pytest/cassandra_tests/validation/entities/secondary_index_test.py, test/cql-pytest/cassandra_tests/validation/operations/compact_storage_test.py, test/cql-pytest/cassandra_tests/validation/operations/select_test.py, test/cql-pytest/test_cast_data.py, test/cql-pytest/test_counter.py, test/cql-pytest/test_describe.py, test/cql-pytest/test_tools.py, test/cql-pytest/test_unset.py, test/cql-pytest/test_wasm.py, test/topology_experimental_raft/test_fencing.py, tools/schema_loader.cc
Counter updates break under tablet migration (#18180), and for this reason counters need to be disabled until the problem is fixed. It's enough to forbid creating a table with counters, as altering a table without counters already cannot result in the table having counters:
1) Adding a counter column to a table without counters:
```
cqlsh> ALTER TABLE temp.cf ADD (col_name counter);
ConfigurationException: Cannot add a counter column (col_name) in a non counter column family
```
2) Altering a column to be of the counter type:
```
cqlsh> ALTER TABLE temp.cf ALTER col_name TYPE counter;
ConfigurationException: Cannot change col_name from type int to type counter: types are incompatible.
```
Fixes: #19449
Fixes: https://github.com/scylladb/scylladb/issues/18876
Need to backport to 6.0, as …
=> cql: forbid having counter columns in tablets tables

db/config.cc, db/config.hh, reader_concurrency_semaphore.cc, reader_concurrency_semaphore.hh, replica/database.cc, test/boost/reader_concurrency_semaphore_test.cc
The reader concurrency semaphore restricts the concurrency of reads that require CPU (intention: they read from the cache) to 1, meaning that if there is even a single active read which declares that it needs just CPU to proceed, no new read is admitted. This is meant to keep the concurrency of reads in the cache at 1. The idea is that concurrency in the cache is not useful: it just leads to the reactor rotating between these reads, all of the finishing later then they could if they were the only active read in the cache.
This was observed to backfire in the case where there reads from a single table are mostly very fast, but on some keys are very slow (hint: collection full of tombstones). In this case the slow read keeps up the fast reads in the queue, increasing the 99th percentile …
=> [Backport 5.4] reader_concurrency_semaphore: make CPU concurrency configurable

service/storage_service.cc, service/storage_service.hh, transport/server.cc, transport/server.hh
this changeset includes two changes:
- service: move storage_service::~storage_service() into .cc
- transport: move the cql_server::~cql_server() into .cc
they intend to address the compile failures when building scylladb with clang-19. clang-19 is more picky when generating the defaulted destructors with incomplete types. but its behavior makes sense regarding to standard compliance. so let's update accordingly.
---
=> transport, service: move definition of destructors into .cc

api/column_family.cc, compaction/compaction_manager.cc, db/virtual_tables.cc, replica/compaction_group.hh, replica/database.hh, replica/table.cc, scylla-gdb.py, test/boost/commitlog_test.cc, test/boost/memtable_test.cc, test/boost/mutation_test.cc, test/lib/sstable_utils.cc, test/lib/sstable_utils.hh, test/perf/perf_fast_forward.cc, test/topology_experimental_raft/test_tablets.py
rwlock was added to protect iterations against concurrent updates to the map.
the updates can happen when allocating a new tablet replica or removing an old one (tablet cleanup).
the rwlock is very problematic because it can result in topology changes blocked, as updating token metadata takes the exclusive lock, which is serialized with table wide ops like split / major / explicit flush (and those can take a long time).
to get rid of the lock, we can copy the storage group map and guard individual groups with a gate (not a problem since map is expected to have a maximum of ~100 elements). so cleanup can close that gate (carefully closed after stopping individual groups such that migrations aren't blocked by long-running ops like major), and ongoing iterations (e.g. triggered by nodetool …
=> replica: remove rwlock for protecting iteration over storage group map

dist/common/scripts/scylla-housekeeping
This reverts https://github.com/scylladb/scylladb/commit/65fbf72ed0f0980381c3307cda5a6d1b1fde2dfb and introduce new version of the patch which fixes SCT breakage after the commit merged.
----
Since Python 3.12, version parsing becomes strict, parse_version() does
not accept the version string like '6.1.0~dev'.
To fix this, we need to pass acceptable version string to parse_version() like
'6.1.0.dev0', which is allowed on Python version scheme.
reference: https://packaging.python.org/en/latest/specifications/version-specifiers/
Fixes https://github.com/scylladb/scylladb/issues/19564
Closes https://github.com/scylladb/scylladb/pull/19572
=> scylla-housekeeping: fix exception on parsing version string v2

sstables/mx/writer.cc, sstables/sstables.cc, test/boost/sstable_3_x_test.cc
There are two schemas associated with a sstable writer:
the sstable's schema (i.e. the schema of the table at the time when the
sstable object was created), and the writer's schema (equal to the schema
of the reader which is feeding into the writer).
It's easy to mix up the two and break something as a result.
The writer's schema is needed to correctly interpret and serialize the data
passing through the writer, and to populate the on-disk metadata about the
on-disk schema.
The sstables's schema is used to configure some parameters for newly created
sstable, such as bloom filter false positive ratio, or compression.
This series fixes the known mixups between the two — when setting up compression,
and when setting up the bloom filters. 
Fixes #16065
The bug is present in all supported …
=> sstables: fix some mixups between the writer's schema and the sstable's schema

service/storage_service.cc, service/storage_service.hh, sstables/sstables.cc, test/boost/memtable_test.cc, test/lib/cql_test_env.cc, test/lib/cql_test_env.hh
Fixes #19753
SSTable file open provides an `io_error_handler` instance which is applied to a file-wrapper to process any IO errors happing during read/write via the handler in `storage_service`, which in turn will effectively disable the node. However, this is not applied to the actual open operation itself, i.e. any exception generated by the file open call itself will instead just escape to caller. 
This PR adds filtering via the `error_handler` to sstable open + makes `storage_service` "isolate" mechanism non-module-static (thus making it testable) and adds tests to check we exhibit the same behaviour in both cases. 
The main motivation for this issue it discussions that secondary level IO issues (i.e. caused by extensions) should trigger the same behaviour as, for example, running out …
=> Apply sstable io error handler to exceptions generated when opening file

service/paxos/paxos_state.hh, service/storage_proxy.cc, test/topology_custom/test_lwt_semaphore.py
Currently the guard does not account correctly for ongoing operation if semaphore acquisition fails. It may signal a semaphore when it is not held.
Should be backported to all supported versions.
=> Fix lwt semaphore guard accounting

configure.py, main.cc, replica/database.cc, replica/database.hh, sstables/index_reader.hh, sstables/sstables.cc, sstables/sstables_manager.cc, sstables/sstables_manager.hh, test/boost/CMakeLists.txt, test/boost/index_reader_test.cc, test/lib/cql_test_env.cc, test/lib/sstable_test_env.hh, test/lib/test_services.cc, tools/schema_loader.cc, tools/scylla-sstable.cc
This PR adds support for aborting index reads from within `index_consume_entry_context::consume_input` when the server is being stopped. The abort source is now propagated down to the `index_consume_entry_context`, making it available for `consume_input` to check if an abort has been requested. If an abort is detected, `consume_input` will throw an exception to stop the index read operation.
=> sstables/index_reader: abort reading during shutdown

sstables/mx/writer.cc, sstables/sstables.cc, sstables/sstables.hh, test/lib/sstable_utils.hh
Pass origin when opening the sstable from the writer and store it in the
sstable object. This will make the origin available for the entire write
path.
=> sstable::open_sstable: pass origin from the writer

db/hints/internal/hint_endpoint_manager.cc, db/hints/manager.cc, db/hints/manager.hh, test/topology_custom/test_hints.py
In 6e79d64, the behavior of `manager::too_many_in_flight_hints_for()`
was accidentally modified. It remained unnoticed for some time
and then fixed. In this commit, we add a test verifying that
the concurrency of hints being written to disk is indeed limited
and the limitations are imposed properly.
Refs scylladb/scylladb#17636
Fixes scylladb/scylladb#17660
=> db/hints: Test `manager::too_many_in_flight_hints_for()`

cql3/functions/functions.cc, cql3/functions/functions.hh, test/lib/cql_test_env.cc
In v4 of https://github.com/scylladb/scylladb/pull/19598 the last commit of the patch was replaced but this change missed merge so submitting it in a separate patch.
In the current patch, the original functions class correctly marks methods as const where appropriate, and the instance() method now returns a const object. This ensures protection against accidental modifications, as all changes must go through the change_batch object.
Since the functions_changer class was intended to serve the same purpose, it is now redundant. Therefore, we are reverting the commit that introduced it.
Relates https://github.com/scylladb/scylladb/issues/19153
=> Improve constness of functions schema code

test/topology_custom/test_raft_recovery_stuck.py
Use the rolling restart to avoid spurious driver reconnects.
This can be eventually reverted once the scylladb/python-driver#295 is fixed.
Fixes scylladb/scylladb#19154
=> test: raft: fix the flaky `test_raft_recovery_stuck`

sstables/storage.cc, sstables/storage.hh, test/boost/sstable_test.cc, test/lib/sstable_utils.hh
`filesystem_storage` methods frequently call `sync_directory()`, for the sake of flushing (sync'ing) a directory. `sync_directory()` always brackets the sync with open and close, and given that most `sync_directory()` calls target the sstable base directory, those repeated opens and closes are considered wasteful. Rework the `filesystem_storage::_dir` member (from a mere pathname) so that it stand for an `opened_directory` object, which keeps the sstable base directory open, for the purpose of repeated sync'ing.
Resolves #2399.
=> keep table directory open for flushing

docs/_ext/utils.py, docs/_templates/db_option.tmpl
before this change, quite a few of the default values are represented in the form of their representations in source code, but this is not user-friendly.
after this change, some of them are updated so that the new representations match with what user finds in `scylla.yaml`. this change is not exhaustive, and there are still cases where the default values are either not readable or still in the form of the expression in C++ source code. but this change establishes a mechinary allowing us to customize the representation on a case-by-case basis.
---
non-critical document improvement, hence no need to backport
=> docs: render default value with user-facing representation

sstables/sstables.cc, sstables/sstables_manager.cc, sstables/sstables_manager.hh, test/boost/bloom_filter_test.cc, test/boost/suite.yaml, test/lib/sstable_test_env.hh
The SSTable is removed from the reclaimed memory tracking logic only
when its object is deleted. However, there is a risk that the Bloom
filter reloader may attempt to reload the SSTable after it has been
unlinked but before the SSTable object is destroyed. Prevent this by
removing the SSTable from the reclaimed list maintained by the manager
as soon as it is unlinked. 
The original logic that updated the memory tracking in
`sstables_manager::deactivate()` is left in place as (a) the variables
have to be updated only when the SSTable object is actually deleted, as
the memory used by the filter is not freed as long as the SSTable is
alive, and (b) the `_reclaimed.erase(*sst)` is still useful during
shutdown, for example, when the SSTable is not unlinked but just
destroyed.
Fixes …
=> sstables: do not reload components of unlinked sstables

db/commitlog/commitlog.cc, db/commitlog/commitlog.hh, db/config.cc, db/config.hh, replica/database.cc, test/boost/commitlog_test.cc
If set, any remaining segment that has data older than this threshold will request flushing, regardless of data pressure. I.e. even a system where nothing happends will after X seconds flush data to free up the commit log.
Related to  #15820
The functionality here is to prevent pathological/test cases where a silent system cannot fully process stuff like compaction, GC etc due to things like CL forcing smaller GC windows etc.
=> commitlog: Add optional max lifetime parameter to cl instance

db/config.cc, test/cql-pytest/test_virtual_tables.py, utils/config_file_impl.hh
When you SELECT a boolean from system.config, it reads as true/false, but this isn't accepted
on UPDATE (instead, we accept 1/0). This is surprising and annoying, so accept true/false in
both directions.
Not a regression, so a backport isn't strictly necessary.
=> config: round-trip boolean configuration variables

test/boost/s3_test.cc, utils/s3/client.cc, utils/s3/client.hh
this member function prepares for the backup feature, where the
object to be stored in the object storage is already persisted as a
file on local filesystem. this brings us two benefits:
- with the file, we don't need to accumulate the payloads in memory
and send them in batch, as we do in upload_sink and in
upload_jumbo_sink. this puts less pressure on the memory subsystem.
- with the file, we can read multiple parts in parallel if multpart
upload applies to it, this helps to improve the throughput.
so, this new helper is introduced to help upload an sstable from local
filesystem to the object storage.
Fixes https://github.com/scylladb/scylladb/issues/16287
=> s3/client: add client::upload_file()

sstables/mx/writer.cc, sstables/sstables.cc, test/boost/sstable_3_x_test.cc
There are two schemas associated with a sstable writer:
the sstable's schema (i.e. the schema of the table at the time when the
sstable object was created), and the writer's schema (equal to the schema
of the reader which is feeding into the writer).
It's easy to mix up the two and break something as a result.
The writer's schema is needed to correctly interpret and serialize the data
passing through the writer, and to populate the on-disk metadata about the
on-disk schema.
The sstables's schema is used to configure some parameters for newly created
sstable, such as bloom filter false positive ratio, or compression.
This series fixes the known mixups between the two — when setting up compression,
and when setting up the bloom filters.
Fixes scylladb/scylladb#16065
The bug is present in …
=> [Backport 5.4] sstables: fix some mixups between the writer's schema and the sstable's schema 

sstables/mx/writer.cc, sstables/sstables.cc, test/boost/sstable_3_x_test.cc
There are two schemas associated with a sstable writer:
the sstable's schema (i.e. the schema of the table at the time when the
sstable object was created), and the writer's schema (equal to the schema
of the reader which is feeding into the writer).
It's easy to mix up the two and break something as a result.
The writer's schema is needed to correctly interpret and serialize the data
passing through the writer, and to populate the on-disk metadata about the
on-disk schema.
The sstables's schema is used to configure some parameters for newly created
sstable, such as bloom filter false positive ratio, or compression.
This series fixes the known mixups between the two — when setting up compression,
and when setting up the bloom filters.
Fixes scylladb/scylladb#16065
The bug is present in …
=> [Backport 6.0] sstables: fix some mixups between the writer's schema and the sstable's schema

auth/common.cc, auth/common.hh, auth/password_authenticator.cc, auth/service.cc, auth/standard_role_manager.cc, service/migration_manager.cc, service/qos/service_level_controller.cc, service/raft/raft_group0_client.cc, service/raft/raft_group0_client.hh, service/raft/raft_group_registry.cc, service/raft/raft_group_registry.hh, service/storage_service.cc, service/topology_coordinator.cc, test/boost/group0_test.cc, test/lib/cql_test_env.cc
Some of the calls inside the `raft_group0_client::start_operation()` method were missing the abort source parameter. This caused the repair test to be stuck in the shutdown phase - the abort source has been triggered, but the operations were not checking it.
This was in particular the case of operations that try to take the ownership of the raft group semaphore (`get_units(semaphore)`) - these waits should be cancelled when the abort source is triggered.
This should fix the following tests that were failing in some percentage of dtest runs (about 1-3 of 100):
* TestRepairAdditional::test_repair_kill_1
* TestRepairAdditional::test_repair_kill_3
Fixes scylladb/scylladb#19223
=> raft: fix the shutdown phase being stuck

locator/load_sketch.hh, service/tablet_allocator.cc, service/tablet_allocator.hh, test/perf/tablet_load_balancing.cc
Tablet load balancer tries to equalize tablet load between shards by
moving tablets. Currently, the tablet load balancer assumes that each
tablet has the same hotness. This may not be true, and some tables may
be hotter than others. If some nodes end up getting more tablets of
the hot table, we can end up with request load imbalance and reduced
performance.
In https://github.com/scylladb/scylladb/commit/79d0711c7e37e34ee28cc4a871da0c3e86bcc559 we implemented a
mitigation for the problem by randomly choosing the table whose tablet
replica should be moved. This should improve fairness of
movement. However, this proved to not be enough to get a good
distribution of tablets.
This change improves candidate selection to not relay on randomness
but rather evaluating candidates with respect to …
=> tablets: load_balancer: Improve per-table balance

db/view/view.cc, db/view/view.hh, test/cql-pytest/test_materialized_view.py, test/cql-pytest/test_shedding.py, test/cql-pytest/util.py, view_info.hh
Currently when a partition is deleted from the base table, we generate a
row tombstone update for each one of the view rows in the partition.
When the partition key in the view is the same as the base, maybe in a
different order, this can be done more efficiently - The whole corresponding
view partition can be deleted with one partition tombstone update.
With this commit, when generating view updates, if the update mutation has a
partition tombstone then for the views which have the same partition key
we will generate a partition tombstone update, and skip the individual
row tombstone updates.
Fixes #8199
=> mv: delete a partition in a single operation when applicable

auth/common.cc, auth/common.hh, auth/default_authorizer.cc, auth/password_authenticator.cc, auth/service.cc, auth/standard_role_manager.cc, service/migration_manager.cc, service/qos/raft_service_level_distributed_data_accessor.cc, service/qos/service_level_controller.cc, service/raft/raft_group0_client.cc, service/raft/raft_group0_client.hh, service/raft/raft_group_registry.cc, service/raft/raft_group_registry.hh, service/storage_service.cc, service/topology_coordinator.cc
Some of the calls inside the raft_group0_client::start_operation() method were missing the abort source parameter. This caused the repair test to be stuck in the shutdown phase - the abort source has been triggered, but the operations were not checking it.
This was in particular the case of operations that try to take the ownership of the raft group semaphore (get_units(semaphore)) - these waits should be cancelled when the abort source is triggered.
This should fix the following tests that were failing in some percentage of dtest runs (about 1-3 of 100):
* TestRepairAdditional::test_repair_kill_1
* TestRepairAdditional::test_repair_kill_3
Fixes #19223
(cherry picked from commit 2dbe9ef2f27c848152e82b2c31ea8c438d530a17)
(cherry picked from commit 5dfc50d35413f541ef02a88bde352f54f3945ceb) …
=> [Backport 6.0] raft: fix the shutdown phase being stuck

db/hints/manager.cc, db/hints/sync_point.cc, db/hints/sync_point.hh, idl/hinted_handoff.idl.hh, test/boost/commitlog_test.cc, test/boost/compound_test.cc, test/boost/config_test.cc, test/boost/expr_test.cc, test/boost/flat_mutation_reader_test.cc, test/boost/hint_test.cc, test/boost/idl_test.cc, test/boost/mutation_query_test.cc, test/boost/mutation_reader_test.cc, test/boost/mutation_test.cc, test/boost/mutation_writer_test.cc, test/boost/nonwrapping_interval_test.cc, test/boost/query_processor_test.cc, test/boost/service_level_controller_test.cc, test/boost/sstable_resharding_test.cc, test/boost/statement_restrictions_test.cc, test/boost/top_k_test.cc, test/boost/transport_test.cc, test/boost/user_function_test.cc, test/boost/view_build_test.cc, test/boost/wrapping_interval_test.cc, test/perf/perf_fast_forward.cc, tools/scylla-sstable.cc, tools/scylla-types.cc
Change the format of sync points to use host ID instead of IPs, to be consistent with the use of host IDs in hinted handoff module.
Introduce sync point v3 format which is the same as v2 except it stores host IDs instead of IPs.
The decoding supports both formats with host IDs and IPs, so a sync point contains now a variant of either types, and in the case of new type the translation is avoided.
Fixes scylladb/scylladb#18653
(cherry picked from commit scylladb/scylladb@b824e73)
(cherry picked from commit scylladb/scylladb@afc9a1a)
(cherry picked from commit scylladb/scylladb@c56de90)
(cherry picked from commit scylladb/scylladb@222dbf2)
In scylladb/scylladb#18733, we were experiencing a test failure
because the test code was receiving the reply `"DONE"` instead of
`"IN_PROGRESS"` when …
=> [Backport 6.0] hinted handoff: migrate sync point to host ID 

replica/database.cc, replica/database.hh, sstables/sstables_manager.cc, sstables/storage.cc, sstables/storage.hh
Commit ad0e6b79 (replica: Remove all_datadir from keyspace config) removed all_datadirs from keyspace config, now it's datadir turn. After this change keyspace no longer references any on-disk directories, only the sstables's storage driver attached to keyspace's tables does.
refs #12707
=> Drop datadir from keyspace::config

replica/database.cc, test/cql-pytest/test_counter.py
rewrite the function as coroutine to make it easier to read and maintain, following lifetime issues we had and fixed in this function.
The second commit adds a test that drops a table while there is a counter update operation ongoing in the table.
The test reproduces issue https://github.com/scylladb/scylla-enterprise/issues/4475 and verifies it is fixed.
Follow-up to https://github.com/scylladb/scylladb/pull/19948
Doesn't require backport because the fix to the issue was already done and backported. This is just cleanup and a test.
=> db: coroutinize do_apply_counter_update

service/migration_manager.cc, service/raft/raft_group0_client.cc, service/raft/raft_group0_client.hh, service/storage_service.cc
Some of the calls inside the raft_group0_client::start_operation() method were missing the abort source parameter. This caused the repair test to be stuck in the shutdown phase - the abort source has been triggered, but the operations were not checking it.
This was in particular the case of operations that try to take the ownership of the raft group semaphore (get_units(semaphore)) - these waits should be cancelled when the abort source is triggered.
This should fix the following tests that were failing in some percentage of dtest runs (about 1-3 of 100):
* TestRepairAdditional::test_repair_kill_1
* TestRepairAdditional::test_repair_kill_3
Fixes #19223
(cherry picked from commit 2dbe9ef2f27c848152e82b2c31ea8c438d530a17)
(cherry picked from commit 5dfc50d35413f541ef02a88bde352f54f3945ceb) …
=> [Backport 5.4] raft: fix the shutdown phase being stuck

db/view/view.cc, db/view/view_builder.hh
It runs in the background and consists of two parts -- async() lambda and following .then()-s. This PR move the background running code into its own method and coroutinizes it in parts. With #19954 merged it finally looks really nice.
=> Coroutinize view_builder::start()

test/boost/sstable_test.cc
This is a followup to #19937, for #19803. See in particular [this comment](https://github.com/scylladb/scylladb/issues/19803#issuecomment-2258371923).
The primary conversion target is coroutines. However, while coroutines are the most convenient style, they are only infrequently usable in this case, for the following reasons:
- Wherever we have a `future::finally()` that calls a cleanup function that returns a future (which must be awaited), we cannot use `co_await`. We can only use `seastar::async()` with `deferred_close` or `defer()`.
- The code passes lots of lambdas, and `co_await` cannot be used in lambdas. First, I tried, and the compiler rejects it; second, a capturing lambda that is a coroutine is a trap [[1]](https://devblogs.microsoft.com/oldnewthing/20211103-00/?p=105870) …
=> convert the rest of `test/boost/sstable_test.cc` to co-routines and seastar::thread

collection_mutation.cc, collection_mutation.hh, mutation/compact_and_expire_result.hh, mutation/mutation_compactor.hh, mutation/mutation_partition.cc, mutation/mutation_partition.hh, querier.cc, querier.hh, test/boost/mutation_test.cc
We have two mechanism to give visibility into reads having to process many tombstones:
* a warning in the logs, triggered if a read processed more the `tombstone_warn_threshold` dead rows/tombstones
* a trace message, which includes stats of the amount of rows in the page, including the amount of live and dead rows as well as tombstones
This series extends this to also include information on cells, so we have visibility into the case where a read has to process an excessive amount of cell tombstones (mainly because of collections).
A log line is now also logged if the amount of dead cells/tombstones in the page exceeds `tombstone_warn_threshold`. The trace message is also extended to contain cell stats.
The `tombstone_warn_threshold` log lines now receive a 10s rate-limit to avoid …
=> querier: include cell stats in page stats

compaction/compaction_manager.cc, compaction/compaction_manager.hh, compaction/task_manager_module.cc, replica/database.hh, replica/table.cc, test/boost/compaction_group_test.cc, test/boost/cql_query_large_test.cc, test/boost/database_test.cc, test/boost/memtable_test.cc, test/boost/sstable_compaction_test.cc, test/boost/view_complex_test.cc, test/perf/perf_fast_forward.cc
If parent_info argument of compaction_manager::perform_compaction
is std::nullopt, then created compaction executor isn't tracked by task 
manager. Currently, all compaction operations should by visible in task 
manager.
Modify split methods to keep split executor in task manager. Get rid of
the option to bypass task manager.
=> compaction: drop compaction executors' possibility to bypass task manager

auth/service.cc, cql3/query_processor.cc, cql3/query_processor.hh, db/schema_tables.cc, locator/load_sketch.hh, locator/tablets.cc, locator/tablets.hh, locator/token_metadata.cc, main.cc, mutation/canonical_mutation.cc, mutation/canonical_mutation.hh, replica/tablets.cc, replica/tablets.hh, service/migration_listener.hh, service/migration_manager.cc, service/raft/group0_state_machine.cc, service/storage_service.cc, service/storage_service.hh, service/tablet_allocator.cc, service/topology_coordinator.cc, test/boost/schema_change_test.cc, test/boost/tablets_test.cc, test/perf/perf_tablets.cc, test/perf/tablet_load_balancing.cc, transport/event_notifier.cc, transport/server.hh
Currently, each change to tablet metadata triggers a full metadata reload from disk. This is very wasteful, especially if the metadata change affects only a single row in the `system.tablets` table. This is the case when the tablet load balancer triggers a migration, this will affect a single row in the table, but today will trigger a full reload.
We expect tablet count to potentially grow to thousands and beyond and the overhead of this full reload can become significant.
This PR makes tablet metadata reload partial, instead of reloading all metadata on topology or schema changes, reload only the partitions that are affected by the change. Copy the rest from the in-memory state.
This is done with two passes: first the change mutations are scanned and a hint is produced. This hint is then …
=> tablets: reload only changed metadata

cell_locking.hh, counters.cc
`maybe_rehash` is complimentary and is not strictly require to succeed. If it fails, it will retry on the next call, but there's no reason to throw an exception that will fail its caller, since `maybe_rehash` is called as the final step after the caller has already succeeded with its action.
Minor enhancement for the error path, no backport required.
=> cell_locker: maybe_rehash: ignore allocation failures

service/topology_coordinator.cc, test/topology_custom/test_tablets_cql.py
ALTER tablets KS executes in 2 steps:
1. ALTER KS's cql handler forms a global topo req, and saves data required to execute this req,
2. global topo req is executed by topo coordinator, which reads data attached to the req.
The KS name is among the data attached to the req. There's a time window between these steps where a to-be-altered KS could have been DROPped, which results in topo coordinator forever trying to ALTER a non-existing KS. In order to avoid it, the code has been changed to first check if a to-be-altered KS exists, and if it's not the case, it doesn't perform any schema/tablets mutations, but just removes the global topo req from the coordinator's queue.
BTW. just adding this extra check resulted in broader than expected changes, which is due to the fact that the code is …
=> Prevent ALTERing non-existing KS with tablets

cql3/selection/selection.cc, cql3/selection/selection.hh, cql3/statements/select_statement.cc, cql3/statements/select_statement.hh, test/cql-pytest/test_distinct.py, test/cql-pytest/test_group_by.py
This change fixes #17237, fixes #5361 and fixes #5362 by passing the limit value down the call chain in cql3. A test is also added.
fixes #17237
fixes #5361
fixes #5362
The regression happened in 5.4 as we changed the way GROUP BY is processed in 432cb02 - to force aggregation when it is used. The LIMIT value was not passed to aggregations and thus we failed to adhere to it.
W want to backport this fix to 5.4 and 6.0 to have continuous correct results for the test case from #17237
This patch consists of 4 commits:
- fa4225ea0fac2057b7a9976f57dc06bcbd900cd4 - cql3: respect the user-defined page size in aggregate queries - a precondition for this patch to be implementable
- 8fbe69e74dca16ed8832d9a90489ca47ba271d0b - cql3/select_statement: simplify the get_limit function - the …
=> cql: process LIMIT for GROUP BY select queries

test/nodetool/conftest.py
before this change, we assume user runs nodetool tests right under the root source directory. if user runs them under `test/nodetool`, the suppression rules are not applied. as the path is incorrect in that case.
after this change, the supression rules' path is deduced from the top src directory. so we can now run the nodetool test under `test/nodetool` .
---
no need to backport, this change improves developer's experience.
=> test/nodetool: enable running nodetool tests under test/nodetool

api/column_family.cc, compaction/compaction_manager.cc, db/virtual_tables.cc, replica/compaction_group.hh, replica/database.hh, replica/table.cc, scylla-gdb.py, test/boost/commitlog_test.cc, test/boost/memtable_test.cc, test/boost/mutation_test.cc, test/lib/sstable_utils.cc, test/lib/sstable_utils.hh, test/perf/perf_fast_forward.cc, test/topology_experimental_raft/test_tablets.py
rwlock was added to protect iterations against concurrent updates to the map.
the updates can happen when allocating a new tablet replica or removing an old one (tablet cleanup).
the rwlock is very problematic because it can result in topology changes blocked, as updating token metadata takes the exclusive lock, which is serialized with table wide ops like split / major / explicit flush (and those can take a long time).
to get rid of the lock, we can copy the storage group map and guard individual groups with a gate (not a problem since map is expected to have a maximum of ~100 elements). so cleanup can close that gate (carefully closed after stopping individual groups such that migrations aren't blocked by long-running ops like major), and ongoing iterations (e.g. triggered by nodetool …
=> [Backport 6.0] replica: remove rwlock for protecting iteration over storage group map

replica/tablets.cc, test/boost/sstable_set_test.cc, test/boost/sstable_test.hh
Commit https://github.com/scylladb/scylladb/commit/9f93dd9fa3376cfe560c65fb9c9c938ff1d3f99d changed `tablet_sstable_set::_sstable_sets` to be a `absl::flat_hash_map` and in addition, `std::set<size_t> _sstable_set_ids` was added. `_sstable_set_ids` is set up in the `tablet_sstable_set(schema_ptr s, const storage_group_manager& sgm, const locator::tablet_map& tmap)` constructor, but it is not copied in `tablet_sstable_set(const tablet_sstable_set& o)`. 
This affects the `tablet_sstable_set::tablet_sstable_set` method as it depends on the copy constructor. Since sstable set can be cloned when a new sstable set is added, the issue will cause ids not being copied into the new sstable set. It's healed only after compaction, since the sstable set is rebuilt from scratch there.
This PR fixes …
=> replica: fix copy constructor of tablet_sstable_set

compaction/compaction_manager.cc, compaction/compaction_manager.hh, replica/compaction_group.hh, replica/database.hh, replica/table.cc, service/topology_coordinator.cc, test/boost/sstable_compaction_test.cc, test/topology_experimental_raft/test_tablets.py
Consider the following:
```
T
0   split prepare starts
1                               repair starts
2   split prepare finishes
3                               repair adds unsplit sstables
4                               repair ends
5   split executes
```
If repair produces sstable after split prepare phase, the replica will not split that sstable later, as prepare phase is considered completed already. That causes split execution to fail as replicas weren't really prepared. This also can be triggered with load-and-stream which shares the same write (consumer) path.
The approach to fix this is the same employed to prevent a race between split and migration. If migration happens during prepare phase, it can happen source misses the split request, but the tablet will still be split on the …
=> tablets: Fix race between repair and split

alternator/executor.cc, alternator/server.cc, alternator/server.hh, alternator/streams.cc, alternator/ttl.cc, docs/alternator/compatibility.md, docs/alternator/getting-started.md, test/alternator/test_batch.py, test/alternator/test_cql_rbac.py, test/cql-pytest/run.py, test/pylib/manager_client.py, test/topology_experimental_raft/test_alternator.py
Alternator already supports **authentication** - the ability to to sign each request as a particular user. The users that can be used are the different "roles" that are created by CQL "CREATE ROLE" commands. This series adds support for **authorization**, i.e., the ability to determine that only some of these roles are allowed to read or write particular tables, to create new tables, and so on.
The way we chose to do this in this series is to support CQL's existing role-based access control (RBAC) commands - GRANT and REVOKE - on Alternator tables. For example, an Alternator table "xyz" is visible to CQL as "alternator_xyz.xyz", so a `GRANT SELECT ON alternator_xyz.xyz TO myrole` will allow read commands (e.g., GetItem) on that table, and without this GRANT, a GetItem will fail with …
=> Add CQL-based RBAC support to Alternator

db/system_keyspace.cc, db/system_keyspace.hh, gms/gossiper.cc, gms/gossiper.hh, raft/fsm.cc, raft/log.cc, raft/log.hh, raft/server.cc, raft/tracker.cc, service/raft/raft_sys_table_storage.cc, service/storage_service.cc, test/raft/etcd_test.cc, test/raft/fsm_test.cc, test/raft/helpers.cc, test/raft/helpers.hh, test/raft/randomized_nemesis_test.cc, test/raft/replication.cc, test/raft/replication.hh, utils/tagged_integer.hh
~~~
utils/tagged_integer: remove conversion to underlying integer
Silently converting a tagged (i.e., "dimension-ful") integer to a naked
("dimensionless") integer defeats the purpose of having tagged integers,
and is a source of practical bugs, such as
<https://github.com/scylladb/scylladb/issues/20080>.
We could make the conversion operator explicit, for enforcing
static_cast<TAGGED_INTEGER_TYPE::value_type>(TAGGED_INTEGER_VALUE)
in every conversion location -- but that's a mouthful to write. Instead,
remove the conversion operator, and let clients call the (identically
behaving) value() member function.
~~~
No backport needed (refactoring).
The series is supposed to solve #20081.
Two patches in the series touch up code that is known to be (orthogonally) buggy; see
- …
=> utils/tagged_integer: remove conversion to underlying integer

test.py
before this change, we check for the existence of "TestSuite" node
under the root of XML tree, and then enumerating all "TestSuite" nodes
under this "TestSuite", this approach works. but it
* introduces unnecessary indent
* is not very readable
in this change, we just use "./TestSuite/TestSuite" for enumerating
all "TestSuite" nodes under "TestSuite". simpler this way.
---
it's a cleanup in the test driver script, hence no need to backport.
=> test.py: use XPath for iterating in "TestSuite/TestSuite"

configure.py, docs/operating-scylla/admin-tools/scylla-sstable.rst, replica/tablets.cc, replica/tablets.hh, test/cql-pytest/test_tools.py, tools/CMakeLists.txt, tools/load_system_tablets.cc, tools/load_system_tablets.hh, tools/read_mutation.cc, tools/read_mutation.hh, tools/schema_loader.cc, tools/scylla-sstable.cc
before this change, `scylla sstable shard-of` didn't support tablets,
because:
- with tablets enabled, data distribution uses the scheduler
- this replaces the previous method of mapping based on vnodes and shard numbers
- as a result, we can no longer deduce sstable mapping from token ranges
in this change, we:
- read `system.tablets` table to retrieve tablet information
- print the tablet's replica set (list of <host, shard> pairs)
- this helps users determine where a given sstable is hosted
This approach provides the closest equivalent functionality of
`shard-of` in the tablet era.
Fixes scylladb/scylladb#16488
---
no need to backport, it's an improvement, not a critical fix.
=> tools: Enhance scylla sstable shard-of to support tablets

api/api-doc/storage_service.json, api/storage_service.cc, docs/operating-scylla/nodetool-commands/rebuild.rst, repair/repair.cc, repair/repair.hh, repair/row_level.hh, service/storage_service.cc, service/storage_service.hh, test/nodetool/test_rebuild.py, tools/scylla-nodetool.cc, utils/to_string.cc, utils/user_provided_param.hh
It is unsafe to restrict the sync nodes for repair to the source data center if it has too low replication factor in network_topology_replication_strategy, or if other nodes in that DC are ignored.
Also, this change restricts the usage of source_dc to `network_topology` and `everywhere_topology`
strategies, as with simple replication strategy
there is no guarantee that there would be any
more replicas in that data center.
Fixes #16826
Reproducer submitted as https://github.com/scylladb/scylla-dtest/pull/3865
It fails without this fix and passes with it.
* Requires backport to live versions.  Issue hit in the filed with 2022.2.14
=> repair: do_rebuild_replace_with_repair: use source_dc only when safe

test/boost/s3_test.cc, utils/s3/client.cc, utils/s3/client.hh
This is prerequisite for "restore from object storage" feature. In order to collect the sstables in bucket one would need to list the bucket contents with the given prefix. The ListObjectsV2 provides a way for it and here's the respective s3::client extension.
=> Add ability to list S3 bucket contents

table_helper.cc, table_helper.hh
table_helper has some quite awkward code, improve it a little.
Code cleanup, so no reason to backport.
=> table_helper: complete coroutinization

alternator/ttl.cc, compaction/task_manager_module.cc, locator/abstract_replication_strategy.cc, locator/abstract_replication_strategy.hh, locator/tablets.cc, repair/repair.cc, replica/database.cc, replica/database.hh, replica/distributed_loader.cc, service/storage_service.cc, service/storage_service.hh, test/boost/database_test.cc, test/boost/network_topology_strategy_test.cc, test/boost/sstable_compaction_test.cc, test/boost/sstable_directory_test.cc
To prevent stalls due to large number of tokens.
For example, large cluster with say 70 nodes can have
more than 16K tokens.
Fixes #19757
=> abstract_replication_strategy: make get_ranges async

test/boost/estimated_histogram_test.cc, utils/histogram.hh
This series fixes an issue where histogram Summaries return an infinite value.
It updated the quantile calculation logic to address cases where values fall into the infinite bucket of a histogram. 
Now, instead of returning infinite (max int), the calculation will return the last bucket limit, ensuring finite outputs in all cases.
The series adds a test for summaries with a specific test case for this scenario.
Fixes #20255
Need backport to 6.0, 6.1 and 2023.1 and above
=> Make Summary support histogram with infinite bucket vlaues

db/view/node_view_update_backlog.hh, db/view/view_update_backlog.hh, exceptions/coordinator_result.hh, service/storage_proxy.cc, service/storage_proxy.hh, test/topology_custom/test_mv_admission_control.py, test/topology_custom/test_mv_backlog.py
Currently, when a view update backlog of one replica is full, the write is still sent by the coordinator to all replicas. Because of the backlog, the write fails on the replica, causing inconsistency that needs to be fixed by repair. To avoid these inconsistencies, this patch adds a check on the coordinator for overloaded replicas. As a result, a write may be rejected before being sent to any replicas and later retried by the user, when the replica is no longer overloaded.
This patch does not remove the replica write failures, because we still may reach a full backlog when more view updates are generated after the coordinator check is performed and before the write reaches the replica.
Fixes https://github.com/scylladb/scylladb/issues/17426
=> mv: reject user requests by coordinator when a replica is overloaded by MVs

tools/testing/dist-check/dist-check.sh, tools/testing/dist-check/docker.io/rockylinux-9.sh, tools/testing/dist-check/docker.io/util.sh
`dist-check` tests the generated rpm packages by installing them in a centos 7 container. but this script is terribly outdated
- centos 7 is deprecated. we should use a new distro's latest stable release.
- cqlsh was added to the family of rpms a while ago. we should test it as well.
- the directory hierarchy has been changed. we should read the artifacts from the new directories. 
- cmake uses a different directory hierarchy. we should check the directory used by cmake as well.
to address these breaking changes, the scripts are updated accordingly.
---
this change gives an overhaul to a test, which is not used in production. so no need to backport.
=> tools/testing: update dist-check to use rockylinux and adapt to cmake

cql3/statements/select_statement.cc, cql3/statements/select_statement.hh, replica/mutation_dump.cc, replica/mutation_dump.hh, test/topology_custom/test_tablets.py
Attempting to read a partition via `SELECT * FROM MUTATION_FRAGMENTS()`, which the node doesn't own, from a table using tablets causes a crash.
This is because when using tablets, the replica side simply doesn't handle requests for un-owned tokens and this triggers a crash.
We should probably improve how this is handled (an exception is better than a crash), but this is outside the scope of this PR.
This PR fixes this and also adds a reproducer test.
Fixes: https://github.com/scylladb/scylladb/issues/18786
Fixes a regression introduced in 6.0, so needs backport to 6.0 and 6.1
=> select from mutation_fragments() + tablets: handle reads for non-owned partitions

alternator/executor.cc, test/alternator/test_query.py
When executing reversed queries, a native revered format shall be used. Therefore, the table schema and the clustering key bounds are reversed before a partition slice and a read command are constructed.
It is, however, possible to run a reversed query passing a table schema but only when there are no restrictions on the clustering keys. In this particular situation, the query returns correct results. Since the current alternator tests in test.py do not imply any restrictions, this situation was not caught during development of https://github.com/scylladb/scylladb/pull/18864.
Hence, additional tests are provided that add clustering keys restrictions when executing reversed queries to capture such errors earlier than in dtests.
Additional manual tests were performed to test a mixed-node …
=> alternator/executor: Use native reversed format

configure.py
as part of the efforts to address scylladb/scylladb#2717, we are
switching over to the CMake-based building system, and fade out the
mechinary to create the rules manually in `configure.py`.
in this change, we add `--no-use-cmake` to `configure.py`, it serves
two purposes:
* prepare for the change which enables cmake by default, by then,
we would set the default value of `use_cmake` to True, and allow
user to keep using the existing mechinary in the transition period
using `--no-use-cmake`.
* allows the CI to tell if a tree is able to build with CMake.
the command line option of `--use-cmake` is also used by the CI
workflows, and is passed to `configure.py` if `BUILD_WITH_CMAKE`
jenkins pipeline parameter is set. but not all branches with
`--use-cmake` are ready to build with CMake -- …
=> build: add --no-use-cmake option to configure.py

api/api-doc/storage_service.json, api/storage_service.cc, dist/common/nodetool-completion, docs/operating-scylla/nodetool-commands/restore.rst, docs/operating-scylla/nodetool.rst, main.cc, replica/distributed_loader.cc, replica/distributed_loader.hh, sstables/sstable_directory.cc, sstables/sstable_directory.hh, sstables/storage.cc, sstables_loader.cc, sstables_loader.hh, test/boost/s3_test.cc, test/nodetool/test_restore.py, test/object_store/test_backup.py, test/pylib/rest_client.py, tools/scylla-nodetool.cc, utils/lister.hh, utils/s3/client.cc, utils/s3/client.hh
Handed over from https://github.com/scylladb/scylladb/pull/20149
This adds minimal implementation of the start-restore API call.
The method starts a task that runs load-and-stream functionality against sstables from S3 bucket. Arguments are:
```
endpoint -- the ID in object_store.yaml config file
bucket -- the target bucket to get objects from
keyspace -- the keyspace to work on
table -- the table to work on
snapshot -- the name of the snapshot from which the backup was taken
```
The task runs in the background, its task_id is returned from the method once it's spawned and it should be used via /task_manager API to track the task execution and completion.
Remote sstables components are scanned as if they were placed in local upload/ directory. Then colelcted sstables are fed into …
=> Integrated restore

api/api-doc/task_manager.json, api/task_manager.cc, docs/dev/task_manager.md, docs/operating-scylla/nodetool-commands/tasks/abort.rst, docs/operating-scylla/nodetool-commands/tasks/index.rst, docs/operating-scylla/nodetool-commands/tasks/list.rst, docs/operating-scylla/nodetool-commands/tasks/modules.rst, docs/operating-scylla/nodetool-commands/tasks/status.rst, docs/operating-scylla/nodetool-commands/tasks/tree.rst, docs/operating-scylla/nodetool-commands/tasks/ttl.rst, docs/operating-scylla/nodetool-commands/tasks/wait.rst, docs/operating-scylla/nodetool.rst, tasks/task_handler.cc, tasks/task_handler.hh, test/nodetool/conftest.py, test/nodetool/test_help.py, test/nodetool/test_tasks.py, test/rest_api/test_task_manager.py, test/topology_tasks/test_node_ops_tasks.py, tools/scylla-nodetool.cc, tools/utils.cc, tools/utils.hh
Add nodetool commands to manage task manager tasks:
- tasks abort - aborts the task
- tasks list - lists all tasks in the module
- tasks modules - lists all modules
- tasks set-ttl - sets task ttl
- tasks status - gets status of the task
- tasks tree - gets statuses of the task and all its desendent's
- tasks ttl - gets task ttl
- tasks wait - waits for the task and gets its status
Fixes: https://github.com/scylladb/scylladb/issues/19201.
=> nodetool: tasks: add nodetool commands to track task manager tasks

db/hints/internal/hint_endpoint_manager.cc, db/hints/internal/hint_endpoint_manager.hh
In scylladb/scylladb@7301a96, in the function `hint_endpoint_manager::store_hint()`,
we transformed the lambda passed to `seastar::with_gate()` to a coroutine lambda
to improve the readability. However, there was a subtle problem related to
lifetimes of the captures that needed to be addressed:
* Since we started `co_await`ing in the lambda, the captures were at risk of
being destructed too soon. The usual solution is to wrap a coroutine lambda
within a `seastar::coroutine::lambda` object and rely on the extended lifetime
enforced by the semantics of the language.
See `docs/dev/lambda-coroutine-fiasco.md` for more context.
* However, since we don't immediately `co_await` the future returned by
`with_gate()`, we cannot rely on the extended lifetime provided by the wrapper.
The document …
=> db/hints: Move the code for writing hints to a separate function

repair/row_level.cc, test/topology_custom/test_repair.py
repair_service::repair_flush_hints_batchlog_handler may access batchlog
manager while it is uninitialized.
Throw if batchlog manager isn't initialized.
Fixes:  #20236.
Needs backport to 6.0 and 6.1 as they suffer from the uninitialized bm access.
=> repair: throw if batchlog manager isn't initialized

init.cc, init.hh, main.cc, test/topology/test_start_bootstrapped_with_invalid_seed.py
All seeds hostname resolution errors will be ignored during a node restart in case the node had already joined a cluster.  This will prevent restart errors if some seed names are not resolvable.
Fixes scylladb/scylladb#14945
=> Ignore seed name resolution errors during the restart of a cluster member node.

test/perf/perf_sstable.cc, test/perf/perf_sstable.hh
for testing the load performance of load_and_stream operation.
Refs #19989
---
no need to backport. it adds two new tests to the existing `perf_sstable` tool for evaluating the load performance when performing the "load_and_streaming" operation. hence has no impact on the production.
=> perf/perf_sstable: add {crawling,partitioned}_streaming modes

scylla-gdb.py, test/scylla_gdb/conftest.py, test/scylla_gdb/pytest.ini, test/scylla_gdb/run, test/scylla_gdb/test_misc.py
instead of evaluating the constants in-class, accessing them via
a cached class property.
it would be handy if we could source `scylla-gdb.py` in `.gdbinit`,
but this script accesses some symbols which are not available without
a file being debugged. what's why gdb fails to load the init script:
```
Traceback (most recent call last):
File "/home/kefu/dev/scylladb/scylla-gdb.py", line 167, in <module>
class intrusive_slist:
File "/home/kefu/dev/scylladb/scylla-gdb.py", line 168, in intrusive_slist
size_t = gdb.lookup_type('size_t')
^^^^^^^^^^^^^^^^^^^^^^^^^
gdb.error: No type named size_t.
```
so we have to `file path/to/scylla` and *then*
`source scylla-gdb.py` every time when we debug scylla or a seastar
application, instead of loading `scylla-gdb.py` in `.gdbinit`.
the reason is that …
=> scylla-gdb.py: lazy-evaluate the constants 

auth/common.cc, cql3/Cql.g, cql3/cql3_type.cc, cql3/dialect.hh, cql3/prepared_statements_cache.hh, cql3/query_processor.cc, cql3/query_processor.hh, cql3/statements/alter_table_statement.cc, cql3/statements/select_statement.cc, cql3/util.cc, cql3/util.hh, db/config.cc, db/config.hh, db/cql_type_parser.cc, db/schema_tables.cc, docs/cql/cql-extensions.md, table_helper.cc, table_helper.hh, test/boost/cql_auth_syntax_test.cc, test/boost/cql_query_test.cc, test/boost/expr_test.cc, test/boost/statement_restrictions_test.cc, test/cql-pytest/test_prepare.py, test/lib/cql_test_env.cc, tools/schema_loader.cc, transport/server.cc, transport/server.hh
Bind variables in CQL have two formats: positional (`?`) where a variable is referred to by its relative position in the statement, and named (`:var`), where the user is expected to supply a name->value mapping.
In 19a6e69001f26 we identified the case where a named bind variable appears twice in a query, and collapsed it to a single entry in the statement metadata. Without this, a driver using the named variable syntax cannot disambiguate which variable is referred to.
However, it turns out that users can use the positional call form even with the named variable syntax, by using the positional API of the driver. To support this use case, we add a configuration variable to disable the same-variable detection.
Because the detection has to happen when the entire statement is visible, we have …
=> cql3: add option to not unify bind variables with the same name

test/nodetool/test_backup.py, test/nodetool/test_restore.py, tools/scylla-nodetool.cc
this change contains two improvements to "backup" and "restore" commands:
- let them print task id
- let them return 1 as the exist status code upon operation failure
----
these changes are improvements to the newly introduced commands, which are not in any LTS branches yet, so no need to backport.
=> tools/nodetool: improve backup and restore commands

repair/row_level.cc
This series coroutinizes up some functions in repair/row_level.cc. This enhances
readability and reduces bloat:
```
size  build/release/repair/row_level.o.{before,after}
text	   data	    bss	    dec	    hex	filename
1650619	     48	    524	1651191	 1931f7	build/release/repair/row_level.o.before
1604610	     48	    524	1605182	 187e3e	build/release/repair/row_level.o.after
```
46kB of text were saved.
Functions that only touch a single mutation fragment were not coroutinized to avoid
adding a allocation in a fast path. In one case a function was split into a fast path and a
slow path.
Clean-up series, backport not needed.
=> repair: row_level: coroutinize some slow-path functions

test/boost/sstable_mutation_test.cc, test/lib/sstable_test_env.hh, test/lib/test_services.cc
Tests that try to access sstables from test/resource/ typically sstable::load() it after object creation. There's reusable_sst() helper for that. This PR fixes one more caller that still goes longer route by doing sstable and loading it on its own.
=> Reuse sstable::test_env::reusable_sst() helper for pre-exsting sstables

gms/gossiper.cc, main.cc, service/raft/raft_group0.cc, service/storage_service.cc, service/topology_coordinator.cc, test/pylib/internal_types.py, test/pylib/manager_client.py, test/pylib/random_tables.py, test/pylib/scylla_cluster.py, test/topology/util.py, test/topology_random_failures/cluster_events.py, test/topology_random_failures/conftest.py, test/topology_random_failures/error_injections.py, test/topology_random_failures/pytest.ini, test/topology_random_failures/suite.yaml, test/topology_random_failures/test_random_failures.py
The idea of the test is to have a cluster where one node is stressed with injections and failures and the rest of the cluster is used to make progress of the raft state machine.
To achieve this following two lists introduced in the PR:
- ERROR_INJECTIONS in error_injections.py
- CLUSTER_EVENTS in cluster_events.py
Each cluster event is an async generator which has 2 yields and should be used in the following way:
0. Start the generator:
```python
>>> cluster_event_steps = cluster_event(manager, random_tables, error_injection)
```
1. Run the prepare part (before the first yield)
```python
>>> await anext(cluster_event_steps)
```
2.  Run the cluster event itself (between the yields)
```python
>>> await anext(cluster_event_steps)
```
3. Run the check part (after the second yield)
```python …
```
=> test: randomized failure injection for Raft-based topology

service/qos/service_level_controller.cc, service/qos/service_level_controller.hh
The `service_level::marked_for_deletion` field is always set to `false`. It might have served some purpose in the past, but now it can be just removed, simplifying the code and eliminating confusion about the field.
This is just code cleanup, no backport is needed.
=> service/qos: remove unused marked_for_deletion field from service_level struct

sstables/sstables.cc
Shorter and simpler this way. Hopefully it doesn't sit on critical paths
=> Coroutinize sstable::read_summary() method

repair/row_level.cc, test/topology_custom/test_repair.py
repair_service::repair_flush_hints_batchlog_handler may access batchlog
manager while it is uninitialized.
Throw if batchlog manager isn't initialized.
Fixes: https://github.com/scylladb/scylladb/issues/20236.
Needs backport to 6.0 and 6.1 as they suffer from the uninitialized bm access.
(cherry picked from commit https://github.com/scylladb/scylladb/commit/d8e43934185c46f67cc984d3765cc23b6c85e02a)
(cherry picked from commit https://github.com/scylladb/scylladb/commit/f38bb6483a15119312f5785b798453ff221ccc20)
Refs https://github.com/scylladb/scylladb/pull/20251
=> [Backport 6.0] repair: throw if batchlog manager isn't initialized

test.py, test/pylib/report_plugin.py
To enhance the test reports UX:
1. switching off/on passed/failed/skipped test for better visibility 
2. better searching in test results
3. understanding the trends of execution for each test
4. better configurability of the final report
Enable allure adapter for all python tests.
Add tags and parameters to the test to be able to distinguish them across modes and runs.
Related: https://github.com/scylladb/qa-tasks/issues/1665
Related: https://github.com/scylladb/scylladb/pull/19335
Related: https://github.com/scylladb/scylladb/pull/18169
=> [test.py] Enable allure for python test

sstables/sstable_directory.cc, utils/lister.hh
The yielding lister is considered to be better replacement that scan_dir(lambda) one.
Also, the sstable directory will be patched to scan the contents of S3 bucket and yielding lister fits better for generalization.
=> Use yielding directory lister in sstable_directory

docs/dev/docker-hub.md
~~~
What we have today in "docs/dev/docker-hub.md" on "aio-max-nr" dates back
to scylla commit f4412029f414 ("docs/docker-hub.md: add quickstart section
with --smp 1", 2020-09-22). Problems with the current language:
- The "65K" claim as default value on non-production systems is wrong;
"fs/aio.c" in Linux initializes "aio_max_nr" to 0x10000, which is 64K.
- The section in question uses equal signs (=) incorrectly. The intent was
probably to say "which means the same as", but that's not what equality
means.
- In the same section, the relational operator "<" is bogus. The available
AIO count must be at least as high (>=) as the requested AIO count.
- Clearer names should be used;
adjust_max_networking_aio_io_control_blocks() in "src/core/reactor.cc"
sets a great example:
- …
=> docs/dev/docker-hub.md: refresh aio-max-nr calculation

api/api-doc/column_family.json, api/api-doc/storage_service.json, api/column_family.cc, api/storage_service.cc, compaction/compaction.cc, compaction/compaction_descriptor.hh, compaction/compaction_manager.cc, compaction/compaction_manager.hh, compaction/task_manager_module.cc, compaction/task_manager_module.hh, replica/database.hh, replica/table.cc, test/pylib/rest_client.py, test/topology_custom/test_major_compaction.py, tombstone_gc.hh, tools/scylla-nodetool.cc
Any expired tombstone can be garbage collected if it doesn't shadow data in the commit log, memtable, or uncompacting SSTables.
This PR introduces a new mode to major compaction, enabled by the `consider_only_existing_data` flag that bypasses these checks. When enabled, memtables and old commitlog segments are cleared with a system-wide flush and all the sstables (after flush) are included in the compaction, so that it works with all data generated up to a given time point.
This new mode works with the assumption that newly written data will not be shadowed by expired tombstones. So it ignores new sstables (and new data written to memtable) created after compaction started. Since there was a system wide flush, commitlog checks can also be skipped when garbage collecting tombstones. …
=> major compaction: check only sstables being compacted for tombstone garbage collection

db/hints/internal/hint_sender.cc, db/hints/internal/hint_sender.hh, service/topology_coordinator.cc, test/topology/util.py, test/topology_custom/test_hints.py, test/topology_experimental_raft/test_mv_tablets_replace.py
Currently, when attempting to send a hint, we might choose its recipients in one of two ways:
- If the original destination is a natural endpoint of the hint, we only send the hint to that node and none other,
- Otherwise, we send the hint to all current replicas of the mutation.
There is a problem when we decommission a node: while data is streamed away from that node, it is still considered to be a natural endpoint of the data that it used to own. Because of that, it might happen that a hint is sent directly to it but streaming will miss it, effectively resulting in the hint being discarded.
As sending the hint _only_ to the leaving replica is a rather bad idea, send the hint to all replicas also in the case when the original destination of the hint is leaving.
Note that this is a …
=> hints: send hints with CL=ALL if target is leaving

db/commitlog/commitlog.cc, db/commitlog/commitlog.hh, db/commitlog/commitlog_entry.hh, db/commitlog/commitlog_replayer.cc, db/config.cc, db/config.hh, docs/dev/commitlog-file-format.md, gms/feature_service.cc, gms/feature_service.hh, replica/database.cc, test/boost/commitlog_test.cc
Refs #18161
Yet another approach to dealing with large commitlog submissions.
We handle oversize single mutation by adding yet another entry
typo: fragmented. In this case we only add a fragment (aha) of
the data that needs storing into each entry, along with metadata
to correlate and reconstruct the full entry on replay.
Because these fragmented entries are spread over N segments, we
also need to add references from the first segment in a chain
to the subsequent ones. These are released once we clear the
relevant cf_id count in the base.
*
This approach has the downside that due to how serialization etc
works w.r.t. mutations, we need to create an intermediate buffer
to hold the full serialized target entry. This is then incrementally
written into entries of < max_mutation_size, …
=> commitlog: Handle oversized entries

alternator/executor.cc, alternator/serialization.cc, db/view/view.cc, test/alternator/test_batch.py, test/alternator/test_gsi.py, test/alternator/test_item.py, test/alternator/util.py
This series prepares us for working on #11567 -  allow adding a GSI to a pre-existing table. This will require changing the implementation of GSIs in Alternator to not use real columns in the schema for the materialized view, and instead of a computed column - a function which extracts the desired member from the `:attrs` map and de-serializes it.
This series does not contain the GSI re-implementation itself. Rather it contains a few small cleanups and mostly - new regression tests that cover this area, of adding and removing a GSI, and **using** a GSI, in more details than the tests we already had. I developed most of these tests while working on **buggy** fixes for #11567; The bugs in those implementations were exposed by the tests added here - they exposed bugs both in the new feature …
=> Alternator: tests and other preparation towards allowing adding a GSI to an existing table

test/boost/sstable_compaction_test.cc
This includes
- coroutinization
- elimination of unused overload
=> Sanitize open_sstables() helper in compaction test

db/system_distributed_keyspace.cc, db/system_keyspace.cc, db/system_keyspace.hh, db/view/view.cc, db/view/view_builder.hh, gms/feature_service.hh, main.cc, replica/database.cc, replica/database.hh, service/storage_service.cc, service/topology_coordinator.cc, service/topology_coordinator.hh, test/lib/cql_test_env.cc, test/pylib/util.py, test/topology_custom/test_view_build_status.py
Migrate the `system_distributed.view_build_status` table to `system.view_build_status_v2`. The writes to the v2 table are done via raft group0 operations.
The new parameter `view_builder_version` stored in `scylla_local` indicates whether nodes should use the old or the new table.
New clusters use v2. Otherwise, the migration to v2 is initiated by the topology coordinator when the feature is enabled. It reads all the rows from the old table and writes them to the new table, and sets `view_builder_version` to v2. When the change is applied, all view_builder services are updated to write and read from the v2 table.
The old table `system_distributed.view_build_status` is set to read virtually from the new table in order to maintain compatibility.
When removing a node from the cluster, we …
=> view: move view_build_status to group0

repair/row_level.cc
Coroutinize more functions in row-level repair to improve maintainability.
The functions all deal with repair buffers, so coroutinization does not affect performance.
Cleanup, no reason to backport
=> repair: row_level: coroutinize more functions

docs/alternator/alternator.md, docs/index.rst
This PR hides the ToC on the Alternator page, as we don't need it, especially at the end of the page.
The ToC must be hidden rather than removed because removing it would, in turn, remove the "Getting Started With ScyllaDB Alternator" and "ScyllaDB Alternator for DynamoDB users" from the page tree and make them inaccessible.
In addition, this PR moves Alternator higher in the page tree.
Fixes https://github.com/scylladb/scylladb/issues/19823
=> doc: move Alternator in the page tree and remove it's redundant ToC

schema/schema.cc, schema/schema.hh, test/boost/broken_sstable_test.cc, test/boost/mutation_test.cc, test/boost/sstable_compaction_test.cc, test/boost/sstable_datafile_test.cc, test/boost/sstable_directory_test.cc, test/boost/sstable_mutation_test.cc, test/boost/sstable_test.cc, test/boost/sstable_test.hh, test/boost/view_build_test.cc, test/perf/perf_sstable.hh
This function was obsoleted by schema_builder some time ago. Not to patch all its callers, that helper became wrapper around it. Remained users are all in tests, and patching the to use builder directory makes the code shorter in many cases.
=> Remove make_shared_schema() helper

db/hints/internal/hint_sender.cc, db/hints/internal/hint_sender.hh
Currently, when attempting to send a hint, we might choose its recipients in one of two ways:
- If the original destination is a natural endpoint of the hint, we only send the hint to that node and none other,
- Otherwise, we send the hint to all current replicas of the mutation.
There is a problem when we decommission a node: while data is streamed away from that node, it is still considered to be a natural endpoint of the data that it used to own. Because of that, it might happen that a hint is sent directly to it but streaming will miss it, effectively resulting in the hint being discarded.
As sending the hint _only_ to the leaving replica is a rather bad idea, send the hint to all replicas also in the case when the original destination of the hint is leaving.
Note that this is a …
=> [Backport 6.1]: hints: send hints with CL=ALL if target is leaving

test/boost/sstable_mutation_test.cc
This test runs all its cases in seastar thread, but still uses .then() continuations in some of them.
This PR converts all continuations into plain .get()-s.
=> Make use of async() context in sstable_mutation_test

replica/compaction_group.hh, replica/table.cc, test/boost/tablets_test.cc
Cleanup of a deallocated tablet throws an exception. 
Since failed cleanup is retried, we end up in an infinite loop.
Ignore cleanup of deallocated storage groups.
Fixes:  #19752.
Needs to be backported to all branches with tablets (6.0 and later)
=> replica: ignore cleanup of deallocated storage group

db/hints/internal/hint_sender.cc, db/hints/internal/hint_sender.hh
Currently, when attempting to send a hint, we might choose its recipients in one of two ways:
- If the original destination is a natural endpoint of the hint, we only send the hint to that node and none other,
- Otherwise, we send the hint to all current replicas of the mutation.
There is a problem when we decommission a node: while data is streamed away from that node, it is still considered to be a natural endpoint of the data that it used to own. Because of that, it might happen that a hint is sent directly to it but streaming will miss it, effectively resulting in the hint being discarded.
As sending the hint _only_ to the leaving replica is a rather bad idea, send the hint to all replicas also in the case when the original destination of the hint is leaving.
Note that this is a …
=> [Backport 6.0]: hints: send hints with CL=ALL if target is leaving

data_dictionary/storage_options.hh, replica/database.cc, replica/distributed_loader.cc, replica/table.cc, service/storage_service.cc, sstables/sstable_directory.cc, sstables/sstable_directory.hh, sstables/sstables.cc, sstables/sstables.hh, sstables/sstables_manager.cc, sstables/sstables_manager.hh, sstables/storage.cc, sstables/storage.hh, test/boost/mutation_test.cc, test/boost/sstable_directory_test.cc, test/lib/test_services.cc, tools/schema_loader.cc, tools/scylla-sstable.cc
New sstables for a table are created by the table::make_sstable() method. The method then calls sstables_manager::make_sstable() and passes there a path to component files which, in turn, sits on table::config. Since some time ago having an on-disk path for an sstable had become optional, as sstables could be put on S3 storage without local paths involved. In that case the aforementioned "path" is ~~ab~~used as a key in the system.sstables registry, that references a record with information used to retrieve URLs of sstables' objects.
This PR removes the "path" argument from sstables_manager::make_sstable() and its sstable_sdirectory peer. The details of sstables' location are moved onto storage_options and depend on storage type. For now in both storage types this location is still the …
=> Make sstables without on-disk path

compaction/compaction.cc, sstables/kl/reader.cc, sstables/kl/reader.hh, sstables/mx/reader.cc, sstables/mx/reader.hh, sstables/sstable_set.cc, sstables/sstable_set.hh, sstables/sstables.cc, sstables/sstables.hh, test/boost/sstable_datafile_test.cc, test/perf/perf_sstable.cc, test/perf/perf_sstable.hh, tools/scylla-sstable.cc
"crawling" is a little bit obscure in this context. so let's rename this class to reflect the fact that this reader only reads the entire content of the sstable.
both crawling reader for kl and mx formats are renamed. also, in order to be consistent, all "crawling reader" in variable names are updated as well.
---
=> sstable: s/crawling_sstable_mutation_reader/sstable_full_scan_reader

replica/compaction_group.hh, replica/table.cc, test/boost/tablets_test.cc
Cleanup of a deallocated tablet throws an exception.
Since failed cleanup is retried, we end up in an infinite loop.
Ignore cleanup of deallocated storage groups.
Fixes: https://github.com/scylladb/scylladb/issues/19752.
Needs to be backported to all branches with tablets (6.0 and later)
(cherry picked from commit https://github.com/scylladb/scylladb/commit/20d6cf55f25745a4326a3147139b302f5603e5b9)
(cherry picked from commit https://github.com/scylladb/scylladb/commit/2c4b1d6b45095ce939f6953aedbfafa2152671e8)
Refs https://github.com/scylladb/scylladb/pull/20584
=> [Backport 6.1] replica: ignore cleanup of deallocated storage group

mutation/mutation.cc, readers/mutation_reader.hh, test/boost/repair_test.cc, test/boost/sstable_compaction_test.cc
The `consume*()` variants just forward the call to the `_impl` method with the same name. The latter, being a member of `::impl`, will bypass the top level `fill_buffer()`, etc. methods and thus will never call `set_close_required()`. Do this in the top-level `consume*()` methods instead, to ensure a reader, on which only `consume*()` is called, and then is destroyed, will complain as it should (and abort).
Only one place was found in core code, which didn't close the reader: `split_mutation() in `mutation/mutation.cc` and this reader is the "from-mutation" one which has no real close routine. All other places were in tests. All this is to say, there were no real bugs uncovered by this PR.
Fixes #16520
Improvement, no backport required.
=> readers/flat_mutation_reader_v2: call set_close_required() from consume*()

compaction/compaction_manager.cc, compaction/compaction_manager.hh, replica/compaction_group.hh, replica/database.hh, replica/table.cc, service/topology_coordinator.cc, test/boost/sstable_compaction_test.cc, test/topology_experimental_raft/test_tablets.py
Consider the following:
```
T
0   split prepare starts
1                               repair starts
2   split prepare finishes
3                               repair adds unsplit sstables
4                               repair ends
5   split executes
```
If repair produces sstable after split prepare phase, the replica will not split that sstable later, as prepare phase is considered completed already. That causes split execution to fail as replicas weren't really prepared. This also can be triggered with load-and-stream which shares the same write (consumer) path.
The approach to fix this is the same employed to prevent a race between split and migration. If migration happens during prepare phase, it can happen source misses the split request, but the tablet will still be split on the …
=> [Backport 6.1] tablets: Fix race between repair and split

compaction/compaction_manager.cc, compaction/compaction_manager.hh, replica/compaction_group.hh, replica/database.hh, replica/table.cc, service/topology_coordinator.cc, test/boost/sstable_compaction_test.cc, test/topology_experimental_raft/test_tablets.py
Consider the following:
```
T
0   split prepare starts
1                               repair starts
2   split prepare finishes
3                               repair adds unsplit sstables
4                               repair ends
5   split executes
```
If repair produces sstable after split prepare phase, the replica will not split that sstable later, as prepare phase is considered completed already. That causes split execution to fail as replicas weren't really prepared. This also can be triggered with load-and-stream which shares the same write (consumer) path.
The approach to fix this is the same employed to prevent a race between split and migration. If migration happens during prepare phase, it can happen source misses the split request, but the tablet will still be split on the …
=> [Backport 6.0] tablets: Fix race between repair and split 

docs/dev/reader-concurrency-semaphore.md, reader_concurrency_semaphore.cc, test/boost/reader_concurrency_semaphore_test.cc
* Also dump diagnostics when a read times out while active (not queued).
* Add the "Trigger permit" line, containing the details of the permit which caused the diagnostics dump (by e.g. timing out).
* Add the "Identified bottleneck(s)" line, containing the identified bottlenecks which lead to permits being queued. This line is missing if no such bottleneck can be identified.
* Document the new features, as well as the stat dump, which was added some time ago.
Example of the new dump format:
```
INFO  2024-09-12 08:09:48,046 [shard  0:main] reader_concurrency_semaphore - Semaphore reader_concurrency_semaphore_dump_reader_diganostics with 8/10 count and 106192275/32768 memory resources: timed out, dumping permit diagnostics:
Trigger permit: count=0, memory=0, table=ks.tbl0, …
```
=> reader_concurrency_semaphore: improve the diagnostics dump

alternator/controller.cc, alternator/executor.cc, alternator/executor.hh, alternator/server.cc, alternator/server.hh, alternator/streams.cc, alternator/ttl.cc, test/topology_experimental_raft/test_alternator.py
The main goal of this PR is to fix a bug (#20619) in the alternator_enforce_authorization=false setting - which didn't do its job (i.e, _don't_ check permissions) when authorization is configured in CQL but not wanted in Alternator.
The series also a few smaller bugs in the code that were discovered while debugging the main issue:
1. A potential use-after-free (that didn't seem to hit us in practice) is fixed.
2. A confusing error message (that was also reported in #20619) is improved.
3. Make the alternator_enforce_authorization live-updatable. There was no reason why it shouldn't be, and as this series needs to make this flag available to more code, let's just do it properly and assume the flag is live-updatable.
Because the RBAC feature has not been backported to any open-source …
=> Alternator: a few RBAC fixes

cql3/restrictions/statement_restrictions.cc, cql3/restrictions/statement_restrictions.hh, cql3/statements/modification_statement.cc, cql3/statements/select_statement.cc, test/boost/statement_restrictions_test.cc
The statement_restrictions class started life in the object-oriented style - an
object that interacts with its environment via mutators and is observed via
observers.
This is however not suitable for its objective: to analyze the WHERE clause,
select a query plan, and partition the WHERE clause atoms to the various
parts demanded by the query plan (read_command and filters). Furthermore,
the object oriented style makes it hard to work with as you can only call some
observers after the related mutators were called.
Fix this by transforming the code info a more functional style: we call
a function that returns an immutable statement_restrictions object that
can only be observed. This makes it easier to further change in the future,
as changes will not have to consider interaction with the …
=> cql3: statement_restrictions: adapt to functional style

cql3/statements/modification_statement.cc, test/topology_custom/test_query_rebounce.py, transport/server.cc, transport/server.hh
During a query execution, the query can be re-bounced to another shard if the requested data is located there. Previous implementation assumed that the shard cannot be changed after first re-bounce, however with the introduction of Tablets, data could be migrated to another shard after the query was already re-bounced, causing a failure of the query execution. To avoid this issue, the query is re-bounced as needed until it is executed on the correct shard.
Fixes #15465
=> cql_server::connection: Process rebounce message in case of multiple shard migrations

cql3/Cql.g, cql3/attributes.cc, cql3/attributes.hh, cql3/statements/select_statement.cc, service/qos/service_level_controller.hh, test/cql-pytest/test_using_service_level.py
Allow to specify service level used in select statement `SELECT ... USING SERVICE LEVEL sl_name`.
In OSS, this only affects statement's timeout.
In case both service level and timeout are specified `SELECT ... USING SERVICE LEVEL sl_name AND TIMEOUT 1h`, the timeout has higher priority as statement's timeout.
Fixes scylladb/scylladb#18471
=> cql3/statements/select_statement: `SELECT ... USING SERVICE LEVEL`

gms/inet_address.hh
Drop the unused `gms::inet_address::raw_addr` method
and modernize operator== and operator< as class methods 
* Cleanup only, no backport needed
=> gms: inet_address: drop unused raw_addr method and modernize comperators

gms/feature_service.hh, main.cc, message/messaging_service.cc, message/messaging_service.hh, test/lib/cql_test_env.cc, test/manual/gossip.cc, test/manual/message.cc
In https://github.com/scylladb/scylladb/pull/18729, we introduced a new statement tenant $maintenance, but the change wasn't protected by any cluster feature.
This wasn't a problem for OSS, since unknown isolation cookie just uses default scheduling group. However, in enterprise that leads to creating a service level on not-upgraded nodes, which may end up in an error if user create maximum number of service levels.
This patch adds a cluster feature to guard adding the new tenant. It's done in the way to handle two upgrade scenarios:
version without $maintenance tenant -> version with $maintenance tenant guarded by a feature
version with $maintenance tenant but not guarded by a feature -> version with $maintenance tenant guarded by a feature
The PR adds enabled flag to statement tenants. …
=> [Backport 6.2] message/messaging_service: guard adding maintenance tenant under cluster feature

gms/feature_service.hh, main.cc, message/messaging_service.cc, message/messaging_service.hh, test/lib/cql_test_env.cc, test/manual/gossip.cc, test/manual/message.cc
In https://github.com/scylladb/scylladb/pull/18729, we introduced a new statement tenant $maintenance, but the change wasn't protected by any cluster feature.
This wasn't a problem for OSS, since unknown isolation cookie just uses default scheduling group. However, in enterprise that leads to creating a service level on not-upgraded nodes, which may end up in an error if user create maximum number of service levels.
This patch adds a cluster feature to guard adding the new tenant. It's done in the way to handle two upgrade scenarios:
version without $maintenance tenant -> version with $maintenance tenant guarded by a feature
version with $maintenance tenant but not guarded by a feature -> version with $maintenance tenant guarded by a feature
The PR adds enabled flag to statement tenants. …
=> [Backport 6.1] message/messaging_service: guard adding maintenance tenant under cluster feature

sstables/sstable_directory.cc
This one is pretty simple
```
return do_with(std::move(data), [] {
toss_data(data);
return remove(std::move(data));
});
```
it doesn't really need to do_with() since "toss_data" is non-preemptive. Still, convert it into
```
toss_data(data);
co_await remove(std::move(data));
```
=> Coroutinize sstable_directory::remove_unshared_sstables()

test/boost/sstable_datafile_test.cc, test/boost/sstable_test.cc, test/lib/sstable_utils.hh
This one is aimed at giving tests the ability to call private methods of class sstable. Some of the wrappers in the test class wrap public methods and can be removed.
=> Put sstables::test class on a diet

auth/common.cc, cql3/Cql.g, cql3/cql3_type.cc, cql3/dialect.hh, cql3/prepared_statements_cache.hh, cql3/query_processor.cc, cql3/query_processor.hh, cql3/statements/alter_table_statement.cc, cql3/statements/select_statement.cc, cql3/util.cc, cql3/util.hh, db/config.cc, db/config.hh, db/cql_type_parser.cc, db/schema_tables.cc, docs/cql/cql-extensions.md, table_helper.cc, table_helper.hh, test/boost/cql_auth_syntax_test.cc, test/boost/cql_query_test.cc, test/boost/expr_test.cc, test/boost/statement_restrictions_test.cc, test/cql-pytest/test_prepare.py, test/cql-pytest/test_virtual_tables.py, test/lib/cql_test_env.cc, tools/schema_loader.cc, transport/server.cc, transport/server.hh, utils/config_file_impl.hh
Bind variables in CQL have two formats: positional (?) where a variable is referred to by its relative position in the statement, and named (:var), where the user is expected to supply a name->value mapping.
In https://github.com/scylladb/scylladb/commit/19a6e69001f26133a7f7a0a13e89935888884e1a we identified the case where a named bind variable appears twice in a query, and collapsed it to a single entry in the statement metadata. Without this, a driver using the named variable syntax cannot disambiguate which variable is referred to.
However, it turns out that users can use the positional call form even with the named variable syntax, by using the positional API of the driver. To support this use case, we add a configuration variable to disable the same-variable detection.
Because the …
=> [Backport 6.1] cql3: add option to not unify bind variables with the same

compaction/compaction_manager.cc, replica/table.cc, test/topology_experimental_raft/test_tablets.py
To fix a race between split and repair here c1de4859d815b3eb4aeb, a new sstable
generated during streaming can be split before being attached to the sstable
set. That's to prevent an unsplit sstable from reaching the set after the
tablet map is resized.
So we can think this split is an extension of the sstable writer. A failure
during split means the new sstable won't be added. Also, the duration of split
is also adding to the time erm is held. For example, repair writer will only
release its erm once the split sstable is added into the set.
This single-sstable split is going through run_custom_job(), which serializes
with other maintenance tasks. That was a terrible decision, since the split may
have to wait for ongoing maintenance task to finish, which means holding erm
for longer. …
=> tablet: Fix single-sstable split when attaching new unsplit sstables

api/api-doc/storage_service.json, api/storage_service.cc, db/snapshot-ctl.cc, db/snapshot-ctl.hh, db/snapshot/backup_task.cc, db/snapshot/backup_task.hh, docs/dev/object_storage.md, docs/operating-scylla/nodetool-commands/backup.rst, test/nodetool/test_backup.py, test/object_store/test_backup.py, test/pylib/rest_client.py, tools/scylla-nodetool.cc
with this parameter, "backup" API can backup the given table, this
enables it to be a drop-in replacement of existing rclone API used by
scylla manager.
Fixes https://github.com/scylladb/scylladb/issues/20636
---
this change is a part of the efforts to bring the native backup/restore to scylla, no need to backprt.
=> treewide: add "table" parameter to "backup" API 

alternator/executor.cc, docs/alternator/compatibility.md, test/alternator/test_provisioned_throughput.py, test/alternator/util.py
When users create a table using the Alternator API, they can decide if the billing is PROVISIONED of PAY_PER_REQUEST.
If the billing is set to PROVISIONED, they need to set the ProvisionedThroughput ReadCapacityUnits (RCU) and WriteCapacityUnits (WCU).
This series adds support for getting and setting the ProvisionedThroughput. The values will be stored as table extension tags.
Following how TTL is stored within the Alternator, we will use ```system:rcu_attribute``` and ```system:wcu_attribute``` for the labels.
The series adds a test that sets ProvisionedThroughput and validates that it gets the value back. It was tested with both Alternator and AWS.
This series is part of the effort to monitor, limit, and bill Alternator operations.
New code, no need to backport.
=> Alternator store ProvisionedThroughput

service/storage_service.cc, service/topology_coordinator.cc, test/topology_custom/test_replace.py
Before 17f4a151ce27114a66a83874705c223e0dba9ceb the node was marked as
been replaced in join_group0 state, before it actually joins the group0,
so by the time it actually joins and starts transferring snapshot/log no
traffic is sent to it. The commit changed this to mark the node as
being replaced after the snapshot/log is already transferred so we can
get the traffic to the node while it sill did not caught up with a
leader and this may causes problems since the state is not complete.
Mark the node as being replaced earlier, but still add the new node to
the topology later as the commit above intended.
Fixes: https://github.com/scylladb/scylladb/issues/20629
Need to be backported since this is a regression
=> mark node as being replaced earlier

replica/compaction_group.hh, replica/table.cc, test/boost/tablets_test.cc
Cleanup of a deallocated tablet throws an exception.
Since failed cleanup is retried, we end up in an infinite loop.
Ignore cleanup of deallocated storage groups.
Fixes: https://github.com/scylladb/scylladb/issues/19752.
Needs to be backported to all branches with tablets (6.0 and later)
(cherry picked from commit https://github.com/scylladb/scylladb/commit/20d6cf55f25745a4326a3147139b302f5603e5b9)
(cherry picked from commit https://github.com/scylladb/scylladb/commit/2c4b1d6b45095ce939f6953aedbfafa2152671e8)
Refs https://github.com/scylladb/scylladb/pull/20584
=> [Backport 6.0] replica: ignore cleanup of deallocated storage group

service/raft/raft_group0.cc, service/storage_service.cc, test/topology_custom/test_long_join.py
For each new node added to the raft config populate it's ID to IP mapping in raft address map from the gossiper. The mapping may have expired if a node is added to the raft configuration long after it first appears in the gossiper.
Fixes scylladb/scylladb#20600
Backport to all supported versions since the bug may cause bootstrapping failure.
=> Populate raft address map from gossiper on raft configuration change

data_dictionary/data_dictionary.cc, data_dictionary/storage_options.hh, replica/database.cc, replica/database.hh, replica/distributed_loader.cc, replica/table.cc, sstables/storage.cc, test/boost/database_test.cc, test/boost/mutation_test.cc, test/lib/test_services.cc
The datadir keeps path to directory where local sstables can be. The very same information is now kept in table's storage options (#20542). This set fixes the remaining places that still use table::config::datadir and table::dir() and removes the datadir field.
=> Remove datadir string from table::config

service/storage_service.cc, service/topology_coordinator.cc, test/topology_custom/test_replace.py
Before 17f4a151ce27114a66a83874705c223e0dba9ceb the node was marked as
been replaced in join_group0 state, before it actually joins the group0,
so by the time it actually joins and starts transferring snapshot/log no
traffic is sent to it. The commit changed this to mark the node as
being replaced after the snapshot/log is already transferred so we can
get the traffic to the node while it sill did not caught up with a
leader and this may causes problems since the state is not complete.
Mark the node as being replaced earlier, but still add the new node to
the topology later as the commit above intended.
Fixes: https://github.com/scylladb/scylladb/issues/20629
Need to be backported since this is a regression
(cherry picked from commit 644e7a20122e9b53bf62b284d947605e252ba6ef)
(cherry …
=> [Backport 6.1] mark node as being replaced earlier

service/storage_service.cc, service/topology_coordinator.cc, test/topology_custom/test_replace.py
Before 17f4a151ce27114a66a83874705c223e0dba9ceb the node was marked as
been replaced in join_group0 state, before it actually joins the group0,
so by the time it actually joins and starts transferring snapshot/log no
traffic is sent to it. The commit changed this to mark the node as
being replaced after the snapshot/log is already transferred so we can
get the traffic to the node while it sill did not caught up with a
leader and this may causes problems since the state is not complete.
Mark the node as being replaced earlier, but still add the new node to
the topology later as the commit above intended.
Fixes: https://github.com/scylladb/scylladb/issues/20629
Need to be backported since this is a regression
(cherry picked from commit 644e7a20122e9b53bf62b284d947605e252ba6ef)
(cherry …
=>  [Backport 6.0] mark node as being replaced earlier

dist/common/scripts/scylla_coredump_setup, dist/common/scripts/scylla_raid_setup
On RHEL9, systemd-coredump fails to coredump on /var/lib/scylla/coredump because the service only have write acess with systemd_coredump_var_lib_t. To make it writable, we need to add file context rule for /var/lib/scylla/coredump, and run restorecon on /var/lib/scylla.
Fixes #19325
=> scylla_raid_setup: configure SELinux file context

service/raft/raft_group0.cc, service/storage_service.cc, test/topology_custom/test_long_join.py
For each new node added to the raft config populate it&#39;s ID to IP mapping in raft address map from the gossiper. The mapping may have expired if a node is added to the raft configuration
long after it first appears in the gossiper.
Fixes scylladb/scylladb#20600
Backport to all supported versions since the bug may cause bootstrapping failure.
(cherry picked from commit bddaf498dfe061da3b5bdd041b628f49beb68583)
(cherry picked from commit 9e4cd3209611bfad5ce5c8b3c92586574af86d8a)
=>  [Backport 6.0] Populate raft address map from gossiper on raft configuration change

alternator/executor.hh, alternator/rmw_operation.hh, auth/certificate_authenticator.hh, auth/common.cc, cql3/query_processor.hh, cql3/sets.cc, cql3/statements/batch_statement.cc, cql3/statements/batch_statement.hh, cql3/statements/update_statement.cc, data_dictionary/data_dictionary.cc, db/auth_version.hh, db/system_keyspace.hh, service/migration_manager.hh, service/qos/service_level_controller.hh, service/raft/raft_group0_client.cc, service/raft/raft_group0_client.hh, service/raft/raft_group_registry.hh, service/raft/raft_timeout.hh, test/boost/commitlog_cleanup_test.cc, test/boost/cql_query_test.cc, test/boost/database_test.cc, test/boost/group0_cmd_merge_test.cc, test/boost/transport_test.cc
Reduce compile time and unnecessary compilations by reducing #include load.
Minor refactoring, no backport.
=> raft_group0_client: place on a #include diet

db/hints/manager.hh, sstables/consumer.hh, sstables/kl/reader.cc, sstables/mx/bsearch_clustered_cursor.hh, sstables/mx/parsers.hh, sstables/promoted_index_blocks_reader.hh, test/boost/cached_file_test.cc, test/boost/index_reader_test.cc, utils/cached_file.hh, utils/contiguous_shared_buffer.hh, utils/fragmented_temporary_buffer.hh
This fixes a use-after-free bug when parsing clustering key across
pages.
Also includes a fix for allocating section retry, which is potentially not safe (not in practice yet).
Details of the first problem:
Clustering key index lookup is based on the index file page cache. We
do a binary search within the index, which involves parsing index
blocks touched by the algorithm. Index file pages are 4 KB chunks
which are stored in LSA.
To parse the first key of the block, we reuse clustering_parser, which
is also used when parsing the data file. The parser is stateful and
accepts consecutive chunks as temporary_buffers. The parser is
supposed to keep its state across chunks.
In 93482439, the promoted index cursor was optimized to avoid 
fully page copy when parsing index blocks. Instead, parser …
=> sstables: Fix use-after-free on page cache buffer when parsing promoted index entries across pages

utils/directories.cc
clang-tidy warns:
```
Warning: /__w/scylladb/scylladb/utils/directories.cc:132:52: warning: 'path' used after it was moved [bugprone-use-after-move]
132 |         bool can_access = co_await file_accessible(path.string(), access_flags::read | access_flags::write | access_flags::execute);
|                                                    ^
/__w/scylladb/scylladb/utils/directories.cc:121:28: note: move occurred here
121 |         verification_error(std::move(path), "File not owned by current euid: {}. Owner is: {}", geteuid(), sd.uid);
|                            ^
```
because we pass `std::move(path)` to `verification_error()`, and "then" use this variable again in this same function.
this is a false alarm, but we could make it very clear to convince this tool that it's safe to do so. …
=> directories: cleanups to silence clang-tidy false alarms

test/boost/CMakeLists.txt
Fix two recent regressions of the cmake build -- found this time in the test suite.
We (presumably) don't build stable releases (and their tests) with CMake, so backporting these fixes appears unnecessary, even if the regressions have been ported to stable branches.
@xemul @dawmd @tchaikov @tgrabiec @scylladb/scylla-maint
=> fix regressions of building tests with cmake

db/virtual_tables.cc, test/cql-pytest/nodetool.py, test/cql-pytest/test_virtual_tables.py
Use database::get_snapshot_details to get the details
of all snapshots on disk, in particular those of
deleted tables.
Add test_snapshots_dropped_table to test listing
of snapshots of a deleted table.
And harden the existing test cases to use a unique
snapshot tag and to delete it when the test ends.
Fixes #18313
* No backport required at this time since this is rather minor UX issue that weren't hit in the field AFAIK
=> virtual_tables: snapshots: include all snapshots

api/storage_service.cc, db/config.cc, db/config.hh, locator/token_metadata.hh, service/storage_service.cc, service/storage_service.hh, test/nodetool/test_nodeops.py, tools/scylla-nodetool.cc
- As part of deprecation of IP address usage, warning messages were added when IP addresses specified in the `ignore-dead-nodes` and `--ignore-dead-nodes-for-replace` options for scylla and nodetool. 
- Slight optimizations for `utils::split_comma_separated_list`, ` host_id_or_endpoint lists` and `storage_service` remove node operations, replacing `std::list` usage with `std::vector`. 
Fixes scylladb/scylladb#19218
Backport: 6.2 as it's not yet released.
=> Node replace and  remove operations: Add deprecate IP addresses usage warning.

compaction/compaction.cc, compaction/compaction_manager.cc, compaction/compaction_manager.hh, compaction/table_state.hh, replica/database.hh, replica/table.cc, service/storage_service.cc, test/boost/compaction_group_test.cc, test/lib/test_services.cc, test/pylib/rest_client.py, test/topology_experimental_raft/test_tablets.py, tools/scylla-sstable.cc
During split prepare phase, there will be more than 1 compaction group with
overlapping token range for a given replica.
Assume tablet 1 has sstable A containing deleted data, and sstable B containing
a tombstone that shadows data in A.
Then split starts:
1) sstable B is split first, and moved from main (unsplit) group to a
split-ready group
2) now compaction runs in split-ready group before sstable A is split
tombstone GC logic today only looks at underlying group, so compaction is step
2 will discard the deleted data in A, since it belongs to another group (the
unsplit one), and so the tombstone can be purged incorrectly.
To fix it, compaction will now work with all uncompacting sstables that belong
to the same replica, since tombstone GC requires all sstables that possibly
contain …
=> replica: Fix tombstone GC during tablet split preparation

api/api-doc/storage_service.json, api/storage_service.cc, data_dictionary/data_dictionary.cc, data_dictionary/storage_options.hh, replica/distributed_loader.cc, replica/distributed_loader.hh, sstables/sstable_directory.cc, sstables/sstable_directory.hh, sstables_loader.cc, sstables_loader.hh, test/nodetool/rest_api_mock.py, test/nodetool/test_restore.py, test/object_store/test_backup.py, test/pylib/rest_client.py, tools/scylla-nodetool.cc
before this change, we enumerate the sstables tracked by the
system.sstables table, and restore them when serving
requests to "storage_service/restore" API. this works fine with
"storage_service/backup" API. but this "restore" API cannot be
used as a drop-in replacement of the rclone based API currently
used by scylla-manager.
in order to fill the gap, in this change:
* add the "prefix" parameter for specifying the shared prefix of
sstables
* add the "sstables" parameter for specifying the list of  TOC
components of sstables
* remove the "snapshot" parameter, as we don't encode the prefix
on scylla's end anymore.
* make the "table" parameter mandatory.
Fixes https://github.com/scylladb/scylladb/issues/20461
----
this change is a part of the efforts to bring the native backup/restore to …
=> treewide: accept list of sstables in "restore" API 

sstables_loader.cc, sstables_loader.hh, test/object_store/test_backup.py
The restore-from-s3 task uses load-and-stream internally which, in turn, unlinks loaded sstables on success. That's not what user expects when it restores from backup, objects should remain in bucket afterwards.
=> Do not remove objects from backup storage after restore

.github/workflows/iwyu.yaml, db/batchlog_manager.hh, db/chained_delegating_reader.hh, db/commitlog/commitlog.hh, db/commitlog/commitlog_extensions.hh, db/commitlog/replay_position.hh, db/config.hh, db/consistency_level.hh, db/cql_type_parser.hh, db/data_listeners.hh, db/extensions.hh, db/functions/aggregate_function.hh, db/functions/scalar_function.hh, db/heat_load_balance.hh, db/hints/internal/hint_endpoint_manager.hh, db/hints/internal/hint_sender.hh, db/hints/manager.hh, db/hints/resource_manager.hh, db/rate_limiter.hh, db/system_keyspace_view_types.hh, db/tags/utils.hh, db/view/build_progress_virtual_reader.hh, db/view/node_view_update_backlog.hh, db/view/view_builder.hh, db/view/view_update_generator.hh, utils/hashers.hh, utils/i_filter.hh
these unused includes are identified by clang-include-cleaner.
after auditing the source files, all of the reports have been
confirmed.
please note, since we have `using seastar::shared_ptr` in
`seastarx.h`, this renders `#include <seastar/core/shared_ptr.hh>`
unnecessary if we don't need the full definition of `seastar::shared_ptr`.
so, in this change, all the unused includes are removed.
---
=> db: remove unused includes 

test/lib/test_services.cc
There are two issues in it. First, listing the registry with a consumer callback passes wrong argument to the consumer. Second, the primary key of the registry is wrong. Both issues don't show up, because existing tests that use mock don't read from it, only write. Tests that read from registry are python tests that start scylla and thus use real registry.
=> Fix sstables registry mock

.clang-format
Some adjustments to the `.clang-format` options to better match the current code:
* don't sort the include headers: causes large diffs especially in files with a lot of includes, and the `#include` ordering is not prescribed by the Seastar coding style
* binpack the arguments in function declarations and calls: allow binpacking (as opposed to forcing each parameter on a separate line if they don't fit into the line length)
* indented parameter continuation (as opposed to aligning to the open parenthesis) - aligning to the open parenthesis causes alignment issues especially with lambdas
Fixes: scylladb/scylladb#20951
No backport: Not a product issue, just applies to master.
=> clang-format: adjustments to avoid unwanted refactors and better match the Seastar coding style

cql3/statements/alter_keyspace_statement.cc, cql3/statements/ks_prop_defs.cc, cql3/statements/ks_prop_defs.hh, cql3/statements/property_definitions.hh, test/cql-pytest/test_tablets.py, test/topology_custom/test_tablets.py
This patch series fixes a couple of bugs around validating if RF is not changed by too much when performing ALTER tablets KS.
RF cannot change by more than 1 in total, because tablets load balancer cannot handle more work at once. 
Fixes: #20039
Should be backported to 6.0 & 6.1 (wherever tablets feature is present), as this bug may break the cluster.
=> cql: improve validating RF's change in ALTER tablets KS

cql3/functions/user_function.cc, test/cql-pytest/test_describe.py
Scylla doesn't allow for the types of arguments or the return type of a UDF
to be frozen. As a result, before these changes, create statements
produced to restore UDFs as part of `DESCRIBE` statements could not
be executed.
Fixes scylladb/scylladb#20256
Backport: necessary as the restore process may not work correctly without these changes. The affected versions span from 5.2 to the current master, but we only want to apply the fix to the live versions, so 6.0, 6.1, and 6.2.
=> cql3: Print arguments and return type without frozen when describing UDF

main.cc, service/raft/raft_group0.cc, service/raft/raft_group0.hh, service/storage_service.cc, service/storage_service.hh, service/topology_coordinator.cc
Group0 server is often used in asynchronous context, but we do not wait
for them to complete before destroying the server. We already have
shutdown gate for it, so lets use it in those asynch functions.
Also make sure to signal group0 abort source if initialization fails.
Fixes scylladb/scylladb#20701
Backport to 6.2 since it contains af83c5e53eb465 and it made the race easier to hit, so tests became flaky.
=> Wait for all users of group0 server to complete before destroying it

mutation/mutation_partition.cc, mutation/mutation_partition.hh, mutation/mutation_partition_v2.cc, mutation/mutation_partition_v2.hh, service/storage_proxy.cc, utils/chunked_vector.hh, utils/class_registrator.hh, utils/config_file.cc, utils/crc.hh, utils/error_injection.hh, utils/fragment_range.hh, utils/intrusive_btree.hh, utils/loading_cache.hh, utils/logalloc.cc, utils/lsa/chunked_managed_vector.hh, utils/observable.hh, utils/unconst.hh
To avoid depending on two similar libraries (boost ranges and std \<ranges), replace
uses of the former with the latter. This series tackles the utils/ directory.
Code cleanup, no backport.
=> utils: replace dependency on boost ranges with <ranges>

replica/compaction_group.hh, replica/table.cc, test/topology_experimental_raft/test_tablets.py
When tablets are migrated with file-based streaming, we can have a situation where a tombstone is garbage collected before the data it shadows lands. For instance, if we have a tablet replica with 3 sstables:
1. sstable containing an expired tombstone
2. sstable with additional data
3. sstable containing data which is shadowed by the expired tombstone in sstable 1
If this tablet is migrated, and the sstables are streamed in the order listed above, the first two sstables can be compacted before the third sstable arrives. In that case, the expired tombstone will be garbage collected, and data in the third sstable will be resurrected after it arrives to the pending replica.
This change fixes this problem by disabling tombstone garbage collection for pending replicas.
This fixes a problem in …
=> compaction: fix potential data resurrection with file-based migration

repair/repair.hh, repair/row_level.cc
Use clear_gently to avoid the following stalls.
```
~frozen_mutation_fragment at ././frozen_mutation.hh:268
std::destroy_at<frozen_mutation_fragment> at
/usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_construct.h:88
std::allocator_traits<std::allocator<std::_List_node<frozen_mutation_fragment>
> >::destroy<frozen_mutation_fragment> at
/usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/alloc_traits.h:537
std::__cxx11::_List_base<frozen_mutation_fragment,
std::allocator<frozen_mutation_fragment> >::_M_clear at
/usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/list.tcc:77
~_List_base at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_list.h:499
~partition_key_and_mutation_fragments at ././repair/repair.hh:298 …
```
=> repair: Fix stall in repair_get_row_diff_with_rpc_stream_process_op_slow_path

db/consistency_level.cc, locator/abstract_replication_strategy.hh, locator/everywhere_replication_strategy.cc, locator/everywhere_replication_strategy.hh, locator/local_strategy.cc, locator/local_strategy.hh, locator/network_topology_strategy.cc, locator/network_topology_strategy.hh, locator/simple_strategy.cc, locator/simple_strategy.hh, service/storage_proxy.cc, test/topology_custom/test_change_replication_factor_1_to_0.py, tools/build_info.hh
During the investigation of scylladb/scylladb#20282, it was discovered that implementations of speculating read executors have undefined behavior when called with an incorrect number of read replicas. This PR introduces two levels of condition checking:
- Condition checking in speculating read executors for the number of replicas.
- Checking the consistency of the Effective Replication Map in  filter_for_query(): the map is considered incorrect if the list  of replicas contains a node from a data center whose replication factor is 0.
Please note: This PR does not fix the issue found in scylladb/scylladb#20282;   it only adds condition checks to prevent undefined behavior in cases of  inconsistent inputs.
Refs scylladb/scylladb#20625
As this issue applies to the releases versions and can …
=> storage_proxy: Add conditions checking to avoid UB in speculating read executors.

data_dictionary/data_dictionary.cc, data_dictionary/storage_options.hh, db/system_keyspace.cc, db/system_keyspace.hh, db/system_keyspace_sstables_registry.hh, sstables/sstable_directory.cc, sstables/sstable_directory.hh, sstables/sstables.hh, sstables/sstables_registry.hh, sstables/storage.cc, test/lib/test_services.cc, test/object_store/test_basic.py
The system.sstables (a.k.a. sstables registry) primary key is "string location" as partition key and "uuid generation" as clustering one. The "location" part was taken from table.config.datadir value which, in turn, a string containing path to on-disk files if the table was located locally, e.g. /var/lib/scylla/data/ks/cf-abc123 one. Recently [1] the datadir was moved from table config onto storage options, but this string is still used as registry key.
Other than being owned by a table with ID, sstables are accessed by restore-from-object-storage code [2]. To make it work, both storage driver and sstable_directory helper class maintain two formats of object prefixes for sstables components. For S3-backed sstables having a record in registry, the path used is …
=> Use table id as system.sstables partition key

main.cc, replica/tablets.cc, replica/tablets.hh, service/raft/raft_group0_client.cc, service/raft/raft_group0_client.hh, test/lib/cql_test_env.cc
Having tablet metadata with more than 1 pending replica will prevent this metadata from being (re)loaded due to sanity check on load. This patch fails the operation which tries to save the wrong metadata with a similar sanity check. For that, changes submitted to raft are validated, and if it's topology_change that affects system.tablets, the new "replicas" and "new_replicas" values are checked similarly to how they will be on (re)load.
fixes #20043
=> Check system.tablets update before putting it into the table

replica/compaction_group.hh, replica/table.cc, test/topology_experimental_raft/test_tablets.py
This is a manual backport of #20788
When tablets are migrated with file-based streaming, we can have a situation where a tombstone is garbage collected before the data it shadows lands. For instance, if we have a tablet replica with 3 sstables:
1. sstable containing an expired tombstone
2. sstable with additional data
3. sstable containing data which is shadowed by the expired tombstone in sstable 1
If this tablet is migrated, and the sstables are streamed in the order listed above, the first two sstables can be compacted before the third sstable arrives. In that case, the expired tombstone will be garbage collected, and data in the third sstable will be resurrected after it arrives to the pending replica.
This change fixes this problem by disabling tombstone garbage collection for …
=> [Backport 6.2] compaction: fix potential data resurrection with file-based migration

api/api.cc, api/api_init.hh, api/compaction_manager.cc, api/compaction_manager.hh, api/storage_service.cc, main.cc
Endpoints are registered next to the service they use, and the unregistration deferred action is created right after it. When registered, the service in question is passed as argument and then captured by enpoints lambdas. This makes sure that service is not used by endpoints after being stopped.
That's not quite the case for compaction manager. Its endpoints can be registered in several places, and compaction_manager "function" is not unregistered on stop. This patch fixes some of this misbehavior, in particular:
- adds unregistration of compaction_manager API function
- uses sharded<compaction_manager>& argument in endpoints instead of ctx.db.local().get_compaction_manager() chain
- moves some endpoints from storage_service.cc to compaction_manager.cc
=> Sanitize compaction manager API endpoints

cql3/statements/alter_keyspace_statement.cc, cql3/statements/alter_keyspace_statement.hh, cql3/statements/ks_prop_defs.cc, cql3/statements/ks_prop_defs.hh, cql3/statements/property_definitions.hh, test/cql-pytest/test_tablets.py, test/topology_custom/test_tablets.py
This patch series fixes a couple of bugs around validating if RF is not changed by too much when performing ALTER tablets KS.
RF cannot change by more than 1 in total, because tablets load balancer cannot handle more work at once.
Fixes: https://github.com/scylladb/scylladb/issues/20039
Should be backported to 6.0 & 6.1 (wherever tablets feature is present), as this bug may break the cluster.
(cherry picked from commit https://github.com/scylladb/scylladb/commit/042825247f838203c14a770b753ff26a23e6836b)
(cherry picked from commit https://github.com/scylladb/scylladb/commit/adf453af3f391dbd10f787eb16aa8c8ea61f32d5)
(cherry picked from commit https://github.com/scylladb/scylladb/commit/9c5950533fb92ca7e44152dda761fa3a212da526)
(cherry picked from commit …
=> [Backport 6.0] cql: improve validating RF's change in ALTER tablets KS

auth/maintenance_socket_role_manager.cc, auth/maintenance_socket_role_manager.hh, auth/role_manager.hh, auth/service.cc, auth/service.hh, auth/standard_role_manager.cc, auth/standard_role_manager.hh, main.cc, test/topology_experimental_raft/test_restart_cluster.py
This change reorganizes the way standard_role_manager startup is handled: role_manager::ensure_superuser_is_created() is added, which returns a future that resolves once the superuser is available. We wait for this future before starting the CQL server.
There is a change in behavior auth::do_after_system_ready is potentially an infinite loop, and we await its result.
Fixes #10481
Reason for no backports: it's not a regresson and it's an issue that may only affect a tiny time window during the cluster startup.
=> cql: create default superuser if it doesn't exist

docs/Makefile, docs/README.md
- `docs/Makefile`: work around python-poetry issue https://github.com/python-poetry/poetry/issues/8761
- `docs/README.md`: fix minimum poetry version
No backporting needed (docs development).
=> micro-updates to documentation development, on python-poetry

service/raft/group0_state_id_handler.cc, test/topology_experimental_raft/test_tombstone_gc.py
Skip the advertisement of the group0 state id in case the gossiper is
not active (ready).
Sending the application state when the gossiper is not active caused
a warning being shown in the log about the local endpoint not being
found in the gossiper endpoint state map on a (graceful) node restart.
The local endpoint is initialized on the gossiper startup, so we skip
the state id advertisement until the startup is finished.
Fixes: scylladb/scylladb#21117
No backport: Fixes an issue that is currently only present in master
=> raft: consider the gossiper state then sending the group0 state id

db/size_estimates_virtual_reader.cc, interval.hh
To reduce dependency load, replace use of boost ranges with std ranges.
Since std ranges are more particular about what iterators they accept, a custom iterator
in size_estimates_virtual_reader has to be fixed first.
No backport; code cleanup.
=> interval: replace boost ranges with std ranges

docs/operating-scylla/security/node-node-encryption.rst, main.cc, message/messaging_service.cc, message/messaging_service.hh, test/topology/test_tls.py
Fixes #18903
Adds a "transitional" internode encryption mode, under which all _outgoing_ RPC connections will use TLS, but we will still accept any incoming non-tls connection.
This allows an operator to perform a move to TLS RPC without cluster downtime:
1. For each server, add certificate etc options to server_encryption_options + internode_encryption=none + set ssl_storage_port + restart (rolling)
2. For each server, set internode_encryption=transitional + RR
3. For each server, set internode_encryption=all + RR
=> Allow specifying TLS options with internode_encryption=none + add "transitional" mode

api/api.cc, api/api_init.hh, api/commitlog.cc, api/commitlog.hh, api/storage_service.cc, main.cc
Endpoints are registered next to the service they use, and the unregistration deferred action is created right after it. When registered, the service in question is passed as argument and then captured by enpoints lambdas. This makes sure that service is not used by endpoints after being stopped.
That's not so for commitlog endpoints. These are registered in several places, and /commitlog "function" is not unregistered on stop. This patch fixes some of this misbehavior, in particular:
-  adds unregistration of commitlog API function
-  uses sharded<database>& argument in endpoints instead of ctx.db
-  moves some endpoints from storage_service.cc to commitlog.cc
=> Sanitize commitlog API endpoints

alternator/executor.cc, alternator/streams.cc, alternator/ttl.cc, compound_compat.hh, cql3/selection/selection.cc, cql3/statements/alter_table_statement.cc, cql3/statements/batch_statement.cc, cql3/statements/create_view_statement.cc, cql3/statements/select_statement.cc, db/schema_tables.cc, db/view/view.cc, partition_slice_builder.cc, replica/table.cc, schema/schema.cc, schema/schema.hh, sstables/mx/writer.cc, test/lib/random_schema.cc
To reduce dependency load, change uses of boost ranges to std::ranges.
The first patch is preparation, replacing a construct that isn't easy to support with std ranges with something simpler.
No backport as this is a code cleanup.
=> schema: convert from boost ranges to std ranges

CMakeLists.txt, api/CMakeLists.txt, cmake/FindSeastar.cmake, configure.py, dist/CMakeLists.txt, redis/CMakeLists.txt, test/perf/CMakeLists.txt, utils/CMakeLists.txt
before this change, scylla's CMake-based system consumes Seastar
library by including it directly. but this failed to address the needs
of linking against Seastar shared libraries in Debug and Dev builds, while
linking against the static libraries in other builds. because Seastar
uses `BUILD_SHARED_LIBS` CMake variable to determine if it builds
shared libraries. and we cannot assign different values to this
CMake variable based on current configure type -- CMake does not
support. see https://gitlab.kitware.com/cmake/cmake/-/issues/19467
in order to address this problem, we have a couple possible
solutions:
- to enable Seastar to build both shared and static libraries in a
pass. without sacrificing the performance, we have to build
all object files twice: once with -fPIC, once without. in …
=> build: build seastar as an external project

db/config.cc, db/config.hh, db/view/view.cc, replica/database.cc, replica/database.hh, replica/table.cc, scylla-gdb.py, test/lib/cql_test_env.cc, test/pylib/scylla_cluster.py, test/topology_custom/test_mv_read_concurrency.py
When writing to some tables with materialized views, we need to read from the base table first to perform a delete of the old view row. When doing so, the memory used for the read is tracked by the user read concurrency semaphore. When we have a large number of such reads, we may use up all of the semaphore units, causing the following reads to be queued. When we have some user reads coming at the same time, these reads can have very high latency due to the write workload on the base table. We want to avoid this, so that the write workload doesn't have a high impact on the latency of the read workload.
This is fixed in this patch by adding a separate read concurrency semaphore just for view update read-before-writes. With the new semaphore, even if there are many view update …
=> mv: add a dedicated read concurrency semaphore for view update read before writes

replica/database.cc, replica/database.hh, replica/distributed_loader.cc, replica/table.cc, sstables/sstables_manager.cc, sstables/sstables_manager.hh, sstables/storage.cc, sstables/storage.hh
The all_datadirs keeps paths to directories where local sstables can be. In fact, Scylla doesn't put sstables there, but can try to find them on boot and when checking snapshots. The 0th element of this vector, called datadir, had recently been removed by #20675, now it's time to drop all_datadirs as well. The needed paths can be obtained from table's storage options (see #20542) and db::config::data_file_directories option.
=> Remove all_datadirs vector of strings from table::config

replica/compaction_group.hh, replica/database.hh, replica/table.cc, test/pylib/rest_client.py, test/topology_custom/test_compacting_reader_tombstone_gc.py
On the read path, the compacting reader is applied only to the sstable
reader. This can cause an expired tombstone from an sstable to be purged
from the request before it has a chance to merge with deleted data in
the memtable leading to data resurrection.
Fix this by checking the memtables before deciding to purge tombstones
from the request on the read path. A tombstone will not be purged if a
key exists in any of the table's memtables with a minimum live timestamp
that is lower than the maximum purgeable timestamp.
Fixes #20916
`perf-simple-query` stats before and after this fix :
`build/Dev/scylla perf-simple-query --smp=1 --flush` :
```
// Before this Fix
// ---------------
94941.79 tps ( 71.1 allocs/op,   0.0 logallocs/op,  14.1 tasks/op,   59393 insns/op,   24029 cycles/op, …
```
=> replica/table: check memtable before discarding tombstone during read

test.py, test/pylib/scylla_cluster.py
* Add `--max-failures` flag to test.py, which will stop the execution after number of failures
* Helps with "fails-fast" approach and can be used to improve CI speed, especially the 100times run
* Adds the number of cancelled tests to both summary and junit xml. I did not include them in boost, since it does not contain any statistics.
* Removes unnecessary list creation in test.py
* Completely unrelated change, but it is small enough that I feel it can be included as part of this one. If this is an issue I can create separate PR for it
*  Add `Test.started` property
* Helps with determining the current status of the Test and differentiating cancelled/not started tests. 
* Add `Test.failed` and `Test.did_not_run` read-only computed properties   
* Helper methods to determine status, …
=> test.py: Add option to fail after number of failures

service/topology_coordinator.cc, test/topology_custom/test_tablets_cql.py
ALTER tablets-enabled KEYSPACES (KS) may fail due to
`group0_concurrent_modification`, in which case it's repeated by a `for`
loop surrounding the code. But because raft's `add_entry` consumes the
raft's guard (by `std::move`'ing the guard object), retries of ALTER KS
will use a moved-from guard object, which is UB, potentially a crash.
The fix is to remove the before mentioned `for` loop altogether and rethrow the exception, as the `rf_change` event
will be repeated by the topology state machine if it receives the
concurrent modification exception, because the event will remain present
in the global requests queue, hence it's going to be executed as the
very next event.
Note: refactor is implemented in the follow-up commit.
Fixes: scylladb/scylladb#21102
Should be backported to every 6.x …
=> cql/tablets: fix retrying ALTER tablets KEYSPACE

utils/s3/client.cc
File uploading code spawns all parts uploading into background. If this "spawning" fails (not the uploading code itself), any fiber that was spawned before is orphaned. It will eventually stop on its own, by while it's alive it may use(-after-free) the do_upload_file object.
Another issue with not handling spawn exception, is that multipart upload object is not aborted in this case. So it's leaked until garbage collector picks it up, which is not critical, but unpleasant.
=> Do not leak S3 file-uploading parts on exceptions

compaction/compaction.cc, compaction/compaction_manager.cc, compaction/compaction_manager.hh, compaction/table_state.hh, replica/database.hh, replica/table.cc, service/storage_service.cc, test/boost/compaction_group_test.cc, test/lib/test_services.cc, test/pylib/rest_client.py, test/topology_experimental_raft/test_tablets.py, tools/scylla-sstable.cc
During split prepare phase, there will be more than 1 compaction group with
overlapping token range for a given replica.
Assume tablet 1 has sstable A containing deleted data, and sstable B containing
a tombstone that shadows data in A.
Then split starts:
sstable B is split first, and moved from main (unsplit) group to a
split-ready group
now compaction runs in split-ready group before sstable A is split
tombstone GC logic today only looks at underlying group, so compaction is step
2 will discard the deleted data in A, since it belongs to another group (the
unsplit one), and so the tombstone can be purged incorrectly.
To fix it, compaction will now work with all uncompacting sstables that belong
to the same replica, since tombstone GC requires all sstables that possibly
contain shadowed …
=> [Backport 6.0] replica: Fix tombstone GC during tablet split preparation

compaction/compaction.cc, compaction/compaction_manager.cc, compaction/compaction_manager.hh, compaction/table_state.hh, replica/database.hh, replica/table.cc, service/storage_service.cc, test/boost/compaction_group_test.cc, test/lib/test_services.cc, test/pylib/rest_client.py, test/topology_experimental_raft/test_tablets.py, tools/scylla-sstable.cc
During split prepare phase, there will be more than 1 compaction group with
overlapping token range for a given replica.
Assume tablet 1 has sstable A containing deleted data, and sstable B containing
a tombstone that shadows data in A.
Then split starts:
sstable B is split first, and moved from main (unsplit) group to a
split-ready group
now compaction runs in split-ready group before sstable A is split
tombstone GC logic today only looks at underlying group, so compaction is step
2 will discard the deleted data in A, since it belongs to another group (the
unsplit one), and so the tombstone can be purged incorrectly.
To fix it, compaction will now work with all uncompacting sstables that belong
to the same replica, since tombstone GC requires all sstables that possibly
contain shadowed …
=> [Backport 6.1] replica: Fix tombstone GC during tablet split preparation

.github/workflows/iwyu.yaml, dht/i_partitioner.hh, dht/murmur3_partitioner.hh, dht/token.hh
these unused includes are identified by clang-include-cleaner. after auditing the source files, all of the reports have been
confirmed.
---
=> dht: remove unused #includes 

service/topology_coordinator.cc, test/topology/util.py, test/topology_custom/test_tablets_cql.py
ALTER tablets-enabled KEYSPACES (KS) may fail due to
group0_concurrent_modification, in which case it's repeated by a for
loop surrounding the code. But because raft's add_entry consumes the
raft's guard (by std::move'ing the guard object), retries of ALTER KS
will use a moved-from guard object, which is UB, potentially a crash.
The fix is to remove the before mentioned for loop altogether and rethrow the exception, as the rf_change event
will be repeated by the topology state machine if it receives the
concurrent modification exception, because the event will remain present
in the global requests queue, hence it's going to be executed as the
very next event.
Note: refactor is implemented in the follow-up commit.
Fixes: https://github.com/scylladb/scylladb/issues/21102
Should be …
=> [Backport 6.2] cql/tablets: fix retrying ALTER tablets KEYSPACE

compaction/compaction_manager.cc, replica/table.cc, test/topology_experimental_raft/test_tablets.py
To fix a race between split and repair here https://github.com/scylladb/scylladb/commit/c1de4859d815b3eb4aebef7b7e1c7998c6860f76, a new sstable
generated during streaming can be split before being attached to the sstable
set. That's to prevent an unsplit sstable from reaching the set after the
tablet map is resized.
So we can think this split is an extension of the sstable writer. A failure
during split means the new sstable won't be added. Also, the duration of split
is also adding to the time erm is held. For example, repair writer will only
release its erm once the split sstable is added into the set.
This single-sstable split is going through run_custom_job(), which serializes
with other maintenance tasks. That was a terrible decision, since the split may
have to wait for ongoing …
=> [Backport 6.0] tablet: Fix single-sstable split when attaching new unsplit sstables

api/compaction_manager.cc, compaction/compaction.cc, compaction/compaction.hh, compaction/compaction_manager.cc, readers/combined.cc, readers/combined.hh, readers/combined_reader_stats.hh, sstables/sstable_set.cc, sstables/sstable_set.hh, test/boost/mutation_reader_test.cc, test/nodetool/test_compactionhistory.py, test/rest_api/test_compactionhistory.py, tools/scylla-nodetool.cc
Currently, running the `nodetool compactionhistory` command or using the rest api `curl -X GET --header "Accept: application/json" "http://localhost:10000/compaction_manager/compaction_history"` return compaction history without the `row_merged` field.
The series computes rows merged during compaction and provides this information to users via both the nodetool command and the rest api. The `rows_merged` field contains information on merged clustering keys across multiple sstable files. For instance, compacting two sstables of a table consisting of 7 rows where two rows are part of the both sstables, the output would have the following format: {1: 5, 2: 2}.
No backport is required. It extends the existing compaction history output.
Fixes https://github.com/scylladb/scylladb/issues/666
=> Report rows_merged in compaction_history rest api and nodetool

test/boost/sstable_test.cc, test/lib/sstable_utils.hh
There's a `missing_summary_first_last_sane` test case that uses some very specific way of modifying an sstable -- it loads one from resources, then tries to "write" the loaded stuff elsewhere. For that it uses a special purpose test::store() helper and a bunch of auxiliary ones from the same class. Those aux helpers are not used anywhere else and are also very special for this test case, so it make sense to keep this whole functionality in a single helper.
=> Squash some sstables::test helpers

docs/alternator/alternator.md, docs/alternator/new-apis.md
Add a description of the service discovery HTTP requests - `/` and  `/localnodes` that was previously not documented except in a design document that is unfortunately no longer available publically (https://docs.google.com/document/d/1twgrs6IM1B10BswMBUNqm7bwu5HCm47LOYE-Hdhuu_8/edit).
Fixes https://github.com/scylladb/scylladb/issues/20989
Developer-oriented documentation so no need to backport.
=> docs/alternator: explain service discovery HTTP requests

repair/repair.cc, test/topology_custom/test_node_ops_metrics.py
The skipped ranges should be multiplied by the number of tables
Otherwise the finished ranges ratio will not reach 100%.
Fixes #21174
=> repair: Fix finished ranges metrics for removenode

api/token_metadata.cc, locator/token_metadata.cc, locator/token_metadata.hh, service/topology_coordinator.cc, test/nodetool/test_status.py, test/pylib/util.py, test/topology/test_coordinator_queue_management.py, test/topology/test_nodetool.py, tools/scylla-nodetool.cc
In the current scenario, the nodetool status doesn’t display information regarding zero token nodes. For example, if 5 nodes are spun by the administrator, out of which, 2 nodes are zero token nodes, then nodetool status only shows information regarding the 3 non-zero token nodes.
This commit intends to fix this issue by leveraging the “/storage_service/host_id ” API  and adding appropriate logic in scylla-nodetool.cc to support zero token nodes.
A test is also added in nodetool/test_status.py to verify this logic. This test fails without this commit’s zero token node support logic, hence verifying the behavior.
This PR fixes a bug. Hence we need to backport it. Backporting needs to be done only
to 6.2 version, since earlier versions don't support zero token nodes.
Fixes: …
=> fix nodetool status to show zero-token nodes

tasks/task_manager.cc
Fix how regular tasks that have a virtual parent are created 
in task_manager::module::make_task: set sequence number 
of a task and subscribe to module's abort source.
Fixes: #21278.
Needs backport to 6.2
=> tasks: fix virtual tasks children

utils/cached_file.hh
Otherwise, the read will be considered as on-cpu during promoted index
search, which will severely underutlize the disk because by default
on-cpu concurrency is 1.
I verified this patch on the worst case scenario, where the workload
reads missing rows from a large partition. So partition index is
cached (no IO) and there is no data file IO (relies on https://github.com/scylladb/scylladb/pull/20522). 
But there is IO during promoted index search (via cached_file). 
Before the patch this workload was doing 4k req/s, after the patch it does 30k req/s.
The problem is much less pronounced if there is data file or partition index IO involved
because that IO will signal read concurrency semaphore to invite more concurrency.
Fixes #21325
=> utils: cached_file: Mark permit as awaiting on page miss

.github/workflows/iwyu.yaml, auth/standard_role_manager.hh, gms/endpoint_state.cc, gms/feature.hh, gms/feature_service.hh, gms/gossip_digest.hh, gms/gossip_digest_ack.hh, gms/gossip_digest_ack2.hh, gms/gossip_digest_syn.hh, gms/gossiper.cc, gms/gossiper.hh, gms/inet_address.hh, service/load_broadcaster.hh
these unused includes are identified by clang-include-cleaner. after auditing the source files, all of the reports have been
confirmed.
---
=> gms: remove unused #includes 

api/column_family.cc, compound_compat.hh, db/view/view.cc, gms/versioned_value.cc, keys.cc, mutation/mutation_partition.cc, mutation/mutation_partition_v2.cc, readers/mutation_reader.cc, sstables/mx/parsers.hh, sstables/sstable_set.cc, sstables/sstables.cc, sstables/writer.hh, test/boost/compound_test.cc, test/boost/counter_test.cc, test/boost/schema_change_test.cc, test/lib/data_model.cc, test/perf/perf_commitlog.cc, tracing/trace_state.cc
Replace use of boost::ranges::join() with another construct, as it
has no std replacement, and replace other uses with their std
equivalent, in order to reduce dependency load.
Code cleanup - no backport.
=> compound_compat: replace use of boost ranges with std ranges

db/snapshot/backup_task.cc, db/snapshot/backup_task.hh, test/object_store/test_backup.py, utils/s3/client.cc, utils/s3/client.hh, utils/s3/client_fwd.hh
Task manager GET /status method returns two counters that reflect task progress -- total and completed. To make caller reason about their meaning, additionally there's progress_units field next to those counters.
This patch implements this progress report for backup task. The units are bytes, the total counter is total size of files that are being uploaded, and the completed counter is total amount of bytes successfully sent with PUT requests. To get the counters, the client::upload_file() is extended to calculate those.
fixes #20653
=> Collect and report backup progress

node_ops/task_manager_module.cc, node_ops/task_manager_module.hh, tasks/task_manager.cc, tasks/task_manager.hh
Currently, to find the operation with given id, all operations tracked by a virtual task are listed. This isn't necessary, since we only need info regarding one particular operation.
Add a method to check whether a virtual task tracks the operation with the given id.
No backport needed
=> tasks: improve task_manager::lookup_virtual_task

test/boost/chunked_vector_test.cc, utils/chunked_vector.hh
Optimize the various constructors a little, and add an std::from_range_t
constructor.
Minor improvement, so no backports.
=> utils: chunked_vector: various constructor improvements

api/column_family.cc, api/column_family.hh
There's a whole lot of helpers and wrappers in api/ that help handlers manipulate keyspaces and tables. One of those is foreach_column_family which calls the provided callable on a table on each shard. There's exactly the same (but a bit more flexible) helper nearby. While at it, this helper gets a better name.
=> api: Remove foreach_column_family() helper

service/topology_coordinator.cc, test/topology/util.py, test/topology_custom/test_tablets_cql.py
ALTER tablets-enabled KEYSPACES (KS) may fail due to
group0_concurrent_modification, in which case it's repeated by a for
loop surrounding the code. But because raft's add_entry consumes the
raft's guard (by std::move'ing the guard object), retries of ALTER KS
will use a moved-from guard object, which is UB, potentially a crash.
The fix is to remove the before mentioned for loop altogether and rethrow the exception, as the rf_change event
will be repeated by the topology state machine if it receives the
concurrent modification exception, because the event will remain present
in the global requests queue, hence it's going to be executed as the
very next event.
Note: refactor is implemented in the follow-up commit.
Fixes: https://github.com/scylladb/scylladb/issues/21102
Should be …
=> [Backport 6.1] cql/tablets: fix retrying ALTER tablets KEYSPACE

sstables/index_reader.hh
Terminology note: in the context of this series, "index page" means an contiguous segment of the index file starting (inclusive) at a key corresponding to a summary entry and ending (exclusive) before the key corresponding to the next summary entry. "Index pages" are not related to filesystem pages.
---
In a single-partition read, if the searched partition key is the first key in its index page, we start scanning the index for that key starting at the previous index page (inclusive), even though we could start directly from the key's page. Similarly, if the searched partition key is absent from the sstable and lies after all other keys in its appropriate page, we additionally scan the next page, even though it's known from the summary that it can't possibly contain the key.
Those cases …
=> sstables/index_reader: avoid unnecessary index page reads in single-partition reads

alternator/conditions.cc, alternator/executor.cc, alternator/expressions.cc, auth/password_authenticator.cc, auth/roles-metadata.cc, compaction/compaction.cc, compaction/compaction_manager.cc, compaction/compaction_strategy.cc, compaction/size_tiered_compaction_strategy.hh, cql3/functions/as_json_function.hh, cql3/restrictions/statement_restrictions.cc, cql3/selection/selection.cc, cql3/statements/batch_statement.cc, cql3/statements/delete_statement.cc, cql3/statements/select_statement.cc, cql3/user_types.cc, db/view/view.cc, db/virtual_tables.cc, index/secondary_index_manager.cc, partition_snapshot_row_cursor.hh, redis/keyspace_utils.cc, repair/repair.cc, replica/database.cc, streaming/stream_session.cc, test/boost/dynamic_bitset_test.cc, test/boost/partitioner_test.cc, test/boost/row_cache_test.cc, test/boost/sstable_compaction_test.cc, test/boost/sstable_datafile_test.cc
now that we are allowed to use C++23. we now have the luxury of using
`std::ranges::all_of` and `std::ranges::any_of` 
in this change, we replace `boost::algorithm::all_of` and `boost::algorithm::any_of` with
`std::ranges::all_of` and `std::ranges::any_of` respectively.
to reduce the dependency to boost for better maintainability, and leverage standard library features for better long-term support.
this change is part of our ongoing effort to modernize our codebase and reduce external dependencies where possible.
---
=> treewide: trade boost's any_of and all_of for std's any_of and all_of

.github/workflows/iwyu.yaml, cql3/statements/describe_statement.cc, lang/wasm.hh
in this series:
- remove unused `#include` in "lang" subdirectory
- add index and lang to CLEANER_DIR
---
cleanup and improvements in the CI, hence no need to backport.
=> lang, .github: remove unused includes, add more directories to CLEANER_DIR

bytes_ostream.hh
To reduce the dependency load, replace boost ranges with std::ranges.
Cleanup; no backport.
=> bytes_ostream: replace boost ranges with std ranges

api/raft.cc, main.cc, service/raft/raft_group_registry.cc, test/boost/secondary_index_test.cc, test/lib/cql_test_env.cc
In scylladb/scylladb#19745, view_builder was migrated to group0 and since then it is dependant on group0_service.
Because of this, group0_service should be initialized/destroyed before/after view_builder.
This patch also adds error injection to `raft_server_with_timeouts::read_barrier`, which does 1s sleep before doing the read barrier. There is a new test which reproduces the use after free bug using the error injection.
Fixes scylladb/scylladb#20772
scylladb/scylladb#19745 is present in 6.2, so this fix should be backported to it.
=> main,cql_test_env: start group0_service before view_builder

compaction/compaction.cc, compaction/table_state.hh, locator/tablets.cc, locator/tablets.hh, replica/compaction_group.hh, replica/database.hh, replica/table.cc, test/boost/compaction_group_test.cc, test/lib/test_services.cc, tools/scylla-sstable.cc
Split compaction divides the partitions in an existing sstable into two groups and writes them into two new sstables, which replace the original one. The partition count from the original sstable is used as an estimate when writing the new ones, but this estimate is not accurate as the partitions are split between the two new sstables and each will contain only a portion of the original partition count. This also causes the bloom filters to be rebuilt at the end of compaction, as they were initially built with inaccurate estimates.
Fix this by using a better estimate for the output sstables, which is half the original partition count.
Fixes #20253
Improvement; No need to backport.
=> compaction: use better partition estimate for split compaction

.github/workflows/iwyu.yaml, message/messaging_service.hh, message/messaging_service_fwd.hh
these unused includes are identified by clang-include-cleaner. after auditing the source files, all of the reports have been confirmed.
also, update the workflow to prevent future regressions of including unused headers in this subdirectory.
---
=> message: do not include unused headers

compaction/compaction.cc, sstables/checksummed_data_source.cc, sstables/compress.cc, sstables/data_source_types.hh, sstables/kl/reader.cc, sstables/kl/reader.hh, sstables/mx/reader.cc, sstables/mx/reader.hh, sstables/sstable_mutation_reader.hh, sstables/sstable_set.cc, sstables/sstable_set.hh, sstables/sstables.cc, sstables/sstables.hh, sstables/types_fwd.hh, test/boost/sstable_compaction_test.cc
This PR enables compaction tasks to verify the integrity of the input data through checksum and digest checks. The mechanism for integrity checking was introduced in previous PRs (#20207, #20720) as a built-in functionality of the input streams. This PR integrates this mechanism with compaction. The change applies to all compaction types and covers both compressed and uncompressed SSTables adhering to the 3.x format. If a compaction task reads only part of an SSTable, then only the per-chunk checksums are verified, not the digest.
The PR consists of:
* Changes to mx readers to support integrity checking. The kl readers, considered as compatibility-only, were left unchanged. Also, integrity checking on single-partition reversed reads (`data_consume_reversed_partition()`) remains …
=> compaction: Perform integrity checks on compacting SSTables

cql3/statements/prune_materialized_view_statement.cc, mutation/mutation_partition.cc, mutation/mutation_partition.hh, mutation/mutation_partition_v2.cc, mutation/mutation_partition_v2.hh, partition_snapshot_reader.hh, partition_snapshot_row_cursor.hh, test/boost/row_cache_test.cc
Wean the mutation code (at least the headers) from boost ranges to std ranges,
in order to reduce the dependency load. 
Cleanup, so no backport.
=> mutation: switch from boost ranges to std ranges

test/boost/view_schema_test.cc
Before these changes, we didn't wait for the materialized views to
finish building before writing to the base table. That led to generating
an additional view update, which, in turn, led to test failures.
The scenario corresponding to the summary above looked like this:
1. The test creates an empty table and MVs on it.
2. The view builder starts, but it doesn't finish immediately.
3. The test performs mutations to the base table. Since the views
already exist, view updates are generated.
4. Finally, the view builder finishes. It notices that the base
table has a row, so it generates a view update for it because
it doesn't notice that we already have data in the view.
We solve it by explicitly waiting for both views to finish building
and only then start writing to the base table. …
=> test/boost/view_schema_test.cc: Wait for views to build in test_view_update_generating_writetime

repair/repair.cc, repair/task_manager_module.hh, test/topology_custom/test_repair.py
Currently, task_manager_module::abort_all_repairs marks top-level repairs as aborted (but does not abort them) and aborts all existing shard tasks.
A running repair checks whether its id isn't contained in _aborted_pending_repairs and then proceeds to create shard tasks. If abort_all_repairs is executed after _aborted_pending_repairs is checked but before shard tasks are created, then those new tasks won't be aborted. The issue is the most severe for tablet_repair_task_impl that checks the _aborted_pending_repairs content from different shards, that do not see the top-level task. Hence the repair isn't stopped but it creates shard repair tasks on all shards but the one that initialized repair.
Abort top-level tasks in abort_all_repairs. Fix the shard on which the task abort is checked. …
=> repair: fix task_manager_module::abort_all_repairs

cql3/selection/selection.cc, cql3/selection/selection.hh, cql3/statements/select_statement.cc, cql3/statements/select_statement.hh, test/cqlpy/cassandra_tests/validation/operations/compact_storage_test.py, test/cqlpy/cassandra_tests/validation/operations/select_group_by_test.py, test/cqlpy/test_group_by.py
Currently, PER PARTITION LIMIT is not implemented for aggregates and queries can result in more rows than expected from the same partition. 
Instrument the result_set_builder class so that it can enforce PER PARTITION LIMIT for aggregate queries, specifically:
- add per_partition_limit to the result_set_builder
- expose the number of input rows in the selector
result_set_builder gets two new functions handling partition start and end:
- accept_partition_end for notifying that a partition has been finished. This is also called when a page ends, so we cannot simply flush here, as a naive implementation could do.
- accept_new_partition, where we flush_selectors() if it's indeed a new partition (and not a continuation of the previous) and the query has a grouping: we don't want to flush on …
=> cql3: respect PER PARTITION LIMIT for aggregate queries

alternator/executor.cc, combine.hh, counters.hh, cql3/restrictions/statement_restrictions.cc, db/size_estimates_virtual_reader.cc, db/view/view.cc, index/secondary_index.cc, locator/util.cc, replica/database.cc, service/storage_service.cc, service/topology_state_machine.hh, sstables/compress.cc, test/boost/sstable_compaction_test.cc, test/boost/sstable_datafile_test.cc, test/lib/data_model.cc, test/manual/enormous_table_scan_test.cc, tools/schema_loader.cc, tools/scylla-nodetool.cc, tools/scylla-sstable.cc
now that we are allowed to use C++23. we now have the luxury of using `std::ranges::find_if`.
in this change, we:
- replace `boost::find_if` with `std::ranges::find_if`
- remove all `#include <boost/range/algorithm/find_if.hpp>`
to reduce the dependency to boost for better maintainability, and leverage standard library features for better long-term support.
this change is part of our ongoing effort to modernize our codebase and reduce external dependencies where possible.
---
=> treewide: replace boost::find_if with std::ranges::find_if

api/api-doc/storage_service.json, api/storage_service.cc, db/system_keyspace.cc, docs/dev/system_keyspace.md, docs/dev/topology-over-raft.md, gms/feature_service.hh, idl/storage_service.idl.hh, locator/network_topology_strategy.cc, locator/tablets.cc, locator/tablets.hh, message/messaging_service.cc, message/messaging_service.hh, repair/repair.cc, repair/row_level.hh, replica/tablet_mutation_builder.hh, replica/tablets.cc, replica/tablets.hh, service/storage_service.cc, service/storage_service.hh, service/tablet_allocator.cc, service/tablet_allocator.hh, service/topology_coordinator.cc, test/pylib/repair.py, test/pylib/rest_client.py, test/topology_experimental_raft/test_tablet_repair_scheduler.py
This adds a new tablet migration kind: repair. It allows tablet repair
scheduler to use this migration kind to schedule repair jobs.
The current repair scheduler implementation does the following:
- A tablet is picked to be repaired when is requested by user
- The tablet repair can be scheduled along with tablet migration and
rebuild. It runs in the tablet_migration track.
- Repair jobs are scheduled in a smart way so that at any point in time,
there are no more than configured jobs per shard, which is similar to
scylla manager's control.
New feature. No backport is needed.
=> Add tablet repair scheduler support

readers/combined.cc, readers/multishard.cc, readers/mutation_reader.cc
With C++23, we have ranges available. Migrate the code in `readers/` to use ranges, to reduce our dependency on boost (and modernize the code a bit).
Improvement, no backport required
=> readers: migrate to std::ranges

db/config.cc, db/config.hh, repair/repair.cc, repair/row_level.cc, repair/row_level.hh, repair/task_manager_module.hh
The non local strategy system keyspaces usually contain very litte data.
All the tables within them have to be repaired for all the token ranges,
which could be large in clusters with a large number of nodes. In multiple
DC setup, the repair in RBNO is dominated by the network latency. As a
result, it takes a long time to repair those tables even if they are
almost empty.
To speed up the RBNO bootstrap, especially for starting empty clusters,
this patch enables small table optimization for RBNO for system tables.
We could enable it for small user tables as a follow up.
Tests:
1) A 5ms latency is added to simulate cross dc network delay, 256 tokens
per node, 10 nodes:
- Before
topology_custom dev topology_custom.test_boot_time.1 1287.06s
- After
topology_custom dev …
=> repair: Enable small table optimization for RBNO bootstrap and decommission

locator/token_metadata.cc, locator/token_metadata.hh
Reduce dependency load by standardizing on std::ranges. This is a little
involved since a we use a custom iterator.
Code cleanup; no backport.
=> locator: token_metadata: replace boost range with std range

docs/operating-scylla/_common/tools_index.rst, docs/operating-scylla/admin-tools/sstabledump.rst, docs/operating-scylla/admin-tools/sstableloader.rst, docs/operating-scylla/admin-tools/sstablemetadata.rst
Java tools are deprecated and slated for removal in the next ScyllaDB release.
Update the admin-tools docs and make sure all java tool documentation pages have a notice reflecting this fact.
Fixes: https://github.com/scylladb/scylladb/issues/21149
Should be backported to 6.2, so users of the latest stable version can see the notice.
=> docs: update admin-tools docs with deprecation and removal notice for java tools

sstables_loader.cc, sstables_loader.hh, test/object_store/suite.yaml, test/object_store/test_backup.py
Previously, the progress of download_task_impl launched by the "restore" API
was not tracked. Since restore operations can involve large data transfers,
this makes it difficult for users to monitor progress.
The restore process happens in two sequential steps:
1. Open specified SSTables from object storage
2. Download and stream mutation fragments from the opened SSTables to
mapped destinations
While both steps contribute to overall progress, they use different units
of measurement, making a unified progress metric challenging. Because
the load-and-stream step (step 2) is the largest time-consuming part of the
restore. This change implements progress tracking for this step as an
initial improvement to provide users with partial visibility into the
restore operation.
Fixes …
=> replica,sstables: track download progress of download_task_impl

service/storage_service.cc, service/topology_state_machine.hh
Topology request table may change between the code reading it and
calling to cv::when() since reading is a preemption point. In this
case cv:signal can be missed. Detect that there was no signal in between
reading and waiting by introducing reload_count which is increased each
time the state is reloaded and signaled. If the counter is different
before and after reading the state may have change so re-check it again
instead of sleeping.
=> topology_coordinator: introduce reload_count in topology state and use it to prevent race

auth/passwords.cc, auth/passwords.hh
In this PR, we get rid of the unnecessary default switch case in `prefix_for_scheme()`. We also change the return type of the function to `std::string_view` as it's easier to operate on.
Backport: not needed; this is a code cleanup.
=> auth/passwords: Clean up prefix_for_scheme()

generic_server.cc, generic_server.hh, service/client_state.cc, service/client_state.hh, service/qos/service_level_controller.cc, service/qos/service_level_controller.hh, transport/server.cc
This patch reverts 324b3c43c017b9d7b6f38088f74c55eb58d02c93 and adds synchronous versions of `service_level_controller::find_effective_service_level()` and `client_state::maybe_update_per_service_level_params()`.
It isn't safe to do asynchronous calls in `for_each_gently`, as the
connection may be disconnected while a call in callback preempts.
Fixes https://github.com/scylladb/scylladb/issues/21801
=> transport/server: revert using async function in `for_each_gently()`

service/storage_service.cc, service/topology_coordinator.cc, test/topology_custom/test_view_build_status.py
The migration process is doing read with consistency level ALL,
requiring all nodes to be alive.
Fixes scylladb/scylladb#20754
The PR should be backported to 6.2, this version has view builder on group0.
=> service/topology_coordinator: migrate view builder only if all nodes are up

docs/dev/topology-over-raft.md, gms/feature_service.hh, locator/tablets.cc, locator/tablets.hh, replica/compaction_group.hh, replica/table.cc, scripts/tablet-mon.py, service/storage_service.cc, service/tablet_allocator.cc, service/tablet_allocator.hh, service/topology_coordinator.cc, service/topology_state_machine.cc, service/topology_state_machine.hh, test/boost/tablets_test.cc, test/topology_experimental_raft/test_tablets.py, test/topology_experimental_raft/test_tablets_merge.py
The goal of merge is to reduce the tablet count for a shrinking table. Similar to how split increases the count while the table is growing. The load balancer decision to merge is implemented today (came with infrastructure introduced for split), but it wasn't handled until now.
Initial tablet count is respected while the table is in "growing mode". For example, the table leaves it if there was a need to split above the initial tablet count. After the table leaves the mode, the average size can be trusted to determine that the table is shrinking. Merge decision is emitted if the average tablet size is 50% of the target. Hysteresis is applied to avoid oscillations between split and merges.
Similar to split, the decision to merge is recorded in tablet map's resize_type field with the string …
=> Add tablet merge support

gms/feature_service.hh, locator/tablets.cc, locator/tablets.hh, replica/tablet_mutation_builder.hh, replica/tablets.cc, service/storage_service.cc, service/tablet_allocator.cc, service/task_manager_module.cc, service/task_manager_module.hh, service/topology_coordinator.cc, tasks/task_manager.cc, tasks/virtual_task_hint.hh, test/boost/tablets_test.cc, test/topology_tasks/test_tablet_tasks.py
In this change, tablet_virtual_task starts supporting tablet
migration, in addition to tablet repair. Both tablet operations 
reuse the same virtual_task because their task data is retrieved
similarly. However, it changes nothing from the task manager 
API users' perspective. They can list running migrations or check 
their statuses all the same as if migration had its own virtual_task. 
Users can see running migration tasks - finished tasks are not 
presented with the task manager API. However, the result 
of the migration (whether it succeeded or failed) would be
presented to users, if they use wait API.
If a migration was reverted, it will appear to users as failed.
We assume that the migration was reverted, when its destination
does not contain a tablet replica.
Fixes: …
=> tasks: add tablet migration virtual task

db/config.cc, db/config.hh, db/view/view.cc, db/view/view_update_backlog.hh, db/view/view_update_generator.cc, service/misc_services.cc, service/storage_proxy.cc, test/topology_custom/test_mv_backlog.py
This pull request is continuation of scylladb/scylladb#20688 - contents of the main commit are the same, the only change is the additional commit with a test.
Until this patch, the materialized view flow-control algorithm (https://www.scylladb.com/2018/12/04/worry-free-ingestion-flow-control/) used a constant delay_limit_us hard-coded to one second, which means that when the size of view-update backlog reached the maximum (10% of memory), we delay every request by an additional second - while smaller amounts of backlog will result in smaller delays.
This hard-coded one maximum second delay was considered *huge* - it will slow down a client with concurrency 1000 to just 1000 requests per second - but we already saw some workloads where it was not enough - such as a test workload running …
=> materialized view: make flow-control maximum delay configurable

auth/default_authorizer.cc, auth/default_authorizer.hh, db/hints/resource_manager.hh, locator/ec2_multi_region_snitch.hh
this issue was identified by clang-20.
---
=> db,auth,locator: Remove unused member variables

test/boost/cache_algorithm_test.cc
This series attempts to get read of flakiness in `cache_algorithm_test` by solving two problems.
Problem 1:
The test needs to create some arbitrary partition keys of a given size. It intends to create keys of the form:
0x0000000000000000000000000000000000000000...
0x0100000000000000000000000000000000000000...
0x0200000000000000000000000000000000000000...
But instead, unintentionally, it creates partially initialized keys of the form: 0x0000000000000000garbagegarbagegarbagegar...
0x0100000000000000garbagegarbagegarbagegar...
0x0200000000000000garbagegarbagegarbagegar...
Each of these keys is created several times and -- for the test to pass -- the result must be the same each time.
By coincidence, this is usually the case, since the same allocator slots are used. But if some background …
=> cache_algorithm_test: fix flaky failures

test/alternator/test_cql_rbac.py, test/alternator/test_gsi.py, test/alternator/test_gsi_updatetable.py, test/alternator/test_lsi.py, test/alternator/test_metrics.py, test/cqlpy/test_materialized_view.py
This patch includes more tests (in Python) that I wrote while implementing the Alternator UpdateTable feature for adding a GSI to an existing table (https://github.com/scylladb/scylladb/issues/11567).
I explain each of these tests in the separate patches below, but basically they fall into two types:
1. Tests which pass with today's materialized views and Alternator GSI/LSI, and serve to ensure that whatever changes I do to the view update implementation, doesn't break corner cases that already worked.
2. Tests for the UpdateTable feature in Alternator which doesn't work today so xfail - and will need to work for #11567. We already had a few tests for this, but here I add more and improve coverage of various corner cases I discovered while implementing the featue.
I already have a working …
=> More Python tests for materialized view and Alternator GSI feature

data_dictionary/storage_options.hh, replica/distributed_loader.cc, replica/distributed_loader.hh, sstables/storage.cc, sstables_loader.cc, test/object_store/test_backup.py, utils/s3/client.cc, utils/s3/client.hh
Fixes #20717
Enables abortable interface and propagates abort_source to all s3 objects used for reading the restore data.
Note: because restore is done on each shard, we have to maintain a per-shard abort source proxy for each, and do a background per-shard abort on abort call. This is synced at the end of "run()".
Abort source is added as an optional parameter to s3 storage and the s3 path in distributed loader. 
There is no attempt to "clean up" an aborted restore. As we read on a mutation level from remote sstables, we should not cause incomplete sstables as such, even though we might end up of course with partial data restored.
=> Make restore task abortable

sstables/sstables.cc, sstables/sstables.hh, sstables/sstables_manager.cc, sstables/sstables_manager.hh, test/boost/bloom_filter_test.cc, test/lib/sstable_test_env.hh
When an sstable is unlinked, it remains in the _active list of the
sstable manager. Its memory might be reclaimed and later reloaded,
causing issues since the sstable is already unlinked. This patch updates
the on_unlink method to reclaim memory from the sstable upon unlinking,
remove it from memory tracking, and thereby prevent the issues described
above.
Added a testcase to verify the fix.
Fixes #21887
This is a bug fix in the bloom filter reload/reclaim mechanism and should be backported to older versions.
=> sstables_manager: do not reclaim unlinked sstables

locator/topology.cc, locator/topology.hh, test/boost/network_topology_strategy_test.cc
This series converts the call site using compare_endpoints with gms::inet_address.
With that both flavors of compare_endpoints and sort_by_proximity for inet_address
can be retired as no other uses remain.
Also, add a unit test for topology::sort_by_proximity before further changes
to it are considered.
* Code cleanup, no backport is needed
=> Retire topology::sort_by_proximity and compare_endpoints flavors using gms::inet_address

api/column_family.cc, index/built_indexes_virtual_reader.hh, test/cqlpy/test_materialized_view.py, test/cqlpy/test_secondary_index.py
It turned out that aforementioned APIs use slightly different sources of information about view build progress/status which sometimes results in different reporting of whether an index is built. It's good to make those two APIs consistent. Also add a test for the REST API endpoint (system table test was addressed by #21677).
=> Make get_built_indexes REST API endpoint be consistent with system."IndexInfo" table

test/topology_random_failures/cluster_events.py, test/topology_random_failures/error_injections.py, test/topology_random_failures/test_random_failures.py
There are many CI failures (repros of https://github.com/scylladb/scylladb/issues/21534) which caused by `stop_after_setting_mode_to_normal_raft_topology` and `stop_before_becoming_raft_voter` error injections in combination with some cluster events.
Need to deselect them for now to make CI more stable.  First batch deselected in https://github.com/scylladb/scylladb/pull/21658
Also, add the handling of topology state rollback caused by `stop_before_streaming` or `stop_after_updating_cdc_generation` error injections as a separate commit.
See also https://github.com/scylladb/scylladb/issues/21872 and https://github.com/scylladb/scylladb/issues/21957
=> topology_random_failures: deselect more cases which can cause #21534

test.py
test.py: only access combined_tests executable if it is built 
Fixes #22038
=> test.py: only access combined_tests executable if it is built

replica/compaction_group.hh, replica/database.hh, replica/table.cc, service/storage_service.cc, test/topology_custom/test_mv_topology_change.py
Commit f2ff701489995fdc84ea7ca0addbec2918c35be4 introduced
a yield in update_effective_replication_map that might
cause the storage_group manager to be inconsistent with the
new effective_replication_map (e.g. if yielding right
before calling `handle_tablet_split_completion`.
Also, yielding inside storage_service::replicate_to_all_cores
update loop means that base tables and their views
aren't updated atomically, that caused scylladb/scylladb#17786
This change essentially reverts f2ff701489995fdc84ea7ca0addbec2918c35be4
and makes handle_tablet_split_completion synchronous too.
The stopped compaction groups future is kept as a member and
storage_group_manager::stop() consumes this future during table::stop().
- storage_service: replicate_to_all_cores: update base and view tables atomically …
=> table: make update_effective_replication_map sync again

cql3/Cql.g, cql3/expr/expression.cc, cql3/expr/prepare_expr.cc, cql3/selection/selectable.cc, cql3/selection/selection.cc, cql3/selection/selection.hh, cql3/statements/select_statement.cc, docs/cql/dml/select.rst, docs/cql/types.rst, service/mapreduce_service.cc, service/pager/query_pagers.cc, test/cqlpy/cassandra_tests/validation/entities/collections_test.py, test/cqlpy/cassandra_tests/validation/operations/select_order_by_test.py, test/cqlpy/test_select_collection_element.py
This adds to the grammar the option to SELECT a specific element in a collection (map/set/list).
For example:
`SELECT map['key'] FROM table`
`SELECT map['key1']['key2'] FROM table`
This feature was implemented in Cassandra 4.0 and was requested by scylla users.
The behavior is mostly compatible with Cassandra, except:
1. in SELECT, we allow list subscript in a selector, while cassandra allows only map and set.
2. in UPDATE, we allow set subscript in a column condition, while cassandra allows only map and list.
3. the slice syntax `SELECT m[a..b]` is not implemented yet
4. null subscript - `SELECT m[null]` returns null in scylla, while cassandra returns error
Fixes #7751 
backport was requested for a user to be able to use it
=> cql3: allow SELECT of specific collection element

replica/table.cc, test/boost/serialized_action_test.cc, utils/phased_barrier.hh
- utils: phased_barrier: advance_and_await: allocate new gate only when needed
- utils: phased_barrier: add close() method
- and use in existing services
* Improvement. No backport needed
=> Phased barrier improvements

test.py
test.py: Only check existence of Scylla executable
Previously, we had inconsistent behavior around missing executables:
- 561e88f0 added early failure if any executable was missing
- 8b7a5ca8 added a partial skip for combined_test, but didn't properly
handle build paths and artifacts
This change:
1. Moves executable existence check to PythonTestSuite class
2. Only adds combined_test suite when the executable exists
3. Eliminates redundant os.access() checks
4. Corrects the path to combined_test when checking for its existence
This allows running tests with a partial build while properly handling
missing executables, particularly for the combined_test suite.
Fixes scylladb/scylladb#22086
---
no need to backport, because the offending commit (8b7a5ca88d) is not included by any LTS branches …
=> test.py: check for existence of combined test with correct path

test/alternator/conftest.py, test/alternator/run, test/alternator/suite.yaml, test/alternator/test_cql_rbac.py, test/alternator/test_service_levels.py
The recent pull request https://github.com/scylladb/scylladb/pull/22031 introduced some regressions into the test/alternator framework. For a long time now, tests can create their own CQL roles for testing role-based features. But the new service levels test changed the "run" script and test.py's "suite.yaml" to create a new role and service level just for one test. This is not only ugly (the test code is now split to two places) and unnecessary, this setup also means that you can't run this test against an already-running copy of Scylla which wasn't prepared with the "right" role and service level. Even worse - the code that was added test/alternator/run was plain wrong - it used an outdated keyspace name (the code in suite.yaml was fine).
So in this patch I remove that extra run and …
=> Clean up test/alternator mistakes that service levels introduced

service/tablet_allocator.cc, service/topology_coordinator.cc, test/boost/tablets_test.cc, test/topology_custom/test_tablets.py
Main problem:
If we're draining the last node in a DC, we won't have a chance to
evaluate candidates and notice that constraints cannot be satisfied (N
< RF). Draining will succeed and node will be removed with replicas
still present on that node. This will cause later draining in the same
DC to fail when we will have 2 replicas which need relocaiton for a
given tablet.
The expected behvior is for draining to fail, because we cannot keep
the RF in the DC. This is consistent, for example, with what happens
when removing a node in a 2-node cluster with RF=2.
Fixes #21826
Secondary problem:
We allowed tablet_draining transition to be exited with undrained nodes, leaving replicas on nodes in the "left" state.
Third problem: 
We removed DOWN nodes from the candidate node set, even when …
=> Fix edge case issues related to tablet draining 

db/system_keyspace.cc, db/system_keyspace.hh, node_ops/task_manager_module.cc, test/topology_tasks/test_node_ops_tasks.py
node_ops_virtual_task does not filter the entries of system.topology_request 
and so it creates statuses of operations that aren't node ops.
Filter the entries used by node_ops_virtual_task. With this change, the status 
of a bootstrap of the first node will not be visible.
Fixes: https://github.com/scylladb/scylladb/issues/22008.
Needs backport to 6.2 that introduced node_ops_virtual_task
=> node_ops: filter topology_requests entries shown by node_ops_virtual_task

test/boost/cache_algorithm_test.cc
This series attempts to get read of flakiness in cache_algorithm_test by solving two problems.
Problem 1:
The test needs to create some arbitrary partition keys of a given size. It intends to create keys of the form:
0x0000000000000000000000000000000000000000...
0x0100000000000000000000000000000000000000...
0x0200000000000000000000000000000000000000...
But instead, unintentionally, it creates partially initialized keys of the form: 0x0000000000000000garbagegarbagegarbagegar...
0x0100000000000000garbagegarbagegarbagegar...
0x0200000000000000garbagegarbagegarbagegar...
Each of these keys is created several times and -- for the test to pass -- the result must be the same each time.
By coincidence, this is usually the case, since the same allocator slots are used. But if some background task …
=> [Backport 6.1] cache_algorithm_test: fix flaky failures

test/boost/cache_algorithm_test.cc
This series attempts to get read of flakiness in cache_algorithm_test by solving two problems.
Problem 1:
The test needs to create some arbitrary partition keys of a given size. It intends to create keys of the form:
0x0000000000000000000000000000000000000000...
0x0100000000000000000000000000000000000000...
0x0200000000000000000000000000000000000000...
But instead, unintentionally, it creates partially initialized keys of the form: 0x0000000000000000garbagegarbagegarbagegar...
0x0100000000000000garbagegarbagegarbagegar...
0x0200000000000000garbagegarbagegarbagegar...
Each of these keys is created several times and -- for the test to pass -- the result must be the same each time.
By coincidence, this is usually the case, since the same allocator slots are used. But if some background task …
=> [Backport 6.2] cache_algorithm_test: fix flaky failures

service/storage_proxy.cc, service/storage_proxy.hh, test/topology/util.py, test/topology_custom/test_conflicting_keys_read_repair.py
This update addresses an issue in the mutation diff calculation algorithm used during read repair. Previously, the algorithm used `token` as the hashmap key. Since `token` is calculated basing on the Murmur3 hash function, it could generate duplicate values for different partition keys, causing corruption in the affected rows' values.
Fixes scylladb/scylladb#19101
Since the issue affects all the relevant scylla versions, backport to: 6.1, 6.2
=> Fix possible data corruption due to token keys clashing in read repair.

docs/cql/describe-schema.rst, docs/operating-scylla/security/authorization.rst, test/boost/auth_test.cc
As part of #18750, we added a CQL statement CREATE ROLE WITH SALTED HASH that prevented hashing a password when creating a role, effectively leading to inserting a hash given by the user directly into the database. In #21350, we noticed that Cassandra had implemented a CQL statement of similar semantics but different syntax. We decided to rename Scylla's statement to be compatible with Cassandra. Unfortunately, we didn't notice one more difference between what we had in Scylla and what was part of Cassandra.
Scylla's statement was originally supposed to only be used when restoring the schema and the user needn't have to be aware of its existence at all: the database produced a sequence of CQL statements that the user saved to a file and when a need to restore the schema arose, they would …
=> docs: Update documentation on CREATE ROLE WITH HASHED PASSWORD

api/api.cc, api/api_init.hh, api/compaction_manager.cc, api/config.cc, api/config.hh, api/storage_service.cc, api/stream_manager.cc, docs/operating-scylla/nodetool-commands/getcompactionthroughput.rst, docs/operating-scylla/nodetool-commands/getstreamthroughput.rst, docs/operating-scylla/nodetool-commands/setcompactionthroughput.rst, docs/operating-scylla/nodetool-commands/setstreamthroughput.rst, docs/operating-scylla/nodetool.rst, streaming/stream_manager.hh, test/nodetool/test_compaction_throughput.py, test/nodetool/test_stream_throughput.py, test/rest_api/test_system.py, tools/scylla-nodetool.cc, utils/config_file.hh
In Scylla there are two options that control IO bandwidth limit -- the /storage_service/(compaction|stream)_throughput REST API endpoints. The endpoints are partially implemented and have no counterparts in the nodetool.
This set implements the missing bits and adds tests for new functionality.
=> Complete implementation of configuring IO bandwidth limits

test/pylib/scylla_cluster.py
- use "foo not in bar" instead of "not foo in bar"
- test/pylib: use foo instead of `'{}'.format(foo)`
---
=> test/pylib: two trivial cleanups

main.cc, test/lib/cql_test_env.cc, test/topology_custom/test_mv_building.py
In this PR, we pair draining the view builder with its start.
To better understand what was done and why, let's first look at the
situation before this commit and the context of it:
(a) The following things happened in order:
1. The view builder would be constructed.
2. Right after that, a deferred lambda would be created to stop the
view builder during shutdown.
3. group0_service would be started.
4. A deferred lambda stopping group0_service would be created right
after that.
5. The view builder would be started.
(b) Because the view builder depends on group0_client, it couldn't be
started before starting group0_service. On the other hand, other
services depend on the view builder, e.g. the stream manager. That
makes changing the order of initialization a difficult problem,
so we want to …
=> main, view: Pair view builder drain with its start

raft/server.cc, service/raft/raft_group0.cc, test/topology_custom/test_error_becoming_voter.py
When a node is bootstrapped and joined a cluster as a non-voter and changes it's role to a voter, errors can occur while committing a new Raft record, for instance, if the Raft leader changes during this time. These errors are not critical and should not cause a node crash, as the action can be retried.
Fixes scylladb/scylladb#20814
Backport: This issue occurs frequently and disrupts the CI workflow to some extent. Backports are needed for versions 6.1 and 6.2.
=> raft: Handle non-critical config update errors in when changing voter status.

db/view/view.cc
When adding a new view for building, first write the status to the
system tables and then add the view building step that will start
building it.
Otherwise, if we start building it before the status is written to the
table, it may happen that we complete building the view, write the
SUCCESS status, and then overwrite it with the STARTED status. The
view_build_status table will remain in incorrect state indicating the
view building is not complete.
Fixes #20638 
The PR contains few additional small fixes in separate commits related to the view build status table.
It addresses flakiness issues in tests that use the view build status table to determine when view building is complete. The table may be in incorrect state due to these issues, having a row with status STARTED when it actually …
=> view_builder: write status to tables before starting to build

api/api-doc/task_manager.json, gms/feature_service.hh, locator/tablets.cc, locator/tablets.hh, node_ops/task_manager_module.cc, node_ops/task_manager_module.hh, replica/compaction_group.hh, replica/database.hh, replica/table.cc, replica/tablet_mutation_builder.hh, replica/tablets.cc, service/storage_service.cc, service/storage_service.hh, service/task_manager_module.cc, service/task_manager_module.hh, service/topology_coordinator.cc, tasks/task_manager.cc, tasks/task_manager.hh, tasks/types.hh, test/boost/sstable_set_test.cc, test/boost/tablets_test.cc, test/topology_tasks/task_manager_types.py, test/topology_tasks/test_tablet_tasks.py
In this change, tablet_virtual_task starts supporting tablet
resize (i.e. split and merge).
Users can see running resize tasks - finished tasks are not
presented with the task manager API.
A new task state "suspended" is added. If a resize was revoked, 
it will appear to users as suspended. We assume that the resize was revoked
when the tablet number didn't change.
Fixes: #21366.
Fixes: #21367.
No backport, new feature
=> tasks: add tablet resize virtual task

replica/database.cc, replica/table.cc, schema/schema.cc, schema/schema_registry.cc, schema/schema_registry.hh, service/migration_manager.cc, test/boost/schema_registry_test.cc, test/cqlpy/test_materialized_view.py
Currently, when we load a frozen schema into the registry, we lose
the base info if the schema was of a view. Because of that, in various
places we need to set the base info again, and in some codepaths we
may miss it completely, which may make us unable to process some
requests (for example, when executing reverse queries on views).
Even after setting the base info, we may still lose it if the schema
entry gets deactivated due to all `schema_ptr`s temporarily dying.
To fix this, this patch adds the base schema to the registry, alongside
the view schema. We store just the frozen base schema, so that we can
transfer it across shards. With the base schema, we can now set the base
info when returning the schema from the registry. As a result, we can now
assume that all view schemas returned …
=> Cache base info for view schemas in the schema registry

idl/storage_service.idl.hh, message/messaging_service.cc, repair/repair.cc, repair/row_level.cc, repair/row_level.hh, repair/task_manager_module.hh, replica/tablets.cc, replica/tablets.hh, service/storage_service.cc, service/storage_service.hh, service/tablet_operation.hh, service/topology_coordinator.cc, test/boost/tablets_test.cc, test/perf/perf_tablets.cc, test/pylib/repair.py, test/topology_custom/test_tablet_repair_scheduler.py, tombstone_gc.cc, tombstone_gc.hh
The repair_time in system.tablets will be updated when repair runs
successfully. We can now use it to update the repair time for tombstone
gc, i.e, when the system.tablets.repair_time is propagated, call
gc_state.update_repair_time() on the node that is the owner of the
tablet.
Since b3b3e880d3391 ("repair: Reduce hints and batchlog flush"), the
repair time that could be used for tombstone gc might be smaller than
when the repair is started, so the actual repair time for tombstone gc
is returned by the repair rpc call from the repair master node.
Fixes #17507
New feature. No backport is needed.
=> repair: Wire repair_time in system.tablets for tombstone gc

ent/encryption/encrypted_file_impl.cc, ent/encryption/encryption.cc, ent/encryption/encryption_config.cc, ent/encryption/gcp_host.cc, ent/encryption/kmip_host.cc, main.cc
in this changeset, some misspellings identified by codespell were corrected.
---
=> main, encryption: correct misspellings

configure.py, cql3/statements/batch_statement.cc, test/boost/CMakeLists.txt, test/boost/cql_functions_test.cc, test/boost/unique_view_test.cc, utils/unique_view.hh
In order to reduce the dependency on external libraries, and for better integration with ranges in C++ standard library. let's use the homebrew `utils::views::unique()` before unique is accepted by the C++ standard.
---
=> cql3, test, utils: switch from boost::adaptors::uniqued to utils::views:unique 

main.cc, test/auth_cluster/test_raft_service_levels.py
This PR contains the missing part of a fix for scylladb/scylla-enterprise#4912 which was omitted during migration of workload prioritization to the source available repository. Even though the regression test for it was ported, it was silently made ineffective by a different fix (scylladb/scylla-enterprise#4764), so this PR also improves the test.
Fixes: scylladb/scylladb#22404
No need to backport - service levels are not yet a part of any source-available release.
=> main: rename `cql_sg_stats` metrics on scheduling group rename

main.cc, service/storage_service.cc, service/storage_service.hh, test/lib/cql_test_env.cc
There's such a reference on storage_service itself, it can use this->_sys_dist_ks instead thus making its API (both internal and external) a bit simpler.
=> Remove sharded<system_distributed_keyspace>& argument from storage_service::join_cluster()

configure.py, test/boost/bloom_filter_test.cc, test/boost/loading_cache_test.cc, test/boost/reader_concurrency_semaphore_test.cc, test/boost/view_build_test.cc, test/lib/CMakeLists.txt, test/lib/eventually.cc, test/lib/eventually.hh, test/raft/replication.hh, utils/loading_cache.hh
This series exposes a Clock template parameter for loading_cache so that the test could use
the manual_clock rather than the lowres_clock, since relying on the latter is flaky.
In addition, the test load function is simplified to sleep some small random time and co_return the expected string,
rather than reading it from a real file, since the latter's timing might also be flaky, and it out-of-scope for this test.
Fixes #20322
* The test was flaky forever, so backport is required for all live versions.
=> Simplify loading_cache_test and use manual_clock

api/api-doc/storage_service.json, api/storage_service.cc, db/snapshot-ctl.cc, db/snapshot-ctl.hh, db/snapshot/backup_task.cc, db/snapshot/backup_task.hh, test/object_store/test_backup.py, test/pylib/rest_client.py
Previously, during backup, SSTable components are preserved in the
snapshot directory even after being uploaded. This leads to redundant
uploads in case of failed backups or restarts, wasting time and
resources (S3 API calls).
This change removes SSTable components from the snapshot directory once
they are successfully uploaded to the target location. This prevents
re-uploading the same files and reduces disk usage.
This change only "Refs" https://github.com/scylladb/scylladb/issues/20655, because, we can further optimize
the backup process, consider:
- Sending HEAD requests to S3 to check for existing files before uploading.
- Implementing support for resuming partially uploaded files.
Fixes https://github.com/scylladb/scylladb/issues/21799
Refs …
=> backup_task: remove a component once it is uploaded 

replica/database.cc, replica/table.cc, test/topology_custom/test_tablets.py
`tablet_storage_group_manager::all_storage_groups_split()` calls `set_split_mode()` for each of its storage groups to create split ready compaction groups. It does this by iterating through storage groups using `std::ranges::all_of()` which is not guaranteed to iterate through the entire range, and will stop iterating on the first occurrence of the predicate (`set_split_mode()`) returning false. `set_split_mode()` creates the split compaction groups and returns false if the storage group's main compaction group or merging groups are not empty. This means that in cases where the tablet storage group manager has non-empty storage groups, we could have a situation where split compaction groups are not created for all storage groups.
The missing split compaction groups are later created in …
=> split: run set_split_mode() on all storage groups during all_storage_groups_split()

alternator/server.cc, alternator/server.hh, generic_server.cc, generic_server.hh, message/messaging_service.cc, redis/controller.cc, transport/controller.cc
Refs https://github.com/scylladb/seastar/issues/2513
Reloadable certificates use inotify instances. On a loaded test (CI) server, we've seen cases where we literally run out of capacity. This patch uses the extended callback and reload capability of seastar TLS to only create actual reloadable certificate objects on shard 0 for our main TLS points (encryption only does TLS on shard 0 already).
=> TLS: reduce inotify usage by sharing reloadability across shards

service/storage_service.cc, service/topology_coordinator.cc, service/topology_state_machine.cc, service/topology_state_machine.hh
Truncate table for tablets is implemented as a global topology operation. However, it does not have a transition state associated with it, and performs the truncate logic in `topology_coordinator::handle_global_request()` while `topology::tstate` remains empty. This creates problems because `topology::is_busy()` uses transition_state to determine if the topology state machine is busy, and will return false even though a truncate operation is ongoing.
This change introduces a new topology transition `topology::transition_state::truncate_table` and moves the truncate logic to a new method `topology_coordinator::handle_truncate_table()`. This method is now called as a handler of the `truncate_table` transition state instead of a handler of the `trunacate_table` global topology request.
This …
=> truncate: trigger truncate logic from a transition state instead of global topology request

locator/abstract_replication_strategy.cc, repair/repair.cc, test/topology_custom/test_repair.py
Currently, data sync repair handles most no_such_keyspace exceptions,
but it omits the preparation phase, where the exception could be thrown
during make_global_effective_replication_map.
Skip the keyspace repair if no_such_keyspace is thrown during preparations.
Fixes: #22073.
Requires backport to 6.1 and 6.2 as they contain the bug
=> repair: handle no_such_keyspace in repair preparation phase

service/storage_service.cc, service/storage_service.hh
Since now topology does not contain ip addresses there is no need to
create topology on an ip address change. Only peers table has to be
updated. The series factors out peers table update code from
sync_raft_topology_nodes() and calls it on topology and ip address
updates. As a side effect it fixes #22293 since now topology loading
does not require IP do be present, so the assert that is triggered in
this bug is removed.
Fixes: scylladb/scylladb#22293
=> Do not update topology on address change

scylla-gdb.py, sstables/disk_types.hh, sstables/sstables.cc, tools/scylla-sstable.cc
Continue replacing boost types with std one where possible.
Improvement, no backport needed
=> sstables: use std::variant instead of boost::variant

ent/encryption/encrypted_file_impl.cc, test/boost/encrypted_file_test.cc
Fixes #22236
If reading a file and not stopping on block bounds returned by `size()`, we could allow reading from (_file_size+&lt;1-15&gt;) (if crossing block boundary) and try to decrypt this buffer (last one).
Simplest example: 
Actual data size: 4095
Physical file size: 4095 + key block size (typically 16)
Read from 4096: -> 15 bytes (padding) -> transform return `_file_size` - `read offset` -> wraparound -> rather larger number than we expected (not to mention the data in question is junk/zero).
Check on last block in `transform` would wrap around size due to us being >= file size (l).
Just do an early bounds check and return zero if we're past the actual data limit.
=> encrypted_file_impl: Check for reads on or past actual file length in transform

api/api-doc/task_manager.json, api/task_manager.cc, docs/dev/task_manager.md, docs/operating-scylla/admin-tools/task-manager.rst, docs/operating-scylla/nodetool-commands/tasks/drain.rst, docs/operating-scylla/nodetool-commands/tasks/index.rst, docs/operating-scylla/nodetool-commands/tasks/status.rst, docs/operating-scylla/nodetool-commands/tasks/tree.rst, tasks/task_handler.cc, test/nodetool/test_tasks.py, test/rest_api/task_manager_utils.py, test/rest_api/test_task_manager.py, test/topology_tasks/task_manager_client.py, tools/scylla-nodetool.cc
Currently, when the status of a task is queried and the task is already finished, 
it gets unregistered. Getting the status shouldn't be a one-time operation. 
Stop removing the task after its status is queried. Adjust tests not to rely
on this behavior. Add task_manager/drain API and nodetool tasks drain 
command to remove finished tasks in the module.
Fixes: https://github.com/scylladb/scylladb/issues/21388.
It's a fix to task_manager API, should be backported to all branches
=> api: task_manager: do not unregister finish task when its status is queried

main.cc, repair/row_level.cc, repair/row_level.hh, service/storage_service.cc
Repair service is started after storage service, while storage service needs to reference repair one for its needs. Recently it was noticed, that this reverse order may cause troubles and was fixed with the help of an extra gate. That's not nice and makes the start-stop mess even worse. The correct fix is to fix the order both services start/stop in.
=> Fix repair vs storage services initialization order

repair/repair.cc, repair/row_level.hh, repair/task_manager_module.hh, service/storage_service.cc, service/task_manager_module.cc, test/topology_tasks/test_tablet_tasks.py
tablet_repair_task_impl is run as a part of tablet repair. Make it
a child of tablet repair virtual task.
tablet_repair_task_impl started by /storage_service/repair_async API 
(vnode repair) does not have a parent, as it is the top-level task 
in that case.
No backport needed; new functionality
=> service: add child for tablet repair virtual task

data_dictionary/data_dictionary.cc, locator/abstract_replication_strategy.cc, locator/abstract_replication_strategy.hh, locator/everywhere_replication_strategy.cc, locator/everywhere_replication_strategy.hh, locator/local_strategy.cc, locator/local_strategy.hh, locator/network_topology_strategy.cc, locator/network_topology_strategy.hh, locator/simple_strategy.cc, locator/simple_strategy.hh, locator/tablet_replication_strategy.hh, locator/tablets.cc, test/cql/locator_test.result, test/cqlpy/cassandra_tests/validation/operations/alter_test.py, test/cqlpy/cassandra_tests/validation/operations/create_test.py, test/cqlpy/test_keyspace.py
Clean the code validating if a replication strategy can be used.
This PR consists of a bunch of unmerged https://github.com/scylladb/scylladb/pull/20088 commits - the solution to the problem that the linked PR tried to solve has been accomplished in another PR, leaving the refactor commits unmerged. The commits introduced in this PR have already been reviewed in the old PR.
No need to backport, it's just a refactor.
=> cql: clean the code validating replication strategy options

test/pylib/rest_client.py, test/topology_custom/test_config.py, utils/config_file.cc, utils/config_file.hh, utils/config_file_impl.hh
Before this change, it was possible to change non-liveupdatable config
parameter without process restart. This erroneous behavior not only
contradicts the documentation but is potentially dangerous, as various
components theoretically might not be prepared for a change of
configuration parameter value without a restart. The issue came from
a fact that liveupdatability verification check was skipped for default
configuration parameters (those without its initial values
in configuration file during process start).
This change:
- Introduce _initialization_completed member in config_file
- Set _initialization_completed=true when config file is processed on
server start
- Verify config_file's initialization status during config update - if
config_file was initialized, prevent from further …
=> config: prevent SIGHUP from changing non-liveupdatable parameters

api/column_family.cc, api/column_family.hh, api/compaction_manager.cc, api/storage_service.cc, api/storage_service.hh
In column_family.cc and storage_service.cc there exist a bunch of helpers that parse and/or validate ks/cf names, and different endpoints use different combinations of those, duplicating the functionality of each other and generating some mess. This PR cleans the endpoints from column_family.cc that parse and validate fully qualified table name (the '$ks:$cf' string).
A visible "improvement" is that `validate_table()` helper usage in the api/ directory is narrowed down to storage_service.cc file only (with the intent to remove that helper completely), and the aforementioned `for_tables_on_all_shards()` helper becomes shorter and tiny bit faster, because it doesn't perform some re-lookups of tables, that had been performed by validation sanity checks before it.
There's more to be done in …
=> De-duplicate validation of tables in some column_family API endpoints

auth/allow_all_authenticator.hh, auth/authenticator.hh, auth/certificate_authenticator.hh, auth/password_authenticator.cc, auth/password_authenticator.hh, auth/saslauthd_authenticator.hh, auth/service.cc, auth/transitional.cc, test/auth_cluster/test_auth_password_ensured.py, test/pylib/manager_client.py
Before this change, it was ensured that a default superuser is created
before serving CQL. However, the mechanism didn't wait for default
password initialization, so effectively, for a short period, customer
couldn't authenticate as the superuser properily. The purpose of this
change is to improve the superuser initialization mechanism to wait for
superuser default password, just as for the superuser creation.
This change:
- Introduce authenticator::ensure_superuser_is_created() to allow
waiting for complete initialization of super user authentication
- Implement ensure_superuser_is_created in password_authenticator, so
waiting for superuser password initialization is possible
- Implement ensure_superuser_is_create in transitional_authenticator,
so the implementation from …
=> auth: ensure default superuser password is set before serving CQL

.github/workflows/check-license-header.yaml
This patch series contains improvements to our GitHub license header check workflow.
The first patch grants necessary write permissions to the workflow, allowing it to comment directly on pull requests when license header issues are found. This addresses a permissions-related error that previously prevented the workflow from creating comments.
The second patch optimizes the workflow by skipping the license check step when no relevant files have been modified in the pull request. This prevents unnecessary workflow failures that occurred when the check was run without any files to analyze.
Together, these changes make the license header checking process more robust and efficient. The workflow now properly communicates findings through PR comments and avoids running unnecessary checks.
--- …
=> .github: improve license header check workflow

reader_concurrency_semaphore.cc, reader_permit.hh, test/boost/querier_cache_test.cc
`set_notify_handler()` is called after a querier was inserted into the querier cache. It has two purposes: set a callback for eviction and set a TTL for the cache entry. This latter was not disabling the pre-existing timeout of the permit (if any) and this would lead to premature eviction of the cache entry if the timeout was shorter than TTL (which his typical).
Disable the timeout before setting the TTL to prevent premature eviction.
Fixes: https://github.com/scylladb/scylladb/issues/22629
Backport required to all active releases, they are all affected.
=>  reader_concurrency_semaphore: set_notify_handler(): disable timeout 

api/api.cc, api/api_init.hh, api/task_manager.cc, api/task_manager.hh, configure.py, idl/CMakeLists.txt, idl/tasks.idl.hh, main.cc, message/messaging_service.cc, message/messaging_service.hh, node_ops/task_manager_module.cc, node_ops/task_manager_module.hh, service/task_manager_module.cc, service/task_manager_module.hh, tasks/task_handler.cc, tasks/task_handler.hh, tasks/task_manager.cc, tasks/task_manager.hh, test/lib/cql_test_env.cc
Use host_id in a children list of a task in task manager to indicate 
a node on which the child was created.
Move TASKS_CHILDREN_REQUEST to IDL. Send it by host_id.
Fixes: https://github.com/scylladb/scylladb/issues/22284.
Ip to host_id transition; backport isn't needed.
=> tasks: use host_id in task manager

service/storage_service.cc, service/storage_service.hh, service/topology_coordinator.cc
The series fixes a regression and demotes a barrier_and_drain logging error to a warning since this particular condition may happen during normal operation.
We want to backport both since one is a bug fix and another is trivial and reduces CI flakiness.
=> Fix a regression that sometimes causes an internal error and demote barrier_and_drain rpc error log to a warning 

compaction/leveled_compaction_strategy.cc, compaction/size_tiered_compaction_strategy.cc, compaction/time_window_compaction_strategy.cc, locator/abstract_replication_strategy.cc, replica/table.cc, service/mapreduce_service.cc, sstables/sstable_set.cc
Replace boost::remove_if() with the standard library's std::erase_if() or std::ranges::remove_if() to reduce external dependencies and simplify the codebase. This change eliminates the requirement for boost::range and makes the implementation more maintainable.
---
=> tree: migrate from boost::remove_if() to the standard library based alternatives

compaction/compaction_manager.cc, repair/repair.cc, repair/task_manager_module.hh, sstables_loader.cc, sstables_loader.hh, tasks/task_manager.cc, tasks/task_manager.hh
This PR addresses two related issues in our task system:
1. Prepares for asynchronous resource cleanup by converting release_resources() to a coroutine. This refactoring enables future improvements in how we handle resource cleanup.
2. Fixes a cross-shard resource cleanup issue in the SSTable loader where destruction of per-shard progress elements could trigger "shared_ptr accessed on non-owner cpu" errors in multi-shard environments. The fix uses coroutines to ensure resources are released on their owner shards.
Fixes #22759
---
this change addresses a regression introduced by d815d7013cb7c74dfb265f3fe920a3c5b2226646, which is contained by 2025.1 and master branches. so it should be backported to 2025.1 branch.
=> sstable_loader: fix cross-shard resource cleanup in download_task_impl 

service/raft/group0_state_machine.cc, service/raft/group0_state_machine.hh, test/topology_custom/test_rpc_compression.py
We are supposed to be loading the most recent RPC compression dictionary on startup, but we forgot to port the relevant piece of logic during the source-available port. This causes a restarted node not to use the dictionary for RPC compression until the next dictionary update.
Fix that.
Fixes #22738
This is more of a bugfix than an improvement, so it should be backported to 2025.1.
* (cherry picked from commit [dd82b40](https://github.com/scylladb/scylladb/commit/dd82b401867f22b6a1841a355c7fc0c431730a87))
* (cherry picked from commit [8fb2ea6](https://github.com/scylladb/scylladb/commit/8fb2ea61badc638381131e56f4faaf1aaab32073))
Additionally cherry picked https://github.com/scylladb/scylladb/pull/22836 to fix the timeout.
Parent PR: #22739
=> [Backport 2025.1] raft/group0_state_machine: load current RPC compression dict on startup

api/api-doc/storage_service.json, api/storage_service.cc, docs/dev/system_keyspace.md, locator/tablets.cc, locator/tablets.hh, repair/repair.cc, replica/tablets.cc, service/storage_service.cc, service/storage_service.hh, service/topology_coordinator.cc, test/boost/tablets_test.cc, test/pylib/repair.py, test/pylib/rest_client.py, test/topology_custom/test_tablet_repair_scheduler.py
Currently, the tablet repair scheduler repairs all replicas of a tablet. It does not support hosts or DCs selection. It should be enough for most cases. However, users might still want to limit the repair to certain hosts or DCs in production. https://github.com/scylladb/scylladb/pull/21985 added the preparation work to add the config options for the selection. This patch adds the hosts or DCs selection support.
Fixes https://github.com/scylladb/scylladb/issues/22417
New feature. No backport is needed.
=> repair: Introduce Host and DC filter support

main.cc, repair/row_level.cc, repair/row_level.hh, streaming/consumer.cc, streaming/consumer.hh, streaming/stream_manager.cc, streaming/stream_manager.hh, streaming/stream_session.cc, test/lib/cql_test_env.cc
Both, repair and streaming depend on view builder, but since the builder is started too late, both keep sharded<> reference on it and apply `if (view_builder.local_is_initialized())` safety checks.
However, view builder can do its sharded start much earlier, there's currently nothing that prevents it from doing so. This PR moves view builder start up together with some other of its dependencies, and relaxes the way repair and streaming use their view-builder references, in particular -- removes those ugly initialization checks.
refs: #2737
=> Fix view-builder vs (repair and streaming) initialization order

sstables/sstables.cc, sstables/sstables_manager.cc, sstables/sstables_manager.hh, test/boost/bloom_filter_test.cc, test/lib/sstable_test_env.hh
The config variable `components_memory_reclaim_threshold` limits the
memory available to the sstable bloom filters. Any change to its value
is not immediately propagated to the sstable manager, despite it being
a LiveUpdate variable. The updated value takes effect only when a new
sstable is created or deleted.
This PR first refactors the reclaim and reload logic into a single              
background fiber. It then updates the sstable manager to subscribe to           
changes in the `components_memory_reclaim_threshold` configuration value        
and immediately triggers the reclaim/reload fiber when a change is              
detected.
Fixes #21947
This is an improvement and does not need to be backported.
=> sstables_manager: trigger reclaim/reload on `components_memory_reclaim_threshold` update

ent/encryption/encryption.cc, ent/encryption/encryption_exceptions.hh, ent/encryption/gcp_host.cc, ent/encryption/kms_host.cc, test/boost/encryption_at_rest_test.cc
Refs #22628
Adds exception handler + cleanup for the case where we have a bad config/env vars (hint minio) or similar, such that we fail with exception during setting up the EAR context. In a normal startup, this is ok. We will report the exception, and the do a exit(1).
In tests however, we don't and active context will instead be freed quite proper, in which case we need to call stop to ensure we don't crash on shared pointer destruction on wrong shard. Doing so will hide the real issue from whomever runs the test.
Adds some verbosity to track issues with the network proxy used to test EAR connector difficulties. Also adds an earlier close in input stream to help network usage.
Note: This is a diagnostic helper. Still cannot repro the issue above.
=> encryption_at_rest_test/encryption: Add some verbosity etc to help diagnose test run issues

raft/fsm.cc, raft/raft.cc, raft/raft.hh, service/raft/raft_rpc.cc, service/raft/raft_rpc.hh
Serializing `raft::append_request` for transmission requires approximately the same amount of memory as its size. This means when the Raft library replicates a log item to M servers, the log item is effectively copied M times. To prevent excessive memory usage and potential out-of-memory issues, we limit the total memory consumption of in-flight `raft::append_request` messages.
Fixes scylladb/scylladb#14411
=> raft_rpc::send_append_entries: limit memory usage

service/storage_proxy.cc, test/topology_custom/test_truncate_with_tablets.py
Currently, we can not have more than one global topology operation at the same time. This means that we can not have concurrent truncate operations because truncate is implemented as a global topology operation.
Truncate excludes with other topology operations, and has to wait for those to complete before truncate starts executing. This can lead to truncate timeouts. In these cases the client retries the truncate operation, which will check for ongoing global topology operations, and will fail with
an "Another global topology request is ongoing, please retry." error.
This can be avoided by truncate checking if the ongoing global topology operation is a truncate running for the same table who's truncate has just been requested again. In this case, we can wait for the ongoing truncate to …
=> truncate: don't fail on already waiting truncate for the same table

db/system_keyspace.cc, db/system_keyspace.hh, service/migration_manager.hh, service/qos/service_level_controller.cc, service/raft/group0_state_machine.cc, service/raft/group0_state_machine.hh, service/raft/raft_group0.cc, service/raft/raft_group0.hh, service/raft/raft_group0_client.cc, service/raft/raft_group0_client.hh, service/storage_service.cc, service/storage_service.hh
In the current scenario, the problem discovered is that there is a time gap between group0 creation and raft_initialize_discovery_leader call. Because of that, the group0 snapshot/apply entry enters wrong values from the disk(null) and updates the in-memory variables to wrong values. During the above time gap, the in-memory variables have wrong values and perform absurd actions.
This PR removes the variable `_manage_topology_change_kind_from_group0`
which was used earlier as a work around for correctly handling `topology_change_kind` variable, it was brittle and had some bugs(causing issues like scylladb/scylladb#21114). The reason for this bug that _manage_topology_change_kind used to block reading from disk and was enabled after group0 initialization and starting raft server for the …
=> raft topology: Add support for raft topology init to happen before group0 initialization

sstables/sstable_directory.cc, sstables/sstable_directory.hh, sstables/sstables.hh, sstables/storage.cc, sstables/storage.hh
There's a sstable_directory::create_pending_deletion_log() helper method that's called by sstable's filesystem_storage atomic-delete methods and that prepares the deletion log for a bunch of sstables. For that method to do its job it needs to get private sstable->_storage field (which is always the filesystem_storage one), also the atomic-delete transparent context object is leaked into the sstable_directory code and low-level sstable storage code needs to include higher-level sstable_directory header.
This patch unties these knots. As the result:
- friendship between sstable and sstable_directory is removed
- transparent atomic_delete_context is encapsulated in storage.(cc|hh) code
- less code for create_pending_deletion_log() to dump TOC filename into log
=> Untangle sstable-directory vs sstable in pending log creation code

db/config.cc, db/config.hh, locator/network_topology_strategy.cc, locator/network_topology_strategy.hh, locator/tablet_replication_strategy.hh, locator/tablets.cc, locator/tablets.hh, main.cc, service/tablet_allocator.cc, service/tablet_allocator.hh, test.py, test/boost/network_topology_strategy_test.cc, test/boost/tablets_test.cc, test/cqlpy/suite.yaml, test/lib/cql_test_env.cc, test/lib/cql_test_env.hh, test/perf/tablet_load_balancing.cc, test/rest_api/suite.yaml, test/topology_custom/test_major_compaction.py, test/topology_custom/test_tablets.py
This series achieves two things:
1) changes default number of tablet replicas per shard to be 10 in order to reduce load imbalance between shards
This will result in new tables having at least 10 tablet replicas per
shard by default.
We want this to reduce tablet load imbalance due to differences in
tablet count per shard, where some shards have 1 tablet and some
shards have 2 tablets. With higher tablet count per shard, this
difference-by-one is less relevant.
Fixes https://github.com/scylladb/scylladb/issues/21967
2) introduces a global goal for tablet replica count per shard and adds logic to tablet scheduler to respect it by controlling per-table tablet count 
The per-shard goal is enforced by controlling average per-shard tablet replica
count in a given DC, which is controlled by …
=> Respect per-shard tablet goal and 10x default per-shard tablet count

locator/tablets.cc, locator/tablets.hh, repair/repair.cc, service/topology_coordinator.cc, test/topology_custom/test_tablet_repair_scheduler.py
If hosts and/or dcs filters are specified for tablet repair and
some replicas match these filters, choose the replica that will 
be the repair master according to round-robin principle
(currently it's always the first replica).
If hosts and/or dcs filters are specified for tablet repair and
no replica matches these filters, the repair succeeds and 
the repair request is removed (currently an exception is thrown
and tablet repair scheduler reschedules the repair forever).
Fixes: https://github.com/scylladb/scylladb/issues/23100.
Needs backport to 2025.1 that introduces hosts and dcs filters for tablet repair
=> tablets: repair: fix hosts and dcs filters behavior for tablet repair

replica/database.cc, replica/database.hh
Currently for system keyspace part of config members are configured outside of this helper, in the caller. It's more consistent to have full config initialization in one place.
=> replica: Prepare full keyspace config in make_keyspace_config()

api/column_family.cc, api/storage_service.cc, api/storage_service.hh
This is continuation of #21533 
There are two almost identical helpers in api/ -- validate_table(ks, cf) and get_uuid(ks, cf). Both check if the ks:cf table exists, throwing bad_param_exception if it doesn't. There's slight difference in their usage, namely -- callers of the latter one get the table_id found and make use of it, while the former helper is void and its callers need to re-search for the uuid again if the need (spoiler: they do).
This PR merges two helpers together, so there's less code to maintain. As a nice side effect, the existing validate_table() callers save one re-lookup of the ks:cf pair in database mappings.
Affected endpoints are validated by existing tests:
* column_family/{autocompation|tombstone_gc|compaction_strategy}, validated by the tests described in #21533 …
=> De-duplicate API's table name to table ID conversion

alternator/stats.cc, alternator/ttl.cc, cdc/log.cc, compaction/compaction_manager.cc, configure.py, cql3/query_processor.cc, db/commitlog/commitlog.cc, db/row_cache.cc, db/view/view.cc, gms/gossiper.cc, main.cc, repair/repair.cc, replica/database.cc, service/storage_proxy.cc, service/storage_service.cc, sstables/sstables.cc, streaming/stream_manager.cc, transport/server.cc, utils/CMakeLists.txt, utils/labels.cc, utils/labels.hh, utils/logalloc.cc
This series is part of the effort to reduce the overall overhead originating from metrics reporting, both on the Scylla side and the metrics collecting server (Prometheus or similar)
The idea in this series is to create an equivalent of levels with a label. 
First, label a subset of the metrics used by the dashboards.
Second, the per-table metrics that are now off by default will be marked with a different label.
The following specific optional features: CDC, CAS, and Alternator have a dedicated label now.
This will allow users to disable all metrics of features that are not in use.
All the rest of the metrics are left unlabeled. 
Without any changes, users would get the same metrics they are getting today.
But you could pass the `__level=1` and get only those metrics the dashboard needs. …
=> Label basic metrics

reader_concurrency_semaphore.cc, test/boost/reader_concurrency_semaphore_test.cc
It is possible that the permit handed in to register_inactive_read() is already aborted (currently only possible if permit timed out). If the permit also happens to have wait for memory, the current code will attempt to call promise<>::set_exception() on the permit's promise to abort its waiters. But if the permit was already aborted via timeout, this promise will already have an exception and this will trigger an assert. Add a separate case for checking if the permit is aborted already. If so, treat it as immediate eviction: close the reader and clean up.
Fixes: scylladb/scylladb#22919
Bug is present in all live versions, backports are required.
=> reader_concurrency_semaphore: register_inactive_read(): handle aborted permit

service/raft/raft_group0.cc, service/raft/raft_group0.hh, service/storage_service.cc, service/topology_coordinator.cc, test/topology_custom/test_tablets_migration.py
For the limited voters feature to work properly we need to make sure that we are only managing the voter status through the topology coordinator. This means that we should not change the node votership from the storage_service module for the raft topology directly.
We can drop the voter status changes from the storage_service module because the topology coordinator will handle the votership changes eventually. The calls in the storage_service module were not essential and were only used for optimization (improving the HA under certain conditions).
Furthermore, the other bundled commit improves the reaction again by reacting to the node `on_up()` and `on_down()` events, which again shortens the reaction time and improves the HA.
The change has effect on the timing in the tablets migration …
=> raft topology: drop changing the raft voters config via storage_service

main.cc
To simplify aborting scylla while starting the services,
add a _ready state to stop_signal, so that until
main is ready to be stopped by the abort_source,
just register that the signal is caught, and
let a check() method poll that and request abort
and throw respective exception only then, in controlled
points that are in-between starting of services
after the service started successfully and a deferred
stop action was installed.
This patch prevents gate_closed_exception to escape handling
when start-up is aborted early with the stop signal,
causing https://github.com/scylladb/scylladb/issues/23153
The regression is apparently due to a25c3eaa1caa9826abba750dc004566bdda89eb6
Fixes https://github.com/scylladb/scylladb/issues/23153
* Requires backport to 2025.1 due to …
=> main: safely check stop_signal in-between starting services

compaction/compaction_manager.cc, compaction/compaction_manager.hh, configure.py, db/large_data_handler.cc, db/large_data_handler.hh, db/system_keyspace.cc, db/system_keyspace.hh, main.cc, replica/database.cc, replica/database.hh, test/boost/CMakeLists.txt, test/boost/pluggable_test.cc, test/lib/cql_test_env.cc, utils/pluggable.hh
This series adds an async guard to system_keyspace operations
and adds a deferred action to stop the system_keyspace in main() before destroying the service.
This helps to make sure that sys_ks is unplugged from its users and that all async operations using it are drained once it's stopped.
* Enhancement, no backport needed
=> Main: stop system_keyspace

cql3/statements/select_statement.cc, cql3/untyped_result_set.hh, test/boost/secondary_index_test.cc
Secondary index queries fetch partition keys from the index view and store them in an `std::vector`. The vector size is currently limited by the user's page size and the page memory limit (1MiB). These are not enough to prevent large contiguous allocations (which can lead to stalls).
This series introduces a hard limit to the vector size to ensure it does not exceed the allocator's preferred max contiguous allocation size (128KiB). With the size of each element being 120 bytes, this allows for 1092 partition keys. The limit was set to 1000. Any partitions above this limit are discarded.
Discarding partitions breaks the querier cache on the replicas, causing a performance regression, as can be seen from the following measurements:
```
* Cluster: 3 nodes (local Docker containers), 1 vCPU, …
```
=> Apply hard limit to partition range vectors in secondary index queries

api/storage_service.cc, db/legacy_schema_migrator.cc, db/schema_tables.cc, db/schema_tables.hh, replica/database.cc, replica/database.hh, service/client_state.cc
Actually, the main goal of this PR was to remove parse_tables() helpers from api/ in favor of more flexible (yet same complex) parse_table_infos(), but it turned out that it also saves some lookups in database maps.
There are several places in API and schema_tables that have table_id at hand, but at some point drop it and carry keyspace and table names over to a place that maps ks:cf back to table_id and then uses it to find the table object. This PR keeps the table_id with the help of table_info struct in those places. This change allows removing the aforementioned parse_table() helpers from api/ and also saves few lookups in database maps.
Removing the parse_tables() from api/ is the continuation of previous effort that reduces the set of helpers in api/ code that help handlers "parse" …
=> Remove some excessive ks:cf -> table_id conversions in API and schema_tables

test/perf/perf_sstable.cc
`seastar::at_exit()` was marked deprecated recently. so let's use the recommended approach to perform cleanups.
---
=> perf/perf_sstable: stop using at_exit() 

docs/dev/topology-over-raft.md, locator/network_topology_strategy.cc, service/storage_service.cc, service/tablet_allocator.cc, service/tablet_allocator.hh, service/topology_coordinator.cc, service/topology_state_machine.cc, service/topology_state_machine.hh, test/boost/tablets_test.cc, test/lib/cql_test_env.cc, test/lib/cql_test_env.hh, test/lib/topology_builder.hh, test/topology_custom/test_tablets_merge.py
service: Introduce rack-aware co-location migrations for tablet merge
Merge co-location can emit migrations across racks even when RF=#racks,
reducing availability and affecting consistency of base-view pairing.
Given replica set of sibling tablets T0 and T1 below:
[T0: (rack1,rack3,rack2)]
[T1: (rack2,rack1,rack3)]
Merge will co-locate T1:rack2 into T0:rack1, T1 will be temporarily only at
only a subset of racks, reducing availability.
This is the main problem fixed by this patch.
It also lays the ground for consistent base-view replica pairing,
which is rack-based. For tables on which views can be created we plan
to enforce the constraint that replicas don't move across racks and
that all tablets use the same set of racks (RF=#racks). This patch
avoids moving replicas across racks …
=> [Backport 2025.1] Rack aware tablet merge colocation migration 

db/commitlog/commitlog.cc, main.cc, test/boost/commitlog_test.cc
Fixes #23017
When deleting segments while our footprint is over the limit, mainly when recycling/deleting segments after replay (recover boot) we can cause two deletion passes to be running at the same time. This is because delete is triggered by either
a.) replay release
b.) timer check (explicit)
c.) timer initiated flush callback
where the last one is in fact not even waited for. If we are considering many files for delete/recycle, we can, due to task switch, end up considering segments ok to keep, in parallel, even though one of them should be deleted. The end result will be us keeping one more segment than should be allowed.
Now, eventually, this should be released, once we do deletion again, but this can take a while.
Solution is to simply ensure we serialize deletion. This might …
=> commitlog: Serialize file deletion and distribute replayed segments

conf/scylla.yaml, cql3/statements/alter_keyspace_statement.cc, cql3/statements/create_keyspace_statement.cc, db/config.cc, db/config.hh, docs/architecture/tablets.rst, docs/architecture/zero-token-nodes.rst, docs/cql/ddl.rst, docs/reference/glossary.rst, locator/tablets.cc, locator/tablets.hh, main.cc, replica/database.cc, replica/database.hh, test/cluster/test_multidc.py, test/lib/cql_test_env.cc
This PR is an introductory step towards enforcing
RF-rack-valid keyspaces in Scylla.
The scope of changes:
* defining RF-rack-valid keyspaces,
* introducing a configuration option enforcing RF-rack-valid
keyspaces,
* restricting the CREATE and ALTER KEYSPACE statements
so that they never lead to RF-rack invalid keyspaces,
* during the initialization of a node, it verifies that all existing
keyspaces are RF-rack-valid. If not, the initialization fails.
We provide tests verifying that the changes behave as intended.
---
Note that there are a number of things that still need to be implemented.
That includes, for instance, restricting topology operations too.
---
Implementation strategy (going beyond the scope of this PR):
1. Introduce the new configuration option `rf_rack_valid_keyspaces`. …
=> cql3: Introduce RF-rack-valid keyspaces

test/boost/s3_test.cc, test/perf/perf_s3_client.cc, utils/s3/client.cc, utils/s3/client.hh
Currently, to stream data from sstable component the sstables code uses file_data_source_impl. In case the component is on S3, the s3::readable_file is put into that data source. The data source is configured with 128k buffers and at most 4 read-ahead-s. With that configuration, downloading full object from S3 becomes too slow -- GET-ing file with 128k requests is not nice even with 4 parallel read-ahead-s.
Better solution for S3 downloading is to request way larger chunk with one GET and then produce smaller, 128k or alike, buffers upon data arrival. This is what the newly introduced data source impl does -- it spawns a background GET and lets the upper input stream read buffers directly from the arriving body.
This PR doesn't yet make sstable layer use the new sink, just introduces it …
=> Introduce s3 data_source_impl for optimized object streaming

test/cluster/object_store/test_backup.py
This PR includes several fixes to the nowadays flaky test_restore_with_streaming_scopes test.
1. Check that backup and restore APIs don't fail. Currently, if either of them does the test cases fails anyway checking that the data is not restored back, but it's better to know what exactly failed
2. For restore API the test collects the list of sstables to restore from. Currently collecting this list races with background compaction and sometimes leads to restore API to fail which, in turn, makes the whole test to fail
3. Add a test case that validates that restore-from-missing-sstable fails nicely
refs: #23189
No backport, as it's a relatively new test
=> Improve scoped restore test

test.py, test/__init__.py, test/boost/conftest.py, test/cluster/conftest.py, test/cluster/random_failures/conftest.py, test/cluster/random_failures/test_random_failures.py, test/conftest.py, test/nodetool/conftest.py, test/pylib/async_cql.py, test/pylib/cpp/common_cpp_conftest.py, test/pylib/manager_client.py, test/pylib/resource_gather.py, test/pylib/scylla_cluster.py, test/pylib/suite/base.py, test/pylib/suite/boost.py, test/pylib/suite/cql_approval.py, test/pylib/suite/python.py, test/pylib/suite/run.py, test/pylib/suite/tool.py, test/pylib/suite/topology.py, test/pylib/suite/unit.py, test/pylib/util.py, test/pytest.ini
Add possibility to run topology tests using bare pytest command.
To achieve this goal the following changes were made:
- Add fixtures `testpy_testsuite` and `testpy_test` to `test/conftest.py`.
- To build `TestSuite` object we need to discover a corresponding `suite.xml` file.  Do this by walking up thru the fs tree starting from the current test file.
- Run ScyllaClusterManager using pytest fixture if `--manager-api` option is not provided.
And made some refactoring:
- Add path constants to `test` module and use them in different test suites instead of own dups of the same code:
- TOP_SRC_DIR : ScyllaDB's source code root directory
- TEST_DIR : the directory with test.py tests and libs
- BUILD_DIR : directory with ScyllaDB's build artifacts
- Add TestSuite.log_dir attribute as a …
=> test.py: topology: allow to run tests with bare pytest command

api/storage_service.cc, db/snapshot-ctl.cc, db/snapshot-ctl.hh
The scrub API handler may want to snapshot several tables. For that, it calls snapshot-ctl method to snapshot a single table for each table in the list. That's excessive, snapshot-ctl has a method to snapshot a bunch of tables at once, just what the scrub handler needs.
It's an improvement, so no need to backport
=> Snapshot several tables at once in scrub API handler

service/tablet_allocator.cc, service/topology_coordinator.cc, test/cluster/test_tablets.py
Resize finalization is executed in a separate topology transition state,
`tablet_resize_finalization`, to ensure it does not overlap with tablet
transitions. The topology transitions into the
`tablet_resize_finalization` state only when no tablet migrations are
scheduled or being executed. If there is a large load-balancing backlog,
split finalization might be delayed indefinitely, leaving the tables
with large tablets.
This PR fixes the issue by updating the load balancer to no schedule any
migrations and to not make any repair plans when there a resize
finalization is pending in any table.
Also added a testcase to verify the fix.
Fixes #21762
Improvement : No need to backport.
=> Finalize tablet splits earlier

test/boost/database_test.cc
This helper facilitate snapshot creation by various test cases in database_test.cc. This PR generalizes all overloads into one that suits all callers and patches one more test case to use it as well.
=> test/database: Remove most of take_snapshot() helper overloads and re-use them more

tracing/trace_state.hh, transport/server.cc
A default timestamp (not to confuse with the timestamp passed via 'USING TIMESTAMP' query clause) can be set using 0x20 flag and the <timestamp> field in the binary CQL frame payload of QUERY, EXECUTE and BATCH ops. It also happens to be a default of a Java CQL Driver.
However, we were only setting the corresponding info in the CQL Tracing context of a QUERY operation. For an unknown reason we were not setting this for an EXECUTE and for a BATCH traces (I guess I simply forgot to set it back then).
This patch fixes this.
Fixes #23173
The issue fixed by this PR is not critical but the fix is simple and safe enough so we should backport it to all live releases.
=> transport/server.cc: set default timestamp info in EXECUTE and BATCH tracing

test/cluster/auth_cluster/test_auth_no_quorum.py, test/cluster/auth_cluster/test_auth_raft_command_split.py, test/cluster/auth_cluster/test_auth_v2_migration.py, test/cluster/auth_cluster/test_raft_service_levels.py, test/cluster/conftest.py, test/cluster/test_aggregation.py, test/cluster/test_automatic_cleanup.py, test/cluster/test_cluster_features.py, test/cluster/test_concurrent_schema.py, test/cluster/test_gossiper.py, test/cluster/test_mutation_schema_change.py, test/cluster/test_mv.py, test/cluster/test_raft_cluster_features.py, test/cluster/test_random_tables.py, test/cluster/test_replace_alive_node.py, test/cluster/test_topology_rejoin.py, test/cluster/test_topology_schema.py, test/pylib/internal_types.py, test/pylib/manager_client.py, test/pylib/scylla_cluster.py, test/pytest.ini
So that a multi-dc/multi-rack cluster can be populated
in a single call.
* Enhancement, no backport required
=> test/pylib: servers_add: support list of property_files

db/config.cc, db/config.hh, gms/feature_service.hh, idl/storage_service.idl.hh, locator/load_sketch.hh, locator/tablets.cc, locator/tablets.hh, main.cc, message/messaging_service.cc, message/messaging_service.hh, service/storage_service.cc, service/storage_service.hh, service/tablet_allocator.cc, service/topology_coordinator.cc, test/boost/database_test.cc, test/boost/tablets_test.cc, test/lib/cql_test_env.cc, test/lib/cql_test_env.hh, test/lib/topology_builder.hh, test/perf/tablet_load_balancing.cc, test/topology_custom/test_tablets_removenode.py, utils/disk_space_monitor.cc, utils/disk_space_monitor.hh, utils/only_on_shard0.hh
Before this patch, the load balancer was equalizing tablet count per
shard, so it achieved balance assuming that:
1) tablets have the same size
2) shards have the same capacity
That can cause imbalance of utilization if shards have different
capacity, which can happen in heterogeneous clusters with different
instance types. One of the causes for capacity difference is that
larger instances run with fewer shards due to vCPUs being dedicated to
IRQ handling. This makes those shards have more disk capacity, and
more CPU power.
After this patch, the load balancer equalizes shard's storage
utilization, so it no longer assumes that shards have the same
capacity. It still assumes that each tablet has equal size. So it's a
middle step towards full size-aware balancing.
One consequence is that to …
=> [Backport 2025.1] tablets: Make load balancing capacity-aware

repair/row_level.cc, test/cluster/test_tablets.py, test/pylib/repair.py
Currently, repair_writer_impl::create_writer keeps erm to ensure that a sharder is valid. If we repair a tablet, erm blocks the state machine and no operation on any tablet of this table might be performed.
Use auto_refreshing_sharder and topology_guard to ensure that the operation is safe and that tablet operations on the whole table aren't blocked.
Fixes: #23453.
Needs backport to 2025.1 that introduces the tablet repair scheduler.
=> repair: release erm in repair_writer_impl::create_writer when possible

configure.py, db/config.cc, db/config.hh, generic_server.cc, generic_server.hh, redis/controller.cc, redis/controller.hh, redis/server.cc, redis/server.hh, test/boost/generic_server_test.cc, test/perf/CMakeLists.txt, test/perf/perf.cc, test/perf/perf.hh, test/perf/perf_generic_server.cc, transport/server.cc, transport/server.hh
Adds new live updatable config: uninitialized_connections_semaphore_cpu_concurrency.
It should help to reduce cpu usage by limiting cpu concurrency for new connections.  As a last resort when those connections are waiting for initial processing too long (over 1m) they are shed.
New connections_shed and connections_blocked metrics are added for tracking.
Testing:
- manually via simple program creating high number of connection and constantly re-connecting
- added benchmark
Following are benchmark results:
Before:
```
> build/release/test/perf/perf_generic_server --smp=1
170101.41 tps ( 13.1 allocs/op,   0.0 logallocs/op,   7.0 tasks/op,    4695 insns/op,    3178 cycles/op,        0 errors)
[...]
throughput: mean=173850.06 standard-deviation=1844.48 median=174509.66 …
```
=> generic_server: throttle and shed incoming connections according to semaphore limit

db/snapshot-ctl.cc, db/snapshot-ctl.hh, db/snapshot/backup_task.cc, db/snapshot/backup_task.hh, replica/database.cc, replica/database.hh, sstables/component_type.hh, sstables/sstable_directory.hh, sstables/sstables_manager.cc, sstables/sstables_manager.hh, sstables/sstables_manager_subscription.hh, utils/s3/client_fwd.hh
The motivation behind this change to free up disk space as early as possible.
The reason is that snapshot locks the space of all SSTables in the snapshot,
and deleting form the table, for example, by compaction, or tablet migration,
won't free-up their capacity until they are uploaded to object storage and deleted from the snapshot.
This series adds prioritization of deleted sstables in two cases:
First, after the snapshot dir is processed, the list of SSTable generation is cross-referenced with the
list of SSTables presently in the table and any generation that is not in the table is prioritized to
be uploaded earlier.
In addition, a subscription mechanism was added to sstables_manager
and it is used in backup to prioritize SSTables that get deleted from the table directory
during …
=> [Out-of-space prevention] db: backup: prioritize sstables that were deleted from the table

docs/dev/topology-over-raft.md, gms/feature_service.hh, locator/tablets.cc, locator/tablets.hh, repair/repair.cc, repair/row_level.hh, repair/task_manager_module.hh, scripts/tablet-mon.py, service/storage_service.cc, service/tablet_allocator.cc, service/topology_coordinator.cc, test/cluster/test_tablets.py
Currently, when we rebuild a tablet, we stream data from all 
replicas. This creates a lot of redundancy, wastes bandwidth 
and CPU resources.
In this series, we split the streaming stage of tablet rebuild into 
two phases: first we stream tablet's data from only one replica 
and then repair the tablet.
Fixes: https://github.com/scylladb/scylladb/issues/17174.
Needs backport to 2025.1 to prevent out of space during streaming
=> tablets: rebuild: use repair for tablet rebuild

alternator/executor.cc, alternator/stats.cc, alternator/stats.hh, test/alternator/test_metrics.py
This series adds a histogram for get and write batch sizes.
It uses the estimated_histogram implementation which starts from 1 with 1.2 exponential factor, which works
extremely tight to 20 but still covers all the way to 100.
Histograms will be reported per node.
**Backport to 2025.1 so we'll have information about user batch size limitation**
=> Alternator batch count histograms

scylla-gdb.py
Make output more readable by:
* group follower/master repair instances separately
* split repair details into one line for repair summary, then one line for each host info
* add indentation to make the output easier to follow
Also add `-m|--memory` option to calculate memory usage of repair buffers.
Example output:
(gdb) scylla repairs -m
Repairs for which this node is leader:
(repair_meta*) 0x60503ab7f7b0: {id: 19197, table: large_collection_test.table_with_large_collection, reason: decommission, row_buf: {len: 0, memory: 0}, working_row_buf: {len: 30, memory: 48208512}, same_shard: True, tablet: False}
host: 496e8b0c-50bf-4ada-b8f9-3d167138e908, shard: 5, state: repair_state::get_combined_row_hash_finished
host: ce4413ab-33d9-40f8-b13e-d14af8511dda, shard: 4294967295, state: …
=> scylla-gdb.py: improve scylla repairs command

db/virtual_table.cc, db/virtual_table.hh, db/virtual_tables.cc, db/virtual_tables.hh, docs/dev/system_keyspace.md, docs/dev/virtual-tables.md, main.cc, scripts/tablet-mon.py, service/tablet_allocator.cc, service/tablet_allocator.hh, service/topology_coordinator.cc, test/boost/virtual_table_mutation_source_test.cc, test/cluster/test_tablet_stats.py, test/lib/cql_test_env.cc
After load-balancer was made capacity-aware it no longer equalizes tablet count per shard, but rather utilization of shard's storage. This makes the old presentation mode not useful in assessing whether balance was reached, since nodes with less capacity will get fewer tablets when in balanced state. This PR adds a new default presentation mode which scales tablet size by its storage utilization so that tablets which have equal shard utilization take equal space on the graph.
To facilitate that, a new virtual table was added: system.load_per_node, which allows the tool to learn about load balancer's view on per-node capacity. It can also serve as a debugging interface to get a view of current balance according to the load-balancer.
=> Adjust tablet-mon.py for capacity-aware load balancing

test/cluster/test_tablets.py, test/cqlpy/cassandra_tests/validation/operations/alter_test.py, test/cqlpy/cassandra_tests/validation/operations/create_test.py, test/cqlpy/suite.yaml, test/cqlpy/test_guardrail_replication_strategy.py, test/cqlpy/test_keyspace.py, test/cqlpy/test_logs.py, test/cqlpy/test_tablets.py
In this PR, we adjust tests in the cqlpy test suite so they
only use RF-rack-valid keyspaces. After that, we enable
the configuration option `rf_rack_valid_keyspaces` in the
suite by default.
Refs scylladb/scylladb#23428
Backport: backporting to 2025.1 so we can test the option there too.
=> test/cqlpy: Adjust tests to RF-rack-valid keyspaces

gms/feature_service.hh, message/messaging_service.cc, replica/database.hh, service/storage_service.cc, service/storage_service.hh
Scylla operations use concurrency semaphores to limit the number of concurrent operations and prevent resource exhaustion. The semaphore is selected based on the current scheduling group.
For RAFT group operations, it is essential to use a system semaphore to avoid queuing behind user operations. This patch ensures that RAFT operations use the `gossip` scheduling group to leverage the system semaphore.
Fixes scylladb/scylladb#21637
Backport: 6.2 and 6.1
=> Ensure raft group0 RPCs use the gossip scheduling group.

service/storage_service.cc, service/topology_coordinator.cc, test/cluster/test_tablets.py
Commit https://github.com/scylladb/scylladb/commit/876478b84fd0f3a2e67e9385c562c9988973268a ("storage_service: allow concurrent tablet migration in tablets/move API", 2024-02-08) introduced a code path on which the topology state machine would be busy -- in "tablet_draining" or "tablet_migration" state -- at the time of starting tablet migration. The pre-commit code would unconditionally transition the topology to "tablet_migration" state, assuming the topology had been idle previously. On the new code path, this state change would be idempotent if the topology state machine had been busy in "tablet_migration", but the state change would incorrectly overwrite the "tablet_draining" state otherwise.
Restrict the state change to when the topology state machine is idle.
In addition, add the …
=> storage_service: preserve state of busy topology when transiting tablet

alternator/consumed_capacity.cc, alternator/consumed_capacity.hh, alternator/executor.cc, alternator/executor.hh, test/alternator/test_returnconsumedcapacity.py
This series adds support for reporting consumed capacity in BatchGetItem operations in Alternator.
It includes changes to the RCU accounting logic, exposing internal functionality to support batch-specific behavior, and adds corresponding tests for both simple and complex use cases involving multiple tables and consistency modes.
Need backporting to 2025.1, as RCU and WCU are not fully supported
Fixes #23690
=> Alternator batch rcu

service/topology_coordinator.cc
Add missing awaits for the rebuild_repair and repair background actions.
Although the background actions hold the _async_gate
which is closed in topology_coordinator::run(),
stop() still needs to await all background action futures
and handle any errors they may have left behind.
Fixes #23755
* The issue exists since 6.2
=> topology_coordinator: stop: await all background_action_holder:s

test/cluster/test_read_repair.py
There are two tests which test incremental read repair: one with row the other with partition tombstones. The tests currently force vnodes, by creating the test keyspace with {'enabled': false}. Even so, the tests were found to be flaky so one of them are marked for skip. This commit does the following changes:
* Make the tests use tablets by creating the test keyspace with tablets.
* Change the way the tests write data so it works with tablets: currently the tests use scylla-sstable write + upload but this won't work with tablets since upload with tablets implies --load-and-stream which means data is streamed to all replicas (no difference created between nodes). Switch to the classic stop-node + write to other replica with CL=ONE.
* Remove the skip added to the partition-tombstone test …
=> test/cluster/test_read_repair: make incremental test work with tablets

test/boost/managed_bytes_test.cc, utils/managed_bytes.hh
Commit 14bf09f447a67e35ddc5ae7573b05325e4ecb32d added a single-chunk layout to `managed_bytes`, which makes the overhead of `managed_bytes` smaller in the common case of a small buffer.
But there was a bug in it. In the copy constructor of `managed_bytes`, a copy of a single-chunk `managed_bytes` is made single-chunk too.
But this is wrong, because the source of the copy and the target of the copy might have different preferred max contiguous allocation sizes.
In particular, if a `managed_bytes` of size between 13 kiB and 128 kiB is copied from the standard allocator into LSA, the resulting `managed_bytes` is a single chunk which violates LSA's preferred allocation size. (And therefore is placed by LSA in the standard allocator).
In other words, since Scylla 6.0, cache and memtable cells …
=> managed_bytes: in the copy constructor, respect the target preferred allocation size

db/snapshot-ctl.cc, db/snapshot/backup_task.cc, db/snapshot/backup_task.hh, test/cluster/object_store/test_backup.py, utils/s3/client_fwd.hh
This PR enhances S3 throughput by leveraging every available shard to upload backup files concurrently. By distributing the load across multiple shards, we significantly improve the upload performance. Each shard retrieves an SSTable and processes its files sequentially, ensuring efficient, file-by-file uploads.
To prevent uncontrolled fiber creation and potential resource exhaustion, the backup task employs a directory semaphore from the sstables_manager. This mechanism helps regulate concurrency at the directory level, ensuring stable and predictable performance during large-scale backup operations.
Refs #22460
fixes: #22520
```
===========================================
Release build, master, smp-16, mem-32GiB
Bytes: 2342880184, backup time: 9.51 s …
```
=> backup: Optimize S3 throughput with shard-based upload

test/boost/s3_test.cc, utils/s3/client.cc, utils/s3/client.hh
Implement the CopyObject API to directly copy S3 object from one location to another. This implementation consumes zero networking overhead on the client side since the object is copied internally by S3 machinery
Usage example: Backup of tiered SSTables - you already have SSTables on S3, CopyObject is the ideal way to go
No need to backport since we are adding new functionality for a future use
=> Add CopyObject API implementation to S3 client

locator/load_sketch.hh, locator/network_topology_strategy.cc, locator/tablets.cc, locator/tablets.hh, test/boost/tablets_test.cc, test/lib/topology_builder.hh
Fixes the following scenario:
1. Scale out adds new nodes to each rack
2. Table is created - all tablets are allocated to new nodes because they have low load
3. Rebalancing moves tablets from old nodes to new nodes - table balance for the new table is not fixed
We're wrong to try to equalize global load when allocating tablets,
and we should equalize per-table load instead, and let background load
balancing fix it in a fair way. It will add to the allocated storage
imbalance, but:
1. The table is initially empty, so doesn't impact actual storage imbalance.
2. It's more important to avoid overloading CPU on the nodes - imbalance hurts this aspect immediately.
3. If the table was created before imbalance was formed, we would end up in the same situation as in the problematic scenario after …
=> tablets: Equalize per-table balance when allocating tablets for a new table

test/boost/s3_test.cc
This PR introduces a cleanup mechanism in s3_tests to remove uploaded objects after the test completes, ensuring a clean testing environment. Additionally, the recently added test has been refactored and split into smaller, more maintainable parts, improving readability and extending its coverage to include the "proxied" case.
As these changes primarily improve code aesthetics and maintainability, backporting is not necessary.
Refs: https://github.com/scylladb/scylladb/issues/23830
=> Refactor and enhance s3_tests

alternator/executor.cc, cql3/statements/alter_table_statement.cc, cql3/statements/alter_table_statement.hh, cql3/statements/create_view_statement.cc, db/schema_applier.cc, db/schema_tables.cc, db/schema_tables.hh, db/view/base_info.hh, db/view/view.cc, db/view/view.hh, db/view/view_update_generator.cc, db/view/view_update_generator.hh, frozen_schema.cc, frozen_schema.hh, index/secondary_index_manager.cc, replica/database.cc, replica/table.cc, schema/schema.cc, schema/schema.hh, schema/schema_builder.hh, schema/schema_registry.cc, schema/schema_registry.hh, service/migration_manager.cc, test/boost/cql_query_test.cc, test/boost/schema_registry_test.cc, test/cluster/mv/test_mv_building.py, tools/schema_loader.cc, view_info.hh
Currently, the base_info may or may not be set in view schemas.
Even when it's set, it may be modified. This necessitates extra
checks when handling view schemas, as we'll as potentially causing
errors when we forget to set it at some point.
Instead, we want to make the base info an immutable member of view
schemas (inside view_info). To achieve this, in this series we remove
all base_info members that can change due to a base schema update,
and we calculate the remaining values during view update generation,
using the most up-to-date base schema version.
To calculate the values that depend on the base schema version, we
need to iterate over the view primary key and find the corresponding
columns, which adds extra overhead for each batch of view updates.
However, this overhead should be …
=> mv: make base_info in view schemas immutable

cdc/generation.cc, service/topology_coordinator.cc, test/cluster/test_bad_initial_token.py
In case when dht::boot_strapper::get_boostrap_tokens fail to parse the
tokens, the topology coordinator handles the exception and schedules a
rollback. However, the current code tries to continue with the topology
coordinator logic even if an exception occurs, leaving boostrap_tokens
empty. This does not make sense and can actually cause issues,
specifically in prepare_and_broadcast_cdc_generation_data which
implicitly expect that the bootstrap_tokens of the first node in the
cluster will not be empty.
Fix this by adding the missing break.
Fixes: scylladb/scylladb#23897
From the code inspection alone it looks like 2025.1 and 6.2 have this problem, so marking for backport to both of them.
=> topology coordinator: do not proceed further on invalid boostrap tokens

test/boost/sstable_3_x_test.cc
It had recently been patched to re-use the sstables::test class functionality (#23697), now it can be put on some more strict diet.
=> Simplify test/sstable_assertions class API

sstables_loader.cc
This change addresses a critical race condition in the sstables_loader where `get_progress()` could access invalid `progress_holder` instances after `release_resources()` destroyed them.
Problem:
- Progress tracking uses two components: `_progress_state` (tracks state) and `_progress_per_shard` (sharded service with actual progress data)
- `get_progress()` first checks if `_progress_state` is initialized, then accumulates progress from `_progress_per_shard`
- As both functions are coroutines, `get_progress()` could be preempted after state check but before accessing `_progress_per_shard`
- If `release_resources()` runs during this preemption, it destroys the `progress_holder` instances in `_progress_per_shard`, causing `get_progress()` to access invalid memory.
Solution:
- Implemented …
=> sstables_loader: fix the racing between get_progress() and release_resources()

service/raft/group0_voter_calculator.hh, service/raft/group0_voter_handler.cc, test/boost/group0_voter_calculator_test.cc, test/cluster/test_raft_voters.py
Fix an issue in the voter calculator where existing voters were not retained across data centers and racks in certain scenarios. This occurred when voters were distributed across more data centers and racks than the maximum allowed number of voters.
Previously, the prioritization logic for data centers and racks did not consider the number of existing assigned voters. It only prioritized nodes within a single data center or rack, which could result in unnecessary reassignment of voters.
Improved the prioritization logic to account for the number of existing assigned voters in each data center and rack.
Additionally, the limited voters feature did not account for the existing topology coordinator (Raft leader) when selecting voters to be removed. As a result, the limited voters calculator …
=> raft: make sure to retain the existing voters including the current leader (topology coordinator)

replica/table.cc, sstables/sstable_set.cc, test/cluster/test_tablets2.py
When schema is changed, sstable set is updated according to the compaction strategy of the new schema (no changes to set are actually made, just the underlying set type is updated), but the problem is that it happens without a lock, causing a use-after-free when running concurrently to another set update.
Example:
1) A: sstable set is being updated on compaction completion
2) B: schema change updates the set (it's non deferring, so it happens in one go) and frees the set used by A.
3) when A resumes, system will likely crash since the set is freed already.
ASAN screams about it:
SUMMARY: AddressSanitizer: heap-use-after-free sstables/sstable_set.cc ...
Fix is about deferring update of the set on schema change to compaction, which is triggered after new schema is set. Only strategy state …
=> replica: Fix use-after-free with concurrent schema change and sstable set update

exceptions/coordinator_result.hh, exceptions/exceptions.hh, generic_server.cc, generic_server.hh, service/mapreduce_service.cc, service/storage_proxy.cc, test/cluster/test_long_query_timeout_erm.py, test/pylib/manager_client.py, transport/server.cc, transport/server.hh
Before this change, if a read executor had just enough targets to
achieve query's CL, and there was a connection drop (e.g. node failure),
the read executor waited for the entire request timeout to give drivers
time to execute a speculative read in a meantime. Such behavior don't
work well when a very long query timeout (e.g. 1800s) is set, because
the unfinished request blocks topology changes.
This change implements a mechanism to thrown a new
read_failure_exception_with_timeout in the aforementioned scenario.
The exception is caught by CQL server which conducts the waiting, after
ERM is released. The new exception inherits from read_failure_exception,
because layers that don't catch the exception (such as mapreduce
service) should handle the exception just a regular read_failure. …
=> transport: storage_proxy: release ERM when waiting for query timeout

compress.cc, compress.hh, configure.py, init.cc, main.cc, sstable_dict_autotrainer.cc, sstables/sstable_compressor_factory.hh, test/boost/CMakeLists.txt, test/boost/mutation_test.cc, test/boost/sstable_compaction_test.cc, test/boost/sstable_compressor_factory_test.cc, test/boost/sstable_datafile_test.cc, test/boost/sstable_move_test.cc, test/lib/cql_test_env.cc, test/lib/sstable_test_env.hh, test/lib/test_services.cc, test/perf/perf_sstable.cc, test/perf/perf_sstable.hh, tools/load_system_tablets.cc, tools/schema_loader.cc, tools/scylla-sstable.cc
compress: distribute compression dictionaries over shards
We don't want each shard to have its own copy of each dictionary.
It would unnecessary pressure on cache and memory.
Instead, we want to share dictionaries between shards.
Before this commit, all dictionaries live on shard 0.
All other shards borrow foreign shared pointers from shard 0.
There's a problem with this setup: dictionary blobs receive many random
accesses. If shard 0 is on a remote NUMA node, this could pose
a performance problem.
Therefore, for each dictionary, we would like to have one copy per NUMA node,
not one copy per the entire machine. And each shard should use the copy
belonging to its own NUMA node. This is the main goal of this patch.
There is another issue with putting all dicts on shard 0: it eats
an …
=> compress: make sstable compression dictionaries NUMA-aware 

service/storage_service.cc, test/cluster/test_change_ip.py
Used host id to check if the update is for the node itself. Using IP is unreliable since if a node is restarted with different IP a gossiper message with previous IP can be misinterpreted as belonging to a different node.
Fixes: #22777
Backport to 2025.1 since this fixes a crash. Older version do not have the code.
=> Correctly skip updating node's own ip address due to oudated gossiper data 

test/boost/logalloc_test.cc, utils/logalloc.cc, utils/logalloc.hh
The test is failing in CI sometimes due to performance reasons.
There are at least two problems:
1. The initial 500ms (wall time) sleep might be too short. If the reclaimer
doesn't manage to evict enough memory during this time, the test will fail.
2. During the 100ms (thread CPU time) window given by the test to background
reclaim, the `background_reclaim` scheduling group isn't actually
guaranteed to get any CPU, regardless of shares. If the process is
switched out inside the `background_reclaim` group, it might
accumulate so much vruntime that it won't get any more CPU again
for a long time.
We have seen both.
This kind of timing test can't be run reliably on overcommitted machines
without modifying the Seastar scheduler to support that (by e.g. using
thread clock instead of wall time …
=> logalloc_test: don't test performance in test background_reclaim

compress.cc, test/cluster/test_sstable_compression_dictionaries_basic.py
compress: fix an internal error when a specific debug log is enabled
While iterating over the recent https://github.com/scylladb/scylladb/commit/69684e16d867bc98b52861b7fce3d9ac14e6afad,
series I shot myself in the foot by defining `algorithm_to_name(algorithm::none)`
to be an internal error, and later calling that anyway in a debug log.
(Tests didn't catch it because there's no test which simultaneously
enables the debug log and configures some table to have no compression).
This proves that `algorithm_to_name` is too much of a footgun.
Fix it so that calling `algorithm_to_name(algorithm::none)` is legal.
In hindsight, I should have done that immediately.
Fixes #23624
Fix for recently-added code, no backporting needed.
=> compress: fix an internal error when a specific debug log is enabled

serializer_impl.hh, service/raft/raft_sys_table_storage.cc
The get_blob method linearizes data by copying it into a single buffer, which can cause 'oversized allocation' warnings.
In this commit we avoid copying by creating input stream on top of the original fragmened managed bytes, returned by untyped_result_set_row::get_view.
fixes scylladb/scylladb#23903
backport: no need, not a critical issue.
=> raft_sys_table_storage: avoid temp buffer when  deserializing log_entry

api/api-doc/storage_service.json, api/storage_service.cc, docs/operating-scylla/nodetool-commands/cleanup.rst, docs/operating-scylla/nodetool-commands/refresh.rst, replica/distributed_loader.cc, replica/distributed_loader.hh, sstables_loader.cc, sstables_loader.hh, test/nodetool/test_refresh.py, tools/scylla-nodetool.cc
The non-streaming loading of sstables performs cleanup since recently [1]. For vnodes, unfortunately, cleanup is almost unavoidable, because of the nature of vnodes sharding, even if sstable is already clean. This leads to waste of IO and CPU for nothing. Skipping the cleanup in a smart way is possible, but requires too many changes in the code and in the on-disk data. However, the effort will not help existing SSTables and it's going to be obsoleted by tablets some time soon.
Said that, the easiest way to skip cleanup is the explicit --skip-cleanup option for nodetool and respective skip_cleanup parameter for API handler.
New feature, no backport
fixes #24136
refs #12422 [1]
=> Add ability to skip SSTables cleanup when loading them

test/cluster/object_store/test_backup.py
Lots of code from this test can be reused in PR #23861. I'm splitting it now in this change so we can merge it cleanly as a separate patch.
Refs #23564
=> Refactor out code from `test_restore_with_streaming_scopes`

test/boost/chunked_vector_test.cc, utils/chunked_vector.hh
chunked_vector is a replacement for std::vector that avoids large contiguous
allocations.
In this series, we add some missing modifiers and improve quality-of-life for
chunked_vector users (the static_assert patch).
Those modifiers were generally unused since they have O(n) complexity
and therefore not useful for hot paths, but they are used in some
control plane code on vectors which we'd like to replace with chunked_vectors.
A candidate for such a replacement is token_range_vector (see #3335).
This is a prerequisite for fixing some minor stalls; I don't expect we'll backport
fixes to those stalls.
=> utils: chunked_vector: add some modifiers

cql3/statements/create_index_statement.cc, cql3/statements/index_prop_defs.cc, index/secondary_index_manager.cc, index/secondary_index_manager.hh, replica/schema_describe_helper.hh, schema/schema.cc, schema/schema.hh, test/boost/secondary_index_test.cc, test/cqlpy/test_vector_index.py
This pull request adds support for creating custom indexes (at a metadata level) as long as a supported custom class is provided (currently only vector search).
The patch contains:
- a change in CREATE INDEX statement that allows for the USING keyword to be present as long as one of the supported classes is used
-  support for describing custom indexes in the DESCRIBE statement
- unit tests 
Co-authored by: @Balwancia
=> index: implement schema management layer for vector search indexes

test/auth_cluster/test_auth_no_quorum.py, test/auth_cluster/test_auth_raft_command_split.py, test/auth_cluster/test_auth_v2_migration.py, test/auth_cluster/test_raft_service_levels.py, test/pylib/internal_types.py, test/pylib/manager_client.py, test/pylib/scylla_cluster.py, test/pytest.ini, test/topology/conftest.py, test/topology/suite.yaml, test/topology/test_automatic_cleanup.py, test/topology/test_change_ip.py, test/topology/test_cluster_features.py, test/topology/test_concurrent_schema.py, test/topology/test_coordinator_queue_management.py, test/topology/test_global_ignore_nodes.py, test/topology/test_gossiper.py, test/topology/test_mutation_schema_change.py, test/topology/test_mv.py, test/topology/test_nodetool.py, test/topology/test_random_tables.py, test/topology/test_replace_alive_node.py, test/topology/test_snapshot.py, test/topology/test_start_bootstrapped_with_invalid_seed.py, test/topology/test_tls.py, test/topology/test_topology_failure_recovery.py, test/topology/test_topology_rejoin.py, test/topology/test_topology_remove_decom.py, test/topology/test_topology_schema.py, test/topology_custom/test_raft_cluster_features.py
So that a multi-dc/multi-rack cluster can be populated in a single call.
Original PR: scylladb/scylladb#23341
Fixes https://github.com/scylladb/scylladb/issues/23551
(cherry picked from commit 0fdf2a2090b0151c6edbe449d7a29d919e8f06e4)
=> [Backport 2025.1] Merge 'test/pylib: servers_add: support list of property_files' from Benny Halevy

api/api-doc/compaction_manager.json, api/compaction_manager.cc, compaction/compaction.cc, compaction/compaction.hh, compaction/compaction_garbage_collector.hh, compaction/compaction_manager.cc, compaction/compaction_manager.hh, db/compaction_history_entry.hh, db/read_context.hh, db/system_keyspace.cc, db/system_keyspace.hh, docs/operating-scylla/nodetool-commands/compactionhistory.rst, gms/feature_service.hh, mutation/mutation_compactor.hh, mutation/mutation_partition.cc, mutation/mutation_tombstone_stats.hh, readers/compacting.hh, readers/mutation_readers.cc, replica/table.cc, sstables/basic_info.hh, test/boost/mutation_test.cc, test/boost/sstable_compaction_test.cc, test/cqlpy/test_compaction.py, test/cqlpy/util.py, test/nodetool/test_compactionhistory.py, test/rest_api/test_compactionhistory.py, tools/scylla-nodetool.cc
Currently, the `system.compaction_history` table miss information like the type of compaction (cleanup, major, resharding, etc), the sstable generations involved (in and out), shard's id the compaction was triggered on and statistics on purged tombstones to be collected during compaction.
The series extends the table with the following columns:
-  "compaction_type" (text)
- "shard_id" (int)
- "sstables_in" (list<sstableinfo_type>)
- "sstables_out" (list<sstableinfo_type>)
- "total_tombstone_purge_attempt" (long)
- "total_tombstone_purge_failure_due_to_overlapping_with_memtable" (long)
- "total_tombstone_purge_failure_due_to_overlapping_with_uncompacting_sstable" (long)
with a user defined type `sstableinfo_type` that holds the information about sstable file
- generation (uuid)
- origin …
=> Extend compaction_history table with additional compaction statistics

api/api.cc, api/api.hh, api/column_family.cc, api/storage_service.cc, api/storage_service.hh, api/tasks.cc, test/rest_api/test_storage_service.py
The class was introduced to facilitate path and query parameters parsing from requests, but in fact it's mostly dead code.
First, the class introduces the concept of  "mandatory" parameters which are seastar path params. If missing, the parameter validation throws, but in all cases where this option is used in scylla it's impossible to get empty path param -- if the parameter is missing seastar returns 404 (not found) before calling handler.
Second, the req_params::get<T>() doesn't work for anything but string argument (or types such that optional<T> can be implicitly casted to optional<sstring>). And it's in fact only used to get sstrings, so it compiles and works so far.
The remaining ability to parse bool from string is partially duplicated by the validate_bool() method. Using plain …
=> Remove req_params facility from API

dht/i_partitioner_fwd.hh, idl/streaming.idl.hh, message/messaging_service.hh, partition_range_compat.hh, streaming/stream_request.hh
token_range_vector is a sequence of intervals of tokens. It is used
to describe vnodes or token ranges owned by shards.
Since tokens are bloated (16 bytes instead of 8), and intervals are bloated
(40 byte of overhead instead of 8), and since we have plenty of token ranges,
such vectors can exceed our allocation unit of 128 kB and cause allocation stalls.
This series fixes that by first generalizing some helpers and then changing
token_range_vector to use chunked_vector.
Although this touches IDL, there is no compatibility problem since the encoding
for vector and chunked_vector are identical.
There is no performance concern since token_range_vector is never used on
any hot path (hot paths always contain a partition key).
Fixes #3335.
Fixes #24115.
No backport: minor performance fix that …
=> token_range_vector: fragment

replica/table.cc, replica/tablets.cc, sstables/sstable_set.cc, test/boost/sstable_set_test.cc, test/cluster/test_tablets_merge.py
Consider the following scenario:
1) let's assume tablet 0 has range [1, 5] (pre merge)
2) tablet merge happens, tablet 0 has now range [1, 10]
3) tablet_sstable_set isn't refreshed, so holds a stale state, thinks tablet 0 still has range [1, 5]
4) during a full scan, forward service will intersect the full range with tablet ranges and consume one tablet at a time
5) replica service is asked to consume range [1, 10] of tablet 0 (post merge)
We have two possible outcomes:
With cache bypass:
1) cache reader is bypassed
2) sstable reader is created on range [1, 10]
3) unrefreshed tablet_sstable_set holds stale state, but select correctly all sstables intersecting with range [1, 10]
With cache:
1) cache reader is created
2) finds partition with token 5 is cached
3) sstable reader is created on …
=> tablets: fix missing data after tablet merge 

test/pylib/resource_gather.py
Move of the run_process done in https://github.com/scylladb/scylladb/pull/24091 was not fully correct. The method run_process was not overridden in the class ResourceGatherOn, so no metrics are collected at all.
Additionally, fix metrics DB location second time.
=> test.py: fix metrics gathering

test/boost/tablets_test.cc, test/lib/cql_test_env.cc
This PR adjusts existing Boost tests so they respect the invariant
introduced by enabling `rf_rack_valid_keyspaces` configuration option.
We disable it explicitly in more problematic tests. After that, we
enable the option by default in the whole test suite.
Fixes scylladb/scylladb#23958
Backport: backporting to 2025.1 to be able to test the implementation there too.
=> test/boost: Adjust tests to RF-rack-valid keyspaces

test/pylib/cpp/boost/boost_facade.py, test/pylib/cpp/unit/unit_facade.py
Switching to f-string formatting to simplify the code and to unify it with a general approach for formatting strings.
If the log file absent or empty test fails with an error regarding a missing boost log file, however, it's not helpful since it's not a root cause of the fail. Adding logic to log this issue as a warning in a pytest's log file and continue with providing results to the pytest itself.
=> test.py: refactor test facades for better error handling

alternator/executor.cc, alternator/executor.hh, alternator/rmw_operation.hh, alternator/stats.cc, alternator/stats.hh, replica/database.hh, test/alternator/test_metrics.py
This series introduces per-table metrics support for Alternator. It includes the following commits:
Add optional per-table metrics for Alternator
Introduces a shared_ptr-based mechanism that allows Alternator to register per-table metrics. These metrics follow the table's lifecycle, similar to how CQL metrics are handled. The use of shared_ptr ensures no direct dependency between table stats and Alternator.
Enable registration of stats objects per table
Adds support for registering a stats object using a keyspace and table name. Per-table metrics are prefixed with alternator_table to differentiate them from per-shard metrics. Metrics are reported once per node, and those not meaningful at the table level (e.g. create/delete) are excluded. All metrics use the skip_when_empty flag.
Update …
=> Add Support for Per-Table Metrics in Alternator

test/cluster/dtest/audit_test.py, test/cluster/dtest/ccmlib/scylla_cluster.py, test/cluster/dtest/tools/cluster.py, test/cluster/dtest/tools/data.py, test/cluster/suite.yaml
Copied the entire audit_test.py from scylladb/scylla-dtest, to remove the entire file from scylla-dtest after this patch series is merged. The motivation is to move entire audit testing to from dtests, to make it easier to maintain and more reliable.
After audit_test.py was moved from dtests to test.py, someissues that require fixing arose due to differences between the frameworks.
No backport, moving audit_test.py to test.py is a new testing effort.
=> test: dtest: move audit_test.py to test.py

alternator/executor.cc, db/tags/utils.cc, test/topology_custom/test_alternator.py
In ScyllaDB, schema modification operations use "optimistic locking": A schema operation reads the current schema, decides what it wants to do and prepares changes to the schema, and then attempts to commit those changes - but only if the schema hasn't changed since the first read. If the schema has already been changed by some other node - we need to try again. In a loop.
In Alternator, there are six operations that perform schema modification: CreateTable, DeleteTable, UpdateTable, TagResource, UntagResource and UpdateTimeToLive. All of them were missing this loop. We knew about this - and even had FIXME in all places. So all these operations, when facing contention of concurrent schema modifications on different nodes may fail one of these operations with an error like:
Internal server …
=> [backport 2025.1] alternator: fix schema "concurrent modification" errors

test/boost/s3_test.cc, utils/s3/client.cc, utils/s3/client.hh
Revamped the `range` class to actively manage its state by enforcing validation on all modifications. This prevents overflow, invalid states, and ensures the object size does not exceed the 5TiB limit in S3. This should address and prevent future problems related to this issue https://github.com/minio/minio/issues/21333
No backport needed since this problem related only to this change https://github.com/scylladb/scylladb/pull/23880
=> s3_client: Refactor `range` class for state validation

test.py, test/cluster/conftest.py, test/cluster/test_sstable_compression_dictionaries_upgrade.py, test/pylib/manager_client.py, test/pylib/scylla_cluster.py, test/pylib/suite/python.py, test/pylib/suite/topology.py, tools/toolchain/dbuild
This PR adds an upgrade test for SSTable compression with shared dictionaries, and adds some bits to pylib and test.py to support that.
In the series, we:
1. Mount `$XDG_CACHE_DIR` into dbuild.
2. Add a pylib function which downloads and installs a released ScyllaDB package into a subdirectory of `$XDG_CACHE_DIR/scylladb/test.py`, and returns the path to `bin/scylla`.
3. Add new methods and params to the cluster manager, which let the test start nodes with historical Scylla executables, and switch executables during the test.
4. Add a test which uses the above to run an upgrade test between the released package and the current build.
5. Add `--run-internet-dependent-tests` to `test.py` which lets the user of `test.py` skip this test (and potentially other internet-dependent tests in the …
=> test: introduce upgrade tests to test.py, add a SSTable dict compression upgrade test

main.cc, test/cluster/test_config_live_updates.py
In https://github.com/scylladb/scylladb/commit/f96d30c2b50856aefca8aff28eb0f23e3d21b5d8
we introduced the maintenance service, which is an additional
instance of auth::service. But this service has a somewhat
confusing 2-level startup mechanism: it's initialized with
sharded<Service>::start and then auth::service::start
(different method with the same name to confuse even more).
When maintenance_socket was disabled (default setting), the code
did only the first part of the startup. This registered a config
observer but didn't create a permission_cache instance.
As a result, a crash on SIGHUP when config is reloaded can occur.
Fixes: https://github.com/scylladb/scylladb/issues/24528
Backport: all not eol versions since 6.0 and 2025.1
=> main: don't start maintenance auth service if not enabled

auth/common.cc, auth/common.hh, auth/ldap_role_manager.cc, auth/password_authenticator.cc, auth/password_authenticator.hh, auth/service.cc, auth/standard_role_manager.cc, auth/standard_role_manager.hh, test/cluster/auth_cluster/test_auth_after_reset.py, test/cluster/auth_cluster/test_auth_default_superuser_replaced.py, test/pylib/internal_types.py, test/pylib/manager_client.py, test/pylib/scylla_cluster.py
This patchset fixes regression introduced by https://github.com/scylladb/scylla-enterprise/commit/7e749cd848f8c7590f6297f98c6aa39afa36346c when we started re-creating default superuser role and password from the config, even if new custom superuser was created by the user.
Now we'll check, first with CL LOCAL_ONE if there is a need to create default superuser role or password, confirm
it with CL QUORUM and only then atomically create role or password.
If server is started without cluster quorum we'll skip creating role or password.
Fixes https://github.com/scylladb/scylladb/issues/24469
Backport: all versions since 2024.2
=> Fix for cassandra role gets recreated after DROP ROLE

audit/audit.cc, test/cluster/dtest/audit_test.py
Audit component defines `audit` logger which it uses only for `error` and `info` logs,
regarding `audit` module initialization and errors during audit log writing.
This change introduces `debug` level logs on the happy path of audit log writes.
Fixes: https://github.com/scylladb/scylladb/issues/23773
No backport needed - this is a small quality-of-life improvement.
=> audit: introduce debug level logs on happy path

test/pylib/cpp/facade.py, test/pylib/manager_client.py
Add run ID for process output file to be not overwritten in the next case: first run failed, second passed. They are using the same name, so the second run will overwrite and delete the file. This will help to investigate in case of C++ test fails
Add attaching Scylla log files to allure report in case test failed. This is an alternative for link in JUnit report that exists in CI. That change will help to investigate the cluster tests fails. Example can be found in the failed [job](https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/2980/allure/).
Backport is not needed, this is only framework enhancements
=> test.py: enhance allure reporting

alternator/executor.cc, docs/alternator/compatibility.md, test/alternator/test_gsi.py, test/alternator/test_gsi_updatetable.py, test/alternator/test_lsi.py, test/alternator/test_streams.py, test/alternator/test_table.py, test/alternator/util.py
Whereas DynamoDB limits the names of tables, LSIs and GSIs to 255 characters each, Alternator currently has different (and lower) limitations:
1. A table name must be up to 222 characters.
2. For a GSI, the sum of the table's and GSI's name length, plus 1, must be up to 222 characters.
3. For an LSI, the sum of the table's and LSI's name length, plus 2, must be up to 222 characters.
The first patch documents these existing limitations, improves their testing, and fixes a tiny bug found by one of the tests (where UpdateTable adding a GSI's limit testing is off by one).
The second patch unfortunately shows with a reproducer (issue #24598) this limit of 222 is problematic and we may need to lower it: If a user creates a table of length 222 and then enables Alternator streams, Scylla shuts …
=> alternator: improve, document and test table/index name lengths

compound.hh, mutation/mutation_partition.cc, mutation/mutation_partition.hh, mutation/mutation_partition_v2.cc, test/boost/mutation_test.cc, test/boost/row_cache_test.cc
Make sure the keys are full prefixes as it is expected to be the case for rows. At severeal occasions we have seen empty row keys make their ways into the sstables, despite the fact that they are not allowed by the CQL frontend. This means that such empty keys are possibly results of memory corruption or use-after-{free,copy} errors. The source of the corruption is impossible to pinpoint when the empty key is discovered in the sstable. So this patch adds checks for such keys to places where mutations are built: when building or unserializing mutations.
Fixes: https://github.com/scylladb/scylladb/issues/24506
Not a typical backport candidate (not a bugfix or regression fix), but we should still backport so we have the additional checks deployed to existing production clusters.
=> mutation: check key of inserted rows

repair/repair.cc, service/topology_coordinator.cc, test/cluster/test_tablets.py
Currently, repair_service::repair_tablets starts repair if there
is no ongoing tablet operations. The check does not consider global
topology operations, like tablet resize finalization. 
Hence, if:
- topology is in the tablet_resize_finalization state;
- repair starts (as there is no tablet transitions) and holds the erm;
- resize finalization finishes;
then the repair sees a topology state different than the actual -
it does not see that the storage groups were already split.
Repair code does not handle this case and it results with 
on_internal_error.
Start repair when topology is not busy. The check isn't atomic,
as it's done on a shard 0. Thus, we compare the topology versions
to ensure that the business check is valid.
Fixes: https://github.com/scylladb/scylladb/issues/24195.
Needs …
=> repair: postpone repair until topology is not busy 

auth/service.cc, auth/standard_role_manager.cc, cql3/description.cc, cql3/description.hh, cql3/functions/aggregate_fcts.cc, cql3/functions/user_function.cc, cql3/statements/describe_statement.cc, cql3/statements/describe_statement.hh, data_dictionary/data_dictionary.cc, replica/table.cc, schema/schema.cc, schema/schema.hh, service/qos/service_level_controller.cc, test/boost/cql_query_test.cc, test/cluster/test_describe.py, test/lib/random_schema.cc, tools/scylla-sstable.cc, types/types.cc, utils/managed_string.hh
When describing a table, we need to do it carefully: if some
columns were dropped, we must specify that explicitly by
```
ALTER TABLE {table} DROP {column} USING TIMESTAMP ...
```
in the result of the DESCRIBE statement. Failing to do so
could lead to data resurrection.
However, if a table has been altered many, many times,
we might end up with a huge create statement. Constructing
it could, in turn, trigger an oversized allocation.
Some tests ran into that very problem in fact.
In this commit, we want to mitigate the problem: instead of
allocating a contiguous chunk of memory for the create
statement, we use `bytes_ostream` and `managed_bytes` to
possibly keep data scattered in memory. It makes handling
`cql3::description` less convenient in the code, but since
the struct is pretty much …
=> cql3: Represent create_statement using managed_bytes

test/boost/s3_test.cc, test/boost/test_config.yaml, test/pylib/s3_proxy.py, utils/s3/client.cc, utils/s3/client.hh
- Fix missing negation in the `if` in the background downloading fiber
- Add test to catch this case
- Improve the s3 proxy to inject errors if the same resource requested more than once
- Suppress client retry since retrying the same request when each produces multiple buffers may lead to the same data appear more than once in the buffer deque
- Inject exception from the test to simulate response callback failure in the middle
No need to backport anything since this class in not used yet
=> S3 chunked download source bug fixes

conf/scylla.yaml, configure.py, cql3/query_processor.cc, cql3/query_processor.hh, cql3/statements/select_statement.cc, cql3/statements/select_statement.hh, db/config.cc, db/config.hh, docs/dev/protocols.md, main.cc, service/CMakeLists.txt, service/vector_store_client.cc, service/vector_store_client.hh, test/boost/CMakeLists.txt, test/boost/vector_store_client_test.cc, test/lib/cql_test_env.cc, utils/sequential_producer.hh
Vector Store service is a http server which provides vector search index and an ANN (Approximate Nearest Neighbor) functionality. Vector Store retrieves metadata & data from Scylla about indexes using CQL protocol & CDC functionality. Scylla will request ann search using http api.
Commits for the patch:
- implement initial `vector_store_client` service. It adds also a parameter `vector_store_uri` to the scylla.
- refactor sequential_producer as abortable
- implement ip addr retrieval from dns. The uri for Vector Store must contains dns name, this commit implements ip addr refreshing functionality
- refactor primary_key as a top-level class. It is needed for the forward declaration of a primary_key
- implement ANN API. It implements a core ANN search request functionality, adds Vector …
=> vector_store_client: implement vector_store_client service

cql3/statements/describe_statement.cc, cql3/statements/index_target.cc, cql3/statements/index_target.hh, db/schema_tables.cc, index/secondary_index_manager.cc, index/secondary_index_manager.hh, index/vector_index.cc, index/vector_index.hh, test/cqlpy/test_describe.py, test/cqlpy/test_vector_index.py
This PR adds a way for custom indexes to decide whether a view should be created for them, as for the vector_index the view is not needed, because we store it in the external service. To allow this, custom logic for describing indexes using custom classes was added (as it used to depend on the view corresponding to an index).
Fixes: VECTOR-10
=> vector_index: do not create a view when creating a vector index

alternator/executor.cc, alternator/executor.hh, alternator/server.cc, alternator/streams.cc, alternator/ttl.cc, test/alternator/test_query.py, utils/rjson.cc, utils/rjson.hh
This series fixes one cause of oversized allocations - and therefore potentially stalls and increased tail latencies - in Alternator.
The first patch in the series is the main fix - the later patches are cleanups requested by reviewers but also involved other pre-existing code, so I did those cleanups as separate patches.
Alternator's Scan or Query operation return a page of results. When the number of items is not limited by a "Limit" parameter, the default is to return a 1 MB page. If items are short, a large number of them can fit in that 1MB. The test test_query.py::test_query_large_page_small_rows has 30,000 items returned in a single page.
In the response JSON, all these items are returned in a single array "Items". Before this patch, we build the full response as a RapidJSON object …
=> alternator: avoid oversized allocation in Query/Scan

repair/repair.cc, test/cluster/test_boot_nodes.py
repair: Speed up ranges calculation when small table optimization is on
Normally, during bootstrap, in repair_service::bootstrap_with_repair, we
need to calculate which range to sync data from carefully for the new
node. With small table optimization on, we pass a single full range and
all peer nodes to row level repair to sync data with. Now that we only
need to pass a single range and full peers, there is no need to calculate
the ranges and peers in repair_service::bootstrap_with_repair and drop
it later. The calculation takes time which slows down bootstrap, e.g.,
```
Jul 08 22:01:41.927785 cluster-scale-50-200-test-scayle-t-db-node-51209daa-93 scylla[5326]:
[shard 0:strm] repair - bootstrap_with_repair: started with
keyspace=system_distributed_everywhere, nr_ranges=23809
Jul 08 …
```
=> repair: Speed up ranges calculation when small table optimization is on

service/migration_manager.cc, streaming/consumer.cc, test/cluster/test_streaming_deadlock.py
This issue happens with removenode, when RBNO is disabled, so range
streamer is used.
The deadlock happens in a scenario like this:
1. Start 3 nodes: {A, B, C}, RF=2
2. Node A is lost
3. removenode A
4. Both B and C gain ownership of ranges.
5. Streaming sessions are started with crossed directions: B->C, C->B
Readers created by sender side exhaust streaming semaphore on B and C.
Receiver side attempts to obtain a permit indirectly by calling
check_needs_view_update_path(), which reads local tables. That read is
blocked and times-out, causing streaming to fail. The streaming writer
is already using a tracking-only permit.
Even if we didn't deadlock, and the streaming semaphore was simply exhausted
by other receiving sessions (via tracking-only permit), the query may still time-out due to …
=> streaming: Avoid deadlock by running view checks in a separate scheduling group

sstables/index_entry.hh, sstables/index_reader.hh, sstables/mx/partition_reversing_data_source.cc, sstables/mx/partition_reversing_data_source.hh, sstables/mx/reader.cc, sstables/sstable_mutation_reader.hh, sstables/sstables.cc, sstables/sstables.hh, sstables/types.hh, test/boost/sstable_3_x_test.cc, test/boost/sstable_datafile_test.cc, test/boost/sstable_mutation_test.cc, test/lib/index_reader_assertions.hh, tools/scylla-sstable.cc
This is a refactoring patch in preparation for BTI indexes. It contains no functional changes (or at least it's not intended to).
In this patch, we modify the sstable readers to use index readers through a new virtual `abstract_index_readers` interface.
Later, we will add BTI indexes which will also implement this interface.
This interface contains the methods of `index_reader` which are needed by sstable readers, and leaves out all other methods, such as `current_clustered_cursor`.
Not all methods of this interface will be implementable by a trie-based index later. For example, a trie-based index can't provide a reliable `get_partition_key()`, because — unlike the current index — it only stores partition keys for partitions which have a row index. So the interface will have to be further …
=> sstables: put index_reader behind a virtual interface

test.py
Quit from the repeats if the test is under the pytest runner directory and has some typos or is absent. This allows not going several times through the discovery and stopping execution.
Print a warning at the end of the run when no tests were selected by provided name.
Fixes: https://github.com/scylladb/scylladb/issues/24892
=> test.py: print warning when no tests found

service/storage_proxy.cc, service/storage_proxy.hh, service/storage_service.cc, test/cluster/test_unfinished_writes_during_shutdown.py
When a node shuts down, in storage service, after storage_proxy RPCs are stopped, some write handlers within storage_proxy may still be waiting for background writes to complete. These handlers hold appropriate ERMs to block schema changes before the write finishes. After the RPCs are stopped, these writes cannot receive the replies anymore.
If, at the same time, there are RPC commands executing `barrier_and_drain`, they may get stuck waiting for these ERM holders to finish, potentially blocking node shutdown until the writes time out.
This change introduces cancellation of all outstanding write handlers from storage_service after the storage proxy RPCs were stopped. 
Fixes scylladb/scylladb#23665
Backport: since this fixes an issue that frequently causes issues in CI, backport to 2025.1, …
=> storage_service: cancel all write requests after stopping transports

test.py, test/conftest.py, test/pylib/ldap_server.py, test/pylib/suite/base.py
Skip removing any artifacts when -s provided between test.py invocation.
Logs from the previous run will be overridden if tests were executed one
more time. Fox example:
1. Execute tests A, B, C with parameter -s
2. All logs are present even if tests are passed
3. Execute test B with parameter -s
4. Logs for A and C are from the first run
5. Logs for B are from the most recent run
Backport is not needed, since it framework enhancement.
=> test.py: skip cleaning testlog

locator/tablets.cc, locator/tablets.hh, replica/tablets.cc, service/topology_coordinator.cc, test/boost/locator_topology_test.cc, test/boost/network_topology_strategy_test.cc, test/boost/tablets_test.cc, test/perf/tablet_load_balancing.cc
As they are wasteful in many cases, it is better
to move the tablet_map if possible, or clone
it gently in an async fiber.
Add clone() and clone_gently() methods to
allow explicit copies.
* minor optimization, no backport needed
=> tablets: prevent accidental copy of tablets_map

gms/feature_service.cc, gms/feature_service.hh, init.cc, init.hh, main.cc, test/boost/schema_registry_test.cc, test/lib/cql_test_env.cc, test/lib/test_services.cc, test/manual/gossip.cc, test/manual/message.cc, tools/read_mutation.hh, tools/schema_loader.cc, tools/scylla-sstable.cc
Nowadays the way to configure an internal service is
1. service declares its config struct
2. caller (main/test/tool) fills the respective config with values it wants
3. the service is started with the config passed by value
The feature service code behaves likewise, but provides a helper method to create its config out of db::config. This PR moves this helper out of gms code, so that it doesn't mess with system-wide db::config and only needs its own small struct feature_config.
For the reference: similar changes with other services: #23705 , #20174 , #19166
=> Move feature-service config creation code out of feature-service itself

main.cc, service/raft/raft_group0.cc, service/raft/raft_group0.hh, service/raft/raft_group_registry.cc, service/raft/raft_group_registry.hh, service/storage_service.cc, test/cluster/test_cdc_generation_data.py, test/lib/cql_test_env.cc
Previously, `raft_group0::abort()` was called in `storage_service::do_drain` (introduced in #24418) to stop the group0 Raft server before destroying local storage. This was necessary because `raft::server` depends on storage (via `raft_sys_table_storage` and `group0_state_machine`).
However, this caused issues: services like `sstable_dict_autotrainer` and `auth::service`, which use `group0_client` but are not stopped by `storage_service`, could trigger use-after-free if `raft_group0` was destroyed too early. This can happen both during normal shutdown and when 'nodetool drain' is used.
This PR reworks the shutdown logic:
* Introduces `abort_and_drain()`, which aborts the server and waits for background tasks to finish, but keeps the server object alive. Clients will see …
=> raft_group0: split shutdown into abort-and-drain and destroy

db/config.cc, db/config.hh, generic_server.cc, generic_server.hh, test/cluster/auth_cluster/test_raft_service_levels.py, test/cluster/test_long_query_timeout_erm.py, test/cluster/test_write_query_during_cql_server_shutdown.py, test/pylib/manager_client.py, test/pylib/scylla_cluster.py, transport/controller.cc, transport/server.cc, transport/server.hh
This PR implements solution proposed in scylladb/scylladb#24481 
Instead of terminating connections immediately, the shutdown now proceeds in two stages: first closing the receive (input) side to stop new requests, then waiting for all active requests to complete before fully closing the connections.
The updated shutdown process is as follows:
1. Initial Shutdown Phase
* Close the accept gate to block new incoming connections.
* Abort all accept() calls.
* For all active connections:
* Close only the input side of the connection to prevent new requests.
* Keep the output side open to allow responses to be sent.
2. Drain Phase
* Wait for all in-progress requests to either complete or fail.
3. Final Shutdown Phase
* Fully close all connections.
Fixes scylladb/scylladb#24481
=> generic server: 2 step shutdown

auth/standard_role_manager.cc, service/qos/raft_service_level_distributed_data_accessor.cc, service/qos/raft_service_level_distributed_data_accessor.hh, service/qos/service_level_controller.cc, service/qos/service_level_controller.hh, service/qos/standard_service_level_distributed_data_accessor.cc, service/qos/standard_service_level_distributed_data_accessor.hh, test/boost/service_level_controller_test.cc, test/cluster/auth_cluster/test_raft_service_levels.py
Right now, service levels are migrated in one group0 command and auth is migrated in the next one. This has a bad effect on the group0 state reload logic - modifying service levels in group0 causes the effective service levels cache to be recalculated, and to do so we need to fetch information about all roles. If the reload happens after SL upgrade and before auth upgrade, the query for roles will be directed to the legacy auth tables in system_auth - and the query, being a potentially remote query, has a timeout. If the query times out, it will throw an exception which will break the group0 apply fiber and the node will need to be restarted to bring it back to work.
In order to solve this issue, make sure that the service level module does not start populating and using the service level …
=> qos: don't populate effective service level cache until auth is migrated to raft

dht/auto_refreshing_sharder.hh, dht/i_partitioner.cc, dht/token-sharding.hh, locator/tablet_sharder.hh, service/storage_proxy.cc, test/cluster/test_tablets_lwt.py
Currently, `get_cas_shard` uses `sharder.shard_for_reads` to decide which shard to use for LWT execution—both on replicas and the coordinator.
If the coordinator is not a replica, `shard_for_reads` returns a default shard (shard 0). There are at least two problems with this:
* shard 0 can become overloaded, because all LWT coordinators-but-not-replacas are served on it.
* mismatch with replicas: the default shard doesn't match what `shard_for_reads` returns on replicas. This hinders the "same shard for client and server" RPC level optimization.
In this PR we change `get_cas_shard` to use a primary replica shard if the current node is not a replica. This guarantees that all LWT coordinators for the same tablet will be served on the same shard. This is important for LWT coordinator locks …
=> storage_proxy.cc: get_cas_shard: fallback to the primary replica shard

test/boost/reusable_buffer_test.cc, test/cqlpy/test_protocol_exceptions.py, test/cqlpy/util.py, transport/server.cc, transport/server.hh, utils/reusable_buffer.hh
`protocol_exception` is thrown in several places. This has become a performance issue, especially when starting/restarting a server. To alleviate this issue, throwing the exception has to be replaced with returning it as a result or an exceptional future.
This PR replaces throws in the `transport/server` module. This is achieved by using result_with_exception, and in some places, where suitable, just by creating and returning an exceptional future.
There are four commits in this PR. The first commit introduces tests in `test/cqlpy`. The second commit refactors transport server `handle_error` to not rethrow exceptions. The third commit refactors reusable buffer writer callbacks. The fourth commit replaces throwing `protocol_exception` to returning it.
Based on the comments on an issue …
=> [Backport 2025.3] transport: remove throwing protocol_exception on connection start

cql3/Cql.g, cql3/restrictions/statement_restrictions.cc, cql3/statements/raw/select_statement.hh, cql3/statements/select_statement.cc, cql3/statements/select_statement.hh, cql3/util.hh, db/schema_tables.cc, db/schema_tables.hh, index/secondary_index_manager.cc, index/secondary_index_manager.hh, index/vector_index.cc, index/vector_index.hh, service/vector_store_client.hh, test/cqlpy/cassandra_tests/vector_invalid_query_test.py, test/cqlpy/test_invalid_ann_queries.py
This pull request is an addition of ANN OF queries.
The patch contains:
- CQL syntax for ORDER BY `vector_column_name` ANN OF `vector_literal` clause of SELECT statements.
- implementation of external ANN queries (using vector-store service)
- tests
Example syntax:
```
SELECT comment
FROM cycling.comments_vs
ORDER BY comment_vector ANN OF [0.1, 0.15, 0.3, 0.12, 0.05]
LIMIT 3;
```
Limit can be between 1 and 1000 - same as for Cassandra.
Co-authored-by: @janpiotrlakomy @smoczy123 
Fixes: VECTOR-48
Fixes: VECTOR-46
=> cql, vector_search: implement read path

api/api-doc/storage_service.json, api/storage_service.cc, dist/common/nodetool-completion, docs/operating-scylla/nodetool-commands/dropquarantinedsstables.rst, docs/operating-scylla/nodetool.rst, replica/database.hh, replica/table.cc, test/boost/database_test.cc, test/nodetool/test_dropquarantinedsstables.py, test/rest_api/test_storage_service.py, tools/scylla-nodetool.cc
Added a new POST endpoint `/storage_service/drop_quarantined_sstables` to the REST API.
This endpoint allows dropping all quarantined SSTables either globally or
for a specific keyspace and tables.
Optional query parameters `keyspace` and `tables` (comma-separated table names) can be
provided to limit the scope of the operation.
Fixes scylladb/scylladb#19061
Backport is not required, it is new functionality
=> rest_api: add endpoint which drops all quarantined sstables

test.py, test/conftest.py, test/cqlpy/run.py, test/pylib/cpp/boost/boost_facade.py, test/pylib/cpp/common_cpp_conftest.py, test/pylib/cpp/facade.py, test/pylib/cpp/item.py, test/pylib/cpp/unit/unit_facade.py, test/pylib/report_plugin.py
Previous way of execution repeat was to launch pytest for each repeat.
That was resource consuming, since each time pytest was doing discovery
of the tests. Now all repeats are done inside one pytest process.
Backport for 2025.3 is needed, since this functionality is framework only, and 2025.3 affected with this slow repeats as well.
=> test.py: native pytest repeats

test.py, test/cluster/conftest.py, test/cluster/test_sstable_compression_dictionaries_upgrade.py, test/pylib/manager_client.py, test/pylib/scylla_cluster.py, test/pylib/suite/python.py, test/pylib/suite/topology.py, tools/toolchain/dbuild
This PR adds an upgrade test for SSTable compression with shared dictionaries, and adds some bits to pylib and test.py to support that.
In the series, we:
1. Mount $XDG_CACHE_DIR into dbuild.
2. Add a pylib function which downloads and installs a released ScyllaDB package into a subdirectory of $XDG_CACHE_DIR/scylladb/test.py, and returns the path to bin/scylla.
3. Add new methods and params to the cluster manager, which let the test start nodes with historical Scylla executables, and switch executables during the test.
4. Add a test which uses the above to run an upgrade test between the released package and the current build.
5. Add --run-internet-dependent-tests to test.py which lets the user of test.py skip this test (and potentially other internet-dependent tests in the future).
(The …
=> [Backport 2025.2] test: introduce upgrade tests to test.py, add a SSTable dict compression upgrade test

alternator/executor.cc, alternator/executor.hh, db/config.cc, db/config.hh, docs/alternator/new-apis.md, test/alternator/run, test/alternator/test_cql_rbac.py, test/alternator/test_metrics.py, test/alternator/test_scan.py, test/alternator/test_system_tables.py, test/alternator/test_table.py, test/alternator/test_ttl.py, test/alternator/util.py, test/pylib/scylla_cluster.py
In commit 44a1daf we added the ability to read Scylla system tables with Alternator. This feature is useful, among other things, in tests that want to read Scylla's configuration through the system table system.config. But tests often want to modify system.config, e.g., to temporarily reduce some threshold to make tests shorter. Until now, this was not possible
This series add supports for writing to system tables through Alternator, and examples of tests using this capability (and utility functions to make it easy).
Because the ability to write to system tables may have non-obvious security consequences, it is turned off by default and needs to be enabled with a new configuration option "alternator_allow_system_table_write"
No backports are necessary - this feature is only intended for …
=> Alternator - add the ability to write, not just read, system tables

keys/clustering_bounds_comparator.hh, keys/keys.cc, keys/keys.hh, test/boost/managed_bytes_test.cc, utils/managed_bytes.hh
I noticed clustering_bounds_comparator was running an unnecessary
thread_local initialization guard. This series switches the variable
to constinit initialization, removing the guard.
Performance measurements (perf-simple-query) show an unimpressive
20 instruction per op reduction. However, each instruction counts!
Before:
```
throughput:
mean=   203642.54 standard-deviation=1102.99
median= 204328.69 median-absolute-deviation=955.56
maximum=204624.13 minimum=202222.19
instructions_per_op:
mean=   42097.59 standard-deviation=40.07
median= 42111.83 median-absolute-deviation=30.65
maximum=42139.88 minimum=42044.91
cpu_cycles_per_op:
mean=   22664.81 standard-deviation=131.28
median= 22581.10 median-absolute-deviation=111.57
maximum=22832.30 minimum=22553.24
```
After:
```
throughput:
mean= …
```
=> key: clustering_bounds_comparator: avoid thread_local initialization guard overhead

db/config.cc, service/vector_store_client.cc, service/vector_store_client.hh, test/boost/vector_store_client_test.cc
service/vector_store_client: Add live configuration update support
Enable runtime updates of vector_store_uri configuration without
requiring server restart.
This allows to dynamically enable, disable, or switch the vector search service endpoint on the fly.
To improve the clarity the seastar::experimental::http::client is now wrapped in a private http_client class that also holds the host, address, and port information.
Tests have been added to verify that the client correctly handles transitions between enabled/disabled states and successfully switches traffic to a new endpoint after a configuration update.
Closes: VECTOR-102
No backport is needed as this is a new feature.
=> service/vector_store_client: Add live configuration update support

test/boost/encryption_at_rest_test.cc, test/lib/tmpdir.cc, test/lib/tmpdir.hh
This PR extends the `tmpdir` class with an option to preserve the directory if the destructor is called during stack unwinding. It also uses this feature in KMIP tests, where the tmpdir contains PyKMIP server logs, which may be useful when diagnosing test failures.
Fixes #25339.
Not so important to be backported.
=> Preserve PyKMIP logs from failed KMIP tests

test/cluster/dtest/ccmlib/scylla_cluster.py, test/cluster/dtest/ccmlib/scylla_node.py, test/cluster/dtest/commitlog_test.py, test/cluster/dtest/tools/assertions.py, test/cluster/dtest/tools/data.py, test/cluster/dtest/tools/files.py, test/cluster/suite.yaml
Copy `commitlog_test.py` from scylla-dtest test suite and make it works with `test.py`
As a part of the porting process, remove unused imports and markers, remove non-next_gating tests and tests marked with `skip`, 'skip_if', and `xfail` markers.
test.py uses `commitlog` directory instead of dtest's `commitlogs`.
Also, add `commitlog_segment_size_in_mb: 32` option to test_stop_failure_policy to make _provoke_commitlog_failure
work.
Tests `test_total_space_limit_of_commitlog_with_large_limit` and `test_total_space_limit_of_commitlog_with_medium_limit` use too much disk space and have too big execution time.  Keep them in scylla-dtest for now.
Enable the test in `suite.yaml` (run in dev mode only.)
Additional modifications to test.py/dtest shim code:
- add ScyllaCluster.flush() method
- add …
=> test.py: dtest: port next_gating tests from commitlog_test.py

cdc/log.cc, cdc/log.hh, cql3/statements/alter_table_statement.cc, cql3/statements/describe_statement.cc, index/vector_index.cc, index/vector_index.hh, test/boost/cdc_test.cc, test/cql/vs_cdc_enable_disable_test.cql, test/cql/vs_cdc_enable_disable_test.result, test/cqlpy/cassandra_tests/vector_invalid_query_test.py, test/cqlpy/test_describe.py, test/cqlpy/test_invalid_ann_queries.py, test/cqlpy/test_vector_index.py
When a vector index is created in Scylla, it is initially built using a full scan of the database. After that, it stays up to date by tracking changes through CDC, which should be automatically enabled when the vector index is created.
When a user attempts to enable Vector Search (VS), the system checks whether Change Data Capture (CDC) is enabled and properly configured:
1. CDC is not enabled
- CDC is automatically enabled with the minimum required TTL (Time-to-Live) for VS (24 hours) and the delta mode set to 'full' or post-image is enabled.
- If the user later tries to reduce the CDC TTL below 24 hours or set delta mode to 'keys' with post-image disabled, the action fails.
- Error message: Clearly states that CDC TTL must be at least 24 hours and delta mode must be set to 'full' or …
=> cdc, vector_search: enable CDC when the index is created

repair/repair.cc, repair/repair.hh, repair/task_manager_module.hh
Currently, in repair_service::repair_tablets a shard that initiates
the repair keeps repair_tablet_metas of all tablets that have a replica
on this node (on any shard). This may lead to oversized allocations.
Modify tablet_repair_task_impl to repair only the tablets which replicas
are kept on this shard. Modify repair_service::repair_tablets to gather
repair_tablet_metas only on local shard. repair_tablets is invoked on
all shards.
Add a new legacy_tablet_repair_task_impl that covers tablet repair started with
async_repair. A user can use sequence number of this task to manage the repair
using storage_service API.
In a test that reproduced this, we have seen 11136 tablets and 5636096 bytes
allocation failure. If we had a node with 250 shards, 100 tablets each, we could
reach 12MB kept on …
=> [Backport 2025.2] repair: distribute tablet_repair_task_metas between shards

main.cc, service/qos/service_level_controller.cc, service/qos/service_level_controller.hh, test/cluster/auth_cluster/test_raft_service_levels.py, test/lib/cql_test_env.cc
Move management over effective service levels from `service_level_controller`
to a new dedicated type -- `auth_integration`.
Before these changes, it was possible for the service level controller to try
to access `auth::service` after it was deinitialized. For instance, it could
happen when reloading the cache. That HAS happened as described in the following
issue: scylladb/scylladb#24792.
Although the problem might have been mitigated or even resolved in
scylladb/scylladb@10214e13bdf44f82c2d6a53cdcf4d0ae288c838a, it's not clear
how the service will be used in the future. It's best to prevent similar bugs
than trying to fix them later on.
The logic responsible for preventing to access an uninitialized `auth::service`
was also either non-existent, complex, or non-sufficient.
To prevent …
=> service/qos: Modularize service level controller to avoid invalid access to auth::service

api/api.cc, api/api_init.hh, api/cache_service.cc, api/cache_service.hh, main.cc
These two "blocks" of endpoints have different URL prefixes, but work with the same "service", which is sharded<replica::database>. The latter block had already been fixed to carry the sharded<database>& around (#25467), now it's the "cache" turn. However, since these endpoints also work with the database, there's no need in dedicated top-level set/unset machinery (similarly, gossiper has two API set/unset blocks that come together, see #19425), it's enough to just set/unset them next to each other.
Ongoing http_context dependency cleanup, no need to backport
=> Move "cache" API endpoints registration closer to column_family ones 

cql3/statements/ks_prop_defs.cc, docs/cql/ddl.rst, test/cluster/suite.yaml, test/cluster/test_keyspace_rf.py, test/cqlpy/cassandra_tests/validation/operations/create_test.py, test/cqlpy/test_keyspace.py
When creating a new keyspace, replication factor must be stated.
For example:
`CREATE KEYSPACE ks WITH REPLICATION { 'class': 'NetworkTopologyStrategy', 'replication_factor': 3 };`
This patch changes it in the following way - if there is no
replication factor specified, use default replication factor.
Default replication factor is equal to the number of racks that
are not arbiter-only, i.e. racks that have at least one non-arbiter node.
The following syntax is now valid:
`CREATE KEYSPACE ks WITH REPLICATION { 'class': 'NetworkTopologyStrategy' };`
`CREATE KEYSPACE ks WITH REPLICATION { };`
Fixes #16028 
Backport is not needed. This is an enhancement for future releases.
=> cql3: add default replication factor to `create_keyspace_statement`

cql3/statements/select_statement.cc, test/cqlpy/test_permissions.py
Before the patch, user with CREATE access could create a table with CDC or alter the table enabling CDC, but could not query a SELECT on the CDC table they created.
It was due to the fact, the SELECT permission was checked on the CDC log, and later it's "parent" - the keyspace, but not the base table, on which the user had SELECT permission automatically granted on CREATE.
This patch matches the behavior of querying the CDC log to the one implemented for Materialized Views:
1. No new permissions are granted on CREATE.
2. When querying SELECT, the permissions on base table SELECT are checked.
Fixes: https://github.com/scylladb/scylladb/issues/19798
Fixes: VECTOR-151
=> Allow users to SELECT from CDC log tables they created.

repair/repair.cc, repair/repair.hh, repair/task_manager_module.hh
Currently, in repair_service::repair_tablets a shard that initiates
the repair keeps repair_tablet_metas of all tablets that have a replica
on this node (on any shard). This may lead to oversized allocations.
Modify tablet_repair_task_impl to repair only the tablets which replicas
are kept on this shard. Modify repair_service::repair_tablets to gather
repair_tablet_metas only on local shard. repair_tablets is invoked on
all shards.
Add a new legacy_tablet_repair_task_impl that covers tablet repair started with
async_repair. A user can use sequence number of this task to manage the repair
using storage_service API.
In a test that reproduced this, we have seen 11136 tablets and 5636096 bytes
allocation failure. If we had a node with 250 shards, 100 tablets each, we could
reach 12MB kept on …
=> [Backport 2025.1] repair: distribute tablet_repair_task_metas between shards

test/boost/nonwrapping_interval_test.cc, utils/interval.hh
Interval's copy and move constructors are full of branches since the two payload T:s are
optional and therefore have to be optionally-constructed. This can be eliminated for
trivially copyable types (like dht::token) by eliminating interval's user-defined special member
functions (constructors etc) in that special case.
In turn, this enables optimizations in the standard library (and our own containers) that
convert moves/copies of spans of such types into memcpy().
Minor optimization, not a candidate to backport.
=> interval: specialize for trivially copyable types

test.py, test/pylib/runner.py
Add another level of verbosity: quiet. 
Before this it was used as a default one, but it provides not enough information. 
These changes should be coupled with pytest-sugar plugin to have an intended information for each level.
Invoke the pytest as a module, instead of a separate process, to get access to the terminal to be able to it interactively.
Framework change only, so backporting in to 2025.3
Fixes: #25403
=> test.py: add different levels of verbosity for output

test/cluster/test_long_join.py
The test could trigger gossiper API calls before the API was properly registered, causing intermittent 404 errors. Previously the test waited for the "init - starting gossiper" log, but this appears before API registration completes.
Add explicit wait for gossiper API registration to ensure the endpoint is available before making requests, eliminating test flakiness.
Fixes: scylladb/scylladb#25582
No backport needed: Issue only observed in master so far.
=> test: fix race condition in test_long_join

locator/tablets.cc, locator/tablets.hh, mutation_writer/token_group_based_splitting_writer.cc, replica/table.cc, test/cluster/test_tablets2.py
Consider the following:
1) balancer emits split decision
2) split compaction starts
3) split decision is revoked
4) emits merge decision
5) completes merge, before compaction in step 2 finishes
After last step, split compaction initiated in step 2 can fail because it works with the global tablet map, rather than the map when the compaction started. With the global state changing under its feet, on merge, the mutation splitting writer will think it's going backwards since sibling tablets are merged.
This problem was also seen when running load-and-stream, where split initiated by the sstable writer failed, split completed, and the unsplit sstable is left in the table dir, causing problems in the restart.
To fix this, let's make split compaction always work with the state when it started, …
=> replica: Fix split compaction when tablet boundaries change

test/cluster/test_tablets_migration.py
The test started hitting #21779 recently. We deflake it in this commit
by disabling the tablet load balancing before dropping the keyspace at
the end of the test.
We still have to understand why the test started hitting #21779, so we
keep #25938 open.
Refs #25938
The test was flaky only on master, so no backport needed.
=> test: deflake test_restart_leaving_replica_during_cleanup

compaction/task_manager_module.cc, tasks/task_manager.cc
expected_total_workload methods of scrub compaction tasks create a vector of table_info based on table names. If any table was already dropped, then the exception is thrown. It leaves table_info in corrupted state and node crashes with `free(): invalid size`.
Return std::nullopt if an exception was thrown to indicate that total workload cannot be found.
Fixes: #25941.
No release branches affected
=> compaction: handle exception in expected_total_workload

cql3/statements/select_statement.cc, cql3/statements/select_statement.hh, index/secondary_index_manager.cc, index/secondary_index_manager.hh, test/cqlpy/test_secondary_index.py
This patch adds the possibility to track metrics
per secondary index. Currently, only a histogram
of query latencies is tracked, but more metrics
can be added in the future. To add a new metric,
it needs to be added to the index_metrics struct
in index/secondary_index_manager.hh and then
initialized in index/secondary_index_manager.cc
in the constructor of the index_metrics struct.
The metrics are created when the index is created
and removed when the index is dropped.
First lines of the new metric:
\# HELP scylla_index_query_latencies Index query latencies
\# TYPE scylla_index_query_latencies histogram
scylla_index_query_latencies_sum{idx="test_i_idx",ks="test"} 640
scylla_index_query_latencies_count{idx="test_i_idx",ks="test"} 1 …
=> index, metrics: add per-index metrics

db/view/view_building_worker.cc, db/view/view_building_worker.hh
The view building batch lives on shard0 but it might be doing
work on shard which owns the tablet replica.
Until now the batch data was accessed from multiple shards (shard0 and
where the batch was executed).
This patch fixes this by splitting tasks execution into:
- preparation which is always happening on shard0
- actual execution of the tasks on relevant shard, but all necessary
data is copied to the shard and batch object isn't accessed.
Fixes https://github.com/scylladb/scylladb/issues/25804
View building coordinator hasn't been released yet, so no backport needed.
=> db/view/view_building_worker: split batch's data preparation and execution

docs/operating-scylla/security/encryption-at-rest.rst
This PR introduces a major rewrite of the EaR document. The initial motivation for this PR was to fully cover all our supported key providers with working examples, and to add instructions for key rotation. However, many other improvements were made along the way.
Main changes in this PR:
* Add a high-level description for every key provider. Mention limitations.
* Better organize existing provider-specific instructions by placing them into clearly separated, tabbed sections.
* Add instructions for the replicated key provider. Mention explicitly that it cannot be used as default option for user or system encryption, and that it does not support key rotation.
* Add more examples for KMS and GCP to cover all credential types.
* Document missing configuration options.
* Add a new section for …
=> Improve Encryption at Rest documentation

idl/storage_service.idl.hh, service/storage_service.cc, service/storage_service.hh, service/topology_coordinator.cc, test/cluster/test_tablets.py
Currently, in repair_tablet we retrieve session_id from tablet
map (and throw if it isn't specified). In case of topology
coordinator failover, we may end up in a situation where a node
runs outdated repair, treating session of a different operation
as the repair's session:
- topology coordinator starts repair transition (A);
- topology coordinator sends tablet repair rpc to node1;
- topology coordinator is separated from the cluster;
- new topology coordinator is elected;
- new topology coordinator sees waiting repair request (A_2)
and executes it;
- new repair of the same tablet is requested (B);
- new topology coordinator starts repair transition (B);
- new topology coordinator sends tablet repair rpc to node2;
- node2 starts repair (B) as repair master;
- node1 starts repair (A), …
=> service: pass current session_id to repair rpc

compaction/compaction.cc, compaction/compaction_manager.cc, test/boost/sstable_compaction_test.cc
compaction/scrub: register sstables for compaction before validation
When `scrub --validate` runs, it collects all candidate sstables at the
start and validates them one by one in separate compaction tasks.
However, scrub in validate mode does not register these sstables for
compaction, which allows regular compaction to pick them up and
potentially compact them away before validation begins. This leads to
scrub failures because the sstables can no longer be found.
This patch fixes the issue by first disabling compaction, collecting the
sstables, and then registering them for compaction before starting
validation. This ensures that the enqueued sstables remain available for
the entire duration of the scrub validation task.
Fixes #23363
This reported scrub failure occurs on all versions …
=> compaction/scrub: register sstables for compaction before validation

db/row_cache.cc
Currently, during cache invaldation we check if we need to preempt
only after the partition gets invaldaited. This may lead to stalls
if we have a chain of filtered out partitions.
Check for preemption even if the partition does not get invaldated.
Refs: https://github.com/scylladb/scylladb/issues/9136.
Optimization; no backport
=> db: cache: consider preempting after each partition

CMakeLists.txt, configure.py, db/system_keyspace.cc, db/system_keyspace.hh, docs/features/workload-prioritization.rst, generic_server.cc, generic_server.hh, gms/feature_service.hh, service/client_state.hh, service/qos/raft_service_level_distributed_data_accessor.cc, service/qos/raft_service_level_distributed_data_accessor.hh, service/qos/service_level_controller.cc, service/qos/service_level_controller.hh, service/storage_service.cc, service/topology_coordinator.cc, service/topology_coordinator.hh, test/boost/auth_test.cc, test/boost/cql_query_test.cc, test/boost/database_test.cc, test/boost/generic_server_test.cc, test/cluster/auth_cluster/test_raft_service_levels.py, test/cluster/util.py, test/cqlpy/test_describe.py, test/cqlpy/test_service_levels.py, test/perf/perf_generic_server.cc, test/pylib/rest_client.py, transport/server.cc, transport/server.hh
This patch series:
- Increases the number of allowed scheduling groups to allow creation of `sl:driver`
- Implements `create_driver_service_level` that creates `sl:driver` with shares=200 if it wasn't already created
- Implements creation of `sl:driver` for new systems and tests in `raft_initialize_discovery_leader`
- Modifies `topology_coordinator` to use  create `sl:driver` after upgrades.
- Implements using `sl:driver` for new connections in `transport/server`
- Adds to `transport/server` recognition of driver's control connections and forcing them to keep using `sl:driver`.
- Adds tests to verify the new functionality
- Modifies existing tests to let them pass after `sl:driver` is added
- Modifies the documentation to contain new `sl:driver`
The changes were evaluated by a test with …
=> transport: service_level_controller: create and use `driver` service level

service/topology_coordinator.cc, test/cluster/test_view_building_coordinator.py
In multi DC setup, tablet load balancer might generate multiple migrations of the same tablet_id but only one is actually commited to the `system.tablets` table.
This PR moved abortion of view building tasks from the same start of the migration (`<no tablet transition> -> allow_write_both_read_old`) to the next step (`allow_write_both_read_old -> write_both_read_old`). This way, we'll abort only tasks for which the tablet migration was actually started.
The PR also includes a reproducer test.
Fixes scylladb/scylladb#25912
View building coordinator hasn't been released yet, so no backport is needed.
=> topology_coordinator: abort view building a bit later in case of tablet migration

service/migration_manager.cc, test/cqlpy/test_cdc.py
Fix an issue where executing a CREATE TABLE IF NOT EXISTS statement with
CDC enabled fails with an error if the table already exists. Instead,
the query should succeed and be a no-op.
This regression was introduced by commit https://github.com/scylladb/scylladb/commit/fed104805994f28e2c2a9a5cfb58c573d4251db4. Previously, when
executing the query, we would first check if the table exists in
do_prepare_new_column_families_announcement. If it did, we would throw
an already_exists_exception, which was handled correctly; otherwise, we
would continue and create the CDC table in the
before_create_column_families notification.
The order of operations was changed in https://github.com/scylladb/scylladb/commit/fed104805994f28e2c2a9a5cfb58c573d4251db4, causing the
regression. Now, we first create …
=> cdc: fix create table with cdc if not exists

test/alternator/conftest.py, test/alternator/test_gsi.py, test/alternator/test_health.py, test/alternator/test_number.py, test/alternator/test_tag.py, test/alternator/util.py
Issue #26079 noted that multiple Alternator tests are failing when run against DynamoDB. This pull request fixes many of them, in several small patches. In one case we need to avoid a DynamoDB bug that wasn't even the point of the original test (and we create a new test specifically for that DynamoDB bug). Another test exposed a real incompatibility with Alternator (#26103) but didn't need to be exposed in this specific test so again we split the test to one that passes, and another one that xfails on Alternator (not on DynamoDB). A bigger changed had to be done to the tags feature test - since August 2024, the TagResource operation became asynchronous which broke our tests, so we fix this.
Each of these changes are described in more detail in the individual patches.
Refs #26079. It …
=> test/alternator: multiple fixes for tests so they would pass on DynamoDB

db/view/view_building_worker.cc, db/view/view_building_worker.hh, main.cc
The background fibers of the view building worker are indirectly spawned by the main function, thus the fibers inherit the "main" scheduling group. The main scheduling group is not supposed to be used for regular work, only for initialization and deinitialization, so this is wrong.
Wrap the call to `start_backgroud_fibers()` with `with_scheduling_group` and use the streaming scheduling group. The view building worker already handles RPCs in the streaming scheduling group (which do most of the work; background fibers only do some maintenance), so this seems like a good fit.
No need to backport, view build coordinator is not a part of any release yet.
=> mv: run view building worker fibers in streaming group

service/tablet_allocator.cc, test/cluster/test_not_enough_token_owners.py, test/cluster/test_tablets.py, test/cluster/test_tablets2.py, test/perf/tablet_load_balancing.cc
Greatly improves performance of plan making, because we don't consider
candidates in other racks, most of which will fail to be selected due
to replication constraints (no rack overload). Also (but minor)
reduces the overhead of candidate evaluation, as we don't have to
evaluate rack load.
Enabled only for rf_rack_valid_keyspaces because such setups guarantee
that we will not need (because we must not) move tablets across racks,
and we don't need to execute the general algorithm for the whole DC.
Tested with perf-load-balancing, which performs a single scale-out
operation on a cluster which initially has 10 nodes 88 shards each, 2
racks, RF=2, 70 tables, 256 tablets per table. Scale out adds 6 new
nodes (same shard count). Time to reballance the cluster (plan making
only, sum of all …
=> tablets: scheduler: Balance racks separately when rf_rack_valid_keyspaces is true

streaming/stream_blob.cc, streaming/stream_blob.hh, streaming/stream_session.cc, test/cluster/test_view_building_coordinator.py
After https://github.com/scylladb/scylladb/pull/22034, staging status of sstables streamed
via file streaming was ignored and view updates were never generated.
This patch fixes it and now staging sstables are registered to
`view_building_worker`. Then, the worker create view building tasks
for those sstables, so the view building coordinator can schedule them
once the tablet migration is finished.
Fixes https://github.com/scylladb/scylla-enterprise/issues/4572
This fix affects only views on tablets, which are still experimental, so no backport needed.
=> streaming/stream_blob: generate view updates from staging sstables

test/boost/vector_store_client_test.cc, vector_search/dns.cc, vector_search/dns.hh, vector_search/vector_store_client.cc, vector_search/vector_store_client.hh
vector_store_client: Add support for multiple IPs in DNS responses
The DNS resolution logic now processes all IP addresses returned in a DNS
response, not just the primary one.
The client will iterate through the list of resolved IPs, attempting to
query the next one if a request fails. This improves high availability
by allowing the client to query other available nodes if one is down.
References: VECTOR-187
As this is a new feature no backport is needed.
=> vector_store_client: Add support for multiple IPs in DNS responses

test/cluster/dtest/commitlog_test.py, test/cluster/dtest/tools/files.py
The commitlog in the tests with big mutations were corrupted by overwriting 10 chunks of 1KB with random data, which could not be enough due to randomness and the big size of the commitlog (~65MB).
- change `corrupt_file` to overwrite a based on a percentage of the file's size instead of fixed number of chunks
- fix typos
- cleanup comments for clarity
Closes: #25627
=> test: fix test_one_big_mutation_corrupted_on_startup

api/column_family.cc, api/raft.cc, api/storage_service.cc, api/task_manager.cc, api/task_manager_test.cc, test/boost/aws_error_injection_test.cc, test/boost/encryption_at_rest_test.cc, test/pylib/s3_server_mock.py, tools/scylla-nodetool.cc, utils/s3/client.cc, utils/s3/credentials_providers/sts_assume_role_credentials_provider.cc
Acecssing this member directly is deprecated, migrate code to use {get,set}_query_param() and friends instead.
Fixes: https://github.com/scylladb/scylladb/issues/26023
Preparation for seastar update, no backport required.
=> treewide: move away from accessing httpd::request::query_parameters

alternator/executor.cc, docs/alternator/new-apis.md, test/alternator/test_metrics.py, test/alternator/test_streams.py, test/alternator/test_tablets.py, test/cqlpy/test_permissions.py
update all the references about the issue of tablets support for
alternator streams to issue https://github.com/scylladb/scylladb/issues/23838 instead of https://github.com/scylladb/scylladb/issues/16317.
The issue https://github.com/scylladb/scylladb/issues/16317 is about support of CDC with tablets, but it is now
closed and it didn't address alternator streams. the remaining issues
about alternator streams should be addressed as part of https://github.com/scylladb/scylladb/issues/23838, so fix
the references in order for them not to be missed.
backport is not needed
=> alternator: update references to alternator streams issue

sstables/storage.cc
Shorter and cleaner this way. The method is doing parallel_for_each(some_lambda) and the PR only touches the lambda, the outer invocation is probably not worth it to convert plain return into a co_await
Coroutinization enhancement, no need to backport
=> Coroutinize filesystem_storage::check_create_links_replay()

configure.py
Any user provided linker flags are converted to a semicolon separated
string by the `configure.py` script and then passed to cmake via the
`CMAKE_EXE_LINKER_FLAGS` option. But `CMAKE_EXE_LINKER_FLAGS` expects
semicolon separated values only when set from within CMakeLists. When
the option is set from the shell, which is the case with `configure.py`
executing cmake, the values should be separated by space. So, pass the
flags as it is instead of separating them with semicolons.
`configure.py` also incorrectly concatenates the user linker flags and
internal linker flags without a space in between causing flags like
'-gz' and '-fuse-ld=lld' to merge into a single invalid argument. Fix
that by using a proper space when concatenating these two flags.
Fixes #26232
Fix to a dev build option. …
=> configure.py: fix passing of user linker flags to cmake

sstables/sstables.cc, sstables/types.hh, test/boost/schema_loader_test.cc, test/lib/random_schema.hh, tools/schema_loader.cc, tools/scylla-sstable.cc
Sstables store a basic schema in the statistics component. The scylla-sstable tool uses this to be able to read and dump sstables in a self-contained manner, without requiring an external schema source.
The problem is that the schema stored int he statistics component is incomplete: it doesn't store column names for key columns, so these have placeholder names in dump outputs where column names are visible.
This is not a disaster but it is confusing and it can cause errors in scripts which want to check the content of sstables, while also knowing the schema and expecting the proper names for key columns.
To make sstables truly self-contained w.r.t. the schema, add a complete schema to the scylla component. This schema contains the names and types of all columns, as well as some basic …
=> sstable: add more complete schema to scylla component

replica/database.hh, replica/table.cc, test/boost/mutation_test.cc
This method was once implemented by calling table::for_all_partitions(), which was supposed to be non-slow version. Then callers of "non-slow" method were updated and the method itself was renamed into "_slow()" one. Nowadays only one test still uses it.
At the same time the method itself mostly consists of a boilerplate code that moves bits around to call lambda on the partitions read from reader. Open-coding the method into the calling test results in much shorter and simpler to follow code.
Code cleanup, no backport needed
=> Remove table::for_all_partitions_slow()

locator/tablets.cc, replica/database.cc, service/storage_proxy.cc, service/tablet_allocator.cc, test/boost/tablets_test.cc, test/cluster/test_tablets_lwt.py, test/lib/cql_test_env.cc
`SELECT` commands with SERIAL consistency level are historically allowed for vnode-based views, even though they don't provide linearizability guarantees and in general don't make much sense. In this PR we prohibit LWTs for tablet-based views, but preserve old behavior for vnode-based views for compatibility. Similar logic is applied to CDC log tables.
We also add a general check that disallows colocating a table with another colocated table, since this is not needed for now.
Fixes https://github.com/scylladb/scylladb/issues/26258
backports: not needed (a new feature)
=> lwt: prohibit for tablet-based views and cdc logs

api/api-doc/storage_service.json, api/storage_service.cc, docs/operating-scylla/nodetool-commands/getendpoints.rst, keys/keys.cc, keys/keys.hh, service/storage_service.cc, service/storage_service.hh, test/nodetool/rest_api_mock.py, test/nodetool/test_getendpoints.py, test/rest_api/conftest.py, test/rest_api/test_storage_service.py, tools/scylla-nodetool.cc
Before, the `nodetool getendpoints` expected the key as one string separated by : (for example 1:val:ue). This caused errors if any part of the key had a colon because it was unclear whether a colon was a separator or part of the key.
This change adds a new API endpoint, `/storage_service/natural_endpoints/v2/{keyspace}`, which accepts composite partition keys as multiple key_component query parameters (e.g., ?key_component=1&key_component=val:ue). The `nodetool getendpoints` command was updated to support a new `--key-components` option, allowing users to pass key components as an array. The client and test infrastructure were extended to support multiple values for a query parameter, and tests were added to verify correct behavior with composite keys.
The previous method of passing …
=> Fix getendpoints command for compound keys containing ':'

sstables/sstable_directory.cc, test/boost/database_test.cc, test/lib/cql_test_env.hh
TemporaryHashes.db is a temporary sstable component used during ms
sstable writes. It's different from other sstable components in that
it's not included in the TOC. Because of this, it has a special case in
the logic that deletes unfinished sstables on boot.
(After Scylla dies in the middle of a sstable write).
But there's a bug in that special case,
which causes Scylla to forget to delete other components from the same unfinished sstable.
The code intends only to delete the TemporaryHashes.db file from the
`_state->generations_found` multimap, but it accidentally also deletes
the file's sibling components from the multimap. Fix that.
Also, extend a related test so that it would catch the problem before the fix. 
Fixes scylladb/scylladb#26393
Bugfix, needs backport to 2025.4.
=> sstables/sstable_directory: don't forget to delete other components when deleting TemporaryHashes.db
