scylladb/scylladb

db/view/build_progress_virtual_reader.hh
Build progress virtual reader uses Scylla-specific
scylla_views_builds_in_progress table in order to represent
legacy views_builds_in_progress rows. The Scylla-specific table contains
additional cpu_id clustering key part, which is trimmed before returning
it to the user. That may cause duplicated clustering row fragments to be
emitted by the reader, which may cause undefined behaviour in consumers.
The solution is to keep track of previous clustering keys for each
partition and drop fragments that would cause duplication. That way if
any shard is still building a view, its progress will be returned,
and if many shards are still building, the returned value will indicate
the progress of a single arbitrary shard.
Fixes #4524
Tests:
unit(dev) + custom monotonicity checks from …
=> view: ignore duplicated key entries in progress virtual reader

db/view/build_progress_virtual_reader.hh
Reverts scylladb/scylla#4534
Should be merged into next first
=> Revert "view: ignore duplicated key entries in progress virtual reader"

api/column_family.hh, dht/i_partitioner.hh, xx_hasher.hh
These patches fix remaining issues with gcc9 build, that involve a gcc9 bug, a gcc9 bug, and a stricter warning.
Tests: unit(debug, dev, release).
=> Fix gcc9 build

main.cc, supervisor.cc
Increase visibility of startup and shutdown messages.
Ref #4384
=> Init and shutdown logging

docs/review-checklist.md
- code style
- naming
- micro-performance
- concurrency
- unit-testing
- templates and type erasure
- singletons
=> review-checklist.md: add common checks

transport/server.cc
If someone opens a connection to port 9042 and sends some random bytes,
there is a 1 in 64 probability we'll recognize it as a valid frame
(since we only check the version byte, allowing versions 1-4) and we'll
try to read frame.length bytes for the body. If this value is very large,
we'll run out of memory very quickly.
Fix this by checking for reasonable body size (100kB). The initial message
must be a STARTUP, whose body is a [string map] of options, of which just
three are recognized. 100kB is plenty for future expansion.
Note that this does not replace true security on listening ports and
only serves to protect against mistakes, not attacks. An attacker can
easily exhaust server memory by opening many connections and trickle-feeding
them small amounts of data so they appear alive. …
=> transport: reject initial frames with wild body xssizes

tests/mutation_test.cc
row is one of a central objects in the Scylla data model. This patch
improve its test coverage by adding a test case that verifies apply()
and difference() in case of multi-column schema and multiple different
orders of apply() operation.
=> tests/mutation: add test for operations on rows

utils/logalloc.cc
In debug mode the LSA needs objects to be 8-byte aligned in order to
maximise coverage from the AddressSanitizer.
Usually `close_active()` creates a dummy objects that covers the end of
the segment being closed. However, it the last real objects ends in the
last eight bytes of the segment then that dummy won't be created because
of the alignment requirements. This broke exit conditions on loops
trying to read all objects in the segment and caused them to attempt to
dereference address at the end of the segment. This patch fixes that.
Fixes #4653.
=> lsa: make sure align_up_for_asan() doesn't cause reads past end of segment

main.cc
=> Fix command line parsing and add logging.

test.py
If the user specifies an output file name using "--xunit=<filename>",
test.py will write the test results of non-boost tests to the file in the XUnit XML format.
Every boost test creates its own results file already.
Resolves #4680.
=> Add option to create a XUnit output file for non-boost tests in test.py.

sstables/index_reader.hh
If we had an error while reading, then we would have failed to close
the reader, which in turn can cause memory corruption. Make the
closing more robust by using then_wrapped (that doesn't skip on
exception) and log the error for analysis.
Fixes #4761.
=> sstable: index_reader: close index_reader::reader more robustly

configure.py
Currently, seastar is built in seastar/build/{mode}. This means we have two build
directories: build/{mode} and seastar/build/{mode}.
This patch changes that to have only a single build directory (build/{mode}). It
does that by calling Seastar's cmake directly instead of through Seastar's
./configure.py.  However, to support dpdk, if that is enabled it calls cmake
through Seastar's ./cooking.sh (similar to what Seastar's ./configure.py does).
All ./configure.py flags are translated to cmake variables, in the same way that
Seastar does.
Tests: unit (dev), build with and without dpdk, peek at compiler flags while the
compiler is running.
=> build: build seastar in build directory

cql3/restrictions/single_column_restriction.hh, cql3/restrictions/statement_restrictions.cc, tests/cql_query_test.cc
Currently we create a regex from the LIKE pattern for every row
considered during filtering, even though the pattern is always the
same.  This is wasteful, especially since we require costly
optimization in the regex compiler.  Fix it by reusing the regex
whenever the pattern is unchanged since the last call.
=> cql3: Optimize LIKE regex construction

service/storage_service.cc
Make the sleep abortable so that it is able to break the loop during
shutdown.
=> storage_service: Use sleep_abortable instead of sleep

main.cc
Shutdown routines are usually implemented via the deferred_action
mechanism, which runs a function in its destructor. We thus expect
the function to be noexcept, but unfortunately it's not always
the case. Throwing in the destructor results in terminating the program
anyway, but before we do that, the exception can be logged so it's
easier to investigate and pinpoint the issue.
Tested manually by injecting an error into `view_builder::stop()`.
Example output before the patch:
INFO  2019-09-10 12:49:05,858 [shard 0] view - Stopping view builder
terminate called without an active exception
Aborting on shard 0.
Backtrace:
0x000000000184a9ad
(...)
Example output after the patch:
INFO  2019-09-10 12:49:05,858 [shard 0] view - Stopping view builder
ERROR 2019-09-10 12:49:05,858 [shard 0] init - …
=> main: log unexpected errors thrown on shutdown

tests/castas_fcts_test.cc, types.cc
This is the second version of the patch series. The previous one was just the second patch, this one adds more tests an another patch to make it easier to test that the new code has the same behavior as  the old one.
=> Simplify and explain from_varint_to_integer

tests/mutation_diff
* accept diff_command option
* standard input support
=> Mutation diff improvements

cql3/selection/selection.cc, cql3/selection/selection.hh, tests/filtering_test.cc
An otherwise empty partition can still have a valid static column.
Filtering didn't take that fact into account and only filtered
full-fledged rows, which may result in non-matching rows being returned
to the client.
Fixes #5248 
@nyh @avikivity @eliransin
=> Fix filtering static columns on empty partitions

docs/backport.md
This document adds information about how fixes are tracked to be
backported into releases and what is the procedure that is followed to
backport those fixes.
Signed-off-by: Shlomi Livne <shlomi@scylladb.com>
=> Document backport queue and procedure

cql3/query_processor.cc, cql3/statements/batch_statement.cc, cql3/statements/modification_statement.cc, cql3/statements/modification_statement.hh, cql3/statements/select_statement.cc, cql3/statements/select_statement.hh, cql3/statements/statement_type.hh, cql3/statements/truncate_statement.hh, cql3/statements/update_statement.cc, cql3/statements/update_statement.hh, cql3/stats.hh
Welcome to my first PR to Scylla!
The task was intended as a warm-up ("noob") exercise; its description is here: https://github.com/scylladb/scylla/issues/4182
Sorry, I also couldn't help it and did some scouting: edited descriptions of some metrics and shortened few annoyingly long LoC.
=> Added separate counters for accesses to system tables

repair/row_level.cc
In get_full_row_hashes_with_rpc_stream and
repair_get_row_diff_with_rpc_stream_process_op which were introduced in
the "Repair switch to rpc stream" series, rx_hashes_nr metrics are not
updated correctly.
Tests: repair_additional_test.py:RepairAdditionalTest.repair_almost_synced_3nodes_test
In the test we have 3 nodes and run repair on node3, we makes sure the
following metrics are correct.
```
assertEqual(node1_metrics['scylla_repair_tx_hashes_nr'] + node2_metrics['scylla_repair_tx_hashes_nr'],
node3_metrics['scylla_repair_rx_hashes_nr'])
assertEqual(node1_metrics['scylla_repair_rx_hashes_nr'] + node2_metrics['scylla_repair_rx_hashes_nr'],
node3_metrics['scylla_repair_tx_hashes_nr'])
assertEqual(node1_metrics['scylla_repair_tx_row_nr'] + node2_metrics['scylla_repair_tx_row_nr'], …
```
=> repair: Fix rx_hashes_nr metrics

alternator-test/test_expected.py, alternator/conditions.cc, lua.cc, utils/big_decimal.hh
Tests: pytest in alternator-test
=> alternator: Implement Expected operators LE, GE, and BETWEEN

cql3/functions/aggregate_fcts.hh, cql3/functions/functions.cc, tests/cql_query_test.cc
Previously, scylla used `min/max(blob)->blob` overload for collections, tuples and UDTs; effectively making the results being printed as blobs. This PR adds "dynamically"-typed `min()`/`max()` functions for compound types.
These types can be complicated, like `map<int,set<tuple<...`, and created in runtime, so functions for them are created on-demand, similarly to `tojson()`. The comparison remains unchanged - underneath this is still byte-by-byte weak lex ordering.
Fixes #5139
=> cql3: min/max() on collections returns human-readable result

dist/ami/build_ami.sh
If build_rpms was run manually and rpms were built
but not copied to dist/ami/files then copy them
before checking if any rpm is missing.
=> dist/ami/build_ami.sh: support incremental build of rpms

db/schema_tables.cc
schema_tables: notify table deletions before creations
If a set of mutations contains both an entry that deletes a table
and an entry that adds a table with the same name, it's expected
to be a replacement operation (delete old + create new),
rather than a useless "try to create a table even though it exists
already and then immediately delete the original one" operation.
As such, notifications about the deletions should be performed
before notifications about the creations. The place that originally
suffered from this wrong order is view building - which in this case
created an incorrect duplicated entry in the view building bookkeeping,
and then immediately deleted it, resulting in having old, deprecated
entries with stale UUIDS lying in the build queue and never proceeding,
because the …
=> schema_tables: notify table deletions before creations

reloc/build_rpm.sh
Fixed a case sensitive variable.
Adding a log print, to enable understanding what is going on (hard to debug like this).
I need this in order to build debug RPM's https://github.com/scylladb/scylla-pkg/issues/698
=> Fix case sensitive variable name

dist/common/scripts/scylla_util.py
CLI tool path is hardcorded, need to specify correct path on nonroot.
=> nonroot: fix CLI tool path for nonroot

test/boost/extensions_test.cc
Test for CDC schema extension added in #5720 and already merged.
Refs #5589
=> tests: test cdc schema extension

service/storage_service.cc
This is a bug: we tried to retrieve the CDC streams timestamp even if
CDC flag was not enabled in storage_service::start_gossiping.
Fixes https://github.com/scylladb/scylla/issues/5772.
=> storage_service: check for CDC flag in start_gossiping

dist/redhat/scylla.spec.mustache
=> dist/redhat: scylla.spec.mustache: set _no_recompute_build_ids

atomic_cell.cc
Counter cell can represent two things: "delta" (counter update)
and "shards" (counter value). Both are contained in the same
type, but there are differences: e.g. calling `counter_update_value()`
on "shards" cell is a memory corruption. Similarly, call to `value()`
on "delta" cell leads to `abort()` - that's what happens in 
`operator<<(..., atomic_cell_view::printer&)`.
This commit introduces a quickfix: it determines cell type on high
level (from `atomic_cell_view`) and prints counter contents by
`counter_cell_view` or `atomic_cell_view::counter_update_value()`.
Fixes #5616
=> atomic_cell: fix printing counter cells

cdc/log.cc, test/boost/cdc_test.cc
Currently, writes to a static row in a base table are not reflected at all in the corresponding cdc log. This patch causes such writes to be properly logged.
Fixes: #5744
=> cdc: log static rows correctly

configure.py, redis/command_factory.cc, redis/commands.cc, redis/commands.hh, redis/lolwut.cc, redis/lolwut.hh, redis/version.hh
Add lolwut command that shows redis version and ascii art.
see: https://redis.io/commands/lolwut
=> redis: add lolwut command

repair/repair.cc, repair/row_level.cc
repair: Ignore keyspace that is removed in sync_data_using_repair
When a keyspace is removed during node operations, we should not fail
the whole operation. Ignore the keyspace that is removed.
Fixes #5942
=> repair: Ignore keyspace that is removed in sync_data_using_repair

cql3/statements/select_statement.cc, test/boost/secondary_index_test.cc
An empty partition/clustering key pair is a valid state of the 
query paging state. Unfortunately, recent attempts at debugging
a flaky test (#5856) resulted in introducing an assertion (7616290)
which breaks when trying to generate a key from such a pair.
In order to keep the assertion (since it still makes sense in its 
scope), but at the same time translate empty keys properly,
empty keys are now explicitly processed at the beginning of the 
function.
This behaviour was 100% reproducible in a secondary index dtest below.
Fixes #6134
Refs #5856
Tests: unit(dev),
dtest(TestSecondaryIndexes.test_truncate_base)
=> Fix generating base keys from empty indexing paging state

redis-test/test_strings.py, redis/command_factory.cc, redis/commands.cc, redis/commands.hh, redis/query_utils.cc, redis/query_utils.hh
Enabling TTL feature, add setex and ttl commands to use it.
=> redis: add setex and ttl commands

redis-test/test_strings.py, redis/lolwut.cc
Add test for lolwut command, and also fix a bug on lolwut found by the test.
=> redis: add lolwut test

dist/offline_installer/debian/build_offline_installer.sh
Added Ubuntu 18.04 and Debian 9/10.
=> dist/offline_installer/debian: support latest distributions

scripts/create-relocatable-package-python3.py
Recently ./reloc/build_deb.sh started failing with
dpkg-source: info: using source format '1.0'
dpkg-source: info: building scylla-python3 using existing scylla-python3_3.8.3-0.20200604.77dfa4f15.orig.tar.gz
dpkg-source: info: building scylla-python3 in scylla-python3_3.8.3-0.20200604.77dfa4f15-1.diff.gz
dpkg-source: error: cannot represent change to scylla-python3/lib64/python3.8/site-packages/urllib3/packages/backports/__pycache__/__init__.cpython-38.pyc:
dpkg-source: error:   new version is plain file
dpkg-source: error:   old version is symlink to /usr/lib/python3.8/site-packages/__pycache__/six.cpython-38.pyc
dpkg-source: error: unrepresentable changes to source
dpkg-buildpackage: error: dpkg-source -b . subprocess returned exit status 1
debuild: fatal error at line 1182:
Those files …
=> build: drop __pycache__ directories from python3 relocatable package

dist/common/scripts/scylla_util.py
Sync enhanced networking supported instance list to latest one.
Reference: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html
Fixes #6540
=> aws: update enhanced networking supported instance list

streaming/stream_transfer_task.cc
Current sender sends stream_mutation_fragments_cmd::end_of_stream to
receiver when an error is receiver from peer node. To be safe, send
stream_mutation_fragments_cmd::error instead of
stream_mutation_fragments_cmd::end_of_stream to prevent end_of_stream to
be written into the sstable when a partition is not closed yet.
In addition, check if partition_start and partition_end emitted from
reader are paried when the reader is done. If not, fail the stream
session and send stream_mutation_fragments_cmd::error instead of
stream_mutation_fragments_cmd::end_of_stream to isolate the problematic
sstables on the sender node.
Refs: #6478
=> streaming: Do not send end of stream in case of error

service/storage_service.cc
A lot is going on when calculating effective ownership.
For each node in the cluster, we need to go over all the ranges belong
to that node and see if that node is the owner or not.
This patch uses futurized loops with do_for_each so it would preempt if
needed.
The patch replaces the current for-loops with do_for_each and do_with
but does not replace the logic.
Fixes #6380
=> service/storage_service.cc: Make effective_ownership preemptable

dist/common/scripts/scylla_setup, dist/common/scripts/scylla_swap_setup, dist/common/scripts/scylla_util.py
Adding swapfile setup on scylla_setup.
Fixes #6539
=> scylla_setup: add swapfile setup

repair/repair.cc
In decommission operation, current code requires a node in local dc to
sync data with. This requirement is too strong for a non network topology
strategy. For example, consider:
```
n1 dc1
n2 dc1
n3 dc2
```
n2 runs decommission operation. For a keyspace with simple strategy and
RF = 2, it is possible n3 is the new owner but n3 is not in the same dc
as n2.
To fix, perform the dc check only for the network topology strategy.
Fixes #6564
=> repair: Relax node selection in decommission for non network topology strategy

README.md
The word "offers" was inadvertently repeated in a sentence.
Signed-off-by: Dejan Mircevski <github@mircevski.com>
=> README.md: dedupe "offers offers"

dist/common/scripts/scylla_setup
=> Scylla setup fix raid prompt issues

dht/boot_strapper.cc
After commit 7d86a3b208659e92489216e71df13fb33b1a4c3a (storage_service:
Make replacing node take writes), during replace operation, tokens in
_token_metadata for node being replaced are updated only after the replace
operation is finished. As a result, in range_streamer::add_ranges, the
node being replaced will be considered as a source to stream data from.
Before commit 7d86a3b208659e92489216e71df13fb33b1a4c3a, the node being
replaced will not be considered as a source node because it is already
replaced by the replacing node before the replace operation is finished.
This is the reason why it works in the past.
To fix, filter out the node being replaced as a source node explicitly.
Tests: replace_first_boot_test and replace_stopped_node_test
Backports: 4.1
Fixes: #6728
=> boot_strapper: Ignore node to be replaced explicitly as stream source

dist/docker/redhat/Dockerfile
Set SCYLLA_REPO and VERSION values for scylla-4.2
=> dist/docker/redhat/Dockerfile: update 4.2 params

reloc/python3/build_rpm.sh
=> python3: fix incorrect variable name

cql3/functions/aggregate_fcts.cc, test/boost/aggregate_fcts_test.cc
For collections and UDTs the `MIN()` and `MAX()` functions are
generated on the fly. Until now they worked by comparing just the
byte representations of their arguments.
This patch employs specific per-type comparators to provide semantically
sensible, dynamically created aggregates.
Fixes #6768
=> aggregates: Use type-specific comparators in min/max

configure.py, unified/build_unified.sh, unified/install.sh
This introduce unified relocatable package, a single tarball to install
all Scylla packages.
Fixes #6626
See scylladb/scylla-pkg#1218
=> reloc: support unified relocatable package

dist/common/scripts/scylla_io_setup, dist/common/scripts/scylla_util.py
not recommended setups will still run iotune
fixes #6631
=> add out of box configs for GCP VMs with nvmes

configure.py, dist/debian/control.template, dist/debian/python3/control.template
Allow users to build unofficial packages for non-x86 platform.
=> Support building packages on non-x86 platform

repair/row_level.cc, scylla-gdb.py
This series adds scylla repairs command to help debug repair.
Fixes #7103
=> scylla-gdb.py: Add scylla repairs command

unified/build_unified.sh, unified/install.sh, unified/uninstall.sh
Provide an uninstaller for offline & nonroot installation.
Fixes #7076
=> unified: add uninstall.sh

repair/repair.cc
This series follows "repair: Add progress metrics for node ops #6842" and adds the metrics for the remaining node operations, i.e., replace, decommission and removenode. 
Fixes #1244, #6733
=> repair: Add  progress metrics for replace decommission removenode

dist/common/scripts/scylla_cpuscaling_setup
Install section requires for enable/disable services.
Fixes #7230
=> scylla_cpuscaling_setup: add Install section for scylla-cpupower.service

gms/gossiper.cc, gms/gossiper.hh, message/messaging_service.cc
This series improves gossip echo message handling in a loaded cluster. 
Refs: #7197
=> Gossip echo message improvement

service/misc_services.cc
The blacklog of current and max in VIEW_BACKLOG is not update but the
nodes are updating VIEW_BACKLOG all the time. For example:
```
INFO  2020-03-06 17:13:46,761 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.3, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486026590,718)
INFO  2020-03-06 17:13:46,821 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.2, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486026531,742)
INFO  2020-03-06 17:13:47,765 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.3, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486027590,721)
INFO  2020-03-06 17:13:47,825 [shard 0] storage_service - Update system.peers table: …
```
=> gossip: Reduce unncessary VIEW_BACKLOG updates

utils/histogram.hh
When computing moving average rates too early after startup, the
rate can be infinite, this is simply because the sample interval
since the system started is too small to generate meaningful results.
Here we check for this situation and keep the rate at 0 if it happens
to signal that there are still no meaningful results.
This incident is unlikely to happen since it can happen only during a
very small time window after restart, so we add a hint to the compiler
to optimize for that in order to have a minimum impact on the normal
usecase.
Fixes #4469
=> moving avarage rate: Keep computed rates in zero until they are meaningful

db/commitlog/commitlog.cc, test/boost/commitlog_test.cc
Refs #7794
Iff we need to pre-fill segment file ni O_DSYNC mode, we should
drop this for the pre-fill, to avoid issuing flushes until the file
is filled. Done by temporarily closing, re-opening in "normal" mode,
filling, then re-opening.
=> commitlog: Make pre-allocation drop O_DSYNC while pre-filling

database.cc, db/schema_tables.cc, db/schema_tables.hh, schema.cc, schema_registry.cc, schema_registry.hh, service/storage_proxy.hh
This is a backport of the fix for #7709 to 4.3 version.
=> Fix inconsistent mv si backport to 4.3

configure.py, docs/guides/building.md, scripts/build-help.sh
This pull request adds a "ninja help" build target in hopes of making
the different build targets more discoverable to developers.
=> Add a ninja help build target

scylla-gdb.py, test.py, test/scylla-gdb/run, test/scylla-gdb/suite.yaml, test/scylla-gdb/test.py, test/unit/suite.yaml
rebased on next, fixed mode list conflict
=> scylla-gdb unit test

streaming/consumer.cc
Currently, if e.g. find_column_family throws an error,
as seen in #8776 when the table was dropped during repair,
the reader is not closed.
Use a coroutine to simplify error handling and
close the reader if an exception is caught.
Also, catch an error inside the lambda passed to make_interposer_consumer
when making the shared_sstable for streaming, and close the reader
their and return an exceptional future early, since
the reader will not be moved to sst->write_components, that assumes
ownership over it and closes it in all cases.
Fixes #8776
DTest: repair_additional_test.py:RepairAdditionalTest.repair_while_table_is_dropped_test (dev, debug) w/ https://github.com/scylladb/scylla/pull/8635#issuecomment-856661138
=> streaming: make_streaming_consumer: close reader on errors

cql3/statements/select_statement.cc
Increase readability in preparation for managing topology with
effective_replication_map (continuing 69aea59d9).
=> cql3: select_statement: coroutinize indexed_table_select_statement::do_execute_base_query()

test/lib/sstable_utils.hh
Changes done to avoid pitfalls and fix issues of sstable-related unit tests
=> Improvements to test/lib/sstable_utils.hh

dirty_memory_manager.cc, dirty_memory_manager.hh
A collection of small cleanups, and a bug fix.
=> dirty_memory_manager: tidy up

db/system_keyspace.cc, db/system_keyspace.hh, idl/partition_checksum.idl.hh, idl/uuid.idl.hh, main.cc, repair/repair.cc, repair/repair.hh, repair/repair_task.hh, repair/row_level.cc, repair/row_level.hh, types.hh
The PR prepares repair for task manager integration:
- Creates repair_module
- Keeps repair_module in repair_service
- Moves tracker methods to repair_module
- Changes UUID to task_id in repair module
=> Prepare repair for task manager integration

test/boost/sstable_directory_test.cc
The helper is already widely used, one (last) test case can benefit from using it too
=> Use with_sstable_directory() helper in tests

docs/cql/functions.rst
This PR is V2 of the[ PR created by @psarna.](https://github.com/scylladb/scylladb/pull/11560).
I have:
- copied the content.
- applied the suggestions left by @nyh.
- made minor improvements, such as replacing "Scylla" with "ScyllaDB", fixing punctuation, and fixing the RST syntax.
Fixes https://github.com/scylladb/scylladb/issues/11378
=> doc: document user defined functions (UDFs)

db/view/view.cc
=> view: coroutinize maybe_mark_view_as_built

compaction/compaction_manager.cc, compaction/compaction_manager.hh
Three lambdas were removed, simplifying the code.
=> compaction_manager: coroutinize postponed_compactions_reevaluation

replica/table.cc
Extracted from https://github.com/scylladb/scylladb/pull/12139
=> Coroutinize some table functions in preparation to static compaction groups

docs/operating-scylla/system-configuration/snitch.rst
Fixes https://github.com/scylladb/scylladb/issues/11712
Updates added with this PR:
- Added a new section with the description of AzureSnitch (similar to others + examples and language improvements).
- Fixed the headings so that they render properly.
- Replaced "Scylla" with "ScyllaDB".
=> doc: add the description of AzureSnitch to the documentation

repair/row_level.cc
Simplify a somewhat complicated function.
=> repair: coroutinize to_repair_rows_list

test.py
Fix a bug in failure handling and log level.
=> test.py: fix cql failure handling

repair/repair.cc, tasks/task_manager.hh
In most cases, tasks manager's tasks are started just after they are
created. Thus, to reduce boilerplate required for creating and starting
tasks, tasks::task_manager::module::make_and_start_task method is added.
Repair tasks are modified to use the method where possible.
=> Method to create and start task manager task

configure.py, service/raft/raft_group_registry.cc, service/raft/raft_group_registry.hh, test/boost/recent_entries_map_test.cc, utils/recent_entries_map.hh
Fixes: https://github.com/scylladb/scylladb/issues/12309
=> Introduce recent_entries_map datatype to track least recent visited entries.

test.py, test/cql-pytest/run.py, test/lib/cql_test_env.cc, test/pylib/host_registry.py, test/pylib/pool.py, test/pylib/rest_client.py, test/pylib/scylla_cluster.py
Backport the following improvements for test.py efficiency and user experience:
- https://github.com/scylladb/scylladb/pull/12542
- https://github.com/scylladb/scylladb/pull/12560
- https://github.com/scylladb/scylladb/pull/12564
- https://github.com/scylladb/scylladb/pull/12563
- https://github.com/scylladb/scylladb/pull/12588
- https://github.com/scylladb/scylladb/pull/12613
- https://github.com/scylladb/scylladb/pull/12569
- https://github.com/scylladb/scylladb/pull/12612
- https://github.com/scylladb/scylladb/pull/12549
- https://github.com/scylladb/scylladb/pull/12678
Fixes #12617
=> Backport test.py improvements to 5.2

utils/UUID.hh
- utils: UUID: define operator<=> for UUID
- utils: UUID: define operator==() only
=> utils: UUID: use default generated comparison operators

main.cc
- main: expose tools as a vector<>
- main: use a struct for representing tool
- main: track tools descriptin in tool struct
- main: add missing descriptions for tools
- main: move get_tools() into main()
Fixes #13026
=> main: display descriptions of all tools

cql3/query_processor.cc, service/client_state.hh, test/cql-pytest/rest_api.py, test/cql-pytest/test_batch.py, test/cql-pytest/test_shedding.py, test/cql-pytest/test_use.py, test/cql-pytest/util.py, transport/server.cc
=> Transport server error handling fixes backport

utils/bloom_calculations.cc, utils/bloom_calculations.hh
this series applies some random cleanups to bloom_filter. these cleanups were the side products when the author was working on #13314 .
=> bloom_filter: cleanups

api/storage_service.cc, compaction/task_manager_module.cc, compaction/task_manager_module.hh, test/rest_api/test_compaction_task.py
Task manager task implementations of classes that cover
offstrategy keyspace compaction which can be start through
/storage_service/keyspace_compaction/ api.
Top level task covers the whole compaction and creates child
tasks on each shard.
=> Offstrategy keyspace compaction task

utils/s3/client.cc
This is a part of PR #13493 that contains found fixes for the client code itself. The original PR has some questions to resolve, so it's worth merging the fixes separately.
=> A couple of s3/client fixes found when testing over AWS S3

docs/using-scylla/integrations/index.rst, docs/using-scylla/integrations/integration-mindsdb.rst
=> Adding MindsDB integration to Docs

test/boost/sstable_datafile_test.cc, test/boost/sstable_directory_test.cc, test/boost/sstable_move_test.cc, test/boost/sstable_resharding_test.cc, test/lib/sstable_utils.hh
There are two of them currently with slightly different declaration. Better to leave only one.
=> Sanitize test::filename(sstable) API

api/storage_service.cc, compaction/task_manager_module.cc, compaction/task_manager_module.hh, test/rest_api/test_compaction_task.py
Task manager's tasks covering scrub compaction on top, 
shard and table level. 
For this levels we have common scrub tasks for each scrub
mode since they share code. Scrub modes will be differentiated
on compaction group level.
=> Scrub compaction task

test/boost/sstable_directory_test.cc
in this series, instead of hardwiring to integer, we switch to generation generator for creating new generations. this should helps us to migrate to a generation identifier which can also represented by UUID. and potentially can help to improve the testing coverage once we switch over to UUID-based generation identifier. will need to parameterize these tests by then, for sure.
=> test: sstable_*test: use generator to create new generations

compaction/compaction_manager.cc, compaction/compaction_manager.hh, replica/table.cc
Fixes #13429.
Fixes #12390.
Fixes #13430.
=> Backport compaction reevaluation fixes to branch-5.1

compaction/task_manager_module.cc, compaction/task_manager_module.hh, test/rest_api/task_manager_utils.py, test/rest_api/test_compaction_task.py
Implementation of task_manager's tasks that cover major, cleanup, 
offstrategy, and upgrade sstables compaction of one table.
=> Table compaction tasks

compaction/task_manager_module.cc, compaction/task_manager_module.hh, replica/distributed_loader.cc, test/rest_api/test_compaction_task.py
Task manager's tasks covering resharding compaction 
on top and shard level.
=> Compaction reshape tasks

docs/operating-scylla/admin-tools/scylla-sstable.rst, docs/operating-scylla/admin.rst
This PR fixes or removes broken links reported by an online link checker.
Fixes https://github.com/scylladb/scylladb/issues/14488
=> doc: fix broken links reported by the link checker

test/pylib/manager_client.py, test/pylib/rest_client.py, test/pylib/scylla_cluster.py, test/pylib/util.py
Some minor fixes reported by `mypy`.
=> minor test/pylib type fixes

compaction/task_manager_module.cc, compaction/task_manager_module.hh, replica/distributed_loader.cc, test/boost/sstable_directory_test.cc, test/rest_api/test_compaction_task.py
Task manager tasks covering reshard compaction.
Reattempt on https://github.com/scylladb/scylladb/pull/14044. Bugfix for https://github.com/scylladb/scylladb/issues/14618 is squashed with 95191f4. 
Regression test added.
=> Compaction reshard task

test/boost/s3_test.cc
let's use RAII to tear down the client and the input file, so we can
always perform the cleanups even if the test throws.
=> s3/test: close using deferred_close() or deferred()

gms/gossiper.cc, service/storage_service.cc
We don't load gossiper endpoint states in `storage_service::join_cluster` if `_raft_topology_change_enabled`, but gossiper is still needed even in case of `_raft_topology_change_enabled` mode, since it still contains part of the cluster state. To work correctly, the gossiper needs to know the current endpoints. We cannot rely on seeds alone, since it is not guaranteed that seeds will be up to date and reachable at the time of restart.
The problem was demonstrated by the test `test_joining_old_node_fails`, it fails occasionally with `experimental_features: [consistent-topology-changes]` on the line where it waits for `TEST_ONLY_FEATURE` to become enabled on all nodes. This doesn't happen since `SUPPORTED_FEATURES` gossiper state is not disseminated, and feature_service still relies on …
=> raft topology: restore gossiper eps

service/storage_service.cc
For `removenode`, we make a removed node a non-voter early. There is no downside to it because the node is already dead. Moreover, it improves availability in some situations.
For `decommission`, if we decommission a node when the number of nodes is even, we make it a non-voter early to improve availability. All majorities containing this node will remain majorities when we make this node a non-voter and remove it from the set because the required size of a majority decreases.
We don't change `decommission` when the number of nodes is odd since this may reduce availability.
Fixes #13959
=> raft: make a removed/decommissioning node a non-voter early

gms/gossiper.cc
This series fixes a couple of review comments on #14845
=> gossiper: lock_endpoint: fix review comments

repair/row_level.cc
This sort series deals with two stall sources in row-level repair `to_repair_rows_list`:
1. Freeing the input `repair_rows_on_wire` in one shot on return (as seen in https://github.com/scylladb/scylladb/issues/14537)
2. Freeing the result `row_list` in one shot on error.  this hasn't been seen in testing but I have no reason to believe it is not susceptible to stalls exactly like repair_rows_on_wire with the same number of rows and mutations.
Fixes https://github.com/scylladb/scylladb/issues/14537
=> Prevent reactor stalls in to_repair_rows_list

configure.py
more structured this way. this also allows us to quickly identify the part which should/can be reused when migrating to CMake based building system.
Refs https://github.com/scylladb/scylladb/issues/15379
=> build: extract code fragments into functions

test/pylib/minio_server.py
this series extracts the the env variables related functions out and remove unused `import`s for better readability.
=> test/pylib: extract the env variable related functions out

test/boost/s3_test.cc, utils/s3/client.cc
When upload-sink is flushed, it may notice that the upload had not yet been started and fall-back to plain PUT in that case. This will make small files uploading much nicer, because multipart upload would take 3 API calls (start, part, complete) in this case
fixes: #13014
=> Make s3 upload sink PUT small objects

data_dictionary/data_dictionary.cc, data_dictionary/keyspace_metadata.hh, db/schema_tables.cc, replica/database.cc, replica/database.hh, service/migration_listener.hh, service/migration_manager.cc, service/storage_service.cc
This is a backport of https://github.com/scylladb/scylladb/pull/14158 to branch 5.2
=> [Backport 5.2] properly update storage service after schema changes

message/messaging_service.cc, message/messaging_service.hh, replica/table.cc, serializer_impl.hh, test/lib/cql_test_env.cc, test/lib/cql_test_env.hh
This series adds preparation patches for file stream tablet implementation in enterprise branch. It minimizes the differences between those two branches.
=> File stream for tablet preparation

sstables/writer.hh, utils/bit_cast.hh
=> sstables, utils: do not include unused header

scripts/coverage.py
various cleanups in `scripts/coverage.py`. they do not change the behavior of this script in the happy path.
=> scripts/coverage.py: cleanups

gms/gossiper.cc
Backport the following patches to 5.2:
- gossiper: mark_alive: enter background_msg gate (#14791)
- gossiper: mark_alive: use deferred_action to unmark pending (#14839)
=> [Backport to 5.2] gossiper: mark_alive: use deferred_action to unmark pending

streaming/stream_transfer_task.cc, test/topology_experimental_raft/test_tablets.py
The observed crash was in the following piece on "cf" access:
if (*table_is_dropped) {
sslog.info("[Stream #{}] Skipped streaming the dropped table {}.{}", si->plan_id, si->cf.schema()->ks_name(), si->cf.schema()->cf_name());
Fixes #16181
Also, add a test case which reproduces the problem by doing table drop during tablet migration. But note that the problem is not tablet-specific.
=> Fix crash on table drop concurrent with streaming 

main.cc, message/messaging_service.cc, message/messaging_service.hh, repair/repair.cc, repair/repair.hh, repair/row_level.cc, repair/row_level.hh, repair/task_manager_module.hh, test/pylib/manager_client.py, test/pylib/rest_client.py, test/pylib/scylla_cluster.py, test/topology_experimental_raft/pytest.ini, test/topology_experimental_raft/test_tablets.py
This patch adds basic tablet repair support.
Below is an example showing how tablet repairs works. The `nodetool
repair -pr` cmd was performed on all the nodes, which makes sure no duplication
repair work will be performed and each tablet will be repaired exactly once.
Three nodes in the cluster. RF = 2. 16 initial tablets.
Tablets:
```
cqlsh> SELECT  * FROM system.tablets;
keyspace_name | table_id                             | last_token           | table_name | tablet_count | new_replicas | replicas                                                                               | session | stage
---------------+--------------------------------------+----------------------+------------+--------------+--------------+---------------------------------------------------------------------------- …
```
=> Basic tablet repair support

alternator/executor.cc, test/alternator/test_tag.py
Alternator incorrectly refuses an empty tag value for TagResource, but DynamoDB does allow this case and it's useful (note that an empty tag key is rightly forbidden). So this short series fixes this case, and adds additional tests for TagResource which covers this case and other cases we forgot to cover in tests.
Fixes #16904.
=> alternator: allow empty tag value

test/topology/util.py, test/topology_custom/test_raft_snapshot_request.py
Add workaround for scylladb/python-driver#295.
Also an assert made at the end of the test was false, it is fixed with
appropriate comment added.
=> Fix flakiness in test_raft_snapshot_request

types/types.cc
so we can tighten our dependencies a little bit. there are only three places where we are using the `date` library. also, there is no need to reinvent the wheels if there are ready-to-use ones.
=> types: use {fmt} to format time and boolean

repair/row_level.cc
row_level_repair and repair_meta keep a reference to a table. 
If the table is dropped during repair, its object is destructed, leaving
a dangling reference.
Delete {row_level_repair,repair_meta}::_cf and replace their usages.
Fixes: #17233.
=> repair: delete table reference from repair related classes

test/nodetool/test_compactionstats.py, test/nodetool/test_viewbuildstatus.py, tools/scylla-nodetool.cc
=> tools/scylla-nodetool: implement compactionstats and viewbuildstatus

test/nodetool/test_tablestats.py, tools/scylla-nodetool.cc, utils/rjson.hh
=> tools/scylla-nodetool: implement tablestats

query-request.hh, query-result-set.hh, query-result.hh
* query::specific_ranges
* query::partition_slice
* query::read_command
* query::forward_request
* query::forward_request::reduction_type
* query::forward_request::aggregation_info
* query::forward_result::printer
* query::result_set
* query::result_set_row
* query::result::printer
Refs #13245
=> query*.h: add fmt::formatter for types

test/nodetool/test_toppartitions.py, tools/scylla-nodetool.cc
* tighten the param check for toppartitions
* add an extra empty line inbetween reports
=> tools/scylla-nodetool: fixes to address test failures with dtest

tools/format_printers.hh, tools/scylla-nodetool.cc
=> tools/scylla-nodetool: extract and use {yaml,json}_writers

repair/repair.cc, test/rest_api/conftest.py, test/rest_api/run, test/rest_api/suite.yaml, test/rest_api/test_compaction_task.py, test/rest_api/test_storage_service.py
Fix test_compaction_task.py, test_repair_task.py and 
test_storage_service.py to work with tablets.
Fixes: #17338.
=> test: rest_api: fix tests to work with tablets

service/tablet_allocator.cc, service/tablet_allocator.hh, service/topology_coordinator.cc, test/boost/tablets_test.cc
Tablet transition would get stuck anyway for such nodes, so it's not worth trying
refs: #16372 (not fixes, because there's also repair transitions with same problem)
=> Do not try to balance tablets on nodes which are known to be down

cql3/statements/create_keyspace_statement.cc, test/cql-pytest/test_guardrail_replication_strategy.py, test/cql-pytest/test_keyspace.py
The CDC feature is not supported on a table that uses tablets
(Refs https://github.com/scylladb/scylladb/issues/16317), so if a user creates a keyspace with tablets enabled
they may be surprised later (perhaps much later) when they try to enable
CDC on the table and can't.
The LWT feature always had issue Refs https://github.com/scylladb/scylladb/issues/5251, but it has become potentially
more common with tablets.
So it was proposed that as long as we have missing features (like CDC or
LWT), every time a keyspace is created with tablets it should output a
warning (a bona-fide CQL warning, not a log message) that some features
are missing, and if you need them you should consider re-creating the
keyspace without tablets.
This PR does this.
The warning text which will be produced is the …
=> tablets: add warning on CREATE KEYSPACE

test/boost/cql_query_large_test.cc
The current test in boost/cql_query_large_test::test_large_data only checks whether notifications for large rows and cells are written into the system keyspace. It doesn't check this for partitions.
This change adds this check for partitions.
=> test/boost: add test for writing large partition notifications

db/view/view.cc
It's pretty straightforward, but prior to that, exception handling needs some care
=> Coroutinize view_builder::stop()

service/topology_coordinator.cc, test/topology_custom/test_raft_snapshot_request.py, test/topology_experimental_raft/test_cdc_generation_clearing.py
We want to clear CDC generations that are no longer needed
(because all writes are already using a new generation) so they
don't take space and are not sent during snapshot transfers
(see e.g. https://github.com/scylladb/scylladb/issues/17545).
The condition used previously was that we clear generations which
were closed (i.e., a new generation started at this time) more than
24h ago. This is a safe choice, but too conservative: we could
easily end up with a large number of obsolete generations if we
boot multiple nodes during 24h (which is especially easy to do
with tablets.)
Change this bound from 24h to `5s + ring_delay`. The choice is
explained in a comment in the code.
Additionally, improve `test_raft_snapshot_request` that would
become flaky after the change so it's not sensitive to …
=> topology_coordinator: clear obsolete generations earlier

replica/compaction_group.hh, replica/database.hh, replica/table.cc, replica/tablets.cc
=> Some sstable set related improvements

test/pylib/manager_client.py, test/pylib/scylla_cluster.py, test/topology/conftest.py
This commit brings several new features in scylla_cluster.py to fix runaway asyncio task problems in topology tests  
-  Start-Stop Lock and Stop Event in ScyllaServer
- Tasks History, Wait for tasks from Tasks History and Manager broken state in ScyllaClusterManager
- make ManagerClient object function scope
- test_finished_event in ManagerClient
Fixes: scylladb/scylladb#16472
Fixes: scylladb/scylladb#16651
=> fix test teardown race with ongoing test operation

docs/dev/isolation.md
Update `docs/dev/isolation.d`:
* Update the list of scheduling groups
* Remove IO priority groups (they were folded into scheduling groups)
* Add section on RPC isolation
=> docs: update isolation.md

auth/service.cc, cql3/statements/alter_service_level_statement.cc, cql3/statements/attach_service_level_statement.cc, cql3/statements/create_keyspace_statement.cc, cql3/statements/create_service_level_statement.cc, cql3/statements/create_table_statement.cc, cql3/statements/detach_service_level_statement.cc, cql3/statements/drop_service_level_statement.cc, cql3/statements/grant_statement.cc, cql3/statements/revoke_statement.cc, cql3/statements/role-management-statements.cc, cql3/statements/schema_altering_statement.cc
Coroutinization will help improve readability and allow easier changes planned for this code.
This work was separated from https://github.com/scylladb/scylladb/pull/17910 to make it smoother to review and merge.
=> Coroutinize some auth and service levels related functions

replica/compaction_group.hh, replica/database.hh, replica/table.cc
backport not needed, these are just cleanups.
=> Some cleanups for replica table

service/mapreduce_service.cc
mapreduce_server was previously coroutinized, but only partially. This
series completes coroutinization and eliminates remaining continuation chains.
None of this code is performance sensitive as it runs at the super-coordinator level
and is amortized over a full scan of the entire table.
No backport needed as this is a cleanup.
=> mapreduce_service: complete coroutinization

cql3/statements/create_view_statement.cc, test/cql-pytest/test_describe.py, test/cql-pytest/test_materialized_view.py
Before these changes, we could create a materialized
view specifying its ID, but the option was ignored.
This commit makes Scylla respect the option. Now specifying
the ID results in the MV being created with that specific ID.
This way, Scylla's behavior is consistent with Cassandra's.
Because Cassandra doesn't mention the option in its
user documentation, we don't update it either in case
the semantics of it changes in the future -- we want
to have an open door for any modifications.
Note that Cassandra returns a server error if the provided
ID is already in use, both in the case of regular tables
and MVs. That's most likely a bug. Instead of following that
behavior, we stay consistent with the current semantics of
creating a regular table in Scylla: if the provided ID is
already used, …
=> cql3: Make creating MV respect ID option

scripts/get_description.py, scripts/metrics-config.yml
get_description.py script is a document related script that looks for metrics description in the code.
Its configuration needs to address changes in the code.
This series contains a configuration change and a code fix that allows it to run as a standalone script, and not as a library.
No need to backport, this a documentation related script.
=> Update get_description.py script

cql3/statements/describe_statement.cc, docs/dev/describe_schema.md, test/cql-pytest/test_describe.py
In the past, DESC SCHEMA would produce create statements for both the base
and the log table. That was incorrect as the log table is automatically
created alongside the base one. That was solved in scylladb/scylladb@9ab57b1
(scylladb/scylladb#18467).
The mentioned changes implemented the following solution:
* DESC SCHEMA/KEYSPACE/TABLE would still print a create statement for the
CDC base table,
* DESC SCHEMA/KEYSPACE would start printing an alter statement for the
CDC log table. That statement would ensure that the restored log table
has the same parameters as the original one,
* DESC TABLE <base table> would behave as DESC SCHEMA/KEYSPACE, i.e.
it would print a create statement for the base table and an alter
statement for the log table,
* DESC TABLE <log table> would result in an …
=> cql3: Allow for describing CDC log tables

test/boost/view_schema_test.cc
In this PR, we improve various aspects of the test:
* increase obtained information whenever any test case fails,
* split test cases,
* elaborate on the semantics of generating view updates
and what exactly we check and why.
Backport: not needed, this is an enhancement.
=> test/boost/view_schema_test: Improve test_view_update_generating_writetime

replica/database.cc, test/boost/database_test.cc
TRUNCATE TABLE saves the current commit log replay positions in case there is a crash so that replay knows where to begin replaying the mutations. These are collected and saved per shard into `system.truncated`. In case a shard received no mutations, its replay position will be an empty, default constructed object of type `db::replay_position` with its members set to 0. Truncate will incorrectly interpret these empty replay positions as if they were coming from shard 0, and save them as such, potentially overwriting an actual valid replay position coming from the actual shard 0. In the case of a crash, this will cause the commit log on shard 0 to be replayed from the beginning, and result with data resurrection.
Fixes #21719
=> truncate: commit log replay positions are not saved correctly

gms/gossiper.cc, gms/gossiper.hh
The series contains small fixes to the gossiper one of which fixes #21930. Others I noticed while debugged the issue.
Fixes: #21930
=> Do not reset quarantine list in non raft mode

test/boost/multishard_mutation_query_test.cc
This test has multiple problems:
* has 3 embedded loops to run different scenarios, ignores variable from 2 of these, running with hardcoded settings instead
* initializes misses and lookups to 0 at the start of each scenario, this throws off per-page increment checks, when the previous scenario moved these metrics and they don't start from 0; this causes the test to sometimes fail
* duplicate check of drops == 0 (just cosmetic)
Fix all three problems, the second is especially important because it made the test flaky.
Additionally, ensure the test will keep using vnodes in the future, by explicitly creating a vnodes keyspace for them.
Fixes: #16794
Test fix, not a backport candidate normally, we can backport to 2025.1 if the test becomes too unstable there
=>  test/boost/multishard_mutation_query_test: fix test_read_with_partition_row_limits

alternator/executor.cc, test/alternator/test_lsi.py
Previously, LSI keys were stored as separate, top-level columns in the base table. This patch changes this behavior for newly created tables, so that the key columns are stored inside the `:attrs` map. Then, we use top-level computed columns instead of regular ones.
This makes LSI storage consistent with GSIs and allows the use of a collection tombstone on `:attrs` to delete all attributes in a row except for keys in new tables.
Refs https://github.com/scylladb/scylladb/pull/24991
Refs https://github.com/scylladb/scylladb/issues/6930
=> alternator: Store LSI keys in :attrs for newly created tables

docs/features/cdc/cdc-streams.rst
Fixed some minor grammatical changes in the documentation.
=> Fix: small grammatical changes
