tests/filtering_test.cc

The test case ensures that filtering with paging works fine if
an aggretation function is used - the results should be presented
as a single aggregated value, without partial results per-page.
Ref #4540

tests: add test for filtering+paging+aggregation

---

configure.py

In practice, we always want to use the same sanitizer flags with
seastar and scylla. Seastar was already marking its sanitizer flags
public, so what was missing was exporting the link flags via pkgconfig
and dropping the duplicates from scylla.
I am doing this after wasting some time editing the wrong file.
This depends on the seastar patch to export the sanitizer flags in
pkgconfig.
Signed-off-by: Rafael Ávila de Espíndola <espindola@scylladb.com>
Scylla doesn't use pull-requests, please send a patch to the [mailing list](mailto:scylladb-dev@googlegroups.com) instead.
See our [contributing guidelines](../CONTRIBUTING.md) and our [Scylla development guidelines](../HACKING.md) for more information.
If you have any questions please don't hesitate to send a mail to the [dev …

Use the sanitizer flags from seastar

---

cql3/restrictions/statement_restrictions.cc
tests/secondary_index_test.cc

The code that decides whether a query should used indexing was buggy - a partition key index might have influenced the decision even if the whole partition key was passed in the query (which effectively means that indexing it is not necessary).
Fixes #4539

Fix deciding whether a query uses indexing

---

tools/toolchain/Dockerfile
tools/toolchain/image

Update the toolchain baseline to Fedora 30, which includes gcc 9.
Note to maintainer: even more than usual, this should be applied as a patch, because it is based on next rather than master. This is because only next supports gcc 9, and I'm too impatient to wait for promotion.

tools: toolchain: update to Fedora 30 / gcc 9

---

cql3/statements/delete_statement.cc
database.hh
service/storage_service.cc
tests/cql_query_test.cc

If the database supports infinite bound range deletions,
CQL layer will no longer throw an error indicating that both ranges
need to be specified.
Fixes #432
(cherry picked from commit 17acedb0c610d69cbc9675a02af467e44fa5b175)
Update test_range_deletion_scenarios unit test accordingly.

Cql3: lift infinite bound check

---

sstables/mp_row_consumer.hh
sstables/mutation_fragment_filter.hh
sstables/partition.cc
sstables/row.hh

Currently, parser and the consumer save its state and return the
control to the caller, which then figures out that it needs to enter a
new partition, and that it doesn't need to skip. We do it twice, after
row end, and after row start. All this work could be avoided if the
consumer installed by the reader adjusted its state and pushed the
fragments on the spot. This patch achieves just that.
This results in less CPU overhead.
The ka/la reader is left still stopping after row end.
Brings a 20% improvement in frag/s for a full scan in perf_fast_forward (Haswell, NVMe):
perf_fast_forward -c1 -m1G  --run-tests=small-partition-skips:
Before:
```
read    skip      time (s)   iterations     frags     frag/s    mad f/s    max f/s    min f/s    avg aio    aio      (KiB) blocked dropped  idx hit …
```

sstable: mc: reader: Optimize multi-partition scans for data sets with small partitions

---

types.cc
types/collection.hh

This is a band-aid patch that is supposed to fix the immediate problem of large collections causing large allocations. The proper fix is to use IMR but that will take time. In the meanwhile alleviate the pressure on the memory allocator by using a chunked storage collection (`utils::chunked_vector`) instead of `std::vector`. In the linked issue `seastar::chunked_fifo` was also proposed as the container to use, however chunked fifo is not traversable in reverse which disqualifies it from this role.
Refs: #3602

Collection: use utils::chunked_vector to store the cells

---

database.cc
database.hh

_cfg cannot be null, so it can be converted to a reference to
indicate this. Follow-up to fe59997efeef.

database: convert _cfg from a pointer to a reference

---

repair/repair.cc
repair/row_level.cc

Since commit bb56653 (repair: Sync schema from follower nodes before
repair), the behaviour of handling down node during repair has been
changed.  That is, if a repair follower is down, it will fail to sync
schema with it and the repair of the range will be skipped. This means
a range can not be repaired unless all the nodes for the replicas are up.
To fix, we filter out the nodes that is down and mark the repair is
partial and repair with the nodes that are still up.
Tests: repair_additional_test:RepairAdditionalTest.repair_with_down_nodes_2b_test
Fixes: #4616
Backports: 3.1

repair: Allow repair when a replica is down

---

tests/types_test.cc
types.cc

Resolves #4633 (tuple_type was the only type for which to_string wasn't implemented yet).

Implement tuple_type_impl::to_string_impl.

---

cql3/Cql.g
cql3/multi_column_relation.hh
cql3/operator.cc
cql3/operator.hh
cql3/relation.hh
cql3/restrictions/abstract_restriction.hh
cql3/restrictions/primary_key_restrictions.hh
cql3/restrictions/single_column_primary_key_restrictions.hh
cql3/restrictions/single_column_restriction.hh
cql3/restrictions/statement_restrictions.cc
cql3/single_column_relation.cc
cql3/single_column_relation.hh
cql3/token_relation.cc
cql3/token_relation.hh
tests/cql_query_test.cc
types.cc
types.hh

Implement LIKE parsing, intermediate representation, and query processing.  Add tests for this implementation (leaving the LIKE functionality tests in `tests/like_matcher_test.cc`).
Refs #4477.

Complete the LIKE operator

---

utils/config_file.hh

The get_value method returns a pointer to the value that is used by the
value_to_json method.
The assumption is that the void pointer points to the actual value.
Fixes #4678
Scylla doesn't use pull-requests, please send a patch to the [mailing list](mailto:scylladb-dev@googlegroups.com) instead.
See our [contributing guidelines](../CONTRIBUTING.md) and our [Scylla development guidelines](../HACKING.md) for more information.
If you have any questions please don't hesitate to send a mail to the [dev list](mailto:scylladb-dev@googlegroups.com).

config_file.hh: get_value return a pointer to the value

---

tests/logalloc_test.cc

Post commit d8dbacc7f65386642297606e410350bd35ff1e3d
(More precise poisoning in logalloc)
logalloc_test's memory footprint has grown, in particula
in test_region_groups, and it triggers the oom killer on
our test automation machines.
This patch scales down the test so it requires less memory
(Seen ~2.5 GB vs. ~4.4 GB based on ps/RSS)
Fixes #4669
Test: logalloc_test(debug)

tests: logalloc_test: scale down test_region_groups

---

api/messaging_service.cc
db/config.cc
db/config.hh
db/system_keyspace.cc
gms/inet_address.cc
gms/inet_address.hh
gms/inet_address_serializer.hh
idl/gossip_digest.idl.hh
init.cc
locator/ec2_snitch.cc
locator/gce_snitch.cc
locator/rack_inferring_snitch.hh
main.cc
message/messaging_service.cc
service/client_state.hh
service/storage_service.cc
tests/test-serialization.cc
thrift/server.cc
thrift/server.hh
transport/event.cc
transport/event.hh
transport/event_notifier.cc
transport/response.hh
transport/server.cc
transport/server.hh
types.cc
types.hh

Fixes #2027
Modifies inet address type in scylla to use seastar::net::inet_address,
and removes explicit use of ipv4_addr in various network code in favour
of socket_address. Thus capable of resolving and binding to ipv6.
Adds config option to enable/disable ipv6 (default enabled), so
upgrading cluster can continue to work while running mixed version
nodes (since gossip message address serialization becomes different).
v2:
* Made serialization of gms::inet_address ipv6 aware (encoding
addresses so that ipv4 encoding remains the same).
* Made address lookup family optional
* Added enable/disable option
* Removed legacy "raw" access
v3:
* Rebased on master
* Renamed enable_ipv6 to enable_ipv6_dns_lookup

IPv6 support

---

cql3/statements/create_keyspace_statement.cc
cql3/statements/create_keyspace_statement.hh
transport/messages/result_message_base.hh
transport/server.cc
transport/server.hh

If the user creates a keyspace with the 'SimpleStrategy' replication class
in a multi-datacenter environment, they will receive a warning in the CQL shell
and in the server logs.
Resolves #4481 and #4651.

Warn user about using SimpleStrategy with Multi DC deployment

---

repair/row_level.cc

Start n1, n2
Create ks with rf = 2
Run repair on n2
Stop n2 in the middle of repair
n1 will notice n2 is DOWN, gossip handler will remove repair instance
with n2 which calls remove_repair_meta().
Inside remove_repair_meta(), we have:
```
1        return parallel_for_each(*repair_metas, [repair_metas] (auto& rm) {
2            return rm->stop();
3        }).then([repair_metas, from] {
4            rlogger.debug("Removed all repair_meta for single node {}", from);
5        });
```
Since 3.1, we start 16 repair instances in parallel which will create 16
readers.The reader semaphore is 10.
At line 2, it calls
```
6    future<> stop() {
7       auto gate_future = _gate.close();
8       auto writer_future = _repair_writer.wait_for_writer_done();
9       return …
```

repair: Avoid deadlock in remove_repair_meta

---

tests/mutation_reader_test.cc
tests/simple_schema.hh

Currently the
`test_multishard_combining_reader_non_strictly_monotonic_positions` is
flaky. The test is somewhat unconventional, in that it doesn't use the
same instance of data as the input to the test and as it's expected
output, instead it invokes the method which generates this data
(`make_fragments_with_non_monotonic_positions()`) twice, first to
generate the input, and a secondly to generate the expected output. This
means that the test is prone to any deviation in the data generated by
said method. One such deviation, discovered recently, is that the method
doesn't explicitly specify the deletion time of the generated range
tombstones. This results in this deletion time sometimes differing
between the test input and the expected output. Solve by explicitly
passing the same deletion …

tests/mutation_reader_test stabilize test_multishard_combining_reader_non_strictly_monotonic_positions

---

mutation_partition.cc

row::append_cell() has a precondition that the new cell column id needs
to be larger than that of any other already existing cell. If this
precondition is violated the row will end up in an invalid state. This
patch adds assertion to make sure we fail early in such cases.

mutation_partition: verify row::append_cell() precondition

---

database.hh
table.cc

`disable_sstable_write` needs to acquire `_sstable_deletion_sem` to properly synchronize with background deletions done by `on_compaction_completion` to ensure no sstables will be created or deleted during `reshuffle_sstables` after `storage_service::load_new_sstables` disables sstable writes.
Fixes #4622
Test: unit(dev), nodetool_additional_test.py migration_test.py

Fix disable_sstable_write synchronization with on_compaction_completion

---

tests/cql_test_env.cc
tests/test_services.cc

Fix another source of flakyness in `mutation_reader_test`. This one is caused by `storage_service_for_tests` lacking a `config::broadcast_to_all_shards()` call, triggering an invalid memory access (or SEGFAULT) when run on more than one shards.
Refs: #4695

Fix storage service for tests

---

distributed_loader.cc
lister.cc
tests/database_test.cc

Issue #4558 describes a situation in which failure to execute clearsnapshots
will hard crash the node. The problem is that clearsnapshots will internally use
lister::rmdir, which in turn has two in-tree users: clearing snapshots and clearing
temporary directories during sstable creation. The way it is currently
coded, it wraps the io functions in io_check, which means that failures
to remove the directory will crash the database.
We recently saw how benign failures crashed a database during
clearsnapshot: we had snapshot creation running in parallel, adding more
files to the directory that wasn't empty by the time of deletion.  I
have also seen very often users add files to existing directories by
accident, which is another possibility to trigger that.
This patch removes the io_check from …

make sure failure to create snapshots won't crash the node

---

db/data_listeners.cc
db/data_listeners.hh

Data listener reads are implemented as flat_mutation_readers, which
take a reference to the listener and then execute asynchronously.
The listener can be removed between the time when the reference is
taken and actual execution, resulting in a dangling pointer
dereference.
Fix by using a weak_ptr to avoid writing to a destroyed object. Note that writes
don't need protection because they execute atomically.
Fixes #4661.

toppartitions: fix race between listener removal and reads

---

repair/row_level.cc

After switching to rpc stream interface, we increased the row buffer
size. Code works on the buffer that do not yield can stall the reactor.
This series fixes the issue by futurizing or running the code in thread
and yield.
Fixes: #4642

Fix possible stalls in row level repair

---

message/messaging_service.cc

get_rpc_client assumes the messaging_service is not stopped. We should check
is_stopping() before we call get_rpc_client.
We do such check in existing code, e.g., send_message and friends. Do
the same check in the newly introduced
make_sink_and_source_for_stream_mutation_fragments() and friends for row
level repair.
Fixes: #4767

messaging_service: Check if messaging_service is stopped before get_rpc_client

---

db/config.cc
db/config.hh
main.cc
sstables/mc/writer.cc
sstables/sstables.cc
tests/cql_test_env.cc
utils/exceptions.cc
utils/exceptions.hh

Not emitting partition_end for a partition is incorrect. SStable
writer assumes that it is emitted. If it's not, the sstable will not
be written correctly. The partition index entry for the last partition
will be left partially written, which will result in errors during
reads. Also, statistics and sstable key ranges will not include the
last partition.
It's better to catch this problem at the time of writing, and not
generate bad sstables.
Another way of handling this would be to implicitly generate a
partition_end, but I don't think that we should do this. We cannot
trust the mutation stream when invariants are violated, we don't know
if this was really the last partition which was supposed to be
written. So it's safer to fail the write.
Enabled for both mc and la/ka.
Passing …

Catch unclosed partition during sstable write

---

service/storage_service.cc

When a node is restarted, there is a race between gossip starts (other
nodes will mark this node up again and send requests) and the tokens are
replicated to other shards. Here is an example:
- n1, n2
- n2 is down, n1 think n2 is down
- n2 starts again, n2 starts gossip service, n1 thinks n2 is up and sends
reads/writes to n2, but n2 hasn't replicated the token_metadata to all
the shards.
- n2 complains:
token_metadata - sorted_tokens is empty in first_token_index!
token_metadata - sorted_tokens is empty in first_token_index!
token_metadata - sorted_tokens is empty in first_token_index!
token_metadata - sorted_tokens is empty in first_token_index!
token_metadata - sorted_tokens is empty in first_token_index!
token_metadata - sorted_tokens is empty in first_token_index!
storage_proxy - …

storage_service: Replicate and advertise tokens early in the boot up process

---

db/config.cc
db/config.hh
main.cc
sstables/mc/writer.cc
sstables/sstables.cc
tests/cql_test_env.cc
utils/config_file.hh
utils/exceptions.cc
utils/exceptions.hh

Not emitting partition_end for a partition is incorrect. SStable
writer assumes that it is emitted. If it's not, the sstable will not
be written correctly. The partition index entry for the last partition
will be left partially written, which will result in errors during
reads. Also, statistics and sstable key ranges will not include the
last partition.
It's better to catch this problem at the time of writing, and not
generate bad sstables.
Another way of handling this would be to implicitly generate a
partition_end, but I don't think that we should do this. We cannot
trust the mutation stream when invariants are violated, we don't know
if this was really the last partition which was supposed to be
written. So it's safer to fail the write.
Enabled for both mc and la/ka.
Passing …

Catch unclosed partition sstable write

---

idl/streaming.idl.hh
message/messaging_service.cc
message/messaging_service.hh
streaming/stream_session.cc
streaming/stream_session.hh
streaming/stream_transfer_task.cc

In case of error on the sender side, the sender does not propagate the
error to the receiver. The sender will close the stream. As a result,
the receiver will get nullopt from the source in
get_next_mutation_fragment and pass mutation_fragment_opt with no value
to the generating_reader. In turn, the generating_reader generates end
of stream. However, the last element that the generating_reader has
generated can be any type of mutation_fragment. This makes the sstable
that consumes the generating_reader violates the mutation_fragment
stream rule.
To fix, we need to propagate the error. However RPC streaming does not
support propagate the error in the framework. User has to send an error
code explicitly.
Fixes: #4789

streaming: Send error code from the sender to receiver

---

streaming/stream_transfer_task.cc

The stream close() guarantees the data sent will be flushed. No need to
call the stream flush() since the stream is not reused.
Follow up fix for commit bac987e32ada (streaming: Send error code from
the sender to receiver).
Fixes: #4789

streaming: Do not call rpc stream flush in send_mutation_fragments

---

message/messaging_service.cc
message/messaging_service.hh
streaming/stream_mutation_fragments_cmd.hh
streaming/stream_session.cc
streaming/stream_session.hh
streaming/stream_transfer_task.cc

Avoid including the lengthy stream_session.hh in messaging_service.
More importantly, fix the build because currently messaging_service.cc
and messaging_service.hh does not include stream_mutation_fragments_cmd.
I am not sure why it builds on my machine. Spotted this when backporting
the "streaming: Send error code from the sender to receiver" to 3.0
branch.
Refs: #4789

streaming: Move stream_mutation_fragments_cmd to a new file

---

repair/row_level.cc

We need to keep the sstables object alive during the operation of
do_for_each.
Notes: No need to backport to 3.1.
Fixes #4811

repair: Fix use after free in do_estimate_partitions_on_local_shard

---

configure.py
thrift/server.cc
transport/server.cc

Seastar switched accept() to return a single struct instead of a variadic future,
adjust the code to the new API to avoid deprecation warnings.

thrift, transport: switch to new seastar accept() API

---

db/config.cc
db/config.hh
gms/inet_address.cc
gms/inet_address.hh
init.cc
main.cc
service/storage_service.cc

Add listen/rpc "prefer_ipv6" options to DNS lookup of bind addresses for API/rpc/prometheus etc .
Fixes #4751
Adds using a preferred address family to dns name lookups related to
listen address and rpc address, adhering to the respective "prefer" options.
API, prometheus and broadcast address are all considered to be covered by
the "listen_interface_prefer_ipv6" option.
Note: scylla does not yet support actual interface binding, but these
options should apply equally to address name parameters.
Setting a "prefer_ipv6" option automtially enables ipv6 dns family query.

Add listen/rpc "prefer_ipv6" options to DNS lookup

---

main.cc
repair/repair.cc
repair/repair.hh
repair/row_level.cc
repair/row_level.hh

After commit 8a0c4d5 (Merge "Repair switch to rpc stream" from Asias),
we increased the row buffer size for repair from 512KiB to 32MiB per
repair instance. We allow repairing 16 ranges (16 repair instance) in
parallel per repair request. So, a node can consume 16 * 32MiB = 512MiB
per user requested repair. In addition, the repair master node can hold
data from all the repair followers, so the memory usage on repair master
can be larger than 512MiB. We need to provide a way to limit the memory
usage.
In this patch, we limit the total memory used by repair to 10% of the
shard memory. The ranges that can be repaired in parallel is:
max_repair_ranges_in_parallel = max_repair_memory / max_repair_memory_per_range.
For example, if each shard has 4096MiB of memory, then we will have …

repair: Adjust parallelism according to memory size

---

tests/cql_query_test.cc
tests/like_matcher_test.cc
utils/like_matcher.cc

Match SQL's LIKE in allowing an empty pattern, which matches only an empty text field.

cql3: Handle empty LIKE pattern

---

api/api-doc/storage_service.json
api/storage_service.cc
sstables/compress.cc
sstables/compress.hh
sstables/sstables.hh

Refs #4726
Implement the api portion of a "describe sstables" command. 
Adds rest types for collecting both fixed and dynamic attributes, some grouped. Allows extensions to add attributes as well. (Hint hint)
v2:
* Use (not really legal) nested "type" in json
* Rename "table" param to "cf" for consistency
* Some comments on data sizes
* Stream result to avoid huge string allocations on final json

Implement `sstable_info` API command (info on sstables)

---

mutation_reader.cc
position_in_partition.hh
query-request.hh
query.cc
tests/flat_mutation_reader_assertions.hh
tests/mutation_reader_test.cc
tests/mutation_source_test.cc

Make the reader recreation logic more robust, by moving away from deciding which fragments have to be dropped based on a bunch of special cases, instead replacing this with a general logic which just drops all already seen fragments (based on their position).
Special handling is added for the case when the last position is a range tombstone with a non full prefix starting position.
Reproducer unit tests are added for both cases.
Refs: #4695
Fixes: #4733

Multishard combining reader more robust reader recreation

---

dist/docker/redhat/etc/supervisord.conf.d/scylla-housekeeping.conf
dist/docker/redhat/etc/supervisord.conf.d/scylla-jmx.conf
dist/docker/redhat/etc/supervisord.conf.d/scylla-server.conf
distributed_loader.cc

Commit e3f7fe44c04006bfe601713dde97a0bd1436d499 added file owner validation to prevent Scylla from crashing when it tries to touch a file it doesn't own. However, under docker, we cannot expect to pass this check since user IDs are from different namespaces: the process runs in a container namespace, but the data files usually come from a mounted volume, and so their uids are from the host namespace.
So we need to relax the check. We do this by reverting b1226fb15a5a8f0ac4d37733df3c5ba12d84644c, which causes Scylla to run as euid 0 in docker, and by special-casing euid 0 in the ownership verification step.
Fixes #4823.

docker: relax permission checks

---

.github/PULL_REQUEST_TEMPLATE.md

Since we do accept pull requests (in a long-running experiment), the
pull request template suggesting not to use them is inaccurate, and
many requesters forget to remove the boilerplace.
Remove the outdate template.

github: remove github pull request template

---

database.hh
db/view/view_update_generator.cc
table.cc

Streamed view updates parasitized on writing io priority, which is
reserved for user writes - it's now properly bound to streaming
write priority.
Verified manually by checking appropriate io metrics: `scylla_io_queue_total_bytes{class="streaming_write" ...} vs scylla_io_queue_total_bytes{class="query" ...}`

database: assign proper io priority for streaming view updates

---

dist/debian/rules.mustache
install.sh
scripts/create-relocatable-package.py

Our current relocation works by invoking the dynamic linker with the
executable as an argument. This confuses gdb since the kernel records
the dynamic linker as the executable, not the real executable.
Switch to install-time relocation with patchelf: when installing the
executable and libraries, all paths are known, and we can update the
path to the dynamic loader and to the dynamic libraries.
Since patchelf itself is dynamically linked, we have to relocate it
dynamically (with the old method of invoking it via the dynamic linker).
This is okay since it's a one-time operation and since we don't expect
to debug core dumps of patchelf crashes.
We lose the ability to run scylla directly from the uninstalled
tarball, but since the nonroot installer is already moving in the
direction of …

relocatable: switch from run-time relocation to install-time relocation

---

dht/boot_strapper.cc
dht/boot_strapper.hh
dht/range_streamer.cc
dht/range_streamer.hh
init.cc
init.hh
main.cc
service/storage_service.cc
service/storage_service.hh
tests/cql_test_env.cc
tests/gossip.cc
tests/gossip_test.cc
tests/test_services.cc

In b19792405faee91e, we changed the shutdown process not to rely on the global reactor-defined exit, but instead added a local variable to hold the shutdown state. However, we did not propagate that state everywhere, and now streaming processes are not able to abort.
Fix that by enhancing stop_signal with a sharded<abort_source> member that can be propagated to services. Propagate it to storage_service and thence to boot_strapper and range_streamer so that streaming processes can be aborted.
Fixes #4674
Fixes #4501 
Tests: unit (dev), manual bootstrap test

Handle termination signals during streaming

---

tests/cql_query_test.cc

Follow-up to #4610, where a [review comment](https://github.com/scylladb/scylla/pull/4610#pullrequestreview-255590129) asked for test coverage on all types.  Existing tests cover all the types admissible in LIKE, while this PR adds coverage for all inadmissible types.

Add LIKE test cases for all non-string types

---

configure.py

Currently, seastar is built in seastar/build/{mode}. This means we have two build
directories: build/{mode} and seastar/build/{mode}.
This patch changes that to have only a single build directory (build/{mode}). It
does that by calling Seastar's cmake directly instead of through Seastar's
./configure.py.  However, to support dpdk, if that is enabled it calls cmake
through Seastar's ./cooking.sh (similar to what Seastar's ./configure.py does).
All ./configure.py flags are translated to cmake variables, in the same way that
Seastar does.
Contains fix from Rafael to pass the flags for the correct mode.

build: build seastar in build directory

---

service/storage_proxy.cc

The loop over view update handlers used a guard in order to ensure
that the object is not prematurely destroyed (thus invalidating
the iterator), but the guard itself was not in the right scope.
Fixed by replacinga 'for' loop with a 'while' loop, which moves
the iterator incrementation inside the scope in which it's still
guarded and valid.
Fixes #4866

storage_proxy: fix iterator liveness issue in on_down

---

api/column_family.cc

This Patch adds an implementation of the get build index API and remove a
FIXME.
The API returns a list of secondary indexes belongs to a column family.
Example:
CREATE KEYSPACE scylla_demo WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};
CREATE TABLE scylla_demo.mytableID (     uid uuid,     text text,     time timeuuid,     PRIMARY KEY (uid, time) );
CREATE index on scylla_demo.mytableID (time);
$ curl -X GET 'http://localhost:10000/column_family/built_indexes/scylla_demo%3Amytableid'
["mytableid_time_idx"]

API:column_family.cc Add get_build_index implmentation

---

dist/common/scripts/scylla_prepare
main.cc

To prevent termination with SIGILL, tighten the instruction set support checks. First, check for CLMUL too. Second, add a check in `scylla_prepare` to catch the problem early.
Fixes #4921.

Improve cpu instruction set support checks

---

transport/server.cc

During CQL request processing, a gate is used to ensure that
the connection is not shut down until all ongoing requests
are done. However, the gate might have been left too early
if the database was not ready to respond immediately - which
could result in trying to respond to an already closed connection
later. This issue is solved by postponing leaving the gate
until the continuation chain that handles the request is finished.
Refs #4808

transport: wait for the connections to finish when stopping

---

types.cc
types.hh
types/collection.hh
types/map.hh

This avoids a double dispatch on _kind and also removes a few shared_ptr copies.
The extra work was a small regression from the recent types refactoring.

Optimize type find

---

db/config.cc
db/config.hh
flat_mutation_reader.cc
flat_mutation_reader.hh
mutation_fragment.hh
position_in_partition.hh
sstables/compaction.cc
sstables/sstables.cc
tests/flat_mutation_reader_test.cc

Introduce `mutation_fragment_stream_validator` class and use it as a Filter to `flat_mutation_reader::consume_in_thread` from `sstable::write_components` to validate partition region and optionally clustering key monotonicity.
Fixes #4803

Validate position in partition monotonicity

---

sstables/sstables.cc

There is no reason to keep the Scylla Metadata component in memory
after it is read, parsed, and its information fed into the SSTable.
We have seen systems in which the Scylla metadata component is one
of the heaviest memory users, more than the Summary and Filter.
The run identifier is trivially small, so are the feature bits. The
shard information is stored post-parsed once we call
compute_shards_for_this_sstable().
This patch proposes to just get rid of the metadata component copy
in memory altogether once all of that information is already read.
Tests: unit (release), + manual scylla write load + reshard.
Signed-off-by: Glauber Costa <glauber@scylladb.com>

do not keep the scylla metadata in memory

---

cql3/statements/alter_keyspace_statement.cc
cql3/statements/create_keyspace_statement.cc
cql3/statements/ks_prop_defs.cc
cql3/statements/ks_prop_defs.hh
tests/cql_query_test.cc

If the user supplies the 'replication_factor' to the 'NetworkTopologyStrategy' class,
it will expand into a replication factor for each existing DC for their convenience.
Resolves #4210.

Auto-expand replication_factor for NetworkTopologyStrategy

---

scripts/create-relocatable-package.py

gdb searches for libthread_db.so using its canonical name of libthread_db.so.1 rather
than the file name of libthread_db-1.0.so, so use that name to store the file in the
archive.
Fixes #4996.

build: adjust libthread_db file name to match gdb expectations

---

database.cc

Scylla currently crashes if we run manual operations like nodetool
compact with the controller disabled. While we neither like nor
recommend running with the controller disabled, due to some corner cases
in the controller algorithm we are not yet at the point in which we can
deprecate this and are sometimes forced to disable it.
The reason for the crash is that manual operations will invoke
_backlog_of_shares, which returns what is the backlog needed to
create a certain number of shares. That scan the existing control
points, but when we run without the controller there are no control
points and we crash.
Backlog doesn't matter if the controller is disabled, and the return
value of this function will be immaterial in this case. So to avoid the
crash, we return something right away if the …

do not crash in user-defined operations if the controller is disabled

---

reloc/build_reloc.sh

The build directory is meaningless, since it is typically some
directory in a continuous integration server. That means someone
debugging the relocatable package needs to issue the gdb command
'set substitute-path' with the correct arguments, or they lose
source debugging. Doing so in the relocatable package build saves
this step.
The default build is not modified, since a typical local build
benefits from having the paths hardcoded, as the debugger will
find the sources automatically.

relocatable: erase build directory from executable and debug info

---

sstables/compaction_manager.hh

Make it easier for the IDE to resolve references to the seastar
namespace. In any case include files should be stand-alone and not
depend on previously included files.

sstables: compaction_manager: #include seastarx.hh

---

configure.py
tests/managed_vector_test.cc
utils/logalloc.hh

We observed an abort on bad_alloc which was not caused by real OOM,
but could be explained by cache region being locked from a different
shard, which is not allowed, concurrently with memory reclamation.
It's impossible now to prove this, or, if that was indeed the case, to
determine which code path was attempting such lock. This patch adds an
assert which would catch such incorrect locking at the attempt.
Refs #4978
Tests:
- unit (dev, release, debug)

lsa: Assert no cross-shard region locking

---

gms/gossiper.cc
gms/gossiper.hh

- Update the outdated comments in do_stop_gossiping. It was
storage_service not storage_proxy that used the lock. More
importantly, storage_service does not use it any more.
- Drop the unused timer_callback_lock and timer_callback_unlock API
- Use with_semaphore to make sure the semaphore usage is balanced.
- Add log in gossiper::do_stop_gossiping when it tries to take the
semaphore to help debug hang during the shutdown.
Refs: #4891
Refs: #4971

gossiper: Improve the gossip timer callback lock handling

---

mutation_partition.cc
mutation_partition.hh
partition_version.cc
tests/mutation_source_test.cc

Currently affects only counter tables.
Introduced in 27014a2.
mutation_partition(s, mp) is incorrect because it uses s to interpret
mp, while it should use mp_schema.
We may hit this if the current node has a newer schema than the
incoming mutation. This can happen during table schema altering when we receive the
mutation from a node which hasn't processed the schema change yet.
This is undefined behavior in general. If the alter was adding or
removing columns, this may result in corruption of the write where
values of one column are inserted into a different column.
Fixes #5095.

mvcc: Fix incorrect schema version being used to copy the mutation when applying

---

cql3/cql3_type.cc
cql3/cql3_type.hh
cql3/statements/alter_type_statement.cc
db/cql_type_parser.cc
db/schema_tables.cc
tests/schema_change_test.cc
types/user.hh

When a user type changes we were not recreating other uses types that use it. This patch series fixes that and makes it clear which code is responsible for it.

recreate dependent user types

---

db/schema_tables.cc
db/system_keyspace.cc
message/messaging_service.cc
message/messaging_service.hh
multishard_mutation_query.cc
multishard_mutation_query.hh
service/migration_manager.cc
service/storage_proxy.cc
service/storage_proxy.hh
tests/multishard_mutation_query_test.cc

Since variadic future<> is deprecated, switch to rpc::tuple for multiple
return values in rpc calls. This is more or less mechanical translation.

messaging_service: use rpc::tuple instead of variadic futures for rpc

---

db/data_listeners.cc
db/data_listeners.hh
schema_registry.cc
schema_registry.hh
tests/database_test.cc

When the toppartitions operation gathers results, it copies partition
keys with their schema_ptr:s. When these schema_ptr:s are copies
or destroyed, they can cause leaks or premature frees of the schema
in its original shard since reference count operations in are not atomic.
Fix that by converting the schema_ptr to a global_schema_ptr during
transportation.
Fixes #5104 (direct bug)
Fixes #5018 (schema prematurely freed, toppartitions previously executed on that node)
Fixes #4973 (corrupted memory pool of the same size class as schema, toppartitions previously executed on that node)
Tests: new test added that fails with the existing code in debug mode, manual toppartitions test

toppartitions: don't transport schema_ptr across shards

---

.gitignore

Add .pytest_cache and expressions.tokens to the top-level .gitignore.
@psarna @nyh

alternator: Add build byproducts to .gitignore

---

tools/toolchain/README.md

`dbuild` was recently (24c732057) updated to run in interactive mode
when given no arguments; we can now update the README to mention that.

dbuild: Update README on interactive mode

---

service/storage_proxy.cc
service/storage_proxy.hh

Seastar variadic futures are deprecated, so replace with structs to avoid nasty deprecation warnings.

storage_proxy: replace variadic futures with structs

---

streaming/stream_transfer_task.cc

We can use the reader::peek() to check if the reader contains any data.
If not, do not open the rpc stream connection. It helps to reduce the
port usage.
Refs: #4943

streaming:  Do not open rpc stream connection if reader has no data

---

database.cc
database.hh

Schema changes can have big effects on performance, typically it should
be a rare event.
It is useful to monitor how frequently the schema changes.
This patch adds a counter that increases each time a schema changes.
After this patch the metrics would look like:
```
scylla_database_schema_changed{shard="0",type="derive"} 2
```
Fixes #4785

database: Add counter for the number of schema changes

---

tests/random_schema.cc
tests/random_schema.hh

Allow returning fewer random clustering keys than requested since
the schema may limit the total number we can generate, for example,
if there is only one boolean clustering column.
Fixes #5161
1000 runs of mutation_test in release mode.

test: random_schema::make_ckeys: fix inifinte loop

---

gms/gossiper.cc
gms/gossiper.hh

Assume n1 and n2 in a cluster with generation number g1, g2. The
cluster runs for more than 1 year (MAX_GENERATION_DIFFERENCE). When n1
reboots with generation g1' which is time based, n2 will see
g1' > g2 + MAX_GENERATION_DIFFERENCE and reject n1's gossip update.
To fix, check the generation drift with generation value this node would
get if this node were restarted.
This is a backport of CASSANDRA-10969.
Fixes #5164

gossip: Fix max generation drift measure

---

db/system_keyspace.cc
db/system_keyspace.hh
dht/boot_strapper.cc
locator/token_metadata.cc
locator/token_metadata.hh
service/storage_service.cc
service/storage_service.hh

The node startup code (in particular the functions storage_service::prepare_to_join and storage_service::join_token_ring) is complicated and hard to understand.
This patch set aims to simplify it at least a bit by removing some dead code, moving code around so it's easier to understand and adding some comments that explain what the code does.
I did it to help me prepare for implementing generation and gossiping of CDC streams.
The decisions I made are pretty subjective, I won't be surprised if anyone disagrees. I hope we can agree on something at least.
Please review carefully.

Some refactoring of node startup code.

---

api/storage_service.cc
service/storage_service.cc
service/storage_service.hh

From Shlomi:
4 node cluster Node A, B, C, D (Node A: seed)
cassandra-stress write n=10000000 -pop seq=1..10000000 -node <seed-node>
cassandra-stress read duration=10h -pop seq=1..10000000 -node <seed-node>
while read is progressing
Node D: nodetool decommission
Node A: nodetool status node - wait for UL
Node A: nodetool cleanup (while decommission progresses)
I get the error on c-s once decommission ends
java.io.IOException: Operation x0 on key(s) [383633374d31504b5030]: Data returned was not validated
The problem is when a node gets new ranges, e.g, the bootstrapping node, the
existing nodes after a node is removed or decommissioned, nodetool cleanup will
remove data within the new ranges which the node just gets from other nodes.
To fix, we should reject the nodetool cleanup when there …

storage_service: Reject nodetool cleanup when there is pending ranges

---

db/config.cc
db/config.hh
gc_clock.hh
main.cc
serializer.hh

Commit 93270dd8e04e3caf0e7586311badbaf121c14d3f changed gc_clock to be 64-bit, to fix the Y2038 problem. While 64-bit tombstone::deletion_time is serialized in a compatible way, TTLs (gc_clock::duration) were not.
This patchset reverts TTL serialization to the 32-bit serialization format, and also allows opting-in to the 64-bit format in case a cluster was installed with the broken code. Only Scylla 3.1.0 is vulnerable.
Fixes #4855 

Fix TTL serialization breakage

---

tests/mutation_test.cc

mutation_test/test_udt_mutations kept failing on my machine and I tracked it down to the 3rd patch in this series (use int64_t constants for long_type).  While at it, this series also fixes a comment and the end iterator in `BOOST_REQUIRE(std::all_of(...))`
mutation_test: test_udt_mutations: fixup udt comment
mutation_test: test_udt_mutations: fix end iterator in call to std::all_of
mutation_test: test_udt_mutations: use int64_t constants for long_type
Test: mutation_test(dev, debug)

test_udt_mutations fixes

---

cdc/cdc.cc
cdc/cdc.hh
cql3/untyped_result_set.cc
cql3/untyped_result_set.hh
tests/cdc_test.cc
tests/cql_assertions.cc
tests/cql_assertions.hh

This PR is a clone of #5217 with debug tests fixed. 
Adds delta and pre-image data column writes for the atomic columns in a cdc-enabled table.
Note that in this patch set it is still unconditional. Adding option support comes in next set.
Uses code more or less derived from alternator to select pre-image, using raw query interface. So should be fairly low overhead to query generation. Pre-image and delta mutations are mixed in with the actual modification mutations to generate the full cdc log (sans post-image).
Rebased on lastest master as of 2019-10-28.

CDC (atomic) delta + (non-optional) pre-image data columns

---

db/commitlog/commitlog.cc
db/commitlog/commitlog.hh
db/commitlog/commitlog_replayer.cc
db/hints/manager.cc
tests/commitlog_test.cc

Since seastar::streams are based on future/promise, variadic streams
suffer the same fate as variadic futures - deprecation and eventual
removal.
This patch therefore replaces a variadic stream in commitlog::read_log_file()
with a non-variadic stream, via a helper struct.

commitlog: change variadic stream in read_log_file to future<struct>

---

tools/scyllatop/dumptostdout.py
tools/scyllatop/fake.py
tools/scyllatop/livedata.py
tools/scyllatop/metric.py
tools/scyllatop/scyllatop.py
tools/scyllatop/views/stdout.py

Update previous results dictionary using the update_metrics method.
It calls metric_source.query_list to get a list of results (similar to discover()) then for each line in the response it updates results dictionary.
New results may be appeneded depending on the do_append parameter (True by default).
Previously, with prometheous, each metric.update called query_list resulting in O(n^2) when all metric were updated, like in the scylla_top dtest - causing test timeout when testing debug build.
(E.g. [dtest-debug/216/testReport/scyllatop_test/TestScyllaTop/default_start_test/](http://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/216/testReport/scyllatop_test/TestScyllaTop/default_start_test/))

Scyllatop: one pass update of multiple metrics

---

dist/docker/redhat/Dockerfile

This change adds a `SCYLLA_REPO_URL` argument to Dockerfile, which defines the RPM repository used to install Scylla from.
When building a new Docker image, users can specify the argument by passing the `--build-arg SCYLLA_REPO_URL=<url>` option to the `docker build` command. If the argument is not specified, the same RPM repository is used as before, retaining the old default behavior.
We intend to use this in release engineering infrastructure to specify RPM repositories for nightly  builds of release branches (for example, 3.1.x), which are currently only using the stable RPMs.

dist/docker: Add SCYLLA_REPO_URL argument to Dockerfile

---

cql3/functions/aggregate_fcts.hh
cql3/functions/functions.cc
tests/cql_assertions.cc
tests/cql_assertions.hh
tests/cql_query_test.cc
types.hh

Adds missing overloads of functions `count`, `min`, `max` for type `ascii`.
Now they work:
```
cqlsh> CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
cqlsh> USE ks;
cqlsh:ks> CREATE TABLE test_ascii (id int PRIMARY KEY, value ascii);
cqlsh:ks> INSERT INTO test_ascii (id, value) VALUES (0, 'abcd');
cqlsh:ks> INSERT INTO test_ascii (id, value) VALUES (1, 'efgh');
cqlsh:ks> INSERT INTO test_ascii (id, value) VALUES (2, 'ijkl');
cqlsh:ks> SELECT * FROM test_ascii;
id | value
----+-------
1 |  efgh
0 |  abcd
2 |  ijkl
(3 rows)
cqlsh:ks> SELECT count(value) FROM test_ascii;
system.count(value)
---------------------
3
(1 rows)
cqlsh:ks> SELECT min(value) FROM test_ascii;
system.min(value)
-------------------
abcd
(1 rows)
cqlsh:ks> SELECT max(value) …
```

cql3/functions: add missing min/max/count functions for ascii type

---

api/column_family.cc
api/column_family.hh
api/storage_service.cc
canonical_mutation.cc
database.cc
database.hh
memtable.cc
memtable.hh
mutation.cc
mutation_cleaner.hh
mutation_partition.cc
mutation_partition.hh
partition_version.cc
partition_version.hh
row_cache.cc
row_cache.hh
service/storage_proxy.cc
table.cc
tests/counter_test.cc
tests/flat_mutation_reader_test.cc
tests/frozen_mutation_test.cc
tests/memtable_test.cc
tests/mutation_test.cc
tests/mvcc_test.cc
tests/perf/perf_idl.cc
tests/row_cache_test.cc

Fixes issue: #3912
Adds four new per-table metrics for counting writes performed on memtables:
- `memtable_partition_writes` - number of write operations performed on partitions in memtables,
- `memtable_partition_hits` - number of write operations performed on partitions that previously existed in a memtable,
- `memtable_row_writes` - number of row write operations performed in memtables,
- `memtable_row_hits` - number of row write operations that overwrote rows previously present in a memtable.

Partition/row hit/miss counters for memtable write operations

---

cql3/statements/update_statement.cc
cql3/user_types.cc
cql3/user_types.hh
tests/json_cql_query_test.cc

When using INSERT JSON with frozen collection/UDT columns, if the columns were left unspecified or set to null, the statement would create an empty non-null value for these columns instead of using null values as it should have. For example:
```
cqlsh:b> create table t (k text primary key, l frozen<list<int>>, m frozen<map<int, int>>, s frozen<set<int>>, u frozen<ut>);
cqlsh:b> insert into t JSON '{"k": "insert_json"}';
cqlsh:b> select * from t;
k                 | l    | m    | s    | u
-------------------+------+------+------+------
insert_json |     [] |     {} |     {} |        
```
This PR fixes this.
Resolves #5246 and closes #5270.

Correctly handle null/unset frozen collection/UDT columns in INSERT JSON.

---

table.cc

CQL tracing would only report file I/O involving one sstable, even if
multiple sstables were read from during the query.
Steps to reproduce:
- create a table with NullCompactionStrategy
- insert row, flush memtables
- insert row, flush memtables
- restart Scylla
- tracing on
- select * from table
The trace would only report DMA reads from one of the two sstables.
Kudos to @denesb for catching this.
Related issue: #4908

sstables: fix sstable file I/O CQL tracing when reading multiple files

---

dist/docker/redhat/Dockerfile

Modify Dockerfile SCYLLA_REPO_URL argument to point to the 3.2 repository.

dist/docker: Switch to 3.2 release repository

---

gms/gossiper.cc
gms/gossiper.hh

In a cross-dc large cluster, the receiver node of the gossip SYN message
might be slow to send the gossip ACK message. The ack messages can be
large if the payload of the application state is big, e.g.,
CACHE_HITRATES with a lot of tables. As a result, the unlimited ACK
message can consume unlimited amount of memory which causes OOM
eventually.
To fix, this patch queues the SYN message and handles it later if the
previous ACK message is still being sent. However, we only store the
latest SYN message. Since the latest SYN message from peer has the
latest information, so it is safe to drop the previous SYN message and
keep the latest one only. After this patch, there can be at most 1
pending SYN message and 1 pending ACK message per peer node.

gossip: Limit number of pending gossip ACK and ACK2 messages

---

mutation_partition.cc
mutation_partition.hh
tests/mutation_test.cc

This change corrects condition on which a row was considered expired by its TTL.
The logic that decides when a row becomes expired was inconsistent with the logic that decides if a single cell is expired. A single cell becomes expired when `expiry_timestamp <= now`, while a row became expired when `expiry_timestamp < now` (notice the strict inequality). For rows inserted with TTL, this caused non-key cells to expire (change their values to null) one second before the row disappeared. Now, row expiry logic uses non-strict inequality.
Fixes: #4263, #5290.
Tests:
- unit(dev)
- python test described in issue #5290

row_marker: correct row expiry condition

---

scylla-gdb.py

Fixes #5277
Tests: (gdb) scylla active sstables
In v3:
- Defined _lookup_obj helper to simplify cache lookup
In v2:
- Simplified construction of `types` list of dicts
- Added break after yielding result
- Added a cache for resolved vtable_addr

scylla-gdb: active sstables: support k_l/mc sstable readers

---

dist/redhat/build_rpm.sh
dist/redhat/python3/build_rpm.sh
dist/redhat/scylla.spec.mustache
install-dependencies.sh
tools/toolchain/Dockerfile
tools/toolchain/image

This is a minor update as gcc and boost versions did not change. A noteable update is patchelf 0.10, which adds support to large binaries.
A few minor issues exposed by the update are fixed in preparatory patches.

toolchain: update to Fedora 31

---

cdc/cdc.cc
tests/cdc_test.cc

Users should be able to decide whether they need preimage or not. There is already an option for that but it's not respected by the implementation. This PR adds support for this functionality.
Tests: unit(dev).

Return preimage from CDC only when it's enabled

---

dist/common/scripts/scylla_util.py

Currently scylla_io_setup will skip in scylla_setup, because we didn't support
those new instance types.
I manually executed scylla_io_setup, and the scylla-server started and worked
well.
Let's apply this patch first, then check if there is some new problem in
ami-test.
Fixes: https://github.com/scylladb/scylla/issues/5312
@syuu1228 @avikivity

support new aws instance types: c5d, m5d, m5ad, r5d, z1d

---

configure.py
thrift/handler.cc
thrift/server.cc
thrift/server.hh

I'd like to backport #4538 to 3.1 please :+1: 
Tested OK here.

thrift: backport thrift >= 0.11 support from #4538 to 3.1

---

conf/scylla.yaml

These unsupported options do nothing except to confuse users who
try to tune them.
Options removed:
hinted_handoff_throttle_in_kb
max_hints_delivery_threads
batchlog_replay_throttle_in_kb
key_cache_size_in_mb
key_cache_save_period
key_cache_keys_to_save
row_cache_size_in_mb
row_cache_save_period
row_cache_keys_to_save
counter_cache_size_in_mb
counter_cache_save_period
counter_cache_keys_to_save
memory_allocator
saved_caches_directory
concurrent_reads
concurrent_writes
concurrent_counter_writes
file_cache_size_in_mb
index_summary_capacity_in_mb
index_summary_resize_interval_in_minutes
trickle_fsync
trickle_fsync_interval_in_kb
internode_authenticator
native_transport_max_threads
native_transport_max_concurrent_connections
native_transport_max_concurrent_connections_per_ip
rpc_server_type …

conf: remove unsupported options from scylla.yaml

---

tools/toolchain/dbuild

Docker on Fedora 31 is flakey, and is not supported at all on RHEL 8. Podman is a drop-in replacement for docker; this series adds support for using podman in dbuild.
Apart from actually working on Fedora 31 hosts, podman is nicer in being more secure and not requiring a daemon.
Fixes #5332.

tools: toolchain: support podman as a replacement to docker

---

dist/common/scripts/scylla_util.py

The default values of data_file_directories and commitlog_directory were
commented by commit e0f40ed16aa. It causes scylla_util.py:get_scylla_dirs() to
fail in checking the values.
This patch changed get_scylla_dirs() to return default data/commitlog
directories if they aren't set.
/CC @xemul @vladzcloudius

scylla_util: get_scylla_dirs: return default data/commitlog directories if they aren't set

---

cql3/functions/aggregate_fcts.hh
cql3/functions/functions.cc
tests/cql_query_test.cc

This is a partial solution to #5139 (only for two types) because of the above and because collections are much harder to do. They are coming in a separate PR.
What this PR does is simple: adds `system.min()` and `system.max()` fns for `time_type` and `inet_address`, so 'overload resolution' does not use `blob->blob` overload, which caused results to be printed as blobs.

5139 minmax bad printing

---

tracing/tracing.cc
tracing/tracing.hh

Fixes #5243
cql_tracing_test:TestCqlTracing.tracing_shutdown_test hits the following assert:
scylla: /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/sharded.hh:712: Service& seastar::sharded<T>::local() [with Service = tracing::tracing]: Assertion `local_is_initialized()' failed.
Similar to trace_state keep shared_ptr<tracing> _local_tracing_ptr
in one_session_records when constructed so it can be used
during shutdown.
Test: unit(dev), cql_tracing_test:TestCqlTracing.tracing_shutdown_test (dev)

tracing: one_session_records: keep local tracing ptr

---

dist/common/scripts/scylla_blocktune.py
dist/common/scripts/scylla_fstrim
dist/common/scripts/scylla_io_setup
dist/common/scripts/scylla_util.py

Fixed two problem in scylla_io_setup
- Problem 1: paths of default directories is invalid, introduced by commit 5ec191536e  /CC @bhalevy 
- Problem 2: wrong path join, introduced by commit 31ddb2145a /CC @syuu1228 
scylla_io_setup, scylla_fstrim and scylla_blocktune.py:
- Fixed default scylla directories when they aren't assigned in scylla.yaml

fix scylla setup of processing default scylla directories

---

configure.py
redis-test/test_strings.py
redis/command_factory.cc
redis/commands/echo.cc
redis/commands/echo.hh

This patch implemented echo command, which return the string back to client.
Reference:
- https://redis.io/commands/echo
/CC @fastio @nyh

redis: implement echo command

---

docs/maintainer.md

This is a list of recipes used by maintainers to maintain
scylla.git.

docs: add maintainer's handbook

---

redis-test/test_raw_cmd.py
redis/protocol_parser.rl
redis/server.cc

When I test the redis cmd by echo and nc, there is a redundant error in the end.
I checked by strace, currently if client read nothing from stdin, it will
shutdown the socket, redis server will read nothing (0 byte) from socket. But
it tries to process the empty command and returns an error.
$ echo -n -e '*1\r\n$4\r\nping\r\n' |strace nc localhost 6379
| ...
|    read(0, "*1\r\n$4\r\nping\r\n", 8192)   = 14
|    select(5, [4], [4], [], NULL)           = 1 (out [4])
|>>> sendto(4, "*1\r\n$4\r\nping\r\n", 14, 0, NULL, 0) = 14
|    select(5, [0 4], [], [], NULL)          = 1 (in [0])
|    recvfrom(0, 0x7ffe4d5b6c70, 8192, 0, 0x7ffe4d5b6bf0, 0x7ffe4d5b6bec) = -1 ENOTSOCK (Socket operation on non-socket)
|    read(0, "", 8192)                       = 0
|>>> shutdown(4, SHUT_WR) …

redis: skip processing request of EOF

---

dist/docker/redhat/scyllasetup.py

Use default data_file_directories if it's not assigned in scylla.yaml
Docker test of scylla master failed, this PR fixed that.
https://jenkins.scylladb.com/job/scylla-master/job/docker-test/label=muninn/82/console
Test: built a new image, and tested locally
/CC @penberg

scylla-docker: fix default data_directories in scyllasetup.py

---

docs/maintainer.md

Just one lease, not many.
Reported by Piotr Sarna.

docs: maintainers.md: fix typo in git push --force-with-lease

---

table.cc
tests/cql_query_test.cc

In several cases in distributed testing (dtest) we trigger compaction using nodetool compact assuming that when it is done, it is indeed really done.
However, the way compaction is currently implemented in scylla, it may leave behind some background tasks to delete the old sstables that were compacted.
This commit changes major compaction (triggered via the ss::force_keyspace_compaction api) so it would wait on the background deletes and will return only when they finish.
Fixes #4909
Tests: unit(dev), nodetool_refresh_with_data_perms_test, test_nodetool_snapshot_during_major_compaction

Let compaction wait on background deletions

---

scylla-gdb.py

Currently, 'scylla thread' uses arch_prctl() to extract the value of
fsbase, used to reference thread local variables. gdb 8 added support
for directly accessing the value as $fs_base, so use that instead. This
works from core dumps as well as live processes, as you don't need to
execute inferior functions.
The patch is required for debugging threads in core dumps, but not
sufficient, as we still need to set $rip and $rsp, and gdb still[1]
doesn't allow this.
[1] https://sourceware.org/bugzilla/show_bug.cgi?id=9370

gdb: change 'scylla thread' command to access fs_base register directly

---

database.cc

On aarch64, asan detected a use-after-move. It doesn't happen on x86_64,
likely due to different argument evaluation order.
Fix by evaluating full_slice before moving the schema.
Note: I used "auto&&" and "std::move()" even though full_slice()
returns a reference. I think this is safer in case full_slice()
changes, and works just as well with a reference.
Fixes #5419.

database: fix schema use-after-move in make_multishard_streaming_reader

---

db/config.cc
db/config.hh
docs/redis/redis.md
main.cc
redis-test/test_strings.py
redis/commands/del.cc
redis/commands/del.hh
redis/commands/get.cc
redis/exceptions.hh
redis/keyspace_utils.cc
redis/mutation_utils.cc
redis/mutation_utils.hh
redis/reply.hh
redis/server.cc
redis/service.cc

* Rename the options related to Redis API, and describe them clearly.
* Rename `redis_transport_port` to `redis_port`
* Rename `redis_transport_port_ssl` to `redis_ssl_port`
* Rename `redis_default_database_count` to  `redis_database_count`
* Remove unnecessary option `enable_redis_protocol`
* Modify the default value of opition `redis_read_consistency_level` and `redis_write_consistency_level` to `LOCAL_QUORUM`
* Fix the DEL command: support to delete mutilple keys in one command.
* Fix the GET command: return the empty string when the required key is not exists.
* Fix the redis-test/test_del_non_existent_key: mark xfail.

Redis：fix the options related to Redis API, fix the DEL and GET command

---

database.cc
db/commitlog/commitlog.cc
dirty_memory_manager.hh
reader_concurrency_semaphore.cc
reader_concurrency_semaphore.hh
tests/logalloc_test.cc
tests/mutation_reader_test.cc
utils/logalloc.cc
utils/logalloc.hh

Selected semaphores' names are now included in exception messages in case of timeout or when admission queue overflows.
Resolves #5281

Named semaphores in concurrency reader, segment_manager and region_group 

---

db/hints/manager.cc
message/messaging_service.cc
message/messaging_service.hh
service/storage_proxy.cc
service/storage_proxy.hh
service/storage_service.cc
service/storage_service.hh

Introduce a new verb dedicated for receiving and sending hints: `HINT_MUTATION`. It is handled on the streaming connection, which is separate from the one used for handling mutations sent by coordinator during a write.
The intent of using a separate connection is to increase fairness while handling hints and user requests - this way, a situation can be avoided in which one type of requests saturate the connection, negatively impacting the other one.
Information about new RPC support is propagated through new gossip feature `HINTED_HANDOFF_SEPARATE_CONNECTION`.
Fixes #4974.
Tests: unit(release)

hinted handoff: handle hints on separate connection and scheduling group

---

docs/maintainer.md

If you merge a pull request that contains multiple patches via
the github interface, it will document itself as the committer.
Work around this brain damage by using the command line.

docs: maintainer.md: use command line to merge multi-commit pull requests

---

dist/common/sysctl.d/99-scylla-vm.conf
dist/debian/debian/scylla-kernel-conf.postinst
dist/redhat/scylla.spec.mustache

The vm.swappiness sysctl controls the kernel's prefernce for swapping
anonymous memory vs page cache. Since Scylla uses very large amounts
of anonymous memory, and tiny amounts of page cache, the correct setting
is to prefer swapping page cache. If the kernel swaps anonymous memory
the reactor will stall until the page fault is satisfied. On the other
hand, page cache pages usually belong to other applications, usually
backup processes that read Scylla files.
This setting has been used in production in Scylla Cloud for a while
with good results.
Users can opt out by not installing the scylla-kernel-conf package
(same as with the other kernel tunables).

sysctl: reduce kernel tendency to swap anonymous pages relative to page cache

---

conf/scylla.yaml
configure.py
cql3/statements/function_statement.cc
db/config.cc
db/config.hh
service/storage_proxy.cc
service/storage_service.cc
test.py
tests/config_test.cc
tests/cql_test_env.cc
tests/enum_option_test.cc
tests/schema_change_test.cc
tests/user_function_test.cc
utils/enum_option.hh

Add `--experimental-features` -- a vector of features to unlock.  Make corresponding changes in the YAML parser.
Fixes #5338

RFC: Add `experimental_features` option

---

dist/common/scripts/scylla_prepare
dist/common/scripts/scylla_setup
dist/common/scripts/scylla_sysconfig_setup
dist/common/scripts/scylla_util.py

A Linux machine typically has multiple clocksources with distinct
performances. Setting a high-performant clocksource might result in
better performance for ScyllaDB, so this should be considered whenever
starting it up.
This patch introduces the possibility of enforcing optimized Linux
clocksource to Scylla's setup/start-up processes. It does so by adding
an interactive question about enforcing clocksource setting to scylla_setup,
which modifies the parameter "CLOCKSOURCE" in scylla_server configuration
file. This parameter is read by perftune.py which, if set to "yes", proceeds
to (non persistently) setting the clocksource. On x86, TSC clocksource is used.
Fixes #4474

Adding functionality to enforce optimal Linux clocksource setting.

---

api/api-doc/cache_service.json
api/api-doc/column_family.json
api/api-doc/compaction_manager.json
api/api-doc/failure_detector.json
api/api-doc/gossiper.json
api/api-doc/hinted_handoff.json
api/api-doc/messaging_service.json
api/api-doc/storage_proxy.json
api/api-doc/storage_service.json
api/api-doc/stream_manager.json

In swagger 1.2 int is defined as int32.
We originally used int following the jmx definition, in practice
internally we use uint and int64 in many places.
While the API format the type correctly, an external system that uses
swagger-based code generator can face a type issue problem.
This patch replace all use of int in a return type with long that is defined as int64.
Changing the return type, have no impact on the system, but it does help
external systems that use code generator from swagger.
Fixes #5347

api: replace swagger definition to use long instead of int

---

db/hints/manager.cc

To be used by dtest as an indicator that endpoint's hints
were drained and hints directory is removed.
Refs #5354

hinted handoff: log message after removing hints directory

---

cql3/restrictions/single_column_primary_key_restrictions.hh
tests/cql_query_test.cc

The LIKE operator requires filtering, so needs_filtering() must check is_LIKE().  This already happens for partition columns, but it was overlooked for clustering columns in the initial implementation of LIKE.
Fixes #5400.

cql3: Fix needs_filtering() for clustering columns

---

alternator-test/test_expected.py
alternator/conditions.cc
alternator/executor.cc
alternator/rjson.cc
alternator/rjson.hh
alternator/serialization.cc
alternator/serialization.hh

Checking the EQ relation for alternator attributes is usually performed
simply by comparing underlying JSON objects, but sets (SS, BS, NS types)
need a special routine, as we need to make sure that sets stored in
a different order underneath are still equal, e.g:
```python
[1, 3, 2] == [1, 2, 3]
```
Fixes #5021

alternator: Fix EQ operator for sets

---

alternator-test/test_expected.py
alternator/conditions.cc
alternator/conditions.hh

Add the last missing operators and re-enable their tests.
Fixes #5034.

alternator: Implement CONTAINS and NOT_CONTAINS in Expected

---

redis-test/test_strings.py
redis/keyspace_utils.cc

Currently we always try to create 16 keyspaces for Redis, the config
redis_default_database_count doesn't effect.
SELECT command is supported, it would switch between keyspaces. The limitation
is got from configuration. So if we config redis_default_database_count to be
larger than 16, SELECT allows to switch to unexisting keyspace, and it will
fail in read/write data.
Example:
| # scylla --developer-mode 1 --workdir ./ --enable-redis-protocol 1  --redis-default-database-count 20
| # redis-cli
| 127.0.0.1:6379> select 18
| OK
| 127.0.0.1:6379[18]> set a 1
| (error) ERR Can't find a column family STRINGs in keyspace REDIS_18
| 127.0.0.1:6379[18]> get a
| (error) ERR Can't find a column family STRINGs in keyspace REDIS_18
This patchset fixed the issue and added a test for that.
/CC @fastio

redis: create all redis keyspaces as configured

---

tools/toolchain/dbuild

The is_podman check was depending on `docker -v` printing "podman" in
the output, but that doesn't actually work, since podman prints $0.
Use `docker --help` instead, which will output "podman".
Also return podman's return status, which was previously being
dropped.

dbuild: Fix podman invocation

---

database.hh
db/view/view_update_generator.cc
db/view/view_update_generator.hh
distributed_loader.cc
sstables/sstables.cc
sstables/sstables.hh
table.cc

Fixes #5340
(instead of #5329 that was retracted)
Hold the sstable_deletion_sem table::move_sstables_from_subdirs to serialize access to the staging directory.  It now synchronizes snapshot, compaction deletion of sstables, and view_update_generator moving of sstables from staging.
Tests:
* unit (dev) [expect  test_user_function_timestamp_return that fails for me locally, but also on master]
* snapshot_test.py (dev)

Synchronize snapshot and staging sstable deletion using sem

---

cdc/cdc.cc
cdc/cdc.hh
cdc/cdc_options.hh
cql3/statements/alter_table_statement.cc
cql3/statements/create_table_statement.cc
cql3/statements/create_table_statement.hh
cql3/statements/drop_table_statement.cc
main.cc
schema.hh
service/migration_listener.hh
service/migration_manager.cc
tests/cdc_test.cc
tests/cql_test_env.cc

Moves schema creation/alter/drop awareness to use new "before" callbacks from migration manager, and adds/modifies log and streams table as part of the base table modification. 
Makes schema changes semi-atomic per node. While this does not deal with updates coming in before a schema change has propagated cluster, it now falls into the same pit as when this happens without CDC. 
Added side effect is also that now schemas are transparent across all subsystems, not just cql. 
v2:
Pushed new version addressing the mis-squash for cdc.hh
v3:
Rebased on master
v4:
Added two asserts.
v5:
removed "use namespace seastar" and added include "seastarx.h"
v6: 
removed asserts again (gah), and simplified condition in favour of comment

CDC: handle schema changes

---

dist/common/scripts/scylla_setup
dist/common/scripts/scylla_util.py

These series solves an issue with scylla_setup and prevent it from waiting forever if housekeeping cannot look for the new Scylla version.
Fixes  #5302
It should be backported to versions that support offline installations.

Add a timeout for housekeeping when using scylla with no external connectivity

---

repair/row_level.cc
service/storage_service.hh

Initialize bool members in `row_level_repair` and _storage_service` causing ubsan errors. 
Fixes #5531

Fix row level repair uninitialized member

---

dist/common/scripts/scylla_ntp_setup
dist/common/scripts/scylla_util.py

VERSION_ID of centos7 is "7", but VERSION_ID of oel7.7 is "7.7"
This patch fixed ValueError: invalid literal for int() with base 10: '7.7' 
Fixes #5433 
/CC @syuu1228

scylla_ntp_setup: check redhat variant version by parse_version

---

dist/docker/redhat/scylla-jmx-service.sh

The path should /opt/scylladb/jmx, not /opt/scylladb/scripts/jmx.
Fixes #5542

docker: fix typo of scylla-jmx script path

---

cql3/functions/aggregate_fcts.cc
exceptions/exceptions.hh
test/boost/cql_query_test.cc

Fix overflow handling in sum() and avg().
sum:
- aggregated into __int128
- detect overflow when computing result
- and log a warning if found
avg:
- fix division function to divide the accumulator type _sum (__int128 for integers) by _count
- Add unit tests for both cases
Test:
- manual test against Cassandra 3.11.3 to make sure the results in the scylla unit test agree with it.
- unit(dev), cql_query_test(debug)
Fixes #5536

cql3: detect and handle int overflow in aggregate functions

---

atomic_cell.cc
atomic_cell.hh
canonical_mutation.cc
canonical_mutation.hh
collection_mutation.cc
collection_mutation.hh
database.cc
mutation_partition_view.cc
mutation_partition_view.hh

canonical_mutation objects are used for schema reconciliation, which is a fragile area and thus deserves some debugging help.
This series makes canonical_mutation objects printable. The end result looks something like
```
INFO  2019-12-30 17:00:40,935 [shard 1] migration_manager - received definitions update from 127.0.0.1:62937: {{{canonical_mutation: table_id afddfb9d-bc1e-3068-8056-eed6c302ba09 schema_version c179c1d7-9503-3f66-a5b3-70e72af3392a partition_key pk{00026b73} partition_tombstone {tombstone: none}{row {position: clustered,ckp{0003746162},0} tombstone {row_tombstone: none} marker {row_marker: }, column bloom_filter_fp_chance atomic_cell{0.01;ts=1577718040933619;expiry=-1,ttl=0}, column caching atomic_cell{({keys : ALL}, {rows_per_partition : …
```

Pretty print canonical_mutation objects

---

service/storage_proxy.cc

When counter mutation is about to be sent, a leader is elected. If the leader node fails after election, we get `rpc::closed_error`. That exception propagated high up, causing all client connections to be dropped.
This patch intercepts `rpc::closed_error` in `storage_proxy::mutate_counters` and translates it to `mutation_write_failure_exception` (which is, in turn, translated to response with error code). I assume that hinted handoffs will eventually take over the unsent mutation.
RFC because critical code paths are affected and I'm new to counters.
References #2859

storage_proxy: [RFC] intercept `rpc::closed_error` if counter leader is down

---

gms/gossiper.cc
gms/gossiper.hh
main.cc
test/boost/gossip_test.cc
test/lib/cql_test_env.cc
test/lib/test_services.cc
test/manual/gossip.cc

This change makes most sleeps in gossip.cc abortable. It is now possible to quickly shut down a node during startup, most notably during the phase while it waits for gossip to settle.
Fixes #3749.

gossip: make sleeps react to shutdown signal

---

db/config.cc

Murmur3 is the default partitioner.
ByteOrder and Random are the deprecated ones
and should be mentioned in the description.
Signed-off-by: Piotr Jastrzebski <piotr@scylladb.com>

config: fix description of enable_deprecated_partitioners

---

cdc/cdc.cc
cdc/cdc.hh
cql3/statements/modification_statement.cc
service/storage_proxy.cc
service/storage_proxy.hh

Fixes #5314
Instead of tying CDC handling into cql statement objects, this patch set moves it to storage proxy, i.e. shared code for mutating stuff. This means we automatically handle cdc for code paths outside cql (i.e. alternator). 
It also adds api handling (though initially inefficient) for batch statements. 
CDC is tied into storage proxy by giving the former a ref to the latter (per shard). Initially this is _not_ a constructor parameter, because right now we have chicken and egg issues here. Hopefully, Pavels refactoring of migration manager and notifications will untie these and this relationship can become nicer. 
The actual augmentation can (as stated above) be made much more efficient. Hopefully, the stream management refactoring will deal with expensive stream lookup, and …

CDC: do mutation augmentation from storage proxy

---

database.hh
index/secondary_index_manager.cc
index/secondary_index_manager.hh
schema.cc
schema.hh
table.cc
test/boost/cql_query_test.cc

To use a snapshot we need a schema file that is similar to the result of running cql DESCRIBE command.
The DESCRIBE is implemented in the cql driver so the functionality needs to be re-implemented inside scylla.
This series adds a describe method to the schema file and use it when doing a snapshot.
There are different approach of how to handle materialize views and secondary indexes. 
This implementation creates each schema.cql file in its own relevant directory, so the schema for materializing view, for example, will be placed in the snapshot directory of the table of that view.
Fixes #4192

Adding a schema file when creating a snapshot

---

db/hints/manager.cc
gms/gossiper.cc
gms/versioned_value.cc
gms/versioned_value.hh
service/storage_service.cc

When a node does not have gossip STATUS application_state, we currently
use an empty string to present such state in get_gossip_status.
It is better to use an explicit "UNKNOWN" to present it. It makes the
log easier to understand when the status is unknown.
Before:
'gossip - InetAddress n2 is now UP, status ='
After:
'gossip - InetAddress n2 is now UP, status = UNKNOWN'
This patch is safe because the STATUS_UNKNOWN is never sent over the
cluster. So the presentation is only internal to the node.
Fixes #5520

gossiper: Introduce gossip STATUS_UNKNOWN

---

scylla_post_install.sh

awk returns float value on Debian, it causes postinst script failure since we compare it as integer value.
Replaced with sed + bash.
Fixes #5569

scylla_post_install.sh: fix 'integer expression expected' error

---

dist/ami/build_ami.sh
dist/ami/scylla.json

Update Packer to 1.5.1.
Needed to rename clean_ami_name -> clean_resource_name on scylla.json, since
the variable name had been changed.
Also fixed checksum verification code, trimmed unwanted extra strings
from sha256sum output.

dist/ami: update packer to 1.5.1

---

cql3/functions/aggregate_fcts.cc
test/boost/cql_query_test.cc

As a followup to 0bde5906b3337be7691a8fd62d3dfe98e07437e4
This series implements suggestions from @avikivity and @espindola 
It simplifies the template definitions for `accumulator_for`,
adds some debug logging for the overflow values,
and adds unit tests for float and double sum overflow.
Test: unit(dev),
paging_test:TestPagingWithIndexingAndAggregation.test_filter_{indexed,non_indexed,pk}_column(dev)

Simplify sum overflow

---

cql3/functions/time_uuid_fcts.hh
cql3/selection/abstract_function_selector.hh
cql3/selection/aggregate_function_selector.hh
cql3/selection/scalar_function_selector.hh
exceptions/exceptions.hh
test/boost/UUID_test.cc
test/boost/cql_query_test.cc
utils/UUID.hh
utils/UUID_gen.hh

Throw an error in case we hit an invalid time UUID
rather than hitting an assert.
Ref #5552

cql3: time_uuid_fcts: validate time UUID

---

db/view/view.cc
view_info.hh

The method view_info::partition_ranges() is unused.

view_info: Drop partition_ranges()

---

service/storage_service.cc

Futurize get_changed_ranges_for_leaving to fix stalls like:
```
2019-12-17T15:18:33+00:00 ip-10-0-116-62 !INFO | scylla: Reactor stalled
for 4609 ms on shard 0.
0x0000000002accbd2
0x0000000002a4579b
0x0000000002a45cc2
0x0000000002a45ff7
0x00007ff0a609be7f
0x0000000001b0b500
0x0000000001b03185
0x0000000001af0d41
0x0000000001af027a
0x0000000001f7e89a
0x0000000001f9f55a
0x0000000001fc9c09
0x0000000001fcac08
0x00000000007dfee3
/jenkins/slave/workspace/scylla-3.2/build/scylla/seastar/src/core/reactor.cc:1041
(inlined by) seastar::reactor::block_notifier(int) at
/jenkins/slave/workspace/scylla-3.2/build/scylla/seastar/src/core/reactor.cc:1164
?? ??:0 __gnu_cxx::__normal_iterator<dht::token const*,
std::vector<dht::token, std::allocator<dht::token> > > …
```

Futurize get_changed_ranges_for_leaving

---

dist/redhat/build_rpm.sh
dist/redhat/scylla.spec.mustache
dist/redhat/systemd.inc

Fedora 31 version of systemd macros does not work correctly on CentOS7,
since CentOS7 does not support "file trigger" feature.
To fix the issue we need to override macros with CentOS7 version.
See scylladb/scylla-jmx#94

dist/redhat: override systemd macros to CentOS7 version

---

dist/common/scripts/scylla_io_setup

Currently --ami does not check instance types, creates invalid io_properties.yaml on unsupported instance types.
It actually won't occur on AMI startup, since scylla_ami_setup only invoke scylla_io_setup --ami when the instance is supported, so we don't get the issue on startup, but we still get when we run scylla_io_setup manually.
It's better to check instance type on scylla_io_setup, too.
Related #5438

dist/common/scripts/scylla_io_setup: raise error when unsupported instance type

---

conf/scylla.yaml
db/config.cc
db/config.hh
tests/config_test.cc
tests/schema_change_test.cc

Scylla 3.2 doesn't support UDF, so do not accept UDF as a valid option
to experimental_features.
Fixes #5645.
No fix is needed on master, which does support UDF.

config: Remove UDF from experimental_features_t in 3.2

---

cql3/functions/time_uuid_fcts.hh
cql3/selection/abstract_function_selector.hh
cql3/selection/aggregate_function_selector.hh
cql3/selection/scalar_function_selector.hh
exceptions/exceptions.hh
test/boost/UUID_test.cc
test/boost/cql_query_test.cc
utils/UUID.hh
utils/UUID_gen.hh

Throw an error in case we hit an invalid time UUID
rather than hitting an assert.
Fixes #5552
(Ref #5588 that was dequeued and fixed here)
Test: UUID_test, cql_query_test(debug)
In v5:
- utils/UUID_gen: avoid int overflow in make_nanos_since

cql3: time_uuid_fcts: validate time UUID (v5)

---

cql3/restrictions/primary_key_restrictions.hh
cql3/restrictions/restrictions.hh
cql3/restrictions/single_column_restrictions.hh

No-one seems to invoke this method.  Instead, clients invoke
`restriction::values` (note singular "restriction").  Most subclasses of
`restrictions` also inherit from `restriction`, so `values()` still exists
in their public interface.

cql3: Drop restrictions::values() method

---

dist/redhat/scylla.spec.mustache

To install specified version of scylla-conf package, we need to add it on Requires.
See scylladb/scylla-enterprise#1203

dist/redhat: install specified version of scylla-enterprise-conf on meta package

---

cdc/cdc_extension.hh
main.cc

With this patch, client tools (in particular cqlsh) get the access
to CDC options and will be able to print them with `DESC TABLE`.
Accompanies scylladb/scylla-tools-java#142
Fixes #5589

cdc: cdc per-table options put into schema extensions

---

SCYLLA-VERSION-GEN

On our build system we tries to build relocatable package multiple times on
same revision of the repository, it executes ./SCYLLA-VERSION-GEN for each time.
When the build job invoked at midnight and it did not finished until 12:00AM,
first build and last build has different SCYLLA-RELEASE-FILE, since it contains
current date.
--disable-update-version is the option to hold current SCYLLA-RELEASE-FILE
and prevent update, to build packages with consistent revision number.
Fixes scylladb/scylla-pkg#826

SCYLLA-VERSION-GEN: skip updating version files when git hash unchanged

---

api/storage_service.cc

get_snapshot should use http stream to reduce memory allocation and
stalls.
This patch chage the implementation so it would stream each of the
snapshot object instead of creating a single response and return it.
Fixes #5468
Depends on scylladb/seastar#723

api/storage_service: use stream in get_snapshots

---

dist/ami/build_ami.sh

We made --localrpm option to automatically build rpms from sourcecode,
but we actually use the option to produce AMI using prebuilt rpm on our
CI.
To simplified the script, and to prevent accsidently start rpm build
in the script, drop rpm build part.

dist/ami: use prebuilt rpms on --localrpm

---

sstables/index_reader.hh
test/boost/multishard_mutation_query_test.cc

Most of the time schema does not have to be copied and sometimes it's not even used.
tests: unit(dev)

Remove unnecessary schema copies

---

cdc/log.cc
cdc/log.hh
db/system_keyspace.cc
dht/i_partitioner.hh
dht/token-sharding.hh
gms/gossiper.cc
service/storage_service.cc
thrift/handler.cc
transport/server.cc
transport/server.hh

In many places we use global_partitioner() to obtain parameters that are available in config. This PR replaces number of global_partitioner() calls with equivalent non-global ways.
tests: unit(dev)

Reduce usage of global_partitioner()

---

dist/docker/redhat/Dockerfile

Change the SCYLLA_REPO_URL variable to point to branch-3.3 instead of
master. This ensures that Docker image builds that don't specify the
variable build from the right repository by default.

dist/docker: Switch to 3.3 release repository

---

scylla_post_install.sh

In bash, 'A || B && C' will be problem because when A is true, then it will be
evaluates C, since && and || have the same precedence.
To avoid the issue we need make B && C in one statement.
Fixes #5764

scylla_post_install.sh: fix operator precedence issue with multiple statements

---

dist/debian/debian/scylla-server.postrm

Since dpkg does not re-install conffiles when it removed by user,
currently we are missing dependencies.conf and sysconfdir.conf on rollback.
To prevent this, we need to stop running
'rm -rf /etc/systemd/system/scylla-server.service.d/' on 'remove'.
Fixes #5734

dist/debian: keep /etc/systemd .conf files on 'remove'

---

cdc/log.cc
cdc/log.hh
cql3/statements/create_view_statement.cc
service/client_state.cc
test/boost/cdc_test.cc

This patch introduces following modifications:
- Disallows enabling cdc for table `X` when `X_scylla_cdc_log` already exists,
- Restricts DROP permissions for `X_scylla_cdc_log` tables,
- Restricts ALTER and DROP permissions for `cdc_description` and `cdc_topology_description`,
- Disallows `cdc` option when creating materialized views.
Refs #4991.
Tests: unit(dev).

Protect CDC-related tables from being modified by the user

---

cdc/log.cc
test/boost/cdc_test.cc

Setting TTL = -1 in `cdc_options` prevents any writes to CDC log. But enabling CDC and having unwritable log table makes no sense.
Notably, normal writes `USING TTL -1` are forbidden. This patch does the same to TTLs in CDC options.
Fixes #5747

cdc: disallow negative TTL values in CDC options

---

auth/standard_role_manager.cc
cdc/log.cc
cql3/column_identifier.cc
cql3/query_processor.cc
cql3/query_processor.hh
cql3/selection/selectable.cc
cql3/selection/selection.cc
cql3/selection/selection.hh
cql3/selection/selector_factories.cc
cql3/statements/select_statement.cc
db/schema_tables.cc
db/view/view.cc
service/pager/query_pagers.cc
table_helper.cc
table_helper.hh
test/boost/sstable_test.hh
test/boost/view_schema_test.cc
tracing/trace_keyspace_helper.cc
transport/server.cc
view_info.hh

This series removes some #include dependencies around cql3. It results in 30k line (6.6%) reduction in the preprocessed size of database.i, mainly due to elimination of boost::regex (which was brought in in turn by like_matcher). This should result in fewer and faster recompiles.

Reduce #include bloat around cql3 internals from non-cql3 users

---

cdc/log.cc
test/boost/cdc_test.cc

Cells in CDC logs used to be created while completely neglecting TTLs (the TTLs from `cdc = {...'ttl':600}`). This patch adds TTLs to all cells; there are no row markers, so wee need not set TTL there.
Fixes #5688

cdc: set TTLs on CDC log cells

---

table.cc

The table::flush_streaming_mutations is used in the days when streaming
data goes to memtable. After switching to the new streaming, data goes
to sstables directly in streaming, so the sstables generated in
table::flush_streaming_mutations will be empty.
It is unnecessary to invalidate the cache if no sstables are added. To
avoid unnecessary cache invalidating which pokes hole in the cache, skip
calling _cache.invalidate() if the sstables is empty.
The steps are:
- STREAM_MUTATION_DONE verb is sent when streaming is done with old or
new streaming
- table::flush_streaming_mutations is called in the verb handler
- cache is invalidated for the streaming ranges
In summary, this patch will avoid a lot of cache invalidation for
streaming.
Backports: 3.0 3.1 3.2
Fixes: #5769

Do not invalidate cache if no sstable is added in flush_streaming_mutations

---

api/api-doc/storage_service.json
api/storage_service.cc
database.cc
database.hh
service/storage_service.cc
service/storage_service.hh

This series adds an option to the API that supports deleting a specific table from a snapshot.
The implementation works in a similar way to the option to specify specific keyspaces when deleting a snapshot.
The motivation is to allow reducing disk-space when using the snapshot for backup.
A dtest PR is sent to the dtest repository.
Fixes #5658

Delete table from a snapshot

---

service/storage_proxy.cc

This patch fixes a bug that appears because of an incorrect interaction between counters and hinted handoff.
When a counter is updated on the leader, it sends mutations to other replicas that contain all counter shards from the leader. If consistency level is achieved but some replicas are unavailable, a hint with mutation containing counter shards is stored.
When a hint's destination node is no longer its replica, it is attempted to be sent to all its current replicas. Previously, if the cluster did not have the feature HINTED_HANDOFF_SEPARATE_CONNECTION enabled, storage_proxy::mutate function would be used for the purpose of sending the hint. It was incorrect because that function treats mutations for counter tables as mutations containing only a delta (by how much to increase/decrease …

hinted handoff: handle counter update hints correctly

---

db/schema_tables.cc

When dropping a table, the table and its views are dropped
in parallel, this is not a problem as for itself but we
have mechanism to snapshot a deleted table before the
actual delete. When a secondary index is removed, in the
snapshot process it looks for it's schema for creating the
schema part of the snapshot but if the main table is already
gone it will not find it.
This commit serializes views and main table removals and
removes the views prior to the tables.
See discussion on https://github.com/scylladb/scylla/pull/5713
Tests:
Unit tests (dev)
dtest - A test that failed on "can't find schema" error
Fixes #5614

Materialized Views: drop materialized views before it's table

---

cql3/statements/select_statement.cc

This series fixes null pointer dereference seen in #5794
efd7efe41e cql3: generate_base_key_from_index_pk; support optional index_ck
7af1f9e26a cql3: do_execute_base_query: generate open-ended slice when clustering key is unavailable
7fe1a9ec4a cql3: do_execute_base_query: fixup indentation
Fixes #5794
Branches: 3.3

cql3: do_execute_base_query: fix null deref when clustering key is unavailable

---

db/hints/manager.cc
service/storage_proxy.cc
service/storage_proxy.hh

This patch fixes a bug that appears because of an incorrect interaction between counters and hinted handoff.
When a counter is updated on the leader, it sends mutations to other replicas that contain all counter shards from the leader. If consistency level is achieved but some replicas are unavailable, a hint with mutation containing counter shards is stored.
When a hint's destination node is no longer its replica, it is attempted to be sent to all its current replicas. Previously, storage_proxy::mutate was used for that purpose. It was incorrect because that function treats mutations for counter tables as mutations containing only a delta (by how much to increase/decrease the counter). These two types of mutations have different serialization format, so in this case a "shards" mutation …

hinted handoff: send orphaned counter hints correctly

---

api/api-doc/storage_service.json
api/storage_service.cc
database.cc
database.hh
service/storage_service.cc
service/storage_service.hh
test/boost/database_test.cc

This series adds an option to the API that supports deleting a specific table from a snapshot.
The implementation works in a similar way to the option to specify specific keyspaces when deleting a snapshot.
The motivation is to allow reducing disk-space when using the snapshot for backup.
A dtest PR is sent to the dtest repository.
Fixes #5658
Original PR #5805
Tests: (database_test) (dtest snapshot_test.py:TestSnapshot.test_cleaning_snapshot_by_cf)

Delete table snapshot

---

cql3/selection/selector.hh

Aggregate functions for counters do not exist. Until now counters could, at best, fall back to blob->blob overloads, e.g.:
```
cqlsh> select max(cnt) from ks.tbl;
system.max(cnt)
----------------------
0x000000000000000a
(1 rows)
cqlsh> select sum(cnt) from ks.tbl;
InvalidRequest: Error from server: code=2200 [Invalid query]
message="Invalid call to function sum, none of its type signatures match
[...]
```
Meanwhile, bigint (`long_type`) overloads (e.g. `sum(bigint)->bigint`) can be used on counters just fine. In this patch this is achieved by special rule in "overload resolution". `selector` now perceives counters as an `EXACT_MATCH` to their underlying type (bigint).
Fixes #3174

cql3: Fix missing aggregate functions for counters

---

dist/debian/debian/scylla-server.install

It seems like *.service is conflicting on install time because the file
installed twice, both debian/*.service and debian/scylla-server.install.
We don't need to use *.install, so we can just drop the line.
Fixes #5640

dist/debian: fix "unable to open node-exporter.service.dpkg-new" error

---

db/hints/manager.cc
service/storage_proxy.cc
service/storage_proxy.hh

Changes the name of `storage_proxy::mutate_hint_from_scratch` function to another name, whose meaning is more clear: `send_hint_to_all_replicas`.

storage proxy: rename mutate_hint_from_scratch

---

dist/common/scripts/scylla_setup

Since we set 'eth0' as default NIC name, we get following error when running scylla_setup in non-interactive mode without --nic parameter:
```
$ sudo scylla_setup --setup-nic-and-disks --no-raid-setup --no-verify-package --no-io-setup
NIC eth0 doesn't exist.
```
It looks strange since user actually does not specified 'eth0', they might forget to specify --nic.
I think we should shows up usage, when eth0 is not available on the system.
Fixes #5828

scylla_setup: shows up usage when --nic is not specified & eth0 is not available

---

dist/common/scripts/scylla_coredump_setup

We don't need to create 99-scylla-coredump.conf on CentOS8, the file is only
needed for CentOS7.
Fixes #5818

dist/common/scripts/scylla_coredump_setup: don't create /etc/sysctl.d/99-scylla-coredump.conf on CentOS8

---

cdc/log.cc
test/boost/cdc_test.cc

Column `operation` now contains `operation::row_delete` (== 2)
after queries like `delete from tbl where pk=x and ck=y;`. Before
this patch row deletes were treated as updates, which was incorrect
because updates do not contain row tombstones (and row deletes do).
Refs #5709

cdc: Fix `operation` value for row deletes

---

dist/debian/rules.mustache
dist/redhat/scylla.spec.mustache
install.sh

To install scylla using install.sh easily, we need to run following things:
- add scylla user/group
- configure scylla.yaml
- run scylla_post_install.sh
But we don't want to run them when we build .rpm/.deb package,
we also need to add --packaging option to skip them.
Fixes #5830

install.sh: run post-install script just like .rpm/.deb package

---

cdc/log.cc
cdc/log.hh
test/boost/cdc_test.cc

New kind of `operation` is introduced: "insert". It is reported in CDC log whenever the incoming mutation has a live row marker.
Fixes #5723

cdc: distinguishing inserts from updates

---

cdc/log.cc
cdc/log.hh
cql3/sets.cc
test/boost/cdc_test.cc
types.cc
types/set.hh

Rename metadata and data columns according to new spec
Also use transformation methods for names in all code + tests
to make switching again easier
Break up data column tuple
Data column is now pure frozen original type. 
- If column is deleted (set to null), a metadata column cdc$deleted_<name> is set to true, to distinguish null column == not involved in row operation
- For non-atomic collections, a cdc$deleted_elements_<name> column is added, and when removing elements from collection this is where they are shown.
- For non-atomic assign, the "cdc$deleted_<name>" is true, and <name> is set to new value.
column_op removed.
v2:
Modified to use uniform "key" set semantics for all non-atomic types, i.e. udts put deleted fields as field index in `deleted_elements` set.

CDC: implement new column format and naming

---

cdc/log.cc
cdc/log.hh
cdc/split.cc
cdc/split.hh
test/boost/cdc_test.cc

If a batch update is performed with a sequence of changes with a single timestamp, they will now show up in CDC with a single timeuuid in the cdc$time column, distinguished by different cdc$batch_seq_no values.
Fixes #5953.

CDC: use a single `cdc$time` value for a batch of changes 

---

cdc/log.cc
test/cql/cdc_disallow_nested_cdc_logs_test.cql
test/cql/cdc_disallow_nested_cdc_logs_test.result
test/tools/cql_repl.cc

This change disallows creating CDC log tables for already existing CDC log tables. CDC logs nested in that way are not really useful and do not work at the moment, therefore disallowing their creation prevents confusion.
Fixes #5967

cdc: disallow creating nested cdc logs

---

database.cc
database.hh
dht/i_partitioner.hh
dht/murmur3_partitioner.hh
repair/row_level.cc
schema.cc
schema.hh
sstables/binary_search.hh
sstables/compaction_manager.cc
test/boost/mutation_reader_test.cc
test/boost/sstable_datafile_test.cc
test/boost/sstable_test.hh
test/lib/test_services.cc
test/lib/test_services.hh

and make schema::get_partitioner return const&.
Partitioners returned from get_partitioner are shared and not supposed to be changed so let's use the type system to enforce that.
dht::global_partitioner() is deprecated and will be removed as soon as custom partitioners are implemented so it's best to replace it with schema::get_partitioner.

Replace dht::global_partitioner() calls with schema::get_partitioner

---

cql3/restrictions/single_column_restriction.hh
cql3/restrictions/statement_restrictions.cc
test/boost/cql_query_test.cc
test/boost/like_matcher_test.cc
utils/like_matcher.cc
utils/like_matcher.hh

Fixes #5902 by making the LIKE restriction keep a vector of matchers and apply them all to the column value.

Allow repeated LIKE on same column

---

cdc/log.cc
test/boost/cdc_test.cc

If base mutation has at least one row tombstone, its preimage log entry displays all the base columns.
Fixes #5709

cdc: on row delete, show the whole row as preimage

---

dist/docker/redhat/scylla-jmx-service.sh

Apply scylla-jmx sysconfig file on scyla-jmx service, to allow customize
jmx parameter.
Fixes #5939

docker: apply scylla-jmx sysconfig file on scylla-jmx service

---

cdc/log.cc
cdc/log.hh
cql3/untyped_result_set.hh
schema.cc
schema.hh
test/boost/cdc_test.cc

Fixes #4992
Implements post-image support by synthesizing it from
pre-image + delta.
Post-image data differs from the delta data in two ways:
1.) It merges non-atomics into an actual result value
2.) It contains _all_ columns of the row, not just
those affected by the update.
For a non-atomic field, the post-image value of a column
is either the pre-image or the delta (maybe null)
Tested by adding post-image checks to pre-image test
and collection/udt tests

Add postimage implementation

---

database.cc
database.hh
db/schema_features.hh
db/schema_tables.cc
db/schema_tables.hh
dht/i_partitioner.cc
dht/i_partitioner.hh
gms/feature.hh
gms/feature_service.cc
gms/feature_service.hh
main.cc
multishard_mutation_query.cc
mutation_reader.cc
mutation_reader.hh
repair/row_level.cc
schema.cc
schema.hh
schema_builder.hh
schema_mutations.cc
schema_mutations.hh
service/migration_manager.cc
test/boost/mutation_reader_test.cc
test/boost/network_topology_strategy_test.cc
test/boost/partitioner_test.cc
test/boost/sstable_datafile_test.cc
test/lib/test_services.cc

This PR makes it possible to enable the usage of different partitioner for each table. If no table-specific partitioner is set for a given table then a default partitioner is used.
The PR is composed of the following parts:
1. Introduction of schema::get_partitioner that still returns dht::global_partitioner
2. Replacement of all the usage of dht::global_partitioner with schema::get_partitioner
3. Making it possible to set table-specific partitioner in a schema_builder
4. Remove all the places that were setting default partitioner except for main.cc (mostly tests)
5. Move default partitioner from i_partitioner to schema.cc and hide it from the rest of the codebase
6. Remove dht::global_partitioner
After this PR there's no such thing as global partitioner at all. There is only a default …

Allow setting partitioner per table

---

install.sh

Seems like adduser in redhat variants and deiban variants are incompatible,
and there is no addgroup in redhat variants.
Since adduser in install.sh is implemented on debian variants, does not work on redhat compatible.
To fix this we need to use 'useradd' / 'groupadd' instead.
Fixes #6018

install.sh: create user/group correctly on redhat variants

---

gms/application_state.cc

I saw UNKNOWN application state in the logs:
INFO  2020-03-06 11:09:48,931 [shard 0] storage_service - Update
system.peers table: endpoint=127.0.0.2, app_state=CACHE_HITRATES, versioned_value=Value(,14)
INFO  2020-03-06 11:09:48,931 [shard 0] storage_service - Update
system.peers table: endpoint=127.0.0.2, app_state=SCHEMA_TABLES_VERSION, versioned_value=Value(3,15)
INFO  2020-03-06 11:09:48,931 [shard 0] storage_service - Update
system.peers table: endpoint=127.0.0.2, app_state=RPC_READY, versioned_value=Value(0,16)
INFO  2020-03-06 11:09:48,931 [shard 0] storage_service - Update
system.peers table: endpoint=127.0.0.2, app_state=VIEW_BACKLOG, versioned_value=Value(,17)
INFO  2020-03-06 11:09:48,931 [shard 0] storage_service - Update
system.peers table: endpoint=127.0.0.2, …

gossip: Print CDC_STREAMS_TIMESTAMP correctly

---

cdc/log.cc
cdc/log.hh
cdc/split.cc
cdc/stats.hh
service/storage_proxy.cc
service/storage_proxy.hh

Adds CDC-related metrics.
Following counters are added, both for total and failed operations:
- Total number of CDC operations that did/did not perform splitting,
- Total number of CDC operations  that touched a particular mutation part.
- Total number of preimage selects.
Fixes #6002.
Tests: unit(dev, debug)

cdc: add metrics

---

cdc/log.cc
test/boost/cdc_test.cc

Fixes #6073
The logic with pre/post image was tangled into looking at "rs"
and would cause pre-image info to be stored even if only post-image
data was enabled.
Now only generate keys (and rows for them) iff explicitly enabled.
And only generate pre-image key iff we have pre-image data.
Note: this is based on the changes in #6077, so only the latter is merged, this contains both changes.

 cdc::log: Only generate pre/post-image when enabled

---

service/migration_manager.cc
service/migration_manager.hh
service/migration_task.cc
service/migration_task.hh

sync_schema is supposed to make sure that this node knows about all
schema changes known by "nodes" that were made prior to this call.
Currently, when a node is down, the sync is sliently skipped.
To fix, add a flag to migration_task::run_may_throw to indicate that it
should fail if a node is down.
Fixes #4791

migration_manager: Make sync_schema return error when node is down

---

database.hh
db/view/view_update_generator.cc
db/view/view_update_generator.hh
db/view/view_updating_consumer.hh
table.cc
test/boost/view_build_test.cc

There is no reason to read a single SSTable at a time from the staging
directory. Moving SSTables from staging directory essentially involves
scanning input SSTables and creating new SSTables (albeit in a different
directory).
We have a mechanism that does that: compactions. In a follow up patch, I
will introduce a new specialization of compaction that moves SSTables
from staging (potentially compacting them if there are plenty).
In preparation for that, some signatures have to be changed and the
view_updating_consumer has to be more compaction friendly. Meaning:
- Operating with an sstable vector
- taking a table reference, not a database
Because this code is a bit fragile and the reviewer set is fundamentally
different from anything compaction related, I am sending this separately

prepare the view building generator to work through a compaction

---

table.cc

The io_priority parameter used when generating view updates from
streaming is used by the sstable reader, so it should use the I/O priority
for streaming *read* operations, not streaming *write* operations.
Fixes #6231

table: switch to correct io_priority for streaming view updates

---

cql3/statements/create_table_statement.cc
db/legacy_schema_migrator.cc
db/schema_tables.cc
schema.cc
schema_builder.hh

In order to avoid confusion with regard to whose responsibility
it is to sort the key columns (see #5856), the interface which allows
adding columns to the builder with explicit column id
is moved to a private function. An internal with_column_ordered()
overload is maintained to be used for internal operations,
but it's encouraged to use simpler with_column() in new code.
Fixes #6235

treewide: deprecate passing explicit order in schema building

---

cql3/restrictions/statement_restrictions.cc
test/cql/counters_test.cql
test/cql/counters_test.result
types.cc

Queries with `ALLOW FILTERING` and constraints on counter values used to be rejected as "unimplemented". The reason was a missing tri-comparator, which is added in this patch.
Fixes #5635

counters: Fix filtering of counters

---

cdc/log.cc
cdc/log.hh
exceptions/exceptions.hh
service/storage_proxy.cc

CL of LOCAL_QUORUM used to be hardcoded into CDC preimage query
and led to an error every time the number of replicas was lower than CL
would require. The solution here is to link the CLs of writes
to base table with the CLs of CDC reads, so the client will get
the (limited) control over the consistency of preimage SELECTs
(instead of constant misleading errors).
The algorithm is as follows:
1. If write that caused CDC activity was done with CL = ANY,
then do preimage read with CL = ONE.
2. If write that caused CDC activity was done with CL = ALL,
then do preimage read with CL = QUORUM.
3. SERIAL and LOCAL_SERIAL writes cause preimage read with QUORUM
and LOCAL_QUORUM, respectively.
4. In other cases do preimage read with the same CL as base write.
To further mitigate the incomprehensible …

cdc: fix the "NoHostAvailable" client error when CL is not met

---

cdc/generation.cc
docs/cdc.md
gms/gossiper.cc
gms/gossiper.hh
gms/versioned_value.cc
gms/versioned_value.hh
locator/ec2_multi_region_snitch.cc
locator/gossiping_property_file_snitch.cc
service/migration_manager.cc
service/misc_services.cc
service/storage_service.cc
service/storage_service.hh
test/manual/gossip.cc

1. Remove the `versioned_value::factory` class, it didn't add any value. It just forced us to create an object for making `versioned_value`s, for no sensible reason.
2. Move some `versioned_value` deserialization code (string -> internal data structures) into the versioned_value module. Previously, it was scattered all around the place.
3. Make `gossiper::get_seeds` const and return a const reference.
I needed these refactors for a PR I was preparing to fix an issue with CDC. The attempt of fixing the issue failed (I'm trying something different now), but the refactors might be useful anyway.

A bunch of refactors in versioned_value and gossiper

---

mutation_writer/multishard_writer.cc
repair/row_level.cc
test/boost/mutation_writer_test.cc

This series fix hang in multishard_writer when error happens. It contains
- multishard_writer: Abort the queue attached to consumers when producer fails
- repair: Fix hang when the writer is dead
Fixes #6241
Refs: #6248

Fix hang in multishard_writer

---

locator/abstract_replication_strategy.cc
locator/abstract_replication_strategy.hh
locator/everywhere_replication_strategy.hh
locator/local_strategy.hh
locator/network_topology_strategy.hh
locator/simple_strategy.hh
locator/token_metadata.cc
locator/token_metadata.hh
repair/repair.cc
repair/repair.hh
service/storage_proxy.cc
service/storage_service.cc
service/storage_service.hh

storage_service: Make replacing node take writes
Background:
Replace operation is used to replace a dead node in the cluster.
Currently during replace operation, the replacing node does not take any
writes. As a result, new writes to a range after the sync for that range
is done, e.g., after streaming for that range is finished, will not be
synced to the replacing node. Hinted hand off or repair after the
replacing operation will help. But it is better if we can make the
writes to the replacing node to avoid any post replacing operation
actions.
After this series and repair based node operation series, the replace
operation will guarantee the replacing node has all the latest copy of
data including the new writes during the replace operation. In short, no
more repairs before or after the …

Make replacing node take writes

---

alternator/server.cc
gms/gossiper.cc
gms/gossiper.hh
init.cc
message/messaging_service.cc
message/messaging_service.hh
redis/server.cc
test/boost/gossip_test.cc
test/lib/cql_test_env.cc
test/lib/test_services.cc
transport/server.cc

Fixes #6067
Requires seastar patch set "Reloadable TLS certificates"
Makes the scylla endpoint initializations that support TLS use reloadable certificate stores, watching used cert + key files for changes, and reload iff modified. 
Tests in separate dtest set.

Support SSL Certificate Hot Reloading

---

cql3/tuples.hh
test/boost/cql_query_test.cc

This is unrelated to counters, but happens to fix #4209 
`tuple::delayed_value::contains_bind_marker` used to check that
ALL terms are bound (not that ANY of them is bound). As a result,
scylla would crash in prepare codepath for collections of tuples.
After this fix `invalid_request_exception` is thrown instead.

cql3: Fix detection of bound variables in tuples

---

caching_options.hh
cdc/log.cc
cql3/statements/cf_prop_defs.cc
cql3/statements/cf_prop_defs.hh
cql3/statements/property_definitions.cc
cql3/statements/property_definitions.hh
database.hh
gms/feature.hh
gms/feature_service.cc
gms/feature_service.hh
table.cc

We inherited from Origin a `caching` table parameter. It's a map of named caching parameters. Before this PR two caching parameters were expected: `keys` and `rows_per_partition`. So far we have been ignoring them. This PR adds a new caching parameter called `enabled` which can be set to `true` or `false` and controls the usage of the cache for the table. By default, it's set to `true` which reflects Scylla behavior before this PR.
This new capability is used to disable caching for CDC Log table. It is desirable because CDC Log entries are not expected to be read often. They also put much more pressure on memory than entries in Base Table. This is caused by the fact that some writes to Base Table can override previous writes. Every write to CDC Log is unique and does not invalidate any …

Make it possible to turn caching off per table and stop caching CDC Log

---

cdc/log.cc

CDC Log is a time series so it makes sense to use time window compaction strategy for it.
Our support for time series is limited so we make sure that we don't create more than 24 sstables.
If TTL is configured to 0, meaning data does not expire, we don't use time window compaction strategy.
This PR also sets gc_grace_seconds to 0 when TTL is not set to 0.

Use time window compaction strategy for CDC Log table

---

test/boost/cql_query_test.cc

In add40d4e59, we relaxed the prohibition of unbounded DELETE and
stopped testing the failure message.  But there are still scenarios
when unbounded DELETE is prohibited, so add a test to ensure we
continue to catch it where appropriate.

cql: Add test for invalid unbounded DELETE

---

api/storage_service.cc
service/storage_service.cc

This series changes the describe_ring API to use HTTP stream instead of serializing the results and send it as a single buffer.
While testing the change I hit a 4-year-old issue inside service/storage_proxy.cc that causes a use after free, so I fixed it along the way.
Fixes #6297

Use http Stream for describe ring

---

dist/redhat/python3/python.spec
dist/redhat/scylla.spec
reloc/build_deb.sh
reloc/build_rpm.sh
reloc/python3/build_deb.sh
reloc/python3/build_rpm.sh
scripts/create-relocatable-package-python3.py
scripts/create-relocatable-package.py

To make unified relocatable package easily, we may want to merge tarballs to single tarball like this:
zcat *.tar.gz | gzip -c > scylla-unified.tar.xz
But it's not possible with current relocatable package format, since there are multiple files conflicts, install.sh, SCYLLA-*-FILE, dist/, README.md, etc..
To support this, we need to archive everything in the directory when building relocatable package.
Fixes #6315

reloc-pkg: move all files under project name directory

---

idl/partition_checksum.idl.hh
message/messaging_service.cc
message/messaging_service.hh
repair/repair.cc
repair/repair.hh
repair/row_level.cc

Commit 75cf255c67641db7255286908c8b4f5a67590f9c (repair: Ignore keyspace
that is removed in sync_data_using_repair) is not enough to fix the
issue because when the repair master checks if the table is dropped, the
table might not be dropped yet on the repair master.
To fix, the repair master should check if the follower failed the repair
because the table is dropped by checking the error returned from
follower.
With this patch, we would see
WARN  2020-04-14 11:19:00,417 [shard 0] repair - repair id 1 on shard 0
completed successfully, keyspace=ks, ignoring dropped tables={cf}
when the table is dropped during bootstrap.
Tests: update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_add_new_node_while_schema_changes_test
Fixes: #5942

repair: Ignore table removed in sync_data_using_repair

---

database.cc
database.hh
db/batchlog_manager.cc
db/legacy_schema_migrator.cc
db/schema_tables.cc
db/view/view.cc
db/view/view.hh
service/paxos/paxos_state.cc
service/storage_proxy.cc
service/storage_proxy.hh
table.cc
test/boost/batchlog_manager_test.cc
test/boost/database_test.cc
test/manual/sstable_scan_footprint_test.cc
test/perf/perf_cache_eviction.cc

In order to improve materialized views' debuggability, tracing points are added to view update generation path.
Example trace:
```
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------+-----------+----------------+-----------
Execute CQL3 query | 2020-04-27 13:13:46.834000 | 127.0.0.1 |              0 | 127.0.0.1
Parsing a statement [shard 0] | 2020-04-27 13:13:46.834346 | 127.0.0.1 |              1 | 127.0.0.1
Processing a statement [shard 0] | 2020-04-27 13:13:46.834426 | 127.0.0.1 |             80 | 127.0.0.1
Creating write handler for token: -3248873570005575792 natural: {127.0.0.1, 127.0.0.3} pending: {} [shard 0] | 2020-04-27 …
```

Propagate tracing to materialized view update path

---

service/storage_service.cc

Allow a node to join without bootstrapping, even if it couldn't contact other nodes.
Print a BIG WARNING saying that you should never join nodes without
bootstrapping (by marking it as a seed or using auto_bootstrap=off).
Only the very first node should (must) be joined as a seed.
If you want to have more seeds, first join them using the only supported
way (i.e. bootstrap them), and only AFTER they have bootstrapped, change
their configuration to include them in the seed list.
Does not fix, but closes https://github.com/scylladb/scylla/issues/6005. Read the discussion: it's enlightening.
See https://github.com/scylladb/scylla-docs/issues/2647 for the correct procedure of joining a node.
Reverts https://github.com/scylladb/scylla/commit/7cb6ac33f5f54cae665cecd3a90428eb52d424e3.

Allow our users to shoot themselves in their feet.

---

test/boost/dynamic_bitset_test.cc
test/boost/loading_cache_test.cc
test/boost/querier_cache_test.cc
test/unit/lsa_sync_eviction_test.cc

In several tests we were calling random_device::operator() in a tight loop. This is a slow operation, and in gcc 10 can fail if called too frequently due to a bug [1].
Change to use a random_engine instead, seeded once from the random_device.
[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94087

tests: avoid exhausting random_device entropy

---

database.cc
mutation_partition.cc
mutation_query.hh

Counter update is a RMW operation. Until now the "Read" part was
not guarded by a timeout, which is changed in this patch.
Fixes #5069

counters: Read the state under timeout

---

dist/common/scripts/scylla_coredump_setup
dist/common/scripts/scylla_util.py

Currently in coredump setup, we enabled a systemd mount to mount default coredump directory to /var/lib/scylla/coredump, but we didn't start it. So the coredump will still be saved to default coredump directory before a system reboot, it might touch enospc problem.
One patch started the systemd mount during coredump setup, and make the mount effect.
Another patch improved the error message of systemd unit, it's confused when the unit config is invalid.

scylla_coredump_setup: fix coredump directory mount

---

cdc/log.cc
test/cql/cdc_disallow_cdc_for_counters_test.cql
test/cql/cdc_disallow_cdc_for_counters_test.result

CDC for counters is unimplemented as of now, therefore any attempt to enable CDC log on counter table needs to be clearly disallowed. This patch does exactly this.
The check whether schema has counter columns is performed in `cdc_service::impl` in:
- `on_before_create_column_family`,
- `on_before_update_column_family`
and, if so, results in `invalid_request_exception` thrown.
Fixes #6553

CDC: Disallowed CDC for tables with counter column(s)

---

dist/debian/debian_files_gen.py

Since 287d6e5, we mistakenly packaging node-exporter.service in wrong name
on .deb, need to rename in correct name.
Fixes #6604

dist/debian: fix node-exporter.service file name

---

db/view/view.cc
db/view/view_update_generator.cc
table.cc

This series adds error injection points to materialized view paths:
- view update generation from staging sstables;
- view building;
- generating view updates from user writes.
This series comes with a corresponding dtest pull request which adds some test cases based on error injection.
Fixes #6488

Add error injection to mv

---

reloc/python3/build_deb.sh

This is scylla-python3 version of #6611, but we also need to rename
.deb build directory for scylla-python3, since we may lose .deb when
building both scylla and scylla-python3 .deb package, since we currently
sharing build directory.
So renamed it to build/python3/debian.

dist/debian/python3: cleanup build/debian, rename build directory

---

dist/common/scripts/scylla_bootparam_setup

CentOS7 uses GRUB_CMDLINE_LINUX on /etc/default/grub, but Amazon Linux 2 only
has GRUB_CMDLINE_LINUX_DEFAULT, we need to support both.

scylla_bootparam_setup: support Amazon Linux 2

---

test/lib/cql_assertions.cc
test/lib/cql_assertions.hh
test/lib/cql_test_env.cc
test/lib/cql_test_env.hh

This lets the functions operate on a wider variety of arguments and
may also be faster.

Use sstring_view in execute_cql and assertions

---

dist/common/scripts/scylla_cpuscaling_setup
dist/common/scripts/scylla_util.py
dist/redhat/scylla.spec

Amazon Linux 2 has /usr/bin/cpupower, but does not have cpupower.service
unlike CentOS7.
We need to provide the .service file when distribution is Amazon Linux 2.
Fixes #5977

scylla_cpuscaling_setup: support Amazon Linux 2

---

message/messaging_service.cc

The messaging service constructor's body does two main things in this
order:
1. it registers the CLIENT_ID verb with rpc.
2. it initializes the scheduling mechanism in charge of locating the
right scheduling group for each verb.
The registration function uses the scheduling mechanism to determine
the scheduling group for the verb.
This commit simply reverses the order of execution.
Fixes #6628

messagin service: fix execution order in messaging_service constructor

---

dht/boot_strapper.cc
dht/boot_strapper.hh
dht/range_streamer.cc
dht/range_streamer.hh
idl/streaming.idl.hh
repair/repair.cc
service/storage_service.cc
streaming/stream_reason.hh

After "Make replacing node take writes" series, with repair based node
operations disabled, we saw the replace operation fail like:
```
[shard 0] init - Startup failed: std::runtime_error (unable to find
sufficient sources for streaming range (9203926935651910749, +inf) in
keyspace system_auth)
```
The reason is the system_auth keyspace has default RF of 1. It is
impossible to find a source node to stream from for the ranges owned by
the replaced node.
In the past, the replace operation with keyspace of RF 1 passes, because
the replacing node calls token_metadata.update_normal_tokens(tokens,
ip_of_replacing_node) before streaming. We saw:
```
[shard 0] range_streamer - Bootstrap : keyspace system_auth range
(-9021954492552185543, -9016289150131785593] exists on {127.0.0.6}
```
Node …

range_streamer: Handle table of RF 1 in get_range_fetch_map

---

.gitmodules
configure.py
install-dependencies.sh
tools/toolchain/image
zstd.cc

Now that Fedora provides the zstd static library, we can remove the
submodule.
The frozen toolchain is regenerated to include the new package.

build: remove zstd submodule

---

configure.py
reloc/build_reloc.sh

To reduce special cases for the build bots, default dpdk to enabled
in release mode, keeping it disabled for debug and dev.
To allow release modes without dpdk to be build, the --enable-dpdk
switch is converted to a tri-state. When disabled, dpdk is disabled
across all modes. Similarly when enabled the effect is global. When
unspecified, dpdk is enabled for release mode only.

build: default enable dpdk in release mode

---

reader_concurrency_semaphore.cc

tracked_file_impl is a wrapper around another file, that tracks
memory allocated for buffers in order to control memory consumption.
However, it neglects to inherit the disk and memory alignment settings
from the wrapped file, which can cause unnecessarily-large buffers
to be read from disk, reducing throughput.
Fix by copying the alignment parameters.
Fixes #6290.

tracked_file_impl: inherit disk and memory alignment from underlying file

---

repair/repair.cc
repair/repair.hh
repair/row_level.cc
repair/row_level.hh

Use table_id instead of table_name in row level repair to find a table. It
guarantees we repair the same table even if a table is dropped and a new
table is created with the same name.
Refs: #5942

Repair use table id instead of table name

---

dist/common/scripts/scylla_cpuscaling_setup
dist/redhat/scylla.spec

Since scylla-cpupower.service isn't installed by .rpm package, but created
in the setup script, it's better to not use /usr/lib directory, use /etc.
We already doing same way for scylla-server.service.d/*.conf, *.mount, and
*.swap created by setup scripts.

scylla_cpuscaling_setup: move the unit file to /etc/systemd

---

api/api-doc/storage_service.json
api/storage_service.cc
cdc/generation.cc
service/storage_service.cc
service/storage_service.hh

The command regenerates streams when:
- generations corresponding to a gossiped timestamp cannot be
fetched from `system_distributed` table,
- or when generation token ranges do not align with token metadata.
In such case the streams are regenerated and new timestamp is
gossiped around. The returned JSON is always empty, regardless of
whether streams needed regeneration or not.
Fixes #6498
Accompanied by: scylladb/scylla-jmx#109, scylladb/scylla-tools-java#172

api: Command to check and repair cdc streams

---

api/storage_proxy.cc
configure.py
service/storage_proxy.cc
service/storage_proxy_stats.hh
test/boost/estimated_histogram_test.cc
utils/estimated_histogram.hh
utils/histogram_metrics_helper.hh

This series Adds a pseudo-floating-point histogram implementation.
The histogram is used for time_estimated_histogram a histogram for latency tracking and then used in storage_proxy as a more efficient with a higher resolution histogram.
Follow up series would use the new histogram in other places in the system and will add an implementation that supports lower values.
Fixes #5815
Fixes #4746

Adding Optimized pseudo floating point estimated histogram

---

db/hints/manager.cc
db/hints/manager.hh

This series contains two improvements to hint file replay logic in hints manager:
- During replay of a hint file, keeping track of the first hint that fails to be sent is now done via a simple std::optional variable instead of an unordered_set. This slightly reduces complexity of next replay position calculation.
- A corner case is handled: if reading commitlog fails, but there won't be an error related to sending hints, starting position wouldn't be updated. This could cause us to replay more hints than necessary.
Tests:
- unit(dev)
- dtest(hintedhandoff_additional_test, dev)

hinted handoff: improve segment replay logic

---

test/boost/range_test.cc

Intersection was previously not tested for singular ranges.  This
ensures it will always work for singular ranges, too.

range_test: Add cases for singular intersection

---

dist/common/scripts/scylla_swap_setup

fallocate creates sparse file, XFS rejects such file for swapfile:
https://bugzilla.redhat.com/show_bug.cgi?id=1129205
Use dd instead.
Fixes #6650

scylla_swap_setup: don't create sparse file

---

dist/debian/python3/build_deb.sh
dist/debian/python3/changelog.template
dist/debian/python3/control.template
dist/debian/python3/debian/rules
dist/debian/python3/debian_files_gen.py
reloc/python3/build_reloc.sh
scripts/create-relocatable-package-python3.py

Same as 287d6e5, we need to drop pystache from package build script
since Fedora 32 dropped it.

dist/debian/python3: drop dependency on pystache

---

dist/common/scripts/scylla_raid_setup

systemd requires daemon-reload after adding drop-in file, so we need to
do that after writing mounts.conf.
Fixes #6674

scylla_raid_setup: daemon-reload after mounts.conf installed

---

dist/common/scripts/scylla_swap_setup

On Ubuntu 18.04 and ealier & Deiban 10 and ealier, /usr merge is not done, so
/usr/bin/systemd-escape and /bin/systemd-escape is different place, and we call
/usr/bin but Debian variants tries to install the command in /bin.
Drop full path, just call command name and resolve by default PATH.
Fixes: #6650

scylla_swap_setup: fix systemd-escape path

---

interface/cassandra.thrift

The thrift compiler (since 0.13 at least) complains that
the csharp target is deprecated and recommend replacing it
with netstd. Since we don't use either, humor it.
I suspect that this warning caused some spurious rebuilds,
but have not proven it.

thrift: switch csharp backend to netstd

---

configure.py

As HACKING.md suggests, we now require gcc version >= 10.  Set the
minimum at 10.1.1, as that is the first official 10 release:
https://gcc.gnu.org/releases.html
Tests: manually run configure.py and ensure it passes/fails
appropriately.

configure.py: Update gcc version check

---

configure.py

The variable doesn't appear to be used anywhere.
Tests: manually run configure.py

configure.py: Drop unused var cassandra_interface

---

dist/common/scripts/scylla_util.py

Currently we we mistakenly made two different way to detect distribution,
directly reading /etc/os-release and use distro package.
distro package provides well abstracted APIs and still have full access to
os-release informations, we should switch to it.
Fixes #6691

scylla_util.py: stop using /etc/os-release, use distro

---

dist/common/scripts/scylla_ntp_setup

Use distro API to simplify distribution detection.

scylla_ntp_setup: switch to distro package

---

dist/common/scripts/scylla_swap_setup

Show better error message and exit with non-zero status when memory size <1GB.
Fixes #6659

scylla_swap_setup: handle <1GB environment

---

dist/common/scripts/scylla_util.py

When we started to porting bash script to python script, we are not able to use
subprocess.run() since EPEL only provides python 3.4, but now we have
relocatable python, so we can switch to it.

scylla_util.py: switch to subprocess.run()

---

api/storage_service.cc
locator/abstract_replication_strategy.cc
locator/abstract_replication_strategy.hh
sstables/compaction_manager.cc
sstables/compaction_manager.hh

compaction_manager: Avoid stall in perform_cleanup
The following stall was seen during a cleanup operation:
scylla: Reactor stalled for 16262 ms on shard 4.
| std::_MakeUniq<locator::tokens_iterator_impl>::__single_object std::make_unique<locator::tokens_iterator_impl, locator::tokens_iterator_impl&>(locator::tokens_iterator_impl&) at /usr/include/fmt/format.h:1158
|  (inlined by) locator::token_metadata::tokens_iterator::tokens_iterator(locator::token_metadata::tokens_iterator const&) at ./locator/token_metadata.cc:1602
| locator::simple_strategy::calculate_natural_endpoints(dht::token const&, locator::token_metadata&) const at simple_strategy.cc:?
|  (inlined by) locator::simple_strategy::calculate_natural_endpoints(dht::token const&, locator::token_metadata&) const at …

Compaction fix stall in perform cleanup

---

dist/common/scripts/scylla_setup

hugepages package now renamed to libhugetlbfs-bin, we need to follow
the change.
Fixes #6673

scylla_setup: follow hugepages package name change on Ubuntu 20.04LTS

---

repair/repair.cc

In commit 12d929a5ae1f3166ec56e54239f40e6137f6d2c2 (repair: Add table_id
to row_level_repair), a call to find_column_family() was added in
repair_range. In case of the table is dropped, it will fail the
repair_range which in turn fails the bootstrap operation.
Tests: update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_add_new_node_while_schema_changes_test
Fixes: #5942

repair: Handle dropped table in repair_range

---

dist/debian/python3/build_deb.sh
dist/debian/python3/debian_files_gen.py

Sync version number fixup from main package, contains #6546 and #6752 fixes.
Note that scylla-python3 likely does not affect this versioning issue,
since it uses python3 version, which normally does not contain 'rcX'.

dist/debian/python3: apply version number fixup on scylla-python3

---

dist/common/scripts/scylla-housekeeping

We could get "cannot serialize '_io.BufferedReader' object" when request get 404 error from the server
Now you will get legit error message in the case.
Fixes - https://github.com/scylladb/scylla/issues/6690

scylla-housekeeping: wrap urllib.request with try ... except

---

gms/gossiper.cc
gms/gossiper.hh

It is not used any more after 75cf1d18b512baeadb3445a7db7d63c90eafb322
(storage_service: Unify handling of replaced node removal from gossip)
in the "Make replacing node take writes" series.
Refs #5482

gossiper: Drop unused replaced_endpoint

---

dist/common/scripts/scylla_util.py

It seems distro.id() is NOT always same output as ID in /etc/os-release.
We need to replace "ol" to "oracle", "amzn" to "amazon".
Fixes #6761

scylla_util.py: use correct ID value for distro.id()

---

cql3/restrictions/statement_restrictions.cc
test/boost/cql_query_test.cc

WHERE clauses with start point above the end point were handled
incorrectly.  When the slice bounds are transformed to interval
bounds, the resulting interval is interpreted as wrap-around (because
start > end), so it contains all values above 0 and all values below
0.  This is clearly incorrect, as the user's intent was to filter out
all possible values of a.
Fix it by explicitly short-circuiting to false when start > end.  Add
a test case.
Fixes #5799.

cql/restrictions: Handle `WHERE a>0 AND a<0`

---

dist/debian/debian/scylla-server.default
dist/debian/debian/scylla-server.node-exporter.service
dist/debian/debian/scylla-server.scylla-fstrim.service
dist/debian/debian/scylla-server.scylla-housekeeping-daily.service
dist/debian/debian/scylla-server.scylla-housekeeping-restart.service
dist/debian/debian/scylla-server.service
dist/debian/debian_files_gen.py

Instead of running shutil.copy() for each *.{service,default},
create symlink for these files.
Python will copy original file when copying debian directory.

debian: use symlink copying files to build/debian/debian/

---

dist/common/scripts/node_exporter_install

Stop node-exporter.service before re-install it, to avoid 'Text file busy' error.
Fixes #6782

node_exporter_install: stop service before force installing

---

dist/common/scripts/scylla_coredump_setup

"coredumpctl info" behavior had been changed since systemd-v232, we need to
support both version.
Before systemd-v232, it was simple.
It print 'Coredump' field only when the coredump exists on filesystem.
Otherwise print nothing.
After the change made on systemd-v232, it become more complex.
It always print 'Storage' field even the coredump does not exists.
Not just available/unavailable, it describe more:
- Storage: none
- Storage: journal
- Storage: /path/to/file (inacessible)
- Storage: /path/to/file
To support both of them, we need to detect message version first, then
try to detect coredump path.
Fixes: #6789
reference: https://github.com/systemd/systemd/commit/47f50642075a7a215c9f7b600599cbfee81a2913

scylla_coredump_setup: support older version of coredumpctl message format

---

db/commitlog/commitlog.cc
db/commitlog/commitlog.hh
db/hints/manager.cc

When commitlog is recreated in hints manager, only shutdown() method is
called, but not release(). Because of that, some internal commitlog
objects (`segment_manager` and `segment`s) may be left pointing to each
other through shared_ptr reference cycles, which may result in memory
leak when the parent commitlog object is destroyed.
This PR prevents memory leaks that may happen this way by calling
release() after shutdown() from the hints manager.
Fixes: #6409, #6776

hinted handoff: fix commitlog memory leak

---

reloc/python3/build_deb.sh

Fixes #6802 
While building unified-deb we first use scylla/reloc/build_deb.sh to create the scylla core package, and after that scylla/reloc/python3/build_deb.sh to create python3.
On 058da69#diff-4a42abbd0ed654a1257c623716804c82 a new rm -rf command was added.
It causes python3 process to erase Scylla-core process.
Set python3 to erase its own dir scylla-python3-package only.

build-deb.sh: fix rm to erase only python

---

message/messaging_service.cc
message/messaging_service.hh
repair/repair.hh
repair/row_level.cc
serializer_impl.hh

In one of the longevity tests, we observed 1.3s reactor stall which came from
repair_meta::get_full_row_hashes_source_op. It traced back to a call to
std::unordered_set::insert() which triggered big memory allocation and
reclaim.
I measured std::unordered_set, absl::flat_hash_set, absl::node_hash_set
and absl::btree_set. The absl::btree_set was the only one that seastar
oversized allocation checker did not warn in my tests where around 300K
repair hashes were inserted into the container.
- unordered_set:
hash_sets=295634, time=333029199 ns
- flat_hash_set:
hash_sets=295634, time=312484711 ns
- node_hash_set:
hash_sets=295634, time=346195835 ns
- btree_set:
hash_sets=295634, time=341379801 ns
The btree_set is a bit slower than unordered_set but it does not have
huge memory allocation. I do …

repair: Switch to btree_set for repair_hash.

---

test/boost/cql_query_test.cc

cquery_nofail returns the query result, not a future.  Invoking .get()
on its result is unnecessary.  This just happened to compile because
shared_ptr has a get() method with the same signature as future::get.
Tests: cql_query_test unit test (dev)

cql_query_test: Drop get() on cquery_nofail result

---

dist/common/scripts/scylla_prepare

Let's report each missing CPU feature individually, and improve the
error message a bit. For example, if the "clmul" instruction is missing,
the report looks as follows:
ERROR: You will not be able to run Scylla on this machine because its CPU lacks the following features: pclmulqdq
If this is a virtual machine, please update its CPU feature configuration or upgrade to a newer hypervisor.
Fixes #6528

scylla_prepare: Improve error message on missing CPU features

---

dist/common/scripts/scylla_raid_setup
dist/common/scripts/scylla_setup
dist/debian/debian/scylla-server.postrm
dist/redhat/scylla.spec

Since we already use systemd unit file for coredump bind mount and swapfile,
we should move to systemd mount unit for data partition as well.

scylla_raid_setup: switch to systemd mount unit

---

repair/row_level.cc

In case a row hash conflict, a hash in set_diff will get more than one
row from get_row_diff.
For example,
Node1 (Repair master):
row1  -> hash1
row2  -> hash2
row3  -> hash3
row3' -> hash3
Node2 (Repair follower):
row1  -> hash1
row2  -> hash2
We will have set_diff = {hash3} between node1 and node2, while
get_row_diff({hash3}) will return two rows: row3 and row3'. And the
error below was observed:
repair - Got error in row level repair: std::runtime_error
(row_diff.size() != set_diff.size())
In this case, node1 should send both row3 and row3' to peer node
instead of fail the whole repair. Because node2 does not have row3 or
row3', otherwise node1 won't send row with hash3 to node1 in the first
place.
Refs: #6252

repair: Relax size check of get_row_diff and set_diff

---

alternator/executor.cc
alternator/stats.cc
alternator/stats.hh
api/api.hh
api/column_family.cc
api/column_family.hh
database.hh
db/view/row_locking.cc
db/view/row_locking.hh
service/paxos/paxos_state.cc
table.cc

This series is a continuation of the series that introduced the time_estimated_histogram.
time_estimated_histogram is more efficient and uses a higher reporting resolution.
See  #5815 and  #4746

Switch Estimated histogram to time_estimated_histogram latency

---

api/api-doc/storage_service.json
api/storage_service.cc
repair/repair.cc
repair/repair.hh

This new api blocks until the repair job is either finished or failed.
E.g., curl -X GET http://127.0.0.1:10000/storage_service/repair_status/?id=123
The current asynchronous api returns immediately even if the repair is in progress.
E.g., curl -X GET http://127.0.0.1:10000/storage_service/repair_async/ks?id=123
User can use the new synchronous API to avoid keep sending the query to
poll if the repair job is finished.
Fixes #6445

repair: Add synchronous API to query repair status

---

locator/token_metadata.cc

Currently, when update_normal_tokens is called, a warning logged.
Token X changing ownership from A to B
It is not correct to log so because we can call update_normal_tokens
against a temporary token_metadata object during topology calculation.
Refs: 6437

token_metadata: Fix incorrect log in update_normal_tokens

---

locator/token_metadata.cc
service/storage_service.cc

1) storage_service: Make handle_state_left more robust when tokens are empty
In case the tokens for the node to be removed from the cluster are
empty, log the application_state of the leaving node to help understand
why the tokens are empty and try to get the tokens from token_metadata.
2) token_metadata: Do not throw if empty tokens are passed to remove_bootstrap_tokens
Gossip on_change callback calls storage_service::excise which calls
remove_bootstrap_tokens to remove the tokens of the leaving node from
bootstrap tokens. If empty tokens, e.g., due to gossip propagation issue
as we saw in https://github.com/scylladb/scylla/issues/6468, are passed
to remove_bootstrap_tokens, it will throw. Since the on_change callback
is marked as noexcept, such throw will cause the node to terminate …

Make handle_state_left more robust when tokens are empty

---

dist/common/scripts/scylla_raid_setup

To use UUID, we need a tag "UUID=<uuid>".
reference: https://www.freedesktop.org/software/systemd/man/systemd.mount.html
reference: https://man7.org/linux/man-pages/man8/mount.8.html

scylla_raid_setup: fix incorrect block device path

---

repair/repair.cc
repair/repair.hh

Currently, repair uses an integer to identify a repair job. The repair
id starts from 1 since node restart. As a result, different repair jobs
will have same id across restart.
To make the id more unique across restart, we can use an uuid in
addition to the integer id. We can not drop the use of the integer id
completely since the http api and nodetool use it.
Fixes #6786

repair: Add uuid to a repair job

---

cql3/restrictions/restriction.hh
cql3/restrictions/statement_restrictions.cc
cql3/single_column_relation.cc
cql3/statements/delete_statement.cc
test/boost/restrictions_test.cc

Fix #6825 by explicitly distinguishing single- from multi-column expressions in AST.
Tests: unit (dev), dtest secondary_indexes_test.py (dev)

Distinguish single-column expressions in AST

---

db/schema_tables.cc

When upgrading from a version that lacks some schema features,
during the transition, when we have a mixed cluster. Schema digests
are calculated without taking into account the mixed cluster supported
features. Every node calculate the digest as if the whole cluster supports
its supported features.
Scylla already has a mechanism of redaction to the lowest common
denominator, but it haven't been used in this context.
This commit is using the redaction mechanism when calculating the digest on
the newly added table so it will match the supported features of the
whole cluster.
Tests: Manual upgrading - upgraded to a version with an additional
feature and additional schema column and validated that the digest
of the tables schema is identical on every node on the mixed cluster.

schema: take into account features when converting a table creation to schema_mutations

---

dist/common/scripts/scylla_setup

scylla_setup: abort RAID disk prompt when no free disks available

---

dist/common/scripts/scylla_setup
dist/docker/redhat/commandlineparser.py
dist/docker/redhat/scyllasetup.py
docs/docker-hub.md

This adds a '--io-setup N' command line option, which users can pass to
specify whether they want to run the "scylla_io_setup" script or not.
This is useful if users want to specify I/O settings themselves in
environments such as Kubernetes, where running "iotune" is problematic.
While at it, add the same option to "scylla_setup" to keep the interface
between that script and Docker consistent.
Fixes #6587

docker: Make I/O configuration setup configurable

---

cql3/restrictions/statement_restrictions.cc
cql3/statements/delete_statement.cc

This takes care of some follow-up requests from the #5763 review.
Use concepts to explicitly state some interface constraints, and rename `find_if` to `find_atom`.

Follow-up to CQL restrictions rewrite

---

dist/common/scripts/scylla_setup

Selected list on disk prompt is looks like an alternatives, it's better to use
single quote.
Fixes #6760

scylla_setup: remove square bracket from disk prompt selected list

---

locator/token_metadata.cc
service/storage_service.cc

The log "removing pending replacing node" is printed whenever a node
jumps to normal status including a normal restart. For example, on
node1, we saw the following when node2 restarts.
[shard 0] storage_service - Node 127.0.0.2 state jump to normal
[shard 0] storage_service - Remove node 127.0.0.2 from pending replacing endpoint
This is confusing since no node is really being replaced.
To fix, log only if a node is really removed from the pending replacing
nodes.
In addition, since do_remove_node will call del_replacing_endpoint,
there is no need to call del_replacing_endpoint again in
storage_service::handle_state_normal after do_remove_node.
Fixes #6936

storage_service: Improve log on removing pending replacing node

---

repair/row_level.cc

We saw scylla hit user after free in repair with the following procedure during tests:
- n1 and n2 in the cluster
- n2 ran decommission
- n2 sent data to n1 using repair
- n2 was killed forcely
- n1 tried to remove repair_meta for n1
- n1 hit use after free on repair_meta object
This was what happened on n1:
1) data was received -> do_apply_rows was called -> yield before create_writer() was called
2) repair_meta::stop() was called -> wait_for_writer_done() / do_wait_for_writer_done was called
with _writer_done[node_idx] not engaged
3) step 1 resumed, create_writer() was called and _repair_writer object was referenced
4) repair_meta::stop() finished, repair_meta object and its member _repair_writer was destroyed
5) The fiber created by create_writer() at step 3 hit use after free on …

repair: Fix race between create_writer and wait_for_writer_done

---

scylla_post_install.sh

On CentOS7, systemd does not support percentage-based parameter.
To apply memory parameter on CentOS7, we need to override the parameter
in bytes, instead of percentage.
Fixes #6783

scylla_post_install.sh: generate memory.conf for CentOS7

---

dist/common/scripts/scylla_raid_setup
dist/common/scripts/scylla_util.py
scripts/create-relocatable-package.py

To mount RAID volume correctly (#6876), we need to wait for MDRAID initialization.
To do so we need to add After=mdmonitor.service on var-lib-scylla.mount.
Also, `lsblk -n -oPARTTYPE {dev}` does not work for CentOS7, since older lsblk does not supported PARTTYPE column (#6954).
We need to provide relocatable lsblk and run it on out() / run() function instead of distribution provided version.

Mount RAID volume correctly beyond reboot

---

cdc/cdc_options.hh
cdc/log.cc
mutation_partition.hh
test/cql/cdc_delta_modes_test.cql
test/cql/cdc_delta_modes_test.result

The goal is to have finer control over CDC "delta" rows, i.e.:
- disable them totally (mode `off`);
- record only base PK+CK columns (mode `keys`);
- make them behave as usual (mode `full`, default).
The editing of log rows is performed at the stage of `finish`ing CDC mutation.
Fixes #6838

cdc: New delta modes: `off`, `keys`, `fulll`

---

dist/common/scripts/scylla_raid_setup
dist/common/scripts/scylla_setup

We should run var-lib-scyllla.mount existance check before formatting RAID.

scylla_setup: check var-lib-scylla.mount existance before formatting RAID

---

conf/scylla.yaml
db/config.cc
db/config.hh
docs/protocol-extensions.md
transport/controller.cc
transport/server.cc
transport/server.hh

This is inspired by #6781. The idea is to make Scylla listen for CQL connections on port 9042 (where both old shard-aware and shard-unaware clients can still connect the traditional way). On top of that I added a new port, where everything works the same way, only the port from client's socket used to determine the shard No. to connect to. Desired shard No. is the result of `clientside_port % num_shards`.
The new port is configurable from scylla.yaml and defaults to 19042 (unencrypted, unless user configures encryption options and omits `native_shard_aware_transport_port_ssl` in DB config).
Two "SUPPORTED" tags are added: "SCYLLA_SHARD_AWARE_PORT" and "SCYLLA_SHARD_AWARE_PORT_SSL". For compatibility, "SCYLLA_SHARDING_ALGORITHM" is still kept.
Fixes #5239

transport: Added listener with port-based load balancing

---

cql3/statements/delete_statement.cc

A couple of previous PRs received feedback on the tombstone-range check in delete_statement.  This PR implements it.

Implement prior feedback for tombstone-range checks

---

repair/repair.cc
repair/repair.hh

This series adds progress metrics for the node operations. Metrics for bootstrap and rebuild progress are added as a starter. I will add more for the remaining operations after getting feedback.
With this the Scylla Monitor and Scylla Manager can know the progress of the bootstrap and other node operations. E.g.,
```
scylla_node_ops_bootstrap_nr_ranges_finished{shard="0",type="derive"} 50
scylla_node_ops_bootstrap_nr_ranges_total{shard="0",type="derive"} 1040
```
Fixes #1244, #6733

repair: Add progress metrics for node ops

---

database.cc

Fixes #6995
In c2c6c71 the assert on replay positions in flushed sstables discarded by
truncate was broken, by the fact that we no longer flush all sstables
unless auto snapshot is enabled.
This means the low_mark assertion does not hold, because we maybe/probably
never got around to creating the sstables that would hold said mark.
Note that the (old) change to not create sstables and then just delete
them is in itself good. But in that case we should not try to verify
the rp mark.

database: Do not assert on replay positions if truncate does not flush

---

dist/common/scripts/scylla_raid_setup
dist/common/scripts/scylla_util.py

On older Debian variants does not have mdmonitor.service, we should use
mdadm.service instead.
Fixes #7000

scylla_raid_setup: use mdadm.service on older Debian variants

---

configure.py
repair/row_level.cc
test/boost/stall_free_test.cc
utils/stall_free.hh

This path set fixes stalls in repair that are caused by std::list merge and clear operations during test_latency_read_with_nemesis test. 
Fixes #6940
Fixes #6975
Fixes #6976

Fix repair stalls in get_sync_boundary and apply_rows_on_master_in_thread

---

auth/service.cc

The service constructor included a check ensuring that only
standard_role_manager can be used with password_authenticator. But
after 00f7bc6, password_authenticator does not depend on any action of
standard_role_manager. All queries to meta::roles_table in
password_authenticator seem self-contained: the table is created at
the start if missing, and salted_hash is CRUDed independently of any
other columns bar the primary key role_col_name.
NOTE: a nonstandard role manager may not delete a role's row in
meta::roles_table when that role is dropped. This will result in
successful authentication for that non-existing role. But the clients
call check_user_can_login() after such authentication, which in turn
calls role_manager::exists(role). Any correctly implemented role
manager will then …

auth: Drop needless role-manager check

---

conf/scylla.yaml
docs/protocols.md
transport/controller.cc

Let users disable the unencrypted native transport too by setting the port to
zero in the scylla.yaml configuration file.
Fixes #6997

transport: Allow user to disable unencrypted native transport

---

db/commitlog/commitlog.cc

Refs #6148
Separates disk usage into two cases: Allocated and used.
Since we use both reserve and recycled segments, both
which are not actually filled with anything at the point
of waiting.
Also refuses to recycle segments or increase reserve size
if our current disk footprint exceeds threshold.
And finally uses some initial heuristics to determine when
we should suggest flushing, based on disk limit, segment
size, and current usage. Right now, when we only have
a half segment left before hitting used == max.
Some initial tests show an improved adherence to limit
though it will still be exceeded, because we do _not_
force waiting for segments to become cleared or similar
if we need to add data, thus slow flushing can still make
usage create extra segments. We will however attempt to …

Make commitlog respect disk limit better

---

repair/row_level.cc

It is pretty hard to find the repair_meta object when debugging a core.
This patch makes it is easier by putting repair_meta object created by
both repair follower and master into a map.
Fixes #7009

repair: Track repair_meta created on both repair follower and master

---

database.hh
db/hints/manager.cc
db/hints/resource_manager.cc
db/hints/resource_manager.hh
db/view/view.cc
db/view/view_builder.hh
db/view/view_update_generator.cc
db/view/view_update_generator.hh
table.cc

This series addresses various issues with metrics and semaphores - it mainly adds missing metrics, which makes it possible to see the length of the queues attached to the semaphores. In case of view building and view update generation, metrics was not present in these services at all, so a first, basic implementation is added.
More precise semaphore metrics would ease the testing and development of load shedding and admission control.

Add metrics to semaphores

---

alternator/streams.cc
cdc/cdc_options.hh
cdc/log.cc
test/boost/cdc_test.cc

Changes the "preimage" option from binary true/false to on/off/full (accepting true/false, and using old style notation for normal to string - for upgrade reasons), where "full" will force us to include all columns in pre image log rows. 
Adds small test (just adding the case to preimage test). 
Uses the feature in alternator
Fixes #7030

CDC: allow "full" preimage in logs

---

gms/gossiper.cc

1. The node1 is shutdown
2. The node1 sends shutdown message to node2
3. The node2 receives gossip shutdown message but the handler yields
4. The node1 is restarted
5. The node1 sends new gossip endpoint_state to node2, node2 applies the state
in apply_state_locally and calls gossiper::handle_major_state_change
and then calls gossiper::mark_alive
6. The shutdown message handler in step 3 resumes and sets status of node1 to SHUTDOWN
7. The gossiper::mark_alive fiber in step 5 resumes and calls gossiper::real_mark_alive,
node2 will skip to mark node1 as alive because the status of node1 is
SHUTDOWN. As a result, node1 is alive but it is not marked as UP by node2.
To fix, we serialize the two operations.
Fixes #7032

gossip: Fix race between shutdown message handler and apply_state_local

---

gms/gossiper.cc
gms/gossiper.hh
idl/gossip_digest.idl.hh
message/messaging_service.cc
message/messaging_service.hh
service/storage_service.cc
service/storage_service.hh

gossip: Get rid of seed concept
The concept of seed and the different behaviour between seed nodes and
non seed nodes generate a lot of confusion, complication and error for
users. For example, how to add a seed node into into a cluster, how to
promote a non seed node to a seed node, how to choose seeds node in
multiple DC setup, edit config files for seeds, why seed node does not
bootstrap.
If we remove the concept of seed, it will get much easier for users.
After this series, seed config option is only used once when a new node
joins a cluster.
Major changes:
- Seed nodes are only used as the initial contact point nodes.
- Seed nodes now perform bootstrap. The only exception is the first node
in the cluster.
- The unsafe auto_bootstrap option is now ignored.
- Gossip shadow round now …

Get rid of seed concept in gossip

---

scylla-gdb.py

It is needed to print the boost::intrusive::list which is used
by repair_meta_for_masters in repair.
Fixes #7037
Signed-off-by: Botond Dénes <bdenes@scylladb.com>
Signed-off-by: Asias He <asias@scylladb.com>

scylla-gdb.py: Add boost_intrusive_list_printer

---

test/boost/user_types_test.cc

This testcase was temporarily commented out in 37ebe52, because it
relied on buggy (#6369) behaviour fixed by that commit.  Specifically,
it expected a NULL comparison to match a NULL cell value.  We now
bring it back, with corrected result expectation.

test: Restore a case in user_types_test

---

dist/debian/debian/rules

Since older binutils on some distribution does not able to handle
compressed debuginfo generated on Fedora, we need to disable it.
However, debian packager force debuginfo compression since debian/compat = 9,
we have to uncompress them after compressed automatically.
Fixes #6982

dist/debian: disable debuginfo compression on .deb

---

alternator/expressions.cc
cql3/expr/expression.cc
cql3/functions/castas_fcts.cc
database.cc
keys.cc
mutation_fragment.hh
position_in_partition.hh
sstables/compaction_strategy.cc
test/boost/view_complex_test.cc
thrift/handler.cc
unimplemented.cc
utils/murmur_hash.cc
utils/murmur_hash.hh

Quoth @avikivity: "switch is not a function, and we celebrate that by
putting a space after it like other control-flow keywords."
https://github.com/scylladb/scylla/pull/7052#discussion_r471932710

everywhere: Insert space after `switch`

---

cdc/change_visitor.hh
cdc/log.cc
cdc/split.cc

These abstractions are used for walking over mutations created by a write
coordinator, deconstructing them into ``atomic'' pieces (``changes''),
and consuming these pieces.
Read the big comment in cdc/change_visitor.hh for more details.
4 big functions were rewritten to use the new abstractions.
tests: 
- unit (dev build)
- all dtests from cdc_tests.py, except `cdc_tests.py:TestCdc.cluster_reduction_with_cdc_test`, have passed (on a dev build). The test that fails also fails on master.
Part of https://github.com/scylladb/scylla/issues/5945.

cdc: introduce a ,,change visitor'' and ,,inspect mutation'' abstractions

---

dist/common/scripts/scylla_setup
dist/common/scripts/scylla_util.py
install.sh

To verify offline installed image with do_verify_package() in scylla_setup, we introduce is_offline() function works just like is_nonroot() but the install not with --nonroot.

Do verify package for offline

---

cql3/expr/expression.hh
cql3/restrictions/multi_column_restriction.hh
cql3/single_column_relation.cc
cql3/single_column_relation.hh
cql3/statements/select_statement.cc

Instantiating binary_operator directly is more readable.

cql3/expr: Drop make_column_op()

---

gms/gossiper.cc

We saw errors in killed_wiped_node_cannot_join_test dtest:
Aug 2020 10:30:43 [node4] Missing: ['A node with address 127.0.76.4 already exists, cancelling join']:
The test does:
n1, n2, n3, n4
wipe data on n4
start n4 again with the same ip address
Without this patch, n4 will bootstrap into the cluster new tokens. We
should prevent n4 to bootstrap because there is an existing
node in the cluster.
In shadow round, the local node should apply the application state of
the node with the same ip address. This is useful to detect a node
trying to bootstrap with the same IP address of an existing node.
Tests: bootstrap_test.py
Fixes: #7073

gossip: Apply state for local node in shadow round

---

alternator/streams.cc
cdc/log.cc
test/alternator/test_streams.py
test/boost/cdc_test.cc
test/cql/cdc_delta_modes_test.cql
test/cql/cdc_delta_modes_test.result
test/cql/cdc_static_and_clustered_rows_test.result
test/cql/cdc_with_lwt_test.result

Fixes #6935
DynamoDB streams for some reason duplicate the record keys
into both the "Keys" and "OldImage"/"NewImage" sub-objects
when doing GetRecords. But only if there is other data
to include.
This patch appends the pk/ck parts into old/new image
iff we had any record data.
Updated to handle keys-only updates, and distinguish creating vs. updating rows. Changes cdc to not generate preimage 
for non-existent/deleted rows, and also fixes missing operations/ttls in keys-only delta mode.

alternator_streams: Include keys in OldImage/NewImage

---

service/storage_service.cc

The get_natural_endpoints returns the list of nodes holding a key.
There is a variation of the method that gets the key as string, the
current implementation just cast the string to bytes_view, which will
not work. Instead, this patch changes the implementation to use
from_nodetool_style_string to translate the key (in a nodetool like
format) to a token.
Fixes #7134

storage_service.cc: get_natural_endpoints should translate key

---

install.sh
unified/install.sh

On older distribution such as CentOS7, it does not support systemd user mode.
On such distribution nonroot mode does not work, show error message and
reject installing before copying files.
Fixes #7071

install.sh: show warning when systemd does not support user mode

---

install.sh
unified/install.sh

1. scylla setup scripts doesn't work, because python3 path isn't correct in creating relocatable packages if user doesn't set python3 path in running unified/install.sh. This PR fixed the problem by setting the default python3 value according to the install mode (root/nonroot).
2. another patch cleaned the tmp scylla.yaml after installation

offline installation: fix default value of python3/sysconfdir and a small cleanup

---

cdc/cdc_options.hh
cdc/log.cc
test/cql/cdc_delta_modes_test.cql
test/cql/cdc_delta_modes_test.result

Refs #7095
Fixes #7128
CDC delta!=full both relied on post-filtering
to remove generated log row and/or cells. This is inefficient.
Instead, simply check if the data should be created in the
visitors.
v2:
* Fixed delta logs rows created (empty) even when delta == off
v3:
* Killed delta == off (patch in series)

cdc: Remove post-filterings for keys-only/off cdc delta generation

---

cql3/restrictions/statement_restrictions.cc
cql3/restrictions/statement_restrictions.hh

cql3: Drop get_partition_key_unrestricted_components

---

cql3/restrictions/statement_restrictions.cc

statement_restrictions::process_partition_key_restrictions() was
checking has_unrestricted_components(), whereas just an empty() check
suffices there, because has_unrestricted_components() is implicitly
checked five lines down by needs_filtering().
The replacement check is cheaper and simpler to understand.

cql3: Simplify pk test in statement_restrictions

---

db/system_keyspace.cc

Make `enable_cache` configuration option also affect caching of system keyspaces. Fixes #2909.
It makes `--enable-cache` command-line option change caching of system keyspaces (`system`, `system_schema`). 
Manually verified that after setting `--enable-cache false`, no calls to caching were performed (added debug prints) - previously caching was still performed in system keyspaces.

db: Propagate enable_cache to system keyspaces

---

bytes.hh
lua.cc
test/boost/user_function_test.cc
test/boost/utf8_test.cc
transport/request.hh
types.cc
utils/utf8.cc
utils/utf8.hh

Before this change, if there was a UTF-8 validation error, Scylla provided no further information about location of invalid character inside the offending string.
Added new `validate_with_error_position` function, which returns a position of invalid UTF-8 byte in a string. Modified all "invalid UTF-8" exception messages to present a location information to user (below - in bold highlighted added new text):
- Invalid UTF-8 string inside prepared statement argument:
`exceptions::invalid_request_exception: Exception while binding column b: marshaling error: Validation failed - non-UTF8 character in a UTF8 string,` **`at byte offset 0`**
- Server-side message returned to the Java Cassandra client:
`Exception in thread "main" com.datastax.oss.driver.api.core.servererrors.ProtocolError: Cannot …

utf8: Print invalid UTF-8 character position

---

alternator/executor.cc
alternator/executor.hh
alternator/streams.cc
cdc/cdc_options.hh

Stream descriptions, as returned from create, update and describe stream was missing "latest" stream arn. 
Shard descriptions sequence number (for us timeuuid:s) were formatted wrongly. The spec states they should be numeric only. 
Both these defects break Kinesis operations. 
v2: 
* Fixed sequence number in getrecords

Alternator streams - fix table description and sequence number

---

cql3/statements/alter_type_statement.cc
test/cql/forbid_adding_to_udt_used_in_partkey_test.cql
test/cql/forbid_adding_to_udt_used_in_partkey_test.result

Changing a user type may allow adding duplicate rows to tables where
this type is used in a partitioning key. Fix by checking all types
of existing partitioning columns before allowing to add new fields to
the type.
Fixes #6941

cql: Forbid adding new fields to UDTs used in partition key columns

---

main.cc
service/storage_proxy.cc
service/storage_proxy.hh

Hints writes are handled by storage_proxy in the exact same way
regular writes are, which in turn means that the same smp service
group is used for both. The problem is that it can lead to a priority
inversion where writes of the lower priority  kind occupies a lot of
the semaphores units making the higher priority writes wait for an
empty slot.
This series adds a separate smp group for hints as well as a field
to pass the correct smp group to mutate_locally functions, and
then uses this field to properly classify the writes.
Fixes #7177

storage_proxy: add a separate smp_group for hints

---

install.sh
unified/install.sh

This is v2 of 7089, removed key press waiting since it likely breaked next build
----
On older distribution such as CentOS7, it does not support systemd user mode.
On such distribution nonroot mode does not work, show warning message and
skip running systemctl --user.
Fixes #7071

install.sh: show warning nonroot mode when systemd does not support user mode

---

dist/common/scripts/scylla_prepare
dist/common/scripts/scylla_util.py

When configuration files for perftune contain invalid parameter, scylla_prepare
may cause traceback because error handling is not eough.
Throw all errors from create_perftune_conf(), catch them on scylla_prepare,
proceed running scylla w/o using perftune.
Fixes #6847

dist/common/scripts:  abort scylla_prepare with better error message

---

digest_algorithm.hh
digester.hh
gms/feature.hh
gms/feature_service.cc
gms/feature_service.hh
mutation_partition.cc
mutation_partition.hh
service/storage_proxy.cc
test/boost/mutation_test.cc
xx_hasher.hh

This series fixes a bug in `appending_hash<row>` that caused it to ignore any cells after the first NULL. It also adds a cluster feature which starts using the new hashing only after the whole cluster is aware of it. The series comes with tests, which reproduce the issue.
Fixes #4567
Based on #4574

Fix ignoring cells after null in appending hash

---

unified/install.sh

Currently, we run openjdk existance check after scylla main program installed.
We should do it before installing anything.

unified: don't proceed offline install when openjdk is not available

---

database.cc
main.cc
sstables/sstables.cc
sstables/sstables.hh
sstables/sstables_manager.cc
sstables/sstables_manager.hh
table.cc
test/boost/broken_sstable_test.cc
test/boost/mutation_reader_test.cc
test/boost/mutation_test.cc
test/boost/schema_changes_test.cc
test/boost/sstable_3_x_test.cc
test/boost/sstable_conforms_to_mutation_source_test.cc
test/boost/sstable_datafile_test.cc
test/boost/sstable_directory_test.cc
test/boost/sstable_mutation_test.cc
test/boost/sstable_resharding_test.cc
test/boost/sstable_test.cc
test/boost/view_build_test.cc
test/lib/cql_test_env.cc
test/lib/sstable_test_env.hh
test/lib/sstable_utils.hh
test/lib/test_services.cc
test/lib/test_services.hh
test/perf/perf_sstable.hh

Currently, sstable_manager is used to create sstables, but it loses track
of them immediately afterwards. This series makes an sstable's life fully
contained within its sstable_manager.
The first practical impact (implemented in this series) is that file removal
stops being a background job; instead it is tracked by the sstable_manager,
so when the sstable_manager is stopped, you know that all of its sstable
activity is complete.
Later, we can make use of this to track the data size on disk, but this is not
implemented here.

sstables: make sstable_manager control the lifetime of the sstables it manages

---

dist/common/scripts/scylla_setup

hugepages and libhugetlbfs-bin packages is only required for DPDK mode,
and unconditionally installation causes error on offline mode, so drop it.
Fixes #7182

scylla_setup: drop hugepages package installation

---

locator/token_metadata.cc
locator/token_metadata.hh
service/storage_service.cc

This PR removes  _pending_ranges and _pending_ranges_map in token_metadata.
This removal of  makes copying of token_metadata faster and reduces the chance to cause reactor stall.
Refs: #7220

Remove _pending_ranges and _pending_ranges_map in token_metadata

---

dist/common/scripts/scylla_coredump_setup
dist/common/scripts/scylla_cpuscaling_setup
dist/common/scripts/scylla_kernel_check
dist/common/scripts/scylla_ntp_setup
dist/common/scripts/scylla_raid_setup
dist/common/scripts/scylla_setup
dist/common/scripts/scylla_util.py

We need to skip internet access on offline installation.
To do this we need following changes:
- prevent running yum/apt for each script
- set default "NO" for scripts it requires package installation
- set default "NO" for scripts it requires internet access, such as NTP
See #7153

dist/common/scripts: skip internet access on offline installation

---

dist/common/scripts/scylla_ntp_setup

To simplify scylla_ntp_setup, use chrony on all distributions.

scylla_ntp_setup: use chrony on all distributions

---

alternator/error.hh
alternator/server.cc
alternator/server.hh
alternator/stats.cc
alternator/stats.hh
main.cc

Note: this pull request is temporarily created against /next, because it depends on https://github.com/scylladb/scylla/pull/7279.
This series adds support for `max_concurrent_requests_per_shard` config variable to alternator. Excessive requests are shed and RequestLimitExceeded is sent back to the client.
Tested manually by reloading Scylla multiple times and editing the config, while bombarding alternator with many concurrent requests. Observed excepted failures are:
`botocore.errorfactory.RequestLimitExceeded: An error occurred (RequestLimitExceeded) when calling the CreateTable operation: too many in-flight requests: 17
`
Fixes #7294

Add max concurrent requests to alternator

---

fix_system_distributed_tables.py
table_helper.cc
table_helper.hh
tracing/trace_keyspace_helper.cc

In order to improve observability, add a userspace field to the the system_traces.sessions table.
Fixes #6737.

tracing: add username to the session table

---

tracing/trace_keyspace_helper.cc

`trace_keyspace_helper::make_slow_query_mutation_data` expected a
"query" key in its parameters, which does not appear in case of
e.g. batches of prepared statements. This is example of failing
`record.parameters`:
```
...{"query[0]" : "INSERT INTO ks.tbl (pk, i) values (?, ?);"},
{"query[1]" : "INSERT INTO ks.tbl (pk, i) values (?, ?);"}...
```
In such case Scylla recorded no trace and said:
```
ERROR 2020-09-28 10:09:36,696 [shard 3] trace_keyspace_helper - No
"query" parameter set for a session requesting a slow_query_log record
```
Fix here is to leave query empty if not found. The users can still
retrieve the query contents from existing info in `system_traces.node_slow_log`.
Fixes #5843

tracing: Fix error on slow batches v2

---

table.cc

Fix a race condition in on_compaction_completion() that can prevent shutdown, as well as an exception handling error. See individual patches for details.
Fixes #7331.

table: fix race and exception handling in on_compaction_completion()

---

alternator/error.hh
alternator/streams.cc
cdc/generation.hh
test/alternator/test_streams.py

The remains of the defunct #7246. 
Fixes #7344
Fixes #7345
Fixes #7346
Fixes #7347
Shard ID length is now within limits.
Shard end sequence number should be set when appropriate.
Shard parent is selected a bit more carefully (sorting)
Shards are filtered by time to exclude cdc generations we cannot get data from (too old)
Shard paging improved

Alternator streams: Fix shard lengths, parenting, expiration, filter useless ones and improve paging

---

cql3/restrictions/token_restriction.hh
test/boost/restrictions_test.cc

Before this change, invalid query exception on selects with both normal and token restrictions was only thrown when token restriction was after normal restriction. 
This change adds proper validation when token restriction is before normal restriction.
**Before the change - does not return error in last query; returns wrong results:**
```
cqlsh> CREATE TABLE ks.t(pk int, PRIMARY KEY(pk));
cqlsh> INSERT INTO ks.t(pk) VALUES (1);
cqlsh> INSERT INTO ks.t(pk) VALUES (2);
cqlsh> INSERT INTO ks.t(pk) VALUES (3);
cqlsh> INSERT INTO ks.t(pk) VALUES (4);
cqlsh> SELECT pk, token(pk) FROM ks.t WHERE pk = 2 AND token(pk) > 0;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Columns "ColumnDefinition{name=pk, type=org.apache.cassandra.db.marshal.Int32Type, kind=PARTITION_KEY, …
```

token_restriction: invalid_request_exception on SELECTs with both normal and token restrictions

---

db/view/view.cc
db/view/view.hh
schema_registry.cc

schema pointers can be obtained from two distinct entities,
one is the database, those schema are obtained from the table
objects and the other is from the schema registry.
When a schema or a new schema is attached to a table object that
represents a base table for views, all of the corresponding attached
view schemas are guarantied to have their base info in sync.
However if an older schema is inserted into the registry by other way
of just becoming obsolete e.g loaded from other node, it will be
missing this info.
This becomes a problem when this schema is published through the
schema registry as it can be obtained for an obsolete read command
for example and then eventually cause a segmentation fault by null
dereferencing the _base_info ptr.
Refs #7420

materialized views: add a base table reference if missing

---

db/view/view.cc
db/view/view.hh
service/migration_manager.cc

This PR purpose is to handle schema integrity issues that can arise in races involving materialized views.
The possibility of such integrity issues was found in #7420 , where a view schema was used for reading without
it's _base_info member initialized resulting in a segfault.
We handle this doing 3 things:
1. First guard against using an uninitialized base info - this will be considered as an internal error as it will indicate that
there is a path in our code that creates a view schema to be used for reads or writes but is not initializing the base info.
2. We allow the base info to be initialized also from partially matching base (most likely a newer one that this used to create the view).
3. We fix the suspected path that create such a view schema to initialize it. (in migration …

view info: preserve integrity by allowing base info for reads only and by initializing base info

---

db/view/view.cc
db/view/view.hh
service/migration_manager.cc

This is a backport of PR #7469 that did not apply cleanly to 4.2 with a trivial conflict, another commit that touched one of the files but in a completely different region.

Backport PR #7469 to 4.2

---

dist/common/scripts/node_exporter_install

We currently uses outdated version of node_exporter, let's upgrade to latest
version.
Fixes #7427

node_exporter_install: upgrade to latest release

---

cql3/statements/select_statement.cc
test/boost/secondary_index_test.cc

Fixes #7355.
Before this changes, there were a few invalid results of aggregates/GROUP BY on tables with secondary indexes (see below).
Unfortunately, it still does NOT fix the problem in issue #7043. Although this PR moves forward fixing of that issue, there is still a bug with `TOKEN(...)` in `WHERE` clauses of indexed selects that is not addressed in this PR. It will be fixed in my next PR.
It does NOT fix the problems in issues #7432, #7431 as those are out-of-scope of this PR and do not affect the correctness of results (only return a too large page).
Before the change, `GROUP BY` `SELECT`s with some `WHERE` restrictions on an indexed column would return invalid results (same grouped column values appearing multiple times):
```
CREATE TABLE ks.t(pk int, ck int, v int, PRIMARY KEY(pk, …
```

select_statement: Fix aggregate results on indexed selects

---

tools/scyllatop/livedata.py

This patch change the code that iterates over the metrics to use a copy
of the metrics names to make it safe to remove the metrics from the
metrics object.
Fixes #7488

scyllatop/livedata.py: Safe iteration over metrics

---

connection_notifier.cc
connection_notifier.hh
service/client_state.hh
transport/server.cc
transport/server.hh

This patch fills the following columns in `system.clients` table:
* `connection_stage`
* `driver_name`
* `driver_version`
* `protocol_version`
It also improves:
* `client_type` - distinguishes cql from thrift just in case
* `username` - now it displays correct username iff `PasswordAuthenticator` is configured.
What is still missing:
* SSL params (I'll happily get some advice here)
* `hostname` - I didn't find it in tested drivers
Refs #6946

transport/system_ks: Add more info to `system.clients`

---

cql3/statements/create_table_statement.cc
test/cql/counters_disallow_ttl_test.cql
test/cql/counters_disallow_ttl_test.result

In such attempt `invalid_request_exception` is thrown.
Also, a simple CQL test is added.
Fixes #6879

create_table_statement: Disallow default TTL on counter tables

---

database.hh
gms/gossiper.cc
gms/gossiper.hh
main.cc

Gossip currently runs inside the default (main) scheduling group. It is
fine to run inside default scheduling group. From time to time, we see
many tasks in main scheduling group and we suspect gossip. It is best
we can move gossip to a dedicated scheduling group, so that we can catch
bugs that leak tasks to main group more easily.
After this patch, we can check:
scylla_scheduler_time_spent_on_task_quota_violations_ms{group="gossip",shard="0"}
Fixes #7154

gossiper: Use dedicated gossip scheduling group

---

db/view/view.cc
db/view/view.hh

This series adds more context to debugging information in case a view gets out of sync with its base table.
A test was conducted manually, by:
1. creating a table with a secondary index
2. manually deleting computed column information from system_schema.computed_columns
3. restarting the target node
4. trying to write to the index
Here's what's logged right after the index metadata is loaded from disk:
```
ERROR 2020-10-30 12:30:42,806 [shard 0] view - Column idx_token in view ks.t_c_idx_index was not found in the base table ks.t
ERROR 2020-10-30 12:30:42,806 [shard 0] view - Missing idx_token column is caused by an incorrect upgrade of a secondary index. Please recreate index ks.t_c_idx_index to avoid future issues.
```
And here's what's logged during the actual failure - when Scylla …

Add debug context to views out of sync

---

install.sh
scripts/create-relocatable-package.py

Since scylla-ccm wants to skip systemctl, we need to support --packaging
in nonroot mode too.
Related: https://github.com/scylladb/scylla-ccm/pull/250
Related: scylladb/scylla-ccm#249
Related: #7187

install.sh: allow --packaging with nonroot mode

---

dist/common/scripts/scylla_util.py

when logging in to the GCE instance that is created from the GCE image it takes 10 seconds to understand that we are not running on AWS. Also, some unnecessary debug logging messages are printed:
```
bentsi@bentsi-G3-3590:~/devel/scylladb$ ssh -i ~/.ssh/scylla-qa-ec2 bentsi@35.196.8.86
Warning: Permanently added '35.196.8.86' (ECDSA) to the list of known hosts.
Last login: Sun Nov  1 22:14:57 2020 from 108.128.125.4
_____            _ _       _____  ____  
/ ____|          | | |     |  __ \|  _ \ 
| (___   ___ _   _| | | __ _| |  | | |_) |
\___ \ / __| | | | | |/ _` | |  | |  _ < 
____) | (__| |_| | | | (_| | |__| | |_) |
|_____/ \___|\__, |_|_|\__,_|_____/|____/ 
__/ |                       
|___/                        
Version:
666.development-0.20201101.6be9f4938
Nodetool:
nodetool …
```

improvements for GCE image

---

SCYLLA-VERSION-GEN

Now that scylla-ccm and scylla-dtest conform to PEP-440
version comparison (See https://www.python.org/dev/peps/pep-0440/)
we can safely change scylla version on master to be the development
branch for the next release.
The version order logic is:
4.3.dev is followed by
4.3.rc[i] followed by
4.3.[n]
Note that also according to
https://blog.jasonantman.com/2014/07/how-yum-and-rpm-compare-versions/
4.3.dev < 4.3.rc[i] < 4.3.[n]
as "dev" < "rc" by alphabetical order
and both "dev" and "rc*" < any number, based on the general
rule that alphabetical strings compare as less than numbers.
Refs scylladb/scylla-machine-image#79
Test: unit
Dtest: gating
Message-Id: <20201015151153.726637-1-bhalevy@scylladb.com>

SCYLLA-VERSION-GEN: change master version to 4.4.dev

---

repair/row_level.cc

repair: Use single writer for all followers
Currently, repair master create one writer for each follower to write
rows from follower to sstables. That are RF - 1 writers in total. Each
writer creates 1 sstable for the range repaired, usually a vnode range.
Those sstables for a given vnode range are disjoint.
To reduce the compaction work, we can create one writer for all the
followers. This reduces the number of sstables generated by repair
significantly to one per vnode range from RF - 1 per vnode range.
Fixes #7525

repair: Use single writer for all followers

---

dist/debian/debian_files_gen.py

Currently debian_files_gen.py mistakenly renames scylla-server.service to
"scylla-server." on non-standard product name environment such as
scylla-enterprise, it should be fix to correct filename.
Fixes #7423

dist/debian: fix typo for scylla-server.service filename

---

dist/common/scripts/scylla_util.py
install.sh

We currently set PATH for relocatable CLI tools in scylla_util.run() and
scylla_util.out(), but it doesn't work for perftune.py, since it's not part of
Scylla, does not use scylla_util module.
We can set PATH in python thunk instead, it can set PATH for all python scripts.
Fixes #7350

install.sh: set PATH for relocatable CLI tools in python thunk

---

cql3/restrictions/statement_restrictions.cc
cql3/restrictions/statement_restrictions.hh

Rewrite in a more readable way that will later allow us to split the WHERE expression in two: a storage-reading part and a post-read filtering part.
Tests: unit (dev,debug)

cql3: Rewrite the need_filtering logic

---

dist/common/scripts/scylla_util.py

DEBIAN_FRONTEND environment variable was added just for prevent opening
dialog when running 'apt-get install mdadm', no other program depends on it.
So we can move it inside of apt_install()/apt_uninstall() and drop scylla_env,
since we don't have any other environment variables.
To passing the variable, added env argument on run()/out().

dist/common/scripts/scylla_util.py: move DEBIAN_FRONTEND environment variable to apt_install()/apt_uninstall()

---

bytes_ostream.hh
cartesian_product.hh
cdc/log.cc
clustering_interval_set.hh
compound.hh
compound_compat.hh
counters.hh
db/size_estimates_virtual_reader.cc
locator/token_metadata.cc
locator/token_metadata.hh
sstables/compress.hh
types/listlike_partial_deserializing_iterator.hh
types/tuple.hh
utils/log_heap.hh

std::iterator is deprecated since C++17 so define all the required iterator_traits directly and stop using std::iterator at all.
More context: https://www.fluentcpp.com/2018/05/08/std-iterator-deprecated

Remove std::iterator usage

---

flat_mutation_reader.hh
mutation_reader.cc

It is now called `merging_reader`, and is used to change a `FragmentProducer`
that produces a non-decreasing stream of mutation fragments batches into
a `flat_mutation_reader` producing a non-decreasing stream of fragments.
The resulting stream of fragments is increasing except for places where
we encounter range tombstones (multiple range tombstones may be produced
with the same position_in_partition)
`merging_reader` is a simple adapter over `mutation_fragment_merger`.
The old `combined_mutation_reader` is simply a specialization of `merging_reader`
where the used `FragmentProducer` is `mutation_reader_merger`, an abstraction that
merges the output of multiple readers into one non-decreasing stream of fragment
batches.
There is no separate class for `combined_mutation_reader` now. …

mutation_reader: generalize `combined_mutation_reader`

---

cdc/generation.cc
cdc/generation.hh
service/storage_service.cc

After the concept of the seed nodes was removed we can distinguish
whether the node is the first node in the cluster or not.
Thanks to this we can avoid adding delay to the timestamp of the first
CDC generation.
The delay is added to the timestamp to make sure that all the nodes
in the cluster manage to learn about it before the timestamp becomes in the past.
It is safe to not add the delay for the first node because we know it's the only node
in the cluster and no one else has to learn about the timestamp.
Fixes #7645

Don't add delay to the timestamp of the first CDC generation

---

cdc/cdc_extension.hh
db/config.cc
db/config.hh
test/boost/cdc_test.cc
test/lib/cql_test_env.cc

Now that CDC is GA, it should be enabled in all the tests by default.
To achieve that the PR adds a special db::config::add_cdc_extension() helper which is used in cql_test_env
to make sure CDC is usable in all the tests that use cql_test_env.
As a result, cdc_tests can be simplified.
Finally, some trailing whitespaces are removed from cdc_tests.

Cleanup CDC tests after CDC became GA

---

db/hints/resource_manager.cc
db/hints/resource_manager.hh

Follow-up to https://github.com/scylladb/scylla/pull/6916.
- Fixes wrong usage of `resource_manager::prepare_per_device_limits`,
- Improves locking in `resource_manager` so that it is more safe to call its methods concurrently,
- Adds comments around `resource_manager::register_manager` so that it's more clear what this method does and why.

Changing hints configuration followup

---

dist/common/scripts/node_exporter_install
dist/common/scripts/scylla_bootparam_setup
dist/common/scripts/scylla_coredump_setup
dist/common/scripts/scylla_ec2_check
dist/common/scripts/scylla_kernel_check
dist/common/scripts/scylla_ntp_setup
dist/common/scripts/scylla_prepare
dist/common/scripts/scylla_raid_setup
dist/common/scripts/scylla_selinux_setup
dist/common/scripts/scylla_setup
dist/common/scripts/scylla_stop
dist/common/scripts/scylla_swap_setup
dist/common/scripts/scylla_sysconfig_setup
dist/common/scripts/scylla_util.py

We initially implemented run() and out() functions because we couldn't use
subprocess.run() since we were on Python 3.4.
But since we moved to relocatable python3, we don't need to implement it ourselves.
Why we keep using these functions are, because we needed to set environemnt variable to set PATH.
Since we recently moved away these codes to python thunk, we finally able to
drop run() and out(), switch to subprocess.run().

dist/common/scripts: drop run() and out(), swtich to subprocess.run()

---

dist/common/scripts/scylla_prepare

perftune.py only run clocksource setup when --tune system specified,
so we need to add it on the parameter when SET_CLOCKSOURCE=yes.
Fixes #7672

scylla_prepare: add --tune system when SET_CLOCKSOURCE=yes

---

redis/service.cc
transport/controller.cc

Fixes #7211
If we start a sharded<> object, then proceed to do potentially
exceptional stuff, we should destroy it on said exception.
Otherwise, the exception propagation will abort on RAII
destruction of the sharded<>. And we get no exception logging.

Add missing shaded<>::stop in exceptional startup code for CQL/redis

---

dist/redhat/scylla.spec

We have "Conflicts: kernel < 3.10.0-514" on rpm package to make sure
the environment is running newer kernel.
However, user may use non-standard kernel which has different package name,
like kernel-ml or kernel-uek.
On such environment Conflicts tag does not works correctly.
Even the system running with newer kernel, rpm only checks "kernel" package
version number.
To avoid such issue, we need to drop Conflicts tag, need to check kernel version
in scylla_setup script instead.
Fixes #7675

dist/redhat: drop Conflicts with older kernel

---

cql3/expr/expression.cc
cql3/restrictions/statement_restrictions.cc
test/boost/secondary_index_test.cc
test/lib/cql_assertions.cc
test/lib/cql_assertions.hh

Fix #7680 by never using secondary index for multi-column restrictions.
Modify expr::is_supported_by() to handle multi-column correctly.

Don't use secondary indices for multi-column restrictions

---

test/cql-pytest/conftest.py
test/cql-pytest/run.py
test/cql-pytest/test_validation.py

The first two patches in this series are small improvements to cql-pytest to prepare for the third and main patch. This third patch adds cql-pytest tests which check that we fail CQL queries that try to inject non-ASCII and non-UTF-8 strings for ascii and text columns, respectively.
The tests do not discover any unknown bug in Scylla, however, they do show that Scylla is more strict in its definition of "valid UTF-8" compared to Cassandra.

test/cql-pytest: tests for string validation (UTF-8 and ASCII)

---

dist/common/scripts/scylla_rsyslog_setup
dist/common/scripts/scylla_setup

This patch adds an option to scylla_setup to configure an rsyslog destination.
The monitoring stack has an option to get information from rsyslog it
requires that rsyslog on the scylla machines will send the trace line to
it.
The configuration will be in a Scylla configuration file, so it is safe to run it multiple times.
Fixes #7589

dist/common/scripts/scylla_setup: Optionally config rsyslog destination

---

db/large_data_handler.cc
db/large_data_handler.hh
docs/sstable-scylla-format.md
sstables/kl/writer.cc
sstables/mx/writer.cc
sstables/sstables.cc
sstables/sstables.hh
sstables/types.hh

This series introduces a `large_data_counters` element to `scylla_metadata` component to explicitly count the number of `large_{partitions,rows,cells}` and `too_many_rows` in the sstable.  These are accounted for in the sstable writer whenever the respective large data entry is encountered.
It is taken into account in `large_data_handler::maybe_delete_large_data_entries`, when engaged.
Otherwise, if deleting a legacy sstable that has no such entry in `scylla_metadata`, just revert to using the current method of comparing the sstable's `data_size` to the various thresholds.
Fixes #7668
Dtest: wide_rows_test.py (in progress)

Use large_data_counters in scylla_metadata to decide when to delete large_data records

---

mutation_reader.cc
mutation_reader.hh
test/boost/mutation_reader_test.cc
test/lib/mutation_source_test.cc
test/lib/mutation_source_test.hh
test/lib/random_schema.cc
test/lib/random_utils.hh
test/lib/simple_position_reader_queue.hh
test/perf/perf_mutation_readers.cc

This abstraction is used to merge the output of multiple readers, each
opened for a single partition query, into a non-decreasing stream
of mutation_fragments.
It is similar to `mutation_reader_merger`,
but an important difference is that the new merger may select new readers
in the middle of a partition after it already returned some fragments
from that partition.  It uses the new `position_reader_queue` abstraction
to select new readers. It doesn't support multi-partition (ring range) queries.
The new merger will be later used when reading from sstable sets created
by TimeWindowCompactionStrategy. This strategy creates many sstables
that are mostly disjoint w.r.t the contained clustering keys, so we can
delay opening sstable readers when querying a partition until after we have …

mutation_reader: introduce clustering_order_reader_merger

---

dist/common/scripts/scylla_setup

scylla_setup command suggestion does not shows an argument of --io-setup,
because we mistakely stores bool value on it (recognized as 'store_true').
We always need to print '--io-setup X' on the suggestion instead.
Also, --nic is currently ignored by command suggestion, need to print it just like other options.
Related #7395

scylla_setup: fix wrong command suggestion

---

collection_mutation.hh
mutation_partition.cc
serializer_impl.hh
test/lib/cql_test_env.cc
types.cc
utils/fragment_range.hh

A sequel to #7692.
This series gets rid of linearization in `serialize_for_cql`, which serializes collections and user types from `collection_mutation_view` to CQL. We switch from `bytes` to `bytes_ostream` as the intermediate buffer type.
The only user of of `serialize_for_cql` immediately copies the result to another `bytes_ostream`. We could avoid some copies and allocations by writing to the final `bytes_ostream` directly, but it's currently hidden behind a template.
Before this series, `serialize_for_cql_aux()` delegated the actual writing to `collection_type_impl::pack` and `tuple_type_impl::build_value`, by passing them an intermediate `vector`. After this patch, the writing is done directly in `serialize_for_cql_aux()`. Pros: we avoid the overhead of creating an intermediate …

types: don't linearize in serialize_for_cql()

---

configure.py
serializer_impl.hh
test/boost/mutation_test.cc
test/lib/mutation_source_test.cc

The switch to clang disabled the clang-specific -Wunused-value
since it generated some harmless warnings. Unfortunately, that also
prevent [[nodiscard]] violations from warning.
Fix by clearing all instances of the warning (including [[nodiscard]]
violations that crept in while it was disabled) and reinstating the warning.

Reinstate [[nodiscard]] support

---

cql3/Cql.g
cql3/attributes.cc
cql3/attributes.hh
cql3/statements/batch_statement.cc
cql3/statements/batch_statement.hh
cql3/statements/create_view_statement.cc
cql3/statements/modification_statement.cc
cql3/statements/modification_statement.hh
cql3/statements/raw/select_statement.hh
cql3/statements/select_statement.cc
cql3/statements/select_statement.hh
docs/cql-extensions.md
service/storage_proxy.cc
service/storage_proxy.hh
test/cql-pytest/test_using_timeout.py

This series allows setting per-query timeout via CQL. It's possible via the existing `USING` clause, which is extended to be available for `SELECT` statement as well. This parameter accepts a duration and can also be provided as a marker.
The parameter acts as a regular part of the `USING` clause, which means that it can be used along with `USING TIMESTAMP` and `USING TTL` without issues.
The series comes with a pytest test suite.
Examples:
```cql
SELECT * FROM t USING TIMEOUT 200ms;
```
```cql
INSERT INTO t(a,b,c) VALUES (1,2,3) USING TIMESTAMP 42 AND TIMEOUT 50ms;
```
Working with prepared statements works as usual - the timeout parameter can be
explicitly defined or provided as a marker:
```cql
SELECT * FROM t USING TIMEOUT ?;
```
```cql
INSERT INTO t(a,b,c) VALUES (?,?,?) USING …
```

Add per query timeout

---

database.cc
database.hh
table.cc

This series makes sure that before the table is dropped, all pending memtable flushes related to its memtables would finish.
Normally, flushes are not problematic in Scylla, because all tables are by default `auto_snapshot=true`, which also implies that a table is flushed before being dropped. However, with `auto_snapshot=false` the flush is not attempted at all. It leads to the following race:
1. Run a node with `auto_snapshot=false`
2. Schedule a memtable flush  (e.g. via nodetool)
3. Get preempted in the middle of the flush
4. Drop the table
5. The flush that already started wakes up and starts operating on freed memory, which causes a segfault
Tests: manual(artificially preempting for a long time in bullet point 2. to ensure that the race occurs; segfaults were 100% reproducible …

Add waiting for flushes on table drops

---

cql3/restrictions/single_column_primary_key_restrictions.hh
cql3/restrictions/single_column_restrictions.hh
test/boost/restrictions_test.cc
test/boost/secondary_index_test.cc

There were two problems with handling conflicting equalities on the same PK column (eg, c=1 AND c=0):
1. When the column is indexed, Scylla crashed (#7772)
2. Computing ranges and slices was throwing an exception
This series fixes them both; it also happens to resolve some old TODOs from restriction_test.
Tests: unit (dev, debug)

cql3: Fix handling of impossible restrictions on a primary-key column

---

mutation_reader.cc
sstables/sstable_set.cc
sstables/sstable_set_impl.hh
sstables/sstables.hh
sstables/time_window_compaction_strategy.hh
test/boost/mutation_reader_test.cc

We introduce a new single-key sstable reader for sstables created by `TimeWindowCompactionStrategy`.
The reader uses the fact that sstables created by TWCS are mostly disjoint with respect to the contained `position_in_partition`s in order to avoid having multiple sstable readers opened at the same time unnecessarily. In case there are overlapping ranges (for example, in the current time-window), it performs the necessary merging (it uses `clustering_order_reader_merger`, introduced recently).
The reader uses min/max clustering key metadata present in `md` sstables in order to decide when to open or close a sstable reader.
The following experiment was performed:
1. create a TWCS table with 1 minute windows
2. fill the table with 8 equal windows of data
(each window flushed to a separate …

Avoid scanning sstables in parallel for TWCS single-partition queries

---

mutation_reader.cc
test/boost/mutation_reader_test.cc

With 0 readers the merger would produce a `partition_end` fragment
when it should immediately return `end_of_stream` instead.

clustering_order_reader_merger: fix the 0 readers case

---

database.hh
distributed_loader.cc
row_cache.cc
row_cache.hh
table.cc
test/boost/database_test.cc
test/boost/row_cache_test.cc
test/boost/sstable_datafile_test.cc
test/boost/sstable_test.hh
test/manual/sstable_scan_footprint_test.cc
test/perf/perf_row_cache_update.cc
test/unit/row_cache_alloc_stress_test.cc
test/unit/row_cache_stress_test.cc

On every compaction completion, sstable set is rebuilt from scratch.
With LCS and ~160G of data per shard, it means we'll have to create
a new sstable set with ~1000 entries whenever compaction completes,
which will likely result in reactor stalling for a significant
amount of time.
Fixes #7758.
Signed-off-by: Raphael S. Carvalho <raphaelsc@scylladb.com>

table: Fix potential reactor stall on LCS compaction completion

---

database.hh
distributed_loader.cc
row_cache.cc
row_cache.hh
table.cc
test/boost/database_test.cc
test/boost/row_cache_test.cc
test/boost/sstable_test.hh
test/manual/sstable_scan_footprint_test.cc
test/perf/perf_row_cache_update.cc
test/unit/row_cache_alloc_stress_test.cc
test/unit/row_cache_stress_test.cc

On every compaction completion, sstable set is rebuilt from scratch.
With LCS and ~160G of data per shard, it means we'll have to create
a new sstable set with ~1000 entries whenever compaction completes,
which will likely result in reactor stalling for a significant
amount of time.
Fixes #7758.
since last version:
- dropped unit test and rebased

Fix potential reactor stall on LCS compaction completion

---

dist/common/scripts/scylla_setup

node_exporter had been added to scylla-server package by commit
95197a09c91eb719c252abed847b8c035f5f9600.
So we can enable it by default for offline installation.
/CC @tzach @slivne @eyalgutkind @syuu1228

scylla_setup: enable node_exporter for offline installation

---

api/storage_service.cc
configure.py
db/view/view_update_generator.cc
sstables/shared_sstable.hh
sstables/sstable_set.cc
sstables/sstable_set.hh
sstables/sstable_set_impl.hh
table.cc
test/boost/sstable_set_test.cc
test/boost/sstable_test.hh
test/lib/sstable_test_env.hh
test/perf/perf_sstable_set.cc

Currently, the sstable_set in a table is copied before every change
to allow accessing the unchanged version by existing sstable readers.
This patch changes the sstable_set to a structure that keeps all its
versions that are referenced somewhere and provides a way of getting
a reference to an immutable version of the set.
Each sstable in the set is associated with the versions it is alive in,
and is removed when all such versions don't have references anymore.
To avoid copying, the object holding all sstables in the set version is
changed to a new structure, sstable_list, which was previously an alias
for std::unordered_set<shared_sstable>, and which implements most of the
methods of an unordered_set, but its iterator uses the actual set with
all sstables from all referenced versions and …

sstables: replace the sstable_set with a versioned one

---

idl-compiler.py
idl/mutation.idl.hh

After these changes the generated code deserializes the stream into a chunked vector, instead of an contiguous one, so even if there are many fields in it, there won't be any big allocations.
I haven't run the scylla cluster test with it yet but it passes the unit tests.

idl: remove the large allocation in mutation_partition_view::rows()

---

dist/common/scripts/scylla_coredump_setup
dist/common/scripts/scylla_cpuscaling_setup
dist/common/scripts/scylla_fstrim_setup
dist/common/scripts/scylla_ntp_setup
dist/common/scripts/scylla_prepare
dist/common/scripts/scylla_raid_setup
dist/common/scripts/scylla_selinux_setup
dist/common/scripts/scylla_setup
dist/common/scripts/scylla_stop
dist/common/scripts/scylla_sysconfdir.py
dist/common/scripts/scylla_sysconfig_setup
dist/common/scripts/scylla_util.py
install.sh
unified/install.sh

Since we introduced relocatable package and offline installer, scylla binary itself can run almost any distributions.
However, setup scripts are not designed to run in unsupported distributions, it causes error on such environment.
This PR adds minimal support to run offline installation on unsupported distributions, tested on SLES, Arch Linux and Gentoo.

Support unofficial distributions

---

redis/protocol_parser.rl
test/redis/test_strings.py

If the message is larger than current buffer size, we need to consume
more data until we reach to tail of the message.
To do so, we need to return nullptr when it's not on the tail.
Fixes #7273

redis: support large redis message

---

db/commitlog/commitlog.cc
db/commitlog/commitlog.hh
db/commitlog/commitlog_entry.hh
test/boost/commitlog_test.cc

Fixes #7615
Makes the CL writer interface N-valued (though still 1 for the "old" paths). Adds a new write path to input N mutations -> N rp_handles. 
Guarantees that all entries are written or none are, and that they will be flushed to disk together. 
Small test included. 
v2: 
* Improved comments
* add_entries uses set for schema inclusion check
* Test now verifies written data
v3:
* Changed file format to allow entries within entry
* Now CRC multi-entry and verify full multi-entry set before replay
v4: 
* Fixed "produce" call not waited for in replay

Commitlog multi-entry write

---

clustering_ranges_walker.hh
sstables/mp_row_consumer.hh
test/boost/clustering_ranges_walker_test.cc

Whenever we push a fragment, we check whether the buffer is
full and return proceed::no if so, so that the state machine pauses
and lets the consumer continue. This patch adds an additional
condition - if preemption is needed, we also return proceed::no.
This drops us back to the outer loop
(in sstable_mutation_reader::fill_buffer), which will yield to
the reactor as part of seastar::do_until().
Two cases (partition_start and partition_end) did not have the
check for is_buffer_full(); it is added now. This can trigger
is the partition has no rows.
Unlike the previous attempt, push_ready_fragments() is not touched.
The extra preemption opportunities triggered a preexisting bug in
clustering_ranges_walker; it is fixed in the first patch of the series.
I tested this by reading from a large …

sstable: reader: preempt after every fragment

---

database.cc
db/schema_tables.cc
db/schema_tables.hh
schema.cc
schema_registry.cc
schema_registry.hh

This series fixes some race conditions in MV/SI schema creation and load, we spotted some places where a schema without
a base table reference can sneak into the registry. This can cause to an unrecoverable error since write commands
with those schemas can't be issued from other nodes. Most of those cases can occur on 2 main and uncommon cases,
in a mixed cluster (during an upgrade) and in a small window after a view or base table altering.
Fixes #7709

Fix inconsistencies in MV and SI

---

locator/network_topology_strategy.cc
test/boost/cql_query_test.cc
test/cql/locator_test.cql
test/cql/locator_test.result

The same trick is used as in C*:
https://github.com/apache/cassandra/blob/79e693e16e2152097c5b27d2d7aaa1763e34f594/src/java/org/apache/cassandra/locator/NetworkTopologyStrategy.java#L241
The edited CQL test relied on quietly accepting non-existing DCs, so it had to be removed. Also, one boost-test referred to nonexistent `datacenter2` and had to be removed.
Fixes #7595

locator: Check DC names in NetworkTopologyStrategy

---

db/schema_tables.cc
gms/feature_service.hh
service/migration_manager.cc

When a table is altered in a mixed cluster by a node with a more recent version, the request can
fail if there is a difference in schema_features between the two versions.
This miniset handles the two problems that prevents the sync.

Fix mixed cluster schema sync

---

alternator/conditions.cc
alternator/conditions.hh
alternator/executor.cc
alternator/executor.hh
alternator/expressions.cc
alternator/expressions_types.hh
alternator/streams.cc
docs/alternator/alternator.md
docs/alternator/compatibility.md
test/alternator/conftest.py
test/alternator/test_condition_expression.py
test/alternator/test_expected.py
test/alternator/test_filter_expression.py
test/alternator/test_gsi.py
test/alternator/test_item.py
test/alternator/test_projection_expression.py
test/alternator/test_returnvalues.py
test/alternator/test_update_expression.py

This series fixes #5024 - which is about adding support for nested attribute paths (e.g., a.b.c[2]) to Alternator.
The series adds complete support for this feature in ProjectionExpression, ConditionExpression, FilterExpression and UpdateExpression - and also its combination with ReturnValues. Many relevant tests - and also some new tests added in this series - now pass.
The first patch in the series fixes #8043 a bug in some error cases in conditions, which was discovered while working in this series, and is conceptually separate from the rest of the series.

Alternator: support nested attribute paths in all expressions

---

alternator/streams.cc
cdc/generation.cc
cdc/generation.hh
cql3/query_processor.cc
cql3/query_processor.hh
db/config.cc
db/config.hh
db/system_distributed_keyspace.cc
db/system_distributed_keyspace.hh
db/system_keyspace.cc
db/system_keyspace.hh
docs/design-notes/cdc.md
main.cc
service/client_state.cc
service/storage_service.cc
test/boost/cdc_test.cc
test/boost/query_processor_test.cc
test/cql-pytest/test_cdc.py
test/lib/cql_test_env.cc

Until now, the lists of streams in the `cdc_streams_descriptions` table
for a given generation were stored in a single collection. This solution
has multiple problems when dealing with large clusters (which produce
large lists of streams):
1. large allocations
2. reactor stalls
3. mutations too large to even fit in commitlog segments
This commit changes the schema of the table as described in issue #7993.
The streams are grouped according to token ranges, each token range
being represented by a separate clustering row. Rows are inserted in
reasonably large batches for efficiency.
The table is renamed to enable easy upgrade. On upgrade, the latest CDC
generation's list of streams will be (re-)inserted into the new table.
Yet another table is added: one that contains only the generation …

Split CDC streams table partitions into clustered rows 

---

cdc/generation.cc
cdc/generation.hh
cdc/metadata.cc
configure.py
test/boost/cdc_generation_test.cc

Currently, whole topology description for CDC is stored in a single row.
This means that for a large cluster of strong machines (say 100 nodes 64
cpus each), the size of the topology description can reach 32MB.
This causes multiple problems. First of all, there's a hard limit on
mutation size that can be written to Scylla. It's related to commit log
block size which is 16MB by default. Mutations bigger than that can't be
saved. Moreover, such big partitions/rows cause reactor stalls and
negatively influence latency of other requests.
This patch limits the size of topology description to about 4MB. This is
done by reducing the number of CDC streams per vnode and can lead to CDC
data not being fully colocated with Base Table data on shards. It can
impact performance and consistency of data. …

cdc: Limit size of topology description

---

cdc/log.cc

Due to small value optimization used in `bytes`, views to `bytes` stored
in `vector` can be invalidated when the vector resizes, resulting in
use-after-free and data corruption. Fix that.

cdc: log: fix a use-after-free in process_bytes_visitor

---

main.cc
test/boost/logalloc_test.cc
utils/logalloc.cc
utils/logalloc.hh

This series adds background reclaim to lsa, with the goal
that most large allocations can be satisfied from available
free memory, and and reclaim work can be done from a preemptible
context.
If the workload has free cpu, then background reclaim will
utilize that free cpu, reducing latency for the main workload.
Otherwise, background reclaim will compete with the main
workload, but since that work needs to happen anyway,
throughput will not be reduced.
A unit test is added to verify it works.
Fixes #1634.

lsa: background reclaim

---

alternator/executor.hh
alternator/streams.cc
api/storage_service.cc
cdc/generation.cc
cdc/generation.hh
cdc/generation_service.hh
cdc/log.cc
cdc/log.hh
main.cc
service/storage_service.cc
service/storage_service.hh
test/boost/gossip_test.cc
test/lib/cql_test_env.cc
test/lib/test_services.cc
test/manual/gossip.cc

Currently all management of CDC generations happens in storage_service,
which is a big ball of mud that does many unrelated things.
This PR introduces a new service crafted to handle CDC generation
management: listening and reacting to generation changes in the cluster.
We plug the service in, initializing it in main and test code,
passing a reference to storage_service and having storage_service call
the service (using the `after_join` method): the service only starts
doing its job after the node joins the token ring (either on bootstrap
or restart).
Some parts of generation management still remain in storage_service:
the bootstrap procedure, which happens inside storage_service,
must also do some initialization regarding CDC generations,
for example: on restart it must retrieve the …

cdc: move (most of) CDC generation management to a new service

---

alternator/executor.hh
alternator/streams.cc
api/storage_service.cc
cdc/generation.cc
cdc/generation.hh
cdc/generation_service.hh
cdc/log.cc
cdc/log.hh
main.cc
service/storage_service.cc
service/storage_service.hh
test/boost/gossip_test.cc
test/lib/cql_test_env.cc
test/lib/test_services.cc
test/manual/gossip.cc

Currently all management of CDC generations happens in storage_service,
which is a big ball of mud that does many unrelated things.
This PR introduces a new service crafted to handle CDC generation
management: listening and reacting to generation changes in the cluster.
We plug the service in, initializing it in main and test code,
passing a reference to storage_service and having storage_service call
the service (using the `after_join` method): the service only starts
doing its job after the node joins the token ring (either on bootstrap
or restart).
Some parts of generation management still remain in storage_service:
the bootstrap procedure, which happens inside storage_service,
must also do some initialization regarding CDC generations,
for example: on restart it must retrieve the …

 cdc: move (most of) CDC generation management to a new service

---

cache_flat_mutation_reader.hh
configure.py
row_cache.cc
row_cache.hh
test/perf/perf_row_cache_reads.cc

fill_buffer() will keep scanning until _lower_bound_changed is true,
even if preemption is signaled, so that the reader makes forward
progress.
Before the patch, we did not update _lower_bound on touching a dummy
entry. The read will not respect preemption until we hit a non-dummy
row. If there is a lot of dummy rows, that can cause reactor stalls.
Fix that by updating _lower_bound on dummy entries as well.
Refs #8153.
Tested with perf_row_cache_reads:
```
$ build/release/test/perf/perf_row_cache_reads -c1 -m200M
Rows in cache: 0
Populating with dummy rows
Rows in cache: 373929
Scanning
read: 183.658966 [ms], preemption: {count: 848, 99%: 0.545791 [ms], max: 0.519343 [ms]}, cache: 99/100 [MB]
read: 120.951515 [ms], preemption: {count: 257, 99%: 0.545791 [ms], max: 0.518795 [ms]}, cache: …
```

row_cache: Make fill_buffer() preemptable when cursor leads with dummy rows

---

redis/server.cc
redis/server.hh

The Redis transport layer seems to have originated as a copy-paste of 
the CQL transport layer. This pull request removes bunch of unused
and commented out bits of code, and also does some minor cleanups
like organizing includes, to make the code more readable.

Clean up Redis transport layer

---

test/cql-pytest/test_shedding.py
transport/server.cc

When shedding requests (e.g. due to their size or number exceeding the limits), errors were returned right after parsing their headers, which resulted in their bodies lingering in the socket. The server always expects a correct request header when reading from the socket after the processing of a single request is finished, so shedding the requests should also take care of draining their bodies from the socket.
Fixes #8193

Fix reading whole requests during shedding

---

redis/command_factory.hh
redis/keyspace_utils.hh
redis/options.hh
redis/query_processor.hh
redis/query_utils.hh
redis/reply.hh
redis/service.cc
redis/service.hh

This pull request removes seastar namespace imports from the header 
files. There are some additional cleanups to make that easier and to 
remove some commented out code.

More Redis cleanups

---

alternator/streams.cc
db/system_distributed_keyspace.cc
db/system_distributed_keyspace.hh

Refs: #8012
Fixes: #8210
With the update to CDC generation management, the way we retrieve and process these changed. 
One very bad bug slipped through though; the code for getting versioned streams did not take into
account the late-in-pr change to make clustering of CDC gen timestamps reversed. So our alternator
shard info became quite rump-stumped, leading to more or less no data depending on when generations
changed w.r. data. 
Also, the way we track the above timestamps changed, so we should utilize this for our end-of-iterator check.

Fix alternator streams management regression

---

db/commitlog/commitlog.cc
db/commitlog/commitlog.hh
db/hints/manager.cc

A recent change to the commitlog (4082f57) caused its configurable size limit to be strictly enforced - after reaching the limit, new segments wouldn't be allocated until some of the previous segments are freed. This flow can work for the regular commitlog, however the hints commitlog does not delete the segments itself - instead, hints manager recreates its commitlog every 10 seconds, picks up segments left by the previous instance and deletes each segment manually only after all hints are sent out from a segment.
Because of the non-standard flow, it is possible that the hints commitlog fills up and stops accepting more hints. Hints manager uses a relatively low limit for each commitlog instance (128MB divided by shard count), so it's not hard to fill it up. What's worse, hints manager …

hints: use a soft disk space limit in hints commitlog

---

configure.py
install-dependencies.sh
install.sh
scripts/create-relocatable-package.py

Add fix_system_distributed_tables.py to the package.
Since the script requires cassandra-driver, add it to relocatable python3.
But python cassandra-driver rpm does not available, and our relocatable python3 requires rpm to solve dependencies,
the PR do some trick:
install by pip -> convert pip to rpm -> convert to relocatable python3

add fix_system_distributed_tables.py to the package, add cassandra-driver to relocatable python3

---

dist/common/scripts/scylla_coredump_setup
dist/common/scripts/scylla_setup
dist/common/scripts/scylla_util.py

Basically SLES support is already done in f20736d93d4d8e4f9c5539f2daa23351724b05a0, but it was for offline installer.
This fixes few more problems to install our rpm to SLES.
After this change, we can just install our rpm for both CentOS/RHEL and SLES in single image, like unified deb.
SLES uses original package manager called 'zypper', but it does support yum repository so no need to change required for repo.

Support installing our rpm to SLES

---

service/storage_proxy.cc

With this change, coordinator prefers himself as the "counter leader", so if another endpoint is chosen as the leader, we know that coordinator was not a member of replica set. With this guarantee we can increment `scylla_storage_proxy_coordinator_writes_coordinator_outside_replica_set` metric after electing different leader (that metric used to neglect the counter updates).
The motivation for this change is to have more reliable way of counting non-token-aware queries.
Fixes #4337

storage_proxy: Include counter writes in `writes_coordinator_outside_replica_set`

---

test/boost/logalloc_test.cc
utils/logalloc.cc

The log structured allocator's background reclaimer tries to
allocate CPU power proportional to memory demand, but a
bug made that not happen. Fix the bug, add some logging,
and future-proof the timer. Also, harden the test agains\
overcommitted test machines.
Fixes #8234.
Test: logalloc_test(dev), 20 concurrent runs on 2 cores (1 hyperthread each)

logalloc: improve background reclaim shares management

---

bytes_ostream.hh
repair/repair.cc
service/pager/paging_state.cc
sstables/sstables.cc
sstables/writer.hh
transport/server.cc
types.cc
types.hh
utils/bit_cast.hh
utils/crc.hh
utils/fragment_range.hh
utils/linearizing_input_stream.hh
utils/managed_bytes.hh

In some places we use the `*reinterpret_cast<const net::packed<T>*>(&x)`
pattern to reinterpret memory. This is a violation of C++'s aliasing rules,
which invokes undefined behaviour.
The blessed way to correctly reinterpret memory is to copy it into a new
object. Let's do that.
Note: the reinterpret_cast way has no performance advantage. Compilers
recognize the memory copy pattern and optimize it away.

treewide: get rid of incorrect reinterpret casts

---

configure.py

This series makes configure.py output slightly more helpful in case of incorrect parameters passed to the compiler/linker.

Add more context to configure.py

---

api/api-doc/storage_service.json
api/storage_service.cc
configure.py
test/boost/tracing.cc
tracing/trace_state.hh
tracing/tracing.cc
tracing/tracing.hh

The set of patches introduces a new tracing mode - `fast slow query tracing`. In this mode, Scylla tracks only tracing sessions and omits all tracing events if the tracing context does not have a `full_tracing` state set.
Fixes https://github.com/scylladb/scylla/issues/2572
Motivation
---
We want to run production systems with that option always enabled so we could always catch slow queries without an overhead. The next step is we are gonna optimize further the costs of having tracing enabled to minimize session context handling overhead to allow it to be as transparent for the end-user as possible.
Fast tracing mode
---
To read the status do
$ curl -v http://localhost:10000/storage_service/slow_query
To enable fast slow-query tracing
$ curl -v --request POST …

tracing: fast slow query tracing

---

thrift/server.cc
thrift/server.hh

Thrift used to be quite unsafe with regard to its retry mechanism, which caused very rapid use of resources, namely the number of file descriptors. It was also prone to use-after-free due to spawning futures without guarding the captured objects with anything.
The mechanism is now cleaned up, and a simple exponential backoff replaced previous constant backoff policy.
Fixes #8317
Tests: unit(dev), manual(see #8317 for a simple reproducer)

Fix the retry mechanism in Thrift frontend

---

db/config.cc
docs/design-notes/protocols.md

The Thrift layer is functional, but it's not usually the first-choice protocol for Scylla users, so it's hereby disabled by default.
Fixes #8336

Disable thrift by default

---

scylla-gdb.py

The command can be used to inspect IO queues of a local reactor.
Example output:
```
(gdb) scylla io-queues
Dev 0:
Class:                  |shares:         |ptr:
--------------------------------------------------------------------------------
"default"               |1               |(seastar::priority_class_data *)0x6000002c6500
"commitlog"             |1000            |(seastar::priority_class_data *)0x6000003ad940
"memtable_flush"        |1000            |(seastar::priority_class_data *)0x6000005cb300
"streaming"             |200             |(seastar::priority_class_data *)0x0
"query"                 |1000            |(seastar::priority_class_data *)0x600000718580
"compaction"            |1000            |(seastar::priority_class_data *)0x6000030ef0c0
Max request size:    2147483647 …
```

scylla-gdb.py: Add io-queues command

---

main.cc
service/memory_limiter.hh
service_permit.hh
thrift/controller.cc
thrift/controller.hh
thrift/handler.cc
thrift/handler.hh
thrift/server.cc
thrift/server.hh

This pull request adds partial admission control to Thrift frontend. The solution is partial mostly because the Thrift layer, aside from allowing Thrift messages, may also be used as a base protocol for CQL messages. Coupling admission control to this one is a little bit more complicated due to how the layer currently works - a Thrift handler, created once per connection, keeps a local `query_state` instance for the occasion of handling CQL requests. However, `query_state` should be kept per query, not per connection, so adding admission control to this aspect of the frontend is left for later.
Finally, the way service permits are passed from the server, via the handler factory, handler and then to queries is hacky. I haven't figured out how to force Thrift to pass custom context per …

Add partial admission control to Thrift frontend

---

gms/feature_service.cc
gms/feature_service.hh
repair/repair.cc
repair/repair.hh
sstables/kl/writer.cc
sstables/kl/writer.hh
sstables/mx/writer.cc
sstables/sstables.hh
sstables/sstables_manager.cc
test/boost/sstable_mutation_test.cc

Following the work started in 253a7640e, a new batch of old features is assumed to be always available. They are all still announced via gossip, but the code assumes that the feature is always true, because we only support upgrades from a previous release, and the release window is considerably smaller than 2 years.
Features picked this time via `git blame`, along with the date of their introduction:
* fe4afb1aa3 (Asias He                  2018-09-05 14:52:10 +0800  109) static const sstring ROW_LEVEL_REPAIR = "ROW_LEVEL_REPAIR";
* ff5e541335 (Calle Wilund              2019-02-05 13:06:07 +0000  110) static const sstring TRUNCATION_TABLE = "TRUNCATION_TABLE";
* fefef7b9eb (Tomasz Grabiec            2019-03-05 19:08:07 +0100  111) static const sstring CORRECT_STATIC_COMPACT_IN_MC = …

Clean up > 2-year-old features

---

db/hints/manager.cc
db/hints/manager.hh
service/storage_service.cc

This PR changes the `can_send` function so that it looks at the `token_metadata` in order to tell if the destination node is in the ring. Previously, gossiper state was used for that purpose and required a relatively complicated condition to check. The new logic just uses `token_metadata::is_member` which reduces complexity of the `can_send` function.
Additionally, `storage_service` is slightly modified so that during a removenode operation the `token_metadata` is first updated and only then endpoint lifecycle subscribers are notified. This was done in order to prevent a race just like the one which happened in #5087 - hints manager is a lifecycle subscriber and starts a draining operation when a node is removed, and in order for draining to work correctly, `can_send` should keep …

hints: use token_metadata to tell if node has left the ring

---

cdc/generation.cc
cdc/generation.hh
cdc/generation_id.hh
cdc/generation_service.hh
db/system_distributed_keyspace.cc
db/system_distributed_keyspace.hh
db/system_keyspace.cc
db/system_keyspace.hh
docs/design-notes/cdc.md
gms/application_state.cc
gms/application_state.hh
gms/versioned_value.cc
gms/versioned_value.hh
service/storage_service.cc
service/storage_service.hh

The "most important" major changes are:
1. storage_service: simplify CDC generation management during node replace
Previously, when node A replaced node B, it would obtain B's
generation timestamp from its application state (gossiped by other
nodes) and start gossiping it immediately on bootstrap.
But that's not necessary:
- if this is the timestamp of the last (current) generation, we would
obtain it from other nodes anyway (every node gossips the last known
timestamp),
- if this is the timestamp of an earlier generation, we would forget
it immediately and start gossiping the last timestamp (obtained from
other nodes).
This commit simplifies the bootstrap code (in node-replace case) a bit:
the replacing node no longer attempts to retrieve the CDC generation
timestamp from the node being …

CDC generations: refactors and improvements

---

db/commitlog/commitlog.cc
db/commitlog/commitlog.hh
test/boost/commitlog_test.cc

Fixes #8363
Fixes #8376
Delete segements has two issues when running with size-limited
commit log and strict adherence to said limit.
1.) It uses parallel processing, with deferral. This means that
the disk usage variables it looks at might not be fully valid
- i.e. we might have already issued a file delete that will
reduce disk footprint such that a segment could instead be
recycled, but since vars are (and should) only updated
_post_ delete, we don't know.
2.) It does not take into account edge conditions, when we only
delete a single segment, and this segment is the border segment
- i.e. the one pushing us over the limit, yet allocation is
desperately waiting for recycling. In this case we should
allow it to live on, and assume that next delete will reduce
footprint. Note: to ensure …

commitlog: Fix race and edge condition in delete_segments

---

cql3/statements/select_statement.cc
test/cql-pytest/test_secondary_index.py

Currently the heuristics for picking an index for a query
are not very well defined. It would be best if we used
statistics to pick the index which is likely to perform
the fastest, but for starters we should at least let the user
decide which index to pick by picking the first one by the
order of restrictions passed to the query.
The (failing) test case from this patch shows the expected
results.
Ref: #7969

Add a (failing) test for picking secondary indexes in order

---

dist/common/scripts/scylla_ntp_setup
dist/common/scripts/scylla_util.py

On current implementation, we may re-run ntp configuration even it
already configured.
Also, the system may configured with non-default ntp client, we just
ignoring that and configure with default ntp client.
This patch minimize unnecessary re-configuration of ntp client.
It run in following order:
1. Check NTP client is already running. If it running, skip setup
2. Check NTP client is alrady installed. If it installed, use it
3. If there is non of NTP client package installed,
- if it's CentOS, install chrony
- if it's on other distributions, install systemd-timesyncd

scylla_ntp_setup: detect already installed ntp client

---

atomic_cell.hh
cdc/log.cc
cql3/untyped_result_set.hh
keys.hh
types.cc
types/map.hh
types/set.hh

CDC log uses `bytes` to deal with cells and their values, and linearizes all values indiscriminately.
This series makes a switch from `bytes` to `managed_bytes` to avoid that linearization.
Fixes #7506.

cdc: log: avoid linearizations

---

cache_flat_mutation_reader.hh
read_context.hh
row_cache.cc

It is possible that a partition is in cache but is not present in sstables that are underneath.
In such case:
1. cache_flat_mutation_reader will fast forward underlying reader to that partition
2. The underlying reader will enter the state when it's empty and its is_end_of_stream() returns true
3. Previously cache_flat_mutation_reader::do_fill_buffer would try to fast forward such empty underlying reader
4. This PR fixes that
Fixes #8435 
Fixes #8411

Make sure that cache_flat_mutation_reader::do_fill_buffer does not fast forward finished underlying reader

---

cdc/log.cc

In the first commit, add validation of `enable` and `postimage` CDC options. Both options are boolean options, but previously they were not validated, meaning you could issue a query:
```
CREATE TABLE ks.t(pk int, PRIMARY KEY(pk)) WITH cdc = {'enabled': 'dsfdsd'};
```
and it would be executed without any errors, silently interpreting `dsfdsd` as false.
The first commit narrows possible values of those boolean CDC options to `false`, `true`, `0`, `1`. After applying this change, issuing the query above would result in this error message:
```
ConfigurationException: Invalid value for CDC option "enabled": dsfdsd
```
I actually encountered this lacking validation myself, as I mistakenly issued a query:
```
CREATE TABLE ks.t(pk int, PRIMARY KEY(pk)) WITH cdc = {'enabled': true, 'preimage': …
```

Improve validation of "enable", "postimage" and "ttl" CDC options

---

configure.py
test/perf/perf.cc
test/perf/perf.hh
test/perf/perf_simple_query.cc

Calculate and display the number of memory allocations and tasks
executed per operation. Sample results (--smp 1):
180022.46 tps (90 allocs/op, 20 tasks/op)
178963.44 tps (90 allocs/op, 20 tasks/op)
178702.41 tps (90 allocs/op, 20 tasks/op)
177679.74 tps (90 allocs/op, 20 tasks/op)
179539.36 tps (90 allocs/op, 20 tasks/op)
median 178963.44 tps (90 allocs/op, 20 tasks/op)
median absolute deviation: 575.92
maximum: 180022.46
minimum: 177679.74
This allows less noisy tracking of how some changes impact performance.

test: perf: perf_simple_query: collect allocation and task statistics

---

repair/repair.cc

repair: Handle everywhere_topology in bootstrap_with_repair
The everywhere_topology returns the number of nodes in the cluster as
RF. This makes only streaming from the node losing the range impossible
since no node is losing the range after bootstrap.
Shortcut to stream from all nodes in local dc in case the keyspace is
everywhere_topology.
Fixes #8503

repair: Handle everywhere_topology in bootstrap_with_repair  

---

compound.hh
sstables/consumer.hh
sstables/index_reader.hh
sstables/kl/reader.cc
sstables/kl/reader_impl.hh
sstables/mx/parsers.hh
sstables/mx/reader.cc
sstables/promoted_index_blocks_reader.hh
sstables/sstable_mutation_reader.cc
sstables/sstable_mutation_reader.hh
test/boost/sstable_test.cc
utils/fragmented_temporary_buffer.hh

sstable cells are parsed into temporary_buffers, which causes large contiguous allocations for some cells. 
This is fixed by storing fragments of the cell value in a fragmented_temporary_buffer instead. 
To achieve this, this patch also adds new methods to the fragmented_temporary_buffer(size(), ostream& operator<<()) and adds methods to the underlying parser(primitive_consumer) for parsing byte strings into fragmented buffers.
Fixes #7457, and (as the last of 4 patches) #6376

sstables: remove large allocations when parsing cells

---

db/system_distributed_keyspace.cc
service/qos/service_level_controller.cc
service/qos/service_level_controller.hh

The service level controller spawns an updating thread,
which wasn't properly waited for during shutdown.
This behavior is now fixed.
Tests: manual
Fixes #8468

qos: make sure to wait for service level updates on shutdown

---

cql3/restrictions/statement_restrictions.cc
cql3/restrictions/statement_restrictions.hh
cql3/statements/modification_statement.cc
cql3/statements/select_statement.cc

In an ongoing effort to drop the `restrictions` class hierarchy, rewrite the partition-range calculation code to use the new `expression` objects.
Refs: #7217 #3815
Tests: unit (dev, debug)

Calculate partition ranges from expr::expression

---

reader_concurrency_semaphore.cc
reader_concurrency_semaphore.hh
reader_permit.hh
test/boost/multishard_mutation_query_test.cc
test/boost/mutation_reader_test.cc
test/boost/querier_cache_test.cc

This is a backport of https://github.com/scylladb/scylla/commit/8aaa3a7bb8db0f9f267d569e6892d9ddd33f71df to <= branch-4.5. The main conflicts were around Benny's reader close series (fa43d7680), but it also turned out that an additional patch (https://github.com/scylladb/scylla/commit/2f1d65ca110764baf92bb0fbf6ad5bb7a71dd6c3) also has to backported to make sure admission on signaling resources doesn't deadlock.
Refs: https://github.com/scylladb/scylla/issues/8493

[branch 4.5] Backport reader_permit: always forward resources to the semaphore

---

reader_concurrency_semaphore.cc
reader_concurrency_semaphore.hh
reader_permit.hh
test/boost/multishard_mutation_query_test.cc
test/boost/mutation_reader_test.cc
test/boost/querier_cache_test.cc

This is a backport of 8aaa3a7 to branch-4.4. The main conflicts were around Benny's reader close series (fa43d76), but it also turned out that an additional patch (2f1d65c) also has to backported to make sure admission on signaling resources doesn't deadlock.
Refs: #8493

[branch 4.4] Backport reader_permit: always forward resources to the semaphore 

---

idl/partition_checksum.idl.hh
repair/repair.hh
service/storage_service.cc
service/storage_service.hh

In commit 323f72e48a7d89d9edc40257a1f45c202accc146 (repair: Switch to
use NODE_OPS_CMD for replace operation), we switched replace operation
to use the new NODE_OPS_CMD infrastructure.
In this patch set, we continue the work to switch decommission and bootstrap 
operation to use NODE_OPS_CMD.
Fixes #8472
Fixes #8471

Switch to use NODE_OPS_CMD for decommission and bootstrap operation

---

cql3/statements/select_statement.cc
test/cql-pytest/test_secondary_index.py

When recreating the paging state from an indexed query,
a bunch of panic checks were introduced to make sure that
the code is correct. However, one of the checks is too eager -
namely, it throws an error if the base column type is not equal
to the view column type. It usually works correctly, unless the
base column type is a clustering key with DESC clustering order,
in which case the type is actually "reversed". From the point of view
of the paging state generation it's not important, because both
types deserialize in the same way, so the check should be less
strict and allow the base type to be reversed.
Tests: unit(release), along with the additional test case
introduced in this series; the test also passes
on Cassandra
Fixes #8666

Fix type checking in index paging

---

db/commitlog/commitlog.cc

Shutdown must never fail, otherwise it may cause hangs
as seen in https://github.com/scylladb/scylla/issues/8577.
This change wraps the file created in `allocate_segment_ex` in `make_checked_file` so that scylla will abort when failing to write to the commitlog files.
In case other errors are seen during shutdown, just log them and continue with shutting down to prevent scylla from hanging.
Fixes #8577

commitlog: make_checked_file for segments, report and ignore other errors on shutdown

---

test/alternator/run
test/cql-pytest/run
test/cql-pytest/run-cassandra
test/cql-pytest/run.py

In this small series, I rewrite test/alternator/run to Python using the utility functions developed for test/cql-pytest. In the future, we should do the same to test/redis/run and test/scylla-gdb/run.
The benefit of this rewrite is less code duplication (all run scripts start with the same duplicate code to deal with temporary directories, to run Scylla IP addresses, etc.), but most importantly - in the future fixes we do to cql-pytest (e.g., parameters needed to start Scylla efficiently, how to shut down Scylla, etc.) will appear automatically in alternator test without needing to remember to change both.
Another benefit is that test/alternator/run will now be Python, not a shell script. This should make it easier to integrate it into test.py (refs #6212) in the future - if we want to.

test/alternator: rewrite run script to share code with cql-pytest's run script

---

locator/token_metadata.cc
locator/token_metadata.hh
service/storage_proxy.cc

`ring_range()`/`tokens_iterator` are more complicated than they need to be. The `include_min` parameter is not used anywhere, and `tokens_iterator` is pimplified without a good reason. Simplify that.

locator: token_metadata: simplify `tokens_iterator`

---

cql3/statements/select_statement.cc
cql3/statements/select_statement.hh
test/boost/index_with_paging_test.cc

Indexed select statements fetch primary key information from
their internal materialized views and then use it to query
the base table. Unfortunately, the current mechanism for retrieving
base table rows makes it easy to overwhelm the replicas with unbounded
concurrency - the number of concurrent ops is increased exponentially
until a short read is encountered, but it's not enough to cap the
concurrency - if data is fetched row-by-row, then short reads usually
don't occur and as a result it's easy to see concurrency of 1M or
higher. In order to avoid overloading the replicas, the concurrency
of indexed queries is now capped at 4096 and additionally throttled
if enough results are already fetched. For paged queries it means that
the query returns as soon as 1MB of data is ready, and for …

cql3: limit the concurrency of indexed statements

---

gms/gossiper.cc
gms/gossiper.hh
service/storage_service.cc
service/storage_service.hh

This backport fixes the follow issue:
Cassandra stress fails to achieve consistency during replace node operation #8013
without the NODE_OPS_CMD infrastructure.
The commit c82250e0cfacb62617155ac98583ac90aed40133 (gossip: Allow deferring advertise of local node to be up) which fixes for
During replace node operation - replacing node is used to respond to read queries #7312
is already present in 4.5 branch.

Backport for 4.5: Fix replacing node takes writes

---

api/api-doc/storage_service.json
api/storage_service.cc
database.hh
db/snapshot-ctl.cc
db/snapshot-ctl.hh
table.cc
test/boost/database_test.cc

The option is provided by nodetool snapshot
https://docs.scylladb.com/operating-scylla/nodetool-commands/snapshot/
```
nodetool [(-h <host> | --host <host>)] [(-p <port> | --port <port>)]
[(-pp | --print-port)] [(-pw <password> | --password <password>)]
[(-pwf <passwordFilePath> | --password-file <passwordFilePath>)]
[(-u <username> | --username <username>)] snapshot
[(-cf <table> | --column-family <table> | --table <table>)]
[(-kc <kclist> | --kc.list <kclist>)]
[(-sf | --skip-flush)] [(-t <tag> | --tag <tag>)] [--] [<keyspaces...>]
-sf / –skip-flush    Do not flush memtables before snapshotting (snapshot will not contain unflushed data)
```
But is currently ignored by scylla-jmx (scylladb/scylla-jmx#167)
and not supported at the api level.
This patch adds support for the option in …

treewide: add support for snapshot skip-flush option

---

db/view/view.cc
db/view/view.hh
table.cc

This series addresses #8852 by:
* migrating to chunked_vector in view update generation code to avoid large allocations
* reducing the number of futures kept in mutate_MV, tracking how many view updates were already sent
Combined with #8853 I was able to only observe large partition warnings in the logs for the reproducing code, without crashes, large allocation or reactor stall warnings. The reproducing code itself is not part of cql-pytest because I haven't yet figured out how to make it fast and robust.
Tests: unit(release)
Refs  #8852

Avoid large allocs in mv update code

---

cql3/restrictions/statement_restrictions.cc
cql3/restrictions/statement_restrictions.hh
cql3/statements/select_statement.cc
test/cql-pytest/cassandra_tests/validation/entities/secondary_index_test.py

Another step towards dropping the `restrictions` class.  When calculating the partition slice of a global-index table, use `expression` objects instead of a `restrictions` subclass.
Refs #7217.
Tests: unit (all dev, some debug)

Use expressions to calculate the global-index partition slice

---

main.cc
service/qos/service_level_controller.cc
service/qos/service_level_controller.hh

The polling loop of the service level controller queries a distributed table in order to detect
configuration changes. If a node gets decommissioned, this loop continues to run until shutdown, if a node
stays in the decommissioned mode without being shut down, the loop will fail to query the table and this will
result in warnings and eventually errors in the log. This is not really harmful but it adds unnecessary noise
to the log.
The series below lays the infrastructure for observing storage service state changes, which eventually being
used to break the loop upon preparation for decommissioning.
Tests:
Unit test (dev)
Next Gating Dtests
Fixes #8836

Service Level Controller: Stop polling distributed data when decommissioned

---

main.cc
service/qos/service_level_controller.cc
service/qos/service_level_controller.hh

This is a rework of #8916 
The polling loop of the service level controller queries a distributed table in order to detect
configuration changes. If a node gets decommissioned, this loop continues to run until shutdown, if a node
stays in the decommissioned mode without being shut down, the loop will fail to query the table and this will
result in warnings and eventually errors in the log. This is not really harmful but it adds unnecessary noise
to the log.
The series below lays the infrastructure for observing storage service state changes, which eventually being
used to break the loop upon preparation for decommissioning.
Tests:
Unit test (dev)
Failing tests in jenkins.
Fixes #8836
The previous merge (possibly due to conflict resolution) contained a misplaced get that caused an abort on …

Service Level Controller: Stop polling distributed data when decommissioned (reworked)

---

flat_mutation_reader.cc
flat_mutation_reader.hh
flat_mutation_reader_v2.hh
test/lib/mutation_source_test.cc

The downgrade_to_v1 didn't reset the state of range tombstone assembler
in case of the calls to next_partition or fast_forward_to, which caused
a situation where the closing range tombstone change is cleared from the
buffer before being emitted, without notifying the assembler. This patch
fixes the behaviour in fast_forward_to as well.
Fixes #9022

flat_mutation_reader: downgrade_to_v1 - reset state of rt_assembler

---

cql3/restrictions/statement_restrictions.cc
test/cql-pytest/test_allow_filtering.py
test/cql-pytest/test_secondary_index.py

Add examples from issue #8991 to tests
Both of these tests pass on `cassandra 4.0` but fail on `scylla 4.4.3`
First test tests that selecting values from indexed table using only clustering key returns correct values.
The second test tests that performing this operation requires filtering.
The filtering test looks similar to [the one for #7608](https://github.com/scylladb/scylla/blob/1924e8d2b63e6611b78ac6252b5ddbc4884f9d22/test/cql-pytest/test_allow_filtering.py#L124) but there are some differences - here the table has two clustering columns and an index, so it could test different code paths.
Contains a quick fix for the `needs_filtering()` function to make these tests pass.
It returns `true` for this case and the one described in #7708.
This implementation is a bit conservative - it …

cql-pytest: Test selecting from indexed table using only clustering key

---

db/batchlog_manager.cc
db/batchlog_manager.hh
main.cc
service/storage_service.cc

This PR contains the parts relevant to batchlog_manager stop in #8998 without adding a gate to the storage_proxy for synchronization with on-going queries in storage_proxy::drain_on_shutdown.
As explained in #9009, we see that the batchlog_manager isn't stopped if scylla shuts down during startup, e.g. when waiting for gossip to settle, since currently the batchlog_manager is stopped only from `storage_service::do_drain`, while `storage_service::drain_on_shutdown` deferred shutdown is installed only later on:
https://github.com/scylladb/scylla/blob/222ef17305b07e8faabd5d921e2bad0d7f78e106/main.cc#L1419-L1421
Fixes #9009
DTest: compact_storage_tests.py:TestCompactStorage.wide_row_test paging_test:TestPagingDatasetChanges.test_cell_TTL_expiry_during_paging …

Harden batchlog_manager stop and call from main in deferred action

---

api/storage_service.cc
database.hh
db/system_keyspace.cc
db/system_keyspace.hh
db/virtual_table.cc
db/virtual_table.hh
dht/token_range_endpoints.hh
distributed_loader.cc
distributed_loader.hh
flat_mutation_reader.cc
main.cc
mutation_reader.cc
mutation_reader.hh
service/storage_service.cc
test/boost/virtual_table_mutation_source_test.cc
test/lib/cql_test_env.cc
test/lib/mutation_source_test.cc
test/lib/mutation_source_test.hh
thrift/handler.cc

This is the 2nd PR in series with the goal to finish the hackathon project authored by @tgrabiec, @kostja, @amnonh and @mmatczuk (improved virtual tables + function call syntax in CQL). This one introduces a new implementation of the virtual tables, the streaming tables, which are suitable for large amounts of data.
This PR was created by @jul-stas and @StarostaGit

db/virtual_table: Streaming tables for large data + describe_ring example table

---

db/schema_tables.cc

schema_tables is quite hairy, but can be easily simplified with coroutines.
In addition to switching future-returning functions to coroutines, we also
switch Seastar threads to coroutines. This is less of a clear-cut win; the
motivation is to reduce the chances of someone calling a function that
expects to run in a thread from a non-thread context. This sometimes works
by accident, but when it doesn't, it's pretty bad. So a uniform calling convention
has some benefit.
I left the extra indents in, since the indent-fixing patch is hard to rebase in case
a rebase is needed. I will follow up with an indent fix post merge.
Test: unit (dev, debug, release)

db: schema_tables: coroutinize

---

repair/repair.cc
repair/repair.hh

This series improves the repair logging by removing the unused sub_ranges_nr counter, adding peer node ip in the log, removing redundant logs in case of error.

repair: Log improvement and cleanup

---

configure.py
service/qos/qos_configuration_change_subscriber.hh
service/qos/service_level_controller.cc
service/qos/service_level_controller.hh
test/boost/service_level_controller_test.cc

In order to decouple the service level controller from the systems logic, we introduce an API for subscribing to configuration changes. The timing of the call was determined with resource creation and destruction in mind. An API subscriber can create
resources that will be available from the very start of the service level existence it can also destroy them since the service level
is guarantied not to exist anymore at the time of the call to the deletion notification callback.
Testing:
unit tests - all + a newly added one.
dtests - next-gating (dev mode)

Add service level config change subscription API

---

db/view/view.cc
db/view/view_builder.hh
main.cc

In order to be able to avoid a deadlock when CQL server cannot be started,
the view builder shutdown procedure is now split to two parts -
- drain and stop. Drain is performed before storage proxy shutdown,
but stop() will be called even before drain is scheduled.
The deadlock is as follows:
- view builder creates a reader permit in order to be able
to read from system tables
- CQL server fails to start, shutdown procedure begins
- view builder stop() is not called (because it was not scheduled
yet), so it holds onto its reader permit
- database shutdown procedure waits for all permits to be destroyed,
and it hangs indefinitely because view builder keeps holding
its permit.
Fixes #9306

Split view builder shutdown procedure to drain + stop

---

enum_set.hh
partition_slice_builder.hh
query.cc
test/boost/enum_set_test.cc

The above mentioned method is supposed to work both ways: reversed <-> forward, so setting the reversed bit is not correct: it should be toggled, which is what this mini-series does.

query::reverse_slice(): toggle reversed bit instead of setting it

---

database.hh
db/commitlog/commitlog_entry.hh
db/commitlog/commitlog_types.hh
db/commitlog/rp_set.hh
table.cc
test/boost/database_test.cc
test/manual/sstable_scan_footprint_test.cc
test/perf/perf_cache_eviction.cc

There are now 231 translation units that indirectly include commitlog.hh
due to the need to have access to db::commitlog::force_sync.
Move that type to a new file commitlog_types.hh and make it available
without access to the commitlog class.
This reduces the number of translation units that depend on commitlog.hh
to 84, improving compile time.

commitlog: reduce inclusions of commitlog.hh due to db::commitlog::force_sync

---

service/qos/qos_configuration_change_subscriber.hh
service/qos/service_level_controller.cc
test/boost/service_level_controller_test.cc

In order to ease future extensions to the information being sent
by the service level configuration change API, we pack the additional
parameters (other the the service level options) to the interface in a
structure. This will allow an easy expansion in the future if more
parameters needs to be sent to the observer.
Signed-off-by: Eliran Sinvani <eliransin@scylladb.com>

Service Level Controller: Add an extention point to the API

---

compaction/compaction.cc
compaction/compaction_manager.cc
sstables/exceptions.hh
sstables/sstable_directory.cc

The gist of this series is splitting `compaction_abort_exception` from `compaction_stop_exception`
and their respective error messages to differentiate between compaction being stopped due to e.g. shutdown
or api event vs. compaction aborting due to scrub validation error.
While at it, cleanup the existing retry logic related to `compaction_stop_exception`.
Dtest: nodetool_additional_test.py:TestNodetool.{{scrub,validate}_sstable_with_invalid_fragment_test,{scrub,validate}_ks_sstable_with_invalid_fragment_test,{scrub,validate}_with_one_node_expect_data_loss_test} (dev, w/ https://github.com/scylladb/scylla-dtest/pull/2267)

Cleanup compaction_stop_exception

---

docs/design-notes/IDL.md
idl-compiler.py
message/messaging_service.cc
message/rpc_protocol_impl.hh

Introduce new syntax in IDL compiler to allow generating
registration/sending code for RPC verbs:
```
verb [[attr1, attr2...] my_verb (args...) -> return_type;
```
`my_verb` RPC verb declaration corresponds to the
`netw::messaging_verb::MY_VERB` enumeration value to identify the
new RPC verb.
For a given `idl_module.idl.hh` file, a registrator class named
`idl_module_rpc_verbs` will be created if there are any RPC verbs
registered within the IDL module file.
These are the methods being created for each RPC verb:
```
static void register_my_verb(netw::messaging_service* ms, std::function<return_type(args...)>&&);
static future<> unregister_my_verb(netw::messaging_service* ms);
static future<> send_my_verb(netw::messaging_service* ms, netw::msg_addr id, args...);
```
Each method accepts a …

IDL: support generating boilerplate code for RPC verbs

---

dist/common/scripts/scylla_io_setup
dist/common/scripts/scylla_util.py

Currently, scylla-server fails to start on ARM instances because scylla_io_setup does not have preset parameters even instance type added to 'supported instance'.
To fix this, we need to add io parameter preset on scylla_io_setup.
Also, we mistakenly added EBS only instances at a004b1da305a8a83d94e5ea585b6f41a69647640, need to remove them.
Instrances does not have ephemeral disk should be 'unsupported instance', we still run our AMI on it, but we print warning message on login prompt, and user requires to run scylla_io_setup.
Fixes #9493

AWS: add scylla_io_setup preset parameters for ARM instances

---

alternator/executor.cc
alternator/expressions.cc
alternator/serialization.cc
alternator/serialization.hh
test/alternator/test_item.py
test/alternator/test_update_expression.py

In UpdateItem's AttributeUpdates (old-style parameter) we were missing
support for the ADD operation - which can increment a number, or add
items to sets (or to lists, even though this fact isn't documented).
This two-patch series add this missing feature. The first patch just moves
an existing function to where we can reuse it, and the second patch is
the actual implementation of the feature (and enabling its test).
Fixes #5893

alternator: add support for AttributeUpdates Add operation

---

dist/common/scripts/scylla_ntp_setup
dist/common/scripts/scylla_util.py

On scylla_unit.py, we provide `systemd_unit.is_active()` to return `systemctl is-active` output.
When we introduced systemd_unit class, we just returned `systemctl is-active` output as string, but we changed the return value to bool after that (2545d7fd438338263d0cc52eb8e7433fb61afee7).
This was because `if unit.is_active():` always becomes True even it returns "failed" or "inactive", to avoid such scripting bug.
However, probably this was mistake.
Because systemd unit state is not 2 state, like "start" / "stop", there are many state.
And we already using multiple unit state ("activating", "failed", "inactive", "active") in our Cloud image login prompt:
https://github.com/scylladb/scylla-machine-image/blob/next/common/scylla_login#L135
After we merged …

Revert "scylla_util.py: return bool value on systemd_unit.is_active()"

---

db/commitlog/commitlog.cc
test/boost/commitlog_test.cc

If allocate_segment_ex fail, we should put the filename opened/created into delete set to ensure we reclaim disk space.
Similarly, if we fail/skip recycling a segment file in delete_segments we should still signal recycle waiters iff a disk delete was done, since this might change wait conditions (i.e. space used)

commitlog: handle allocation/recycle failure better

---

alternator/auth.hh
auth/permissions_cache.hh
cql3/authorized_prepared_statements_cache.hh
cql3/prepared_statements_cache.hh
cql3/query_processor.cc
cql3/query_processor.hh
test/boost/loading_cache_test.cc
utils/loading_cache.hh

This series introduces a new version of a loading_cache class.
The old implementation was susceptible to a "pollution" phenomena when frequently used entry can get evicted by an intensive burst of "used once" entries pushed into the cache.
The new version is going to have a privileged and unprivileged cache sections and there's a new loading_cache template parameter - SectionHitThreshold. The new cache algorithm goes as follows:
* We define 2 dynamic cache sections which total size should not exceed the maximum cache size.
* New cache entry is always added to the "unprivileged" section.
* After a cache entry is read more than SectionHitThreshold times it moves to the second cache section.
* Both sections' entries obey expiration and reload rules in the same way as before this patch.
* …

Loading cache improve eviction use policy

---

db/commitlog/commitlog.cc
test/boost/commitlog_test.cc

Backport of series to 4.6
Refs #9348

Backport of #9348 (xceptions in commitlog::segment_manager::delete_segments could cause footprint counters to loose track)

---

compaction/compaction.cc
db/view/view.cc
db/view/view_update_generator.cc
sstables/sstable_set.cc
sstables/sstable_set.hh
table.cc
test/boost/sstable_compaction_test.cc

Since sstable reader was already converted to flat_mutation_reader_v2, compaction layer can naturally be converted too.
There are many dependencies that use v1. Those strictly needed like readers in sstable set, which links compaction to sstable reader, were converted to v2 in this series. For those that aren't essential we're relying on V1<-->V2 adaptors, and conversion work on them will be postponed. Those being postponed are: scrub specialized reader (needs a validator for mutation_fragment_v2), interposer consumer, combined reader which is used by incremental selector. incremental selector itself was converted to v2.
tests: unit(debug).

Convert compaction to flat_mutation_reader_v2

---

configure.py

Clang (and gcc) can combine loads and stores of independent variables
into wider operations, often using vector registers. This reduces
instruction count and execution unit occupancy. However, clang
is too aggressive and generates loads that break the store-to-load
forwarding rules: a load must be the same size or smaller than the
corresponding load, or it will execute with a large penalty.
Disabling slp results in larger but faster code. Comparing
before and after on Zen 3:
slp:
226766.49 tps ( 75.1 allocs/op,  12.1 tasks/op,   45073 insns/op)
226679.57 tps ( 75.1 allocs/op,  12.1 tasks/op,   45074 insns/op)
226168.79 tps ( 75.1 allocs/op,  12.1 tasks/op,   45061 insns/op)
225884.34 tps ( 75.1 allocs/op,  12.1 tasks/op,   45068 insns/op)
225998.16 tps ( 75.1 allocs/op,  12.1 tasks/op, …

build: disable superword-level parallism (slp) on clang

---

cql3/column_identifier.cc
cql3/column_identifier.hh
cql3/expr/expression.hh
cql3/selection/selectable.cc

column_identifier serves two purposes: a value type used to denote an
identifier (which may or may not map to a table column), and `selectable`
implementation used for selecting table columns. This stands in the way
of further refactoring - the unification of the WHERE clause prepare path
(prepare_expression()) and the SELECT clause prepare path
(prepare_selectable()).
Reduce the entanglement by moving the selectable-specific parts to a new
type, selectable_column, and leaving column_identifier as a pure value type.

cql3: disentangle column_identifier from selectable

---

range_tombstone_list.cc
range_tombstone_list.hh
test/boost/range_tombstone_list_test.cc

Appending an empty range adjacent to an existing range tombstone would
not deoverlap (by dropping the empty range tombstone) resulting in
different (non canoncial) result depending on the order of appending.
Suppose that range tombstone [a, b] covers range tombstone [x, x), and [a, x) and [x, b) are range tombstones which correspond to [a, b] split around position x.
Appending [a, x) then [x, b) then [x, x) would give [a, b)
Appending [a, x) then [x, x) then [x, b) would give [a, x), [x, x), [x, b)
The fix is to drop empty range tombstones in range_tombstone_list so that the result is canonical.
Fixes #9661

db: range_tombstone_list: Deoverlap empty range tombstones

---

scylla-gdb.py

Catches inconsistencies in LSA state.
Currently:
- discrepancy between segment set in _closed_segments and shard's
segment descriptors
- cross-shard segment references in _closed_segments
- discrepancy in _closed_occupancy stats and what's in segment
descriptors
- segments not present in _closed_segments but present in
segment descriptors
Refs https://github.com/scylladb/scylla/issues/9544

gdb: Introduce "scylla lsa-check"

---

gms/feature.hh
gms/feature_service.cc
gms/feature_service.hh
idl/read_command.idl.hh
mutation_partition.cc
query_class_config.hh
service/storage_proxy.cc

The default for get_unlimited_query_max_result_size() is 100MB (adjustable through config), whereas query::result_memory_limiter::maximum_result_size is 1MB (hard coded, should be enough for everybody)
This limit is then used by the replica to decide when to break pages and, in case of reversed clustering order reads, when to fail the read when accumulated data crosses the threshold. The latter behavior stems from the fact that reversed reads had to accumulate all the data (read in forward order) before they can reverse it and return the result. Reverse reads thus need a higher limit so that they have a higher chance of succeeding.
Most readers are now supporting reading in reverse natively, and only reversing wrappers (make_reversing_reader()) inserted on top of ka/la sstable readers …

Use the same page size limit in reverse queries as in forward reads

---

gms/gossiper.cc
service/misc_services.cc
service/storage_proxy.cc
utils/loading_cache.hh

Some code assumes that lowres_clock::duration is milliseconds, but public
documentation never claimed that. Harden the code for a change in the
definition by removing the assumptions.

Fix bad lowres_clock::duration assumptions

---

replica/database.cc
replica/database.hh

Fixes #9408
While it is rare, some customer issues have shown that we can run into cases where commit log apply (writing mutations to it) fails badly. In the known cases, due to oversized mutations. While these should have been caught earlier in the call chain really, it would probably help both end users and us (trying to figure out how they got so big and how they got so far) iff we added info to the errors thrown (and printed), such as ks, cf, and mutation content.
Somewhat controversial, this makes the apply with CL decision path coroutinized, mainly to be able to do the error handling    for the more informative wrapper exception easier/less ugly. Could perhaps do with futurize_invoke + then_wrapper also. But future is coroutines...
This is as stated somewhat problematic, it adds an …

database: Add error message with mutation info on commit log apply failure

---

data_dictionary/data_dictionary.cc
data_dictionary/data_dictionary.hh
data_dictionary/impl.hh
replica/database.cc
thrift/controller.cc
thrift/handler.cc
thrift/handler.hh
thrift/server.cc
thrift/server.hh

replica::database is (as its name indicates) a replica-side service, while thrift
is coordinator-side. Convert thrift's use of replica::database for data dictionary
lookups to the data_dictionary module. Since data_dictionary was missing a
get_keyspaces() operation, add that.
Thrift still uses replica::database to get the schema version. That should be
provided by migration_manager, but changing that is left for later.

thrift: switch to replica::database uses to data_dictionary

---

cdc/generation.cc
cdc/generation_service.hh
gms/gossiper.cc
gms/gossiper.hh
gms/i_endpoint_state_change_subscriber.hh
locator/production_snitch_base.cc
locator/reconnectable_snitch_helper.hh
repair/row_level.cc
service/load_broadcaster.hh
service/migration_manager.cc
service/migration_manager.hh
service/misc_services.cc
service/qos/service_level_controller.cc
service/storage_service.cc
service/storage_service.hh
service/view_update_backlog_broker.hh
streaming/stream_manager.cc
streaming/stream_manager.hh
utils/atomic_vector.hh

This series greatly reduces gossipers' dependence on `seastar::async` (yet, not completely).
`i_endpoint_state_change_subscriber` callbacks are converted to return futures (again, to get rid of `seastar::async` dependency), all users are adjusted appropriately (e.g. `storage_service`, `cdc::generation_service`, `streaming::stream_manager`, `view_update_backlog_broker` and `migration_manager`).
This includes futurizing and coroutinizing the whole function call chain up to the `i_endpoint_state_change_subscriber` callback functions.
To aid the conversion process, a non-`seastar::async` dependent variant of `utils::atomic_vector::for_each` is introduced (`for_each_futurized`). A different name is used to clearly distinguish converted and non-converted code, so that the last step (remove …

gms, service: futurize and coroutinize gossiper-related code

---

conf/scylla.yaml
db/config.cc
db/config.hh
replica/database.cc
replica/database.hh
replica/table.cc

Just in case the new algorithm turns out to be buggy, or give a
performance regression, add a flag to fall-back to the old algorithm for
use in the field.

db: config: add a flag to disable new reversed reads algorithm

---

dist/common/scripts/scylla_raid_setup

We found that monitor mode of mdadm does not work on RAID0, and it is
not a bug, expected behavior according to RHEL developer.
Therefore, we should stop enabling mdmonitor when RAID0 is specified.
Fixes #9540
----
This reverts 0d8f932 and introduce correct fix.

scylla_raid_setup: use mdmonitor only when RAID level > 0

---

db/snapshot-ctl.cc
db/snapshot-ctl.hh
replica/database.cc
replica/database.hh
replica/table.cc
test/boost/database_test.cc

Snapshot-ctl methods fetch information about snapshots from
column family objects. The problem with this is that we get rid
of these objects once the table gets dropped, while the snapshots
might still be present (the auto_snapshot option is specifically
made to create this kind of situation). This commit switches from
relying on column family interface to scanning every datadir
that the database knows of in search for "snapshots" folders.
This PR is a rebased version of #9539 (and slightly cleaned-up, cosmetically)
and so it replaces the previous PR.
Fixes #3463
Closes #7122

snapshots: Fix snapshot-ctl to include snapshots of dropped tables

---

api/api.cc
api/api.hh
api/storage_service.cc
test/rest_api/test_storage_service.py

Refs #10087
Add validation of all params for the keyspace_scrub api.
The validation method is generic and should be used by all apis eventually,
but I'm leaving that as follow-up work.
While at it, fixed the exception types thrown on invalid `scrub_mode` or `quarantine_mode` values from `std::runtime_error` to `httpd::bad_param_exception` so to generate the `bad_request` http status.
And added unit tests to verify that, and the handling of an unknown parameter.
DTest: nodetool_additional_test.py::TestNodetool::{test_scrub_with_one_node_expect_data_loss,test_scrub_with_multi_nodes_expect_data_rebuild,test_scrub_sstable_with_invalid_fragment,test_scrub_ks_sstable_with_invalid_fragment,test_scrub_segregate_sstable_with_invalid_fragment,test_scrub_segregate_ks_sstable_with_inva …

api: keyspace_scrub: validate params

---

cql3/statements/select_statement.cc
cql3/statements/select_statement.hh
exceptions/exceptions.hh
service/pager/query_pager.hh
service/pager/query_pagers.cc
service/storage_proxy.cc
service/storage_proxy.hh
test/boost/result_utils_test.cc
utils/exception_container.hh
utils/result.hh
utils/result_combinators.hh
utils/result_loop.hh
utils/result_try.hh

This PR propagates the read coordinator logic so that read timeout and read failure exceptions are propagated without throwing on the coordinator side.
This PR is only concerned with exceptions which were originally thrown by the coordinator (in read resolvers). Exceptions propagated through RPC and RPC timeouts will still throw, although those exceptions will be caught and converted into exceptions-as-values by read resolvers.
This is a continuation of work started in #10014.
Results of `perf_simple_query --smp 1 --operations-per-shard 1000000` (read workload), compared with merge base (10880fb0a720e3dcddcb301f8f1c624923e89a03):
```
BEFORE:
125085.13 tps ( 80.2 allocs/op,  12.2 tasks/op,   49010 insns/op)
125645.88 tps ( 80.2 allocs/op,  12.2 tasks/op,   49008 insns/op)
126148.85 tps ( …
```

Propagate CQL coordinator timeouts and failures for reads

---

cql3/type_json.cc
test/boost/json_cql_query_test.cc

Add support for specifing integers in scientific format (for example 1.234e8) in INSERT JSON statement:
```
INSERT INTO table JSON '{"int_column": 1e7}';
```
Before the JSON parsing library was switched to RapidJSON from JsonCpp, this statement used to work correctly, because JsonCpp transparently casts double to integer value.
Inserting a floating-point number ending with .0 is allowed, as the fractional part is zero. Non-zero fractional part (for example 12.34) is disallowed. A new test is added to test all those behaviors.
This behavior differs from Cassandra, which disallows those types of numbers (1e7, 123.0 and 12.34), however some users rely on that behavior and JSON specification itself does not distinct between floating-point numbers and integer numbers (only a single "number" …

Allow integers in scientific format in `INSERT JSON` 

---

compound_compat.hh
db/view/view.cc
dht/murmur3_partitioner.cc
sstables/sstables.cc
test/boost/sstable_test.cc
test/boost/view_schema_pkey_test.cc
test/cql-pytest/test_materialized_view.py
test/cql-pytest/test_secondary_index.py

Cassandra generally does not allow empty strings as partition keys (note, by the way, that empty strings are allowed as clustering keys, as well as in individual components of a compound partition key).
However, Cassandra does allow empty strings in _regular_ columns - and those regular columns can be indexed by a secondary index, or become an empty partition-key column in a materialized view. As noted in issues #9375 and #9364 and verified in a few xfailing cql-pytest tests, Scylla didn't allow these cases - and this patch series fixes that.
Before the last patch in this series finally enables empty-string partition keys in materialized views, we first need to solve a couple of bugs in our code related to handling empty partition keys:
The first patch fixes issue #10178 - a bug in …

Allow empty partition keys in views

---

query.cc

It was a suggestion from @psarna, done to get more info about the abort from #10174.

query: transform asserts into `on_internal_error` in `forward_result::merge`

---

compaction/compaction.cc
compaction/compaction.hh
compaction/compaction_manager.cc
compaction/compaction_manager.hh
sstables/sstable_directory.cc
test/boost/sstable_compaction_test.cc
test/lib/sstable_utils.cc
test/lib/sstable_utils.hh

The series overhauls the compaction_manager::task design and implementation
by properly layering the functionality between the compaction_manager
that deals with generic task execution, and the per-task business logic that is defined
in a set of classes derived from the generic task class.
While at it, the series introduces `task::state` and a set of helper functions to manage it
to prevent leaks in the statistics, fixing #9974.
Two more stats counter were exposed: `completed_tasks` and a new `postponed_tasks`.
Test: sstable_compaction_test
Dtest: compaction_test.py compaction_additional_test.py
Fixes #9974

Overhaul compaction_manager::task

---

replica/memtable.cc
replica/memtable.hh
replica/table.cc
row_cache.cc
row_cache.hh

When row_cache::make_reader() and memtable::make_flat_reader() see that the query result is empty, they return empty_flat_reader, which is a trivial implementation of flat_mutation_reader.
Even though empty_flat_reader doesn't do anything meaningful, it still needs to be created, handled in merging_reader and destroyed. Turns out this is costly.
This patch series replaces hot path uses of empty_flat_reader with an empty optional.
Performance effects:
`perf_simple_query --smp 1`
TPS: 138k -> 168k
allocs/op: 80.2 -> 71.1
insns/op: 49.9k -> 45.1k
`perf_simple_query --smp 1 --enable-cache=1 --flush`
TPS: 125k -> 150k
allocs/op: 79.2 -> 71.1
insns/op: 51.7k -> 47.2k
For a cassandra-stress benchmark (localhost, 100% cache reads) this translates to a TPS increase from ~42k to ~48k per …

replica: Optimize empty_flat_reader out of the hot path

---

cql3/expr/expression.cc
test/cql-pytest/test_filtering.py
test/cql-pytest/test_null.py

In the filtering expression "WHERE m[?] = 2", our implementation was buggy when either the map, or the subscript, was NULL (and also when the latter was an UNSET_VALUE). Our code ended up dereferencing null objects, yielding bizarre errors when we were lucky, or crashes when we were less lucky - see examples of both in issues #10361, #10399, #10401. The existing test `test_null.py::test_map_subscript_null` reproduced all these bugs sporadically.
In this series we improve the test to reproduce the separate bugs separately, and also reproduce additional problems (like the UNSET_VALUE). We then **define** both `m[NULL]` and `NULL[2]` to result in NULL instead of the existing undefined (and buggy, and crashing) behavior. This new definition is consistent with our usual SQL-inspired tradition …

Fix map subscript crashes when map or subscript is null

---

replica/database.cc
replica/database.hh
test/boost/database_test.cc

Said method has to evict all querier cache entries, belonging to the to-be-dropped table. This is already the case, but there was a window where new entries could sneak in, causing a stale reference to the table to be de-referenced later when they are evicted due to TTL. This window is now closed, the entries are evicted after the method has waited for all ongoing operations on said table to stop.
Fixes: #10450

replica/database: drop_column_family(): properly cleanup stale querier cache entries

---

test/boost/loading_cache_test.cc
test/lib/cql_test_env.cc
test/lib/cql_test_env.hh
utils/loading_cache.hh

This series enforces a minimum size of the unprivileged section when
performing `shrink()` operation.
When the cache is shrunk, we still drop entries first from unprivileged
section (as before this commit), however, if this section is already small
(smaller than `max_size / 2`), we will drop entries from the privileged
section.
This is necessary, as before this change the unprivileged section could
be starved. For example if the cache could store at most 50 entries and 
there are 49 entries in privileged section, after adding 5 entries (that would 
go to unprivileged section) 4 of them would get evicted and only the 5th one 
would stay. This caused problems with BATCH statements where all 
prepared statements in the batch have to stay in cache at the same time 
for the batch to correctly …

loading_cache: force minimum size of unprivileged 

---

auth/default_authorizer.cc
auth/password_authenticator.cc
auth/roles-metadata.cc
auth/service.cc
auth/standard_role_manager.cc
cql3/query_processor.cc
cql3/query_processor.hh
db/batchlog_manager.cc
db/legacy_schema_migrator.cc
db/query_context.hh
db/schema_tables.cc
db/system_distributed_keyspace.cc
db/system_keyspace.cc
service/raft/raft_group0.cc
service/raft/raft_sys_table_storage.cc
test/boost/batchlog_manager_test.cc
test/boost/cql_query_test.cc
test/boost/query_processor_test.cc

There was some doubts about which internal prepared statements are cached and which aren't.
In addition some queries that should have been cached (IMO), weren't. This PR adds some verbosity
to the caching enabling parameter as well as adding caching to some queries.
As a followup I would suggest to have internal queries as a compile time strings that have a compile time hash, this
will make the cache lookup not be dependent on the query textual length as it is today, this makes sense given that the
queries are static even today.

Make internal statements caching more coherent

---

compaction/compaction.cc
compaction/compaction.hh
compaction/compaction_strategy.hh
readers/flat_mutation_reader.hh

This series gets rid of the remaining usage of flat_mutation_reader v1 in compaction
Test: sstable_compaction_test

compaction: get rid of reader v1

---

dirty_memory_manager.hh
replica/database.cc
replica/database.hh
replica/table.cc
test/boost/database_test.cc

This series fixes a few issue on the table truncate path:
- "memtable_list: safely futurize clear_and_add"
- reinstates an async version of table::clear_and_add, just safe against #10421
- a unit test reproducing #10421 was added to make sure the new version is indeed safe.
- "table: clear: serialize with ongoing flush" fixes #10423
- a unit test reproducing #10423 was added
Fixes #10281
Fixes #10423
Test: unit(dev), database_test. test_truncate_without_snapshot_during_{writes,flushes} (debug)

Harden table truncate

---

sstables/index_reader.hh
test/boost/sstable_datafile_test.cc
test/lib/random_schema.cc
test/lib/random_schema.hh

Attempting to call advance_to() on the index, after it is positioned at EOF, can result in an assert failure, because the operation results in an attempt to move backwards in the index-file (to read the last index page, which was already read). This only happens if the index cache entry belonging to the last index page is evicted, otherwise the advance operation just looks-up said entry and returns it. To prevent this, we add an early return conditioned on eof() to all the partition-level advance-to methods.
A regression unit test reproducing the above described crash is also added.
Fixes: #10403

sstables/index_reader: short-circuit fast-forward-to when at EOF

---

sstables/consumer.hh
utils/fragmented_temporary_buffer.hh

primitive_consumer::read_bytes() destroys and creates a vector for every value it reads.
This happens for every cell.
We can save a bit of work by reusing the vector.

 sstables: consumer: reuse the fragmented_temporary_buffer in read_bytes()

---

api/api-doc/storage_service.json
api/storage_service.cc
db/legacy_schema_migrator.cc
db/schema_tables.cc
db/snapshot-ctl.cc
db/snapshot-ctl.hh
replica/database.cc
replica/database.hh
replica/table.cc
test/boost/database_test.cc
test/boost/extensions_test.cc
test/cql-pytest/util.py
test/rest_api/rest_util.py
test/rest_api/test_storage_service.py

This series refactors `table::snapshot` and moves the responsibility
to flush the table before taking the snapshot to the caller.
`flush_on_all` and `snapshot_on_all` helpers are added to replica::database
(by making it a peering_sharded_service) and upper layers,
including api and snapshot-ctl now call it instead of calling cf.snapshot directly.
With that, error are handed in table::snapshot and propagated
back to the callers.
Failure to allocate the `snapshot_manager` object is fatal,
similar to failure to allocate a continuation, since we can't
coordinate across the shards without it.
Test: unit(dev), rest_api(debug)
Fixes #10500

Handle errors during snapshot

---

docs/guides/debugging.md
gdbinit

This series update debugging.md with:
- add an example .gdbinit file
- update recommendation for finding the relocatable packages using a build-id on http://backtrace.scylladb.com/

Docs: improve debugging.md

---

compaction/compaction_manager.hh
replica/table.cc
test/boost/mutation_test.cc
test/boost/sstable_3_x_test.cc
test/boost/sstable_compaction_test.cc
test/boost/sstable_resharding_test.cc
test/lib/test_services.hh
test/perf/perf_sstable.hh

Reapply: "disable_auto_compaction: stop ongoing compactions"
This is a reapplication of a former commit
https://github.com/scylladb/scylla/commit/4affa801a5ea1994e226d3e7581f3f38506dcc22 which was reverted by
https://github.com/scylladb/scylla/commit/8e8dc2c930f5541531c3326127f012e7bc6292ef.
This commit is a fixed version of the original where a call to the
compaction_manager constructor accidentally issued (`compaction_manager()`)
instead a call to retrieve a compaction manager reference
(`get_compaction_manager()`), we don't use this function because it
doesn't exist anymore - it existed at the time the patch was written
bu was removed in https://github.com/scylladb/scylla/commit/9066224cf4a8634867128e7d2d9e0032df46af8a later on,
instead, we just use the private table member …

Reapply: "disable_auto_compaction: stop ongoing compactions"

---

scylla-gdb.py
test/scylla-gdb/test_misc.py

This series adds two commands:
* scylla sstable-summary
* scylla sstable-index-cache
The former dumps the content of the sstable summary. This component is kept in memory in its entirety, so this can be easily done. The latter command dumps the content of the sstable index cache. This contains all the index-pages that are currently cached. The promoted index is not dumped yet and there is no indication of whether a given entry is in the LRU or not, but this already allows at seeing what pages are in the cache and what aren't.

scylla-gdb.py: add commands to dump sstables summary and index-cache

---

idl-compiler.py
mutation_partition_view.cc
query-result-reader.hh
serializer_impl.hh
test/boost/frozen_mutation_test.cc
test/boost/idl_test.cc
test/boost/serialization_test.cc

Currently, the idl-generated deserialization code, e.g. mutation_partition_view::rows() deserializes and returns a complete utils::chunked_vector<deletable_row_view> . And that could be arbitrarily long.
To consume it gently, we don't need the whole vector in advance, but rather we can consume it one element at a time (and in a nested way for cells in a row in the future).
Use `range_deserializer` to consume range tombstones and rows one item at a time.
We may consider in the future also gently iterating over cells
in a row and then dipping into collection cells that might also
contain a large number of items.
Fixes #10558

Add range deserializer

---

test/boost/cql_query_test.cc
types.cc
types.hh
types/listlike_partial_deserializing_iterator.hh

Let's say we have a query like:
```cql
INSERT INTO ks.t (list_column) VALUES (?);
```
And the driver sends a list with null inside as the bound value, something like `[1, 2, null, 4]`.
In such case we should throw `invalid_request_exception` because `nulls` are not allowed inside collections.
Currently when a query like this gets executed Scylla throws an ugly marshalling error.
This is because the validation code reads size of the next element, interprets it as an unsigned integer and tries to read this much.
In case of `null` element the size is `-1`, which when converted to unsigned `size_t` gives 18446744073709551615 and it fails to read this much.
This PR adds proper validation checks to make the error message better.
I also added some tests.
I originally tried to write them in …

cql: Add proper validation for null and unset inside collections send as bound values

---

message/messaging_service.cc
readers/mutation_readers.cc

The handle must not point at this reader implementation after it's destroyed.
This fixes use-after-free when the queue_reader_v2
is destroyed first as repair_writer_impl::_queue_reader,
before repair_writer_impl::_mq is destroyed.
The issue was introduced in 39205917a8d77ebd4608f95afd0fb40ab38d6c0a
in the definition of `repair_writer_impl`.
Fixes #10528
While at it, fix also an ignored exceptional future seen in the test:
`repair_additional_test.py::TestRepairAdditional::test_repair_kill_3`

Fix use-after-free when queue reader is destroyed before its handle

---

repair/repair.cc
repair/repair.hh
repair/row_level.hh

This patch set adds two commits to allow trigger off strategy early for node operations.
*) repair: Repair table by table internally
This patch changes the way a repair job walks through tables and ranges
if multiple tables and ranges are requested by users.
Before:
```
for range in ranges
for table in tables
repair(range, table)
```
After:
```
for table in tables
for range in ranges
repair(range, table)
```
The motivation for this change is to allow off-strategy compaction to trigger
early, as soon as a table is finished. This allows to reduce the number of
temporary sstables on disk. For example, if there are 50 tables and 256 ranges
to repair, each range will generate one sstable. Before this change, there will
be 50 * 256 sstables on disk before off-strategy compaction triggers. After …

Allow trigger off strategy compaction early for node operations

---

cql3/expr/expression.cc
cql3/expr/expression.hh
cql3/expr/prepare_expr.cc
test/boost/cql_query_test.cc
test/boost/restrictions_test.cc

Currently we support queries like:
```cql
SELECT * FROM ks.tab WHERE p IN (1, 2, null, 4);
```
Nothing can be equal to null so this is equivalent to:
```cql
SELECT * FROM ks.tab WHERE p IN (1, 2, 4);
```
Cassandra doesn't support it at all.
```cql
> SELECT * FROM ks.tab WHERE p IN (1, 2, null, 4)
Error: DbError(Invalid, "Invalid null value in condition for column p")
> SELECT * FROM ks.tab WHERE p IN (1, 2, ?, 4) # ? is NULL
Error: DbError(Invalid, "Invalid null value in condition for column p")
> SELECT * FROM ks.tab WHERE p IN ? # ? is (1, 2, null, 4)
Error: DbError(Invalid, "Invalid null value in condition for column p")
```
It makes little sense to send a null inside list of IN values and supporting it is a bit cumbersome.
Supporting it causes trouble because internally the values are …

cql: Remove support for null inside lists of IN values

---

conf/scylla.yaml
db/config.cc
db/config.hh
sstables/mx/writer.cc
sstables/sstables.cc
sstables/sstables.hh
sstables/sstables_manager.cc
sstables/stats.hh
test/boost/config_test.cc
test/boost/sstable_datafile_test.cc
test/boost/sstable_mutation_test.cc

Add column_index_auto_scale_threshold_in_kb to the configuration (defaults to 10MB).
When the promoted index (serialized) size gets to this
threshold, it's halved by merging each two adjacent blocks
into one and doubling the desired_block_size.
Fixes #4217

auto-scale promoted index

---

raft/fsm.cc
raft/server.cc
test/raft/randomized_nemesis_test.cc

Introduce a new operation, `raft_read`, which calls `read_barrier`
on a server, reads the state of the server's state machine, and returns
that state.
Extend the generator in `basic_generator_test` to generate `raft_read`s.
Only do it if forwarding is enabled (although it may make sense to test
read barriers in non-forwarding scenario as well - we may think about it
and do it in a follow-up).
Check the consistency of the read results by comparing them with the model
and using the result to extend the model with any newly observed elements.
The patchset includes some fixes for correctness (#10578)
and liveness (handling aborts correctly).

raft: test `read_barrier`s in `randomized_nemesis_test`

---

compaction/compaction_manager.cc
compaction/compaction_manager.hh

First patch removes incorrect usage of rwlock which should be restricted to minor and major compaction tasks.
Second patch revives a semaphore, which was lost in 6737c880458c, as we want major to not wait on off-strategy completion before deciding whether or not it should proceed with execution. It wouldn't proceed with execution if user asked major to stop while waiting for a chance to run.
For master, we're going to rely on abortable variant of get_units() to allow major to be quickly aborted.
Fixes #10485.

Rework off strategy compaction locking for branch 5.0

---

alternator/error.hh
alternator/executor.cc
alternator/executor.hh
alternator/server.cc
alternator/ttl.cc
test/alternator/test_backup.py

This small series implements the DescribeTimeToLive and DescribeContinuousBackups operations in Alternator. Even if the corresponding features aren't implemented, it can help applications that we implement just the Describe operation that can say that this feature is in fact currently disabled.
Fixes  #10660

alternator: add Describe operations even if a feature is not supported

---

raft/raft.cc
raft/server.cc
raft/server.hh
raft/tracker.cc
raft/tracker.hh
test/raft/randomized_nemesis_test.cc

We modify the `reconfigure` and `modify_config` APIs to take a vector of
<server_id, bool> pairs (instead of just a vector of server_ids), where
the bool indicates whether the server is a voter in the modified config.
The `reconfiguration` operation would previously shuffle the set of
servers and split it into two parts: members and non-members. Now it
partitions it into three parts: voters, non-voters, and non-members.
The PR also includes fixes for some liveness problems stumbled upon
during testing.

raft: test non-voters in `randomized_nemesis_test`

---

db/cache_tracker.hh
mutation.cc
mutation.hh
mutation_cleaner.hh
mutation_compactor.hh
mutation_partition.cc
mutation_partition.hh
partition_version.cc
partition_version.hh
replica/memtable.cc
replica/table.cc
row_cache.cc
test/boost/flat_mutation_reader_test.cc
test/boost/memtable_test.cc
test/boost/mutation_reader_test.cc
test/boost/mvcc_test.cc
test/boost/row_cache_test.cc
test/lib/flat_mutation_reader_assertions.hh
test/lib/mutation_assertions.hh

When memtable receives a tombstone it can happen under some workloads
that it covers data which is still in the memtable. Some workloads may
insert and delete data within a short time frame. We could reduce the
rate of memtable flushes if we eagerly drop tombstoned data.
One workload which benefits is the raft log. It stores a row for each
uncommitted raft entry. When entries are committed they are
deleted. So the live set is expected to be short under normal
conditions.
Fixes #652.

memtable, cache: Eagerly compact data with tombstones

---

multishard_mutation_query.cc

This series converts try/catch blocks in coroutines for multishard_mutation_query to use coroutine::as_future to get and handle errors, reducing exception handling costs (that are expected on timeouts).
It was previously sent to the mailing list.
This version (v2) is just a rebase of the v1 series,
with one patch dropped as it was already merged to master independentally.

multishard_mutation_query: use coroutine::as_future

---

repair/row_level.cc

Found with scylla --blocked-reactor-notify-ms 1 during replace operation with rbno turned on. 
The stalls showed without this patch were gone after this path set.

Fix stalls during repair with rbno

---

cql3/attributes.cc
cql3/column_condition.cc
cql3/expr/expression.cc
cql3/expr/expression.hh
cql3/expr/prepare_expr.cc
cql3/expr/to_restriction.cc
cql3/operation.cc
cql3/selection/selectable.cc
cql3/selection/selectable.hh
cql3/statements/create_aggregate_statement.cc
cql3/statements/select_statement.cc
cql3/statements/update_statement.cc

Currently, preparing the left-hand-side of a binary operator and the
right-hand-side use different code paths. The left-hand-side derives
the type of the expression from the expression itself, while the
right-hand-side imposes the type on the expression (allowing the types
of bind variables to be inferred).
This series unifies the two, by making the imposed type (the "receiver")
optional, and by allowing prepare to fail gracefully if we were not able
to infer the type. The old prepare_binop_lhs() is removed and replaced
with prepare_expression, already used for the right hand side.
There is one step remaining, and that is to replace prepare_binary_operator
with prepare_expression, but that is more involved and is left for a follow-up.

cql3: expr: unify left-hand-side and right-hand-side of binary_operator prepares

---

test/cql-pytest/conftest.py
test/cql-pytest/test_filtering.py
test/cql-pytest/test_secondary_index.py

Older versions of the Python Cassandra driver had a bug where a single empty
page aborts a scan.
The test test_secondary_index.py::test_filter_and_limit uses filtering and deliberately 
tiny pages, so it turns out that some of them are  empty, so the test breaks on buggy
versions of the driver, which cause the test to fail when run by developers who happen
to have old versions of the driver.
So in this small series we skip this test when running on a buggy version of the driver.
Fixes #10763

test/cql-pytest: skip another test on older, buggy, drivers

---

cql3/expr/expression.cc
cql3/expr/expression.hh
cql3/expr/prepare_expr.cc
cql3/selection/selection.cc
cql3/values.hh
db/view/view.cc

The left-hand-side of a binary_operator is currently evaluated via 
a get_value() function that receives the row values. On the other hand,
the right hand side is evaluated via evaluate(), which receives query_options
in order to resolve bind variables.
This series unifies the two paths into evaluate(), and standardizes the different
inputs into a new evaluation_inputs struct. The old hacks column_value_eval_bag
and column_maybe_subscripted are removed.

cql3: expr: unify binary operator left-hand-side and right-hand-side evaluation

---

alternator/executor.cc
test/alternator/test_gsi.py
test/alternator/test_lsi.py
test/alternator/test_tag.py

This series includes three small fixes (and of course, tests) for various edge cases of GSI and LSI handling in Alternator:
1. We add the IndexArn that were missing in DescribeTable for indexes (GSI and LSI)
2. We forbid the same name to be used for both GSI and LSI (allowing it was a bug, not a feature)
3. We improve the error handling when trying to tag a GSI or LSI, which is not currently allowed (it's also not allowed in DynamoDB).

Three small fixes to Alternator's handling of GSIs and LSIs

---

replica/database.hh
replica/table.cc
test/boost/memtable_test.cc
test/lib/mutation_source_test.cc
test/lib/mutation_source_test.hh

If we reach a situation where flush rate exceeds compaction rate, we may
end up with arbitrarily large number of sstables on disk. If a read is
executed in such case, the amount of memory required is proportional to
the number of sstables for the given shard, which in extreme cases can
lead to OOM.
In the wild, this was observed in 2 scenarios:
- A node with >10 shards creates a keyspace with thousands of tables,
drops the keyspace and shuts down before compaction finishes. Dropping
keyspace drops tables, and each dropped table is smp::count writes to
system.local table with flush after write, which creates tens of
thousands of sstables. Bootstrap read from system.local will run OOM.
- A failure to agree on table schema (due to a code bug) between nodes
during repair resulted in excessive …

Block flush until compaction finishes if sstables accumulate

---

sstables/sstable_directory.cc
test/boost/sstable_directory_test.cc

`sstable_directory::process_sstables_dir` may hit an exception when calling `handle_component`.
In this case we currently destroy the `sstable_dir_lister` variable without closing the `directory_lister` first -
leading to terminate in `~directory_lister` as seen in #10697.
This mini-series handles this exception and always closes the `directory_lister`.
Add unit test to reproduce this issue.
Fixes #10697

process_sstables_dir: close directory_lister on error

---

service/storage_service.cc

This patch set 
- adds log before and after batch log replay
- removes a duplicated call to trigger batch log replay
- removes obsoletes log

Batchlog replay for decommission fix and cleanup

---

db/view/view_update_generator.cc
replica/database.hh
replica/distributed_loader.cc
replica/table.cc
sstables/sstable_set.cc
sstables/sstables.cc
sstables/sstables.hh

This series decouples the staging sstables from the table's sstable set.
The current behavior keeps the sstables in the staging directory until view building is done. They are readable as any other sstable, but fenced off from compaction, so they don't go away in the meanwhile.
Currently, when views are built, the sstables are moved into the main table directory where they will then be compacted normally.
The problem with this design is that the staging sstables are never compacted, in particular they won't get cleaned up or scrubbed.
The cleanup scenario open a backdoor for data resurrection when the staging sstables are moved after view building while possibly containing stale partitions (#9559) which will not be cleaned up until next time cleanup compaction is performed.
With this …

Compact staging sstables

---

api/storage_service.cc
replica/database.hh
replica/distributed_loader.cc
sstables/generation_type.hh
sstables/sstable_directory.cc
sstables/sstable_directory.hh
sstables/sstable_set.cc
sstables/sstables.cc
sstables/sstables.hh
test/boost/database_test.cc
test/boost/mutation_reader_test.cc
test/boost/sstable_3_x_test.cc
test/boost/sstable_compaction_test.cc
test/boost/sstable_datafile_test.cc
test/boost/sstable_directory_test.cc
test/boost/sstable_move_test.cc
test/boost/sstable_resharding_test.cc
test/boost/sstable_test.cc
test/boost/sstable_test.hh
test/lib/sstable_test_env.hh
test/lib/sstable_utils.cc
test/lib/sstable_utils.hh
utils/extremum_tracking.hh

- Use `sstables::generation_type` in more places
- Enforce conceptual separation of `sstables::generation_type` and `int64_t`
- Fix `extremum_tracker` so that `sstables::generation_type` can be non-default-constructible
Fixes #10796.

sstables: generation_type tidy-up

---

test/perf/perf.cc
test/perf/perf.hh
test/perf/perf_commitlog.cc
test/perf/perf_simple_query.cc

This PR adds necessary modifications to perf_simple_query so that it can be used to test performance of the timeout handling path. With an appropriate combination of flags, it is possible to consistently trigger timeouts on every operation.
The following flags are added:
- `--stop-on-error` - if true (which is the default), the test stops after encountering the first exception and reports it; otherwise it causes errors to be counted and reported at the end.
- `--timeout <x>` - allows to use `USE TIMEOUT <x>` in the benchmark query/statement.
- `--bypass-cache` - uses `BYPASS CACHE` in the benchmark query (relevant only to reads).
Examples:
```
./build/release/test/perf/perf_simple_query --smp=1 --operations-per-shard=1000000 --write
131023.65 tps ( 56.2 allocs/op,  13.2 tasks/op,   49784 …
```

test: perf: allow testing timeouts in perf_simple_query

---

cql3/statements/schema_altering_statement.cc
idl-compiler.py
idl/group0.idl.hh
main.cc
message/messaging_service.cc
message/messaging_service.hh
message/rpc_protocol_impl.hh
service/migration_manager.cc
service/raft/messaging.hh
service/raft/raft_group0.cc
service/raft/raft_group0.hh
service/raft/raft_group_registry.cc
service/raft/raft_group_registry.hh
service/raft/raft_rpc.cc
service/raft/raft_rpc.hh
service/raft/raft_sys_table_storage.cc
service/storage_service.cc
service/storage_service.hh
test/boost/cdc_test.cc
test/boost/memtable_test.cc
test/lib/cql_test_env.cc

The commits here were extracted from PR https://github.com/scylladb/scylla/pull/10835 which implements upgrade procedure for Raft group 0.
They are mostly refactors which don't affect the behavior of the system, except one: the commit https://github.com/scylladb/scylla/commit/4d439a16b31ce4cddd0052320c9c5893dec38390 causes all schema changes to be bounced to shard 0. Previously, they would only be bounced when the local Raft feature was enabled. I do that because:
1. eventually, we want this to be the default behavior
2. in the upgrade PR I remove the `is_raft_enabled()` function - the function was basically created with the mindset "Raft is either enabled or not" - which was right when we didn't support upgrade, but will be incorrect when we introduce intermediate states (when we upgrade …

A bunch of refactors related to Raft group 0

---

test/cql-pytest/conftest.py
test/cql-pytest/run-cassandra
test/cql-pytest/run.py
test/cql-pytest/test_permissions.py
test/cql-pytest/util.py
test/pylib/scylla_server.py

This series adds the infrastructure needed for testing user permissions, like the ability to create temporary roles and CQL sessions which log in as different users, and a few initial test cases for granting and revoking permissions.

Add test cases for granting and revoking data permissions

---

db/view/view.cc
multishard_mutation_query.cc
mutation_compactor.hh
mutation_partition.cc
querier.cc
querier.hh
readers/mutation_readers.cc
replica/database.cc
replica/database.hh
replica/table.cc
test/boost/database_test.cc
test/boost/mutation_query_test.cc
test/boost/mutation_test.cc
test/boost/querier_cache_test.cc
test/perf/perf_row_cache_reads.cc

Said parameter is a convenience so downstream consumers of the
mutation compactors don't have to check the `bool is_live` already
passed to them. This convenience however causes a template parameter and
additional logic for the compactor. As the most prominent of these
consumers (the query result builder) will soon have to switch to
`emit_only_live_rows::no` for other reasons anyway (it will want to count
tombstones), we take the opportunity to switch everybody to ::no. This
can be done with very little additional complexity to these consumers --
basically an additional if or two. With everybody using the `::no` variant
of the compactor, we can remove this template parameter and the logic
associated with it altogether.

mutation_compactor: remove emit only live rows parameter

---

compaction/compaction_manager.cc
test/boost/sstable_compaction_test.cc

If the compaction_descriptor returned by `time_window_compaction_strategy::get_sstables_for_compaction`
is marked with `has_only_fully_expired::yes` it should always be compacted
since `time_window_compaction_strategy::get_sstables_for_compaction` is not idempotent.
It sets `_last_expired_check` and if compaction is postponed and retried before
`expired_sstable_check_frequency` has passed, it will not look for those fully-expired
sstables again. Plus, compacting them is the cheapest possible as it does not require
reading anything, just deleting the input sstables, so there's no reason not postpone it.
Also, extend `max_ongoing_compaction_test` to test serialization of compaction jobs with the same weight.
Fixes #10989

Always register fully expired sstables for compaction

---

idl/group0.idl.hh
idl/raft.idl.hh
idl/raft_storage.idl.hh
raft/fsm.cc
raft/fsm.hh
raft/raft.cc
raft/raft.hh
raft/server.cc
raft/server.hh
raft/tracker.cc
raft/tracker.hh
serializer_impl.hh
service/raft/raft_address_map.hh
service/raft/raft_group0.cc
service/raft/raft_group_registry.cc
service/raft/raft_rpc.cc
service/raft/raft_rpc.hh
service/raft/raft_sys_table_storage.cc
test/raft/discovery_test.cc
test/raft/etcd_test.cc
test/raft/fsm_test.cc
test/raft/helpers.cc
test/raft/helpers.hh
test/raft/raft_sys_table_storage_test.cc
test/raft/randomized_nemesis_test.cc
test/raft/replication.cc
test/raft/replication.hh
test/raft/replication_test.cc
to_string.hh

Whether a server can vote in a Raft configuration is not part of the
address. `server_address` was used in many context where `can_vote` is
irrelevant.
Split the struct: `server_address` now contains only `id` and
`server_info` as it did before `can_vote` was introduced. Instead we
have a `config_member` struct that contains a `server_address` and the
`can_vote` field.
Also remove an "unsafe" constructor from `server_address` where `id` was
provided but `server_info` was not. The constructor was used for tests
where `server_info` is irrelevant, but it's important not to forget
about the info in production code. Replace the constructor with helper
functions which specify in comments that they are supposed to be used in
tests or in contexts where `info` doesn't matter (e.g. when checking …

raft: split `can_vote` field form `server_address` to separate struct

---

replica/table.cc
test/boost/database_test.cc

Currently, all the mutations this test generates are applied on shard 0.
In rare cases, this may lead to the following crash, when the flushed
sstable doesn't contain any key that belongs to the current shard,
as seen in https://jenkins.scylladb.com/job/releng/job/Scylla-CI/1390/artifact/testlog/x86_64/dev/database_test.test_truncate_without_snapshot_during_writes.114.log
```
WARN  2022-07-17 17:41:36,630 [shard 0] sstable - create_sharding_metadata: range=[{-468459073612751032, pk{00046b657930}}, {-468459073612751032, pk{00046b657930}}] has no intersection with shard=0 first_key={key: pk{00046b657930}, token:-468459073612751032} last_key={key: pk{00046b657930}, token:-468459073612751032} ranges_single_shard=[] ranges_all_shards={{1, {[{-468459073612751032, pk{00046b657930}}, …
```

database_test: test_truncate_without_snapshot_during_writes: apply mutation on the correct shard

---

docs/using-scylla/alternator/index.rst
docs/using-scylla/features-open-source.rst

The Scylla Alternator documentation is now part of the Scylla user documentation (previously it was dev documentation).
This PR updates the links to the Alternator documentation.

doc: fix the links to Alternator

---

service/raft/discovery.hh
service/raft/raft_group0.cc
service/raft/raft_group0.hh
service/storage_service.cc

A series of refactors to the `raft_group0` service.
Read the commits in topological order for best experience.
This PR is more or less equivalent to the second-to-last commit of PR https://github.com/scylladb/scylla/pull/10835, I split it so we could have an easier time reviewing and pushing it through.

Refactor group 0 operations (joining, leaving, removing).

---

service/forward_service.cc

This series refactors the code to get rid of unnecessary
allocations by extracing a helper requires_thread() function,
as well as by removing std::optional usage in forward_result,
now that it's possible to merge empty results with each other,
both ways (#11064).

forward_service: reduce allocations in forward_service

---

cql3/expr/expression.cc
test/cql-pytest/test_filtering.py
test/cql-pytest/test_null.py

This is a backport of https://github.com/scylladb/scylla/pull/10420 to branch 5.0.
Branch 5.0 had somewhat different code in this expression area, so the backport was not automatically, but nevertheless was fairly straightforward - just copy the exact same checking code to its right place, and keep the exact same tests to see we indeed fixed the bug.
Refs #10535.
The original cover letter from https://github.com/scylladb/scylla/pull/10420:
In the filtering expression "WHERE m[?] = 2", our implementation was buggy when either the map, or the subscript, was NULL (and also when the latter was an UNSET_VALUE). Our code ended up dereferencing null objects, yielding bizarre errors when we were lucky, or crashes when we were less lucky - see examples of both in issues …

Backport: Fix map subscript crashes when map or subscript is null

---

compaction/compaction_manager.cc
compaction/compaction_manager.hh
compaction/leveled_manifest.hh
compaction/time_window_compaction_strategy.cc
replica/table.cc
test/boost/memtable_test.cc
test/lib/mutation_source_test.cc
test/lib/mutation_source_test.hh

Called from try_flush_memtable_to_sstable,
maybe_wait_for_sstable_count_reduction will wait for
compaction to catch up with memtable flush if there
the bucket to compact is inflated, having too many
sstables.  In that case we don't want to add fuel
to the fire by creating yet another sstable.
Fixes #4116

Memtable flush: wait for sstable count reduction if needed

---

multishard_mutation_query.cc
mutation_compactor.hh
mutation_partition.cc
querier.hh
test/cql-pytest/test_scan.py

When stopping the read, the multishard reader will dismantle the 
compaction state, pushing back (unpopping) the currently processed
partition's header to its originating reader. This ensures that if the
reader stops in the middle of a partition, on the next page the
partition-header is re-emitted as the compactor (and everything
downstream from it) expects.
It can happen however that there is nothing more for the current
partition in the reader and the next fragment is another partition.
Since we only push back the partition header (without a partition-end)
this can result in two partitions being emitted without being separated
by a partition end.
We could just add the missing partition-end when needed but it is
pointless, if the partition has no more data, just drop the header, we
won't …

multishard_mutation_query: don't unpop partition header of spent partition

---

dirty_memory_manager.cc
dirty_memory_manager.hh
test/boost/dirty_memory_manager_test.cc
test/boost/logalloc_test.cc
utils/logalloc.cc

Currently logalloc::region is relying on boost binomial_heap handle to properly move listeners registration when the region (when derived from dirty_memory_manager_logalloc::size_tracked_region) is moved, like boost::intrusive link hooks do -
hence https://github.com/scylladb/scylla/blob/81e20ceaab8f54938aa77842ee5c9d9e62639432/dirty_memory_manager.cc#L89-L90 does nothing.
Unfortunately, this doesn't work as expected.
This series adds a unit test that verifies the move semantics
and a fix to size_tracked_region and region_group code to make it pass.
Also "logalloc: region: get_impl might be called on disengaged _impl when moved"
fixes a couple corner cases where the shared _impl could be dereferenced when disengaged, and
the change also adds a unit test for that too.

logalloc: region: properly track listeners when moved

---

api/storage_service.cc
backlog_controller.hh
compaction/compaction.cc
compaction/compaction_descriptor.hh
compaction/compaction_manager.cc
compaction/compaction_manager.hh
main.cc
replica/database.cc
replica/database.hh
scylla-gdb.py
test/boost/database_test.cc
test/boost/sstable_compaction_test.cc
test/lib/cql_test_env.cc
test/rest_api/test_storage_service.py

Start compaction_manager as a sharded service
and pass a reference to it to the database rather
than having the database construct its own compaction_manager.
This is part of the wider scope effort to decouple compaction from replica database and table.

Decouple compaction manager from database

---

locator/token_metadata.cc
locator/token_metadata.hh

token_metadata: impl: keep the set of normal token owners as a member
We don't need to recalculate the unique set of normal token
everytime we change `_token_to_endpoint_map`.
Similarly, this doesn't have to be done in `get_all_endpoints`.
Instead we can maintain it inexpensively in
`remove_endpoint`, and let `count_normal_token_owners`
just return its size and `get_all_endpoints` just return
the saved set.
Closes #11128
Fixes #11146

token_metadata: keep the set of normal token owners as a member

---

partition_snapshot_row_cursor.hh
partition_version_list.hh
row_cache.cc

When the last non-dummy row is evicted from a partition, the partition
entry is evicted as well. The existing logic in on_evicted() leaves
the last dummy row in the partition version before evicting the
partition entry. This row may still be attached to the LRU. Eviction
of partition entry goes through mutation_cleaner::clear_gently(). If
this is preempted, the destruction may proceed in the background. If
evicition happens on the remaining row in that entry before it's
destroyed, the code will hit undefined behavior. on_evicted() calls
partition_version::is_referenced_from_entry(), which is unspecified
when the version is enqueued in the mutation_cleaner. It returns
incorrect value for the last item remaining in the LRU (middle entires evict fine).
In that case, eviction will try to …

Fix undefined behavior during eviction

---

test/conftest.py
test/pylib/random_tables.py
test/pylib/scylla_server.py
test/topology/conftest.py
test/topology/pytest.ini

These are the first commits out of #10815 and is itself based on #11193 .
It starts by moving pytest logic out of the common `test/conftest.py` and into `test/topology/conftest.py`, including removing the async support as it's not used anywhere else.
There's a fix of a bug of leaving tables in `RandomTables.tables` after dropping all of them.
Keyspace creation is moved out of `conftest.py` into `RandomTables` as it makes more sense and this way topology tests avoid all the workarounds for old version (topology needs ScyllaDB 5+ for Raft, anyway).
And a minor fix.

Raft test topology part 1

---

api/storage_service.cc
dht/boot_strapper.cc
dht/range_streamer.cc
dht/range_streamer.hh
locator/abstract_replication_strategy.cc
locator/abstract_replication_strategy.hh
locator/everywhere_replication_strategy.cc
locator/everywhere_replication_strategy.hh
locator/local_strategy.cc
locator/local_strategy.hh
locator/network_topology_strategy.cc
locator/network_topology_strategy.hh
locator/simple_strategy.cc
locator/simple_strategy.hh
locator/token_metadata.cc
repair/repair.cc
replica/database.cc
replica/database.hh
service/storage_service.cc
service/storage_service.hh
test/boost/network_topology_strategy_test.cc
utils/sequenced_set.hh

This series converts the synchronous `effective_replication_map::get_range_addresses` to async
by calling the replication strategy async entry point with the same name, as its callers are already async
or can be made so easily.
To allow it to yield and work on a coherent view of the token_metadata / topology / replication_map,
let the callers of this patch hold a effective_replication_map per keyspace and pass it down
to the (now asynchronous) functions that use it (making affected storage_service methods static where possible
if they no longer depend on the storage_service instance).
Also, the repeated calls to everywhere_replication_strategy::calculate_natural_endpoints
are optimized in this series by introducing a virtual abstract_replication_strategy::has_static_natural_endpoints …

Make get_range_addresses async and hold effective_replication_map_ptr around it

---

partition_snapshot_row_cursor.hh
position_in_partition.hh
test/boost/mvcc_test.cc
test/boost/row_cache_test.cc

Scenario:
cache = [
row(pos=2, continuous=false),
row(pos=after(2), dummy=true)
]
Scanning read starts, starts populating [-inf, before(2)] from sstables.
row(pos=2) is evicted.
cache = [
row(pos=after(2), dummy=true)
]
Scanning read finishes reading from sstables.
Refreshes cache cursor via
partition_snapshot_row_cursor::maybe_refresh(), which calls
partition_snapshot_row_cursor::advance_to() because iterators are
invalidated. This advances the cursor to
after(2). no_clustering_row_between(2, after(2)) returns true, so
advance_to() returns true, and maybe_refresh() returns true. This is
interpreted by the cache reader as "the cursor has not moved forward",
so it marks the range as complete, without emitting the row with
pos=2. Also, it marks row(pos=after(2)) as continuous, so later …

row_cache: Fix missing row if upper bound of population range is evicted and has adjacent dummy

---

docs/operating-scylla/procedures/tips/best-practices-scylla-on-docker.rst

Fix https://github.com/scylladb/scylla-doc-issues/issues/842
This PR changes the default for the `overprovisioned` option from `disabled` to `enabled`, according to https://github.com/scylladb/scylla-doc-issues/issues/842.
In addition, I've used this opportunity to replace "Scylla" with "ScyllaDB" on the updated page.

doc: change the default for the overprovisioned option

---

docs/architecture/architecture-fault-tolerance.rst

Fix https://github.com/scylladb/scylla-doc-issues/issues/438
In addition, I've replaced "Scylla" with "ScyllaDB" on that page.

doc: fix the typo on the Fault Tolerance page

---

db/system_keyspace.cc

Previously, the `system.local`'s `rpc_address` column kept local node's
`rpc_address` from the scylla.yaml configuration. Although it sounds
like it makes sense, there are a few reasons to change it to the value
of scylla.yaml's `broadcast_rpc_address`:
- The `broadcast_rpc_address` is the address that the drivers are
supposed to connect to. `rpc_address` is the address that the node
binds to - it can be set for example to 0.0.0.0 so that Scylla listens
on all addresses, however this gives no useful information to the
driver.
- The `system.peers` table also has the `rpc_address` column and it
already keeps other nodes' `broadcast_rpc_address`es.
- Cassandra is going to do the same change in the upcoming version 4.1.
Fixes: #11201

db/system_keyspace: in system.local, use broadcast_rpc_address in rpc_address column

---

db/commitlog/commitlog.cc
db/commitlog/commitlog.hh
db/hints/manager.cc
main.cc

Fixes #11184
Fixes #11237
In prev (broken) fix for https://github.com/scylladb/scylladb/issues/11184 we added the footprint for left-over
files (replay candidates) to disk footprint on commitlog init.
This effectively prevents us from creating segments iff we have tight limits. Since we nowadays do quite a bit of inserts _before_ commitlog replay (system.local, but...) we can end up in a situation where we deadlock start because we cannot get to the actual replay that will eventually free things.
Another, not thought through, consequence is that we add a single footprint to _all_ commitlog shard instances - even though only shard 0 will get to actually replay + delete (i.e. drop footprint).
So shards 1-X would all be either locked out or performance degraded.
Simplest fix is to add the …

commitlog: Revert/modify fac2bc4 - do footprint add in delete

---

querier.cc
querier.hh
reader_concurrency_semaphore.cc
reader_concurrency_semaphore.hh
replica/database.cc
test/boost/querier_cache_test.cc
test/boost/reader_concurrency_semaphore_test.cc

Currently, when detaching the table from the database, we force-evict all queriers for said table. This series broadens the scope of this force-evict to include all inactive reads registered at the semaphore. This ensures that any regular inactive read "forgotten" for any reason in the semaphore, will not end up in said readers accessing a dangling table reference when destroyed later.
Fixes: https://github.com/scylladb/scylladb/issues/11264

database: evict all inactive reads for table when detaching table

---

test.py
test/pylib/manager_client.py
test/pylib/scylla_cluster.py
test/topology/conftest.py
test/topology/test_topology.py

Test schema changes when there was an underlying topology change.
- per test case checks of cluster health and cycling
- helper class to do cluster manager API requests
- tests can perform topology changes: stop/start/restart servers
- modified clusters are marked dirty and discarded after the test case
- cql connection is updated per topology change and per cluster change

Raft test topology part 3

---

column_computation.hh
cql3/Cql.g
cql3/expr/expression.cc
cql3/restrictions/statement_restrictions.cc
cql3/statements/create_index_statement.cc
cql3/statements/create_index_statement.hh
cql3/statements/index_target.cc
cql3/statements/index_target.hh
cql3/statements/select_statement.cc
db/view/view.cc
db/view/view.hh
docs/dev/secondary_index.md
gms/feature_service.hh
index/secondary_index.cc
index/secondary_index.hh
index/secondary_index_manager.cc
index/secondary_index_manager.hh
schema.cc
schema.hh
test/boost/secondary_index_test.cc
test/cql-pytest/cassandra_tests/validation/entities/secondary_index_on_map_entries_test.py
test/cql-pytest/cassandra_tests/validation/entities/secondary_index_test.py
test/cql-pytest/cassandra_tests/validation/operations/select_single_column_relation_test.py
test/cql-pytest/cassandra_tests/validation/operations/select_test.py
test/cql-pytest/test_materialized_view.py
test/cql-pytest/test_secondary_index.py
types/tuple.hh
view_info.hh

This pull request introduces global secondary-indexing for non-frozen collections.
The intent is to enable such queries:
```
CREATE TABLE test(int id, somemap map<int, int>, somelist<int>, someset<int>, PRIMARY KEY(id));
CREATE INDEX ON test(keys(somemap));
CREATE INDEX ON test(values(somemap));
CREATE INDEX ON test(entries(somemap));
CREATE INDEX ON test(values(somelist));
CREATE INDEX ON test(values(someset));
-- index on test(c) is the same as index on (values(c))
CREATE INDEX IF NOT EXISTS ON test(somelist);    
CREATE INDEX IF NOT EXISTS ON test(someset);
CREATE INDEX IF NOT EXISTS ON test(somemap);
SELECT * FROM test WHERE someset CONTAINS 7;
SELECT * FROM test WHERE somelist CONTAINS 7;
SELECT * FROM test WHERE somemap CONTAINS KEY 7;
SELECT * FROM test WHERE somemap CONTAINS 7; …
```

Secondary index of collection columns

---

test.py
test/conftest.py
test/pylib/manager_client.py
test/pylib/scylla_cluster.py
test/topology/conftest.py

- Remove `ScyllaCluster.__getitem__()`  (pending request by @kbr- in a previous pull request), for this remove all direct access to servers from caller code
- Increase Python driver timeouts (req by @nyh)
- Improve `ManagerClient` API requests: use `http+unix://<sockname>/<resource>` instead of `http://localhost/<resource>` and callers of the helper method only pass the resource
- Improve lint and type hints

Raft test topology II part 1

---

idl/streaming.idl.hh
message/messaging_service.cc
message/messaging_service.hh
sstables_loader.cc
streaming/stream_coordinator.hh
streaming/stream_event.hh
streaming/stream_fwd.hh
streaming/stream_manager.cc
streaming/stream_manager.hh
streaming/stream_plan.hh
streaming/stream_receive_task.hh
streaming/stream_result_future.cc
streaming/stream_result_future.hh
streaming/stream_session.cc
streaming/stream_session.hh
streaming/stream_state.hh
streaming/stream_transfer_task.cc
streaming/stream_transfer_task.hh

This series turns plan_id from a generic UUID into a strong type so it can't be used interchangeably with other uuid's.
While at it, streaming/stream_fwd.hh was added for forward declarations and the definition of plan_id.
Also, `stream_manager::update_progress` parameter name was renamed to plan_id to represent its assumed content, before changing its type to `streaming::plan_id`.

Streaming: define plan_id as a strong tagged_uuid type

---

dirty_memory_manager.cc
partition_snapshot_reader.hh
replica/database.cc
scylla-gdb.py
test/boost/logalloc_test.cc
test/perf/perf_row_cache_update.cc
utils/logalloc.cc
utils/logalloc.hh

Currently the state of LSA is scattered across a handful of global variables. This series consolidates all these into a single one: the shard tracker. Beyond reducing the number of globals (the less globals, the better) this paves the way for a planned de-globalization of the shard tracker itself.
There is one separate global left, the static migrators registry. This is left as-is for now.

utils/logalloc: consolidate lsa state in shard tracker

---

raft/server.cc
test/raft/randomized_nemesis_test.cc

When `io_fiber` fetched a batch with a configuration that does not
contain this node, it would send the entries committed in this batch to
`applier_fiber` and proceed by any remaining entry dropping waiters (if
the node was no longer a leader).
If there were waiters for entries committed in this batch, it could
either happen that `applier_fiber` received and processed those entries
first, notifying the waiters that the entries were committed and/or
applied, or it could happen that `io_fiber` reaches the dropping waiters
code first, causing the waiters to be resolved with
`commit_status_unknown`.
The second scenario is undesirable. For example, when a follower tries
to remove the current leader from the configuration using
`modify_config`, if the second scenario happens, the follower will …

raft: server: drop waiters in `applier_fiber` instead of `io_fiber`

---

replica/distributed_loader.cc
replica/distributed_loader.hh

Fixes #11349
In 7396de7 (and refactorings before it) the set of prioritized keyspaces (and processing thereof)
was removed, due to apparent non-usage (which is true for open-source version).
This functionality is however required for certain features of the enterprise version (ear).
As such is needs to be restored and reenabled. This patch set does so, adapted
to the recent version of this file.

distributed_loader: Restore separate processing of keyspace init prio/normal

---

scylla-gdb.py
test/scylla-gdb/test_misc.py

Said command is broken since 4.6, as the type of `reader_concurrency_semaphore::_permit_list` was changed without an accompanying update to this command. This series updates said command and adds it to the list of tested commands so we notice if it breaks in the future.

scylla-gdb.py: bring scylla reads-stats up-to-date

---

dist/common/scripts/scylla_raid_setup

Just like https://github.com/scylladb/scylladb/commit/4a8ed4cc6f285a834f42a122283d41c4571a7708, we also need to wait for udev event completion to
create /dev/disk/by-uuid/$UUID for newly formatted disk, to mount the
disk just after formatting.
Also added code to check make sure uuid and uuid based device path are valid.
Fixes #11359

scylla_raid_setup: prevent mount failed for /var/lib/scylla

---

docs/operating-scylla/admin-tools/scylla-sstable.rst
docs/operating-scylla/admin-tools/sstabledump.rst

This is a very important aspect of the tool that was completely missing from the document before. Also add a comparison with SStableDump.
Fixes: https://github.com/scylladb/scylladb/issues/11363

Docs: document how scylla-sstable obtains its schema

---

configure.py
raft/raft.hh
raft/server.cc
raft/server.hh
service/raft/raft_group0.cc
service/raft/raft_group0.hh
service/raft/raft_group_registry.cc
service/raft/raft_group_registry.hh
test/boost/group0_test.cc
test/lib/cql_test_env.cc
test/lib/cql_test_env.hh
test/raft/raft_server_test.cc
test/raft/replication.hh

Halted background fibers render raft server
effectively unusable, so report this
explicitly to the clients.
Fix: #11352

raft server, abort on background errors

---

compaction/compaction.cc
compaction/compaction_descriptor.hh
replica/database.cc
sstables/mx/writer.cc
sstables/sstable_set.cc
sstables/sstables.cc
sstables/sstables.hh
sstables/sstables_manager.cc
sstables/sstables_manager.hh
test/boost/broken_sstable_test.cc
test/boost/sstable_3_x_test.cc
test/boost/sstable_compaction_test.cc
test/boost/sstable_datafile_test.cc
test/lib/sstable_test_env.hh
test/lib/sstable_utils.cc
tools/scylla-sstable.cc

Introduces support to split large partitions during compaction. Today, compaction can only split input data at partition boundary, so a large partition is stored in a single file. But that can cause many problems, like memory pressure (e.g.: https://github.com/scylladb/scylladb/issues/4217), and incremental compaction can also not fulfill its promise as the file storing the large partition can only be released once exhausted.
The first step was to add clustering range metadata for first and last partition keys (retrieved from promoted index), which is crucial to determine disjointness at clustering level, and also the order at which the disjoint files should be opened for incremental reading.
The second step was to extend sstable_run to look at clustering dimension, so a set of files …

Add support to split large partitions across SSTables

---

cdc/generation.cc
db/system_keyspace.cc
db/system_keyspace.hh
service/storage_service.cc

There's a bunch of helpers for CDC gen service in db/system_keyspace.cc. All are static and use global qctx to make queries. Fortunately, both callers -- storage_service and cdc_generation_service -- already have local system_keyspace references and can call the methods via it, thus reducing the global qctx usage.

Don't use qctx in CDC tables quering

---

configure.py
db/config.cc
main.cc
message/messaging_service.cc
message/messaging_service.hh
raft/raft.hh
raft/server.cc
raft/server.hh
service/raft/raft_group0.cc
service/raft/raft_group0.hh
service/raft/raft_group_registry.cc
service/raft/raft_group_registry.hh
test/boost/group0_test.cc
test/lib/cql_test_env.cc
test/lib/cql_test_env.hh
test/pylib/manager_client.py
test/pylib/pool.py
test/pylib/scylla_cluster.py
test/raft/raft_server_test.cc
test/raft/replication.hh
test/topology/conftest.py

- Raise on response not HTTP 200 for `.get_text()` helper
- Fix API paths
- Close and start a fresh driver when restarting a server and it's the only server in the cluster
- Fix stop/restart response as text instead of inspecting (errors are status 500 and raise exceptions)

Raft test topology fix request paths and API response handling

---

mutation_reader.cc
test/boost/mutation_reader_test.cc

This pull request backports 3 important fixes from https://github.com/scylladb/scylladb/commit/adc08d0ab9c6f2b98003d20a09b133a061e18a0b. Said 3 commits fixed important bugs in the v2 variant of the evitable reader, but were not backported because they were part of a large series doing v2 conversion in general. This means that 5.0 was left with a buggy evictable reader v2, which is used by repair. So far in the wild we've seen one bug manifest itself: the evictable reader getting stuck, spinning in a tight loop in `evictable_reader_v2::do_fill_buffer()`, in turn making repair being stuck too.
Fixes: #11223

[branch 5.0] Backport 3 fixes for the evictable reader v2

---

docs/cql/dml.rst
docs/cql/functions.rst
docs/kb/count-all-rows.rst

Fix https://github.com/scylladb/scylladb/issues/11373
- Updated the information on the "Counting all rows in a table is slow" page.
- Added COUNT to the list of selectors of the SELECT statement (somehow it was missing).
- Added the note to the description of the COUNT() function with a link to the KB page for troubleshooting if necessary. This will allow the users to easily find the KB page.

doc: update the "Counting all rows in a table is slow" page

---

docs/upgrade/_common/upgrade-guide-v4-rpm.rst
docs/upgrade/_common/upgrade-guide-v5-ubuntu-and-debian-p1.rst
docs/upgrade/_common/upgrade-guide-v5-ubuntu-and-debian-p2.rst
docs/upgrade/_common/upgrade-image-opensource.rst
docs/upgrade/upgrade-opensource/index.rst
docs/upgrade/upgrade-opensource/upgrade-guide-from-5.0-to-5.1/index.rst
docs/upgrade/upgrade-opensource/upgrade-guide-from-5.0-to-5.1/metric-update-5.0-to-5.1.rst
docs/upgrade/upgrade-opensource/upgrade-guide-from-5.0-to-5.1/upgrade-guide-from-5.0-to-5.1-debian.rst
docs/upgrade/upgrade-opensource/upgrade-guide-from-5.0-to-5.1/upgrade-guide-from-5.0-to-5.1-image.rst
docs/upgrade/upgrade-opensource/upgrade-guide-from-5.0-to-5.1/upgrade-guide-from-5.0-to-5.1-rpm.rst
docs/upgrade/upgrade-opensource/upgrade-guide-from-5.0-to-5.1/upgrade-guide-from-5.0-to-5.1-ubuntu.rst

Fix https://github.com/scylladb/scylladb/issues/11376
This PR adds the upgrade guide from version 5.0 to 5.1. It involves adding new files (5.0-to-5.1) and language/formatting improvements to the existing content (shared by several upgrade guides).

doc: add the upgrade guide from 5.0 to 5.1

---

compaction/compaction.cc
db/config.cc
keys.cc
querier.cc
querier.hh
replica/database.cc
replica/database.hh
replica/table.cc

Add cassandra functional - show warn/err when tombstone_warn_threshold/tombstone_failure_threshold reached on select, by partitions. Propagate raw query_string from coordinator to replicas.

Add cassandra functional - show warn/err when tombstone threshold reached.

---

locator/gossiping_property_file_snitch.cc
service/storage_service.cc
service/storage_service.hh

Snitch uses gossiper for several reasons, one of is to re-gossip the topology-related app states when property-file snitch config changes. This set cuts this link by moving re-gossiping into the existing storage_service::snitch_reconfigured() subscription. Since initial snitch state gossiping happens in storage service as well, this change is not unreasonable.

Cut one of snitch->gossiper links

---

locator/abstract_replication_strategy.cc
locator/token_metadata.cc

The goal is not to default initialize an object when its fields are about to be immediately overwritten by the consecutive code.

Avoid default initialization of token_metadata and topology when not needed

---

test.py
test/pylib/scylla_cluster.py
test/topology/suite.yaml
test/topology_raft_disabled/suite.yaml

Fix the type of `create_server`, rename `topology_for_class` to `get_cluster_factory`, simplify the suite definitions and parameters passed to `get_cluster_factory`

test.py: cleanups in topology test suites

---

cql3/Cql.g
cql3/statements/delete_statement.cc
cql3/statements/raw/modification_statement.hh
cql3/statements/raw/truncate_statement.hh
cql3/statements/select_statement.cc
cql3/statements/truncate_statement.cc
cql3/statements/truncate_statement.hh
docs/cql/cql-extensions.md
docs/cql/ddl.rst
service/storage_proxy.cc
service/storage_proxy.hh
test/cql-pytest/test_using_timeout.py

Extend the cql3 truncate statement to accept attributes,
similar to modification statements.
To achieve that we define cql3::statements::raw::truncate_statement
derived from raw::cf_statement, and implement its pure virtual
prepare() method to make a prepared truncate_statement.
The latter is no longer derived from raw::cf_statement,
and just stores a schema_ptr to get to the keyspace and column_family.
`test_truncate_using_timeout` cql-pytest was added to test
the new USING TIMEOUT feature.
Fixes #11408
Also, update docs/cql/ddl.rst truncate-statement section respectively.

Add support for TRUNCATE USING TIMEOUT

---

db/large_data_handler.cc
docs/troubleshooting/debugging-large-partition.rst
docs/troubleshooting/large-partition-table.rst
docs/troubleshooting/large-rows-large-cells-tables.rst

The series contains fixes for system.large_* log warning and respective documentation.
This prepares the way for adding a new system.large_collections table (See #11449):
Fixes #11620
Fixes #11621
Fixes #11622
the respective fixes should be backported to different release branches, based on the respective patches they depend on (mentioned in each issue).

Fix large data warning and docs

---

test.py
test/pylib/manager_client.py
test/pylib/scylla_cluster.py
test/topology/conftest.py

Include the unique test name (the unique name distinguishes between different test repeats) and the test case name where possible. Improve printing of clusters: include the cluster name and stopped servers. Fix some logging calls and add new ones.
Examples:
```
------ Starting test test_topology ------
```
became this:
```
------ Starting test test_topology.1::test_add_server_add_column ------
```
This:
```
INFO> Leasing Scylla cluster {127.191.142.1, 127.191.142.2, 127.191.142.3} for test test_add_server_add_column
```
became this:
```
INFO> Leasing Scylla cluster ScyllaCluster(name: 02cdd180-40d1-11ed-8803-3c2c30d32d96, running: {127.144.164.1, 127.144.164.2, 127.144.164.3}, stopped: {}) for test test_topology.1::test_add_server_add_column
```

Improve test.py logging

---

dirty_memory_manager.cc
dirty_memory_manager.hh
replica/database.cc
scylla-gdb.py
test/boost/dirty_memory_manager_test.cc

region_group evolved as a tree, each node of which contains some
regions (memtables). Each node has some constraints on memory, and
can start flushing and/or stop allocation into its memtables and those
below it when those constraints are violated.
Today, the tree has exactly two nodes, only one of which can hold memtables.
However, all the complexity of the tree remains.
This series applies some mechanical code transformations that remove
the tree structure and all the excess functionality, leaving a much simpler
structure behind.
Before:
- a tree of region_group objects
- each with two parameters: soft limit and hard limit
- but only two instances ever instantiated
After:
- a single region_group object
- with three parameters - two from the bottom instance, one from the top instance

dirty_memory_manager: simplify region_group

---

compaction/compaction_manager.cc
utils/exceptions.hh

The seastar defer_stop() helper is cool, but it forwards any exception from the .stop() towards the caller. In case the caller is main() the exception causes Scylla to abort(). This fires, for example, in compaction_manager::stop() when it steps on ENOSPC
Signed-off-by: Pavel Emelyanov <xemul@scylladb.com>

compaction_manager: Don't let ENOSPC throw out of ::stop() method

---

test/pylib/manager_client.py
test/pylib/random_tables.py
test/pylib/rest_client.py
test/pylib/scylla_cluster.py
test/topology/conftest.py
test/topology/test_random_tables.py
test/topology/test_topology.py
test/topology_raft_disabled/test_raft_upgrade.py

- Separate `aiohttp` client code
- Helper to access Scylla server REST API
- Use helper both in `ScyllaClusterManager` (test.py process) and `ManagerClient` (pytest process)
As `ScyllaCluster` manages through IPs some APIs require to specify both.

test.py topology Scylla REST API client

---

api/column_family.cc
db/config.cc
db/config.hh
dirty_memory_manager.cc
dirty_memory_manager.hh
docs/dev/debugging.md
replica/database.cc
scylla-gdb.py
test/boost/dirty_memory_manager_test.cc
test/boost/memtable_test.cc
test/manual/sstable_scan_footprint_test.cc
test/perf/perf_fast_forward.cc

This series undoes some recent damage to clarity, then
goes further by renaming terms around dirty_memory_manager
to be clearer. Documentation is added.

dirty_memory_manager: simplify, clarify, and document

---

main.cc
service/raft/raft_group0.cc
service/raft/raft_group0.hh
test/lib/cql_test_env.cc

The raft_group0 code needs system_keyspace and now it gets one from gossiper. This gossiper->system_keyspace dependency is in fact artificial, gossiper doesn't need system ks, it's there only to let raft and snitch call gossiper.get_system_keyspace().
This makes raft use system ks directly, snitch is patched by another branch

Make raft_group0 -> system_keyspace dependency explicit

---

cql3/expr/expression.cc
test/boost/restrictions_test.cc
test/cql-pytest/test_null.py

Currently doing `CONTAINS NULL` or `CONTAINS KEY NULL` on a collection evaluates to `true`.
This is a really weird behaviour. Collections can't contain `NULL`, even if they wanted to.
Any operation that has a NULL on either side should evaluate to `NULL`, which is interpreted as `false`.
In Cassandra trying to do `CONTAINS NULL` causes an error.
Fixes: #10359
The only problem is that this change is not backwards compatible. Some existing code might break.

cql3: Make CONTAINS NULL and CONTAINS KEY NULL return false

---

replica/compaction_group.hh
replica/database.hh
replica/table.cc
test/boost/sstable_compaction_test.cc
test/boost/sstable_resharding_test.cc
test/boost/sstable_test.hh
test/lib/sstable_utils.cc
test/lib/sstable_utils.hh
test/lib/test_services.cc
test/lib/test_services.hh

What's contained in this series:
- Refactored compaction tests (and utilities) for integration with multiple groups
- The idea is to write a new class of tests that will stress multiple groups, whereas the existing ones will still stress a single group.
- Fixed a problem when cloning compound sstable set (cannot be triggered today so I didn't open a GH issue)
- Many changes in replica::table for allowing integration with multiple groups
Next:
- Introduce for_each_compaction_group() for iterating over groups wherever needed.
- Use for_each_compaction_group() in replica::table operations spanning all groups (API, readers, etc).
- Decouple backlog tracker from compaction strategy, to allow for backlog isolation across groups
- Introduce static option for defining number of compaction groups …

Preliminary changes for multiple Compaction Groups

---

conf/scylla.yaml
db/config.cc
db/config.hh
db/large_data_handler.cc
db/large_data_handler.hh
db/system_keyspace.cc
docs/dev/sstable-scylla-format.md
docs/dev/system_keyspace.md
docs/troubleshooting/large-rows-large-cells-tables.rst
gms/feature_service.cc
gms/feature_service.hh
replica/database.cc
sstables/mx/writer.cc
sstables/types.hh
test/boost/sstable_3_x_test.cc
test/lib/simple_schema.hh
tools/scylla-sstable.cc
utils/updateable_value.hh

This series adds support for detecting collections that have too many items
and recording them in `system.large_cells`.
A configuration variable was added to db/config: `compaction_collection_items_count_warning_threshold` set by default to 10000.
Collections that have more items than this threshold will be warned about and will be recorded as a large cell in the `system.large_cells` table.  Documentation has been updated respectively.
A new column was added to system.large_cells: `collection_items`.
Similar to the `rows` column in system.large_partition, `collection_items` holds the number of items in a collection when the large cell is a collection, or 0 if it isn't.  Note that the collection may be recorded in system.large_cells either due to its size, like any other cell, and/or due …

Detect and record large collections

---

reader_concurrency_semaphore.cc
reader_concurrency_semaphore.hh
replica/database.cc
test/boost/reader_concurrency_semaphore_test.cc

Allowing to change the total or initial resources the semaphore has. After calling `set_resources()` the semaphore will look like as if it was created with the specified amount of resources when created.
Use the new method in `replica::database::revert_initial_system_read_concurrency_boost()` so it doesn't lead to strange semaphore diagnostics output. Currently the system semaphore has 90/100 count units when there are no reads against it, which has led to some confusion.
I also plan on using the new facility in enterprise.

reader_concurrency_semaphore: add set_resources()

---

replica/database.hh
replica/distributed_loader.cc
replica/distributed_loader.hh

We should scan all sstables in the table directory and its
subdirectories to determine the highest sstable version and generation
before using it for creating new sstables (via reshard or reshape).
Otherwise, the generations of new sstables created when populating staging (via reshard or reshape) may collide with generations in the base directory, leading to https://github.com/scylladb/scylladb/issues/11789
Refs scylladb/scylladb#11789
Fixes scylladb/scylladb#11793

distributed_loader: detect highest generation before populating column families

---

main.cc
repair/repair.cc
repair/repair.hh
repair/row_level.hh
service/storage_service.cc
service/storage_service.hh

The storage_service::stop() calls repair_service::abort_repair_node_ops() but at that time the sharded<repair_service> is already stopped and call .local() on it just crashes.
The suggested fix is to remove explicit storage_service -> repair_service kick. Instead, the repair_infos generated for the sake of node-ops are subscribed on the node_ops_meta_data's abort source and abort themselves automatically.
fixes: #10284

Subscribe repair_info::abort on node_ops_meta_data::abort_source

---

db/view/view.cc
db/view/view.hh
test/alternator/test_gsi.py

As described in issue #11801, we saw in Alternator when a GSI has both partition and sort keys which were non-key attributes in the base, cases where updating the GSI-sort-key attribute to the same value it already had caused the entire GSI row to be deleted.
In this series fix this bug (it was a bug in our materialized views implementation) and add a reproducing test (plus a few more tests for similar situations which worked before the patch, and continue to work after it).
Fixes #11801

Alternator, MV: fix bug in some view updates which set the view key to its existing value

---

dist/common/scripts/scylla_util.py

It seems like distribution original sysconfig files does not use double
quote to set the parameter when the value does not contain space.
Adding function to detect spaces in the value, don't usedouble quote
when it not detected.
Fixes #9149

scylla_util.py: on sysconfig_parser, don't use double quote when it's possible

---

docs/index.rst

This PR introduces the following changes to the documentation landing page:
- The " New to ScyllaDB? Start here!" box is added.
- The "Connect your application to Scylla" box is removed.
- Some wording has been improved.
- "Scylla" has been replaced with "ScyllaDB".

doc: improve the documentation landing page 

---

api/storage_service.cc
replica/database.hh
replica/table.cc

Flush the memtable before cleaning up the table so not to leave any disowned tokens in the memtable
as they might be resurrected if left in the memtable.
Fixes #1239

cleanup compaction: flush memtable

---

direct_failure_detector/failure_detector.hh
gms/gossiper.cc
gms/gossiper.hh
main.cc
service/raft/raft_group0.cc
service/raft/raft_group_registry.cc
service/raft/raft_group_registry.hh
service/raft/raft_rpc.cc
service/raft/raft_rpc.hh
test/lib/cql_test_env.cc
test/raft/failure_detector_test.cc
test/raft/randomized_nemesis_test.cc

Whenever a Raft configuration change is performed, `raft::server` calls
`raft_rpc::add_server`/`raft_rpc::remove_server`. Our `raft_rpc`
implementation has a function, `_on_server_update`, passed in the
constructor, which it called in `add_server`/`remove_server`;
that function would update the set of endpoints detected by the
direct failure detector. `_on_server_update` was passed an IP address
and that address was added to / removed from the failure detector set
(there's another translation layer between the IP addresses and internal
failure detector 'endpoint ID's; but we can ignore it for the purposes
of this commit).
Therefore: the failure detector was pinging a certain set of IP
addresses. These IP addresses were updated during Raft configuration
changes.
To implement the …

service/raft: failure detector: ping `raft::server_id`s, not `gms::inet_address`es

---

db/system_keyspace.cc
service/storage_service.cc

Currently, when replacing a node ip, keeping the old host,
we might end up with the the old endpoint in system.peers
if it is inserted back into the topology by `handle_state_normal`
when on_join is called with the old endpoint.
Then, later on, on_change sees that:
```
if (get_token_metadata().is_member(endpoint)) {
co_await do_update_system_peers_table(endpoint, state, value);
```
As described in #11925.
Fixes #11925

handle_state_normal: do not update topology of removed endpoint

---

docs/cql/compaction.rst
docs/operating-scylla/security/auditing.rst
docs/operating-scylla/security/ldap-authentication.rst
docs/operating-scylla/security/ldap-authorization.rst
docs/rst_include/enterprise-only-note.rst
docs/using-scylla/in-memory.rst
docs/using-scylla/workload-prioritization.rst

This PR is a follow-up to https://github.com/scylladb/scylladb/pull/11918.
With this PR:
- The "ScyllaDB Enterprise" label is added to all the features that are only available in ScyllaDB Enterprise.
- The previous Enterprise-only note is removed (it was included in multiple files as _/rst_include/enterprise-only-note.rst_ - this file is removed as it is no longer used anywhere in the docs).
- "Scylla Enterprise" was removed from `versionadded `because now it's clear that the feature was added for Enterprise.

doc: add the "Scylladb Enterprise" label to the Enterprise-only fearues

---

memtable-sstable.hh
multishard_mutation_query.cc
mutation_compactor.hh
schema_upgrader.hh
test/cql-pytest/test_scan.py
test/raft/future_set.hh
test/raft/logical_timer.hh
thrift/utils.hh
utils/entangled.hh
utils/immutable-collection.hh

When stopping the read, the multishard reader will dismantle the
compaction state, pushing back (unpopping) the currently processed
partition's header to its originating reader. This ensures that if the
reader stops in the middle of a partition, on the next page the
partition-header is re-emitted as the compactor (and everything
downstream from it) expects.
It can happen however that there is nothing more for the current
partition in the reader and the next fragment is another partition.
Since we only push back the partition header (without a partition-end)
this can result in two partitions being emitted without being separated
by a partition end.
We could just add the missing partition-end when needed but it is
pointless, if the partition has no more data, just drop the header, we
won't …

[branch-4.6] multishard_mutation_query: don't unpop partition header of spent partition 

---

multishard_mutation_query.cc
mutation_compactor.hh
test/cql-pytest/test_scan.py

When stopping the read, the multishard reader will dismantle the 
compaction state, pushing back (unpopping) the currently processed
partition's header to its originating reader. This ensures that if the
reader stops in the middle of a partition, on the next page the
partition-header is re-emitted as the compactor (and everything
downstream from it) expects.
It can happen however that there is nothing more for the current
partition in the reader and the next fragment is another partition.
Since we only push back the partition header (without a partition-end)
this can result in two partitions being emitted without being separated
by a partition end.
We could just add the missing partition-end when needed but it is
pointless, if the partition has no more data, just drop the header, we
won't …

[branch-5.0] multishard_mutation_query: don't unpop partition header of spent partition

---

serializer_impl.hh
test/boost/serialization_test.cc

As indicated in #11816, we'd like to enable deserializing vectors in reverse. 
The forward deserialization is achieved by reading from an input_stream. The
input stream internally is a singly linked list with complicated logic. In order to 
allow for going through it in reverse, instead when creating the reverse vector
initializer, we scan the stream and store substreams to all the places that are a
starting point for a next element. The iterator itself just deserializes elements 
from the remembered substreams, this time in reverse.
Fixes
#11816
CC @bhalevy

Introduce reverse vector_deserializer.

---

idl/raft.idl.hh
raft/raft.hh
raft/server.cc

When `modify_config` or `add_entry` is forwarded to the leader, it may reach the node at "inappropriate" time and result in an exception. There are two reasons for it - the leader is changing and, in case of `modify_config`, other `modify_config` is currently in progress. In both cases the command is retried, but before this patch there was no delay before retrying, which could led to a tight loop.
The patch adds a new exception type `transient_error`. When the client receives it, it is obliged to retry the request after some delay. Previously leader-side exceptions were converted to `not_a_leader`, which is strange, especially for `conf_change_in_progress`.
Fixes: #11564

raft: wait for the next tick before retrying
